### ISSUE TITLE
Move typeshed to some more official place like github.com/python

### ISSUE THREAD

**Issue by vlasovskikh** [python/typeshed#10]

**Comment by gvanrossum** [comment]
Also, put something a little more inviting in the README, e.g. see https://github.com/ambv/typehinting/pull/141

**Comment by matthiaskramm** [comment]
Added a note about contributions to the README.

Who do I talk to about creating http://github.com/python/typeshed/ and giving Jukka and me access?

**Comment by gvanrossum** [comment]
I think the process is that Jukka (must be the rep owner) transfers ownership to the python project. I've done this once. I think the UI is straightforward, but I don't recall if there is the requirement that the owner who is giving the repo away must be a member of the receiving project. We'd need to get one of the owners of https://github.com/python to do that and accept the transfer, IIRC. DStuffT can probably help you.

**Comment by matthiaskramm** [comment]
Done: http://github.com/python/typeshed

**Comment by gvanrossum** [comment]
Thanks! I've updated PEP 484 with the new location.
