### ISSUE TITLE
OpenSSL.SSL.SSLeay_version returns bytes, not str

### ISSUE THREAD

**Issue by wRAR** [python/typeshed#10024]
The stub has `def SSLeay_version(type: int) -> str`, while in practice:

```
In [3]: OpenSSL.SSL.SSLeay_version(OpenSSL.SSL.SSLEAY_VERSION)
Out[3]: b'OpenSSL 3.0.7 1 Nov 2022'
```

The function itself, at least in this version, is just `_ffi.string(_lib.OpenSSL_version(type))`, and as OpenSSL_version(3) returns a `char*` it looks correct to get `bytes` in Python.

**Comment by srittau** [comment]
Thanks! #10037 should fix this.
