### ISSUE TITLE
beautifulsoup4: Could `Tag.find_all` return `ResultSet[PageElement]` instead of `ResultSet[Any]`?

### ISSUE THREAD

**Issue by willfrey** [python/typeshed#10029]
Could this be changed to return `ResultSet[PageElement]`?

https://github.com/python/typeshed/blob/a035372a916e057f309409cd008e2dbe93e29ddc/stubs/beautifulsoup4/bs4/element.pyi#L328-L336

This would agree with the wording of `find_all`'s docstring. If this is a safe change, I'm happy to submit a PR.

Thanks!

**Comment by Akuli** [comment]
This has been discussed before. See #7254.

**Comment by willfrey** [comment]
@Akuli I see. I. had a feeling that there was a reason as to why this was still `Any`, but I thought I'd ask. I'll close this.

Thanks!
