### ISSUE TITLE
functools.cached_property should be covariant over it's return type

### ISSUE THREAD

**Issue by tjf801** [python/typeshed#10048]
Currently,  `cached_property[_T]` is invariant over `_T`, causing the code below to not type check.
```py
from functools import cached_property

class Base:
    @cached_property # can also be replaced with `property` and gets the same result
    def foo(self) -> float:
        ...

class Derived(Base):
    @cached_property
    def foo(self) -> int: # TypeVar "_T@cached_property" is invariant, "int" is incompatible with "float"
        ...
```
The only reason I see for this is that the `__set__` method takes a `_T` as a parameter, but this doesn't actually exist at runtime. If this is truly necessary, it might be nice to have an immutable version of this class that does not allow the value to be set at runtime. Also, I feel like it is relevant to mention the fact that `cached_property` is normally able to be used instead of `property` (which does act covariantly when no `setter` is defined).

**Comment by sobolevn** [comment]
`int` and `float` are bad examples, because they are not really subclasses. Type-checkers special-case it (the history is complex):

```python
>>> int.__mro__
(<class 'int'>, <class 'object'>)
>>> float.__mro__
(<class 'float'>, <class 'object'>)
```

So, here's another example: https://mypy-play.net/?mypy=latest&python=3.11&gist=8d1bb7242f12f58a3e5d3cacdd546ad6

```python
from functools import cached_property

class A: ...
class B(A): ...

class X:
    @cached_property
    def some(self) -> A: ...
    
class Y(X):
    @cached_property
    def some(self) -> B: ...
```

And it does not reproduce this problem.

**Comment by hmc-cs-mdrissi** [comment]
I can reproduce it with your example on pyright. It produces an error message of,

```
"some" overrides symbol of same name in class "X"
  "cached_property[B]" is incompatible with "cached_property[A]"
    TypeVar "_T@cached_property" is invariant
      "B" is incompatible with "A"
```

Strangely pyright playground does not reproduce it indicating this might be related to a recent typeshed/pyright change. My guess is mypy special cases for property also handle it for cached property while pyright mainly relies on cached_property stubs. I see some special casing in [mypy](https://github.com/python/mypy/blob/4276308be01ea498d946a79554b4a10b1cf13ccb/mypy/semanal.py#L1504) related to cached_property.

**Comment by sobolevn** [comment]
Feedback is welcome https://github.com/python/typeshed/pull/10053

**Comment by JelleZijlstra** [comment]
Making it covariant seems unsound since cached_property can be set.
