### ISSUE TITLE
`_SubParsersAction.add_parser` doesn't work well with ArgumentParser subclasses using different `__init__` signatures.

### ISSUE THREAD

**Issue by yilei** [python/typeshed#10082]
Example code:

```python
import argparse

class MyParser(argparse.ArgumentParser):

    def __init__(self, custom_arg: str, **kwargs):
        self.custom_arg = custom_arg
        super().__init__(**kwargs)



parser = MyParser('my program', custom_arg='root')

sub_parsers = parser.add_subparsers()
sub_parser = sub_parsers.add_parser('a sub parser', custom_arg='sub_parser')
print(f'{sub_parser.custom_arg=}')
```

The `add_parser` passes `**kwargs` to the `_parser_class`, which is `MyParser` in this case: https://github.com/python/cpython/blob/b934f97850b7b2db30fa2b26720d58aac4783149/Lib/argparse.py#L1205 so this code works:

```
$ python example.py
sub_parser.custom_arg='sub_parser'
```

But it fails type checking because of this: https://github.com/python/typeshed/blob/1d9f35369d724954e7fc34970692f5509dd10ac7/stdlib/argparse.pyi#L472

```
$ mypy --version
mypy 1.2.0 (compiled: yes)
$ mypy example.py
example.py:14: error: Unexpected keyword argument "custom_arg" for "add_parser" of "_SubParsersAction"  [call-arg]
Found 1 error in 1 file (checked 1 source file)
```

The real world example is https://github.com/abseil/abseil-py/blob/main/absl/flags/argparse_flags.py, the custom subclass has an extra `inherited_absl_flags=` argument: https://github.com/abseil/abseil-py/blob/c5c609cf04ea3f46eb620eb1b948ee2294645c4a/absl/flags/argparse_flags.py#L132 The `argparse_flags` module provides integration between [`absl.flags` flags](https://abseil.io/docs/python/guides/flags) and `argparse`.

I'm not sure this could be solved though, but I'd like to file this issue to hear your thoughts/opinions.

**Comment by srittau** [comment]
This is difficult to solve using the current typing capabilities. (Unless I'm missing a clever solution involving ParamSpec.) Maybe the best we can do is to add a generic `**kwargs` argument to `add_parser` with a comment explaining the situation.
