### ISSUE TITLE
PIL `Image.load` return value is wrong

### ISSUE THREAD

**Issue by mementum** [python/typeshed#10084]
The stub for `Image.load` says the method returns nothing.

https://github.com/python/typeshed/blob/acfde4e40b3a75aeff1d6324a4eb9adbca5579e2/stubs/Pillow/PIL/Image.pyi#L183

But the actual `load` method returns something. See link

https://github.com/python-pillow/Pillow/blob/f32e6a6ae6ed57f772b5840221e320d5473b094d/src/PIL/Image.py#L3832

`pixel_access` is defined in the `C` part of the library giving the type the name `PixelAccess` (as also referenced in the documentation)

https://github.com/python-pillow/Pillow/blob/b4419169a42b201903fef72712b1fcd43c2ebcef/src/_imaging.c#L3832

**Comment by Akuli** [comment]
Duplicate of #9126.
