### ISSUE TITLE
typing.Literal.__args__ is missing?

### ISSUE THREAD

**Issue by st-pasha** [python/typeshed#10085]
The following code
```python
ImageTypes = Literal["jpg", "gif", "png"]
image_types = ImageTypes.__args__
```
produces a number of errors in Pylance v2023.4.30:
```
Type of "__args__" is unknown Pylance[reportUnknownMemberType]
Cannot access member "__args__" for type "Type[Literal['jpg']]"
  Member "__args__" is unknown Pylance[reportGeneralTypeIssues]
Cannot access member "__args__" for type "Type[Literal['gif']]"
  Member "__args__" is unknown Pylance[reportGeneralTypeIssues]
Cannot access member "__args__" for type "Type[Literal['png']]"
  Member "__args__" is unknown Pylance[reportGeneralTypeIssues]
(function) __args__: Unknown
```

Ideally, it should be able to infer the type in this case as `Tuple[str, ...]`.

**Comment by AlexWaygood** [comment]
It's impossible to add a stub for this attribute. This is why [`typing.get_args`](https://docs.python.org/3/library/typing.html#typing.get_args) exists. Use that function to retrieve the value of `Literal.__args__`.

If you're using a version of Python that doesn't have `typing.get_args` yet, you can use the backport in [the third-party typing_extensions package](https://github.com/python/typing_extensions).
