### ISSUE TITLE
Remove invoke stubs (not until November 2023)

### ISSUE THREAD

**Issue by kasium** [python/typeshed#10103]
Invoke 2.1.0 now ships inline type annotations: https://www.pyinvoke.org/changelog.html
Earliest month of removal: end of October

**Comment by JelleZijlstra** [comment]
Not quite since they didn't ship a py.typed: #10100

**Comment by AlexWaygood** [comment]
The clock starts as soon as the `py.typed` file is included in a wheel that's published on PyPI. We're not quite there yet, due to a packaging bug in `invoke`: https://github.com/pyinvoke/invoke/pull/936

**Comment by kasium** [comment]
Thanks, haven't seen this

**Comment by AlexWaygood** [comment]
Thanks to @sobolevn, a version of invoke that includes a `py.typed` file in the wheel has now been uploaded to PyPI 🎉
