### ISSUE TITLE
`create_baseline_stubs.py` script does not add default values

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#10126]
As title says. Now that typeshed prefers having default values, it would make sense if the `create_baseline_stubs.py` script added them.
Maybe that would be stubgen's job?
For now I'm running https://github.com/JelleZijlstra/stubdefaulter manually as I am moving stubs out of https://github.com/microsoft/python-type-stubs, but I don't think that's even documented/mentioned in the contributing guidelines.

**Comment by AlexWaygood** [comment]
Yeah, really this should be added to stubgen, but in the meantime, I wouldn't be opposed to adding a stubdefaulter step to `create_baseline_stubs.py`

**Comment by JelleZijlstra** [comment]
https://pypi.org/project/stubdefaulter/0.1.0/

Oops, I missed the description. I guess that's for 0.2.0 :)

**Comment by Avasam** [comment]
Awesome.
On it!
