### ISSUE TITLE
Support numpy arrays for ReadableBuffer and WriteableBuffer

### ISSUE THREAD

**Issue by geertj** [python/typeshed#10129]
Numpy arrays support the buffer protocol. It would be nice if we could add them to the ReadableBuffer and WriteableBuffer types.

**Comment by JelleZijlstra** [comment]
This isn't feasible to do because these aliases are defined in a place where we cannot use third-party libraries.

However, we'll soon switch typeshed to use PEP 688 (https://peps.python.org/pep-0688/) for marking buffer types, which means that third-party buffer types will be supported directly.

**Comment by geertj** [comment]
Thanks @JelleZijlstra for the quick reply and the pointer.
