### ISSUE TITLE
`restval`/`restkey` from `csv.DictReader` can be `Any`

### ISSUE THREAD

**Issue by Viicos** [python/typeshed#10145]
This is how `restval` and `restkey` are currently defined:

https://github.com/python/typeshed/blob/348f46452f8a864c5e0f279398fad0a943f67ab1/stdlib/csv.pyi#L69-L80

But looking at the [code](https://github.com/python/cpython/blob/1c420e138fd828895b6bd3c44ef99156e8796095/Lib/csv.py#L127-L131) and [docs](https://docs.python.org/3/library/csv.html#csv.DictReader), they basically can take any value (or at least any hashable value for `restkey`). Is it required for these two parameters to be `str | None`?

**Comment by ljluestc** [comment]
import ast
import collections
import os

def find_constants(directory):
    constants = collections.defaultdict(list)

    for root, dirs, files in os.walk(directory):
        for file in files:
            if file.endswith(".py"):
                filepath = os.path.join(root, file)
                with open(filepath, "r") as f:
                    code = f.read()
                    tree = ast.parse(code)

                for node in ast.walk(tree):
                    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name) and isinstance(node.value, ast.Constant):
                        constant_name = node.targets[0].id
                        constant_value = node.value.value
                        constants[constant_name].append((constant_value, filepath))

    return constants

def main():
    directory = "/path/to/your/codebase"
    constants = find_constants(directory)

    for name, occurrences in constants.items():
        if len(occurrences) > 1:
            print(f"Constant '{name}' is defined in multiple modules:")
            for value, filepath in occurrences:
                print(f"  Value: {value}, Defined in: {filepath}")
            print("Consider re-exporting or reusing this constant.")
            print()

if __name__ == "__main__":
    main()

**Comment by srittau** [comment]
Considering that `DictReader` is already generic over the fieldnames, it would make sense to me to use `_T` for `restkey` as well. PR welcome!
