### ISSUE TITLE
Remove stubs for pyvmomi (not until November 2023)

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#10149]
https://github.com/python/typeshed/pull/10148

**Comment by intgr** [comment]
Just for information, I tried the upstream type hints and they are not usable yet. With the initial pyvmomi release shipping type stubs (8.0.1.0), there are syntax errors a few of the files, preventing their use completely with mypy (https://github.com/vmware/pyvmomi/issues/1015), and beyond that it looks like there will be other issues as well.

I'm sure the upstream stubs will improve over time, just need to wait some more. November deadline seems reasonable.

The upside is that upstream type stubs look like they're autogenerated and very extensive, they cover all of the API surface, not just a few object types like `types-pyvmomi`.

**Comment by AlexWaygood** [comment]
Ah, thanks for letting us know. If the upstream type hints are completely unusable, maybe it would be better to revert #10148 for now. (With the stubs marked as obsolete, the description on PyPI tells users not to use `types-pyvmomi` anymore, which is obviously incorrect advice right now.) This is a pretty unusual situation, though.

**Comment by AlexWaygood** [comment]
Okay, for now we've reverted marking the stubs as obsolete. We can mark `types-pyvmomi` as obsolete again once the upstream types are usable.

**Comment by intgr** [comment]
With the latest pyvmomi version 8.0.1.0.1 (May 25), the upstream type stubs work well with mypy for my use cases.

PyCharm still struggles with upstream types, but I have not investigated that in detail.

**Comment by AlexWaygood** [comment]
"Upstream types don't work perfectly with all type checkers" feels like it falls into the category of "the stubs are somewhat buggy" rather than "the stubs are fundamentally broken". So I'd vote for marking `types-pyvmomi` as obsolete once more, in that case. Thanks for the update @intgr!

**Comment by AlexWaygood** [comment]
Now marked as obsolete since 8.0.1.0.1: https://github.com/python/typeshed/commit/2ec6ba979f98c3c49d3a7ac2b11f1b3459e8e95a
