### ISSUE TITLE
IO.seek and IO.write have incorrect return type in python 2

### ISSUE THREAD

**Issue by euresti** [python/typeshed#1016]
Just making sure this isn't by design before I make a pull request:

`seek` probably should return an `int`
  https://github.com/euresti/typeshed/blob/master/stdlib/2/typing.pyi#L245
  https://github.com/euresti/typeshed/blob/master/stdlib/3/typing.pyi#L341

`write` probably should return an `int`
    https://github.com/euresti/typeshed/blob/master/stdlib/2/typing.pyi#L256
    https://github.com/euresti/typeshed/blob/master/stdlib/3/typing.pyi#L353

Also would it be useful to combine this module into 2and3?

**Comment by ambv** [comment]
We probably need an entry in CONTRIBUTING about 2and3, I'll write something down.

**Comment by ambv** [comment]
Actually, we already have a rather concise rule of thumb there:
"If the given library works on both Python 2 and Python 3, prefer to put your stubs in an `2and3` directory, unless the types are so different that the stubs become unreadable that way."

`typing.py` might be one of those cases. If your investigation proves otherwise, merging them would be worthwhile.

**Comment by euresti** [comment]
Hmm. Something is weird. If I add an `import sys` at the top of `stdlib/2/typing.pyi` I get:

```
stdlib/2/types.pyi:16: error: Cannot determine type of 'long'
```

Also if I try to use bytes in `stdlib/2/typing.pyi` (My aproach was to make `2/typing.pyi` and `3/typing.pyi` identical before renaming them to 2and3/typing.pyi I get an error 

```
stdlib/2/typing.pyi:402: error: Invalid type "builtins.bytes"
```

Must be an import ordering issue.

**Comment by JelleZijlstra** [comment]
I believe there's an import cycle among typing, types, builtins, and a few other modules that's necessary to bootstrap the type system. Adding more imports to typing may easily break things. Specifically, your error makes it sound like types.pyi gets evaluated before builtins.pyi (which defines `long`).

I don't know if merging the Python 2 and 3 versions of typing in typeshed is worthwhile; the actual implementation uses different files for Python 2 and 3 too.
