### ISSUE TITLE
asyncio.create_task doesn't accept async_generator_asend objects

### ISSUE THREAD

**Issue by kumaraditya303** [python/typeshed#10185]
The following code fails to typecheck with mypy but works just fine at runtime.
```py
import asyncio
from typing import AsyncGenerator


async def func() -> AsyncGenerator[int, None]:
    yield 1


async def main() -> None:
    a = func()
    print(await asyncio.create_task(a.asend(None)))

asyncio.run(main())
```
Error:

```console
❯ mypy main.py
main.py:11: error: Argument 1 to "create_task" has incompatible type "Awaitable[int]"; expected "Union[Generator[Any, None, <nothing>], Coroutine[Any, Any, <nothing>]]"  [arg-type]
main.py:11: error: Argument 1 to "create_task" has incompatible type "Awaitable[int]"; expected "Union[Generator[Any, None, object], Coroutine[Any, Any, object]]"  [arg-type]
Found 2 errors in 1 file (checked 1 source file)
```

mypy version: mypy 1.0.0 (compiled: yes)

**Comment by kumaraditya303** [comment]
cc @AlexWaygood

**Comment by srittau** [comment]
@kumaraditya303 Could you give the error message, and the line the error appears in? Also, which mypy version are you using?

**Comment by kumaraditya303** [comment]
@srittau Updated comment to include details.

**Comment by AlexWaygood** [comment]
I'm curious if @graingert has any thoughts on this, as he was involved in the discussion around reverting #7491!

**Comment by graingert** [comment]
AsyncGenerator defines an interface based on returning awaitable objects and not coroutines so it makes sense to me that people should annotate their async def generators used with create_task with AsyncGeneratorType

**Comment by kumaraditya303** [comment]
Well for me, changing it to return `collections.abc.Coroutine` makes the most sense as that's how it is implemented in `genobject.c`. 

cc @gvanrossum
