### ISSUE TITLE
Release types on Conda Forge

### ISSUE THREAD

**Issue by Ubadub** [python/typeshed#10189]
Most of the type stubs made available in the typeshed can be installed via both pip and conda. However, there are some exceptions. In particular, a project I am working on requires types-tqdm and types-pywin32, neither of which are presently available via conda.

Please upload these to conda forge. It would make dependency management for us easier.

**Comment by AlexWaygood** [comment]
As far as I know, nobody on the typeshed team is involved with uploading any of our stubs to conda-forge. I assume the stubs that are uploaded to conda-forge are being packaged by benevolent third parties.

We could possibly consider uploading all our packages to conda-forge, but it might involve complicating the logic in https://github.com/typeshed-internal/stub_uploader a fair bit

**Comment by srittau** [comment]
I'm -0 on uploading to conda-forge. We already support Python's official package repository. If the Conda project is interested to upload type stubs to conda-forge, they should be able to do so fairly easily.

**Comment by Ubadub** [comment]
If I fork and submit a PR to the [stub-uploader](https://github.com/typeshed-internal/stub_uploader) that works in automated conda-forge uploads, would you guys consider it, or should I not bother?

As I understand, the PIP stub uploading process uses git workflows, which presumably I couldn't hook into directly on my own, but I could write the code to get us almost there and then maybe someone with the requisite permissions can make sure it works? I'm not sure what the contribution process works like, assuming you guys are open to his of course.

**Comment by AlexWaygood** [comment]
I would personally be _open_ to it, _as long as_ it didn't _significantly_ increase the complexity of the stub-uploader logic. But I'm not a stub-uploader maintainer, so I'll defer to the other members of the typeshed team who are when it comes to this.

**Comment by sobolevn** [comment]
I think that this can be done via regular feedstock.

So, we can just create two new repos in `conda-forge` and it will sync the releases automatically. Example: https://github.com/conda-forge/pytest-mypy-plugins-feedstock/pull/6

**Comment by Ubadub** [comment]
@sobolevn Yeah, I realized this a couple days ago and [opened a PR](https://github.com/conda-forge/staged-recipes/pull/22939).

If any of you would like to be listed as a maintainer, please let me know, and I will update the PR accordingly.

**Comment by sobolevn** [comment]
You can list me, I am both conda and typeshed member.

**Comment by AlexWaygood** [comment]
Looks like these were added in https://github.com/conda-forge/staged-recipes/pull/22939! Closing for now; happy to reopen if there's still some unresolved things here
