### ISSUE TITLE
sqlalchemy Engine and Connection should be subclasses of Connectable

### ISSUE THREAD

**Issue by Stiivi** [python/typeshed#1018]
The following code:

```python
import sqlalchemy

connectable: sqlalchemy.engine.base.Connectable
engine: sqlalchemy.engine.base.Engine

connectable = engine
```

Gives error: `Incompatible types in assignment (expression has type "Engine", variable has type "Connectable")`

According to [the documentation](http://docs.sqlalchemy.org/en/latest/core/connections.html#sqlalchemy.engine.Connectable):

> The two implementations of Connectable are Connection and Engine

Tested on Python 3.6.

**Comment by JelleZijlstra** [comment]
We removed the SQLAlchemy stubs, so this is no longer applicable to typeshed. I think it's already fixed in my fork.
