### ISSUE TITLE
Class tuple has not @final decorator

### ISSUE THREAD

**Issue by Watermelo-man** [python/typeshed#10190]
The current annotation of the tuple class allows you to override the count method (maybe something else, didn't check)
Example:
```
from typing import Any

tuple_test_1 = tuple()
tuple_test_1 = ('one','two',5,5,6)
print(tuple_test_1.count(5))
print(tuple_test_1.index(6))

class tuple(tuple):
    def count(self, __value: Any) -> int:
        print('lol')
        return 0

tuple_test_2 = tuple()
tuple_test_2 = ('one','two',5,5,6)
tuple_test_2.count(5)
print(tuple_test_2.index(6))
```
Maybe the @final for the class tuple is forgotten?

**Comment by AlexWaygood** [comment]
Tuple shouldn't be decorated with `@final` in the stubs, because it can be subclassed at runtime, and frequently is subclassed at runtime. Every time you use `collections.namedtuple` or `typing.NamedTuple`, you're creating a subclass of `tuple`.
