### ISSUE TITLE
Process has no attribute info - process_iter from psutil

### ISSUE THREAD

**Issue by emcek** [python/typeshed#10195]
`Proccess` object do not have `info` attribute, but code form `ps.py` is working fine.

**ps.py**
```python
from psutil import process_iter

def proc_is_running(name: str) -> int:
    for proc in process_iter(['pid', 'name']):
        if name in proc.info['name']:
            return proc.info['pid']
    return 0
```
**pip list**
```shell
mypy                      1.3.0
mypy-extensions           1.0.0
types-psutil              5.9.5.12
```
**mypy ps.py**
```shell
ps.py:6: error: "Process" has no attribute "info"  [attr-defined]
ps.py:7: error: "Process" has no attribute "info"  [attr-defined]
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
`info` seems to be added to `Process` dynamically by `process_iter()` if the `attrs` argument was provided:

https://github.com/giampaolo/psutil/blob/49aba759744c06fb3a6fa998155428520f161734/psutil/__init__.py#L1423-L1428

I think the best we can do is to add `Process.info` with a comment that it only exists when constructed through `process_iter()`.

**Comment by emcek** [comment]
Yes, this is dynamic behavior.

**Comment by sobolevn** [comment]
I've sent https://github.com/giampaolo/psutil/pull/2260 to fix it upstream, later we can add `info` as a regular attribute.
