### ISSUE TITLE
Return types of some `AbstractSet` methods could be more specific

### ISSUE THREAD

**Issue by connorbrinton** [python/typeshed#10193]
Currently [the type annotations for `AbstractSet` in typeshed](https://github.com/python/typeshed/blob/b5c9d8d6770e09dff00648b79281702e111d4e01/stdlib/typing.pyi#LL505C1-L518C60) are defined as follows:
```python
class AbstractSet(Collection[_T_co], Generic[_T_co]):
    @abstractmethod
    def __contains__(self, x: object) -> bool: ...
    def _hash(self) -> int: ...
    # Mixin methods
    def __le__(self, other: AbstractSet[Any]) -> bool: ...
    def __lt__(self, other: AbstractSet[Any]) -> bool: ...
    def __gt__(self, other: AbstractSet[Any]) -> bool: ...
    def __ge__(self, other: AbstractSet[Any]) -> bool: ...
    def __and__(self, other: AbstractSet[Any]) -> AbstractSet[_T_co]: ...
    def __or__(self, other: AbstractSet[_T]) -> AbstractSet[_T_co | _T]: ...
    def __sub__(self, other: AbstractSet[Any]) -> AbstractSet[_T_co]: ...
    def __xor__(self, other: AbstractSet[_T]) -> AbstractSet[_T_co | _T]: ...
    def isdisjoint(self, other: Iterable[Any]) -> bool: ...
```

Notably, methods such as `__and__`, `__or__`, `__sub__` and `__xor__` return instances of type `AbstractSet[...]`.

However, the CPython implementation [actually creates instances using `self.__class__`](https://github.com/python/cpython/blob/a412fc58ccb8c6739b179137321cbbb1abebcd2f/Lib/_collections_abc.py#L609-L621) (technically it calls a class method and uses the `cls` argument). As a result, the types actually returned by the CPython implementation are more specific instances of the self type.

This distinction becomes important when subclassing `AbstractSet` (or `Set`, as it's known in `collections.abc`). Here's example of doing this and inspecting the resulting types, both at runtime and during type checking:

<details>
<summary>Example</summary>

```python
from collections.abc import Iterable, Iterator, Set
from typing import TYPE_CHECKING

class MagicSet(Set[int]):
    numbers: frozenset[int]

    def __init__(self, numbers: Iterable[int]) -> None:
        self.numbers = frozenset(numbers)

    def __contains__(self, x: object) -> bool:
        return x in self.numbers

    def __iter__(self) -> Iterator[int]:
        return iter(self.numbers)

    def __len__(self) -> int:
        return len(self.numbers)


odds = MagicSet([1, 3, 5, 7, 9])
primes = MagicSet([3, 5, 7])

if TYPE_CHECKING:
    reveal_type(odds & primes)
else:
    print(type(odds & primes))
    
if TYPE_CHECKING:
    reveal_type(odds | primes)
else:
    print(type(odds | primes))
    
if TYPE_CHECKING:
    reveal_type(odds - primes)
else:
    print(type(odds - primes))
    
if TYPE_CHECKING:
    reveal_type(odds ^ primes)
else:
    print(type(odds ^ primes))
```

Running this script using Python results in:
```
<class '__main__.MagicSet'>
<class '__main__.MagicSet'>
<class '__main__.MagicSet'>
<class '__main__.MagicSet'>
```

Type-checking this script using Mypy results in:
```
test.py:26: note: Revealed type is "typing.AbstractSet[builtins.int]"
test.py:31: note: Revealed type is "typing.AbstractSet[builtins.int]"
test.py:36: note: Revealed type is "typing.AbstractSet[builtins.int]"
test.py:41: note: Revealed type is "typing.AbstractSet[builtins.int]"
Success: no issues found in 1 source file
```
</details>

It would be great if collection-returning methods of `AbstractSet` (and methods on other collections that might return self types?) could be annotated to indicate that they return instances of the derived type, rather than a generic `AbstractSet` 🙂

I wasn't sure what the best way to implement this would be, since the `Self` type in the official typing module isn't present until Python 3.11. I see that [there's a `Self` type variable in the `_typeshed` package](https://github.com/python/typeshed/blob/b5c9d8d6770e09dff00648b79281702e111d4e01/stdlib/_typeshed/__init__.pyi#L28)--would that be the right annotation to use?

**Comment by JelleZijlstra** [comment]
`Self` isn't a problem; we can use `typing_extensions.Self` on any version.

But the generic is a problem for some of these like `__or__`: we would want to return something like "`Self[_T_co | _T]`", but that's not possible without higher-kinded types. We could still change `__and__`, but that would introduce an inconsistency.

**Comment by AlexWaygood** [comment]
Another question, though, is about the role of `AbstractSet` in the type system, as an abstract interface. We don't return `Self` from `typing.Iterator.__iter__` or `contextlib.AbstractContextManager.__enter__`, even though the default implementations returns `self` at runtime, because not all iterators need to return `self` from their `__iter__` methods in order for them to be considered iterators by the language, and not all context managers need to return `self` from their `__enter__` methods in order to be considered context managers by the language.

Similarly, do _all_ set classes in Python _have_ to return `self` from these methods in order for them to be considered compatible with the interface? (I'm not sure.)

**Comment by AlexWaygood** [comment]
Going to close this for the reasons I mentioned in https://github.com/python/typeshed/issues/10193#issuecomment-1554697469 -- I don't think it would be a good idea to have more precise annotations for these methods, since `AbstractSet` is an abstract base class.
