### ISSUE TITLE
`os.EX_OK` exists on Win32

### ISSUE THREAD

**Issue by michaelmhoffman** [python/typeshed#10242]
Running `python.exe -m mypy .` on a directory where there's a script with `from os import EX_OK` leads to an error on Windows:

```
pdfcomments\__main__.py:20: error: Module "os" has no attribute "EX_OK"; maybe "X_OK"?  [attr-defined]
```

`stdlib/os/__init__.pyi` contains a type hint for `EX_OK` that is guarded by an `if sys.platform != "win32"` block. However, since  python/cpython@19459f8, `EX_OK` has been supported on Windows. It should be placed outside the guard block.

**Comment by AlexWaygood** [comment]
Thanks, your analysis looks accurate— PR welcome!

**Comment by aminalaee** [comment]
With credits to @michaelmhoffman , created a PR for this.
