### ISSUE TITLE
pywin32: PyNETRESOURCE attributes incorrectly typed as read-only

### ISSUE THREAD

**Issue by skykasko** [python/typeshed#10272]
Writable attributes of `PyNETRESOURCE` objects are incorrectly typed as read-only. For example, consider the following script:

```py
import win32wnet

net_resource = win32wnet.NETRESOURCE()
net_resource.lpRemoteName = r"\\10.0.0.1\share"
win32wnet.WNetAddConnection2(net_resource, Password="pwd", UserName="username")
```

The code works when executed (if actual values are subsituted for the remote name, username, and password), but mypy raises the error `Property "lpRemoteName" defined in "PyNETRESOURCE" is read-only  [misc]`.

pywin32's documentation mentions that `lpLocalName`, `lpRemoteName`, `lpComment`, and `lpProvider` are writable attributes (see [`netresource.htm`](https://github.com/mhammond/pywin32/blob/f6300f84dad8a165f45a65d7823a554fa3cc4a5a/win32/Demos/win32wnet/netresource.htm#L53-L60)), and their own tests include examples similar to the one above (see [`test_win32wnet.py`](https://github.com/mhammond/pywin32/blob/f6300f84dad8a165f45a65d7823a554fa3cc4a5a/win32/test/test_win32wnet.py#L124-L127) and [`testwnet.py`](https://github.com/mhammond/pywin32/blob/f6300f84dad8a165f45a65d7823a554fa3cc4a5a/win32/Demos/win32wnet/testwnet.py#L101-L105)).

Versions I am running:

* pywin32: 306
* types-pywin32: 306.0.0.2
* mypy: 1.3.0
* Python: 3.11.4

**Comment by srittau** [comment]
Makes sense, PR welcome!
