### ISSUE TITLE
`tempfile.SpooledTemporaryFile` missing `_file` attribute

### ISSUE THREAD

**Issue by Dr-Irv** [python/typeshed#10286]
According to the python docs, `SpooledTemporaryFile._file` is an attribute: "The returned object is a file-like object whose _file attribute is either an [io.BytesIO](https://docs.python.org/3/library/io.html#io.BytesIO) or [io.TextIOWrapper](https://docs.python.org/3/library/io.html#io.TextIOWrapper) object (depending on whether binary or text mode was specified)"

So the `_file` attribute should be added to `tempfile.pyi` for the `SpooledTemporaryFile` class.

**Comment by sobolevn** [comment]
It is documented indeed (which is rare for protected objects). Please, feel free to send a PR with the fix.

**Comment by heysujal** [comment]
Hi, I want to work on this issue, but I am not able to understand where should I make changes in https://github.com/python/typeshed/blob/8e4595a1682b5daf44498f81b95fbc8d1a651657/stdlib/tempfile.pyi#L361

**Comment by Akuli** [comment]
The new `_file` attribute will be pretty similar to the existing `encoding` attribute, so you could make a copy of that to get started. In the stub, `encoding` is a method decorated with `@property`, which means that it is actually a read-only attribute and not really a method.


```
>>> import tempfile
>>> f = tempfile.SpooledTemporaryFile(mode='w+')
>>> f.encoding
'UTF-8'
>>> f._file
<_io.TextIOWrapper encoding='UTF-8'>
```

The difference is that `_file` should not be a `str`, but one of two things depending on the mode. You can use `@overload` to achieve that. Look at `write()` and `writelines()`, for example.

**Comment by heysujal** [comment]
@sobolevn @AlexWaygood Sorry for the delay. I have made a PR ,please review it.
