### ISSUE TITLE
os.open() can take Path objects in Python 3.6

### ISSUE THREAD

**Issue by toolness** [python/typeshed#1030]
I noticed that the following code fails when checked by mypy under Python 3.6:

```py
import os
from pathlib import Path

fd = os.open(Path('/dev/null'), os.O_RDONLY)
```

The following error is produced:

```
error: Type argument 1 of "open" has incompatible value "Path"
```

However, the code seems to work fine due to Python 3.6's support for [PEP 519](https://docs.python.org/3/whatsnew/3.6.html#pep-519-adding-a-file-system-path-protocol).

If this is a problem with the type stubs then I could try submitting a PR.  mypy rocks!

**Comment by JelleZijlstra** [comment]
Yes, this is a problem with the stubs. There's an open PR to fix a few other functions in a similar way at #991, but we need to change a lot more functions.

**Comment by JelleZijlstra** [comment]
`os.open` is now declared as taking `_PathType`, which includes `PathLike` in 3.6+.
