### ISSUE TITLE
Remove distribution types-pkg-resources

### ISSUE THREAD

**Issue by srittau** [python/typeshed#10340]
`types-pkg-resources` was uploaded by accident after our transition to separate third-party distributions. The stubs are actually part of `types-setuptools`. Unfortunately, there are quite a few daily downloads, so just removing the package would probably cause a bit of problems. As a first step, we should manually upload a version that says: "Don't use this, use types-setuptools instead." Another manual upload could then remove the stubs from the distribution, so that people using this package get notified that there is a problem. Finally, all versions could get yanked.

Cf. #7197

**Comment by srittau** [comment]
I think manually creating a package would be overkill.

@ilevkivskyi I think you have access to the typeshed_bot account on PyPI. Could you yank all releases and remove the package from PyPI?

**Comment by ilevkivskyi** [comment]
I  yanked all 4 releases with a reason "Use types-setuptools instead". Are you sure you want to delete the package? This will make the project name available to any other PyPI user.

**Comment by srittau** [comment]
Thanks! In that case deleting doesn't sound like the right option. I think that's all we can do.
