### ISSUE TITLE
PEP 249 Python Database API Specification v2.0

### ISSUE THREAD

**Issue by Stiivi** [python/typeshed#1037]
The DB API 2 type annotations are not provided in a shared module. They are mostly included as private types of modules implementing the API, such as [sqlite3](https://github.com/python/typeshed/blob/c8435f43158ddf8ec4335a2a2877fcddc0a76c1b/stdlib/2/sqlite3/dbapi2.pyi) or [mysql](https://github.com/python/typeshed/blob/f398628948105fcfb8befc1fd160632856c6fc02/third_party/2and3/pymysql/times.pyi)

This should be a module with types importable by any other module that implements the DB2 API or uses DB2 API functionality, such as SQLAlchemy `Connectable` or `RowProxy` (see #1029).

**Comment by JelleZijlstra** [comment]
Going to close this since it's been open for a long time with no progress. Also, with PEP 561 now around this doesn't need to be done through typeshed.

**Comment by srittau** [comment]
Actually, I'm just about to add some DB API types for SQLAlchemy to `_typeshed`. So I'm going to reopen this for a bit.
