### ISSUE TITLE
`ArgumentParser.parse_args` with `Namespace` subclass does not work anymore

### ISSUE THREAD

**Issue by lkct** [python/typeshed#10400]
Ref: https://github.com/microsoft/pylance-release/issues/4569#issuecomment-1618797898

This is introduced in #10307. (cc @qthequartermasterman as the author)

https://github.com/python/typeshed/blob/31dca1d660937e2e3fe4670934b8c331d6f4144c/stdlib/argparse.pyi#L173-L178

The first overload now shadows the following. E.g., `ArgumentParser().parse_args(namespace=MyNamespace())` should match the third but actually matches the first, which unexpectedly returns `Namespace` instead of `MyNamespace`.

**Comment by srittau** [comment]
See discussion in #10387.
