### ISSUE TITLE
contextvars are in both stubs and stdlib

### ISSUE THREAD

**Issue by s04lg934jkg** [python/typeshed#10418]
There are two different contextvars pyi, one in stdlib and other in stubs.
If there is no good reason to keep both, I suggest to remove the one from stubs.

**Comment by hauntsaninja** [comment]
Thanks for suggesting this. Python 3.6 has been dead a long time (and the contextvars package hasn't seen any releases), so I'd be supportive of deleting the stubs for the third party version
