### ISSUE TITLE
Create stubs for `docker-py`

### ISSUE THREAD

**Issue by Viicos** [python/typeshed#10412]
For reference:
- https://github.com/docker/docker-py/issues/2796
- https://github.com/docker/docker-py/pull/3085

I will try to keep track of the PRs that will implement this here

**Comment by AlexWaygood** [comment]
Hi @Viicos! I'm going to close this for now, as there isn't really anything actionable for typeshed's maintainers here. But we'll happily accept stubs for docker-py if you want to contribute them — PR welcome :)

**Comment by adamtheturtle** [comment]
`types-docker` was added in https://github.com/python/typeshed/pull/11749.
