### ISSUE TITLE
Type mismatch in `email.charset.Charset.body_encode`

### ISSUE THREAD

**Issue by cushionbadak** [python/typeshed#10429]
### Summary

**Modification Target**: `Charset.body_encode` in `stdlib/email/charset.pyi`
**Current type hint**: `(self, string: str) -> str`
**Proposed type hint**: `(self, string: Optional[str]) -> Optional[str]`

See the existing implementation here: [charset.pyi#L21](https://github.com/python/typeshed/blob/81b8211d0edeed0a39253e096aaab86e1699e25b/stdlib/email/charset.pyi#L21)

### Description

The method [`Charset.body_encode`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/email/charset.py#L369-L379) can return `None` if it's invoked with `None` as the `string` parameter.
```python
    def body_encode(self, string):
        if not string:
            return string
        ...
```

Although the type hint currently does not allow for `None` to be passed as an argument, there's a mismatch with how it's used in the [`Message.set_charset`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/email/message.py#L379) method from the standard library's `email/message.py`, which can pass `None` to `body_encode`. This is because the `Message` class's attribute [`self._payload` is initially set to `None`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/email/message.py#L135-L154). 
```python
            self._payload = charset.body_encode(self._payload)
```
```python
class Message:
    def __init__(self, policy=compat32):
        self._payload = None
        ...
```

The mismatch (passing `None` as an argument) was discovered in the CPython email unit test, [`TestMessageAPI.test_getset_charset`](https://github.com/python/cpython/blob/0481b805d6631063887fcbcc27684aa8a2576fae/Lib/test/test_email/test_email.py#L62-L86), found in `test/test_email/test_email.py`. The minimized example below demonstrates the type mismatch:
```python
    def test_getset_charset(self):
        msg = Message()
        charset = Charset('iso-8859-1')
        msg.set_charset(charset)
        ...
```

P.S. All CPython links refer to commit hash `0481b8...` from the current CPython 3.12 branch.

**Comment by srittau** [comment]
Thanks! I believe our best option is to use an overload for the None -> None case. Just changing the return type without an overload would be unergonomic (and unnecessary) for what is most likely the common case: Passing in a `str`. So something like:

```python
    @overload
    def body_encode(self, string: None) -> None: ...
    @overload
    def body_encode(self, string: str) -> str: ...
```

PR welcome!
