### ISSUE TITLE
wrong condition for EQFULL constant within stdlib/errno.pyi

### ISSUE THREAD

**Issue by s04lg934jkg** [python/typeshed#10438]
EQFULL is defined not only for MacOS in this code
https://github.com/python/typeshed/blob/f812d71ffa2662a0291f8e5e32a7e2ff082a8af1/stdlib/errno.pyi#L117

if sys.platform != "win32":
    ...
    if sys.platform != "darwin" or sys.version_info >= (3, 11):
        EQFULL: int  # undocumented

It looks like the intention was to defined EQFULL for MacOS starting from python 3.11, but in fact it is also defined for any system that is not Windows or Mac.

**Comment by srittau** [comment]
I can confirm that at least with Ubuntu and Python 3.11 the errno does not exist. Cc @AlexWaygood who submitted the original PR.

**Comment by AlexWaygood** [comment]
> Cc @AlexWaygood who submitted the original PR.

Prior to #8142 it was defined unconditionally on all platforms and all versions. I changed the availability on Windows and macOS in #8142, but left the availability on Linux as it was as I don't have a Linux box to test on.

**Comment by AlexWaygood** [comment]
The original PR in which it was added was #7553 by @JelleZijlstra

**Comment by Akuli** [comment]
Doesn't exist on linux for me either. Tried Python 3.8, 3.9, 3.10 and 3.11.

**Comment by srittau** [comment]
I'll send a PR to update errno on Linux later.

**Comment by AlexWaygood** [comment]
Fixed by #10440
