### ISSUE TITLE
_typeshed.Sentinel

### ISSUE THREAD

**Issue by srittau** [python/typeshed#10480]
While preparing #10479 I noticed that there is a problem with stubtest and sentinels. Currently, we either annotate a sentinel default value in a hacky way or we need to add the function to the stubtest allowlist, masking other potential problems. We could just add a non-type alias `Sentinel = object` to `_typeshed` and use that as the default value and teach stubtest about it. Alternatively,  we could add a `_typeshed.Sentinel` type alias (probably to `Never`) and teach stubtest not to check default values when the argument includes that type. I prefer the first option, because I think this reads better:

```python
def foo(x: int | None = Sentinel)
def foo(x: int | None | Sentinel = ...)
```

[PEP 661](https://peps.python.org/pep-0661/) would alleviate the need for this in the long term, but non-PEP-661 sentinels will still be around "forever".

**Comment by sobolevn** [comment]
One more use-case: `argparse.BooleanOptionalAction` with its `deprecated_default` sentinel: https://github.com/python/cpython/blob/832c37d42a395d4ea45994daffa5e41bd74ac1bb/Lib/argparse.py#L887-L898

**Comment by srittau** [comment]
Of course the first form would not work without changes to type checkers, since I don't think we can define `Sentinel` in a way that it's accepted as default value. But those changes would basically be similar to what PEP 661 proposes anyway. So maybe the more pragmatic way is to define `Sentinel: TypeAlias = Never` and use it as a type annotation. This should work without any changes to type checkers, but we can change stubtest to ignore the implementation's default value in that case.
