### ISSUE TITLE
Missing `url: str` in `stdlib.http.client.pyi`?

### ISSUE THREAD

**Issue by jamesbraza** [python/typeshed#10494]
I have this code:

```python
from urllib import request

response: http.client.HTTPResponse = request.urlopen(request.Request("some_url", method="POST"))
response.url  # Warning on url
```

From the [`urllib.request` docs here](https://docs.python.org/3/library/urllib.request.html#module-urllib.response):
> The typical response object is a [urllib.response.addinfourl](https://docs.python.org/3/library/urllib.request.html#urllib.response.addinfourl) instance:

And `urllib.response.addinfourl` has:

> geturl()
>     _Deprecated since version 3.9:_ Deprecated in favor of [url](https://docs.python.org/3/library/urllib.request.html#urllib.response.addinfourl.url).

However, the `HTTPResponse` stub currently doesn't have `url: str` in it.  I think it should be added, would you agree?

---

I am willing to open a PR to fix this.

**Comment by jamesbraza** [comment]
Alternately, should `http.client.HTTPResponse` inherit from (or mix in) `requests.response.addinfourl`?

**Comment by sobolevn** [comment]
Yes, all documented attributes should be added :)
