### ISSUE TITLE
Type errors when using AnyStr.join

### ISSUE THREAD

**Issue by tpoliaw** [python/typeshed#10495]
I have a delimiter and a list of things to be joined. The (simplified version of the) method I have defined is 
```python
def joiner(delim: AnyStr, objs: Iterable[AnyStr]) -> AnyStr:
    return delim.join(objs)
```
Mypy is fine with this but pyright reports it as an error
```
/tmp/type_demo.py
  /tmp/type_demo.py:7:27 - error: Argument of type "Iterable[AnyStr@joiner]" cannot be assigned to parameter "__iterable_of_bytes" of type "Iterable[ReadableBuffer]" in function "join"
    "Iterable[AnyStr@joiner]" is incompatible with "Iterable[ReadableBuffer]"
      TypeVar "_T_co@Iterable" is covariant
        Type "str* | bytes*" cannot be assigned to type "ReadableBuffer"
          "str*" is incompatible with protocol "ReadableBuffer"
            "__buffer__" is not present (reportGeneralTypeIssues)
  /tmp/type_demo.py:9:27 - error: Argument of type "Iterable[AnyStr@joiner]" cannot be assigned to parameter "__iterable" of type "Iterable[str]" in function "join"
    "Iterable[AnyStr@joiner]" is incompatible with "Iterable[str]"
      TypeVar "_T_co@Iterable" is covariant
        Type "str* | bytes*" cannot be assigned to type "str"
          "bytes*" is incompatible with "str" (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations
```

As far as I can make out this should be valid (replacing `AnyStr` with either `str` or `bytes` is fine).

I'm happy for this to be intended behaviour if there's an edge case I'm missing but if so is there a way to make it valid from my side or is this an invalid expression that should be changed anyway?

**Comment by AlexWaygood** [comment]
Your code looks fine to me, and I can't see anything wrong with our stubs for `str.join()` or `bytes.join()`. This looks like a pyright issue to me; I suggest you open an issue at https://github.com/microsoft/pyright/issues
