### ISSUE TITLE
Label for stubsabot

### ISSUE THREAD

**Issue by srittau** [python/typeshed#10503]
I suggest to add a new label for stubsabot. This would enable us to easily see all open stubsabot PRs and see which libraries need updating.

**Comment by AlexWaygood** [comment]
Makes sense to me! Note that you can also sort typeshed's packages by `package_status` at https://alexwaygood.github.io/typeshed-stats/stats-csv/ to get an overview of which packages are out of date (currently `stripe`, `pyasn1`, `jsonschema` and `tensorflow`). That data is also downloadable using the `typeshed-stats` CLI, or you can just scrape it from https://github.com/AlexWaygood/typeshed-stats/tree/main/examples (updated twice a day)
