### ISSUE TITLE
xml.sax.saxutils.XMLGenerator can take SupportsWrite[bytes]

### ISSUE THREAD

**Issue by wRAR** [python/typeshed#10550]
Currently `XMLGenerator.__init__` is typed as taking `SupportsWrite[str]` for the code path in `xml.sax.saxutils._gettextwriter()` that wraps the file-like object into `io.TextIOWrapper` which, I think, can take binary file-like objects.

Please let me know if I'm wrong.

**Comment by srittau** [comment]
In fact I think it *only* accepts `SupportsWrite[bytes]`, since `TextIOWrapper` only wraps byte streams, if I'm not mistaken. PR welcome!
