### ISSUE TITLE
docutils.frontend.get_default_settings missing from stubs

### ISSUE THREAD

**Issue by mbdevpl** [python/typeshed#10568]
`frontend.py` module in docutils has these lines (I'm skipping most of the code below, 
link to latest version of the file: <https://repo.or.cz/docutils.git/blob/HEAD:/docutils/docutils/frontend.py>)

```python3
"""
...
Interface function:
   `get_default_settings()`.  New in 0.19.
...
"""

def get_default_settings(*components):
    """Return default runtime settings for `components`.

    Return a `frontend.Values` instance with defaults for generic Docutils
    settings and settings from the `components` (`SettingsSpec` instances).

    This corresponds to steps 1 and 2 in the `runtime settings priority`__.

    __ https://docutils.sourceforge.io/docs/api/runtime-settings.html
       #settings-priority
    """
    with warnings.catch_warnings():
        warnings.filterwarnings('ignore', category=DeprecationWarning)
        return OptionParser(components).get_default_values()
```

This was done as part of migration from optparse to argparse in docutils: <https://repo.or.cz/docutils.git/commit/fd4a0125639e4caccc591e1377f3de4fff638e4e?f=docutils/docutils/frontend.py>

Then, I have the following script:

```python3
"""Script to parse RST markup."""

import docutils.frontend
import docutils.nodes
import docutils.parsers.rst
import docutils.utils


def parse_rst(text: str) -> docutils.nodes.document:
    """Parse text assuming it's an RST markup."""
    parser = docutils.parsers.rst.Parser()
    settings = docutils.frontend.get_default_settings(docutils.parsers.rst.Parser)
    document = docutils.utils.new_document('<rst-doc>', settings=settings)
    parser.parse(text, document)
    return document
```

and these relevant packages installed:
```bash
$ pip freeze | grep -E '(docutils|mypy)'
docutils==0.20.1
mypy==1.5.0
mypy-extensions==1.0.0
types-docutils==0.20.0.1
```

Then, I get this:
```
$ python3 -m mypy parse_rst.py
parse_rst.py:12: error: Module has no attribute "get_default_settings"  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

Clearly, the module has this function:

```bash
$ grep -n -F "get_default_settings" ~/Software/Spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/python-3.11.0-tabbwylcmzsapq3wvci3xdh7ztalg5vm/lib/python3.11/site-packages/docutils/frontend.py
30:   `get_default_settings()`.  New in 0.19.
945:def get_default_settings(*components):
```

However, it's missing from the stubs. I'd like to add it to the stubs, and will submit a PR shortly. However, it's puzzling that there have been 2 PRs already that maybe should've contained the change?

* python/typeshed#8260
* python/typeshed#10167

I'll try to keep the PR minimal and include only the changes needed to fix the above issue, but there may be other changes made to the library in other places that also may need addressing.

**Comment by Daverball** [comment]
It's because the stubs are incomplete and stubtest is set to `ignore_missing_stub = True` in the `METADATA.toml`. So stubsbot will not complain if newly added symbols are missing from the stubs.

The only way to remedy this going forward would be to complete the stubs enough to be able to remove the flag from stubtest. Otherwise this will keep happening and will rely on people like yourself to notice the missing symbols.

Maybe you can get away with extending the `stubtest_allowlist.txt` in the `@tests` folder instead, I haven't taken a close look so I don't know why stubtest is set to `ignore_missing_stub`.

**Comment by mbdevpl** [comment]
I see! Thank you for the explanation! I'm not sure if realistically I'd be able to write out all the type information for all the stubs for docutils -- I'm neither involved in the development of the library, nor a user beyond that single use case (of parsing the `.rst` files). But, if there's anything I can do to help get the PR #10569 merged, please let me know here or in the PR.
