### ISSUE TITLE
saxutils.escape should accept unicode

### ISSUE THREAD

**Issue by dgoldstein0** [python/typeshed#1062]
https://github.com/python/typeshed/blob/7d80824092962f06962bd02f3bd04865401e85c4/stdlib/2and3/xml/sax/saxutils.pyi#L10

should allow the first argument to be unicode.  @euresti seems to think the proper type is `AnyStr` and return type should be `AnyStr`; I trust his judgement.

**Comment by gvanrossum** [comment]
Well don't just stand there, *do* something! :-)
