### ISSUE TITLE
Rename `codecs._Encoder`, `codecs._Decoder`, `.encode` and `.decode` `input` argument

### ISSUE THREAD

**Issue by denballakh** [python/typeshed#10657]
`input` argument of `.encode` and `.decode` methods shadows built-in function `input`, which might trigger linter checks and make code editor highlight this variable as built-in.

This shows that nobody is calling these methods using `input` keyword argument:
https://grep.app/search?q=decode%28input%3D&filter[lang][0]=Python
https://grep.app/search?q=encode%28input%3D&filter[lang][0]=Python

**Comment by srittau** [comment]
I haven't investigates this, but we should probably just turn them into positional-only arguments.

**Comment by sobolevn** [comment]
Yes, they are pos-only in CPython:

```python
>>> import codecs
>>> codecs.getencoder('utf8')
<built-in function utf_8_encode>
```

```c
_codecs.utf_8_encode
    str: unicode
    errors: str(accept={str, NoneType}) = None
    /
```

Also, docs do not specify the signature https://docs.python.org/3/library/codecs.html#codecs.getencoder

So, pos-only is our best bet.
