### ISSUE TITLE
redis-py types don't seem to be quite ready as of version 5.0.0

### ISSUE THREAD

**Issue by meshantz** [python/typeshed#10684]
Upgrading to redis 5.0.0 and removing types-redis results in an error for the code given in https://github.com/redis/redis-py/issues/2933

Can `types-redis` really be removed at that point? Is that issue a known backwards incompatibility that clients are expected to work around?

**Comment by AlexWaygood** [comment]
Basically a duplicate of the discussion in #10592; please add your thoughts there! :)
