### ISSUE TITLE
`value_encode` and `value_decode` of `http.cookies.BaseCookie` not returning tuples

### ISSUE THREAD

**Issue by flaeppe** [python/typeshed#10699]
[Documentation](https://docs.python.org/3/library/http.cookies.html#cookie-objects) states

> Return a tuple (real_value, coded_value) [...]

For both `BaseCookie.value_decode` and `BaseCookie.value_encode`, although typeshed doesn't align:

https://github.com/python/typeshed/blob/32535ee8952dffecbe7a9fd04e5ed8ba0f1c8da2/stdlib/http/cookies.pyi#L50-L53

**Comment by sobolevn** [comment]
@flaeppe please, feel free to send a PR :)

**Comment by flaeppe** [comment]
Yes, already done: #10702
