### ISSUE TITLE
`defaultdict` should be able take only one type argument. 

### ISSUE THREAD

**Issue by muzam1l** [python/typeshed#10692]
Currently, to create a typed `collections.defaultdict`, we need something like this: 

```py
d = defaultdict[str, int](int)
```

While the second type argument (`int` in this case) may be helpful for other types like lists, etc., it should be inferred from the first argument to `defaultdict()` by default. So we can write the above statement as below to avoid repetition: 

```py
d = defaultdict[str](int)
```

We are able to skip both of type arguments currently. In that case type inferred type in the above case would be  `defaultdict[Unknown, int]`, but it does not allow us to just type the `key` without typing `value`.

**Comment by AlexWaygood** [comment]
I agree that type hints for `defaultdict` can get annoyingly verbose, but there's no way of improving the situation given the current type system, which means there's nothing actionable here for typeshed unfortunately :(
