### ISSUE TITLE
2.7 stub for Decimal is incomplete, incompatible with numbers.Number

### ISSUE THREAD

**Issue by wittekm** [python/typeshed#107]
Incomplete in that it has no **div** (and some other stubs). 
Also, the true code for it registers it as an instanceof Number via a .register call; we need to add Number to the interfaces it implements.

**Comment by wittekm** [comment]
(These are what caused the rollback on https://github.com/python/typeshed/commit/6a496215e7ddc728db15d4b6c190779523a3507e )

**Comment by JelleZijlstra** [comment]
Looks like #545 fixed this back in 2016.
