### ISSUE TITLE
`tuple` methods should use `Self`?

### ISSUE THREAD

**Issue by randolf-scholz** [python/typeshed#10727]
In the definition of `tuple`

https://github.com/python/typeshed/blob/8597724ac113d187d2ebc9f58cef3b410b1d5dae/stdlib/builtins.pyi#L956-L980

It seems in many methods, **in the arbitrary size case**, one could/should substitute `tuple[_T_co, ...]` with `Self`, in particular `__add__(self, __value: tuple[_T_co, ...])`, `__mul__`, `__rmul__` and `__getitem__(self, __key: slice)`. I.e. when `tuple[_T_co, ...]` appears as a return value.

How can one do a case distinction between the arbitrary size case and the fixed size case?

**Comment by randolf-scholz** [comment]
Ad least for `list` it seems that the override should be `def __getitem__(self, __s: slice) -> Self` instead of https://github.com/python/typeshed/blob/8597724ac113d187d2ebc9f58cef3b410b1d5dae/stdlib/builtins.pyi#L1037-L1038. However, both inherit this method from `Sequence`.

Thinking about it, it seems that even for `Sequence` we should have

```python
def __getitem__(self, __s: slice) -> Self
```

and `tuple` is rather the odd one out.

**Comment by AlexWaygood** [comment]
> Thinking about it, it seems that even for `Sequence` we should have
> 
> ```python
> def __getitem__(self, __s: slice) -> Self
> ```

Be careful about that one. Changing the signature of `Sequence.__getitem__` means you're changing the definition of what it means in Python for something to be considered a Sequence. I'm not sure it's true that a class _has_ to return `Self` from `__getitem__` in order for it to be considered a `Sequence` — I think we can be more lenient there

**Comment by randolf-scholz** [comment]
As per my other comment, one possible solution would be to introduce a `FixedSizeSequence` that captures the nature of `tuple[T1, ..., Tn]` and then do a case distinction when calling `tuple[...]`

- `tuple[T, ...]` -> `Sequence[T]`
- `tuple[T1, ...., Tn]` -> `FixedSizeSquence[Ts]`, where `Ts` is a `TypeVarTuple`.

Or, and I don't know if this is possible, do a case distinction in `Sequence` where `Sequence[T]` gives one set of overloads, but `Sequence[Ts]` for a `TypeVarTuple` gives another set of overloads.

**Comment by randolf-scholz** [comment]
> I'm not sure I fully understand this proposal, since Sequence is generic over a single TypeVar rather than a TypeVarTuple

Like, if it were possible to overload a whole class definition

```python
@overload # T regular TypeVar
class Sequence(T): 
    ...
    @overload
    def __getitem__(self, slice) -> Self: ...
@overload # Ts  TypeVarTuple
class Sequence(*Ts): 
    ...
    @overload
    def __getitem__(self, slice) -> Sequence[...]: ...
```

**Comment by AlexWaygood** [comment]
> Like, if it were possible to overload a whole class definition

Well, that would _definitely_ need a PEP :-) And the typeshed issue tracker probably isn't the right place to discuss that ;-)

**Comment by JukkaL** [comment]
Returning `Self` from tuple `__getitem__` would be incorrect:
```py
from typing import NamedTuple

class A(NamedTuple):
    x: int
    y: int

print(type(A(0, 0)[:1]))   # <class 'tuple'>
```
`list` is similar.

**Comment by AlexWaygood** [comment]
Indeed:

```pycon
>>> class Foo(tuple): ...
...
>>> type(Foo((1, 2, 3))[:2])
<class 'tuple'>
>>> class Bar(list): ...
...
>>> type(Bar([1, 2, 3])[:2])
<class 'list'>
```

@randolf-scholz, if the `pytorch.Size` class is returning `Self` from these methods, it must be overriding `__getitem__`. I don't think there's anything actionable for typeshed here, I'm afraid :-)
