### ISSUE TITLE
openpyxl Worksheet columns is incorrectly typed

### ISSUE THREAD

**Issue by ostr00000** [python/typeshed#10744]
Property `columns` should return a generator of `tuple[Cell]` instead of a single `Cell`.

This is a very similar issue to #9904, except for `column`.

**Comment by kltws** [comment]
Looking at the implementation of Worksheet, particularly in the _clean_merge_range method (called by merge_cells), it seems that the Worksheet._cells dict can contain MergedCell instances in addition to Cell instances. Shouldn't columns (and for that matter, all the other methods like cell, __getitem__, rows, iter_rows/iter_cols that returns things found in _cells) be typed to reflect this?

**Comment by ostr00000** [comment]
## Type of internal `_cells`
Yes, the type of `Worksheet()._cells` is `dict[tuple[int, int], Cell | MergedCell]`, so the return type is indeed `Cell | MergedCell`.
Current `openpyxl` implementation for reference: https://foss.heptapod.net/openpyxl/openpyxl/-/blob/branch/3.1/openpyxl/worksheet/worksheet.py#L609

## Possible solution
If I understand tips from `CONTRIBUTING.md` correctly union type should be avoided, because to satisfy type check an explicit `if` must be written on result from such function.
The preferred solution is to use `Any` and then annotate the result with expected type (when we know that `MergedCell` is not used at all) or perform `isinstance` check.

I see 3 possible solutions:
1. Keep in stub only `Cell` type - after all `MergedCell` is not so frequently used.
2. Refactor stub to use `Cell | MergedCell` - this is real type, but it requires additional check in user code + it is not recommended by typeshed (`avoid union return types` in https://github.com/python/typeshed/blob/main/CONTRIBUTING.md).
3. Refactor stub to use `Any` - this is recommended by typeshed, but provides no typing value (without additional, explicit annotation).
4. Refactor stub to use common class for `Cell` and `MergedCell`. Fortunately, there is common class `StyleableObject`. But in that case, a `typing.cast` would be required (instead of annotating) if somebody would want to use `Cell`.

There is https://github.com/python/typing/issues/566 that would be handy in this case.
I am ok with no additional type (option `1`), so I am not going to create new issue/PR.

## Real solution
Of course, a function returning many types is a code smell. According to [current usage](https://sourcegraph.com/search?q=context:global+file:.*py%24+/%5Cbisinstance%5C%28%5Cw%2B%2C%5Cs*MergedCell%5Cb%5C%29/&patternType=standard&sm=0&groupBy=group), most usages want only to get a value:
- increment column until normal cell: `while isinstance(cell, MergedCell): column += 1`,
- get real cell: ` cell = self.normalize_merged_cell_link`,
- skip processing: `warnings.warn(...); continue`.

The best solution, in my opinion, is to redesign `Worksheet` class interface: 
- let `cell` return always `Cell` object,
- if you are interested whenever the cell is merged, call an additional function.
