### ISSUE TITLE
Typing of requests.HTTPError possibly too strict

### ISSUE THREAD

**Issue by moltob** [python/typeshed#10764]
Recent contributions https://github.com/python/typeshed/pull/8989 and https://github.com/python/typeshed/pull/10740 improved the typing of `requests.HTTPError`, so now we have:

https://github.com/python/typeshed/blob/5b8193b9fd437cca0ad00609c367f5188798c870/stubs/requests/requests/exceptions.pyi#L13-L16

This is causing issues in our code as it appears to be incompatible to the way requests itself is using the type:

Now the `request` argument is mandatory. However, requests itself does not do it this way, e.g. see the implementation of [`Response.raise_for_status`](https://github.com/psf/requests/blob/881281250f74549f560408e5546d95a8cd73ce28/src/requests/models.py#L1018-L1019):

![image](https://github.com/python/typeshed/assets/6240478/39b5dbb7-16e8-49dd-8c7a-ead5bc0ac040)

Secondly, the type is now restricted to be `Request`.  In particular this prevents assigning a `PreparedRequest` (which is not derived from `Request`). However, this is exactly what requests is doing in [`RequestException.__init__`](https://github.com/psf/requests/blob/881281250f74549f560408e5546d95a8cd73ce28/src/requests/exceptions.py#L21-L23), in addition to explicitly allowing _not_ to pass a `request` argument:

![image](https://github.com/python/typeshed/assets/6240478/98a4a6c6-0521-48cb-a22d-ba5d0d5da790)

Please reconsider the strict typing.

@JelleZijlstra @srittau

**Comment by akx** [comment]
It looks like the type of `request` in the exception should be `Request | PreparedRequest`, since `response.request` is typed to be a `PreparedRequest`; trying to manually do `HTTPError(response=resp, request=resp.request)` now raises 

> Argument "request" to "HTTPError" has incompatible type "PreparedRequest"; expected "Request"

**Comment by srittau** [comment]
Thanks to @akx's PR, the `request` type is now relaxed. But per the example given I think the assumptions in #8989 and #10740 are wrong and we need to allow `None` values (and defaults) again for `request` and `response`.

**Comment by hsheth2** [comment]
I opened https://github.com/python/typeshed/pull/10776 to fix this - @srittau let me know what you think.

**Comment by srittau** [comment]
types-requests 2.31.0.6 should fix the remaining issues when it gets released within the next few hours. Please comment here if there are still issues remaining, so we can reopen the issue. Thanks again to @akx and @hsheth2 for the fixes!

**Comment by djowett** [comment]
I still get an error like this, is that intended?

```
 error: Missing named argument "response" for "HTTPError"  [call-arg]
```

**Comment by AlexWaygood** [comment]
> I still get an error like this in 2.31.0.6, is that intended?
> 
> ```
>  error: Missing named argument "response" for "HTTPError"  [call-arg]
> ```
> 
> the argument is indeed missing, but isn't that valid?

This should be fixed in the latest version of `types-requests`.
