### ISSUE TITLE
Issue with ctypes Structure.from_buffer_copy class method

### ISSUE THREAD

**Issue by eehusky** [python/typeshed#10777]
I was getting ready to submit this against pyright but happened across this report there which brought me here since it seems to be the same sort of problem.
https://github.com/microsoft/pyright/issues/5932

And related to this typeshed issue.
https://github.com/python/typeshed/issues/10567

When calling the from_buffer_copy class method on a ctypes structure an error is reported indicating it is not callable when it should be (when calling it on an instance of the structure its fine and shouldnt be?).

```python
import ctypes

class SomeStructure(ctypes.Structure):
    _fields_ = [
        ('field0', ctypes.c_uint32),
        ('field1', ctypes.c_uint32),
        ('field2', ctypes.c_uint32),
        ('field3', ctypes.c_uint32),
    ]

SomeStructure.from_buffer_copy(bytes([0]*16)) # error, should be ok   Object of type "_CField[Any, Any, Any]" is not callable

SomeStructure(0,0,0,0).from_buffer_copy(bytes([0]*16)) # ok, should be an error/fails at runtime?

# And for some reason this works (and it should).
SomeStructureArray = SomeStructure*10
SomeStructureArray.from_buffer_copy(bytes([0]*160)) # is okay and should be okay
```

**VS Code extension or command-line**
pyright version: 1.1.328

**Comment by eehusky** [comment]
I also noticed that this error is reproducible with the other structure class methods in_dll, from_buffer, etc.

**Comment by srittau** [comment]
This is weird. `from_buffer_copy` is marked as a classmethod in the stubs and mypy 1.5.1 treats it as such, i.e. it accepts both:

```python
SomeStructure.from_buffer_copy(bytes([0]*16))
SomeStructure(0,0,0,0).from_buffer_copy(bytes([0]*16))
```

I'm not sure there is a way to reject the second call, as it would work with "normal" classmethods, but it doesn't work here (for whatever reason). I'm not sure why pyright rejects the first call, though. Maybe @erictraut has an idea.

**Comment by erictraut** [comment]
The metaclass used for `SomeStructure` is `_StructUnionMeta`, which is defined as:
```python
class _StructUnionMeta(_CDataMeta):
    ...
    def __getattr__(self, name: str) -> _CField[Any, Any, Any]: ...
```

Pyright is assuming that the runtime will use this `__getattr__` call when accessing `from_buffer_copy` in the first expression. However, it appears that this isn't consistent with the actual runtime behavior.

I've reopened the [bug report in pyright](https://github.com/microsoft/pyright/issues/5932) and will take another look at it. 

I think it's safe to close this issue. Apologies for misdiagnosing this.
