### ISSUE TITLE
types-jsonschema 4.19.0.0 cannot be used with mypy on Python 3.7

### ISSUE THREAD

**Issue by GavBurke** [python/typeshed#10772]
There's not much info I can give in this "bug report", so hopefully others seen the same issue and can chime in, but after our nightly pipeline upgrade it's types-jsonschema from 4.17.0.10 to 4.19.0.0 on Saturday night, our pipeline now breaks with mypy reporting `/home/gavin/.local/lib/python3.7/site-packages/referencing/_core.py:188: error: invalid syntax  [syntax]
Found 1 error in 1 file (errors prevented further checking)`

Downgrading types-jsonschema to 4.17.0.10 then fixes this issue

**Comment by AlexWaygood** [comment]
`types-jsonschema 4.19.0.0` depends on the `referencing` library following #10583. The `referencing` library is incompatible with Python 3.7, as it uses PEP-570 syntax (but the library didn't state as such in its `pyproject.toml` or `setup.py` file in its early versions, meaning that pip will happily install it on Python 3.7, unfortunately).

**Comment by AlexWaygood** [comment]
Once https://github.com/typeshed-internal/stub_uploader/pull/103 is merged, we will be able to push a release of `types-jsonschema` to PyPI that properly declares that it can only be used with Python 3.8+. Not sure what's to be done with the already-released version of `types-jsonschema`, though.

**Comment by AlexWaygood** [comment]
> We could yank release 14.9.0.0.

Yeah. Suggested plan of action:
1. Revert https://github.com/python/typeshed/pull/10583 temporarily
2. Yang release 4.19.0.0 from PyPI
3. Merge https://github.com/typeshed-internal/stub_uploader/pull/103
4. Revert the revert of https://github.com/python/typeshed/pull/10583, but add `requires_python = ">= 3.8"` to the `METADATA.toml` file

**Comment by srittau** [comment]
This seems to have worked: https://pypi.org/project/types-jsonschema/#files

@ilevkivskyi Could you yank types-jsonschema 4.19.0.0 and 4.19.0.1?

**Comment by GavBurke** [comment]
> This seems to have worked: https://pypi.org/project/types-jsonschema/#files
> 
> @ilevkivskyi Could you yank types-jsonschema 4.19.0.0 and 4.19.0.1?

Any timeline on the yanking of the 4.19.x python 3.7 packages??

**Comment by ilevkivskyi** [comment]
> Could you yank types-jsonschema 4.19.0.0 and 4.19.0.1?

Done.

**Comment by AlexWaygood** [comment]
I confirmed locally that `pip install types-jsonschema --upgrade` will now install `types-jsonschema-4.17.0.10` if you're using Python 3.7. This should therefore now be fixed.

Thanks for yanking @ilevkivskyi, and thanks for reporting @GavBurke! Sorry for the disruption -- please let us know if you have any more problems :-)
