### ISSUE TITLE
Daily tests are running on forks

### ISSUE THREAD

**Issue by hamdanal** [python/typeshed#10781]
I just want to let you know that automated daily tests are running on forks of typeshed. I didn't know this until I got a notification about a failing test here https://github.com/hamdanal/typeshed/actions/runs/6306583853. Maybe automated tests should not run on forks? Only tests triggered by changes/commits/PRs would be relevant to forks (I think!).

**Comment by AlexWaygood** [comment]
Thanks! #10782 should fix this
