### ISSUE TITLE
Add `Traversable` to builtin `open` overloads

### ISSUE THREAD

**Issue by a-recknagel** [python/typeshed#10793]
You can put a `Traversable` in the `open` function and it will work:

```python
import importlib.resources

with open(importlib.resources.files("mypy") / "__init__.py") as f:
    print(f.read()) # prints: "# This page intentionally left blank"
```

But mypy complains about it:
```
foo.py:3: error: No overload variant of "open" matches argument type "Traversable"  [call-overload]
```

Or is there a reason why all the examples for `importlib.resources.files` use `traversable.open()` over `open(traversable)`?

----

moved from https://github.com/python/mypy/issues/16194

**Comment by srittau** [comment]
In this particular example, a `PosixPath` is returned from `files()`, which matches the `Traversable` protocol and can be passed to `open()`. But `Traversable` is not guaranteed to be "openable", which is probably why it provides the `open()` method.

**Comment by AlexWaygood** [comment]
As a workaround (if you don't want to use the `.open()` method for some reason), you can do something like this to narrow the type returned by `importlib.resources.files`:

```py
import importlib.resources
import os

the_file = importlib.resources.files("mypy") / "__init__.py"
assert isinstance(the_file, os.PathLike)
with open(the_file) as f:
    print(f.read()) # prints: "# This page intentionally left blank"
```
