### ISSUE TITLE
request: Explicitly-reexport `@type_check_only` in `typing_extensions`

### ISSUE THREAD

**Issue by bzoracler** [python/typeshed#10829]
`@typing.type_check_only` was not explicitly-reexported from `typing_extensions` as part of the [typing-extensions 4.7.* update](https://github.com/python/typeshed/pull/10344):

https://github.com/python/typeshed/blob/860e34eec9873df0bd934df43b1efce32ea9964c/stdlib/typing_extensions.pyi#L70

As it is public API in `typing.pyi` with no indication of being deprecated, would there be any issues in re-exporting this symbol? I understand that it's still not available as a runtime object in `typing_extensions.py`, if that affects anything.

**Comment by JelleZijlstra** [comment]
I don't think we should claim it's in `typing-extensions` when it isn't.

And I wouldn't want to add it to `typing-extensions` before it is in `typing` in reality.

**Comment by bzoracler** [comment]
I get the impression from the Python docs that [`typing.type_check_only` will remain a non-runtime object](https://docs.python.org/3/library/typing.html#typing.type_check_only), with no plans to put an existent symbol in `typing.py`. However, since the symbol is wholly defined in `typing.pyi`, I assumed that the motivation for re-exporting the other symbols from `typing` would equally apply to `type_check_only`, allowing one to use `typing_extensions` in lieu of `typing` in all situations.

Not a big issue though, since there's plenty of workarounds. Thanks for the response.
