### ISSUE TITLE
Incorrect types filters in `bleach.sanitizer.Cleaner`

### ISSUE THREAD

**Issue by fsan** [python/typeshed#10834]
Hello

I have read the README.md for typeshed and it suggests to open a github issue for discussing potential incorrect stubs. I hope this is the right place to post this question.

I am having problems with `types-bleach` and I believe it might be because the stubs are incorrect.
I simplified the minimal example of `bleach.sanitizer.Cleaner` to open this ticket and I was able to reproduce it using `types-bleach="*"` and `bleach~=6.0` in my dependencies.

Here is the code that mypy is rejecting:
```python3
from bleach.html5lib_shim import Filter
from bleach.sanitizer import Cleaner, BleachSanitizerFilter

class MyFilter(Filter):
        ...

if __name__ == "__main__":
    cleaner: Cleaner = Cleaner(filters=[MyFilter])
```

When running: `mypy main.py`:
```
main.py:10: error: List item 0 has incompatible type "type[MyFilter]"; expected "_Filter"  [list-item]
main.py:10: note: Following member(s) of "MyFilter" have conflicts:
main.py:10: note:     Expected:
main.py:10: note:         def __call__(self, *, source: BleachSanitizerFilter) -> Any
main.py:10: note:     Got:
main.py:10: note:         def MyFilter(self) -> MyFilter
Found 1 error in 1 file (checked 1 source file)
```

I do not believe this is a liskov substitution problem because, as you can see in the documentation for Mozilla bleach [here](https://github.com/mozilla/bleach/blob/main/docs/clean.rst#html5lib-filters-filters), `Cleaner.__init__` expects a `Type[Filter]` as list element and not a `Filter`.

If I understood correctly the the problem, `bleach-stubs.sanitizer` should have a different typing.

Current types:
```python3
class Cleaner:
    # ...
    filters: Iterable[_Filter]
     #...
    def __init__(
        self,
        # ...
        filters: Iterable[_Filter] | None = None,
        # ...
    ) -> None: ...
    # ...
```

My suggested typing

```python3
class Cleaner:
    # ...
    filters: Iterable[Type[Filter]]
     #...
    def __init__(
        self,
        # ...
        filters: Iterable[Type[Filter]] | None = None,
        # ...
    ) -> None: ...
    # ...
```

I would like to know if the analysis above makes sense or if I am missing something.
Thank you 🙇

**Comment by srittau** [comment]
Thanks for the report. `_Filter` is a protocol to which html5lib's `Filter` class's constructor is compatible to. So it would work, except that our typing of `bleach.html5lib_shim.Filter` is incorrect:

https://github.com/python/typeshed/blob/25eb99cbec6d791558bce4b5b224e307ce755029/stubs/bleach/bleach/html5lib_shim.pyi#L7-L8

We didn't type the constructor, which is why type checkers falsely assume that `Filter` is incompatible.

**Comment by fsan** [comment]
Thank you for your answer. I agree it should work but for some reason not clear to me yet it is not.
I am sure I saw other examples from typeshed using the same Protocol and I had no problems with them.

I am sorry, but I do not understand what would be the solution for this case that I should apply.

**Comment by srittau** [comment]
@fsan types-bleach 6.0.0.5 should fix your problem. Please let us know if the problem persists.

**Comment by fsan** [comment]
Hello @srittau 
I tested it with `6.0.0.5` and it worked for me.
Thank you very much 🙇 🙇
