### ISSUE TITLE
`PyInstaller.building.api.EXE` is missing `hide_console`

### ISSUE THREAD

**Issue by bersbersbers** [python/typeshed#10844]
Compare https://github.com/pyinstaller/pyinstaller/pull/7735 and

> (Windows) Add an option to hide or minimize the console window in console-enabled applications, but only if the program’s process owns the console window (i.e., the program was not launched from an existing console window). ([#7729](https://github.com/pyinstaller/pyinstaller/issues/7729))

from https://pyinstaller.org/en/v6.0.0/CHANGES.html#id1

**Comment by srittau** [comment]
Indeed. This should probably be added for all platforms, because it exists on all platforms and just issues a warning on non-Windows platforms. PR welcome!

This should have been caught by our tests, but wasn't, since we have an overzealous stubtest allowlist entry: `PyInstaller\.building\.\w+?`.
