### ISSUE TITLE
Return type of zipfile.Path.open is not correct when using non-binary mode

### ISSUE THREAD

**Issue by FeldrinH** [python/typeshed#10847]
Example:
```python
import zipfile

zip_path = zipfile.Path('example.zip', at='example.txt')
with zip_path.open(mode='r') as f:
    content = f.read()
    assert isinstance(content, str)
```
In this example the code functions as expected, and prints `<class 'str'>`, but the inferred type for `f` is `IO[bytes]` and the inferred type for content is consequently `bytes`, which is incorrect. The signature of `zipfile.Path.open` seems to assume a binary mode no matter what the `mode` argument actually is.

Python version: 3.10.11

PS: I am aware of https://github.com/python/typeshed/issues/9966. I believe that that is a separate issue, because the issue there is about `zipfile.Path.open` arguments, whereas this issue is about the return value.

**Comment by srittau** [comment]
Thanks for the report. Our `Path.open()` signature was broken in several regards. I opened #10861 to fix it.
