### ISSUE TITLE
APScheduler 3.x

### ISSUE THREAD

**Issue by davetapley** [python/typeshed#10850]
It sounds like 4.x will have typing (https://github.com/agronholm/apscheduler/issues/465), but in the interim I started stubs for 3.x.

I have them on a fork here: https://github.com/JEFuller/typeshed

If there's interest then perhaps we can get them fleshed out and open a PR.

See also: https://github.com/agronholm/apscheduler/discussions/793

**Comment by srittau** [comment]
Is there an expected release date for 4.x? We usually remove type stubs six months after the typed package releases its own stubs. So if the release is "soon", it would probably involve more busy work than it's worth. Otherwise PR welcome!

**Comment by davetapley** [comment]
@agronholm suggests this year in ⬇️ but I guess we'll see!
https://github.com/agronholm/apscheduler/issues/465#issuecomment-1690760114

@srittau is six months hard rule?
I think 3.x to 4.x will be a big change, so I _assume_ people will be on 3.x for much longer.

Just curious, are there technical challenges to having stubs in here for the previous major version?

**Comment by srittau** [comment]
It's not a hard rule, so if the old version is still in heavy use, we can keep the stubs longer.
