### ISSUE TITLE
Missing stub for configparser.SectionProxy

### ISSUE THREAD

**Issue by Xandaros** [python/typeshed#1085]
Can be imported and used just fine, but mypy complains that it can't find it.
It doesn't appear to be in the stub, but I might have found the wrong file - the project layout is a little confusing.

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR to fix it! The code should be in stdlib/3/configparser.pyi.

**Comment by ymyzk** [comment]
This issue is seemed to be fixed in #1311

**Comment by JelleZijlstra** [comment]
It is, thanks for commenting!
