### ISSUE TITLE
click stubs incompatible with Flask custom scripts

### ISSUE THREAD

**Issue by bbc2** [python/typeshed#1086]
The use of `click.group` with `FlaskGroup` and the `create_app` keyword argument, as suggested by http://flask.pocoo.org/docs/0.12/cli/#custom-scripts, raises an error with mypy 0.501:

```
app/manage.py:17: error: Unexpected keyword argument "create_app" for "group"
venv/lib/mypy/typeshed/third_party/3.6/click/decorators.pyi:42: note: "group" defined here
```

A simple way to reproduce the problem is with the following.

```python
import click


class FooGroup(click.Group):
    def __init__(self, msg, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.message = msg


@click.group(cls=FooGroup, msg='OK')
def cli():
    pass


if __name__ == '__main__':
    cli()
```

```
test.py:12: error: Unexpected keyword argument "msg" for "group"
venv/lib/mypy/typeshed/third_party/3.6/click/decorators.pyi:42: note: "group" defined here
```

**Comment by JelleZijlstra** [comment]
Thanks for the report! click.group's stub is in third_party/3.6/click/decorators.pyi, and pull requests correcting the arguments it takes would be appreciated.

**Comment by bbc2** [comment]
Actually I'm not sure what the best way to fix this is.  As you can see, the permitted arguments for `click.group` depend on the class you pass as the `cls` argument. Here, `FlaskGroup` allows `create_app` but my `FooGroup` takes a `msg` (that's arbitrary). Is there a way to express that with stubs? Otherwise, should we hard-code `create_app` so that it only works for users of `FlaskGroup` or allow any argument so that it works for any class but with some precision loss for mypy? I'd go for the latter because I think false positives are worse than false negatives but, as a minor contributor, I can't really judge.

**Comment by JelleZijlstra** [comment]
Sounds like it should just take `**kwargs: Any`.
