### ISSUE TITLE
LifoQueue and PriorityQueue in asyncio are not generic

### ISSUE THREAD

**Issue by azag0** [python/typeshed#1087]
Shouldn't `LifoQueue` and `PriorityQueue` from asyncio inherit from `Queue[T]` instead of `Queue`?

**Comment by azag0** [comment]
`JoinableQueue` as well.

**Comment by JelleZijlstra** [comment]
Looks like you're right. Pull requests are welcome.

**Comment by gvanrossum** [comment]
Fixed by #1088.
