### ISSUE TITLE
Missing click stubs referenced by click_default_group

### ISSUE THREAD

**Issue by s04lg934jkg** [python/typeshed#10872]
I've noticed that the stub for click_default_group in typeshed imports the click module, but the click stubs seem to be absent. This could lead to incomplete type checking for projects using both libraries. Can you add or reference the necessary click stubs?

https://github.com/python/typeshed/blob/main/stubs/click-default-group/click_default_group.pyi#L4

**Comment by AlexWaygood** [comment]
`types-click-default-group` declares a dependency on `click>=8.0.0`, which has inline types. A standards-compliant installer such as `pip` should install `click` as a dependency if you ask it to install `types-click-default-group`:

```
>pip install types-click-default-group
Collecting types-click-default-group
  Obtaining dependency information for types-click-default-group from https://files.pythonhosted.org/packages/4d/c0/365dc9bb50bfde3a735230beaa00d404bdd61103e54180f277c3e6aaf4ec/types_click_default_group-1.2.0.0-py3-none-any.whl.metadata
  Downloading types_click_default_group-1.2.0.0-py3-none-any.whl.metadata (1.5 kB)
Collecting click>=8.0.0 (from types-click-default-group)
  Obtaining dependency information for click>=8.0.0 from https://files.pythonhosted.org/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl.metadata
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting colorama (from click>=8.0.0->types-click-default-group)
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading types_click_default_group-1.2.0.0-py3-none-any.whl (2.9 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Installing collected packages: colorama, click, types-click-default-group
Successfully installed click-8.1.7 colorama-0.4.6 types-click-default-group-1.2.0.0
```

Is that not happening for you?

**Comment by s04lg934jkg** [comment]
Thanks for fast reply. I am reading pyi files as is by my tools, not checking dependencies.
My mistake. Closing.
