### ISSUE TITLE
Using `<` on a SupportsRichComparisonT

### ISSUE THREAD

**Issue by Kache** [python/typeshed#10886]
Is the following expected? Or is there an issue with either typeshed or the type checker?

```py
def foo(a: SupportsRichComparisonT, b: SupportsRichComparisonT):
    return a < b
```

```
main.py:16: error: Unsupported left operand type for < (some union)  [operator]
Found 1 error in 1 file (checked 1 source file)
```

https://mypy-play.net/?mypy=master&python=3.11&gist=2dcc0cc29ac7d0ee49e87b14a327b301

**Comment by srittau** [comment]
Yes, `SupportsRichComparisonT` allows objects which support *either* `<` *or* `>`. The latter will of course not work with this code. You would need to use `SupportsDunderLT` (or a typevar bound to it).

**Comment by AlexWaygood** [comment]
The situation is _slightly_ more complicated. `a < b` will only fail if both of the following hold True:
1. Either `type(a)` does not define `__lt__`, or `type(a).__lt__(a, b)` returns `NotImplemented`
2. Either `type(b)` does not define `__gt__`, or `type(b).__gt__(b, a)` returns `NotImplemented`

Observe:

```pycon
Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> class OnlyHasGT:
...     def __init__(self, x):
...         self.x = x
...     def __gt__(self, other):
...         return self.x > other.x
...
>>> class OnlyHasLT:
...     def __init__(self, x):
...         self.x = x
...     def __lt__(self, other):
...         return self.x < other.x
...
>>> OnlyHasGT(42) < OnlyHasGT(64)
True
>>> OnlyHasGT(42) < OnlyHasLT(64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: '<' not supported between instances of 'OnlyHasGT' and 'OnlyHasLT'
>>> OnlyHasLT(42) < OnlyHasGT(64)
True
>>> OnlyHasLT(42) < OnlyHasLT(64)
True
```

If both `a` and `b` are `SupportsRichComparisonT`, that means that both of them have _either_ a `__lt__` method _or_ a `__gt__` method. I think that means that mypy's error is a true positive, as it can't be ruled out that `a` only has a `__gt__` method and `b` only has a `__lt__` method which, as you can see from the REPL demo above, would mean that the `a < b` operation would fail.
