### ISSUE TITLE
pywin32.win32.win32print.StartDocPrinter wrong positional arguments order

### ISSUE THREAD

**Issue by belono** [python/typeshed#10891]
Greetings!

I would like to report a simple issue:

The order of positional arguments to [pywin32.win32.win32print.StartDocPrinter](https://github.com/python/typeshed/blob/main/stubs/pywin32/win32/win32print.pyi#L16) should be `(hprinter, level, _tuple)` as indicated in [pywin32 docs](https://mhammond.github.io/pywin32/win32print__StartDocPrinter_meth.html) instead of `(hprinter, _tuple, level)`.

This is causing false positives during the type checking.

**Comment by Akuli** [comment]
PR welcome :)

**Comment by belono** [comment]
I closed my fork's PR in favor of #10898 which is more complete and targets upstream repository.

Thank you all for your work!
