### ISSUE TITLE
Replace isort with ruff?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#10911]
I think @AlexWaygood suggested this originally and I pushed back against it. I've come around to the idea to using ruff for sorting imports, iff ruff has feature parity with and same sort order as isort (for our use case).

**Comment by AlexWaygood** [comment]
I'm +1 on this. isort isn't exactly bug-free, and has very infrequent releases (so bugs don't generally get fixed quickly). From what I can tell, ruff pretty much has feature parity with isort, has much more frequent releases, and is also faster. Plus, we're already using ruff in CI, so it'll be one less tool to have to worry about.
