### ISSUE TITLE
Wrong argument nullability in hashlib.scrypt

### ISSUE THREAD

**Issue by Trolldemorted** [python/typeshed#10941]
The `hashlib.scrypt` function parameter type are wrong. The type hints indicate that `n`, `r` and `p` are optional:
https://github.com/python/typeshed/blob/5643362a1ea3187e3068a9107558e83a80afb334/stdlib/hashlib.pyi#L119-L122

but they are not:
https://docs.python.org/3/library/hashlib.html#hashlib.scrypt

**Comment by srittau** [comment]
Indeed. See this comment from the source code:

https://github.com/python/cpython/blob/9d4a1a480b65196c3aabbcd2d165d1fb86d0c8e5/Modules/_hashopenssl.c#L1299-L1301
