### ISSUE TITLE
types-openpyxl / worksheet.pyi / class Worksheet / method Cell / incorrect type for the value parameter

### ISSUE THREAD

**Issue by Questionsdenombres** [python/typeshed#10952]
# Used versions
- types-openpyxl==3.1.0.24
- openpyxl==3.1.2

# Declared type
File worksheet.pyi:
```python
def cell(self, row: int, column: int, value: str | None = None) -> Cell: ...
```

# Docstring of the "cell"method
File worksheet.py:
```python
    def cell(self, row, column, value=None):
        """
        Returns a cell object based on the given coordinates.

        Usage: cell(row=15, column=1, value=5)

        Calling `cell` creates cells in memory when they
        are first accessed.

        :param row: row index of the cell (e.g. 4)
        :type row: int

        :param column: column index of the cell (e.g. 3)
        :type column: int

        :param value: value of the cell (e.g. 5)
        :type value: numeric or time or string or bool or none

        :rtype: openpyxl.cell.cell.Cell
        """
```
# Mismatch
`str | None` versus `numeric or time or string or bool or none`

Thanks for your great Job !
Patrick - Paris, France.

**Comment by srittau** [comment]
PR welcome!

**Comment by Avasam** [comment]
FWIW there's some Cell value related changes in https://github.com/python/typeshed/pull/9511/files#diff-dabc24e406450b802c51dd6c9d1062ac0fed975dc4daef0e9cbe468aedcb6978R91 , so this should be fixed once I extract and complete Cell-related changes. But no ETA on that, feel free to open a PR specific for your needs.

**Comment by max-muoto** [comment]
@srittau This seems like it's fixed post: https://github.com/python/typeshed/pull/12363
