### ISSUE TITLE
type annotations for json.loads() does not exclude memoryview

### ISSUE THREAD

**Issue by kovidgoyal** [python/typeshed#10990]
Passing memoryview into json.loads raises a TypeError. But the type annotations do not enforce this.

Reference: https://github.com/python/cpython/issues/74379

**Comment by srittau** [comment]
Thanks for the report. This seems to be a mypy issue (python/mypy#15313). The stubs are correctly annotated as accepting `str | bytes | bytearray`:

https://github.com/python/typeshed/blob/359d4c095ddb3cc7a67f418a6685e1b094cb3825/stdlib/json/__init__.pyi#L39-L40
