### ISSUE TITLE
No library stubs for "requests" despite "types-requests" being installed.

### ISSUE THREAD

**Issue by T-31** [python/typeshed#11026]
Mypy won't find the stubs from typeshed for the "requests" module even after installing the "types-requests" stubs.

![Screenshot 2023-11-13 at 17 24 25](https://github.com/python/typeshed/assets/94144692/33decc04-09e9-42bb-8ea6-c5e221fe0561)

```
Installing missing stub packages:
/opt/homebrew/opt/python@3.11/bin/python3.11 -m pip install types-requests

Requirement already satisfied: types-requests in /opt/homebrew/lib/python3.11/site-packages (2.31.0.10)
Requirement already satisfied: urllib3>=2 in /opt/homebrew/lib/python3.11/site-packages (from types-requests) (2.0.7)
```

`requests` version 2.31.0
`types-requests` version 2.31.0.10

**Comment by JelleZijlstra** [comment]
I can't reproduce this. Likely your IDE is running in a different environment than the one you installed types-requests into. In any case, this is better reported to mypy, not typeshed.
