### ISSUE TITLE
shutil.chown stubs don't support passing in a integer file descriptor

### ISSUE THREAD

**Issue by kanetkarster** [python/typeshed#11079]
https://mypy-play.net/?mypy=latest&python=3.11&gist=a9a6c8d5712f81b264ec11df14a4bb2a 

```python
import shutil
import tempfile

with tempfile.TemporaryFile() as file:
    shutil.chown(file.fileno(), group="my_group")
```

per the python docs, [os.chown](https://docs.python.org/3/library/os.html#os.chown) which is directly called by [shutil.chown](https://github.com/python/cpython/blob/48dfd74a9db9d4aa9c6f23b4a67b461e5d977173/Lib/shutil.py#L1435C34-L1435C34) supports "[specifying a file descriptor](https://docs.python.org/3/library/os.html#path-fd)"

I believe the overloaded stubs in https://github.com/python/typeshed/blob/9bbfa3362a4abaa9b732b1389097985dc0f474aa/stdlib/shutil.pyi#L157C82-L157C82 should be changed accordingly.

I can send a PR if there's agreement with this

**Comment by srittau** [comment]
Sounds right, PR welcome!

**Comment by AlexWaygood** [comment]
We have an alias here that's useful for this kind of thing 👍

https://github.com/python/typeshed/blob/9bbfa3362a4abaa9b732b1389097985dc0f474aa/stdlib/_typeshed/__init__.pyi#L221

**Comment by kanetkarster** [comment]
https://github.com/python/typeshed/pull/11082 for this! Appreciate the quick feedback
