### ISSUE TITLE
str.count annotation is missing optional parameters.

### ISSUE THREAD

**Issue by gwk** [python/typeshed#1108]
```
s = "abc"
c = s.count('b', 0, 0) # x.py:2:4: error: Too many arguments for "count" of "str"
```
The code is valid; the error is spurious. As discussed in PR #1107, it appears that fixing this is a bit complex due to the type definition of Sequence.count.

**Comment by gwk** [comment]
@gvanrossum @JelleZijlstra I think I made a mistake in my earlier exploration of the problem. Simply changing the annotation of `str.count` appears to work, contrary to what I said earlier. Working on a new PR now.

**Comment by gvanrossum** [comment]
Glad you figured it out. Looking forward to the new PR. You can close the old one yourself.
