### ISSUE TITLE
str method start/end parameters should accept values supporting __index__

### ISSUE THREAD

**Issue by gwk** [python/typeshed#1110]
`str` `count`, `find`, `index`, `rfind`, and `rindex` all accept `int`, `None`, or any value implementing `__index__` for the start/end parameters. PR #1109 improves the annotation from `int` to `Optional[Int]`, but still neglects the `__index__` protocol. Rather than proposing a `typing.SupportsIndex` ABC, @JelleZijlstra suggested that we wait until PEP 544 to deal with this.

Note that there is a similar problem with `list` and `tuple`, with the additional caveat that CPython 3.6 does not accept None values but the raised exception suggests that they are supposed to. This deserves a bugs.python.org report.

**Comment by gwk** [comment]
Filed http://bugs.python.org/issue29935 for the list/tuple concern.

**Comment by srittau** [comment]
Python 3.8 actually added `SupportsIndex` (which was backported to `typing_extensions`), so this should be possible now.

**Comment by asottile** [comment]
also noticing this for `bytes.__getitem__` (and presumably `__getitem__` for a lot of the builtin types as well)
