### ISSUE TITLE
Referencing typeshed's own local stubs in editors

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#11102]
I've had a certain annoying pain point for quite some time with typeshed stubs.

From https://github.com/microsoft/pylance-release/issues/5209 :
> I'd expect absolute imports to find symbols from typeshed's own stubs, and "Go to type definition" to lead to typeshed's own `.pyi` (when it exists) instead of the installed library.
>
> Here's a couple example:
> ![image](https://github.com/microsoft/pylance-release/assets/1350584/e06090d1-d0b9-4f5f-9686-1c5523e8b9f3)
> ![image](https://github.com/microsoft/pylance-release/assets/1350584/7cfa1433-d882-48c1-9c85-a1b5bfdd165d)
> When new modules get added (or a new stub gets worked on, which is full of new modules):
> ![image](https://github.com/microsoft/pylance-release/assets/1350584/35e56da7-619d-42d4-b0cc-acfef0c4c68f)

`pip install types-*` inside typeshed is of limited use [...]
> when the stub library, or the module, doesn't exist yet. Or even if the current module is being modified in an incompatible manner (like adding generics to class).

One option is to use relative imports, but that can lead to going up many parents, and doesn't solve the issue when writing tests (all the openpyxl tests I wrote were painful because I could *not* trust my editor).

Another possible solution brought by Eric Traut:
> [...] Perhaps you could use an editable install when developing the stub package?

I don't have the most experience working with editable installs, but that would require writing a `pyproject.toml` for each stub right? Could it be done dynamically with a script?

I'd love to hear thoughts and experiences from other contributors. Especially if you use different tooling than I do (VSCode+Pylance)

Ref.: #8774

**Comment by hauntsaninja** [comment]
Maybe easier than setting up editable installs is just setting PYTHONPATH in your editor

**Comment by Avasam** [comment]
Ok so configuring `python.autoComplete.extraPaths` doesn't see to do anything:
```json
    "python.autoComplete.extraPaths": [
        "${workspaceFolder}/stubs/redis"
    ]
```

However, there's `python.envFile` which defaults to `${workspaceFolder}/.env`. I tried with the following content which worked:
```env
PYTHONPATH=stubs/redis
```
I could change the default to `${workspaceFolder}/.vscode/.env` and create a `.env` file in `.vscode` since it's specific to that editor (same as any other vscode config). Unless someone tells me this can be reused by other editors which have similar issues.
But having to maintain the full list of stubs in there is... eh. At least it's progress and I can maintain it for myself short-term.

**Comment by Avasam** [comment]
I have created a small script for myself that indiscriminately adds all stubs to `.vscode/.env`. I'm sharing here for posterity, but I doubt anyone else would ever need it.
```py
import os
from pathlib import Path


def main() -> None:
    vscodeFolder = Path(__file__).parent
    stubsFolder = vscodeFolder / ".." / "stubs"
    pythonPath = f"{os.pathsep}stubs{os.path.sep}".join(["PYTHONPATH=$PYTHONPATH", *os.listdir(stubsFolder)])
    with open(vscodeFolder / ".env", "w") as venvFile:
        venvFile.write(pythonPath)


if __name__ == "__main__":
    main()
```
