### ISSUE TITLE
defusedxml has no type stubs

### ISSUE THREAD

**Issue by solkaz** [python/typeshed#11140]
[For being the recommend library for handling xml](https://docs.python.org/3/library/xml.html#the-defusedxml-and-defusedexpat-packages), it is surprising that there are no type stubs for defusedxml. [There was previously an issue raised in defusedxml's repository](https://github.com/tiran/defusedxml/issues/46), but that was closed, and the project maintainer requested that an issue be opened on typeshed - having not found an issue for defusedxml, I'm writing this one out.

I'm fairly new to this kind of work, but happy to assist with getting this done

**Comment by srittau** [comment]
Thanks for the report. We generally accept new stubs in typeshed, so if you want to work on the stubs, please feel free to open a PR. See the CONTRIBUTING file for details. We don't keep requests for new third-party stubs open, though, so I'm going to close this issue.

**Comment by radarhere** [comment]
Stubs have now been contributed for defusedxml - https://github.com/python/typeshed/pull/11179 / https://pypi.org/project/types-defusedxml/
