### ISSUE TITLE
I’ve created and tested stubs for antlr4. 

### ISSUE THREAD

**Issue by Beakerboy** [python/typeshed#11161]
https://github.com/Beakerboy/VBA-Linter/tree/dev/stubs/antlr4

**Comment by srittau** [comment]
Thanks for creating those stubs! What is your intention of this issue? Are you looking to integrate the stubs into typeshed?

**Comment by Beakerboy** [comment]
If you want them, yeah. ANTLR is pretty popular so others may find it useful. You want a pull request or is there a particular format you want them in?

**Comment by srittau** [comment]
We'd certainly appreciate a PR to add these stubs. Please note that we have additional checks and tests, which might cause additional work.

**Comment by Beakerboy** [comment]
#11192 
Lots of red x's, let me know which need to be resolved.
