### ISSUE TITLE
win32print : WritePrinter accept bytes

### ISSUE THREAD

**Issue by a-detiste** [python/typeshed#11160]
We found this in EscPOS project that sends raw bytes to controle PointOfSales printers.

https://github.com/mhammond/pywin32/blob/main/win32/src/win32print/win32print.cpp#L976
https://github.com/python/typeshed/blob/main/stubs/pywin32/win32/win32print.pyi#L27C4-L27C4

@Avasam 

> WritePrinter|Copies the specified bytes to the specified printer

https://github.com/python-escpos/python-escpos/pull/607

**Comment by Avasam** [comment]
I'm about to do a batch up pywin32 updates so that I can turn on `reportUnknownMemberType` in AutoSplit. I can include `WritePrinter` changes.
