### ISSUE TITLE
typing.Final hint not showing when used at class level

### ISSUE THREAD

**Issue by Greg7000** [python/typeshed#11195]
**Describe the bug**
In VsCode (1.85.1) with Pylance language server (which uses the static type checker Pyright under the hood). The 'typing.Final' hint works well with module level constants however the hint is not provided for class variables.

**Code or Screenshots**
**Module level final hint OK**
![final_pylance_ok](https://github.com/python/typeshed/assets/43616824/918acdb2-4ae9-4959-87ae-5313c8ca17c9)

**Module level final hint NOK**
![final_pylance_nok](https://github.com/python/typeshed/assets/43616824/8ca7299c-5537-4c85-bf4a-a13106afe43c)

**Comment by AlexWaygood** [comment]
It sounds like you need to file this issue over at https://github.com/microsoft/pyright/issues; I'm not sure what there is for us to do here at typeshed :)
