### ISSUE TITLE
No type checking error for a function that returns a value and yields

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#11222]
Today I had this bug, and mypy didn't catch it:

```python
from collections.abc import Iterator

def get_strings(foo: bool) -> Iterator[str]:
    if foo:
        return ["foo1", "foo2"]
    else:
        yield "bar1"
        yield "bar2"

print(list(get_strings(True)))  # empty list
```

IMO this should be a type checking error. It might be fixable in typeshed by adjusting how/when `Generator` becomes a subtype of `Iterator`. If it isn't, I suggest just closing this issue, because there's already so many mypy issues that this would surely be a duplicate.

**Comment by hauntsaninja** [comment]
This PR makes mypy error on your example: https://github.com/python/mypy/pull/16717
