### ISSUE TITLE
pexpect - wrong annotation on timeout spawn class argument

### ISSUE THREAD

**Issue by renatoGarcia** [python/typeshed#11239]
On annotation for `timeout` argument of spawn class [`__init__` method](https://github.com/python/typeshed/blob/9fe7e1f28fb5f395b803e5c9ffc87cf2ef6cb42b/stubs/pexpect/pexpect/pty_spawn.pyi#L21), it is being set as `int` only.  However, it shold be `float | None` [as in documentation](https://github.com/pexpect/pexpect/blob/aa989594e1e413f45c18b26ded1783f7d5990fe5/pexpect/pty_spawn.py#L88).

The change from `int` to `float` is justified both from documentation referring to it as "number", as with it being possibly [forwarded](https://github.com/pexpect/pexpect/blob/aa989594e1e413f45c18b26ded1783f7d5990fe5/pexpect/_async_pre_await.py#L31) to `asyncio.wait_for` function, that [accept it as a float](https://docs.python.org/3/library/asyncio-task.html?highlight=wait_for#asyncio.wait_for).

**Comment by gareth-rees** [comment]
Two other code paths where it makes sense for `timeout` to be a `float` are:

1. In [`poll_ignore_interrupts`](https://github.com/pexpect/pexpect/blob/aa989594e1e413f45c18b26ded1783f7d5990fe5/pexpect/utils.py#L172-L173) where `timeout` is multiplied by 1000 to get a value in milliseconds for passing to [`select.poll.poll`](https://docs.python.org/3/library/select.html#select.poll.poll):
    ```
    timeout_ms = None if timeout is None else timeout * 1000
    results = poller.poll(timeout_ms)
    ```
    If `timeout` is required to be `int` then it is impossible to specify sub-second timeouts even though these are supported by `select.poll.poll`.

2. In [`select_ignore_interrupts`](https://github.com/pexpect/pexpect/blob/aa989594e1e413f45c18b26ded1783f7d5990fe5/pexpect/utils.py#L143) where `timeout` is passed to [`select.select`](https://docs.python.org/3/library/select.html#select.select):
    ```
    return select.select(iwtd, owtd, ewtd, timeout)
    ```
    The `select.select` documentation says, "The optional `timeout` argument specifies a time-out as a floating point number in seconds".
