### ISSUE TITLE
ctypes.LibraryLoader.LoadLibrary also accepts bytes

### ISSUE THREAD

**Issue by DeinAlptraum** [python/typeshed#11258]
It is typed as `ctypes.LibraryLoader.LoadLibrary(self, name: str) -> _DLLT: ...)` (see https://github.com/python/typeshed/blob/1de5830a2703936a96a126248227d5c7db883674/stdlib/ctypes/__init__.pyi#L72C4-L72C51) but I tested myself (only on Linux though) that passing `bytes` also works just fine.

If that is changed 
https://github.com/python/typeshed/blob/1de5830a2703936a96a126248227d5c7db883674/stdlib/ctypes/__init__.pyi#L47C1-L47C15
and
https://github.com/python/typeshed/blob/1de5830a2703936a96a126248227d5c7db883674/stdlib/_ctypes.pyi#L47C1-L47C68
should also be adapted

**Comment by srittau** [comment]
This seems incidental. For example, in the aix and Windows code paths, `name` is checked against strings. This would also mean that we'd have to make `CDLL` generic, so that we can type the `_name` attribute properly. I don't think we should make this change.

**Comment by DeinAlptraum** [comment]
Thanks for the answer. I've notcied this because the clang Python bindings are using this, but as I'm currently in the process of type-annotating them anyway, I'll just make it explicitly string and reference this issue.

Should I close this?
