### ISSUE TITLE
tkinter canvas: no error for float font size

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#11270]
No type checking error, but fails when running the code:

```python3
import tkinter
c = tkinter.Canvas()
c.pack()
c.create_text((100, 100), text="asd", font=("", 12.34, ""))
tkinter.mainloop()
```

Not sure if this applies to other areas of tkinter than the `Canvas` widget.

**Comment by ajaya0** [comment]
@Akuli 

import tkinter

c = tkinter.Canvas()
c.pack()
c.create_text(100, 100, text="asd", font=("", 12.34, ""))
tkinter.mainloop()

This should work without any issues. The create_text method takes the x and y coordinates as separate arguments, and you've passed them as a tuple in your original code, causing the problem.

**Comment by Akuli** [comment]
It can accept a tuple of coordinates or two separate arguments, but that's not what this issue is about. This is about the `font` parameter. I get this from your code and from my code:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2866, in create_text
    return self._create('text', args, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 2832, in _create
    return self.tk.getint(self.tk.call(
                          ^^^^^^^^^^^^^
_tkinter.TclError: expected integer but got "12.34"
```

**Comment by ajaya0** [comment]
could please tell me the path of this code

**Comment by ajaya0** [comment]
can you asign this problem to me

**Comment by ajaya0** [comment]
yes i can. please tell me more about this

**Comment by Akuli** [comment]
The tkinter stubs are in `stdlib/tkinter`. But if you don't know how a project is structured, you can search. For example, you could search for the method name `create_text` by running `git grep create_text`, like this:

```
$ git grep create_text
stdlib/tkinter/__init__.pyi:    def create_text(
stdlib/tkinter/__init__.pyi:    def create_text(
```

From here you can look at how the `font` argument is defined, and figure out why it accepts floats for the size even though it shouldn't.

**Comment by ajaya0** [comment]
import tkinter
c = tkinter.Canvas()
c.pack()
c.create_text(100, 100, text="asd", font=("", round(12.34), ""))
tkinter.mainloop() 

Now, I've used the round function to ensure that the font size is an integer. This should resolve the issue you're facing with the font parameter.

**Comment by Akuli** [comment]
Yes, but that's not what this issue is about either :)

The problem is that if I run a type checker on the invalid code, the type checker doesn't complain. It should complain, so that I notice the problem before I run the code.
