### ISSUE TITLE
Incorrect type for `setuptools._distutils.ccompiler.CCompiler.compile`

### ISSUE THREAD

**Issue by MarcellPerger1** [python/typeshed#11271]
The type of the `macros` argument of `CCompiler.compile` method (in `setuptools._distutils`) is incorrect.  
It should be `list[_Macro] | None` instead of `_Macro | None` (see the [documentation](https://setuptools.pypa.io/en/latest/deprecated/distutils/apiref.html#distutils.ccompiler.CCompiler.compile:~:text=macros%2C%20if%20given%2C%20must%20be%20a%20list%20of%20macro%20definitions))
https://github.com/python/typeshed/blob/5286722ef319b3931aa3e1af6b8948be2f6fa333/stubs/setuptools/setuptools/_distutils/ccompiler.pyi#L64-L74

**Comment by srittau** [comment]
Indeed, the implementation confirms this (and that it does an explicit `isinstance` check for `list`). PR welcome!
