### ISSUE TITLE
psycopg2.extras.LogicalReplicationConnection.cursor incorrect type

### ISSUE THREAD

**Issue by fovc9** [python/typeshed#11282]
mypy incorrectly complains about the following usage of `psycopg2.extras.LogicalReplicationConnection.cursor` ([docs](https://www.psycopg.org/docs/extras.html#replication-support-objects))

```py
import psycopg2
from psycopg2.extras import LogicalReplicationConnection
connection = psycopg2.connect(..., connection_factory=LogicalReplicationConnection)
cur = connection.cursor()
cur.start_replication(replication_slot, decode=True)  # [attr-defined]
```

The resulting error is

> "cursor" has no attribute "start_replication"  [attr-defined]

I think the reason this confusion arises is that [`ReplicationConnection`](https://github.com/python/typeshed/blob/770724013de34af6f75fa444cdbb76d187b41875/stubs/psycopg2/psycopg2/_psycopg.pyi#L511C36-L511C36) is not correctly typed. In the above example, `cur` should have type `psycopg2.extras.ReplicationCursor`, but instead it has type [`psycopg2._psycopg.cursor`](https://github.com/python/typeshed/blob/770724013de34af6f75fa444cdbb76d187b41875/stubs/psycopg2/psycopg2/_psycopg.pyi#L87).

`connection` appears to have the correct type, but the `.cursor()` method is inherited from the vanilla connection, [which (correctly) returns](https://github.com/python/typeshed/blob/770724013de34af6f75fa444cdbb76d187b41875/stubs/psycopg2/psycopg2/_psycopg.pyi#L453-L455) `psycopg2._psycopg.cursor` if no default is given

In the real implementation, `connection` [uses a C struct field called `cursor_factory` if none is given to the `.connect()` call](https://github.com/psycopg/psycopg2/blob/00870545b72231775258af4a4dd40842d2f18f0f/psycopg/connection_type.c#L80-L87). For `ReplicationConnection`, that field [is initialized to `psycopg2.extras.ReplicationCursor`](https://github.com/psycopg/psycopg2/blob/00870545b72231775258af4a4dd40842d2f18f0f/psycopg/replication_connection_type.c#L111C33-L111C39).

In the example above, then `cur` should have type `ReplicationCursor`, which would correctly locate the `start_replication` method

**Comment by ajaya0** [comment]
#Check this code 

import psycopg2
from psycopg2.extras import ReplicationConnection, ReplicationCursor
connection = psycopg2.connect(..., connection_factory=ReplicationConnection)
cur: ReplicationCursor = connection.cursor()
cur.start_replication(replication_slot, decode=True)
