### ISSUE TITLE
Why is the product of `Real` numbers `Any`?

### ISSUE THREAD

**Issue by Kakadus** [python/typeshed#11340]
Consider the following code:
```py
from numbers import Real

a: Real
b: Real
reveal_type(a * b)  # Any
reveal_type(a + b)  # Any
reveal_type(a - b)  # Any
reveal_type(a / b)  # Any

```
reveals `Any` during typechecking. Why is this the case? Even if `b` is typed as `int` or `float`, the result is still `Any`

From a mathematical perspective, this does not seem to make much sense.

I'm using latest mypy on python 3.11

**Comment by srittau** [comment]
Looking at the `numbers` module, while many arguments and return types are explicitly annotated using `Any`, I think most of those are actually unannotated. Many `Any`s were added in #4401, possibly to remove warnings about partially/unannotated methods. Maybe @erictraut remembers details.

**Comment by JelleZijlstra** [comment]
Note that the `numbers` module in general doesn't play well with type checking; see python/mypy#3186 for much background on why.

I don't see a reason why we can't annotate the return types of method like `Real.__add__`, though.

**Comment by erictraut** [comment]
@srittau, I don't remember the details of that PR. I think I was on a mission at that time to get all of the stdlib stubs to be "complete" with regard to return type annotations.

**Comment by srittau** [comment]
I've removed the `Any` annotations. Now at least we clearly mark the stubs as unannotated. Any PR to improve the situation welcome! I'm going to close the issue though, since we don't keep issues for unannotated stubs open. Thanks, for reporting this, @Kakadus!
