### ISSUE TITLE
`tkinter.Button` `overrelief` argument should allow empty string

### ISSUE THREAD

**Issue by MarcellPerger1** [python/typeshed#11356]
The `overrelief` argument of `tkinter.Button` should allow the empty string (`Literal[""]`) as well as the usual relief styles, see [the tcl docs](https://tcl.tk/man/tcl8.6/TkCmd/button.htm#M9:~:text=If%20the%20value%20of%20this%20option%20is%20the%20empty%20string%2C%20then%20no%20alternative%20relief%20is%20used%20when%20the%20mouse%20cursor%20is%20over%20the%20button.%20The%20empty%20string%20is%20the%20default%20value).

Relevant part of the code:

https://github.com/python/typeshed/blob/7a6a749449e15ec591fe9b3b17a3ffe312236cf2/stdlib/tkinter/__init__.pyi#L1033

This also applies to `Checkbutton` and `Radiobutton`.

**Comment by Akuli** [comment]
You're right, these should be changed to `_Relief | Literal[""]`. PR welcome :)
