### ISSUE TITLE
Mypy does not agree with types-pexpect version 4.9 for pexpect.spawn().before

### ISSUE THREAD

**Issue by pradiptama** [python/typeshed#11382]
After 4.9 update following started failing with mypy
```
def somefunction()-> str:
    p = pexpect.spawn('touch xx')
    p.expect(pexpect.EOF)
    return p.before.decode()
```
Mypy error out 
```
error: Incompatible types in assignment (expression has type "str | None", variable has type "bytes") 
```
Pinning to 4.8 resolved the issue.

**Comment by srittau** [comment]
I can't reproduce this problem with the latest stub, but I do get a type error in the `p.before.decode()` line. The latest stubs added a lot of annotations of fields that were not annotated before, among the the `SpawnBase.before` field, which is now annotated as `AnyStr | None`.

**Comment by pradiptama** [comment]
I think this is my side issue that we are using pexpect 4.8. Thanks for looking into this. I will close this issue.
