### ISSUE TITLE
Tornado module for Python 2.7 broken locally in tests

### ISSUE THREAD

**Issue by ddfisher** [python/typeshed#114]
Running with Python 3.5.1 on OS X, I get:
```
$ python3 runtests.py
running mypy --python-version 3.5 # with 243 files
running mypy --python-version 3.4 # with 243 files
running mypy --python-version 3.3 # with 229 files
running mypy --python-version 3.2 # with 228 files
running mypy --python-version 2.7 # with 330 files
third_party/2.7/sqlalchemy/sql/base.pyi:4: note: In module imported here,
third_party/2.7/sqlalchemy/engine/strategies.pyi:6: note: ... from here:
third_party/2.7/tornado/util.pyi:1: error: Duplicate module named '.util'
--- exit status 1 ---
```

**Comment by gvanrossum** [comment]
You should run it as follows:
```
python3 runtests.py -x sqlalchemy
```
There's still something wrong with the sqlalchemy stubs. Strange though that it also complains about tornado in this case.

**Comment by ddfisher** [comment]
Do you think it's worth putting a script in the repo which runs `runtests.py` with the same flags as CI? (And then making CI use that script, obviously.)

**Comment by gvanrossum** [comment]
No, we should fix the sqlalchemy stubs.

On Fri, Mar 11, 2016 at 4:34 PM, David Fisher <notifications@github.com>
wrote:

> Do you think it's worth putting a script in the repo which runs
> runtests.py with the same flags as CI? (And then making CI use that
> script, obviously.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/typeshed/issues/114#issuecomment-195616704>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
Done in 4f483dc314e9ae5ad5fe141a1bc6de500213c836.
