### ISSUE TITLE
Drop support for 3.2

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#1145]
Typing recently dropped support for Python 3.2 (python/typing#374) and mypy only supports 3.3 and up. Not sure about pytype and PyCharm. The last release of the 3.2 series was in October 2014 and pip and setuptools don't support it.

Concretely, I propose:
- We stop testing against 3.2 in Travis
- We don't require 3.2 behavior to be supported in new stubs (e.g., functions added in 3.3 don't need a version_info check).
- We don't actively remove existing version checks for 3.2. Removing them is fine as part of a larger refactoring.

#1144 is an example of a PR where supporting 3.2 would complicate the stub needlessly.

**Comment by gvanrossum** [comment]
Sounds good. I think we should drop 4.2 completely for mypy too.

**Comment by gvanrossum** [comment]
We debated this and we will do it for mypy and typeshed.

**Comment by gvanrossum** [comment]
Make it so!

**Comment by JelleZijlstra** [comment]
I can submit the typeshed PR when I get a chance.
