### ISSUE TITLE
ProtocolError when installing types-requests

### ISSUE THREAD

**Issue by alexharv074** [python/typeshed#11450]
Our build in a project that installs `types-requests` started failing last night and with an error message like this:

<img width="1375" alt="Screenshot 2024-02-19 at 12 12 25 pm" src="https://github.com/python/typeshed/assets/2305330/e97a084e-99dc-46f3-8612-0ea170df44db">

Our requirement.txt file has
```
autopep8
dohq-artifactory
flake8
ipdb
mypy
pre-commit
pycodestyle
pylint
pytest
pytest-cov
pytest-responsemock
semver
setuptools
sceptre
twine
types-PyYAML
types-requests
types-setuptools
mypy-boto3-cloudformation
mypy-boto3-codeartifact
```

Has anyone seen this before?

**Comment by hauntsaninja** [comment]
This is unrelated to types-requests. It's between whatever index you're using (if not upstream PyPI) and pip

**Comment by alexharv074** [comment]
@hauntsaninja We are however using upstream PyPI. I really just wanted to know if others are experiencing the same issue and if anyone knows what the root cause could be. So far as we know, nothing has changed on our side.
