### ISSUE TITLE
sqlite3 connect, Connection missing Python3.12 `autocommit` flag

### ISSUE THREAD

**Issue by gwk** [python/typeshed#11466]
In 3.12 `sqlite3.Connection` and the corresponding `connect` function gained a new `autocommit` parameter which is a three-valued flag: True | False | LEGACY_TRANSACTION_CONTROL. This is currently missing from typeshed.

**Comment by hauntsaninja** [comment]
Thanks, PR welcome! (Looks like signature is not available at runtime, so stubtest doesn't detect this)
