### ISSUE TITLE
Nuisance `TarFile.extract[all]` deprecation warning in type checkers

### ISSUE THREAD

**Issue by layday** [python/typeshed#11472]
The generalised `TarFile.extract[all]` deprecation warning when it is called without a `filter` argument or with `filter` being `None` encourages adopting a sub-standard workaround in preference to enforcing a filter systematically throughout a code base or for all `extract[all]` calls of a `TarFile`, e.g. by assigning `extraction_filter` on the `TarFile` instance or subclassing `TarFile` as we're doing [here](https://github.com/pypa/build/blob/main/src/build/_compat/tarfile.py).  Satisfying the deprecation warning by passing `filter` to `extract[all]` also means that each call would have to be Python version-gated or wrappers would have to be created for the pair of `extract` and `extractall` as older Python versions do not have a `filter` parameter and the initial implementation was broken for symlinks, meaning that we cannot simply rely on `data_filter` being present, even if that were to be type-checkable.

**Comment by JelleZijlstra** [comment]
Thanks. You make a good point that the filter can also be set on the class, making it difficult to avoid the deprecation warning from type checkers. I removed the `@deprecated` in #11476.
