### ISSUE TITLE
Missing stubs in Python 2.7 standard library 

### ISSUE THREAD

**Issue by matthiaskramm** [python/typeshed#1147]
C extensions:

- [ ] _abcoll
- [ ] _sysconfigdata
- [ ] copy_reg
- [ ] encodings
- [ ] sre_compile
- [ ] sre_constants
- [ ] sre_parse

Standard library (`*.py`) modules:

- [ ] Bastion
- [x] CGIHTTPServer
- [ ] DocXMLRPCServer
- [ ] MimeWriter
- [x] SimpleHTTPServer
- [ ] SimpleXMLRPCServer
- [ ] _LWPCookieJar
- [ ] _MozillaCookieJar
- [ ] _abcoll
- [ ] _osx_support
- [ ] _pyio
- [ ] _strptime
- [ ] _threading_local
- [ ] aifc
- [ ] antigravity
- [ ] anydbm
- [ ] audiodev
- [ ] bdb
- [ ] cgitb
- [ ] chunk
- [ ] codeop
- [ ] copy_reg
- [ ] dbhash
- [ ] dircache
- [ ] dumbdbm
- [ ] dummy_thread
- [ ] dummy_threading
- [x] formatter
- [ ] fpformat
- [ ] htmllib
- [ ] ihooks
- [ ] imaplib
- [ ] imghdr
- [ ] imputil
- [ ] macpath
- [ ] macurl2path
- [ ] mailbox
- [ ] mailcap
- [ ] mhlib
- [ ] mimify
- [ ] modulefinder
- [ ] multifile
- [ ] mutex
- [ ] netrc
- [ ] new
- [ ] nntplib
- [x] ntpath
- [ ] nturl2path
- [ ] os2emxpath
- [ ] pickletools
- [ ] popen2
- [ ] poplib
- [ ] posixfile
- [ ] pty
- [x] pydoc
- [ ] rexec
- [ ] sched
- [x] sets
- [ ] sgmllib
- [ ] smtpd
- [ ] sre
- [ ] sre_compile
- [ ] sre_constants
- [ ] sre_parse
- [ ] statvfs
- [ ] stringold
- [ ] sunaudio
- [ ] this
- [ ] toaiff
- [ ] user
- [ ] whichdb
- [ ] xmllib
- [x] xmlrpclib

**Comment by Solumin** [comment]
#1166 added ntpath, macpath and os2emxpath

**Comment by srittau** [comment]
Closing this as 2.7 is at end-of-life. While we still support 2.7, I don't think we strive to complete 2.7 stubs.
