### ISSUE TITLE
Logger.makeRecord stub should have a return type

### ISSUE THREAD

**Issue by lvu** [python/typeshed#1153]
In `typeshed/stdlib/2and3/logging/__init__.pyi`, `.makeRecord()` is declared with ` -> None`, which is obviously incorrect; probably, ` -> LogRecord` should be specified.

**Comment by JelleZijlstra** [comment]
Feel free to open a pull request. This should be a simple fix.

**Comment by lvu** [comment]
It's already fixed in master. Pity that's master doesn't work with mypy 0.501 and mypy master doesn't work at all :(

**Comment by gvanrossum** [comment]
Can you file a separate issue about the problems you are having with master? (Please update to the latest and be sure to run git submodule update.

**Comment by lvu** [comment]
@gvanrossum  Sorry, cannot reproduce it anymore. Probably is was due to mypy/typeshed mismatch.
