### ISSUE TITLE
Text vs Union[str, Text] arguments question

### ISSUE THREAD

**Issue by euresti** [python/typeshed#1158]
So I've been moving stuff into 2and3 and trying to make it unicode compatible.  There are many functions that in python2 take `str` but allow `unicode`, while on python 3 these only allow `str`.  For example `timeit.timeit`

Currently in the code some of these functions are typed as `Text` basically asuming that the `str`  to `Text` promotion will happen. Other places, e.g `timeit`, use `Union[str, Text]`.  Are there benefits to one over the other?  Should there be a standard?

**Comment by gvanrossum** [comment]
Not sure. I've been using Text, given that it's the cleanest and doesn't require fixing up when we leave PY2 behind (I wouldn't leave `Union[str, Text]` in pure-PY3 code).

**Comment by euresti** [comment]
Does PyCharm handle str -> Text promotion the same way?  I know PyCharm sometimes tells me to call something with a unicode literal.  But that may have been some versions ago?

**Comment by gvanrossum** [comment]
I don't know, I haven't used PyCharm much (or at all) lately. Maybe @vlasovskikh Can find the answer for you. It's possible that this promotion is actually a mypy feature, not in the PEP 484 spec. (Though maybe we should add it there? It seems useful.)

**Comment by vlasovskikh** [comment]
`typing.Text` on PY2 is an alias for `unicode`. After a long discussion on how to handle str/bytes/unicode/Text in PY2 and PY3 https://github.com/python/typing/issues/208 PyCharm has switched to `str` -> `unicode` promotion for PY2. See the corresponding PyCharm issue https://youtrack.jetbrains.com/issue/PY-20407.

**Comment by euresti** [comment]
Perfect, `Text` it is!
