### ISSUE TITLE
Issue Label Reorganization

### ISSUE THREAD

**Issue by srittau** [python/typeshed#11605]
We have 30 labels in total, and they are in need of a bit of a cleanup. Looking through the list, here are the current labels with my comments and suggested action:

* deferred – recently discussed and quite useful → keep
* dependencies – used by renovate → keep
* DO-NOT-MERGE – Can't we mark those PRs as drafts? →remove
* docs – Documentation isn't a crucial part of typeshed, I suggest merging this with the project label (see below) → merge into "project"
* feature-tracker – Useful → keep
* good-first-issue – Used quite a bit in the past and might still be useful, although I see a bit of an overlap with "help wanted"→merge into "help wanted"
* help wanted – Useful, especially for external contributors→keep
* implementation-pending – Basically a special case of "deferred", I don't think we need a separate label→merge into "deferred"
* inexpressable – Useful label to apply when closing issues; can be revisited from time to time or used to find missing type system features→keep
* needs decision→rarely, I don't this this adds much→remove
* priority-high→rarely used, but I can see it being useful from time to time
* project→This was intended for build, CI, test infrastructure related issues, i.e. the technical side outside of the stubs itself, although the current naming doesn't distinguish it very well from project-discussion→rename to "infrastructure"
* project-discussion→This was more intended for project policy discussions and organizatorial stuff →rename to "policies" or "project-policies"
* question →Rarely used; typing's discussion forum is probably a better place for questions about using the stubs →remove
* regression → Still useful to me→rename to "type-regression"
* removal→Useful to keep track of pending removals→keep, but rename to type-removal
* size-*→Not often tagged, also not very easy to judge, and of limited usefulness nowadays→remove
* stubsabot→Use by our favorite bot→keep
* topic-* →Useful for grouping topics that need special attention, but I think a few aren't pulling their weight anymore→keep most, remove topic-redis and topic-xml
* type-*→Still useful to categorize the type of problem, although types-stubs-request is more of historical significance as we usually don't keep those open, still useful to tag →keep

Let's also use the dashes for separating words. They are not needed, and we use them inconsistently. Also, we could change prefixes (type-, topic-) to use colons instead. And add more prefixes.

----

This would be my suggested new list (I'll update it trying to reflect the current discussion consensus):

* bot: dependencies
* bot: stubsabot
* complexity: high
* help wanted (description: "An actionable problem of low to medium complexity where a PR would be very welcome")
* priority: high
* priority: regression
* project: feature tracker
* project: infrastructure
* project: policy
* reason: inexpressable
* status: deferred
* status: DO NOT MERGE
* status: needs decision
* topic: asyncio
* topic: io
* topic: tkinter
* type: false negative
* type: false positive
* type: improvement
* type: incomplete
* type: removal
* type: stubs request

**Comment by AlexWaygood** [comment]
Thanks! I agree with most of your ideas. Some specific points (anything you proposed above that I haven't specifically responded to below, I agree with):

- We don't have many PRs labelled with "needs decision" currently, but in the past I've found it useful to mark PRs where it's clear there's no consensus right now among the maintainers, and we're having trouble deciding on whether to proceed with it or to close it. That's useful if you're going through the open PRs to see whether there are any that can be easily merged or closed.
- DO-NOT-MERGE: Agree that there are other ways of making clear that a PR should not be merged, but also, is there any particular harm in keeping this? If you really don't want something to be merged, I think it's useful to signal it as loudly as possible. Marking something as draft isn't _necessarily_ an unambiguous signal that you don't consider something mergeable yet -- I've seen this cause confusion in other projects, when maintainers have marked contributor PRs as "ready for review" and merged them, to the surprise of the contributors.
- I agree that the current `size-*` are maybe not particularly helpful. However, it's also the case that we've received feedback in the past that it's hard for new contributors to tell which of our open issues are in need of drive-by contributions, and which are difficult problems that might need a substantial amount of work and/or discussion. The `help wanted` label is good for indicating problems where contributions are welcome, but maybe we do need some way of indicating the opposite of that -- problems which are difficult, and maybe unsuited for drive-by contributors. `difficult`? `hard`?
- Not sure we need all the `type-*` ones:
  - `types-stubs-request` -- we usually answer the question (usually with "yes"), and then just close the issue. Not sure we really need this label.
  - `type-improvement` -- not sure it really tells us much if an issue has this label. Surely any PR to typeshed hopes to improve something?
  - `type-regression` -- is this needed? Is it important to distinguish regressions from other bugs on our issue tracker? I feel like we'd take the same approach to fixing them as we would with other bugs.

**Comment by AlexWaygood** [comment]
It feels slightly odd quote-replying to my own message here, but I see you responded by editing your responses into my message rather than posting a new reply 😄

> In a way we want help with all issues that are tagged with one of the `type:` labels. Maybe instead of `help wanted` we keep the `good-first-issue` label?

I've had pretty mixed experiences with the `good-first-issue` label, both in typeshed and elsewhere. In my experience, it tends to attract people who are very new to Python/programming in general; these contributors often need a lot of coaching. We're a good entry-level project for people new to typing (unlike, say, mypy, which isn't), but I'm not sure we're a great entry-level project for people new to Python/programming altogether. I've had much better experiences with the `help wanted` label.

> * improvement is badly named. It's basically an "other stub problems" category. As such I think it's still useful, but a better name would be welcome.

But surely "other stub problems" can be equally well conveyed by the issue not having any label at all?

> * regression is useful as a kind of priority marker. Maybe it'd make sense to name it "priority: regression"?

That makes sense to me!

**Comment by srittau** [comment]
Yikes. Misclicked and destroyed Alex's response. Imagine this response being between the two messages by Alex above.

----

> - We don't have many PRs labelled with "needs decision" currently, but in the past I've found it useful to mark PRs where it's clear there's no consensus right now among the maintainers, and we're having trouble deciding on whether to proceed with it or to close it. That's useful if you're going through the open PRs to see whether there are any that can be easily merged or closed.
> - DO-NOT-MERGE: Agree that there are other ways of making clear that a PR should not be merged, but also, is there any particular harm in keeping this? If you really don't want something to be merged, I think it's useful to signal it as loudly as possible. Marking something as draft isn't _necessarily_ an unambiguous signal that you don't consider something mergeable yet -- I've seen this cause confusion in other projects, when maintainers have marked contributor PRs as "ready for review" and merged them, to the surprise of the contributors.

Ok, I've added those two back.

> - I agree that the current `size-*` are maybe not particularly helpful. However, it's also the case that we've received feedback in the past that it's hard for new contributors to tell which of our open issues are in need of drive-by contributions, and which are difficult problems that might need a substantial amount of work and/or discussion. The `help wanted` label is good for indicating problems where contributions are welcome, but maybe we do need some way of indicating the opposite of that -- problems which are difficult, and maybe unsuited for drive-by contributors. `difficult`? `hard`?

In a way we want help with all issues that are tagged with one of the `type:` labels. Maybe instead of `help wanted` we keep the `good-first-issue` label?

> - Not sure we need all the `type-*` ones:
>   - `types-stubs-request` -- we usually answer the question (usually with "yes"), and then just close the issue. Not sure we really need this label.
>   - `type-improvement` -- not sure it really tells us much if an issue has this label. Surely any PR to typeshed hopes to improve something?
>   - `type-regression` -- is this needed? Is it important to distinguish regressions from other bugs on our issue tracker? I feel like we'd take the same approach to fixing them as we would with other bugs.

- stubs-request has 46 closed issues. I wouldn't want to lose this information. And while we usually don't keep these requests open anymore, I think it's still useful to tag those issues when closing.
- improvement is badly named. It's basically an "other stub problems" category. As such I think it's still useful, but a better name would be welcome.
- regression is useful as a kind of priority marker. Maybe it'd make sense to name it "priority: regression"?

**Comment by AlexWaygood** [comment]
In a way we want help with all issues that are tagged with one of the type: labels. Maybe instead of help wanted we keep the good-first-issue label?

I've had pretty mixed experiences with the `good-first-issue` label, both in typeshed and elsewhere. In my experience, it tends to attract people who are very new to Python/programming in general; these contributors often need a lot of coaching. We're a good entry-level project for people new to typing (unlike, say, mypy, which isn't), but I'm not sure we're a great entry-level project for people new to Python/programming altogether. I've had much better experiences with the `help wanted` label.

        improvement is badly named. It's basically an "other stub problems" category. As such I think it's still useful, but a better name would be welcome.

But surely "other stub problems" can be equally well conveyed by the issue not having any label at all?

        regression is useful as a kind of priority marker. Maybe it'd make sense to name it "priority: regression"?

That makes sense to me!

**Comment by srittau** [comment]
> But surely "other stub problems" can be equally well conveyed by the issue not having any label at all?

But no label is not necessarily related to problematic stubs. It can be anything, a question, something project related, some off-topic comment, something that fits in no other category.

**Comment by picnixz** [comment]
I'm not a contributor to this repo, but there is one single reason why at Sphinx I added the "DO NOT MERGE" label although I could have the draft: it's because I can visually see with a big flashy red that this PR is something I don't want to merge now for whatever reason (and also so that people know that it's more than just being a draft since sometimes converting it to draft makes the PR seem "stale/abandonned").

**Comment by AlexWaygood** [comment]
> > But surely "other stub problems" can be equally well conveyed by the issue not having any label at all?
> 
> But no label is not necessarily related to problematic stubs. It can be anything, a question, something project related, some off-topic comment, something that fits in no other category.

Maybe... it still feels too broad/vague to me to be a particularly useful label. But maybe that's just me :)

**Comment by srittau** [comment]
> I've had pretty mixed experiences with the `good-first-issue` label, both in typeshed and elsewhere. In my experience, it tends to attract people who are very new to Python/programming in general; these contributors often need a lot of coaching. We're a good entry-level project for people new to typing (unlike, say, mypy, which isn't), but I'm not sure we're a great entry-level project for people new to Python/programming altogether. I've had much better experiences with the `help wanted` label.

Makes sense. So, drop "good-first-issue", keep "help wanted",  and mostly apply it to issues with low to medium complexity? Then, do we need to add "high complexity" (or similar)?

**Comment by AlexWaygood** [comment]
> Makes sense. So, drop "good-first-issue", keep "help wanted", and mostly apply it to issues with low to medium complexity? Then, do we need to add "high complexity" (or similar)?

Yeah, that makes sense to me

**Comment by srittau** [comment]
I've incorporated this into the "consensus list" in the first post. Also added the "low to medium" complexity wording to the "help wanted" description there.

**Comment by picnixz** [comment]
Btw, when I first saw the "good-first-issue" label, for me it was "it's a good issue that the author found" and not "this is good for *you*, contributor". So I think the "help wanted" is less confusing (this one, I understand it as "plz hlp us" and is generally for any kind of complexity; if the problem is too hard I usually add an "expert" label but if you describe the help wanted as you did it should be fine).

**Comment by AlexWaygood** [comment]
> Also added "categories" "bot: " and "status: " to the remaining labels. I think this will make the rather large list cleaner to look at.

We might not want to rename the `help wanted` label, as it is special-cased by GitHub. For people who have starred the repository, they'll see on their GitHub dashboard when a `help wanted` label is added to an issue. Here's an example I saw on my dashboard a few days ago:

![image](https://github.com/python/typeshed/assets/66076021/954c92f2-df3b-4a29-a4c5-10a1ff3873f9)

**Comment by Avasam** [comment]
`good first issue` is also a special label https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels

I've seen it used to find projects to contribute to during OSS pushes (like "hackathons", "hacktober", and such). Although we have `good-first-issue` (with dashed), so 🤷

**Comment by srittau** [comment]
Are there any more comments on the list in the first post? Otherwise I would implement the changes in a day or two.

**Comment by srittau** [comment]
Done. I've also updated some of the colors, mostly using the same color or same shade for the same "prefix".

I also kept "topic: redis" for now, considering the amount of open issues.

Please leave a comment if there are changes you don't like or additional suggestions you have!

**Comment by srittau** [comment]
One additional though: Maybe rename the unspecific "type:" prefix to "stubs:" to make it clearer that these labels apply specifically to issues with stubs?

**Comment by srittau** [comment]
> One additional though: Maybe rename the unspecific "type:" prefix to "stubs:" to make it clearer that these labels apply specifically to issues with stubs?

Done that as well.

**Comment by Avasam** [comment]
> `good first issue` is also a special label [docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels)

For posterity, just because I found more info about it:
![image](https://github.com/python/typeshed/assets/1350584/09322bca-4d93-4c2f-93db-d3b490265c6c)

https://github.com/python/typeshed/contribute
