### ISSUE TITLE
Typeshed for WebOb is missing `webob.compat` module

### ISSUE THREAD

**Issue by fmigneault** [python/typeshed#11663]
For example, the following is valid `from webob.compat import cgi_FieldStorage`, but is flagged by IDEs such as PyCharm as missing from the stubs.

![image](https://github.com/python/typeshed/assets/19194484/fb7d964a-96cb-4c8c-b5e5-c0b76a9b7818)

Other stubs from `webob` are found accordingly.

**Comment by AlexWaygood** [comment]
PR welcome!

**Comment by AlexWaygood** [comment]
On second thought, though: are you _sure_ the `.compat` submodule is meant to be public API? Are you meant to be importing things from `webob.compat`, as an end user? It might be a regresion in user experience if IDEs started suggesting this module in autocompletions if it's not intended to be public API. It seems like it might be mainly a module providing compatibility for Python 2? https://github.com/Pylons/webob/blob/0a69ff129df2da9bba347981c4ef632a8b7c2ddb/src/webob/compat.py#L12

**Comment by JelleZijlstra** [comment]
Our general policy is to add private objects when users ask for them, so I think we should include this. I agree it's questionable whether it's a good idea to use this module in user code.

**Comment by fmigneault** [comment]
The specific situation I have is that I employ `request.POST.get("file")` for an endpoint that supports uploading a file, and that results into this  `cgi_FieldStorage` object. Without the explicit type cast with `cgi_FieldStorage`, I get more linting errors and missing properties than if I omitted it. I agree in hiding away some magic that could happen to hide interfaces of `_cgi_FieldStorage` (note underscore), but the methods (notably `read_multi` for multipart content) are important interfaces for my use case.

What would be the recommended strategy to define this type, since it mostly derives from https://github.com/python/typeshed/blob/main/stdlib/cgi.pyi that is already defined (except the extra `read_multi`) ?

**Comment by Daverball** [comment]
@fmigneault  I would suggest not doing this and instead use the dummy type `webob.request._FieldStorageWithFile` I created for this:

```python
if TYPE_CHECKING:
    from webob.request import _FieldStorageWithFile
```

It's worth noting that the cgi Module is deprecated and the next version of WebOb will likely replace this with a different object located somewhere else.

Apart from `cgi_FieldStorage` the entire `compat` module has already been removed upstream.
