### ISSUE TITLE
`typing_extensions.deprecated` decorator should take a `LiteralString`

### ISSUE THREAD

**Issue by DetachHead** [python/typeshed#11699]
the `deprecated` decorator is intended for type checkers to be able to show the deprecation message to the user, which is only possible if the string is a [`LiteralString`](https://peps.python.org/pep-0675/) (ie. known at compiletime)

**Comment by JelleZijlstra** [comment]
Sure, feel free to send a PR. This should then also be changed in CPython and typeshed.

**Comment by JelleZijlstra** [comment]
> Sure, feel free to send a PR. This should then also be changed in CPython and typeshed.

Sorry I thought this issue was on typing-extensions. Typeshed is the most important place to change it; the runtime annotations don't really matter here.
