### ISSUE TITLE
Update to `types-requests` to `2.31.0.20240402` makes my CI to fail

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#11701]
```
 /home/runner/work/djangorestframework-stubs/djangorestframework-stubs/tests/typecheck/test_fields.yml:61: 
E   pytest_mypy_plugins.utils.TypecheckAssertionError: Output is not expected: 
E   Actual:
E     ../../opt/hostedtoolcache/Python/3.11.8/x64/lib/python3.11/site-packages/requests-stubs/cookies.pyi:40: error: Unused "type: ignore" comment (diff)
```

Link: https://github.com/typeddjango/djangorestframework-stubs/actions/runs/8516700456/job/23326129351?pr=570
PR: https://github.com/typeddjango/djangorestframework-stubs/pull/570
Configuration: https://github.com/typeddjango/djangorestframework-stubs/blob/master/mypy.ini

**Comment by srittau** [comment]
The latest version contains changes from #11656, which exclusively annotates `RequestsCookieJar`.

**Comment by JelleZijlstra** [comment]
@sobolevn I don't think you can rely on something like this working reliably. Typeshed might add a `# type: ignore` to silence a different type checker or a mypy configuration option that you don't use.

**Comment by AlexWaygood** [comment]
It's been reported before that the `pytest-mypy-plugins` sometimes causes mypy errors to "leak" out from typeshed (even though mypy should suppress all typing errors that come from the stdlib or a `site-packages` stubs package when it's analysing user code). E.g. https://github.com/python/typeshed/issues/7503. This looks like the same thing, and I agree with Jelle that this wasn't really a regression from us -- it was really just a latent bug in either mypy or `pytest-mypy-plugins` that was newly exposed.

This time it happened to be easily fixable from our end, though :-)
