### ISSUE TITLE
Missing backwards compatibility module for pyflakes

### ISSUE THREAD

**Issue by tkiss80** [python/typeshed#11736]
Hi!

I've recently noticed in the PyCharm IDE (which uses the typeshed stubs) that it marks the following as a problem:

```python
from pyflakes.scripts import pyflakes
```

It says it cannot find the _scripts_ module inside _pyflakes_. It is true that according the Git history, the pyflakes project moved the _pyflakes.scripts.pyflakes_ module to _pyflakes.api_: [link](https://github.com/PyCQA/pyflakes/commit/7bd964f152bcd9bdc44aea1afeac8a879c66d61a)

However, it seems that later they added back the module for backwards compatibility, this time only importing the contents of the file from its new place: [link](https://github.com/PyCQA/pyflakes/commit/21bb75dc5fef6ae9e1b35b5b85c8e163e990a4fe)

This is the current version: [link](https://github.com/PyCQA/pyflakes/blob/main/pyflakes/scripts/pyflakes.py)

Would it be possible to update the pyflakes stubs according to above?

Thanks,
Tamas

**Comment by srittau** [comment]
PR welcome to add this module to our stubs.

**Comment by tkiss80** [comment]
I’ll look into it, thanks!
