### ISSUE TITLE
ModuleNotFoundError: No module named 'types_python_dateutil'

### ISSUE THREAD

**Issue by stamenminkov** [python/typeshed#11746]
Hi, I'm trying to install [types-python-dateutil](https://pypi.org/project/types-python-dateutil/) via [EasyBuild](https://easybuild.io/), however it fails on the pip sanity check with the following message:

```
ModuleNotFoundError: No module named 'types_python_dateutil'
```

This usually happens when the python module name is not provided accordingly, as the sanity check step tests if all components and dependencies can be loaded fine.

Is that the correct name of the module? When checking inside the package it indeed seems to be the one [`types_python_dateutil.egg-info` folder, etc.], however the installation still fails :/

**Comment by JelleZijlstra** [comment]
Stub packages do not provide any module that can be imported from Python, only stub files (which will show up under the name `python_dateutil-stubs` in your virtual environment). This sounds like a bug in your build tool.
