### ISSUE TITLE
[pyinstaller] Support v6.6

### ISSUE THREAD

**Issue by bersbersbers** [python/typeshed#11750]
pyinstaller v6.6 added `--optimize`, see https://pyinstaller.org/en/stable/CHANGES.html#features

**Comment by srittau** [comment]
Thanks, we always accept PRs that update our stubs to the latest implementation version. That said, I'm going to close this issue, as stubsabot will automatically create a pull request tonight, which we keep as long as the stubs were not updated.

**Comment by srittau** [comment]
For reference: #11751
