### ISSUE TITLE
Add "checker scripts" to third-party stubs

### ISSUE THREAD

**Issue by srittau** [python/typeshed#11760]
We've just added a check to check_consistent.py to assert that the modules from stubs/setuptools/setuptools/_distutils are re-exported from stubs/setuptools/distutils. Maybe it would make sense to move such third-party-stubs-specific checks to the tests directory if the stubs, and call these check scripts from check_consistent:

* Keeps stuff belonging to each other closer together.
* We could limit calling it if the stubs in question were changed.

**Comment by Akuli** [comment]
IMO this seems overly complicated for 20 lines of code that handle one very special case.

**Comment by srittau** [comment]
Indeed. This was more of a thought for the future if such checks should become more common. I think we had similar checks before for other libraries, but I'm not completely sure.

**Comment by JelleZijlstra** [comment]
I agree with Akuli this is overkill if it's only for setuptools. We can set up this abstraction if and when we need it in more places.

I think in the past we had checks that `__builtin__.pyi` and `builtins.pyi` had to be consistent (they both had to exist for Python 2 reasons and couldn't be symlinked for Windows reasons), but I don't recall any other checks for specific third-party libraries.

**Comment by srittau** [comment]
I'm closing this for now, but it's something to keep in mind, should we have more checks at some point.
