### ISSUE TITLE
Consider changing configparser.RawConfigParser.write's fp argument to some standard IO type, e.g. TextIO

### ISSUE THREAD

**Issue by eskultety** [python/typeshed#11776]
The [currently declared type](https://github.com/python/typeshed/blob/0445d74489d7a0b04a8c64a5a349ada1408718a9/stdlib/configparser.pyi#L197) is a typeshed's own private `SupportsWrite` protocol type constrained to string. Looking at the official documentation of configparser's [`write`](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.write) it states that

> Write a representation of the configuration to the specified [file object](https://docs.python.org/3/glossary.html#term-file-object), which must be opened in text mode (accepting strings)

so IIUC it should be appropriate to change the type hint to something that matches that statement, e.g. `TextIO`.
The reason for this suggestion is that with type hinting enabled it's impossible to correctly subclass `ConfigParser` and override the `write` method due to mismatching types leading to `@no_type_check`. Note that importing from a "private" `_typeshed` module is not a solution.

**Comment by JelleZijlstra** [comment]
Using `TextIO` would cause false positives for users using IO types that do not inherit from `TextIO`. "File objects" are very heterogeneous in practice, and protocols are the best way to describe them.

You can define the protocol in your own code, or import it from [useful_types](https://github.com/hauntsaninja/useful_types/blob/364c7cdd21d239ddde457c9247d103752fb10fd5/useful_types/__init__.py#L245).

**Comment by srittau** [comment]
We tend to annotate input types as narrow as possible in typeshed. Use of the `IO` classes (which predate the introduction of protocols) is discouraged in these cases, since they are much too broad.
