### ISSUE TITLE
`os.chmod()` on Windows doesn't follow symlinks by default

### ISSUE THREAD

**Issue by nineteendo** [python/typeshed#11774]
I just read https://github.com/python/cpython/issues/113188 which states the following:

> os.chmod() still does not follow symlinks by default on Windows

But the stubs say otherwise:

https://github.com/python/typeshed/blob/0445d74489d7a0b04a8c64a5a349ada1408718a9/stdlib/os/__init__.pyi#L750

We should just use an ellipsis here:

```python
def chmod(path: FileDescriptorOrPath, mode: int, *, dir_fd: int | None = None, follow_symlinks: bool = ...) -> None: ...
```

- PR: https://github.com/python/typeshed/pull/11775

**Comment by srittau** [comment]
Then the Python docs are wrong and should be fixed first: https://docs.python.org/3/library/os.html#os.chmod.

> os.chmod(path, mode, *, dir_fd=None, follow_symlinks=True)

**Comment by nineteendo** [comment]
It has already been fixed on the main branch: https://docs.python.org/3.13/library/os.html#os.chmod

> The default value of *follow_symlinks* is `False` on Windows.

**Comment by srittau** [comment]
Semi-fixed. It still says `True` in the signature, only when reading the low-contrast box on the next screen page, it states the correct default. Also, in older docs versions, it doesn't state that follow_symlinks doesn't exist/isn't supported on Windows.

**Comment by nineteendo** [comment]
> Also, in older docs versions, it doesn't state that follow_symlinks doesn't exist/isn't supported on Windows.

No, but `os.supports_follow_symlinks` exists for that purpose.
