### ISSUE TITLE
Change `logging.lastResort`

### ISSUE THREAD

**Issue by edyounis** [python/typeshed#11770]
The [last resort handler in logging](https://github.com/python/typeshed/blob/7c8e82fe483a40ec4cb0a2505cfdb0f3e7cc81d9/stdlib/logging/__init__.pyi#L590) should be a generic `Handler` rather than a stream handler.

In the Python logging documentation, it refers to the `lastResort` handler as a handler in one sentence and a `StreamHandler` in another. It is set to a `StreamHandler` by default, but setting it to another type of `Handler` works without issue in practice.

**Comment by srittau** [comment]
Makes sense, PR welcome!
