### ISSUE TITLE
OrderedDict is not resolved correctly under @dataclasses.dataclass

### ISSUE THREAD

**Issue by gkirchou** [python/typeshed#11793]
`popitem` in [OrderedDict](https://github.com/python/cpython/blob/d8f350309ded3130c43f0d2809dcb8ec13112320/Lib/collections/__init__.py#L165) has a different interface than [Dict](https://github.com/python/cpython/blob/d8f350309ded3130c43f0d2809dcb8ec13112320/Objects/dictobject.c#L4337).

In a nutshell:
- OrderedDict: `def popitem(self, last=True):`
- Dict: `def popitem(self):`

---

When creating the `OrderedDict` directly, `popitem` interface is resolved correctly as it's in [collections/__init__.pyi](https://github.com/python/typeshed/blob/57f3dcac8dbed008479b251512975901a0206deb/stdlib/collections/__init__.pyi#L348):

```python
def test_ordereddict_popitem(od: OrderedDict[int, int]) -> None:
  assert_type(od.popitem(), tuple[int, int])
  assert_type(od.popitem(True), tuple[int, int])
```

When creating the `OrderedDict` under an object which accepts `Dict`, it works too:

```python
def test_ordereddict_popitem_in_object(od: OrderedDict[int, int]) -> None:
  class object:
    d: dict[int, int]

  o = object()
  o.d = od

  # reveal_type(o.d)
  # `OrderedDict` for runtime
  # `collections.OrderedDict[builtins.int, builtins.int]` for mypy

  assert_type(o.d.popitem(), tuple[int, int])
  assert_type(o.d.popitem(True), tuple[int, int])
```

However, when creating the `OrderedDict` under a dataclass object which accepts `Dict`, it stops working:

```python
def test_ordereddict_popitem_in_dataclass(od: OrderedDict[int, int]) -> None:
  @dataclasses.dataclass
  class dataclassObject(object):
    d: dict[int, int]

  o = dataclassObject(d=od)

  # reveal_type(o.d)
  # `OrderedDict` for runtime
  # `builtins.dict[builtins.int, builtins.int]` for mypy

  assert_type(o.d.popitem(), tuple[int, int])
  assert_type(o.d.popitem(True), tuple[int, int])
```

This returns errors:

```
Too many arguments for "popitem" of "MutableMapping"  [call-arg]
      assert_type(o.d.popitem(True), tuple[int, int])
                  ^~~~~~~~~~~~~~~~~
```

**Comment by gkirchou** [comment]
I made a PR to demo this: https://github.com/python/typeshed/pull/11794/files

I also tried to fix by extending `popitem` in typing.pyi's [MutableMapping](https://github.com/python/typeshed/blob/57f3dcac8dbed008479b251512975901a0206deb/stdlib/typing.pyi#L658), but it doesn't work. I guess this may be related to dataclass's type resolution?

**Comment by JelleZijlstra** [comment]
This is not a bug in typeshed. When you access an attribute on a dataclass, type checkers use the declared type of the dataclass; they do not narrow the type further based on the exact arguments passed to the constructor. They perhaps could do that, but it seems only very rarely useful, and possibly unsafe under certain circumstances.
