### ISSUE TITLE
Adding support for xmlrpclib [Python 2.7]: Reassigning keywords

### ISSUE THREAD

**Issue by Solumin** [python/typeshed#1181]
I'm currently working on support for xmlrpclib. Current progress can be seen here: https://gist.github.com/Solumin/7ce81a761979072fb56186b5f280fd29

_Note:_ This passes all tests, both Pytype and Mypy.

There's one large flaw. xmlrpclib defines its own True and False constants:
https://github.com/python/cpython/blob/2.7/Lib/xmlrpclib.py#L295
It basically cheats and adds them directly to the module's dictionary, averting the whole issue with keywords. (It seems the Python 3000 version doesn't do this, thankfully.)

This causes problems when trying to type check a file. For example, try:
```python
import xmlrpclib

def foo(x):
  x.append(4)

def main(argv=()):
  foo([1, 2, 3])
  foo(xmlrpclib.False)
```
Pytype doesn't complain about xmlrpclib.False, but it obviously can't type check it, either.
Mypy throws an error: `KeyError: "Could not find builtin symbol 'module'.`

The obvious solution is adding `False = ...  # type: bool` to the file. Pytype allows this, but Mypy complains about assigning to a keyword.

What's the best way to encode xmlrpclib.True and xmlrpclib.False in the pyi file?

**Comment by matthiaskramm** [comment]
Played around with this for a while, as well, but even constructs like

```
True = True  # type: ignore
False = False  # type: ignore
```

don't seem to satisfy mypy.

**Comment by matthiaskramm** [comment]
But maybe this is for the best. I don't mind getting type errors for `xmlrpclib.True`, especially since that constant is the same as the canonical `True`. So I'd suggest just not putting those two constants into the stub.

**Comment by Solumin** [comment]
I think that might be the best solution. I do see a few uses of xmlrpclib.True on Github, though none of .False outside of xmlrpclib tests. It's not ideal, but in the worst case, users can just put `type: ignore` comments on it, if they're running Mypy.

**Comment by JelleZijlstra** [comment]
The reason for the mypy parse errors is presumably that mypy parses stubs using Python 3 syntax, and Python 3 syntactically disallows assignments to True/False.

I agree with Matthias that we should just skip these constants from the stub.

**Comment by Solumin** [comment]
That makes sense to me. I've updated xmlrpclib.pyi accordingly. Thanks!
