### ISSUE TITLE
pyinstaller: `Splash(text_pos=...)` accepts `None`

### ISSUE THREAD

**Issue by bersbersbers** [python/typeshed#11834]
`pyinstaller` generates `.spec` files with `text_pos = None`. Related:

https://github.com/python/typeshed/blob/7d56cd9a6cf6e0a4ea89c68d0397e197aff32cbe/stubs/pyinstaller/PyInstaller/building/splash.pyi#L27-L33

`tuple[int, int]` should be `tuple[int, int] | None`

**Comment by srittau** [comment]
PR welcome

**Comment by bersbersbers** [comment]
@srittau thanks, see #11835.
