### ISSUE TITLE
Cannot instantiate abstract class 'mmap' Python 3 only.

### ISSUE THREAD

**Issue by euresti** [python/typeshed#1184]
Running mypy (python 3) on 
```
import mmap

mm = mmap.mmap(-1, 0)
```
gives 
```
example.py:3: error: Cannot instantiate abstract class 'mmap' with abstract attributes '__contains__', '__iter__' and '__reversed__'
```

But `mmap.mmap` does not actually have those values anyway.  So it's not a matter of just adding those.

**Comment by gvanrossum** [comment]
Hm, this was added in #425 where the inheritance of Sequence[bytes] was replaced with inheritance of Iterable[bytes], Container[bytes], Sized, Reversible[bytes]. Maybe we should revert that part of that diff? (Though I'm not sure that mmap implements a full Sequence either?)
