### ISSUE TITLE
psutil's Process.wait timeout argument to be float

### ISSUE THREAD

**Issue by dpinol** [python/typeshed#11866]
Should timeout argument be a float instead of int like in subprocess?

https://github.com/python/typeshed/blob/main/stubs/psutil/psutil/__init__.pyi#L225
`def wait(self, timeout: int | None = None) -> int: ...`

https://github.com/python/typeshed/blob/main/stdlib/subprocess.pyi#L2549
`def wait(self, timeout: float | None = None) -> int: ...`

**Comment by srittau** [comment]
I haven't looked at psutil's implementation of `wait()`, but we've had this is issue fairly often. PR welcome.
