### ISSUE TITLE
Requests: missing type spec for `create_cookie`

### ISSUE THREAD

**Issue by rdegraaf-ncc3** [python/typeshed#11879]
There are a number of functions with no type specs in requests.cookies.  The one that's bugging me is `create_cookie` but I see several others in the source:

*   https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L32
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L33
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L34
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L59
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L60
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L61
* https://github.com/python/typeshed/blob/main/stubs/requests/requests/cookies.pyi#L62

**Comment by srittau** [comment]
Not all typeshed stubs are fully typed, but any improvements are welcome! That said, we don't keep issues about this open.
