### ISSUE TITLE
BeautifulSoup: incomplete type specs for "formatter"

### ISSUE THREAD

**Issue by rdegraaf-ncc3** [python/typeshed#11878]
A number of output-related methods in BeautifulSoup accept an argument named "formatter":

*   https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L298
* https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L305
* https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L309
* https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L311
* https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L313
* https://github.com/python/typeshed/blob/main/stubs/beautifulsoup4/bs4/element.pyi#L316

In all of these cases, the type spec given is "`str | Formatter`".  However, according to https://beautiful-soup-4.readthedocs.io/en/latest/#output-formatters, a formatter may be either one of two strings, a formatter function, *or `None`*.  Consequently, the type spec should be "`str | Formatter | None`".

**Comment by srittau** [comment]
We could also change `str` to `Literal` and explicitly list the accepted formatters. Any PRs welcome!
