### ISSUE TITLE
Deprecate `pathlib.Path.link_to` in typeshed as it was removed in Python 3.12

### ISSUE THREAD

**Issue by jzazo** [python/typeshed#11874]
Hi,

`pathlib.Path.link_to` was deprecated since Python 3.10 and scheduled for removal in Python 3.12.

Because typeshed has not deprecated the method, static annotators do not issue a warning. Can this be fixed? I am not sure how to create a PR that solves the [issue](https://github.com/python/typeshed/blob/3e3fd0dd86933214d903654c1e7057f25dba93fa/stdlib/pathlib.pyi#L225).

Originally reported to [pyright](https://github.com/microsoft/pyright/issues/7868).

The docs of the method:
```
Make the target path a hard link pointing to this path.

Note this function does not make this path a hard link to *target*, despite the implication of the function and argument names. The order of arguments (target, link) is the reverse of Path.symlink_to, but matches that of os.link.

Deprecated since Python 3.10 and scheduled for removal in Python 3.12. Use hardlink_to() instead.
```

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR that adds the `@typing_extensions.deprecated` decorator to this method.

**Comment by AlexWaygood** [comment]
fixed in https://github.com/python/typeshed/pull/11875, thanks for the PR!
