### ISSUE TITLE
types._Cell seems to not exist anymore

### ISSUE THREAD

**Issue by yoann9344** [python/typeshed#11901]
The built-ins stubs imports `types._Cell` ([here](https://github.com/python/typeshed/blob/main/stdlib/builtins.pyi#L34)). I don't find it anymore in `types.py` (from [3.8](https://github.com/python/cpython/blob/3.8/Lib/types.py) to [main](https://github.com/python/cpython/blob/main/Lib/types.py)).
Is it replaced by `types.CellType` ([here](https://docs.python.org/3/library/types.html#types.CellType)) ?

Maybe we should consider to replace the import. Eventually with a condition if python < 3.8 are still supported ? Or at least, to write a comment above `types._Cell`'s import (which could be useful for readers as I'm and for futures code clean up) ?

**Comment by Daverball** [comment]
`types.CellType` is an alias for `types._Cell` in typeshed: https://github.com/python/typeshed/blob/6565e8a0a0efbd8735a473e6c0d57f787c7fa4a2/stdlib/types.pyi#L573

This might be a leftover from when 3.7 and earlier were still supported. So it seems fine to just rename `types._Cell` and get rid of the alias and fix the two or three imports that uses it. The only caveat would be that this would eventually break older version of `types-six` with newer versions of type checkers that no longer have `types._Cell`.

**Comment by JelleZijlstra** [comment]
Note that stubs often contain private (underscore-prefixed) names that do not exist at runtime but help with the stub implementation. In this case from @Daverball's analysis it seems we can get rid of the private name though.

**Comment by yoann9344** [comment]
Thanks for the explanations ! I let you handle the PR/issue.
See you later ;)
