### ISSUE TITLE
`enum.nonmember` Typing Issues

### ISSUE THREAD

**Issue by max-muoto** [python/typeshed#11921]
There are some issues with the typing for `enum.nonmember`:

```python

import enum


class MyEnum(enum.StrEnum):
    VAL_1 = "val_1"
    VAL_2 = "val_2"

    _items = enum.nonmember({VAL_1: 1, VAL_2: 2})

    def to_int(self) -> int:
        return self._items[self]

```

Behavior like this is is fully supported at runtime, however, `__getattr__` isn't defined on `enum.nonmember`, making this raise an error in Pyright. Previously, this was allowed, but now the typeshed definitions are fully relied on: https://github.com/microsoft/pyright/issues/7924

Current types:

```python
  class nonmember(Generic[_EnumMemberT]):
      def __init__(self, value: _EnumMemberT) -> None: ...
      def __getattr__(self, name: str) -> _EnumMemberT: ...
```

Additionally, using `.value` here actually does lead to a runtime error, but types for `nonmember` would indicate that being fine.

```python
# Fine
MyEnum.VAL_1.to_int()
```

Type-checker would except this, but this fails at runtime:

```python
import enum


class MyEnum(enum.StrEnum):
    VAL_1 = "val_1"
    VAL_2 = "val_2"

    _items = enum.nonmember({VAL_1: 1, VAL_2: 2})

    def to_int(self) -> int:
        return self._items.value[self]

#  'dict' object has no attribute 'value'
MyEnum.VAL_1.to_int()
```

**Comment by srittau** [comment]
The stubs for `nonmember` are a 1:1 representation of the runtime class. The reason that this works at runtime is some magic in `EnumDict`:

https://github.com/python/cpython/blob/81c3130c51a2b1504842cb1a93732cc03ddbbd79/Lib/enum.py#L402-L404

This is something that the stubs can't reproduce, but needs to be hard-coded into type checkers, unfortunately.
