### ISSUE TITLE
stubs for 3rd party modules

### ISSUE THREAD

**Issue by dmwyatt** [python/typeshed#12]
* Is it intended for stubs for third party modules to come from their respective developers or just from the community as a whole?

I'd like to look into creating some stubs for various projects not owned by me.  I know in PEP-0484 it says: 

_Note that stubs for a given package will not be included here without the explicit consent of the package owner._

I'm just looking for clarification about whether that specifically means that such stubs will only come from the package owner or if I (for example) would have to work it out with the package owner and then have the owner communicate that to Boss Of Typeshed.

* What should pull requests for third party modules look like?  

Take a library that has multiple modules and packages.  Should our pull request put all the stubs in a package named after the third party library and then have a structure in that package mirroring the structure of that third party library?

Probably fodder for an updated README.md as mentioned in #1 ...

**Comment by matthiaskramm** [comment]
As long as the package owner is fine with you submitting stubs (and we'll just take your word for that), you're welcome to create a pull request.

Third party packages should be below python2/dist-packages/package_name/ and python3/dist-packages/package_name/, respectively, with the directory structure of the stubs mirroring the structure of the package. (If it's just a single file, use python2/dist-packages/package_name.py)
