### ISSUE TITLE
Add _interpreters to stdlib

### ISSUE THREAD

**Issue by tonybaloney** [python/typeshed#12011]
The `_interpreters` and `_interpchannels` packages were added in 3.13b1 but are missing type annotations.

Related #11990 

I'd be happy to submit these sometime over the next week in a PR

**Comment by tonybaloney** [comment]
Cc @ericsnowcurrently

**Comment by max-muoto** [comment]
Have started to work on these, I'd imagine I'll have a PR up in the coming days.

**Comment by AlexWaygood** [comment]
It might be easier to review if we first added some generated stubs using stubgen (if possible, using our wrapper script `scripts/create_baseline_stubs.py`), and we then incrementally made improvements to the generated stubs

**Comment by max-muoto** [comment]
Put up a first PR for `_interpchannels`: https://github.com/python/typeshed/pull/12199

**Comment by max-muoto** [comment]
We can close this out now @srittau.
