### ISSUE TITLE
Collective type of TypedDict values

### ISSUE THREAD

**Issue by Gouvernathor** [python/typeshed#12027]
A TypedDict is always of type dict[str, **_object_**] regardless of the annotations of the various values.

```py
SeatData = TypedDict("SeatData", {"fill": str, "stroke": str, "stroke-width": str, "title": str}, total=False)

def nodeset(k: str, v: str):
   ...

...

for k, v in seat_data.items():
    if v:
        nodeset(k, v) # warning on v, an object passed instead of a str
```

It's probably hard at compilation time to make a dynamic union of all the types passed as value types, so I don't expect this to be an easy bug to fix 😅

**Comment by srittau** [comment]
This is outside the jurisdiction of typeshed. This is something that your type checker (mypy?) should handle better. Please file a bug there!
