### ISSUE TITLE
asyncio: Awaitable is not available on AbstractEventLoop.create_task 

### ISSUE THREAD

**Issue by lambdalisue** [python/typeshed#1202]
https://github.com/python/typeshed/blob/8dc082dce5a742a0d87270a4494304acec000ec7/stdlib/3.4/asyncio/events.pyi#L79

The line should be

```
def create_task(self, coro: Union[Future[_T], Awaitable[_T], Generator[Any, None, _T]]) -> Task[_T]: ...
```

in Python 3.5 or later? Am I wrong?

**Comment by JelleZijlstra** [comment]
Isn't that redundant because Future inherits from Awaitable?

**Comment by gvanrossum** [comment]
Hm, it does, and yet there's this in tasks.pyi:
```
_FutureT = Union[Future[_T], Generator[Any, None, _T], Awaitable[_T]]
```
@lambdalisue Do you have a code snippet which you think is correct, which fails with the suggested addition to the union in create_task(), and which passes if you make that change to the stubs?

**Comment by azag0** [comment]
Can we reopen this? I hit this issue as well.

While its true that "Future inherits from Awaitable," it would need to be the other way round. So the signature of `BaseEventLoop.create_task` in Python >=3.5 should really be
```python
def create_task(self, coro: Union[Awaitable[_T], Generator[Any, None, _T]]) -> Task[_T]: ...
```
instead of
```python
def create_task(self, coro: Union[Future[_T], Generator[Any, None, _T]]) -> Task[_T]: ...
```

Likewise, `_FutureT` in tasks.pyi could really be
```python
_FutureT = Union[Generator[Any, None, _T], Awaitable[_T]]
```
instead of
```python
_FutureT = Union[Future[_T], Generator[Any, None, _T], Awaitable[_T]]
```

**Comment by JelleZijlstra** [comment]
Reopening for now; I don't have much time now can look into this during the PyCon sprints or after. Feel free to open a PR with a concrete suggested change.
