### ISSUE TITLE
Serial exclusive should be bool

### ISSUE THREAD

**Issue by JPHutchins** [python/typeshed#12034]
Looks like `exclusive`, here https://github.com/python/typeshed/blob/a83f02c2d9b24831eabb1c8f07bb65576712053a/stubs/pyserial/serial/serialutil.pyi#L65, should be a bool not float.

Reference: https://pyserial.readthedocs.io/en/latest/pyserial_api.html#serial.Serial

**Comment by srittau** [comment]
PR welcome!
