### ISSUE TITLE
networkx: Return type needs to be more specific

### ISSUE THREAD

**Issue by professoraldous** [python/typeshed#12053]
https://github.com/python/typeshed/blob/b2f6e5221b180d42a3770543a72036baa52b3907/stubs/networkx/networkx/algorithms/dag.pyi#L26

Per https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.transitive_reduction.html#networkx.algorithms.dag.transitive_reduction, the result should be a `DiGraph` and its contained type should match the contained type of the `DiGraph` for its input.

**Comment by srittau** [comment]
Sounds right. PR welcome!

**Comment by professoraldous** [comment]
https://github.com/python/typeshed/pull/12066

Cheers!
