### ISSUE TITLE
aiofiles.tempfiles missing python 3.12-specific overloads for NamedTemporaryFile

### ISSUE THREAD

**Issue by katanacrimson** [python/typeshed#12091]
Was digging through things to determine why I was being told by my editor that `aiofiles.tempfile.NamedTemporaryFile` didn't support the py3.12 argument `delete_on_close`, and it appears that it's that this isn't specified here and that it is *not* that I'm losing my mind. :)

https://github.com/python/typeshed/blob/main/stubs/aiofiles/aiofiles/tempfile/__init__.pyi

If we look through these, there are no python 3.12-specific variants which identify this delete_on_close argument which was added to support the behaviors of the same-named argument added to `tempfiles.NamedTemporaryFile` in python 3.12.

We can find the relevant portion of the python 3.12 overload of the `aiofiles.tempfile.NamedTemporaryFile` here:

https://github.com/Tinche/aiofiles/blob/v23.2.1/src/aiofiles/tempfile/__init__.py#L24-L61

**Comment by srittau** [comment]
If in doubt, always assume that the stubs are wrong first. :) PR welcome!

**Comment by max-muoto** [comment]
> If in doubt, always assume that the stubs are wrong first. :) PR welcome!

Put up a PR here!

**Comment by max-muoto** [comment]
We should be able to close this @srittau.
