### ISSUE TITLE
tuple.__new__ does not accept class with only __getitem__ method

### ISSUE THREAD

**Issue by JonathanPlasse** [python/typeshed#12094]
Currently the `tuple` constructor only accepts iterables.
https://github.com/python/typeshed/blob/97ccd8985a3b8fd7b888c0653e92f296db6fd56a/stdlib/builtins.pyi#L932-L933
But the `tuple` constructor can also take in classes that only have the `__getitem__` method and is not iterable.
```python
class A:
    def __getitem__(self, key):
        if key >= 3:
            raise IndexError
        return key

print(tuple(A()))  # (0, 1, 2)
```

A `_GetItemIterable` could be added to `tuple.__new__` signature like for `iter`.
https://github.com/python/typeshed/blob/97ccd8985a3b8fd7b888c0653e92f296db6fd56a/stdlib/builtins.pyi#L1424-L1431

I am open to make a PR to fix it.

**Comment by AlexWaygood** [comment]
Sort of a duplicate of https://github.com/python/typeshed/issues/7813

**Comment by JonathanPlasse** [comment]
Thank you, I need to improve my issue searching methodology.
