### ISSUE TITLE
Add stub for `tf.math.angle`

### ISSUE THREAD

**Issue by Aweptimum** [python/typeshed#12095]
I noticed [`tf.math.angle`](https://www.tensorflow.org/api_docs/python/tf/math/angle) is missing from the `math.pyi` file.

Would it just follow the same pattern as the `tf.math.abs` function? Like this:
```python
@overload
def angle(x: TensorCompatible, name: str | None = None) -> Tensor: ...
@overload
def angle(x: SparseTensor, name: str | None = None) -> SparseTensor: ...
@overload
def angle(x: RaggedTensor, name: str | None = None) -> RaggedTensor: ...
```

I copied that into my local `math.pyi` file and my IDE is happy

**Comment by hmc-cs-mdrissi** [comment]
Close. The dense/ragged overload are correct. The sparse overload crashes in practice. Most tensorflow functions don't support sparse and documentation is unreliable on whether sparse works. So I use repl to spot check each tf function for each of 3 main tensor types.

A small pr for dense/ragged case would be good.

**Comment by Aweptimum** [comment]
Would that include adding `angle as angle` to [`__init__.pyi`](https://github.com/python/typeshed/blob/d755da86dd8518dc40c55d1b753797d35959fe4a/stubs/tensorflow/tensorflow/__init__.pyi) in the tf.math import? To be consistent with the other methods (I did not do that locally, but still got intellisense)

**Comment by hmc-cs-mdrissi** [comment]
Yes that import is needed if you want tf.math.angle to work for type checkers that track re-export rules.
