### ISSUE TITLE
Parameter `preset` has incorrect type for tarfile.open with modes `w.xz`, `x.xz`

### ISSUE THREAD

**Issue by antecrescent** [python/typeshed#12127]
Reproduction:
```python
import lzma
import tarfile
import tempfile

with tempfile.NamedTemporaryFile() as temp:
    with tarfile.open(fileobj=temp, mode="w:xz", preset=9 | lzma.PRESET_EXTREME,) as tar:
        pass
```
Context:
For modes 'w:xz' and 'x:xz', [tarfile.open()](https://docs.python.org/3/library/tarfile.html#tarfile.open) accepts the keyword argument preset to specify the compression level of the file.
`preset` (if provided) should be an integer in the range 0-9, optionally OR-ed with the constant `PRESET_EXTREME`.

Proposed fix:
Since the constant is a large `int` according to `lzma.pyi`, I assume that `preset` should also be of that type. Currently, it's defined as `Literal[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] | None` only in `open(...)`.

**Comment by srittau** [comment]
Makes sense to change preset to just `int | None`. PR welcome!
