### ISSUE TITLE
`isinstance` can take `typing.Union` as second arg in 3.10 and newer

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#12137]
Currently it allows for `types.UnionType` but not `typing.Union`
```
if sys.version_info >= (3, 10):
    _ClassInfo: TypeAlias = type | types.UnionType | tuple[_ClassInfo, ...]
else:
    _ClassInfo: TypeAlias = type | tuple[_ClassInfo, ...]

def isinstance(obj: object, class_or_tuple: _ClassInfo, /) -> bool: ...
```

I think mypy currently assumes that whatever typeshed says for isinstance has no false positives

**Comment by JelleZijlstra** [comment]
I'm not sure we could express this in typeshed. `Union[int, str]` is not an instance of `typing.Union`.

**Comment by AlexWaygood** [comment]
(I don't object to revisiting this, but this is a duplicate of #7505)

**Comment by hauntsaninja** [comment]
Thanks, looks like most of the relevant discussion is on https://github.com/python/typeshed/pull/7508. Sounds like most people are surprised that isinstance works at all with old Union / type checkers should special case this even more than they currently do
