### ISSUE TITLE
"Redis[Any]" has no attribute "aclose"

### ISSUE THREAD

**Issue by kwist-sgr** [python/typeshed#12144]
```python
# example.py 
from redis.asyncio import from_url, Redis


async def main() -> None:
    redis: Redis = from_url('redis://localhost:6379/0')
    await redis.aclose()
```

```shell
$ mypy example.py 
example.py:6: error: "Redis[Any]" has no attribute "aclose"; maybe "close"?  [attr-defined]
Found 1 error in 1 file (checked 1 source file)
```

```shell
Python 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from redis.asyncio import Redis
>>> Redis.aclose
<function Redis.aclose at 0x7737b06de170>
```

**Your Environment**

```shell
mypy              1.10.0
mypy-extensions   1.0.0
redis             5.0.3
types-redis       4.6.0.20240425
```

**Comment by srittau** [comment]
`aclose()` was only added during redis 5.1(?) development. Our redis stubs only support redis 4. redis 5 has type annotations.

**Comment by AlexWaygood** [comment]
Building on what @srittau said there — while you have `types-redis` installed in your environment, mypy will use those as the single source of truth w.r.t. Redis. If you want mypy to make use of `redis-py`'s inline type annotations for newer methods like `aclose`, you'll need to uninstall `types-redis` from your environment in order for mypy to pick them up @kwist-sgr. If you then encounter any new mypy issues as a result of uninstalling `types-redis` from your environment, you'll then have to report those issues upstream to `redis-py`, unfortunately.

**Comment by kwist-sgr** [comment]
@AlexWaygood Got it. Thanks! :smiley:
