### ISSUE TITLE
overly strict type for tornado.web.RequestHandler.initialize

### ISSUE THREAD

**Issue by dgoldstein0** [python/typeshed#1214]
https://github.com/python/typeshed/blob/fe0e3744ccce52f6dc8b4258392840c075642111/third_party/2/tornado/web.pyi#L21
http://www.tornadoweb.org/en/stable/web.html#tornado.web.RequestHandler.initialize

According to the types, initialize is a no-arg member function.  According to the docs, the intent is for you to override it with whatever params you want, and for them to be provided from the `Application`.  I'm not really sure if it is possible to statically type this.  What I figured out is if I give each of my variables a default (e.g. `None`) things are happy, but it would be nice if this wasn't needed as the code works as long as you don't forget a config value otherwise.

**Comment by dgoldstein0** [comment]
fwiw example code where I've worked around this.  I've simplified a little from my actual use case since I think this shows the issue clearly enough

```
class BaseRequestHandler(tornado.web.RequestHandler):
    def initialize(
        self,
        messages=None, # type: Optional[MessagesListType]
        waiting=None, # type: Optional[WaitingListType]
    ):
        # type: (...) -> None
        # defaults of `None` are necessary to make mypy happy.  The args here come from
        # the config dict below, so really these options aren't optional - they are always given
        # - but mypy can't tell that.
        assert messages
        assert waiting

        self.waiting = waiting
        self.messages = messages

class FooHandler(BaseRequestHandler):
    def post(self, *args, **kwargs):
         # type: (*Any, **Any) -> None
         ...

class BarHandler(BaseRequestHandler):
    def post(self, *args, **kwargs):
         # type: (*Any, **Any) -> None
         ...

def make_app():
    # type: () -> tornado.web.Application
    messages = [] # type: MessagesListType
    waiting = [] # type: WaitingListType
    config = {
        'messages': messages,
        'waiting': waiting,
    }

    return tornado.web.Application([
        (r'/foo', FooHandler, config),
        (r'/bar', BarHandler, config),
    ])
```

**Comment by JelleZijlstra** [comment]
Sounds like we should change the stub to make `initialize` take `**kwargs: Any`. Would you mind submitting a PR?

**Comment by dgoldstein0** [comment]
would that then require that any overriding initialize call also take `**kwargs`?

**Comment by JelleZijlstra** [comment]
You're right, it would.

**Comment by dgoldstein0** [comment]
hm.  Still probably better than the status quo.

**Comment by JelleZijlstra** [comment]
I think they're about equally bad. Maybe we can do something like putting `initialize: ClassVar[Callable[..., None]]` in typeshed, but I haven't tried to see what mypy makes of that.

**Comment by dgoldstein0** [comment]
actually it isn't - I wrote a quick demo program:

```
from typing import Any

class A(object):
    def foo(self, **kwargs):
        # type: (**Any) -> None
        pass

class B(A):
    def foo(self, a, b, c, **kwargs):
        # type: (int, str, bool, **Any) -> None
        pass
```

And ended up with `metaserver/asdf.py:9: error: Signature of "foo" incompatible with supertype "A"`

**Comment by dgoldstein0** [comment]
so yeah... equally bad sounds about right.

To strongly type this what we need is RequestHandler to have a type variable which says what the type of the initialize params are expected to be, and then for Application to match that with the config object given  when it's constructed.  Would be neat if we could get that to work but I don't think mypy is advanced enough to do things like that yet.

**Comment by srittau** [comment]
I can't really see a way to fix this in typeshed, since the sub-classes use a different signature by design. Using `# type: ignore` is probably the best option.

**Comment by wilson0x4d** [comment]
> would that then require that any overriding initialize call also take **kwargs?

only from a strict type-checking perspective if using a type checker that doesn't understand how kwds are implemented in Python.

> actually it isn't - I wrote a quick demo program:
> 
> ```
> from typing import Any
> 
> class A(object):
>     def foo(self, **kwargs):
>         # type: (**Any) -> None
>         pass
> 
> class B(A):
>     def foo(self, a, b, c, **kwargs):
>         # type: (int, str, bool, **Any) -> None
>         pass
> ```
> 
> And ended up with `asdf.py:9: error: Signature of "foo" incompatible with supertype "A"`

Unsurprising. Consider the following which are run-time compatible:

```python
class A(object):
    def foo(self, *args, **kwargs):
        # type: (*Any, **Any) -> None
        print([args, kwargs])

class B(A):
    def foo(self, a, b, c, **kwargs):
        # type: (int, str, bool, **Any) -> None
        super().foo(a, b, c, **kwargs)

# observe run-time covariance
A().foo(2, 'b', True, fo='sho')
B().foo(*(2, 'b', True), fo='sho')
```

In the original code `A:foo()`'s signature lacked positional parameters, `B:foo()`'s signature contained positional parameters. From a Python language perspective the two signatures were incompatible (even without type checking). In the provided alternative version `A` and `B` have run-time compatible signatures for `foo()`, but even though `tuple[int,str,bool]` is covariant with `tuple[Any,Any,Any]` an excessively strict type checker might complain.

I know this is an old post, and somewhat unrelated to the issue at hand, but just wanted to point out the glaring problem with the "demo" code.
