### ISSUE TITLE
sys.getfilesystemencoding() in Python 2 returns Optional[str]

### ISSUE THREAD

**Issue by euresti** [python/typeshed#1221]
We have quite a bit of code that does:
`foo.encode(encoding=sys.getfilesystemencoding())`

This fails in python 2 because 
`def getfilesystemencoding() -> Union[str, None]: ...`

In my many years of working on Python I've never seen this function return None. Maybe it can, but Python 3 seems to think it wont.
Could it be a good idea to change the python 2 version to not return an Optional?

**Comment by gvanrossum** [comment]
Yeah, just fix it.
