### ISSUE TITLE
[tensorflow] Update keras to 3.4

### ISSUE THREAD

**Issue by srittau** [python/typeshed#12222]
Currently, keras is pinned to `>=3.3.3,<3.4` in the stubtest requirements. This should be updated to `>=3.4`, but this currently causes stubtest to fail.

**Comment by Avasam** [comment]
Tangentially related: #11714

**Comment by alliesw** [comment]
What do the failure details from the stubtest logs state?

**Comment by srittau** [comment]
keras now uses `==3.6.*`
