### ISSUE TITLE
`zipimport` is missing 3.10 methods

### ISSUE THREAD

**Issue by ZeroIntensity** [python/typeshed#12236]
The stubs for `zipimport` are out of date. For example, since 3.10, `zipimport.zipimporter` has implemented `exec_module` and `create_module`, but these don't exist in the type stubs.

I would be happy to author the PR, if there are no objections (or some other reason why this was left out in the first place).

**Comment by max-muoto** [comment]
Just seems like a simple oversight, put up a PR fixing this: https://github.com/python/typeshed/pull/12242
