### ISSUE TITLE
"tcgetattr" is not a known attribute of module "tty"

### ISSUE THREAD

**Issue by powellnorma** [python/typeshed#12249]
Example code:
```py
import tty
mode = tty.tcgetattr(1)
```

I believe this stems from tty.py using: `from termios import *` - Pyright warns about this with `Wildcard import from a library not allowed`.

**Comment by srittau** [comment]
Indeed, the stubs don't replicate the star import from the runtime. This is deliberate. `tty.tcgetattr` is not documented, you should use the documented `termios.tcgetattr` instead of the re-export from tty.
