### ISSUE TITLE
Return annotation of `argparse.ArgumentParser.parse_args()` too strict

### ISSUE THREAD

**Issue by nineteendo** [python/typeshed#12274]
I was trying to annotate an argument parser with subparsers, and noticed the return annotation of `argparse.ArgumentParser.parse_args()` is too strict. Take [this example](https://mypy-play.net/?mypy=latest&python=3.12&gist=0b44596710a5334897ec928c5a274f6a):

```python
from argparse import ArgumentParser
from typing import Any, Literal

class _FooNamespace:
    foo: str

class _BarNamespace:
    bar: int

class _MainNamespace:
    command: Literal["foo", "bar"] | None

parser: ArgumentParser = ArgumentParser()
commands = parser.add_subparsers(dest="command")
foo_parser: ArgumentParser = commands.add_parser("foo")
foo_parser.add_argument("foo")
bar_parser: ArgumentParser = commands.add_parser("bar")
bar_parser.add_argument("bar", type=int)
args = parser.parse_args()
main_args: _MainNamespace = args
if main_args.command is None:
    print("hello world")
elif main_args.command == "foo":
    foo_args: _FooNamespace = args
    print("hello", foo_args.foo)
elif main_args.command == "bar":
    bar_args: _BarNamespace = args
    print("spam" * bar_args.bar)
```

mypy output:

```none
main.py:24: error: Incompatible types in assignment (expression has type "Namespace", variable has type "_MainNamespace")  [assignment]
main.py:28: error: Incompatible types in assignment (expression has type "Namespace", variable has type "_FooNamespace")  [assignment]
main.py:31: error: Incompatible types in assignment (expression has type "Namespace", variable has type "_BarNamespace")  [assignment]
```

The "real" type of `args` is `_MainNamespace & (_FooNamespace | _BarNamespace | object)` (using a hypothetical intersection), but there's no way to infer that. And even if this was possible, it would still be impossible to determine which of theses cases we're dealing with. The current annotation is `argparse.Namespace`, which acts a lot like `Any`, but doesn't allow assigning to arbitrary namespaces.

**Would it make sense to use `Any` for the return annotation of `argparse.ArgumentParser.parse_args()`?**

**Comment by hauntsaninja** [comment]
No, I don't think it'd make sense for typeshed to change its return type.

If you want `Any`, you're welcome to assign that type to `Args`: `args: Any = parser.parse_args()`.

For your specific case, turning `_FooNamespace` into a Protocol might be more like what you want here.

Finally, I've also seen people do the equivalent of `TypedActualClass(**vars(parser.parse_args()))`

**Comment by nineteendo** [comment]
`typing.cast()` is a bit nicer:

```python
args: _MainNamespace = parser.parse_args(namespace=_MainNamespace())
if args.command is None:
    print("hello world")
elif main_args.command == "foo":
    args: _FooNamespace = cast(_FooNamespace, args)
    print("hello", foo_args.foo)
elif args.command == "bar":
    bar_args: _BarNamespace = cast(_BarNamespace, args)
    print("spam" * bar_args.bar)
```
