### ISSUE TITLE
Mypy incorrectly reports an error with logging.basicConfig(level='CRITICAL')

### ISSUE THREAD

**Issue by fniessink** [python/typeshed#1232]
Using mypy 0.501 / Python 3.6 on the code below gives an error message that is incorrect since the `level` argument to `basisConfig` can be both an integer and a string.

```
import logging

logging.basicConfig(level='CRITICAL')
```

**Comment by JelleZijlstra** [comment]
Thanks for reporting! This is almost certainly an issue for github.com/python/typeshed.

**Comment by fniessink** [comment]
I'm confused. That's where I opened the issue, didn't I?

**Comment by gvanrossum** [comment]
Sorry, you're right. It's just that the way you wrote your problem description (calling out the mypy version etc.) made this look like many typeshed issues that are filed in the mypy tracker. Our apologies!

**Comment by JelleZijlstra** [comment]
Oops yes, sorry for that. I was clicking through mypy notifications and didn't notice this one was typeshed.

**Comment by fniessink** [comment]
Well, I would like to report the typeshed version, but I don't see a way to get mypy to tell me the typeshed version it is using. So that's why I mentioned the mypy version.

**Comment by gvanrossum** [comment]
On to sunnier places! Can you come up with a PR to fix this issue?
