### ISSUE TITLE
Invalid stubs for ExifRead process_file

### ISSUE THREAD

**Issue by vinicius507** [python/typeshed#12371]
**Describe the bug**

LSP servers throws misleading diagnostics on the ExitRead library due to typeshed stubs of the library being incorrect.

**Code or Screenshots**

```python
import exifread

def parse_exif_data(file: BinaryIO):
    logging.info("Parsing EXIF data from %s", file.name)
    tags = exifread.process_file(file)
    logging.info("Image %s has %d tags", file.name, len(tags))
```

![image](https://github.com/user-attachments/assets/a8d42bda-d0bb-49ee-bdd1-9c4ed080d742)

The `process_file` function has the following signature:

```py
def process_file(fh: BinaryIO, stop_tag=DEFAULT_STOP_TAG,
                 details=True, strict=False, debug=False,
                 truncate_tags=True, auto_seek=True, extract_thumbnail=True)
``` 

While the stubs have the following signature:

```py
def process_file(
    fh: Reader,  # Should be BinaryIO
    stop_tag: str = "UNDEF",
    details: bool = True,
    strict: bool = False,
    debug: bool = False,
    truncate_tags: bool = True,
    auto_seek: bool = True,
) -> dict[str, Any]: ...
```

**Environment**

- **OS:** `Linux desktop 6.6.37 #1-NixOS SMP PREEMPT_DYNAMIC Fri Jul 5 07:34:07 UTC 2024 x86_64 GNU/Linux`
- **Neovim:** 0.10.0
- **Python:** 3.11.8
- **ExifRead:** 3.0.0

**Comment by srittau** [comment]
Using `BinaryIO` as type annotation for library arguments is seldom a good idea, as it is not a protocol and requires sub-classing. That said, it seems the return annotation for `Reader.__iter__()` is plain wrong and should be `Iterator[bytes]`, instead of just `bytes`.

**Comment by vinicius507** [comment]
> Using `BinaryIO` as type annotation for library arguments is seldom a good idea, as it is not a protocol and requires sub-classing. That said, it seems the return annotation for `Reader.__iter__()` is plain wrong and should be `Iterator[bytes]`, instead of just `bytes`.

So should I open a new issue about the `Reader.__iter__()` return annotation then?

**Comment by JelleZijlstra** [comment]
Better yet, send a PR fixing it :)

Issues are useful if there is something controversial to discuss, but for simple mistakes in the stub, it's fine to only send a PR.

**Comment by vinicius507** [comment]
> Better yet, send a PR fixing it :)
> 
> Issues are useful if there is something controversial to discuss, but for simple mistakes in the stub, it's fine to only send a PR.

Will do so. Thanks a ton.
