### ISSUE TITLE
Click 6.6 + Py 3.6 Decorator Stub Issues

### ISSUE THREAD

**Issue by cooperlees** [python/typeshed#1238]
First time stub + decorator 'typer', so please bare with me. I want to try and have the click stubs cater for a very common use case I repeat a lot in CLI tools I write.

Mypy reports the following:
```
stdout:
python/pyfi/venv_builder.py:69:1: error: Unexpected keyword argument "context_settings" for "command"
python/pyfi/venv_builder.py:70:1: error: Argument 4 to "option" has incompatible type 
Callable[[Context, Option, bool], bool]; expected 
"Optional[Callable[[Context, Parameter, str], Any]]"
lib/mypy/typeshed/third_party/3.6/click/decorators.pyi:28:0: note: "command" defined here
```

I've also seen `Unexpected keyword argument "context_settings" for "group"`

Sample Code:

```python
def _handle_debug(
    ctx: click.core.Context,
    param: click.core.Option,
    debug: bool
) -> bool:
    ...
    return debug

@click.command(context_settings=CONTEXT_SETTINGS)  # Just a dict allow me to have -h for help
@click.option('--debug', '-d',
              is_flag=True,
              callback=_handle_debug,
              help='Turn on debug logging')
def main(debug: bool=False):
    ...
```

Looking at the stubs I see I should be just able to add context_settings to option, but for param I always get an Option object passed and the stubs say Param. Should we Union[Option, Param] + Union[bool, str, int] and make a common Type Alias in the PR? Thoughts.

**Comment by cooperlees** [comment]
Put this up on my fork for people to look @ and help with comments:
https://github.com/cooperlees/typeshed/commit/e81ed4b6d7b61d17ae9aeab9ce51bd43f265aa68

**Comment by cooperlees** [comment]
Doing a PR to get a review. https://github.com/python/typeshed/pull/1244

**Comment by JelleZijlstra** [comment]
I believe #1244 fixed this.
