### ISSUE TITLE
`is_dataclass(Any)` return type incorrect, differs from `is_dataclass(object)`

### ISSUE THREAD

**Issue by intgr** [python/typeshed#12401]
I found this surprising and arguably incorrect. According to mypy:

```python
from typing import Any
from dataclasses import is_dataclass


def example1(arg: Any) -> None:
    if is_dataclass(arg):
        reveal_type(arg)  # ❌ Revealed type is "type[_typeshed.DataclassInstance]"


def example2(arg: object) -> None:
    if is_dataclass(arg):
        reveal_type(arg)  # ✅ Revealed type is "Union[_typeshed.DataclassInstance, type[_typeshed.DataclassInstance]]"
```

[(Mypy playground)](https://mypy-play.net/?mypy=latest&python=3.12&gist=3cb374974a1ca716a0d27c749921ddd4)

This is because `Any` matches the 1st overload, even if 2nd overload with `object` argument is more appropriate for `Any`:

```python
@overload
def is_dataclass(obj: type) -> TypeIs[type[DataclassInstance]]: ...
@overload
def is_dataclass(obj: object) -> TypeIs[DataclassInstance | type[DataclassInstance]]: ...
```

I couldn't think of an elegant fix for this.

**Comment by srittau** [comment]
I don't think there is a fix, as `Any` is compatible with everything, so it will always match the first overload. Reordering is also not possible, at least not until we get a "Not" type (python/typing#801).

**Comment by intgr** [comment]
As a hack, we could add another overload case, with argument type that no real type ever satisfies but only `Any` can satisfy. Could we use the `Never` type?

**Comment by sobolevn** [comment]
Refs https://github.com/python/mypy/issues/17579

**Comment by max-muoto** [comment]
For reference Pyright is handling this just fine: https://pyright-play.net/?pyrightVersion=1.1.374&pythonVersion=3.14&strict=true&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoCCKcAUKJFACYCGM1AxgDbUDOLApi5trvkiwH0adJqxYkJldsCjsAHtWyN2ARgAU1EGgBchYgEooAWgB8UAHJgU7bSSj3MM-kNoNmbDVv22HvqCHYAN3ZqRgF4BHZPNEMoCRIpGXlFBGUAJmjdMAAjACt2ehhDUwsrGzsHJCdBYTcxaO8Kv38gkLCIqKbmh000Lt9DEiA

**Comment by intgr** [comment]
Opened PR:

* #12517

**Comment by sobolevn** [comment]
MyPy PR is here: https://github.com/python/mypy/pull/17678
