### ISSUE TITLE
Unexpected behavior with io.TextIO

### ISSUE THREAD

**Issue by kmarekspartz** [python/typeshed#1240]
(Previously filed as python/mypy#3306)

Dropped my notes / examples / Dockerfile into https://gist.github.com/zeckalpha/c0bed39b7de8dee64e0c895b852a850d

I've been having trouble adding types to:

``` python
from sys import stdin, stdout

... # import something as TIO... See below.

def main(input_io: TIO=stdin, output_io: TIO=stdout) -> None:
    for line in input_io.readlines():
        output_io.write(line)


if __name__ == '__main__':
    main()
```

Depending on which class is used for the typing we get different results:

# io.TextIO

    from io import TextIO as TIO

Type checks but fails at runtime with:

    ImportError: cannot import name 'TextIO'

I'd expect this one to fail during type checking. _This is a bug, I think._ There seems to be issues with https://github.com/python/typeshed/blob/397f99836842494de2e9561001d16cbe64b3b937/stdlib/3/io.pyi and I suspect a change there (possibly breaking it out to minor versions of Python 3) would catch this.

# io.TextIOBase

    from io import TextIOBase as TIO

Fails at type check:

    error: Incompatible types in assignment (expression has type "TextIO", variable has type "TextIOBase")
    error: Argument 1 to "write" of "TextIOBase" has incompatible type "bytes"; expected "str"

This is okay, but a poor error message, e.g. "Did you mean typing.TextIO?" might be a better error message. A stretch goal :)

# io.TextIOWrapper

from io import TextIOWrapper as TIO

Fails at type check:

    error: Incompatible types in assignment (expression has type "TextIO", variable has type "TextIOWrapper")

Also okay.

# typing.TextIO

    from typing import TextIO as TIO

Works great, but type(sys.stdin) is not TextIO in Python 3.6.

Related issues with `TextIO`:

https://github.com/python/mypy/issues/2111
https://github.com/python/mypy/issues/2337
https://github.com/python/mypy/issues/266
https://github.com/python/mypy/issues/1462
https://github.com/python/typeshed/issues/163

**Comment by JelleZijlstra** [comment]
`from io import TextIO` should now be caught by mypy since `io.pyi` no longer exports that name. I don't think there's anything else actionable here.

**Comment by HazardousPeach** [comment]
Wait, don't we still need `open` to return a TextIOBase in typeshed instead of a  TextIO?

**Comment by moshez** [comment]
This is still causing a problem:

```
$ ./build/nox/lint/bin/mypy foo.py 
foo.py:2: error: Dict entry 0 has incompatible type "int": "TextIO"; expected "int": "TextIOBase"
Found 1 error in 1 file (checked 1 source file)
$ cat foo.py 
import typing, io, sys
varname: typing.Mapping[int, io.TextIOBase] = {5: sys.stdout}
```
