### ISSUE TITLE
`ZipFile.writestr` type hints do not match the docstring

### ISSUE THREAD

**Issue by Ravencentric** [python/typeshed#12431]
https://github.com/python/cpython/blob/5f6001130f8ada871193377954cfcfee01ef93b6/Lib/zipfile/__init__.py#L1897-L1905
```py
    def writestr(self, zinfo_or_arcname, data,
                 compress_type=None, compresslevel=None):
        """Write a file into the archive.  The contents is 'data', which
        may be either a 'str' or a 'bytes' instance; if it is a 'str',
        it is encoded as UTF-8 first.
        'zinfo_or_arcname' is either a ZipInfo instance or
        the name of the file in the archive."""
        if isinstance(data, str):
            data = data.encode("utf-8")
```
https://github.com/python/typeshed/blob/9eae1ae1a5b47745c7d289bb2092f2b4340e7622/stdlib/zipfile/__init__.pyi#L172-L178

The docstring says it can accept either `bytes` or `str`, however the typehint only covers `str`

**Comment by JelleZijlstra** [comment]
bytes is a SizedBuffer though.

**Comment by Ravencentric** [comment]
Yep, just realised that. Dunno what happened there in my head.
