### ISSUE TITLE
TextIOBuffer `_WrappedBuffer` attr `isatty` should be `bool`

### ISSUE THREAD

**Issue by ashleysommer** [python/typeshed#12437]
There was a small bug in this PR earlier this year to create a protocol for `TextIOBuffer` `_WrappedBuffer`
https://github.com/python/typeshed/pull/11420

See here:
https://github.com/python/typeshed/blob/a21c4bc4f15c07e07cb3e0bbe684b0fb1c81788f/stdlib/io.pyi#L171

`isatty` should return `bool`.

Notice `isatty` on `IOBase` is a bool:
https://github.com/python/typeshed/blob/a21c4bc4f15c07e07cb3e0bbe684b0fb1c81788f/stdlib/io.pyi#L63

And literally [every other occurrence](https://github.com/search?q=repo%3Apython%2Ftypeshed++isatty&type=code&p=1) of `isatty` in every other type stub is a `bool` too.

Looks like the mistake came from [this comment](https://github.com/python/typeshed/issues/11418#issuecomment-1943678532) because that comment incorrectly lists `isatty` as `int` too.

**Comment by srittau** [comment]
Good catch! PR welcome.

**Comment by ashleysommer** [comment]
@srittau Easy. PR here: https://github.com/python/typeshed/pull/12438
