### ISSUE TITLE
Check incorrect when using a TimestampSeries and tools from pandas.tseries.offsets

### ISSUE THREAD

**Issue by clemconv1** [python/typeshed#12471]
It seems type annotations are wrong between a Timestamp series and tools offered by the offsets library

`df["year_end"] = df["date"] + pd.tseries.offsets.YearEnd(0)` is flagged with `Operator "+" not supported for types "TimestampSeries" and "YearEnd"`

**Comment by AlexWaygood** [comment]
Hi! We don't have any stubs for `pandas` here. Did you maybe mean to report this to the `pandas-stubs` project?

**Comment by AlexWaygood** [comment]
Closing for now, but I'm happy to reopen if this is indeed a bug report about one of the typeshed stubs packages! :)
