### ISSUE TITLE
[types-polib] typing for `msgctxt` of `_BaseFile.find` is wrongly typed

### ISSUE THREAD

**Issue by DanieleIsoni** [python/typeshed#12502]
In [this line](https://github.com/python/typeshed/blob/e9b3b03764d0557e103e1b2c4d95ce02965db22b/stubs/polib/polib.pyi#L41) the `msgctxt` argument is typed as bool when it should be a str. As the documentation of the function says:

> `msgctxt`  
>     string, allows specifying a specific message context for the search.

**Comment by srittau** [comment]
Indeed. Considering this defaults to `False`, the correct annotation is probably `str | Literal[False]`. PR welcome!

**Comment by ZeroIntensity** [comment]
Created #12506 for this!
