### ISSUE TITLE
`inspect.cleandoc` appears to be incorrectly annotated (pre 3.13)

### ISSUE THREAD

**Issue by Matiiss** [python/typeshed#12516]
Here's the annotation:
https://github.com/python/typeshed/blob/e2aea1e70f60fcbb77f944a3dfd2a58dfb54200e/stdlib/inspect.pyi#L289

However, in the source code (for Python 3.12 at least) it can return `None`
https://github.com/python/cpython/blob/3.12/Lib/inspect.py#L882-L890
![image](https://github.com/user-attachments/assets/c1894b8e-2507-4dd8-bfa1-ba1f3cdb1772)

This is not really documented anywhere and the type hints don't suggest it either. (This type hint has been there for what seems to be 9 years, when in reality this function should have been annotated as returning `Optional[str]`)

(current `main` branch is fine and it appears that this is the behavior since 3.13)
https://github.com/python/cpython/blob/main/Lib/inspect.py#L781-L786 (this link will probably not be valid in the future)
![image](https://github.com/user-attachments/assets/8396e8e7-ba26-4b1f-9e7a-6d0802d14ccd)

(If this is something to be fixed in some way or another (or in another repository), I'd be happy to do so)

**Comment by Akuli** [comment]
I think nothing needs to be changed/fixed.

Getting a `UnicodeError` from that line of code is difficult, and will not happen by accident. No matter what string you pass in, it will always succeed. And if you pass in `None` or `bytes`, it will fail in other ways than `UnicodeError`. (Perhaps that line is a leftover from Python 2 times, when unicode was a mess.)

So even if you consider this to be a feature, it is a feature that is difficult to use, and even more difficult to use correctly, and removed in Python 3.13. It does not make sense for typeshed to support such a feature.

**Comment by JelleZijlstra** [comment]
I looked at the source code and I don't see any way either `.expandtabs()` or `.split()` can raise UnicodeError. So @Akuli is probably right that this is a Python 2 leftover and we shouldn't change the return type in typeshed.
