### ISSUE TITLE
`TarInfo.mtime` typing is stricter than required

### ISSUE THREAD

**Issue by ncoghlan** [python/typeshed#12520]
The typeshed stub types `TarInfo.mtime` strictly as `int` (presumably because it gets initialised to `0` in the standard library code). The Python stdlib docs type it as `int|float`. The implementation does support `float` values in this field as it coerces with `int()` when serialising `mtime` to the tar archive field.

This isn't a blocker for anything (since type checkers can be satisfied by making the truncation explicit in the code setting the `TarInfo.mtime` field), but the discrepancy with the stdlib docs made the issue seem worth filing.

**Comment by ncoghlan** [comment]
I believe making the typeshed stub align with the stdlib docs is the right answer here, so I've submitted a PR for that.

**Comment by srittau** [comment]
For future reference: It's okay to just send PRs in straight-forward cases like this. We don't require an issue for each PR.

**Comment by ncoghlan** [comment]
Thanks.

In this case, I wasn't sure if I had diagnosed the problem properly, hence filing the issue first (it was only after writing it up clearly enough to file the issue that I became convinced enough of my own reasoning to send the PR).

**Comment by ncoghlan** [comment]
@cjwatson I believe that should be updated too (the case where I ran into this problem didn't use that API, so I didn't notice it was also overly strict).

**Comment by cjwatson** [comment]
Thanks for confirming.  Done in #13199.
