### ISSUE TITLE
psycopg2 stubs do not explicitly export anything and so can't be used for typechecking

### ISSUE THREAD

**Issue by sh-at-cs** [python/typeshed#12578]
## Steps to reproduce

1. Create a new venv and install the relevant packages: `pip3 install mypy psycopg2 types-psycopg2`
2. Create a file `example.py` containing `from psycopg2 import cursor`
3. Typecheck this file with Mypy: `mypy example.py`

This will result in the following error:

```
example.py:1: error: Module "psycopg2" does not explicitly export attribute "cursor"  [attr-defined]
```

## Suggested fix

Apparently, recent versions of Mypy need stub definitions to be explicitly exported via `__all__`, but this is missing from the `psycopg2` stubs. So it's probably just to add those?

**Comment by srittau** [comment]
This matches the runtime behavior of psycopg:

```python
Python 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import psycopg2
>>> psycopg2.cursor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'psycopg2' has no attribute 'cursor'
```

Other attributes that exist at runtime are correctly re-exported in the stubs.

At the moment, the best way to use cursor is to import it from `psycopg2._psycopg`. I admit that this is not ideal, and I'm open to the idea of defining clearly marked stubs-only aliases in `__init__.pyi`. (For example called `_Cursor` and `_Connection`.)

**Comment by sh-at-cs** [comment]
Oh I see, I completely misunderstood it then. Thanks!
