### ISSUE TITLE
mypy does not accept `file.write` as callback for `ftplib.FTP.retrbinary`

### ISSUE THREAD

**Issue by frexvahi** [python/typeshed#1258]
```python
import ftplib
from typing import BinaryIO

def download_to(f: BinaryIO):
    with ftplib.FTP('example.com') as ftp:
        ftp.retrbinary('RETR data.bin', callback=f.write)
```

mypy from github master gives:
```
foo.py:6: error: Argument 2 to "retrbinary" of "FTP" has incompatible type overloaded function; expected Callable[[bytes], None]
```

I think the problem is that `write` returns `int` for the number of bytes written. Perhaps the callback should expect `Callable[[bytes], Any]`

**Comment by JelleZijlstra** [comment]
Thanks for the report! Your suggestion sounds reasonable; feel free to test it with mypy and open a PR if it works. (The mention of "overloaded function" makes me think the problem might turn out to be more complicated, but we'll see.)
