### ISSUE TITLE
concurrent.futures stub exposes implementation details

### ISSUE THREAD

**Issue by pkch** [python/typeshed#1261]
[These definitions](https://github.com/python/typeshed/blob/c2e6a6f670f5d75c07eb31cf2509db302825b76d/stdlib/3/concurrent/futures/_base.pyi#L4L18) seem to unnecessarily expose some implementation details.

```
FIRST_COMPLETED = ...  # type: Any
FIRST_EXCEPTION = ...  # type: Any
ALL_COMPLETED = ...  # type: Any
PENDING = ...  # type: Any
RUNNING = ...  # type: Any
CANCELLED = ...  # type: Any
CANCELLED_AND_NOTIFIED = ...  # type: Any
FINISHED = ...  # type: Any
LOGGER = ...  # type: Any

class Error(Exception): ...

DoneAndNotDoneFutures = namedtuple('DoneAndNotDoneFutures', 'done not_done')

def wait(fs: Iterable[Future], timeout: Optional[float] = ..., return_when: str = ...) -> Tuple[Set[Future], Set[Future]]: ...
```

The `return_when` argument to `wait` shows as `str`. This means any string (including a typo) will be recognized as acceptable. In addition, `FIRST_COMPLETED`, `FIRST_EXCEPTION` and `ALL_COMPLETED` are shown as `type: Any`, which means they can accidentally be used anywhere without a type error. Perhaps it might be ok to make the nature of these objects opaque instead? Like this for example:

```
class CompletionType: ...
FIRST_COMPLETED = ...  # type: CompletionType
FIRST_EXCEPTION = ...  # type: CompletionType
ALL_COMPLETED = ...  # type: CompletionType
def wait(fs: Iterable[Future], timeout: Optional[float] = ..., return_when: CompletionType = ...) -> Tuple[Set[Future], Set[Future]]: ...
```

User code should never rely on `CompletionType` being implemented as `str`, so it should not cause any false type check errors. `CompletionType` can be exposed to the user to enable explicit typing of user variables that contain one of these constants.

All the other names (`PENDING`, etc.) are not part of the public API documented for `concurrent.futures`, so it's kinda strange to expose them to the user. They are needed by the other stubs though - is there a standard approach we use in such cases?

Overall, none of these points are a big deal, so if there's any downside to that, we can leave things as is.

**Comment by JelleZijlstra** [comment]
I usually bias towards making stubs reflect reality even if that means exposing implementation details. My first priority is to make sure people don't see errors on working code due to a faulty typeshed stub, even if their code relies on undocumented parts of the API (within reason).

I don't have a lot of experience with this particular module, but I don't think I'd merge a PR making the change you're describing.

**Comment by gvanrossum** [comment]
I'm mostly with Jelle on this one. We could change the type of `FIRST_COMPLETED` and friends to `str`, but I don't think we should introduce your `CompletionType`.

**Comment by pkch** [comment]
Yeah, with the emphasis on the incremental type checking, I can see why my changes could be counter-productive.

As for the change of type of `FIRST_COMPLETED` etc to `str`, that would only catch bugs where those constants are accidentally assigned or passed to the wrong variable/argument. Seems pretty far-fetched, but I can add a PR to make that change if someone thinks it's worth it.

**Comment by gvanrossum** [comment]
It might help if they are passed to the right functions in the wrong position (e.g. accidentally as timeout). You can easily add this to #1262.

**Comment by JelleZijlstra** [comment]
Seems like there is no change necessary here (@pkch correct me if I'm wrong).
