### ISSUE TITLE
Wrongly typed weight parameter of networkx shortest_paths algorithms

### ISSUE THREAD

**Issue by envelio-cb** [python/typeshed#12628]
The weight parameters of networkx' shortest_paths algorithms are typed "str",
but networkx also allows to define a callback for the weight parameter:

Callable[[_Node, _Node, dict[str, Any]], float | None]

So a union of str and this callback type would be a more appropriate type definition imho.

**Comment by srittau** [comment]
I haven't looked at this, but we welcome any PRs that improve our stubs.
