### ISSUE TITLE
Make getLogger optionally return provided custom class

### ISSUE THREAD

**Issue by Arshalok** [python/typeshed#12634]
Hi,

With the current approach when we do `logging.setLoggerClass(CustomLogger)` and later we use `logger = logging.getLogger()`, the returned type is Logger. I am aware that we can work around this with casting. However, if before setting up the logger we import module with `logger = logging.getLogger()` the returned class is Logger and not CustomLogger. Would it be possible to add an optional parameter to getLogger, so we can always return correct class?

Example:
`logger = logging.getLogger(klass=CustomLogger)`

Later on provided parameter value would take priority over self.loggerClass or _loggerClass.

**Comment by srittau** [comment]
Unfortunately, I don't see any way to make this possible with the current typing system. `getLogger` doesn't have a `klass` parameter at runtime, so we can't just add one to the stubs. This would break when running the code. I recommend to use `assert isinstance(logger, CustomerLogger)` on the returned object as that also adds a runtime test.

**Comment by Arshalok** [comment]
Sorry, I think I should've created this in cPython. I know we currently do not have klass parameter in getLogger, that's why  I proposed to add it. I will recreate this issue in the correct repo.
