### ISSUE TITLE
what is the best practice for cython-based library (i.e. lupa)

### ISSUE THREAD

**Issue by RedContritio** [python/typeshed#12648]
I hope to create a stub for the **lupa** library. However, this library is developed based on **Cython** and uses some Cython's built-in types such as `cyfunction` and so on. I wonder if there is an elegant way to solve this problem.

My thoughts:

1. Wait for the stub of the Cython library (seems to take a long time).
2. Customize a set of internal types to replace Cython's built-in types.
3. Use Python's built-in types to replace them according to their behaviors.

**Comment by srittau** [comment]
I assume you mean cython, not CPython. Personally, I have no experience with cython, but when a dependency is untyped, our usual approach is to add "dummy" type aliases for the types we required from the other library:

```python
Floop: TypeAlias = Any  # actually brarp.Floop
```
