### ISSUE TITLE
Please suppress the Pyright errors in `builtins.pyi`

### ISSUE THREAD

**Issue by tylerlaprade** [python/typeshed#12680]
Hi, I am getting 78 permanent errors any time I open up a Python project in VSCode. They are coming from `builtins.pyi` due to `reportIncompatibleMethodOverride`, `reportPrivateUsage`, and `reportOverlappingOverload`. I haven't found any way to ignore them in my `pyrightconfig.json`, and Eric Traut [pointed](https://github.com/microsoft/pylance-release/issues/6409#issuecomment-2359229911) me here.
<img width="524" alt="image" src="https://github.com/user-attachments/assets/5c3a637d-203f-49d8-bbce-8a48f2d0c43f">

**Comment by JelleZijlstra** [comment]
Sorry to send you back and forth, but I feel this is a configuration issue in your type checker. If you're not working on typeshed itself, you shouldn't be seeing errors in the typeshed code.

**Comment by Avasam** [comment]
The Pylance team is on the case 😃 https://github.com/microsoft/pylance-release/issues/6409
I'll close this as I also don't think there's anything to do on typeshed's side for this issue. But feel free to let us know if they find something needs to be changed on our side !
