### ISSUE TITLE
Shouldn't FileIO indicate None as possible return of read/write?

### ISSUE THREAD

**Issue by dcolascione** [python/typeshed#12684]
Typeshed currently has these declarations in `io.pyi` for `FileIO`.

```
    def write(self, b: ReadableBuffer, /) -> int: ...
    def read(self, size: int = -1, /) -> bytes: ...
```

Shouldn't these return `int | None` and `bytes | None`? A `FileIO` is non-blocking mode can return `None` from these methods, yes?

**Comment by tomasr8** [comment]
Looking at the code, both [read](https://github.com/python/cpython/blob/342e654b8eda24c68da64cc21bc9583e480d9e8e/Modules/_io/fileio.c#L875-L885) and [write](https://github.com/python/cpython/blob/342e654b8eda24c68da64cc21bc9583e480d9e8e/Modules/_io/fileio.c#L924-L934) return `None` when `EAGAIN` is raised so technically the return annotation should include `None` as well.

**Comment by srittau** [comment]
For reference, this is similar to what has been discussed in https://discuss.python.org/t/handling-sys-stdin-read-in-non-blocking-mode/59633.

**Comment by srittau** [comment]
Also related to #12414. PR: #12686
