### ISSUE TITLE
os.PathLike type hint incompatible with Python 3.8

### ISSUE THREAD

**Issue by bisrat-otterai** [python/typeshed#12691]
The current type hint for `os.PathLike` in Typeshed is not compatible with Python 3.8. When using `os.PathLike[str]` or `os.PathLike[bytes]`, Python 3.8 raises a `TypeError: 'ABCMeta' object is not subscriptable` error. This affects projects that need to support both Python 3.8 and older versions.

## Example
The following code works in Python 3.9+ but fails in Python 3.8:

```python
import os
from typing import Union

def example_function(file_path: Union[os.PathLike[str], os.PathLike[bytes], str, bytes]) -> None:
     try:
        os.remove(file_path)
    except FileNotFoundError as e:
        pass
    except OSError as e:
        pass
```

Error in Python 3.8:
```python
TypeError: 'ABCMeta' object is not subscriptable
```

### Environment
Python version: 3.8
Typeshed version: Latest

Is there a recommended way to access older versions of typeshed that are compatible with python 3.8?

**Comment by JelleZijlstra** [comment]
See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime for how to deal with this class of issues.

I'd also recommend to stop using 3.8 as it is going out of support in about a week :)
