### ISSUE TITLE
Use `Mapping[str, Any]` as a type hint for the `localns` argument of `typing.get_type_hints`

### ISSUE THREAD

**Issue by Viicos** [python/typeshed#12696]
Ultimately, the `localns` argument is passed to [`eval`](https://docs.python.org/3/library/functions.html#eval), expecting a mapping as the `locals` argument. Happy to send a PR.

**Comment by JelleZijlstra** [comment]
Agree, feel free to send a PR. Note that None is also still valid as a type for this parameter.
