### ISSUE TITLE
Support new version format: compatible releases (~= 2.7)

### ISSUE THREAD

**Issue by srittau** [python/typeshed#12708]
I propose that we support a new version format in addition to our two existing ones (`2.7.5` and `2.7.*`) that works similar to the asterisk one, but starting with a certain version (usually a patch version): `~=2.7.2`. `2.7.*` would be an equivalent to `~=2.7.0`.

See https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release.

### Semantics

The stub package version number is `{version, but at least three components}.{calver}`, e.g. `~=2.7.2` becomes `2.7.2.20240930` and `~=2.7` becomes `2.7.0.20240930`.

### Rationale

Sometimes, a patch version introduces API changes that we want to reflect in stubs. If this happens on a regular basis, we usually switch from version matches (`2.7.*`) to fixed version numbers (`2.7.2`). But for some packages this is a rare occasion and pinning the version would be a disservice. But it's still advantageous to represent the supported version numbers accurately, for making sure the tests pick up the correct packages, for documenting the supported packages accurately in the stubs package's README, and for representing the supported versions better in the stubs package's version number.

**Comment by Avasam** [comment]
proto-based stubs could benefit from this.
If the full version is specified, but with the `~=` (take any patch above) marker, google-protobuf and tensorflow's proto generation scripts could read directly from the METADATA.toml. (not s2clientprotocol though, because that one uses a commit hash)

**Comment by srittau** [comment]
stub_uploader PR:  typeshed-internal/stub_uploader#148
