### ISSUE TITLE
Make `is_dst` parameters of `pytz._FixedOffset` optional

### ISSUE THREAD

**Issue by robsdedude** [python/typeshed#12715]
If I've seen that right, in `pytz` all timezone classes' `.localize` and `.normalize` methods take `bool | None` as `is_dst` argument. All but `_FixedOffset`.

https://github.com/python/typeshed/blob/302e83f003c7ac78081643735a2a912982e90780/stubs/pytz/pytz/__init__.pyi#L33-L34

However, looking at pytz's code, this argument is just ignored for fixed time zones (so factually any type works). Semantically, `None` means (I quote the [docs](https://pythonhosted.org/pytz/))

> If you pass None as the is_dst flag to localize(), pytz will refuse to guess and raise exceptions if you try to build ambiguous or non-existent times.

So for fixed offset timezones it makes perfect sense to accept `None`. There'll just never be ambiguity or non-existence. Hence, why pytz ignores the parameter completely.

**Comment by srittau** [comment]
Sounds right. In fact, `_UTCclass.localize()` already accepts `None`. (Although it's missing the default. And `_UTCclass.normalize()` is completely missing the `is_utc` flag.)

Any PRs welcome!

**Comment by robsdedude** [comment]
I'll see if I can craft a PR in the coming days.
