### ISSUE TITLE
ctypes POINTER invalid incompatible type with None

### ISSUE THREAD

**Issue by caffeinepills** [python/typeshed#12736]
With type checkers (PyCharm's, MyPy) I get the error:
`mypy_test.py:6: error: Argument 1 to "POINTER" has incompatible type "None"; expected "type[Never]"  [arg-type]`

Using this simple example:
```
from ctypes import POINTER
void = None
POINTER(void)
```
`POINTER(None)` in ctypes is equivalent to `c_void_p` and is valid when ran. Minor issue but is technically a compatible type.

**Comment by junkmd** [comment]
Is this change reasonable?

https://github.com/python/typeshed/blob/dbd0d3521745288a3b2e345d8683bb9539d28d60/stdlib/_ctypes.pyi#L101-L102

```diff

+@overload
+def POINTER(type: None, /) -> type[c_void_p]: ...
+@overload
def POINTER(type: type[_CT], /) -> type[_Pointer[_CT]]: ...
```

**Comment by srittau** [comment]
I'm no expert for ctypes, but I think `c_void_p` (without `type`) is the correct return type:

```python
In [6]: POINTER(None) is c_void_p
Out[6]: True
```

**Comment by junkmd** [comment]
`ctypes.POINTER` returns a pointer type for the given `type`, based on the private `_pointer_type_cache` mapping.

The private function [`_reset_cache`](https://github.com/python/cpython/blob/19984fe024bfd90649f1c36b78c9abf3ed72b27d/Lib/ctypes/__init__.py#L277-L286) is [called when the module is loaded](https://github.com/python/cpython/blob/19984fe024bfd90649f1c36b78c9abf3ed72b27d/Lib/ctypes/__init__.py#L604) and clears that mapping, assigning `None` as the key and `c_void_p` as the value.

Therefore, I think it is reasonable that `POINTER(None)` returns `type[c_void_p]`.

I recently dived into the `ctypes` implementation while maintaining a project that needed to be updated to accommodate recent changes made to `ctypes`. This is where I gained this insight.

I'm planning to submit a PR regarding this.

**Comment by Avasam** [comment]
> I'm no expert for ctypes, but I think `c_void_p` (without `type`) is the correct return type:
> 
> ```python
> In [6]: POINTER(None) is c_void_p
> Out[6]: True
> ```

Come to think of it with fresh eyes. Doesn't that confirm the return is indeed the class to be instanciated? (represented by `type[c_void_p]`)?
```py
>>> import ctypes
>>> ctypes.POINTER(None) is ctypes.c_void_p
True
>>> isinstance(ctypes.POINTER(None)(), ctypes.c_void_p)
True
```
Let's do the same exercise with a simple type (`int`):
```py
>>> int is int
True
>>> isinstance(int(), int)
True
```

I'm not sure where the confusion was, maybe I was also too sleepy ^^"

**Comment by srittau** [comment]
> I'm not sure where the confusion was, maybe I was also too sleepy ^^"

You're completely right, of course. No idea why I was confused.
