### ISSUE TITLE
`setuptools.setup()` `libraries` parameter is wrong

### ISSUE THREAD

**Issue by Yay295** [python/typeshed#12752]
it should be `list[tuple[str, dict[str, Any]]]`

as seen in these files:
https://github.com/pypa/setuptools/blob/66a8aee91de7ed8b0f819fb836e5543212e4b860/setuptools/command/build_clib.py
https://github.com/pypa/setuptools/blob/66a8aee91de7ed8b0f819fb836e5543212e4b860/setuptools/_distutils/command/build_clib.py

The valid keys/values in that dictionary are:
```python
sources: list[str] | tuple[str]
obj_deps: dict[str, list[str] | tuple[str]]
macros: list[tuple[str, str] | tuple[str]]
include_dirs: list[str]
cflags: list[str]
```

**Comment by JelleZijlstra** [comment]
PR welcome, cc @Avasam for setuptools.

**Comment by Avasam** [comment]
Your assertion seems correct. Runtime validation is done here to be exact: https://github.com/pypa/setuptools/blob/66a8aee91de7ed8b0f819fb836e5543212e4b860/setuptools/_distutils/command/build_clib.py#L124-L149
