### ISSUE TITLE
Can't use csv.writer with --strict?

### ISSUE THREAD

**Issue by ns-cweber** [python/typeshed#1277]
When I use `mypy --strict` with a `csv.writer(text_io)`, I get the error `Call to untyped function "writer" in typed context`. I expected that since `csv.writer` is part of the standard library, it would be typed in typeshed, but either it's not typed or I'm misreading:

``` py
def writer(csvfile, dialect=..., **fmtparams): ...
```

Is it possible to work around this error?

**Comment by JelleZijlstra** [comment]
The Python 3 stubs for `writer` indeed lack type annotations, which is presumably why mypy complains about them in strict mode. The Python 2 stubs for csv are far more complete for whatever reason, but I don't think the csv module is actually significantly different between Python 2 and 3. Thus, the best solution to your issue would be to merge the Python 2 and 3 stubs into a single stub with full type annotations.
