### ISSUE TITLE
# TODO chain.from_Iterable

### ISSUE THREAD

**Issue by c-nixon** [python/typeshed#128]
Is there any way to implement this currently? I find I run into it quite often.

**Comment by gvanrossum** [comment]
Feel free to send us a pull request! Probably should update the stubs for Python 2 and 3.

**Comment by c-nixon** [comment]
I was wondering if there was a technical reason or if it just wasn't implemented, I'll have a look :)

**Comment by jstasiak** [comment]
I think https://github.com/python/typeshed/commit/17e74036f556b04c761fbde3bd1dc30ab6d15afd and https://github.com/python/typeshed/commit/dca8eeb1fe31b6731d9642a46c9e0606d36e4007 fix this?
