### ISSUE TITLE
unittest.mock.Mock keyword arguments incorrectly not accepted

### ISSUE THREAD

**Issue by JohannesEbke** [python/typeshed#1282]
Hi there,

When i typecheck `from unittest.mock import Mock; Mock(return_value=42)` using mypy 0.511 i get
> mock.py:1: error: Unexpected keyword argument "return_value" for "Mock".

I suspect that https://github.com/python/typeshed/blob/master/stdlib/3/unittest/mock.pyi#L66 is incorrect, and the `__init__` definition should be replaced with `...` so that the __init__ stubs of the base classes are picked up. If I do that in a local ./stub/ copy of unittest, it seems to work OK. Alternatively, all the valid arguments of Mock should be added.

Cheers,
Johannes

**Comment by JelleZijlstra** [comment]
Yes, that looks like a bug, thanks for reporting. Feel free to send a PR!

**Comment by JelleZijlstra** [comment]
Fixed by #1300.
