### ISSUE TITLE
Revisit conventions for comment headers in stub files

### ISSUE THREAD

**Issue by emilyemorehouse** [python/typeshed#1286]
It has been proposed to update the comment header formats used within the stub files. 

Thus far, we have determined that comments that include the applicable Python version are redundant (and in some cases are confusing or misleading), as the directory structure should inform which versions are relevant for a given stub. It could also be argued that the filename should also be sufficient to communicate that the file is a stub file and which module it applies to.

Therefore, we would like to open discussion on any information that is highly relevant to maintain in the comment headers or if they can be removed entirely.

**Comment by JelleZijlstra** [comment]
My preference is to remove the header comments entirely. The .pyi file extension should be sufficient to communicate that a file is a stub, and the directory structure is enough to indicate what Python versions the stub is for. The comments can be harmful because they may not get updated when the stub changes.

I'm open to persuasion otherwise though.

**Comment by gvanrossum** [comment]
I think all the comments we're seeing in the headers are mostly generated by stubgen. I don't see any value in them, the code speaks for itself, and often people forget to update these comments anyways. Out with them!

**Comment by JukkaL** [comment]
I'm agreeing with @JelleZijlstra. The comments may have been useful in the past when stub files were this totally new thing but now the `.pyi` extension and the location in the directory tree is enough. We should maybe also update stubgen to not generate these comments any more? The "generated by stubgen" comment also gets stale quickly.

**Comment by gvanrossum** [comment]
Not sure if we should remove that from stubgen. I think it should be enforced by the reviewer that those comments are removed before merging the PR though.

**Comment by emilyemorehouse** [comment]
Sounds good, I'll be working on this.

**Comment by gvanrossum** [comment]
Fixed by https://github.com/python/typeshed/pull/1292.
