### ISSUE TITLE
__pow__(float, float) should be float | complex, not Any

### ISSUE THREAD

**Issue by vbraun** [python/typeshed#12895]
Exponentiating a float with fractional power can be float or a complex, but nothing else:
 ```
In [1]: 1.0 ** 0.5
Out[1]: 1.0

In [2]: (-1.0) ** 0.5
Out[2]: (6.123233995736766e-17+1j)
```
But the result is currently typed as `Any`, but `float | complex` would be stricter and more self-explanatory

I don't see any technical reason for not doing so, maybe I'm missing something? But getting Any and then have `mypy --strict` complain about it is definitely a headscratcher.

Related issues:
* https://github.com/python/mypy/issues/12073
* https://github.com/python/mypy/issues/8034
* https://github.com/python/typeshed/issues/1406
* https://github.com/microsoft/pyright/issues/2643

**Comment by AlexWaygood** [comment]
We've tried this before, and it causes too many false positive errors unfortunately. Most people most of the time are only using `**` between two positive floats, so it's very confusing for those users to find that mypy infers the result as `float | complex` when they know it's a `float` at runtime. You can see some discussion in https://github.com/python/typeshed/pull/7682.

**Comment by Akuli** [comment]
Perhaps we could use `float | Any`.

**Comment by hauntsaninja** [comment]
See https://github.com/python/typeshed/pull/7682#issuecomment-1110304064 , int | Any could be worth a shot

**Comment by embray** [comment]
> Most people most of the time are only using ** between two positive floats, so it's very confusing for those users

I don't think we should be doing something wrong just because some users didn't learn basic maths
