### ISSUE TITLE
Bug in `ssl.set_psk_server_callback` `callback` type signature

### ISSUE THREAD

**Issue by timrid** [python/typeshed#12931]
According to the [Python 3.13 documentation](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.set_psk_server_callback) the type signature of the callback is `def callback(identity: str | None) -> bytes`. But currently it is defined as `Callable[[str | None], tuple[str | None, bytes]] | None` (see [here](https://github.com/python/typeshed/blob/355abb197eeabc406c3d03b65ff23245e6a38b4e/stdlib/_ssl.pyi#L107)).

**Comment by brianschubert** [comment]
Looks like like the callback type for `set_psk_client_callback` was accidentally duplicated. 

Are you interested in sending a PR?

**Comment by timrid** [comment]
It would take a while for me. If you could do it, that would be nice.
