### ISSUE TITLE
CONTRIBUTING.md still references runtests.sh, which no longer exists

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1296]
@emilyemorehouse Want to do something about this?

(Another thought about CONTRIBUTING.md is that the information in it should perhaps be rearranged to put the most import things first, since few people read the whole thing from top to bottom.)

**Comment by emilyemorehouse** [comment]
Already removed the runtests.sh references in #1293.

I can certainly look at reorganizing as well.

**Comment by gvanrossum** [comment]
Thanks, closing this one. The rest you can do at your leisure!
