### ISSUE TITLE
Review README.md for relevance and importance

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1297]
@emilyemorehouse If you want more ideas for editorial work, I suspect that the README.md could probably be improved for new users by reordering some things and perhaps removing some things?

**Comment by gvanrossum** [comment]
(Also CONTRIBUTING.md.)

**Comment by srittau** [comment]
@gvanrossum Is this bug still relevant?

**Comment by hauntsaninja** [comment]
CONTRIBUTING.md  and README.md recently got some love as part of #4132 and #3727, and have seen many changes since this issue was opened. The current state seems reasonable to me, but happy to reopen if anyone sees things that can be improved.
