### ISSUE TITLE
disallow `A().__class__ = B`

### ISSUE THREAD

**Issue by jorenham** [python/typeshed#12997]
The `object.__class__` getter is annotated to return `type[Self]`, while the setter accepts any argument that's assignable `object`.

https://github.com/python/typeshed/blob/300204c683daea533c842cba45f4504a89db2f5c/stdlib/builtins.pyi#L107-L110

As I also mentioned in https://github.com/microsoft/pyright/issues/9410#issuecomment-2466517948, this could lead to type-unsafe situation, e.g. 

```py
class A: ...
class B: ...
a = A()
a.__class__ = B
reveal_type(a.__class__)  # Type of "a.__class__" is "type[A]"
```

Pyright accepts this, as you'd expect by looking at the stubs ([playground link](https://basedpyright.com/?typeCheckingMode=all&code=MYGwhgzhAECCBc0B0KCwAoUkYCFEqQzGgF44AKASiKQH1asp7TocMAnAUwDdOwRaAFwCeAB07kwdBuCa1K0aAGJoAFTGdoAewBm0AERT6jCPX3QAljH0jxAbVgBdfUA)). 
However, mypy reports an error reports an error at `a.__class__ = B` ([playground link](https://mypy-play.net/?mypy=latest&python=3.12&gist=c7e37a56b788fc1ab704c547fa5104e0)), so I'm guessing it special-cased it.

At runtime the `__class__` behaves just like any other attribute, i.e. invariantly, when getting/setting. 
So that's why I think that `object.__class__` should be more "self-centered", and only accept `type[Self]` in its setter. 

---

As for a practical use-case; I recently came up with the following trick. But at the moment, this unexpectedly requires adding `# type: ignore`s with both pyright and mypy:

```py
from typing import Protocol, override

class Just[T](Protocol):  # ~T@Just is invariant
    @property  # type: ignore[override]
    @override
    def __class__(self, /) -> type[T]: ...  # pyright: ignore[reportIncompatibleMethodOverride]
    @__class__.setter
    def __class__(self, t: type[T], /) -> None: ...

def only_ints_pls(x: Just[int], /):
    assert type(x) is int

only_ints_pls(42)  # true negative
only_ints_pls("42")  # true positive (sanity check)
only_ints_pls(False)  # true positive (only in mypy at the moment)
```

playgrounds:

- [mypy](https://mypy-play.net/?mypy=latest&python=3.12&gist=a9f9282184d202787b0d31c821ab0977)
- [pyright](https://basedpyright.com/?typeCheckingMode=all&code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAK4MYAxmADYA0UYAbgKYghIAmDAsAFDekUCGAZ0FQAUgFdBMANoAVALoAKImBLkKASgBcUKAGIoAP1kABCVMwjUdfi34oY3XbpMJwCJvF0H4HnUjQUXAZpeiYWdnknZxMw5jZOLmcodmAoAH10viFBTMVBBgpgGgB6DSgAWgA%2BWEQQhR0AOmbvKAQ4FjQACxh-QODpEAYcPABJFHJsfhgkACMKBgBZBhgusFYAeUZ4yOiXTOzhTMaCmBgmPZSGNIOBI-T8wuLYHV96%2BVLy6qgAOTAUBhNZrcbipWgoChwdKoGC5BAUQSKAAeOnMMhhHygZS0lxynlqHmR5SQVgcIK4-0h0IccIRigALAAmcr6WAgcQMKAAtDTJCMbiUqEw2mIgBETNFLJ87M5OEESBmjCg%2BXsCrgUFIXQYpAA1hoBRChTT0vDEQAxfgIhhStkctpgeWKzmKVBQCCIOAaIA)

**Comment by Daverball** [comment]
The reason mypy reports an error, is because mypy doesn't support asymmetric properties, it will only use the annotation from the getter, so mypy already works the way you want it to by accident.

I agree however that it seems better to only allow `type[Self]` for the setter, even if that doesn't reflect what's legal at runtime, since the only runtime requirement is a compatible object layout, it at least means as long as a subclass doesn't violate LSP it should be type safe to assign a subclass.

If you want to do an unsafe assignment you can still do it, you'll just have to ignore the type error.

**Comment by jorenham** [comment]
> The reason mypy reports an error, is because mypy doesn't support asymmetric properties, it will only use the annotation from the getter, so mypy already works the way you want it to by accident.

Perhaps this could also explain why this hasn't been brought up before (as far as I could tell) 🤔

**Comment by srittau** [comment]
An exploratory PR couldn't hurt. To me, changing the setter types seems fine.

**Comment by jorenham** [comment]
the mypy primer seems to like it

**Comment by hauntsaninja** [comment]
As Daverball mentions, mypy doesn't model setters of properties correctly, so it already works the way you want it to

**Comment by jorenham** [comment]
> As Daverball mentions, mypy doesn't model setters of properties correctly, so it already works the way you want it to so primer is a no-op

Does that mypy bug also apply to inheritance, `Protocol` matching, and other LSP things?

**Comment by Daverball** [comment]
Yes, also I wouldn't call it a bug per se, it's a difference between mypy's type model and python's object model of properties. I assume this was originally an intentional design choice, so mypyc can always optimize properties a certain way.
