### ISSUE TITLE
Extend google.protobuf to minimally describe the runtime_version internal module

### ISSUE THREAD

**Issue by blast-hardcheese** [python/typeshed#13045]
I'm pursuing better type coverage for mypy-protobuf generated stubs.

[runtime_version](https://github.com/protocolbuffers/protobuf/blob/8b2efee24ce33f9e284651969684143bcd74fc49/python/google/protobuf/runtime_version.py#L8-L12) seems to have been added in protobuf v27.0, and even though it's only intended for internal use, the lack of typing is still causing red squiggles.

What options do I have for either selectively skipping typechecking for "internal" types or would it be preferable to correctly model the exposed types in that module and mirror the comments suggesting that the module isn't intended for public consumption?

Thank you in advance

**Comment by JelleZijlstra** [comment]
If the types in that module are visible to user code, then we should add them to our stubs. PR welcome.
