### ISSUE TITLE
اینجا اندازه این داخل رفتن تکسچر با آن تکسچر یکی باشد 

### ISSUE THREAD

**Issue by amiraaivg** [python/typeshed#13102]
![image](https://github.com/user-attachments/assets/5e7728b8-a4b4-4c1e-8c18-0ff51523260b)

**Comment by amiraaivg** [comment]
به تکسچر ها نگاه کن

**Comment by AlexWaygood** [comment]
@python/organization-owners, please could you ban this user for us? It's been a long string of issues like this over the last few days and they haven't responded to our comments asking for them to stop: https://github.com/python/typeshed/issues?q=is%3Aissue+author%3Aamiraaivg+

**Comment by srittau** [comment]
I set a 3 day interaction limit for new users for typeshed for now.

**Comment by srittau** [comment]
I also reported the use to GitHub.

**Comment by srittau** [comment]
> I set a 3 day interaction limit for new users for typeshed for now.

Which seemed to have done exactly nothing. I've enacted a 24h limit to previous contributors, also I plan to lift it in about an hour or so manually. Please remind me (or notify @JelleZijlstra) if I forget to do so.

**Comment by ambv** [comment]
Blocked.

**Comment by AlexWaygood** [comment]
Thanks so much @ambv!
