### ISSUE TITLE
gzip typing bug

### ISSUE THREAD

**Issue by mixilchenko** [python/typeshed#13175]
Tested with current mypy master branch so expect this to be gzip typeshed issue
https://mypy-play.net/?mypy=master&python=3.12&gist=70da9510c4f58b83d228114fed09afe4

```python
from pathlib import Path
import gzip

with gzip.open('abc', 'rt') as f:
    for line1 in f:
        reveal_type(line1)
        
with (
    Path('abc').open('rb') as bf,
    gzip.open(bf, 'rt') as f,
):
    for line2 in f:
        reveal_type(line2)
```
Result
```
main.py:6: note: Revealed type is "builtins.str"
main.py:13: note: Revealed type is "Union[builtins.bytes, builtins.str]"
```
Expected
```
main.py:6: note: Revealed type is "builtins.str"
main.py:13: note: Revealed type is "builtins.str"
```

**Comment by srittau** [comment]
Thanks for the report. It seems we are missing `_ReadableFileobj | _WritableFileobj` from the third overload. We should also return the concrete `TextIOWrapper` instead of pseudo-protocol `TextIO`. I'll prepare a PR.
