### ISSUE TITLE
python-gflags is no longer updated and obsolete.

### ISSUE THREAD

**Issue by kbaikov** [python/typeshed#13185]
See the message in https://github.com/google/python-gflags

According to the `contibuting.md` the next steps are:
1. wait for this issue to be labeled by a maintainer.
2. create a PR with `no_longer_updated = "true"` in the metadata.toml
3. wait a day and create a removal PR.

Is my understanding correct?

**Comment by Avasam** [comment]
> Is my understanding correct?

Correct :)
As a bonus, it might be nice to include a similar message as the project's readme given there's a migration path. Something like:
```toml
extra_description = """\
`python-gflags` has been merged into
[Abseil Python Common Libraries](https://github.com/abseil/abseil-py).

Please see [the guidelines](absl_migration/migration_guidelines.md)
for migrating to [Abseil](https://github.com/abseil/abseil-py)."""
```

**Comment by srittau** [comment]
I've forced an update of the package on PyPI: https://pypi.org/project/types-python-gflags/. @kbaikov Do you want to send a PR to remove the stubs here?

**Comment by kbaikov** [comment]
> I've forced an update of the package on PyPI: https://pypi.org/project/types-python-gflags/. @kbaikov Do you want to send a PR to remove the stubs here?

@srittau yes, i will send the PR
