### ISSUE TITLE
pexpect: spawn.exitstatus should be `int` or `None`

### ISSUE THREAD

**Issue by SchoolGuy** [python/typeshed#13200]
While the title was formulated very assertively, this is more of a question as I am not 100% sure if my observation is correct.

If I [search the codebase](https://github.com/search?q=repo%3Apexpect%2Fpexpect%20exitstatus&type=code) then I do believe that the field `exitstatus` is a union type of `int` and `None`. Before submitting a full-blown PR I'd like to get confirmation that this observation is correct and the change would be seen as valid - if submitted.

**Comment by JelleZijlstra** [comment]
Looks correct to me from a glance at your search results. The documentation appears quite explicit that this attribute can be None. PR welcome!

**Comment by max-muoto** [comment]
Put up a PR fixing this.

**Comment by brianschubert** [comment]
@max-muoto for future reference: the OP expressed an interest in fixing this. It's a bit impolite to open a PR without giving them a chance to do so.

**Comment by max-muoto** [comment]
> @max-muoto for future reference: the OP expressed an interest in fixing this. It's a bit impolite to open a PR without giving them a chance to do so.

Appreciate the callout, should have waited a little longer here.
