### ISSUE TITLE
`inspect.iscoroutine` does not work for `Coroutine`s?

### ISSUE THREAD

**Issue by PerchunPak** [python/typeshed#13238]
```py
import types
import inspect
from typing import Any, Coroutine


async def example1[T](to_call: Coroutine[Any, Any, T] | T) -> T:
    if inspect.iscoroutine(to_call):
        return await to_call
    return to_call # <- Type "Coroutine[Any, Any, T@example1] | object*" is not assignable to type "T@example1"

async def example2[T](to_call: types.CoroutineType[Any, Any, T] | T) -> T:
    if inspect.iscoroutine(to_call):
        return await to_call
    return to_call
```

https://pyright-play.net/?code=JYWwDg9gTgLgBDAnmApgZwFCkrOwB2aqAxjBgGZQQgLIEDme408AgvogDRwDC0EAVxgEUGMQEM0ifMTgATFOTgoAHuPAAbFAEYA2gBUAugAoYEAPrFxGjQC5e-ISN3sucV9yNwAPnH0BKOABaAD4-Www4KLwlAiIUUgA6YDRiR2F8FFMLKxt-COjCuCgUGAEofDhxAHdxYHgzS2sNSOiSsoqEHOaJKRl5RWU1TRQAJgMTRty7WlQ0RL4qJ0z9ZBQXDm4PP0MfP0DQ8Nao4FjCEhhk1PSRbKa8gqKo9vLKmrqG7ptj4tLXrvuGiAA

Looks like `inspect.iscorountine` has a type guard for `CoroutineType`, which is a subclass of `Coroutine` and this is why it is not compatible. Is there any runtime difference or this is a bug?

**Comment by JelleZijlstra** [comment]
This is correct; see the runtime definition of `iscoroutine` here: https://github.com/python/cpython/blob/ba2d2fda93a03a91ac6cdff319fd23ef51848d51/Lib/inspect.py#L360

The `Coroutine` ABC could in theory have other implementations than `types.CoroutineType`.
