### ISSUE TITLE
Pow can return int with positive integer

### ISSUE THREAD

**Issue by moi15moi** [python/typeshed#13253]
When I run the mypy strict mode like this ``mypy --strict my_file.p``y on this code:
```py
def my_function(x: int) -> int:
    if x < 0:
        raise ValueError("x needs to be higher than 0.")
    return 10 ** x

value = my_function(20)
```
I get this error:
```py
Untitled-1.py:4: error: Returning Any from function declared to return "int"  [no-any-return]
Found 1 error in 1 file (checked 1 source file)
```

I don't understand why it happen.
A positive integer exponent another positive integer will always return a integer, so why does the typing is Any?

PS: I'm not sure if this is the right repos to discuss about this problem, but someone from the python discord told me to open it here.

**Comment by JelleZijlstra** [comment]
Type checkers don't have a concept of "positive integer"; they just know that `x` is an int and don't narrow on the `x < 0` check. (There are type systems that could support such a thing, but most type checkers in Python don't do this.)

Type checkers then look at the definition of `int.__pow__` in this repo (typeshed) to figure out what type to return. That's here:
https://github.com/python/typeshed/blob/fc11e835108394728930059c8db5b436209bc957/stdlib/builtins.pyi#L290

We have hardcoded support for some specific positive integers, but in your case we'll fall back to the last overload, which returns Any.

Mypy's `no-any-return` is a very strict and getting it passing is often difficult.
