### ISSUE TITLE
tkinter.simpledialog how to fix question

### ISSUE THREAD

**Issue by kbaikov** [python/typeshed#13302]
I was trying to fix these entries in the common.txt allowlist:

```tkinter.simpledialog.[A-Z_]+
tkinter.simpledialog.TclVersion
tkinter.simpledialog.TkVersion
```

However i am not sure how. I think the main issue is the star import here: https://github.com/python/cpython/blob/5c814c83cdd3dc42bd9682106ffb7ade7ce6b5b3/Lib/tkinter/simpledialog.py#L26

Possible solutions:
- I can do the same star import in `simpledialog.pyi` and and other stuff like `from tkinter.constants import *` ands silence the unused imports with a pragma.
- Or i can redefine those constants the second time in the simpledialog.pyi.

Need a guidance from the gurus: what is the preferred solution? Perhaps some other common way to fix it?
A link to some similar issue solved in typeshed should be enough.

**Comment by JelleZijlstra** [comment]
Most likely we should just not fix these. The constants are present at runtime due to this star import, but they shouldn't be part of the exposed API of the module.

**Comment by kbaikov** [comment]
Ah, ok.
I was then confused that the tkinter.simpledialog.... is under the:

```# ============================================
# TODO: Allowlist entries that should be fixed
# ============================================
```
section of the common.txt allowlist.
