### ISSUE TITLE
ujson.dumps double_precision

### ISSUE THREAD

**Issue by llchan** [python/typeshed#1332]
https://github.com/python/typeshed/blob/890190d3493e7f9cafbe8049a9f7a4dfcd62f94d/third_party/2and3/ujson.pyi#L20

I think `double_precision` should be an int.

**Comment by llchan** [comment]
(There several instances of this in `ujson.pyi`).

**Comment by ShyPixie** [comment]
What happened here? These changes are not on master anymore
