### ISSUE TITLE
Stub for `locale.format` limits type of `val` argument too much

### ISSUE THREAD

**Issue by homeworkprod** [python/typeshed#1350]
Mypy complains:
```error: Argument 2 to "format" has incompatible type "Decimal"; expected "int"```

Code basically is:
```python
from decimal import Decimal
import locale

a = Decimal('27.12345')
locale.format('%.2f', a)  # returns '27.12'
```

The [stub file for `locale`](https://github.com/python/typeshed/blob/c1944f944ecb867345c83d173afc72028557857d/stdlib/2and3/locale.pyi#L94) defines:
```python
def format(format: _str, val: int, grouping: bool = ..., monetary: bool = ...) -> _str: ...
```

But [the docs state](https://docs.python.org/3/library/locale.html#locale.format):
> Formats a number val according to the current LC_NUMERIC setting. The format follows the conventions of the % operator. For floating point values, the decimal point is modified if appropriate.

That is, the value can be a(ny) number; a float is explicitly mentioned. Above code works on Python 2.7.9 and 3.4.4, so `Decimal` seems to be supported, too.

What I'm not sure about is which types *exactly* are accepted. But `int` clearly is too limited.

**Comment by JelleZijlstra** [comment]
I'd be happy to change the stub to say `float`, and I suppose we can add a Union with Decimal too. Be warned though: the type system doesn't have good support for the numeric tower in general.

**Comment by homeworkprod** [comment]
Sounds fair.

**Comment by homeworkprod** [comment]
Thank you! mypy 0.520 fixes the above issue for me.
