### ISSUE TITLE
typeshed annotations do not permit instantiation of urllib.error.HTTPError

### ISSUE THREAD

**Issue by carljm** [python/typeshed#1377]
Currently in typeshed, [urllib.error.HTTPError is (accurately) annotated](https://github.com/python/typeshed/blob/master/stdlib/3/urllib/error.pyi#L8) as inheriting both `URLError` and `urllib.response.addinfourl`. The `addinfourl` class inherits `addbase`, which [is annotated](https://github.com/python/typeshed/blob/master/stdlib/3/urllib/response.pyi#L6) as inheriting [typing.BinaryIO](https://github.com/python/typing/blob/master/src/typing.py#L2312). This appears to be an attempt to deal with the fact that `addbase` [actually inherits](https://github.com/python/cpython/blob/master/Lib/urllib/response.py#L14) the (private) `tempfile._TemporaryFileWrapper`, which is supposed to wrap a "file-like object", and [proxies all attribute access to the wrapped object](https://github.com/python/cpython/blob/master/Lib/tempfile.py#L473).

This makes some sense: `BinaryIO` is supposed to be the typing "definition" of what "file-like object" means (at least in binary mode). And this works OK for type-checking code that accesses "file-like" methods on an `HTTPError` instance. But it makes it impossible to actually instantiate an `HTTPError` without a spurious mypy error, because the methods of `typing.BinaryIO` (and its parent `typing.IO`) [are all decorated as @abstractmethod](https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L393), and most of them are not overridden by the typeshed annotation of `addbase` or `addinfourl`.

So if you type-check this code (which works fine at runtime):

```
from io import StringIO
from urllib.error import HTTPError

http_error = HTTPError("", 500, "message", dict(), StringIO(''))
```

mypy gives you:

```
error: Cannot instantiate abstract class 'HTTPError' with abstract attributes '__enter__', '__exit__', ... and 'writelines' (16 methods suppressed)
```

I'm filing an issue rather than going straight to pull request because the correct fix here isn't obvious to me, and I'm hoping someone with more typeshed experience can offer a preferred solution. If so, I'm happy to implement it. The obvious solution seems to be repeating all the method definitions from `typing.BinaryIO` and `typing.IO` in the typeshed annotation for `addbase`, without `@abstractmethod`, but I'm hoping there might be an option that avoids this duplication.

**Comment by JelleZijlstra** [comment]
I don't know of a better solution than the one you propose. Perhaps there should be a concrete BinaryIO class that we can inherit from though.

More broadly, it would be good to have an automated way to find classes that can't be instantiated because of abstractmethods—this isn't the first time we found a class that hit this problem.

**Comment by carljm** [comment]
If I created such a concrete `BinaryIO`, any ideas where to put it? I assume it would belong in typeshed, not typing, since it's not something that should actually be instantiated; I'm not sure if there's an existing pattern for where we put things that don't actually exist but are a convenient typeshed fiction. Maybe just directly in `typing.pyi` as `_ConcreteBinaryIO`?

**Comment by gvanrossum** [comment]
IMO we should not make up a concrete BinaryIO class, but we should restructure the class hierarchy in io.pyi to make more sense (I think `BufferedRandom` should inherit from BinaryIO, and there are several other issues with the class hierarchy there).
