### ISSUE TITLE
FunctionType and MethodType are not compatible with Callable

### ISSUE THREAD

**Issue by carljm** [python/typeshed#1378]
I tried to fix this in #1207, but `typing.Callable` is not a valid base class, and attempting to use the `Callable` ABC instead ran into what look like dependency-cycle problems in mypy. This should be fixed by protocols (presuming that the callable protocol would be satisfied by the existence of a `__call__` method), so I haven't pursued any other fix further. Just opening this to track the problem.

**Comment by JelleZijlstra** [comment]
This seems to have been fixed by protocols:
```
$ cat samples/callable.py 
from typing import Callable, Any
from types import FunctionType, MethodType

ft: FunctionType
mt: MethodType

def takes_callable(c: Callable[..., Any]) -> None:
    ...

takes_callable(ft)
takes_callable(mt)

$ mypy samples/callable.py 
$
```
