### ISSUE TITLE
csv.DictReader.__init__ return type

### ISSUE THREAD

**Issue by llchan** [python/typeshed#1381]
[`csv.DictReader.__init__`](https://github.com/python/typeshed/blob/37fc02ea7ec35538234e9bda7a3e9ee17ef4a5c5/stdlib/3/csv.pyi#L54) is missing its return type of `None`

**Comment by JelleZijlstra** [comment]
More importantly perhaps, it's also missing annotations for all of its argument types. PRs are welcome.

**Comment by llchan** [comment]
Yep, you're right. I just noticed that `reader = csv.DictReader(f)` can back with a type of `Any` and assumed it was a return type issue, but the func stub is just missing types for everything.

**Comment by llchan** [comment]
Unfortunately I can't submit PRs easily due to company policy, so I'll have to just report for now. This may change in the future.

**Comment by JelleZijlstra** [comment]
Fixed by #1398.
