### ISSUE TITLE
Wrong interface for AsyncIterable

### ISSUE THREAD

**Issue by ask** [python/typeshed#1396]
In mypy AsyncIterable has an `__anext__` method, but it should not: it should have `__aiter__` only, but that is missing.

The code here:
https://github.com/python/typeshed/blob/0709985d0c676127eae16e18e5710416a9ec6da8/stdlib/3/typing.pyi#L156-L164

Should be:

```py
class AsyncIterable(Generic[_T_co]):
    @abstractmethod
    def __aiter__(self) -> 'AsyncIterator[_T_co]': ...

class AsyncIterator(AsyncIterable[_T_co],
                    Generic[_T_co]):
    @abstractmethod
    def __anext__(self) -> Awaitable[_T_co]: ...
    def __aiter__(self) -> 'AsyncIterator[_T_co]': ...
```

I will try to figure out how to contribute a patch and tests :-)

**Comment by gvanrossum** [comment]
Could you show a small code fragment (or two) showing how the current stub
is wrong, demonstrating that it works at runtime? A PR would also be
welcome but the demonstration is key.

**Comment by ask** [comment]
I have the fix already and I could easily submit a PR, but I'm not sure where the tests go?

Would I add these tests to mypy perhaps?  The test instructions mention running the mypy tests.

I will try to think of a code fragment also, but is not `_collections_abc` the canonical reference here:

https://github.com/python/cpython/blob/2e9cd5825c5ccdbb6f65a57c0c7941078e003c14/Lib/_collections_abc.py#L158-L170

There AsyncIterable has `__aiter__`, (no `__anext__` as typeshed has as the only method),

**Comment by gvanrossum** [comment]
There is no convenient place to put the tests, I just want you to show the test code you ran manually to demonstrate that there is code that works at runtime but that is wrongly rejected by Python, to support this issue. You can put it in the introduction for the PR you submit. (Also link to this issue of course.)
