### ISSUE TITLE
passing unicode to some of the stdlib functions produces incorrect mypy error in python 2.7

### ISSUE THREAD

**Issue by manu-chroma** [python/typeshed#1411]
This issue highlights few incorrect stubs in Python 2 ``stdlib`` stub files. Most of these are related to passing ``unicode`` string to ``stdlib`` functions which work correctly at runtime, but ``mypy`` shows unsupported type. (because stub files have mentioned ``str`` as the only allowed type)  
List of the errors 
- [ ] The docs mention that for ``urlunsplit`` function, ``The parts argument can be any five-item iterable.``
relevant docs link: https://docs.python.org/2/library/urlparse.html#urlparse.urlunsplit
current stubs for the function: https://github.com/python/typeshed/blob/master/stdlib/2/urlparse.pyi#L58
There might be other functions in the ``urlparse`` which might have similar bug. 

- [ ] passing unicode string in ``open()`` builtin and as ``key`` to a dict. 
**test.py**
``` python
from __future__ import unicode_literals
from typing import Any, Text

def hello(name, **kwargs):
    # type: (Text, **Any) -> None
    with open(name, 'w') as r:
        pass

    b = kwargs.get('foo', 'nil')

hello("wow", foo="bar")
```
**output**
``` bash
 ~  mypy --py2 test.py                                                                                                        
test.py:6: error: No overload variant of "open" matches argument types [builtins.unicode, builtins.unicode]
test.py:9: error: No overload variant of "get" of "Mapping" matches argument types [builtins.unicode, builtins.unicode]
``` 
*Updated issue to include other found errors*

**Comment by ethanhs** [comment]
(As mentioned on gitter, the taker of this should also look at whether this method takes unicode)

**Comment by manu-chroma** [comment]
In my code, I pass ``Tuple[str, str, str, str, unicode]`` for ``parts`` argument and it seems to work correctly.

**Comment by JelleZijlstra** [comment]
I'm about to submit PRs to fix two of the issues you mentioned.

I'm not sure your third issue (using unicode keys for a **kwargs dict) can be fixed in typeshed. The hack proposed in python/mypy#3619 will probably fix it though.

**Comment by JelleZijlstra** [comment]
See also python/mypy#1954.

**Comment by JelleZijlstra** [comment]
Both of the functions mentioned are fixed.

**Comment by mehdigmira** [comment]
same issue for:
* attrgetter() function of operator library
* CDLL() function of ctypes
