### ISSUE TITLE
Missing stub for multiprocessing.get_context()

### ISSUE THREAD

**Issue by khyox** [python/typeshed#1422]
Following suggestion in [mypy #3564](https://github.com/python/mypy/issues/3564).

Repro:
```python
import multiprocessing
import os

METHODS = ['spawn', 'fork', 'forkserver']

if __name__ == '__main__':
    for method in METHODS:
        context = multiprocessing.get_context(method)
        with context.Pool(processes=4) as pool:
            results = [pool.apply_async(os.getpid, ()) for i in range(4)]
            print([res.get(timeout=1) for res in results], method)
```
mypy with ```--check-untyped-defs``` or with ```--disallow-untyped-defs``` complains with the single message ```...:8:18:error: Module has no attribute "get_context"```.

**Comment by gvanrossum** [comment]
Thanks for the report -- do you think you will be able to contribute a Pull Request to fix this?

**Comment by khyox** [comment]
Thanks for the opportunity! If it is not urgent to close this issue, then I can try, otherwise, please, feel free to fix it.
