### ISSUE TITLE
Classes should not inherit from Any

### ISSUE THREAD

**Issue by ethanhs** [python/typeshed#1446]
Several classes in typeshed inherit from `Any`, and should not.

```
$ ag "class .*\(Any\)"
stdlib\3\multiprocessing\context.pyi
118:    class ForkProcess(Any):  # type: ignore
124:    class SpawnProcess(Any):  # type: ignore
130:    class ForkServerProcess(Any):  # type: ignore
148:    class SpawnProcess(Any):  # type: ignore

stdlib\3\types.pyi
81:class SimpleNamespace(Any): ...  # type: ignore

stdlib\3\unittest\mock.pyi
34:    class NonCallableMock(Any):

tests\pytype_blacklist.txt
11:# Because of 'class ForkProcess(Any):  # type: ignore'

third_party\3\jwt\algorithms.pyi
3:class Algorithm(Any): ...  # type: ignore
```

As can be seen, all but one of these are type-ignore'd and thus not picked up by mypy.

The multiprocessing classes have `# TODO: type should be BaseProcess once a stub in multiprocessing.process exists`, so that should be okay to change, as that module is there. 

The `types.pyi` `SimpleNameSpace` needed my `__setattr__` implementation.

Apparently the same for `NonCallableMock`

JWT stubs just seem very incomplete.

**Comment by JelleZijlstra** [comment]
Feel free to send some PRs. :)

**Comment by hauntsaninja** [comment]
Looks like it's only the protobuf containers one left. Is it worth adding a test to prevent the addition of Any others?

**Comment by srittau** [comment]
I think adding a test to flake8-pyi would make sense.

**Comment by ethanhs** [comment]
Mypy also has a flag to disallow this, which could perhaps be switched off for the single stub.

**Comment by JelleZijlstra** [comment]
It would be better to turn on mypy's `--disallow-subclassing-any` flag (maybe with a type ignore for the protobuf ones).

**Comment by srittau** [comment]
Good point.
