### ISSUE TITLE
No stubs for mysql

### ISSUE THREAD

**Issue by jukebox** [python/typeshed#146]
```
⌁ [juke:~/minimysqconnector] 1 % cat mini.py                              
from mysql.connector import connect
⌁ [juke:~/minimysqconnector] % mypy mini.py               
mini.py:1: error: Cannot find module named 'mysql.connector'
mini.py:1: note: (Perhaps setting MYPYPATH would help)

```

**Comment by gvanrossum** [comment]
There are no stubs for mysql at all. Would you mind asking the mysql project for permission to add stubs to typeshed? (This is needed because of a policy set in PEP 484: https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo; see also the README.md file in the typeshed repo.)

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
