### ISSUE TITLE
Missing function on pkg_resources.EntryPoint

### ISSUE THREAD

**Issue by danpalmer** [python/typeshed#1463]
Hi, while checking the code:

```python
def get_plugins(config):
    for key, value in config.items():
        entry_point_line = '%s = %s' % (key, value)

        entry_point = pkg_resources.EntryPoint.parse(entry_point_line)
        yield entry_point.name, entry_point.resolve
```

I get the following output:

```
plugins.py:19: error: "EntryPoint" has no attribute "resolve"
```

Checking setuptools, it looks like the function is there https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L2305.

It looks like the original setuptools typing here did include it, but that it was removed in a62d6207abb6ec9bde771a9dafe355e9785ea2ef.

**Comment by JelleZijlstra** [comment]
Thanks for reporting this! The function is also documented in http://setuptools.readthedocs.io/en/latest/pkg_resources.html#entrypoint-objects. I guess the removal was by accident; could you write a PR to add it back?

**Comment by qria** [comment]
Any work on this?
