### ISSUE TITLE
Mypy does not accept `mmap` object in `re.match`

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#1467]
It seems that the `re.compile` types are to restrictive, the following code errors in mypy but running it is no problem:
```python
# _txt_fmt is a object gotten from `re.compile`
with open(file, 'r+') as f:
    with mmap.mmap(f.fileno(), 0) as data:
        match = _txt_fmt.match(data)
```

Mypy gives the error `Argument 1 to "match" of "Pattern" has incompatible type "mmap"; expected "bytes"`.

**Comment by srittau** [comment]
Full example:

```python
import mmap
import re

with open("...", 'r+') as f:
    with mmap.mmap(f.fileno(), 0) as data:
        match = re.compile(b"").match(data)
```

The [mmap documentation](https://docs.python.org/3/library/mmap.html) explicitly mentions the interaction with re: "You can use mmap objects in most places where bytearray are expected; for example, you can use the re module to search through a memory-mapped file." So I believe we should fix this.

**Comment by pavel-razgovorov** [comment]
Hello. Any update on this?

**Comment by srittau** [comment]
PR welcome!

**Comment by itaisteinherz** [comment]
I'd like to work on this.
