### ISSUE TITLE
Accidentally abstract classes

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#1476]
We've had several issues where mypy produces incorrect "Cannot instantiate abstract class" errors because of faulty typeshed stubs (e.g., #1379, #1160, #351, #1475). To find more bugs like those, I hacked mypy (https://github.com/JelleZijlstra/mypy/commit/1fa9c65ea9db9d9024556002e39ab58b5c33997c) to error on any class with abstract methods. Here are the results for 3.6, excluding private classes and those clearly intended to be abstract:

- [x] `stdlib/3/collections/__init__.pyi:62: error: Class collections.UserDict has abstract attributes ['__delitem__', '__getitem__', '__iter__', '__len__', '__setitem__']`
- [x] `stdlib/3/collections/__init__.pyi:63: error: Class collections.UserList has abstract attributes ['__delitem__', '__getitem__', '__len__', '__setitem__', 'insert']`
- [x] `stdlib/3/collections/__init__.pyi:64: error: Class collections.UserString has abstract attributes ['__getitem__', '__len__']`
- [x] `third_party/2and3/requests/structures.pyi:5: error: Class requests.structures.CaseInsensitiveDict has abstract attributes ['__delitem__', '__getitem__', '__iter__', '__len__', '__setitem__']`
- [x] `third_party/2and3/pytz/lazy.pyi:6: error: Class pytz.lazy.LazyDict has abstract attributes ['__getitem__', '__iter__', '__len__']`
- [x] `stdlib/2and3/codecs.pyi:205: error: Class codecs.StreamReaderWriter has abstract attributes ['close', 'fileno', 'flush', 'isatty', 'readable', 'seekable', 'tell', 'truncate', 'writable']`
- [x] `stdlib/2and3/codecs.pyi:221: error: Class codecs.StreamRecoder has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']`
- [x] `stdlib/2and3/bz2.pyi:14: error: Class bz2.BZ2File has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']`
- [x] `stdlib/3/urllib/response.pyi:6: error: Class urllib.response.addinfourl has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']`
- [x] `stdlib/3/http/cookies.pyi:21: error: Class http.cookies.BaseCookie has abstract attributes ['__delitem__', '__getitem__', '__iter__', '__len__']`
- [x] `stdlib/3/http/cookies.pyi:31: error: Class http.cookies.SimpleCookie has abstract attributes ['__delitem__', '__getitem__', '__iter__', '__len__']`
- [x] `stdlib/3.4/tracemalloc.pyi:64: error: Class tracemalloc.Traceback has abstract attributes ['__getitem__', '__len__']`
- [x] `stdlib/3.4/enum.pyi:7: error: Class enum.EnumMeta has abstract attributes ['__len__']`
- [x] `stdlib/2and3/distutils/cmd.pyi:7: error: Class distutils.cmd.Command has abstract attributes ['finalize_options', 'initialize_options', 'run']`
- [x] `stdlib/3/urllib/error.pyi:8: error: Class urllib.error.HTTPError has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']`
- [x] `stdlib/3/io.pyi:260: error: Class io.IncrementalNewlineDecoder has abstract attributes ['decode']`
- [x] `stdlib/3/encodings/utf_8.pyi:3: error: Class encodings.utf_8.IncrementalEncoder has abstract attributes ['encode']`
- [x] `stdlib/3/encodings/utf_8.pyi:5: error: Class encodings.utf_8.IncrementalDecoder has abstract attributes ['_buffer_decode']`
- [x] `stdlib/2and3/distutils/command/build_py.pyi:7: error: Class distutils.command.build_py.build_py has abstract attributes ['finalize_options', 'initialize_options', 'run']`
- [x] `stdlib/2and3/distutils/command/build_py.pyi:8: error: Class distutils.command.build_py.build_py_2to3 has abstract attributes ['finalize_options', 'initialize_options', 'run']`
- [x] `stdlib/2and3/distutils/command/bdist_msi.pyi:5: error: Class distutils.command.bdist_msi.bdist_msi has abstract attributes ['finalize_options', 'initialize_options', 'run']`
- [x] `stdlib/3.4/asyncio/events.pyi:207: error: Class asyncio.events.BaseDefaultEventLoopPolicy has abstract attributes ['get_child_watcher', 'set_child_watcher']`
- [x] `stdlib/2and3/asynchat.pyi:12: error: Class asynchat.async_chat has abstract attributes ['collect_incoming_data', 'found_terminator']`
- [x] `third_party/2and3/requests/packages/urllib3/response.pyi:25: error: Class requests.packages.urllib3.response.HTTPResponse has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'isatty', 'readline', 'readlines', 'seek', 'seekable', 'truncate', 'writable', 'write', 'writelines']`
- [x] `third_party/2and3/requests/cookies.pyi:44: error: Class requests.cookies.RequestsCookieJar has abstract attributes ['__len__']`

I believe most of these aren't intended to be abstract.

**Comment by gvanrossum** [comment]
Wow, great catch, and thanks for endeavoring to fix these.

**Comment by graingert** [comment]
can we get this in mypy for real?

maybe with `--strict-abstract` and fixed with a decorator in mypy_extensions:

```python
@mypy_extensions.abstract
class Foo(Iterable):
    pass
```

"error: Class io.IncrementalNewlineDecode must implement base members ['decode'] or be declared abstract"

**Comment by gvanrossum** [comment]
Let's keep this discussion in #3705.

**Comment by timabbott** [comment]
Are there plans to finish cleaning this up?  We just ran into the SimpleCookie one today.

**Comment by JelleZijlstra** [comment]
I haven't looked at this in a while, sorry. Perhaps we can spend some time on this in the sprints.

If people have ideas for automated ways to detect these classes, that would also be helpful, since otherwise it's easy to have new instances of this bug slip in.

**Comment by JelleZijlstra** [comment]
I just regenerated the list (code is in this mypy branch: https://github.com/JelleZijlstra/mypy/tree/noabstract).

Here's a new list of affected classes in 3.7, excluding classes that are clearly meant to be abstract, those for which I have a PR open with a fix, and private classes:
- [ ] stdlib/2and3/_csv.pyi:23: error: Class _csv._reader has abstract attributes ['__next__']
- [ ] stdlib/2and3/distutils/version.pyi:7: error: Class distutils.version.Version has abstract attributes ['__init__', '__str__', '_cmp', 'parse']
- [ ] stdlib/3/shlex.pyi:14: error: Class shlex.shlex has abstract attributes ['__next__']
- [ ] stdlib/3/urllib/response.pyi:6: error: Class urllib.response.addinfourl has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']
- [ ] stdlib/3/multiprocessing/pool.pyi:18: error: Class multiprocessing.pool.IMapIterator has abstract attributes ['__iter__']
- [ ] stdlib/3.3/lzma.pyi:70: error: Class lzma.LZMAFile has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'flush', 'isatty', 'readlines', 'truncate', 'writelines']
- [ ] stdlib/2and3/distutils/cmd.pyi:7: error: Class distutils.cmd.Command has abstract attributes ['finalize_options', 'initialize_options', 'run']
- [ ] stdlib/3/urllib/error.pyi:8: error: Class urllib.error.HTTPError has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'close', 'fileno', 'flush', 'isatty', 'read', 'readable', 'readline', 'readlines', 'seek', 'seekable', 'tell', 'truncate', 'writable', 'write', 'writelines']
- [ ] stdlib/3/email/policy.pyi:14: error: Class email.policy.Policy has abstract attributes ['fold', 'fold_binary', 'header_fetch_parse', 'header_source_parse', 'header_store_parse']
- [ ] stdlib/2and3/asynchat.pyi:12: error: Class asynchat.async_chat has abstract attributes ['collect_incoming_data', 'found_terminator']
- [ ] third_party/2and3/requests/packages/urllib3/response.pyi:25: error: Class requests.packages.urllib3.response.HTTPResponse has abstract attributes ['__enter__', '__exit__', '__iter__', '__next__', 'isatty', 'readline', 'readlines', 'seek', 'seekable', 'truncate', 'writable', 'write', 'writelines']

**Comment by gvanrossum** [comment]
I take it the check marks indicate PRs filed, not PRs merged? How to indicate that they are merged?

**Comment by JelleZijlstra** [comment]
Yes, it's filed, not merged. This works better for me in tracking what work I still have to do; I'll probably do another check once my current batch of PRs is merged.

Thanks for reviewing my PRs today!

**Comment by JelleZijlstra** [comment]
We just merged a mypy change that will catch these cases in the future. This issue is now fixed.
