### ISSUE TITLE
Missing pyspark third-party library

### ISSUE THREAD

**Issue by MRigal** [python/typeshed#1494]
Especially in case of this library, as it is doing globals generation on the fly to export SQL functions to python, such a typing skeleton would be really great!
See https://github.com/apache/spark/blob/master/python/pyspark/sql/functions.py#L210-L222 for example

I might eventually have time to do that, but I will at least be interested if somebody else is doing it!

**Comment by JelleZijlstra** [comment]
Before we do this, we'll need permission from the authors of the library. Could you ask them if they're OK with typeshed including stubs for pyspark?

**Comment by MRigal** [comment]
OK, there is actually already something available here: https://github.com/zero323/pyspark-stubs

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
