### ISSUE TITLE
Signature error with Counter.most_common

### ISSUE THREAD

**Issue by Daenyth** [python/typeshed#1511]
mypy==0.521

```
from typing import *

c = Counter([('a','b','c'), ('a', 'b', 'c')])
duplicates = [(key, count) for key, count in c.most_common(1) if count > 1]
assert duplicates == [(('a','b','c'), 2)]
```

This file executes without errors, but mypy says
> c.py:4: error: Too many values to unpack (2 expected, 3 provided)

**Comment by ilevkivskyi** [comment]
The return type of ``most_common`` should be ``List[Tuple[_T, int]]`` not ``List[_T]`` (at least in Python 3.4).

**Comment by sproshev** [comment]
It was fixed in https://github.com/python/typeshed/pull/1491
