### ISSUE TITLE
Code supporting python 2 & 3 has no valid annotation for IO vs IOBase? (fcntl.flock)

### ISSUE THREAD

**Issue by neiljp** [python/typeshed#1521]
The latest mypy/typeshed (0.521) complains about the current version of
[this file](https://github.com/zulip/zulip/blob/master/zerver/lib/context_managers.py) in the current zulip repo, after I tried to update the version used in regular checks by zulip. In both versions of python this was a `BinaryIO`/`TextIO` vs `int` incompatibility.

After discussion in gitter with @ethanhs (thanks!), this was resolved preliminarily via changing line 13 (the last of the following) to:
```
@contextmanager
def flock(lockfile, shared=False):
# type: (Union[int, IO[Any]], bool) -> Iterator[None]
```
This resolves the issue in python3 mode, but then python2 mode complains, I believe since it expects `Union[int, IOBase]`.

While it is my understanding that Zulip may well move to python3 in the near future, is there a current solution for such code, where it is intended that it work with both python major versions?

**Comment by ethanhs** [comment]
Ah, I missed this commit https://github.com/python/typeshed/commit/6f23d124c0a06c37ff8d29c333e8d8f2cd9f7e86 that solves it. In 0.521 the signature is `_ANYFILE = Union[int, io.IOBase]` which is obviously wrong. But it is all fixed now. The type signature I suggested should work fine now @neiljp.

**Comment by neiljp** [comment]
Great news! I'm not sure I can make use of it as yet, though, if I use 0.521 in a requirements.txt?
I could probably do it manually locally, but I'm not sure if that's possible until a later mypy release?

**Comment by gvanrossum** [comment]
It's possible to have a specific commit from master in the
requirements.txt, e.g. this (from Zulip):

git+
https://github.com/python/mypy.git@bc452376872a249c5d1d2a6fb5ffaa805a36b972

**Comment by neiljp** [comment]
Understood - that's what I'm changing away from in a Zulip PR :)

I was aiming to go for a numbered mypy release, but then seeing this, perhaps with an improved typeshed to resolve this issue. While I originally assumed a sync only occurred upon release, I imagine I can include the typeshed fix with a mypy git+ requirement referencing a commit after a suitable sync with typeshed, though this would move away from the idea of using a numbered mypy release.

I tried adding in a typeshed commit as a requirement, but that's not possible, at least for now? Is there a plan for them to be released separately?

**Comment by gvanrossum** [comment]
There are good reasons not to decouple typeshed releases.

**Comment by ethanhs** [comment]
(To follow up on what Guido said)

Typeshed and Mypy are often updated in tandem, so separate releases don't make a lot of sense. In addition, we also have to respect that PyCharm and pytype also use typeshed.

**Comment by neiljp** [comment]
Thanks for the help! Resolved via working against the August 3rd commit with the sync.
