### ISSUE TITLE
FileIO.__enter__ returns IOBase

### ISSUE THREAD

**Issue by EvanKrall** [python/typeshed#1540]
I've got some code using FileIO:

```
            with io.FileIO(path, mode=self.mode, closefd=True) as f:
                f.write(to_write.encode('UTF-8'))
```

Mypy complains: `error: "IOBase" has no attribute "write"; maybe "writable"?`

This appears to be because `__enter__` on FileIO is inherited from IOBase, and [`IOBase.__enter__` is marked as returning IOBase.](https://github.com/python/cpython/blob/master/Modules/_io/iobase.c#L435). In fact, `IOBase.__enter__` [returns self](https://github.com/python/cpython/blob/dadca480c5b7c5cf425d423316cd695bc5db3023/Modules/_io/iobase.c#L435).

**Comment by gvanrossum** [comment]
Good catch. This stub probably predates the invention of ["self-type" using type variables](http://mypy.readthedocs.io/en/latest/generics.html#generic-methods-and-generic-self).

Would you like to send a PR for this?

**Comment by EvanKrall** [comment]
Yeah, I think I have the patch ready, just reading CONTRIBUTING.md now.

**Comment by EvanKrall** [comment]
https://github.com/python/typeshed/pull/1541
