### ISSUE TITLE
No stub for asyncio.base_events

### ISSUE THREAD

**Issue by OndrejZapletal** [python/typeshed#1570]
According to [https://github.com/python/mypy/issues/3851](url), this is the appropriate place to raise this issue.

Simple code:
```
import asyncio
item: asyncio.base_events.Server = None
```
results in following error when checked by mypy:
```
main.py:2: error: Name 'asyncio.base_events.Server' is not defined
```
On the other hand code:
```
from asyncio.base_events import Server
item: Server = None
```
doesn't result in any error.

Most likely the problem is that `base_events` is not defined in `typeshed`.

**Comment by CraftSpider** [comment]
The `base_events` file was added in 53d46105795bdec981704649e2b951a4dec41b77, is this issue still necessary?

**Comment by srittau** [comment]
Thanks for pointing this out.
