### ISSUE TITLE
dict_type argument to RawConfigParser is incorrectly specified

### ISSUE THREAD

**Issue by OddBloke** [python/typeshed#1571]
This is perfectly valid code that fails to typecheck:

```py
from configparser import RawConfigParser

RawConfigParser(dict_type=dict)
```

with:

```
example.py:3: error: Argument 1 to "RawConfigParser" has incompatible type Type[Dict[Any, Any]]; expected Mapping[str, str]

```

**Comment by gvanrossum** [comment]
I disagree. Please read up on (in)variance in the mypy docs: http://mypy.readthedocs.io/en/latest/common_issues.html#variance.

**Comment by gvanrossum** [comment]
Oh never mind, sorry. There's a type/instance confusion in the stub.
