### ISSUE TITLE
Typing for os.scandir does not handle dual-nature (iterator, context manager)

### ISSUE THREAD

**Issue by cricalix** [python/typeshed#1573]
The documentation for os.scandir() shows a syntax of:

```
with os.scandir(path) as it:
    ...
```

When this is called as:
```
    def _find_files(base, directory) -> List[str]:
        with os.scandir(os.path.join(base, directory)) as it:
            for dirent in it:
                pass
```

everything is groovy from mypy's point of view.

When called as:
```
    def _find_files(base: str, directory: str) -> List[str]:
        with os.scandir(os.path.join(base, directory)) as it:
            for dirent in it:
                pass
```

mypy will complain with "Iterator[DirEntry[str]] has no attribute "__enter__"; maybe "__iter__"?"

https://github.com/python/typeshed/blob/master/stdlib/3/os/__init__.pyi#L347 appears to be where this comes from. Dig through the C source (and the docs), there's mention of a ScandirIterator.

I'm working on getting a fix for this, but I'll need to bootstrap my knowledge of where to put things in typeshed to fix it.

**Comment by JelleZijlstra** [comment]
Thanks for looking into this! I think you found the right place in the typeshed source.
