### ISSUE TITLE
Feature:  typeshed generator for arbitrary module

### ISSUE THREAD

**Issue by arita37** [python/typeshed#1580]
Goal is to pre-generate typeshed file for arbitray module using inspect,

1) Obviously full type documentation is automatically possible for arbitray module,
but having the pre-generated template would help filling the gaps.

2) Second step is use typeshed files to resolve type indeterminacy for new module.
    it would help automate most of the part of generating typeshed files for new module.

**Comment by JelleZijlstra** [comment]
mypy already includes a tool that does some of this, called stubgen. It does not use inspect though, and does not infer much, if any, type information.

**Comment by JelleZijlstra** [comment]
Out of scope for typeshed.
