### ISSUE TITLE
Add re.RegexFlag (Python 3.6+)

### ISSUE THREAD

**Issue by PJB3005** [python/typeshed#1587]
It's not exported, so you can't say declare a function taking only regex flags.

**Comment by JelleZijlstra** [comment]
This was added in 3.6: https://docs.python.org/3/library/re.html#module-contents. Should be easy to fix in typeshed; feel free to submit a PR!

**Comment by PJB3005** [comment]
Yes, but it's not exported (inside `re`'s `__all__`), so it can't be accessed, can it?

**Comment by JelleZijlstra** [comment]
`__all__` only affects whether the name is imported when you do `from re import *`; `re.RegexFlags` (after `import re`) still works. I don't know why it's not in `__all__`, but perhaps it was by accident. You can file a bug against CPython to get that problem fixed.

For typeshed we don't normally care about `__all__`; we should just add RegexFlags to our stub.
