### ISSUE TITLE
functools.partial does not implement Callable

### ISSUE THREAD

**Issue by PJB3005** [python/typeshed#1597]
It *does* have a `__call__` defined inside the class definition, but it doesn't appear to directly implement `Callable[]`.

**Comment by nicktimko** [comment]
Wondering if this is the cause when attempting to use a `partial` as a factory for `collections.defaultdict`:

```
from collections import defaultdict
from functools import partial
x = defaultdict(partial(int, 10))
```

Running through mypy gives 

>... error: No overload variant of "defaultdict" matches argument types [functools.partial[builtins.int*]]

**Comment by ilevkivskyi** [comment]
This issue is fixed, looks like a problem with overloads, you can continue to investigate in another issue where you posted.
