### ISSUE TITLE
Come up with a way for a module to say "I don't exist"

### ISSUE THREAD

**Issue by o11c** [python/typeshed#16]
While tooling support isn't there yet, there _is_ a way for stubs to indicate "the module only contains this function on this platform/version/implementation", using if branches like:

``` python
# Stubs for gc
if platform.python_implementation() == 'CPython':
    def get_count(o: object) -> int: ...
```

There is also a fairly obvious extension for `try ... except ImportError`

However, there is no way to indicate the complete absence of a module based on such a condition.

This is needed for tools to be able to correctly handle code like:

``` python
try:
    import msvcrt
except ImportError:
    msvcrt = None
```

i.e. only import the `msvcrt` stub if it is supposed to exist on the platform that is currently being checked-for, and otherwise assign the variable to have type `NoneType`, so that it can propogate constant checks for `is [not] None` later.

While it would be possible to add an entirely new set of directories for platform and also for implementation, this would grow quite quickly

**Comment by matthiaskramm** [comment]
Yes, fair point. This might be a useful feature.
I guess a possible syntax would be to add something like
```
if sys.platform != "win32":
  raise ImportError()
```
at the start of, for example, `msvcrt.pyi`.

**Comment by o11c** [comment]
Heh, I just though of module-level `raise ImportError` while I was afk.

**Comment by JelleZijlstra** [comment]
This has been open for three years with little interest shown and it cannot be fixed in typeshed alone, so I'm closing this. A new typing feature like this is better discussed at http://github.com/python/typing.
