### ISSUE TITLE
re.match etc. should support Pattern arguments

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#160]
(Moved from https://github.com/python/mypy/issues/625)

Mypy complains about this code, even though it's valid:

```
import re
x = re.compile('x')
re.match(x, 'xy')
```

The reason is that `re` stubs are too restrictive.

**Comment by Dakkaron** [comment]
As far as I can see, this issue has been fixed by https://github.com/python/typeshed/commit/3e37029bfec1d01584b91c2fc53818f52a849dbe

**Comment by gvanrossum** [comment]
Thanks!
