### ISSUE TITLE
Error for len or enumerate on array.array

### ISSUE THREAD

**Issue by Zac-HD** [python/typeshed#1608]
[`array.array`](https://docs.python.org/3/library/array.html#array.array) objects are essentially efficient lists with a single element type.  They have a size and can be iterated over, but mypy doesn't seem to know this:

    floats.py:105: error: Argument 1 to "len" has incompatible type "array"; expected "Sized"
    floats.py:107: error: Argument 1 to "enumerate" has incompatible type "array"; expected Iterable[<nothing>]

[Source](https://github.com/HypothesisWorks/hypothesis-python/blob/master/src/hypothesis/internal/conjecture/floats.py#L104-L105).

**Comment by amanharitsh123** [comment]
Just have opened a PR for this..have a look

**Comment by gvanrossum** [comment]
This could perhaps be fixed by making stdlib/2/array.pyi a (near) clone of stdlib/3/array.pyi. The two could even easily be merged into stdlib/2and3/. (Though I haven't checked if there are changes to the array API in Python 3.)

**Comment by Zac-HD** [comment]
Closed by #1670, following #1649.
