### ISSUE TITLE
Add things missing from Python 2 builtins stubs

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#161]
Transferred from https://github.com/python/mypy/issues/600 (I double-checked the list and removed items that are now present):

These are missing from Python 2 builtins stubs:

```
apply
coerce
copyright
credits
help
license
```

**Comment by Naruto0** [comment]
Working on it. Maybe a dumb question. Should i download source code of python to better understand `class copyright(site._Printer) -> Any: ...`

I really have no clue if i can use private name like this. Is this place to use Generic Type or something like that? Thanks!

Anyway, BufferError is already there...

**Comment by gvanrossum** [comment]
Honestly, copyright, license, help and credits probably aren't worth adding. They are supposed to be only available in the REPL. (Unless you can find examples in the Python 3 stubs.)

The source code for those is probably not the best place to enlighten unless you're already a Python wizard.

**Comment by Naruto0** [comment]
I once found myself reading throught some python modules code.. and that's quite useful reading. But sadly I'm not a wizard of any kind.
They are in Python 3 builtin.pyi stubs. Defined as builtin methods, like this:
`def copyright() -> None: ...`
So what to do with them..

**Comment by gvanrossum** [comment]
Just copy the PY3 stubs to PY2.

**Comment by Naruto0** [comment]
https://github.com/python/typeshed/pull/165

**Comment by JelleZijlstra** [comment]
apply and coerce are in the stub now and @gvanrossum commented above that we don't really need the others, so I'm closing this issue.
