### ISSUE TITLE
argparse.Action stubs missing member variables

### ISSUE THREAD

**Issue by matthchr** [python/typeshed#1612]
Using MyPy:

```
from typing import Any
import argparse


class A(argparse.Action):
    def __call__(
            self,
            parser: Any,
            namespace: Any,
            values: Any,
            option_string: Any = None) -> None:
        foo = self.const or 'a'
        ...
```

Since `argparse.Action` has a variable named `self.const` I expect that I can use it, but MyPy complains, saying: `temp.py:15: error: "A" has no attribute "const"`

I filed [this issue](https://github.com/python/mypy/issues/3961) with mypy, and was directed here.

**Comment by gvanrossum** [comment]
Do you want to submit a PR? It seems simple enough.

**Comment by JelleZijlstra** [comment]
This is fixed in master.
