### ISSUE TITLE
setLevel and setFormatter parameters problem

### ISSUE THREAD

**Issue by emcek** [python/typeshed#1619]
my code:
``` python
logger = logging.getLogger(name)
logger.setLevel(level=logging.DEBUG)
...
stream_handler = logging.StreamHandler(stream=stdout)
stream_handler.setLevel(logging_level)
stream_handler.setFormatter(fmt=formatter)
```
and mypy-0.521 complains about **fmt vs. form** parameter in `setFormatter` method and **level vs. lvl** in `setLevel` method.
```
ta_cc/cc_logger.py: note: In function "_get_stream_handler":
ta_cc/cc_logger.py:34: error: Unexpected keyword argument "fmt" for "setFormatter" of "Handler"
/usr/local/lib/mypy/typeshed/stdlib/2and3/logging/__init__.pyi:147: note: "setFormatter" of "Handler" defined here
ta_cc/cc_logger.py:109: error: Unexpected keyword argument "level" for "setLevel" of "Logger"
/usr/local/lib/mypy/typeshed/stdlib/2and3/logging/__init__.pyi:46: note: "setLevel" of "Logger" defined here
```

I see in online documentation that indeed there are *lvl* and *form* parameters for all 2.7, 3.5 and 3.6 python version. However my Pycharm suggest *level* and *fmt* for all my installed python interpreters.

I use:
Pycharm-2017.2.3
Python 2.7.12
Python 3.5.2
Python 3.6.2

What could be wrong?

**Comment by JelleZijlstra** [comment]
Relevant links:
- https://github.com/python/cpython/blob/1bbd482bcf6ea36bfe488f868810ffe110238ae1/Lib/logging/__init__.py#L858 – the argument to `setFormatter` is named `fmt`. (And it's the same in 2.7: https://github.com/python/cpython/blob/2.7/Lib/logging/__init__.py#L764)
- https://docs.python.org/3/library/logging.html#logging.Handler.setFormatter – the documentation calls the argument `form`
- https://github.com/python/typeshed/blob/master/stdlib/2and3/logging/__init__.pyi#L147 – typeshed also has `form`
I suppose you found a bug in the CPython docs—feel free to report it to CPython. Typeshed should match the implementation, so feel free to submit a PR. The situation with `setLevel` is probably similar but I didn't track it down.

Really though, the reason why this discrepancy in the docs went unnoticed for so long is that there is no reason to use keyword arguments to these methods. If you just call `setFormatter(fmt)`, you won't have any problems.

**Comment by emcek** [comment]
> Really though, the reason why this discrepancy in the docs went unnoticed for so long is that there is no reason to use keyword arguments to these methods. If you just call setFormatter(fmt), you won't have any problems.

Yes, I found it out just after opening this issue.

I will open minor PR on CPython.

**Comment by emcek** [comment]
reported under: https://bugs.python.org/issue32212

**Comment by emcek** [comment]
Docs and source cod updated:  
https://github.com/python/cpython/commit/a9f8df646aac7fc94ced0aefd1ed2c8566d14d10  
https://github.com/python/cpython/commit/63868181a904c844d8d01e3badfdd5b134acc5fa  
https://github.com/python/cpython/commit/292fce9934280867ca9a65870495f83fca37751e
