### ISSUE TITLE
Write a tool to convert pytypedecl stubs to mypy stubs

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#162]
From https://github.com/python/mypy/issues/382:

> Greg P. Smith pointed out that pytypedecl has a large collection of stubs for builtins and parts of the stdlib that were generated via code analysis, and that more are on the way. It should be easy to convert this collection to mypy stubs and thus augment (or at least verify) the mypy stubs collection.

There's quite a bit of discussion in that issue. I'm not sure how much of it is still useful. But I'm closing out the mypy issues related to stubs so I figured I'd link to it here until someone can review whether there's anything left to do.

**Comment by matthiaskramm** [comment]
pytypedecl is an abandoned project. And the stubs it contained have long been incorporated into typeshed. So there doesn't seem anything left to do.
