### ISSUE TITLE
logging.StreamHandler should define terminator and stream attributes

### ISSUE THREAD

**Issue by bennoleslie** [python/typeshed#1624]
The `terminator` and `stream` attributes should be correctly typed on the `logging.StreamHandler` object so that subclasses can use these public attributes.

`terminator` should have type `str`.
`stream` should have type `IO[str]`. 

https://github.com/python/typeshed/blob/2b97c02801d2063a3016bf50d0007dd49cf74fcc/stdlib/2and3/logging/__init__.pyi#L368

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR!

**Comment by srittau** [comment]
Fixed in #1625.
