### ISSUE TITLE
mypy wrongly complains that 'ssl' has no attribute '_SSLMethod'

### ISSUE THREAD

**Issue by adamtheturtle** [python/typeshed#1630]
I have a `pytest` test which takes the following parameters:

```
@pytest.mark.parametrize('unsupported_tls_version', [
    ssl.PROTOCOL_TLSv1,
    ssl.PROTOCOL_TLSv1_1]
    )
```

I want to add a type hint for the `unsupported_tls_version` parameter.
I believe. that these are of type `ssl._SSLMethod`.

To add a type hint, I use `from ssl import _SSLMethod`.

I believe that the following error from `mypy` is erroneous:

```
~/Desktop> python --version
Python 3.6.0
~/Desktop> mypy --version
mypy 0.521
~/Desktop> cat example.py 
from ssl import _SSLMethod
~/Desktop> python --version
Python 3.6.0
~/Desktop> cat example.py 
from ssl import _SSLMethod
 ~/Desktop> python example.py 
~/Desktop> mypy example.py 
example.py:1: error: Module 'ssl' has no attribute '_SSLMethod'
```

**Comment by JelleZijlstra** [comment]
`_SSLMethod` is private and undocumented, so I actually agree with mypy here. If you want to use private members of a standard library module, I don't think it's typeshed's job to provide accurate typing information.

We might accept a PR adding `_SSLMethod` to the stubs for the ssl module though.

**Comment by adamtheturtle** [comment]
> I actually agree with mypy here

I'm guessing that you agree that `mypy` shouldn't support dealing with private methods but the message "Module 'ssl' has no attribute '_SSLMethod'" is factually incorrect.

> If you want to use private members of a standard library module

The following is my understanding and I am by no means a Python expert.

The constructor is private, but you might consider the interface public as `ssl.PROTOCOL_TLSv1` is public. One way I've dealt with such situations in my own code is to use an abstract base class. The private class can implement the ABC, and the consumer can use the ABC in the type hint.

Such a change would involve a change to Python, and I'm not sure that that would be welcome, or even that the above is good practice.

**Comment by srittau** [comment]
We now accept PRs that add undocumented methods (see CONTRIBUTING for details). Closing as we don't keep requests for undocumented functions open.

**Comment by adamtheturtle** [comment]
Thanks @srittau . I am no longer working on the project which wanted this and so I won't do this, at least for now. I appreciate the update however!
