### ISSUE TITLE
OrderedDict.copy() returns an OrderedDict

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1642]
We should add this to the stub for OrderedDict. (Both Python 2 and 3.)

Note that we can't fix this by using a self-type for `dict.copy()` because in general if you subclass `dict` and don't override `copy()`, your `copy()` method will return just a `dict`. But `OrderedDict.copy()` overrides this behavior and the typeshed stub should say so.

**Comment by elazarg** [comment]
I don't think this is closed yet. #1656 didn't fix this, since the added `__copy__` method is related to the copy() protocol, not to the interface of OrderedDict. The right fix is to add a `copy` method (perhaps in addition to `__copy__`).

**Comment by ilevkivskyi** [comment]
Fixed by #1856
