### ISSUE TITLE
Some positional-only arguments are incorrectly represented in stubs

### ISSUE THREAD

**Issue by namanbharadwaj** [python/typeshed#1643]
See `itertools.islice` as an example: https://github.com/python/typeshed/blob/master/stdlib/2/itertools.pyi#L40-L44

Any tool that knows nothing about Python builtins other than this type stub would infer that `itertools.islice([], stop=10)` is a valid invocation, but it is not, as Python disallows passing any keyword arguments for many of these builtins. Obviously, this is a more general issue with the way that Python builtins are special cases.

My imagined solution would involve adding extra annotation information to the stubs about arguments that must be passed positionally, possibly as comments that can be parsed by tools that care about the extra metadata (in order to avoid complicating the syntax).

Thoughts?

**Comment by namanbharadwaj** [comment]
After a little more thought, non-builtins can also require arguments are passed positionally by taking `*args` and potentially doing some validation on the list. See `collections.Counter` for a non-builtin that does that, where the typeshed annotation is misleading.

**Comment by namanbharadwaj** [comment]
perhaps the solution is to just annotate

```
@overload
def islice(*args: Tuple[Iterable[_T], int]) -> Iterator[_T]: ...
@overload
def islice(*args: Tuple[Iterable[_T], Optional[int], Optional[int], Optional[int]]) -> Iterator[_T]: ...
```

**Comment by JelleZijlstra** [comment]
That would not work; the type of `*args` is the type of individual elements within the tuple.

One solution is to prefix the arguments with `__`, since by convention arguments whose name starts with `__` are positional-only.

In general I'm not sure this is an important enough issue to worry a lot about.

**Comment by srittau** [comment]
Annotating positional-only arguments with `__argname` is the correct solution, until Python gains special syntax for this.
