### ISSUE TITLE
Module has no attribute "errno"

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#1646]
This error is produced by mypy with the following code:
```python
import os
os.errno
```

This however works at runtime (at least on Python 3.4), moreover ``os.errno is errno`` returns ``True``, so I suppose this would be easy to fix by just adding ``import errno as errno`` to ``os/__init__.pyi``.

**Comment by JelleZijlstra** [comment]
That feels like an implementation detail of the `os` module that stubs should not necessarily reflect. Is it documented that `os.errno` will work, and would CPython have qualms about adjusting imports inside the `os` module in a bugfix release?

**Comment by ilevkivskyi** [comment]
It is not documented, but I think it is formally covered by backwards compatibility guarantees. Searching on GitHub for this is hard (because of the dot) but I would estimate there are hundreds of repos that use this.

**Comment by gvanrossum** [comment]
Users should not depend on this. It's no different from using `os.sys`.

**Comment by JelleZijlstra** [comment]
Closing per Guido's comment.
