### ISSUE TITLE
No library stub file for standard library module 'typing.re'

### ISSUE THREAD

**Issue by gwk** [python/typeshed#1652]
`from typing.re import Pattern`

This is legal, but mypy produces:
`error: No library stub file for standard library module 'typing.re'

**Comment by JelleZijlstra** [comment]
This seems hard to fix without making typing into a package in the stubs (move `typing.pyi` to `typing/__init__.pyi`). That would be rather disruptive though.

**Comment by dacut** [comment]
Something's amiss here, and I suspect it's in the [typing documentation](https://docs.python.org/3/library/typing.html).

The typing documentation only mentions IO, BinaryIO and TextIO in the context of the `typing.io` wrapper namespace (which is not a module in itself -- it's just a class with class-level variables, IO, BinaryIO, and TextIO). However, these are *also* defined within the `typing` module itself, but it is undocumented in the official documentation.

[PEP 484](https://www.python.org/dev/peps/pep-0484/) alludes to the existence of this at the `typing` module level but isn't explicit about it.

Guido may need to weigh in here on the intent, but I'm of the opinion that `typing.io` should be deprecated (why have a sub-namespace if you're just going to "pollute" the higher-level `typing` namespace, anyway?), these classes documented in the `typing` module itself, and leave typeshed as-is.

**Comment by gvanrossum** [comment]
The intention was actually the opposite -- `typing.re.Pattern`, `typing.io.IO` etc. are the proper names, and `typing.Pattern` etc. are (deprecated?) shortcuts. PEP 484 only mentions `typing.re.Pattern` etc., and doesn't mention the shortcuts at all.

If the CPython docs don't say this they should be updated.

If we have to turn `typing.pyi` into `typing/__init__.pyi` with additional submodules `re.pyi` and `io.pyi` so be it. (The `typing.py` module used at runtime just patches `sys.modules`, similar to what `os.py` does for `os.path`.)

HOWEVER, the reason for the substructure was that typed versions of other stdlib classes could be added as additional submodules of `typing`. I don't think we're going to do that. So it *could* be argued that we should reverse course. That would also require amending PEP 484. It's not too late: according to PEP 563, PEP 484 graduates from provisional in 3.8.

**Comment by gwk** [comment]
Stylistically, I prefer the single flat namespace, e.g. `from typing import Pattern, TextIO`. I've been using mypy now for about 1.5 years, and compared to other aspects of the system  it took me some time to memorize this idiosyncrasy. For people learning the type system, I think it lowers the barrier to entry to put flatten these types into a single module and documentation page where they can be browsed and searched for.

**Comment by JelleZijlstra** [comment]
I'd also prefer supporting just `from typing import Pattern` for simplicity. Given that `from typing.re import Pattern` doesn't work with mypy and presumably has never worked, I doubt a lot of users rely on the `typing.re` and `typing.io` namespaces.

@gwk @dacut would one of you interested in moving forward this change? It would require amending PEP 484 (as Guido mentioned) as well as the typing documentation in CPython (https://docs.python.org/3/library/typing.html#typing.io) and also making changes in `typing.py` itself.

**Comment by gvanrossum** [comment]
OK, let's proceed this way. But I need someone else to take the lead (I'm
overwhelmed by small projects already).

**Comment by ilevkivskyi** [comment]
I don't have time to it all myself, but I can "supervise" if someone volunteers to make actual PRs.

**Comment by srittau** [comment]
Should this issue be moved over to python/typing?

**Comment by srittau** [comment]
Moved over to python/typing#589.
