### ISSUE TITLE
long type in 2.7 stub

### ISSUE THREAD

**Issue by Naruto0** [python/typeshed#166]
Before I defined _Number as type for argument in [coerce method](https://github.com/python/typeshed/pull/165/commits/fa8d09cde15532250a1ce056d851d80ae8099aa5) Travis build [failed](https://gist.github.com/Naruto0/33a5456883e214d2bd1e31b953b6d374) not recognizing long type.

importing _Number was easy, but not workaround. I'm posting it, because it might be some issue. 

In stub `__builtin__.pyi` long is [defined](https://github.com/python/typeshed/blob/master/stdlib/2.7/__builtin__.pyi#L640) like this:
`long = int`
I would expect rather subclass of int, or more complex code.

If I define varible `y=4524j# type: long` mypy Error says that it expects 'int'.
Full error message:
`long.py: error: Incompatibile types in assignment (expression has type "complex variable", variable has type "int")` 

So my question is, that if this is correct behavior. When I define type to long, i would expect mypy to tell me that I have to use long.

**Comment by gvanrossum** [comment]
There really is very little difference between int and long in Python 2.7, so I think it's fine that mypy and the stubs equate them. (The difference used to be more pronounced in earlier Python versions, and there used to be something called OverflowError that was raised when an integer result was too large to fit in an int; but in 2.7, when you e.g. multiply two ints to get a value that doesn't fit in 64 bits, you'll quetly get a long.
