### ISSUE TITLE
[dateutil.tz] Module has no attribute "tzutc"

### ISSUE THREAD

**Issue by Daenyth** [python/typeshed#1665]
```
import dateutil.tz
dateutil.tz.tzutc
```

The above works fine at runtime, but I get 
```
foo.py:2: error: Module has no attribute "tzutc"
```

Using mypy 0.530

**Comment by Wilfred** [comment]
```
In [5]: dir(dateutil.tz)
Out[5]:
['EPOCH',
 'EPOCHORDINAL',
 'PY3',
 'TZFILES',
 'TZPATHS',
 'ZERO',
 '__all__',
 '__builtins__',
 '__doc__',
 '__file__',
 '__name__',
 '__package__',
 '__path__',
 '_common',
 'bisect',
 'contextmanager',
 'copy',
 'datetime',
 'datetime_ambiguous',
 'datetime_exists',
 'enfold',
 'gettz',
 'itemgetter',
 'os',
 'string_types',
 'struct',
 'sys',
 'time',
 'tz',
 'tzfile',
 'tzical',
 'tzlocal',
 'tzname_in_python2',
 'tzoffset',
 'tzrange',
 'tzrangebase',
 'tzstr',
 'tzutc',
 'tzwin',
 'tzwinlocal']
```

Looks like some exports are missing here: https://github.com/python/typeshed/blob/master/third_party/2/dateutil/tz/__init__.pyi#L1 although they're defined here: https://github.com/python/typeshed/blob/master/third_party/2/dateutil/tz/tz.pyi#L11

**Comment by Daenyth** [comment]
I forgot to mention I think this is a regression. The version of typeshed used by mypy 0.521 accepts the code without error

**Comment by JelleZijlstra** [comment]
Probably because mypy started enforcing that only names imported with `as` are re-exported. Filed a simple PR to fix it in this case.
