### ISSUE TITLE
Could use stubs for third_party package psutil

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1675]
The package is at https://github.com/giampaolo/psutil. I'll ask in its tracker if the author is okay with having stubs added to typeshed.

**UPDATE:** See https://github.com/giampaolo/psutil/issues/1147
**UPDATE 2:** The author approved. (Now all we need is a volunteer to add the stubs.)

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
