### ISSUE TITLE
Incomplete stub for AbstractEventLoop.add_reader

### ISSUE THREAD

**Issue by adamrothman** [python/typeshed#1677]
It's totally valid to pass `sys.stdin` to `AbstractEventLoop.add_reader` – this demo works as expected:
```python
import asyncio
import sys


queue: asyncio.Queue = asyncio.Queue()


def on_stdin():
    queue.put_nowait(sys.stdin.readline())


async def consume():
    while True:
        line = (await queue.get()).strip()
        print(f'received input: {line!r}')
        queue.task_done()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.add_reader(sys.stdin, on_stdin)
    loop.run_until_complete(consume())
```

But `mypy` complains:
```
$ mypy ./repro.py
repro.py:21: error: Argument 1 to "add_reader" of "AbstractEventLoop" has incompatible type "TextIO"; expected "Union[int, socket]"
```

Is adding `TextIO` to that Union enough to fix this?

Also – somewhat unrelated – removing the type annotation from the global variable `queue` results in this:
```
$ mypy ./repro.py
repro.py:5: error: Need type annotation for variable
repro.py:21: error: Argument 1 to "add_reader" of "AbstractEventLoop" has incompatible type "TextIO"; expected "Union[int, socket]"
```

Shouldn't the variable's type be easily inferred from the use of the `asyncio.Queue` constructor?

**Comment by JelleZijlstra** [comment]
It does sound like adding `TextIO` would work, but I haven't checked asyncio's code or docs myself.

As for the "Need type annotation" error, the reason mypy gives that error is that Queue is declared as generic in the stub, so it wants you to declare what is in the Queue. In your case, that would be an `'asyncio.Queue[str]'` (in quotes because Queue is not actually generic at runtime). Just writing `asyncio.Queue` also silences the warning, because mypy infers that to be `asyncio.Queue[Any]`. I'd recommend running mypy with `--disallow-any=generics` to catch this sort of issue.

**Comment by gvanrossum** [comment]
I think we should restrict this to ints -- you should use fileno(). There's
a check to make sure that you don't pass a fd here that's already in use by
a transport, but that check would be fooled if you were to pass a TextIO.

**Comment by adamrothman** [comment]
Thanks for the clarification @JelleZijlstra, that makes sense.

@gvanrossum I see [the check](https://github.com/python/cpython/blob/032a6480e360427d4f964e31643604fad804ea14/Lib/asyncio/selector_events.py#L335) you're referring to. Maybe if the value passed for `fd` isn't an int, the event loop could try to call `fd.fileno()`, raising an exception if the passed object has no such method? This would preserve the semantics of allowing "fd-like" things but I have no idea what an appropriate type annotation would look like.

**Comment by gvanrossum** [comment]
But that's not what the code does. If you want it changed you have to file a bug with CPython, not with typeshed. Until then I see no action needed on this ticket, and I'll close it. (It is also my personal opinion that it's better *not* to make the change you are suggesting, but I can't stop you from filing it in the appropriate forum.)

**Comment by adamrothman** [comment]
@gvanrossum I'm not married to any solution or course of action in particular. I just think it's confusing that the annotation is `Union[int, socket]` when in reality you also pass a `TextIO` and it works. If that's not the desired behavior, should the check in `add_reader` be stricter? I'm happy to file an issue – just want to get your take on what the ideal behavior is.

**Comment by gvanrossum** [comment]
For debatable values of "works". Can you please drop it?
