### ISSUE TITLE
distutils.setup cmdclass type annotation problem

### ISSUE THREAD

**Issue by marienz** [python/typeshed#1681]
typeshed contains an annotation for `distutils.setup`'s `cmdclass` argument:

```
          cmdclass: Mapping[str, Command] = ...,
```

I think this doesn't match what the function actually accepts. `cmdclass` is [documented](https://docs.python.org/3/distutils/extending.html) as taking `Command` subclasses, not `Command` instances. I think that translates to `Mapping[str, Type[Command]]`?

Example false positive from mypy: running mypy 0.540 (with stubs that define `setuptools.setup` and `build_py` as aliases of their distutils equivalents) on its own setup.py results in:

```
setup.py:74: error: Need type annotation for variable
setup.py:109: error: Dict entry 0 has incompatible type "str": "Type[CustomPythonBuild]"; expected "str": "Command"
```

**Comment by gvanrossum** [comment]
An astute observation. Can you send us a PR?
