### ISSUE TITLE
classmethod and staticmethod have no __call__

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#1684]
Adding a simple ``__call__`` like this:
```python
class classmethod(Generic[T]):
    def __init__(self, func: T) -> None:
    __call__: T
```
will reduce number of false positives for some dynamic code that calls it directly ``foo = classmethod(foo)``.

**Comment by JelleZijlstra** [comment]
When somebody submits a PR :).

**Comment by srittau** [comment]
Closing as dupe of #870.
