### ISSUE TITLE
Integrate stub coding style into PEP 8?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#1688]
Currently, both README.md and CONTRIBUTING.md contain (quite sensible) style guidelines for stub files. As third party modules can also ship their own stub files (even if support for that is still spotty), it makes sense to have guidelines for these as well. Are there any plans to integrate the guidelines into PEP 8? Should there be plans?

**Comment by srittau** [comment]
As pointed out by @JelleZijlstra in #1687: A good first step would be to deduplicate/merge the sections in README.md and CONTRIBUTING.md.

**Comment by gvanrossum** [comment]
The typeshed has its own style guide, which is more relaxed than PEP 8. I don't think we should recommend this style to everyone writing stubs though, and I don't think we need more about type annotations or stubs in PEP 8 than there already is (there's a bit about formatting arguments that have both a type and a default).

Feel free to help out by submitting a PR that does the suggested dedupe/merge!

**Comment by srittau** [comment]
Into which document should we merge the coding style? My gut feeling says CONTRIBUTING.md.

**Comment by gvanrossum** [comment]
Yes.
