### ISSUE TITLE
click.echo has incorrect type for message (1st argument)

### ISSUE THREAD

**Issue by fizyk** [python/typeshed#1691]
According to http://click.pocoo.org/6/api/#click.echo you can pass bytes as well as unicode, while typeshed states str, which is bytes on py2 and unicode on py3. 

Should this be rather Text?

My error from py2 code:
```
Argument 1 to "echo" has incompatible type "unicode"; expected "Optional[str]"
```

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR.
