### ISSUE TITLE
click.option typing issue

### ISSUE THREAD

**Issue by fizyk** [python/typeshed#1692]
That could be general question as well,

I'm passing callback to validate given option, the callback is designed to serve strictly string type inputs. 

Click defines the type for callable as https://github.com/python/typeshed/blob/master/third_party/2and3/click/decorators.pyi#L10
https://github.com/python/typeshed/blob/master/third_party/2and3/click/decorators.pyi#L107

However, since my callback calls value.startswith, when I define the type for value (third argument in a callback function as Union as in _Callback, then mypy complains, that int does not have startswith method. ` Item "int" of "Union[int, str]" has no attribute "startswith"`

otherwise it's `Argument 4 to "option" has incompatible type "Callable[[Any, Any, str], str]"; expected "Optional[Callable[[Context, Union[Option, Parameter], Union[bool, int, str]], Any]]`

Now the option also has the [type arg/kwarg,](https://github.com/python/typeshed/blob/master/third_party/2and3/click/decorators.pyi#L102) and it would be ideal, if the typeshed could take whatever's set there into account, although I'm not sure if that's possible.

**Comment by JelleZijlstra** [comment]
This could perhaps be done with a clever overload, something like:
```
@overload
def option(type: Type[str], callback: Callable[[str], Any]) -> None: ...
@overload
def option(type: Type[int], callback: Callable[[int], Any]) -> None: ...
```
(obviously the real stub would be far less simple).

**Comment by fizyk** [comment]
got some time to get back at this.

It seems that this example would work:

```
from typing import TypeVar, Callable, Type

T = TypeVar('T')

def test_type_and_callable(call_type: Type[T], call_using_type: Callable[[int, T], T], typed_value: T) -> T:
    return call_using_type(1, typed_value)


def illust_call_str(a: int, b: str) -> str:
    return str(a) + b

def illust_call_int(a: int, b: int) -> int:
    return a + b


x: str = test_type_and_callable(str, illust_call_str, 'foo')  # ok
y: int = test_type_and_callable(int, illust_call_int, 3)  # ok
z: int = test_type_and_callable(str, illust_call_int, 'bar')  # Error
# error: Incompatible types in assignment (expression has type "str", variable has type "int")
# error: Argument 2 to "test_type_and_callable" has incompatible type "Callable[[int, int], int]"; expected "Callable[[int, str], str]"
q: int = test_type_and_callable(str, illust_call_int, 1)  # Error
# error: Incompatible types in assignment (expression has type "object", variable has type "int")
# error: Argument 2 to "test_type_and_callable" has incompatible type "Callable[[int, int], int]"; expected "Callable[[int, object], object]"
```

The second error message is a bit mystery to me. As if it tries to fined the most common type describing `call_type` and `typed_value`
