### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by dilyanpalauzov** [python/typeshed#1702]
Integrate https://github.com/machinalis/mypy-django into typeshed.

I am aware of #153 but until this is resolved the last stable version can be exposed by typeshed.  This is what most people will use and having it is better than not having django type hints.

**Comment by gvanrossum** [comment]
I actually recommend waiting for PEP 561 and its implementation. Having incomplete stubs in typeshed (which I presume the machinalis stubs are) is worse than no stubs, as we've found out with some other packages (sqlalchemy was actually *withdrawn* for this reason).

**Comment by lwm** [comment]
Trying to pick up the situation here but can I just check what was meant by 'I actually recommend waiting for PEP 561 and its implementation' @gvanrossum. I see that there are [3 methods of including types](https://www.python.org/dev/peps/pep-0561/#specification) and not sure what was meant. Thanks.

**Comment by pjdelport** [comment]
I'm assuming this would mean a separate Django-stubs package.

**Comment by gvanrossum** [comment]
> a separate Django-stubs package

Yes.

**Comment by lwm** [comment]
OK, makes sense. We're going to try and bring about this django-stubs package. Kicking off at:

> https://github.com/TypedDjango/django-stubs#django-stubs

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
