### ISSUE TITLE
Here is a working stub for the chardet package from PyPI

### ISSUE THREAD

**Issue by ArneBachmann** [python/typeshed#1707]
```
from typing import Dict, Text, Union

def detect(byte_str:Union[bytes,str]) -> Dict[Text, Text]: ...
```

into `chardet.pyi`.

Works for Python3. For Python2 we might need to handle unciode strings somehow, but I'm struggling with that.

**Comment by ju-sh** [comment]
Is chardet stub available yet? If not can we start working on it?

**Comment by srittau** [comment]
Contributions are welcome! I don't think we have chardet in typeshed yet.

**Comment by ju-sh** [comment]
@srittau Can we use this issue or is it better to create a new one?

**Comment by srittau** [comment]
This issue is fine for discussing the stub, although details should be discussed in the PR once it is opened.

**Comment by ju-sh** [comment]
Made a tiny part of the stub. Can you have a look? https://github.com/python/typeshed/pull/3734

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
