### ISSUE TITLE
logging methods should accept any "msg" argument that is convertible to a str

### ISSUE THREAD

**Issue by joshstaiger** [python/typeshed#1708]
As per the [LogRecord.getMessage()](https://docs.python.org/3/library/logging.html#logging.LogRecord.getMessage) documentation, logging methods can accept any object that is convertible to a str via the str() method as their `msg` argument.

Currently the logging stub file forces all `msg` arguments to be literal `str` objects (or more specifically `Text`).

Given that any object is convertible to `str`, it seems the `msg` argument should technically have a type of `Any`.  

Though, I'm not sure if that's the best course of action as I'm sure 99% of the time the `msg` is an actual `str` and the type safety is nice to have. 

Just noting this for your attention.

**Comment by JelleZijlstra** [comment]
We've discussed this before and the conclusion has been that we don't want to allow types other than str for the message.

**Comment by srittau** [comment]
Closing this per @JelleZijlstra's comment.
