### ISSUE TITLE
django-cmsplugin-blurp issue

### ISSUE THREAD

**Issue by princedesmers69** [python/typeshed#1742]
Hi,

I am trying to install Combo, a django cms based.

I am using this command on Windows 7:
python -m -pip install --proxy=myproxy requirements.txt

An error occurs after the installation of django-cmsplugin-blurp:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\nurien\appdata\local\temp\pip-build-a1x69l\django-cmsplugin
-blurp\setup.py", line 82, in <module>
        long_description=file('README').read(),
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\nurien\a
ppdata\local\temp\pip-build-a1x69l\django-cmsplugin-blurp\

What can I do to overcome this issue please?

**Comment by gvanrossum** [comment]
Sorry, this is not the right tracker. Look for a tracker for Combo.
