### ISSUE TITLE
Guidance requested: Should 'Optional[int]' have a default value?

### ISSUE THREAD

**Issue by gossrock** [python/typeshed#1758]
While working with the curses (and related) modules I have come across a error message while using the 'addstr' method on an _curses._CursesWindow

when I call `window.addstr('test')` and then run mypy I get the error: 

`error: No overload variant of "addstr" of "_CursesWindow" matches argument types [builtins.str]`

The documentation at https://docs.python.org/3/library/curses.html states:
> window.addstr(str[, attr])
> window.addstr(y, x, str[, attr])
> Paint the character string str at (y, x) with attributes attr, overwriting anything previously on the display.

inside _curses.pyi we have:
```
class _CursesWindow:
    ...
    @overload
    def addstr(self, str: str, attr: Optional[int]) -> None: ...

    @overload
    def addstr(self, y: int, x: int, str: str, attr: Optional[int]) -> None: ...
```

when I change these optional definitions to be `Optional[int]=None` the error goes away but CONTRIBUTING.md states:

> for arguments that default to None, use Optional[] explicitly (see below for details).

This seems to imply that what is actually there should be correct ... But I get this error in not only this place but in any other place in this module that has an Optional that I don't use.

Am I missing something?

**Comment by srittau** [comment]
The comment in CONTRIBUTING means that you should use `def foo(bar: Optional[int] = ...)` instead of `def foo(bar: int = None)`. So my understanding is that the stubs above should probably be:

```python
class _CursesWindow:
    ...
    @overload
    def addstr(self, str: str, attr: Optional[int] = ...) -> None: ...

    @overload
    def addstr(self, y: int, x: int, str: str, attr: Optional[int] = ...) -> None: ...
```

**Comment by JelleZijlstra** [comment]
Remember that technically speaking, there is no relationship between an argument having an Optional type and being optional in the normal Python sense. The first means that None is an allowed value for the argument, the second that it can be omitted in argument list. You can have a required argument with an Optional type, an optional argument with a non-Optional type, and all other variations.

**Comment by gossrock** [comment]
Ah, that makes sense now. Optional[] != optional. I'll start working on fixing the non-optional Optional[] argument in _curses that the documentation says should be optional Optional[] arguments.

**Comment by gossrock** [comment]
another optional argument question. The documentation has several functions where a group of items is expected together such as this:

> window.getch([y, x])

so either 0 or 2 arguments are expected. Would this be best solved by:

```
@overload
def getch(self) -> _chtype: ...

@overload
def getch(self, y: int, x: int) -> _chtype: ...
```
or would this more liberal option be prefered:
`def getch(self, y: Optional[int] = ..., x: Optional[int] = ...) -> _chtype: ...`

**Comment by gvanrossum** [comment]
If you can do it with the overload that's much better!

**Comment by JelleZijlstra** [comment]
Original question was answered.
