### ISSUE TITLE
Missing data attribute in UserDict, UserList and UserString

### ISSUE THREAD

**Issue by Kentzo** [python/typeshed#1759]
All three classes define the `data` attribute and it's definition is missing in typeshed.

**Comment by gossrock** [comment]
A few notes:
UserDict, UserList and UserString are Python2 only.

the files in question would be:
https://github.com/python/typeshed/blob/master/stdlib/2/UserDict.pyi
https://github.com/python/typeshed/blob/master/stdlib/2/UserList.pyi
https://github.com/python/typeshed/blob/master/stdlib/2/UserString.pyi

UserList.pyi and UserString.pyi have almost no annotation, so confirmed here.
UserDict.pyi has some and the UserDict class has the following definition:

```
class UserDict(Dict[_KT, _VT], Generic[_KT, _VT]):
    data = ...  # type: Mapping[_KT, _VT]

    def __init__(self, initialdata: Mapping[_KT, _VT] = ...) -> None: ...

# TODO: __iter__ is not available for UserDict
```
so data does exist for UserDict (though there may be some reason why it is still failing.)

@Kentzo do you have any code that should work but is failing?

**Comment by Kentzo** [comment]
I encountered the UserData.data problem in PyCharm. Perhaps I had an outdated version back then.
