### ISSUE TITLE
Mypy reports error "Cannot assign to a method" when using tkinter report_callback_exception

### ISSUE THREAD

**Issue by jcrmatos** [python/typeshed#1767]
Hello,

When mypy sees tkinter exception handling like this
`root.report_callback_exception = mainloop_exc_handler`
where mainloop_exc_handler is a function or method to handle exceptions under tkinter mainloop, it reports the error "Cannot assign to a method".

I'm using mypy 0.521 with Python 3.5.4 32b on a Windows 7 SP1 x64.

I was told to open the issue here from the mypy github.

Best regards,

JM

**Comment by Akuli** [comment]
@srittau Can we reopen this? Currently I can't get this to work. Here's a minimal example:

```python3
import tkinter
from types import TracebackType
from typing import Type

def error_handler(typ: Type[BaseException], val: BaseException, tb: TracebackType):
    pass

root = tkinter.Tk()
root.report_callback_exception = error_handler
```

```
$ mypy --custom-typeshed-dir=. asdf.py
asdf.py:11: error: Cannot assign to a method
asdf.py:11: error: Invalid self argument "Tk" to attribute function "report_callback_exception" with type "Callable[[Type[BaseException], BaseException, TracebackType], Any]"
asdf.py:11: error: Incompatible types in assignment (expression has type "Callable[[Type[BaseException], BaseException, TracebackType], Any]", variable has type "Callable[[BaseException, TracebackType], Any]")
Found 3 errors in 1 file (checked 1 source file)
```

**Comment by Akuli** [comment]
here's a minimal example of the same problem

```python3
from typing import Callable

class Foo:  # imagine that this is the tkinter.Tk stub
    bar: Callable[[str], None]

def callback(s: str) -> None:
    print(s)

f = Foo()
f.bar = callback
```

I'm not sure about whether this is a mypy problem or a typeshed problem.

**Comment by srittau** [comment]
This looks more like a mypy problem to me. It is somehow expecting an additional `self` argument here.

**Comment by Jesse205** [comment]
This is not a bug; this is intentional behavior by mypy:  
https://mypy.readthedocs.io/en/stable/error_code_list.html#check-that-assignment-target-is-not-a-method-method-assign

The correct approach is to disable it:

```py
def test_mypy2() -> None:
    pass

Tk().wm_deiconify = test_mypy2  # type: ignore[method-assign]
```
