### ISSUE TITLE
About pprint's stream arg

### ISSUE THREAD

**Issue by FichteFoll** [python/typeshed#177]
According to the [docs](https://docs.python.org/3.5/library/pprint.html):

> An output stream may be set using the stream keyword; the only method used on the stream object is the file protocol’s `write()` method.

Currently the stream arg is specified as `TextIO`, which seems overly restrictive to me. I had my variable declared as `IO[str]`, which supports the `.write()` method just fine and would completely suffice, so I believe that `stream` should at least be stripped down to `IO[str]`.

However, since the code actually ony uses `stream.write()` (I checked the source to verify), `IO[str]` still seems overly restrictive with its ~20 methods.

Should a new private typing type be created in the stub that only defines `write()`?

Related: #163

**Comment by gvanrossum** [comment]
I think it's reasonable to switch this to `IO[str]` (and if you send a PR to do that I'll happily review it). I don't think we should introduce new classes for duck typing like `SupportsWrite`; it's fragile (there aren't many interfaces that are documented to call *just* `write()`).

Eventually we should introduce [protocols](https://github.com/python/typing/issues/11) and then we might be able to deal with this better.

**Comment by FichteFoll** [comment]
#11 sounds almost exactly like what I imagined for this. Alright, let's wait for Protocol support before thinking about a SupportsWrite protocol. I'll submit a pr for `IO[str]` in the meantime.

**Comment by FichteFoll** [comment]
So, I did some testing and found out that the Python 2 implementation of pprint uses literal strings, i.e. `str` bytestrings, while in Python 3 literal strings are also `str` but Unicode strings.

In Py3, `IO[str]` is undoubtedly the correct type, but what would I put in Python 2 to specifically target bytestrings? `bytes` or `str`?

**Comment by gvanrossum** [comment]
You seem to be making up terminology ("literal" strings usually refers to writing a string literal in source code, not to the type itself). But I understand your point. In Python 2 `bytes` is just an alias for `str`, and given that in Python 3 this uses `IO[str]` I think that that's also the best type for Python 2.

**Comment by FichteFoll** [comment]
The usage of the term "literal string" was intended, example: https://github.com/python/cpython/blob/02f91871c1a976530cd2c566cbd6c85ad37f97a4/Lib/pprint.py#L140. Either way, `str` is the default string type in Python 2, so that should be natural.
