### ISSUE TITLE
type.__subclasses__() is inaccurate

### ISSUE THREAD

**Issue by neilconway** [python/typeshed#1782]
Typeshed defines the type of the `__subclasses__()` method for builtin class `type` as taking no arguments:

```
def __subclasses__(self: _TT) -> List[_TT]: ...
```

This is true for most instances of `type`, but not for `type` itself (which is also an instance of `type`):

```
>>> str.__subclasses__()
[]
>>> type.__subclasses__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
>>> type.__subclasses__(type)
[<class 'abc.ABCMeta'>]
```

As a result, a legal function like the following does not typecheck:

```
def iter_subclasses(cls: type, _seen: Optional[Set] = None) -> Iterator[type]:
    """
    Generator over all subclasses of a given class, in depth first order.
    """
    if _seen is None:
        _seen = set()
    try:
        subs = cls.__subclasses__()
    except TypeError:  # fails only when cls is type
        subs = cls.__subclasses__(cls)
    for sub in subs:
        if sub not in _seen:
            _seen.add(sub)
            yield sub
            for sub in iter_subclasses(sub, _seen):
                yield sub
```

Yields:

```
t.py:12: error: Too many arguments for "__subclasses__" of "type"
```

**Comment by gvanrossum** [comment]
Isn't this a more general issue where the distinction isn't so much type vs. the rest of the world but metaclasses vs. regular classes?

**Comment by JelleZijlstra** [comment]
`__subclasses__` really does take a single argument; you're just calling it on the type rather than the instance. It's similar to how `object.__str__()` would fail because you need `object.__str__(object())`.

I'm not really sure how we would fix this in typeshed. Maybe your code should just use `type.__subclasses__(type)`?

**Comment by neilconway** [comment]
@JelleZijlstra Thanks for the explanation! Your workaround works for me.

Happy to close this out now, unless you think there's something that can be done to improve the situation in general?
