### ISSUE TITLE
pprint.pformat should support the `compact` parameter for 3.4+

### ISSUE THREAD

**Issue by gwk** [python/typeshed#1786]
From the docs:
> pprint.pformat(object, indent=1, width=80, depth=None, *, compact=False)
> Return the formatted representation of object as a string. indent, width, depth and compact will be passed to the PrettyPrinter constructor as formatting parameters.
> Changed in version 3.4: Added the compact parameter.

From `typeshed/stdlib/2and3/pprint.pyi`:
`def pformat(o: object, indent: int = ..., width: int = ..., depth: int = ...) -> str: ...`

`PrettyPrinter.pformat` is also annotated incorrectly, because the docs only note the extra parameters informally:
> PrettyPrinter.pformat(object)
> Return the formatted representation of object. This takes into account the options passed to the PrettyPrinter constructor.

`    def pformat(self, o: object) -> str: ...` is lacking those options.

**Comment by gvanrossum** [comment]
Do you feel up to submitting a PR?

**Comment by gwk** [comment]
I’m sure I could find time eventually, but not immediately!

**Comment by JelleZijlstra** [comment]
Fixed by #2162.
