### ISSUE TITLE
BytesIO.name and StringIO.name should not be defined

### ISSUE THREAD

**Issue by srittau** [python/typeshed#1790]
Please consider the following Python 3.6 code:

```python
from io import BytesIO


class NamedBytesIO(BytesIO):

    def __init__(self, content: bytes, name: str) -> None:
        super().__init__(content)
        self.name = name
```

mypy 0.560 complains:

> test.py:8: error: Property "name" defined in "NamedBytesIO" is read-only

This is due to the fact that in typeshed `BytesIO` derives from `BinaryIO`, which defines the `name` property. The actual `BytesIO` implementation does not have such an attribute:

```
>>> from io import BytesIO
>>> BytesIO(b"").name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_io.BytesIO' object has no attribute 'name'
```

Interestingly, `StringIO` does not have this problem:

```python
from io import StringIO


class NamedStringIO(StringIO):

    def __init__(self, content: str, name: str) -> None:
        super().__init__(content)
        self.name = name
```

This checks fine with mypy, since the `StringIO` stub includes a `name` field, which also does not match the implementation:

```
>>> from io import StringIO
>>> StringIO("").name
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '_io.StringIO' object has no attribute 'name'
```

**Comment by gvanrossum** [comment]
Ow, this cuts deep. It seems class `IO` defined in `types.py` has a `name` property. This is one of the problems with poorly specified protocols like IO -- we guess at what's part of the spec and what isn't. We'll probably need another helper class to represent the kinds of files returned by open(), and tighten up the spec of `types.IO`.

**Comment by srittau** [comment]
A previous issue that discussed `StringIO.name`: #598.

**Comment by gvanrossum** [comment]
Rather than trying to fix the deep issues (which seem impossibly hard) let's just add
```py
name = ...  # type: str
```
to `BytesIO` so it matches the hack we have for `StringIO`.

**Comment by gvanrossum** [comment]
(Can you make a PR?)
