### ISSUE TITLE
Extending ContextManager shows typing error

### ISSUE THREAD

**Issue by oxo42** [python/typeshed#1796]
I have extended ExitStack like:
```
class PatchStack(ExitStack):
     def patch(self, *args, **kwargs):
        return self.enter_context(patch(*args, **kwargs))
````
Then in my code I have
```
with PatchStack() as stack:
    stack.patch('the.thing')
```

This works as expected in the tests but I get the type error
```
T484
"ExitStack" has no attribute "patch"
```

This seems to be because when you enter the context manager, it returns the type `ExitStack` [here](https://github.com/python/typeshed/blob/master/stdlib/2and3/contextlib.pyi#L56).

I can work around this by adding a typed `__enter__` method and casting.

```
class PatchStack(ExitStack):
    def patch(self, *args, **kwargs):
        return self.enter_context(patch(*args, **kwargs))
    def __enter__(self) -> 'PatchStack':
        return cast('PatchStack', super().__enter__())
```

This feels kind of janky.

**Comment by ilevkivskyi** [comment]
I think this can be fixed by a self-type. Would you like to make a PR?
