### ISSUE TITLE
PEP 484 forward references should be quoted?

### ISSUE THREAD

**Issue by jtatum** [python/typeshed#180]
PEP 484 mentions that forward references should be quoted:
```python
class Tree:
    def __init__(self, left: 'Tree', right: 'Tree'):
        self.left = left
        self.right = right
```
This convention doesn't seem to be followed in the typeshed stubs, for instance, from datetime:
```python
class date:
    @classmethod
    def fromtimestamp(cls, t: float) -> date: ...
```
Not sure whether the PEP is ambiguous (maybe this isn't necessary in stub files?) or whether this is an error. I realize mypy has no trouble parsing these, but I'm wondering about other type checkers. The latest version of PyCharm, for instance, cannot resolve a stub written this way (see https://youtrack.jetbrains.com/issue/PY-19374).

**Comment by matthiaskramm** [comment]
We should probably follow the spec and quote. So far, it didn't matter much since both pytype and mypy can parse these as-is. But it's good to know that pycharm can't.

**Comment by gvanrossum** [comment]
Hm... While the PEP isn't very clear about this, the intention here is that
since stub files are not executable, the quoting there is unnecessary. So
maybe file this as a PyCharm bug?

**Comment by jtatum** [comment]
The PyCharm bug I filed was closed citing the PEP ;) I'll reopen it.

**Comment by gvanrossum** [comment]
Would you mind linking to the IntelliJ issue here?

**Comment by jtatum** [comment]
Sure: https://youtrack.jetbrains.com/issue/PY-19374

**Comment by gvanrossum** [comment]
Thanks! Could you or anyone reading this submit a PR to edit the PEP to
make this unambiguous?

--Guido (mobile)

**Comment by jtatum** [comment]
Can do.

**Comment by jtatum** [comment]
Attached a patch to http://bugs.python.org/issue26982

**Comment by gvanrossum** [comment]
I'm sorry, I don't like these edits much. They introduce an awkward forward
reference to stub files, and the second diff chunk changes an unimportant
section in an overview of considered but rejected alternatives.

Also, let's move this to the upstream GitHub repo I use for PEP 484 --
github.com/python/typing.

Thanks for giving it a try!

On Sun, May 8, 2016 at 9:03 PM, James Tatum <notifications@github.com>
wrote:

> Attached a patch to http://bugs.python.org/issue26982
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/python/typeshed/issues/180#issuecomment-217771841>
>



-- 
--Guido van Rossum (python.org/~guido)
