### ISSUE TITLE
codecs.iterdecode returns and Iterator but should be a Generator

### ISSUE THREAD

**Issue by vrih** [python/typeshed#1806]
Happy to submit a pull request to fix this but wanted to check I'm on the right track first.

I believe codecs.iterdecode should returns a Generator rather than an Iterator. They are mostly the same, but I had some code lying around similar to:

```
>>> result = codecs.iterdecode("some string", "utf-8")
>>> result.close()
>>> type(result)
<class 'generator'>
```

This code is rejected by mypy as iterators have no `close()` method.

https://github.com/python/typeshed/blob/2a30532f8d250e59b393252332429aa6b2fc6c33/stdlib/2and3/codecs.pyi#L85

**Comment by vrih** [comment]
Pull request submitted: https://github.com/python/typeshed/pull/1807

**Comment by vrih** [comment]
Pull request merged

**Comment by gvanrossum** [comment]
(Pro-tip: next time add "Fixes #XXXX" to the commit message of your PR --
then GitHub will auto-close the issue.)
