### ISSUE TITLE
Should traceback.print_exception() allow None arguments?

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#1821]
Currently, in Python 3 mode, `traceback.print_exception()` is declared to take non-None values only. But e.g. `sys.exc_info()` returns a tuple of `Optional` values. So with `--strict-optional` if you write e.g.
```py
import sys
import traceback
def f() -> None:
    type, value, tb = sys.exc_info()
    traceback.print_exception(type, value, tb)
```
then you'll get
```
_.py:5: error: Argument 1 to "print_exception" has incompatible type "Optional[Type[BaseException]]"; expected "Type[BaseException]"
_.py:5: error: Argument 2 to "print_exception" has incompatible type "Optional[BaseException]"; expected "BaseException"
```
However at runtime (at least in Python 3.6) this seems to be accepted explicitly (`exc_type` is ignored and there are checks to guard against `exc_value` being `None`; `exc_tb` is always optional.

There is no problem with the equivalent code in Python 2, or if `--strict-optional` is omitted.

**Comment by JelleZijlstra** [comment]
All the arguments to `traceback.print_exception` are now Optional.
