### ISSUE TITLE
ZipFile takes unicode as well as str

### ISSUE THREAD

**Issue by anowlcalledjosh** [python/typeshed#1823]
Testcase:

```python
zipfile.ZipFile(u"file.zip", u"r")
```

This is valid in Python 2.7.12, but pytype complains about it, presumably because of [this typeshed definition](https://github.com/python/typeshed/blob/5264fa6d5dab850e3b1c6eccabbe3c72d01bae83/stdlib/2and3/zipfile.pyi#L25):

```python
def __init__(self, file: Union[str, IO[bytes]], mode: str = ..., compression: int = ...,
             allowZip64: bool = ...) -> None: ...
```

I guess the `str` needs to be replaced with `typing.Text`.

This is also true for the `path` argument to `ZipFile.extractall`, and probably more (those are the only two cases I've encountered, and I don't really have time right now to go through all the functions in the module and check whether they accept `unicode`).

**Comment by gvanrossum** [comment]
Yes, this makes sense. Can you submit a PR?

**Comment by anowlcalledjosh** [comment]
Turns out I misremembered what `typing.Text` is (it's `str` in Py3, `unicode` in Py2; I thought it was `Union[str, unicode]` in Py2) – I *think* that doesn't actually change anything, see e.g. #1158. Right?

For the Python-3-specific parts of the stubs, would you prefer for them also to be converted to `Text`, or left as `str`?

**Comment by gvanrossum** [comment]
There's no particular reason to use Text in Py3-only code. In Py2,
Text/unicode is more or less treated as a superclass of str (which isn't
true at runtime, but produces the least problems of all approaches we've
thought of).
