### ISSUE TITLE
Module 'stat' has no attribute 'filemode'

### ISSUE THREAD

**Issue by yurikhan** [python/typeshed#1836]
```python
from stat import filemode
```

```
$ mypy test1.py
test1.py:1: error: Module 'stat' has no attribute 'filemode'
```

Looking in my copy of typeshed/stdlib, I see that `3/stat.pyi` does not contain a stub for `filemode`. `3.4/_stat.pyi` does, but mypy does not see it there.

What is the right way to deal with that?

**Comment by gvanrossum** [comment]
You can submit a PR that adds something like this
```py
if sys.version_info >= (3, 3):
    def filemode...
```
