### ISSUE TITLE
Set difference unexpectedly permissive

### ISSUE THREAD

**Issue by chadaustin** [python/typeshed#1840]
Mypy passes accepts the following snippet, even though the set subtraction is guaranteed to be a no-op.

```
    a: Set[str] = set(["hello"])
    b: Set[bytes] = set([b"world"])
    b -= a
```

Would it make sense to require `Set[T]` for both arguments to a difference operation?

**Comment by gvanrossum** [comment]
But if we did that, wouldn't mypy just infer `T` as `object` and still allow it?

**Comment by chadaustin** [comment]
In context, I had the function's return type as `List[bytes]`, and the return statement `return sorted(b - a)`, so even if `sorted(b - a)` returned `List[object]`, I'd still see a type error when it checks against `List[bytes]`, right?

**Comment by gvanrossum** [comment]
Yeah, but the point is that the set operation itself wouldn't get the error
-- and in some cases the error would come much later and surprise people.

**Comment by chadaustin** [comment]
Better a surprising type error (easily diagnosed with reveal_type) than shipping a no-op to production, as I did before submitting this issue. :)

**Comment by srittau** [comment]
Changing `object` to `_T` in this line:

https://github.com/python/typeshed/blob/9ee458226c212acc2691f014d2a5575f33160d6d/stdlib/3/builtins.pyi#L717

makes mypy complain about the last line in the example above. This seems reasonable to me. (Similar to the other set operations.) This is also in line with the other container types. For example, we only ordering comparisons between lists of the same type, but for sets we allow any set. This is inconsistent.
