### ISSUE TITLE
Annotation for getLevelName in logging does not accept `str` but the code does

### ISSUE THREAD

**Issue by rgabbard** [python/typeshed#1842]
Currently for `getLevelName` in `logging` there is 

```
def getLevelName(lvl: int) -> str: ...
```

However the code for it (Python 3.6.3) accepts a string argument as well:
```
def getLevelName(level):
    """
    Return the textual representation of logging level 'level'.

    If the level is one of the predefined levels (CRITICAL, ERROR, WARNING,
    INFO, DEBUG) then you get the corresponding string. If you have
    associated levels with names using addLevelName then the name you have
    associated with 'level' is returned.

    If a numeric value corresponding to one of the defined levels is passed
    in, the corresponding string representation is returned.

    Otherwise, the string "Level %s" % level is returned.
    """
    # See Issues #22386, #27937 and #29220 for why it's this way
    result = _levelToName.get(level)
    if result is not None:
        return result
    result = _nameToLevel.get(level)
    if result is not None:
        return result
    return "Level %s" % level
```

It is not clear to me from the method's docstring that the behavior of the code with respect to strings is guaranteed, though, so perhaps leaving it as `int` is safer.

**Comment by gvanrossum** [comment]
The docs at
https://docs.python.org/3/library/logging.html#logging.getLevelName imply
that the "reverse" behavior (where it returns an int when a string is
passed in) is considered a mistake and undocumented:

> *Changed in version 3.4:* In Python versions earlier than 3.4, this
> function could also be passed a text level, and would return the
> corresponding numeric value of the level. This undocumented behaviour was
> considered a mistake, and was removed in Python 3.4, but reinstated in
> 3.4.2 due to retain backward compatibility.
>
I think it's a feature that typeshed doesn't repeat this mistake -- if you
find this bug in your code thanks to static typing you should be grateful,
not request a change to typeshed. :-)

**Comment by rgabbard** [comment]
Thanks - since the "reverse" behavior is considered a bug, typeshed is definitely both correct and helpful here.

I think the fundamental problem, though, is that it is difficult for the user (especially someone new to Python) to determine whether or not the reverse behavior in fact *is* a bug.  There are many examples of the deprecated behavior on the web, the code supports the reverse behavior without a comment that its use is deprecated, and [the docstring](https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L118 ) doesn't contain the "Changed in version 3.4... message" (only [the RST docs](https://github.com/python/cpython/blob/master/Doc/library/logging.rst) do, and many inexperienced users would be unaware they need to check both places - you wouldn't for the Java Standard Library, for example).  There is a comment `# See Issues #22386, #27937 and #29220 for why it's this way`, but even if the user tracks down those issues, none of them clearly say the reverse behavior should be considered a bug, and the last even contains the comment "I perhaps should have done a separate API for that, like getLevelForName(), but it's too late now due to backward compatibility requirements - it's been like this for a long time", which implies that the reverse usage is the correct (and perhaps only available) way of obtaining the desired behavior.  

All of that isn't typeshed's problem, of course - is https://bugs.python.org/ the correct place to request such an update to the docstring to clarify the reverse behavior is deprecated?

**Comment by gvanrossum** [comment]
Yeah, if you really think this requires action, bugs.python.org is the
place to request it.
