### ISSUE TITLE
`__slots__` Union type should not include `None`.

### ISSUE THREAD

**Issue by gwk** [python/typeshed#1853]
Consider the following function:
```
def all_slots(type: Type) -> Set[str]:
  '''
  Subclasses of slots classes may define their own slots,
  which hold just the additions to the parent class.
  Therefore we need to iterate over the inheritance chain to get all slot names.
  We use __mro__ here, and hope for the best regarding multiple inheritance.
  '''
  slots: Set[str] = set()
  for t in type.__mro__:
    try: s = t.__slots__
    except AttributeError: break
    else:
      if isinstance(s, str):
        slots.add(s) # single slot.
      else:
        slots.update(cast(Iterable[str], s)) # mypy bug: __slots__ cannot be None.
  return slots
```

Without the cast, using latest mypy/typeshed, I get:
`Argument 1 to "update" of "set" has incompatible type "Optional[Iterable[str]]"; expected "Iterable[str]"`

Mypy thinks that the type of `__slots__` is `Union[str, Iterable[str], None]` (it eliminates the `str` case due to the check above).

However, I don't think `__slots__` can legally be `None`:
```
class Z: __slots__ = None
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object is not iterable
```

**Comment by gvanrossum** [comment]
Looks like you're right -- please submit a fix to remove the `Optional[]`. There's no way in typeshed (or mypy) to express "this may or may not exist" and mypy does not help detecting cases where that may be an issue, but `Optional[]` is definitely not the right way to spell that.

**Comment by gwk** [comment]
It does seem like there should be a generic type understood by Mypy as “possibly an attribute”. I’ve run into this a number of times and had to refactor code in order to express correct type annotations. Usually the refactoring makes the code better but it seems like static checkers should be able handle those idioms. Should this be opened against mypy or std typing?

George

**Comment by gvanrossum** [comment]
I believe this is already a feature request for mypy. It's not always
possible to reliably check it though.
