### ISSUE TITLE
`cfgparser.optionxform = str` gives erroneous error

### ISSUE THREAD

**Issue by adamtheturtle** [python/typeshed#1857]
The example at https://docs.python.org/3.6/library/configparser.html#configparser.ConfigParser.optionxform on hpw to make `ConfigParser` option names gives a `mypy` error.

```console
(e2e) Adam@MacBook-Pro ~/Desktop> cat typeshed_example.py 
from configparser import ConfigParser

cfgparser = ConfigParser()
cfgparser.optionxform = str
(e2e) Adam@MacBook-Pro ~/Desktop> python --version
Python 3.6.4
(e2e) Adam@MacBook-Pro ~/Desktop> mypy typeshed_example.py --show-traceback
typeshed_example.py:4: error: Cannot assign to a method
typeshed_example.py:4: error: Incompatible types in assignment (expression has type "Type[str]", variable has type "Callable[[str], str]")
(e2e) Adam@MacBook-Pro ~/Desktop> python typeshed_example.py 
(e2e) Adam@MacBook-Pro ~/Desktop> 
```

**Comment by adamtheturtle** [comment]
I believe that the `option` parameter [here](https://github.com/python/typeshed/blob/324f1761f451f2e321050ea9815db86dcf1479e8/stdlib/3/configparser.pyi#L133) should be a `Callable` and not a `str`.

**Comment by JelleZijlstra** [comment]
This seems like a mypy bug to me: mypy should allow assigning to a method when the type matches. Could you report a bug against mypy?

**Comment by adamtheturtle** [comment]
Thank you for looking at this @JelleZijlstra . I will close this in favour of https://github.com/python/mypy/issues/5062.
