### ISSUE TITLE
pynamodb 3.2.1 added new methods in Attributes which are not in typeshed

### ISSUE THREAD

**Issue by goheer** [python/typeshed#1858]
pynamodb 3.2.1 added new methods in Attributes which are not in typeshed
`
model_x.update(actions=[ModelX.state.add(1)])
`
will fail will errors like 
`
Is causing these typecheck errors
xxx.py:159: error: Missing positional arguments "attributes", "conditional_operator", "expected_values" in call to "update" of "Model"
xxx.py:159: error: Item "int" of "Union[int, float]" has no attribute "add"
xxx:159: error: Item "float" of "Union[int, float]" has no attribute "add"
`

**Comment by JelleZijlstra** [comment]
Would you be open to sending a pull request? Your summary (which talks about new methods) doesn't match the type errors you give (which talk about missing arguments and wrong types).

**Comment by JelleZijlstra** [comment]
We no longer ship stubs for pynamodb.
