### ISSUE TITLE
Missing hidden field in NamedTuple

### ISSUE THREAD

**Issue by ltworf** [python/typeshed#1861]
this is missing in typing.NamedTuple

```
    _field_types = ...  # type: collections.OrderedDict[str, Tuple[str, Type]]
```

It allows some nice introspection.

I'll open a PR when I can, this is mostly to remind myself.

**Comment by ilevkivskyi** [comment]
I don't think mypy reads `NamedTuple` spec from typeshed. This class is heavily special-cased in mypy, so it may be necessary to fix this in mypy. This is also easy however.

**Comment by ltworf** [comment]
Well I found out it is required because I had to add that line in the file typing.pyi otherwise mypy tells me my code is accessing some field that doesn't exist…
