### ISSUE TITLE
socket.recv_into() types

### ISSUE THREAD

**Issue by tomato42** [python/typeshed#1862]
I've noticed that the type in https://github.com/python/typeshed/blob/master/stdlib/2and3/socket.pyi#L555 :
```
    def recv_into(self, buffer: bytearray, nbytes: int,
        flags: int = ...) -> Any: ...
``` 
for `buffer` is `byterray`

while documentation specifies that `recv_into()` expects a [buffer object](https://docs.python.org/3/library/socket.html#socket.socket.recv_into), in particular `memoryview()` should work while it isn't a subtype of `bytearray()`.

Not sure if the correct solution would be to use `Union` here or if there is some abstract base class for `bytearray` and `memoryview`

**Comment by JelleZijlstra** [comment]
As I understand it, memoryview is implicitly promoted to bytearray. Did you encounter an issue in real code?

**Comment by tomato42** [comment]
no, I haven't encountered issue in real code, was just looking through typeshed code.

I'm not sure it is promoted to bytearray:
```
>>> isinstance(memoryview(bytearray()), bytearray)
False
```

and the interface it exposes is different, e.g. you can't truncate (or extend) a `memoryview`:
```
>>> a = memoryview(bytearray(10))
>>> a[:] = b''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: cannot modify size of memoryview object
>>> a = bytearray(10)
>>> a[:] = b''
>>> a
bytearray(b'')
>>> 
```

**Comment by JelleZijlstra** [comment]
Confirmed that this causes problems:
```
$ mypy --python-version 2.7 --custom-typeshed-dir . samples/recvintomv.py 
samples/recvintomv.py:6: error: Argument 1 to "recv_into" of "socket" has incompatible type "memoryview"; expected "bytearray"
$ cat samples/recvintomv.py 
import socket

sock = socket.socket()
mv = memoryview(b'hello')

sock.recv_into(mv, 1)
```
