### ISSUE TITLE
argparse.ArgumentParser.add_action should return Action, not None

### ISSUE THREAD

**Issue by EvanKrall** [python/typeshed#1878]
add_action [returns](https://github.com/python/cpython/blob/3.6/Lib/argparse.py#L1348) the Action object added, but argparse.pyi has it [returning None](https://github.com/python/typeshed/blob/master/stdlib/2and3/argparse.pyi#L79).

This causes mypy to complain about code like:

```
parser.add_argument("--proto").completer=ChoicesCompleter(('http', 'https', 'ssh', 'rsync', 'wss'))
```
as [suggested by the `argcomplete` docs](https://pypi.python.org/pypi/argcomplete#specifying-completers):

```
error: "add_argument" of "ArgumentParser" does not return a value
```

**Comment by gvanrossum** [comment]
Good catch -- do you feel up to submitting a PR with a fix?

**Comment by EvanKrall** [comment]
Yeah, I can do that tomorrow.
