### ISSUE TITLE
divmod doesn't support Decimal correctly

### ISSUE THREAD

**Issue by euresti** [python/typeshed#1889]
```
from decimal import Decimal
from typing import TYPE_CHECKING

i = 8
f = 8.0
d = Decimal(8)

di = divmod(i, 3)
df = divmod(f, 3)
dd = divmod(d, 3)  # error: Value of type variable "_N" of "divmod" cannot be "SupportsInt"
ddd = divmod(d, Decimal(3))  # error: Value of type variable "_N" of "divmod" cannot be "Decimal"

print(di)  # (2, 2)
print(df)  # (2.0, 2.0)
print(dd)  # (Decimal('2'), Decimal('2'))
print(ddd)  # (Decimal('2'), Decimal('2'))

if TYPE_CHECKING:
    reveal_type(di)  # error: Revealed type is 'Tuple[builtins.int*, builtins.int*]'
    reveal_type(df)  # error: Revealed type is 'Tuple[builtins.float*, builtins.float*]'
    reveal_type(dd)  # error: Revealed type is 'Tuple[typing.SupportsInt*, typing.SupportsInt*]'
    reveal_type(ddd) # error: Revealed type is 'Tuple[decimal.Decimal*, decimal.Decimal*]'
```

**Comment by gvanrossum** [comment]
Interesting. For regular operators like `+` this is dealt with by the operator overloads in decimal.pyi, but mypy doesn't know that `divmod()` should also be treated as a binary operator (deferring to `__divmod__` and `__rdivmod__`).

We can add a hack to typeshed () but I think it's better to fix mypy so it understands `divmod()`.

**Comment by euresti** [comment]
Sounds like fun!  But I think I'll still need a typeshed change to add `__divmod__` and `__rdivmod__` to int and float.

**Comment by euresti** [comment]
Would adding a `SupportsDiv` Protocol be a reasonable thing to do?

**Comment by ilevkivskyi** [comment]
There are already quite a few protocols in typing, I don't think we need more.

**Comment by gvanrossum** [comment]
Yeah, the "one-trick pony" protocols (e.g. SupportsInt) were added as a
crutch, before we had real Protocols that anyone could define as needed.

Just add __[r]divmod__ to the classes that need them (int, float, Decimal
and Fraction, AFAICT).

**Comment by euresti** [comment]
Resolved here https://github.com/python/mypy/commit/63d6e7ccc6f11a3a66e2936ef55f3853a0d60c24
