### ISSUE TITLE
Please submit high-quality stubs for importlib

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#189]
I guess both PY3 and PY2 versions are wanted.

This came up in #183.

**Comment by brettcannon** [comment]
QQ about the `sys.version` checking support; is it reasonable to expect type checkers to follow the checks within a class definition, i.e. place a version guard around methods that were added in later versions of Python?

**Comment by gvanrossum** [comment]
That doesn't present any additional problems; the existing support for `PY2` and `PY3` in mypy already works that way.

**Comment by tharvik** [comment]
Any news? Or can I try to rewrite a cleaner version than #183?

**Comment by brettcannon** [comment]
I'm still planning on writing the stubs in the next month or so (a bit swamped with Python 3.6 stuff ATM).

**Comment by brettcannon** [comment]
Question for @gvanrossum: what directory should I put the stubs in? Importlib was introduced in Python 3.1, but a lot of things have been added over the years. Should I just put it into 3/ ? And how zealous should I be with version checks (e.g. a new method added in Python 3.4)?

And a reminder to myself, I should check what attributes modules have by default and in what versions of Python they became defaults

**Comment by gvanrossum** [comment]
I would put it in 3/, and add sys.version_info checks around new methods. (Mypy currently ignores those, but eventually we will make it respect them, so you might as well put them in now.)

**Comment by brettcannon** [comment]
I'm going to fix this issue step-by-step to make sure I'm doing it correctly, so I'm starting w/ `importlib.__init__` and I will build from there.

I also noticed that the `types` module has the wrong details for modules, so I will fix that as part of this issue as well (`__package__`, `__loader__`, and `__spec__` as initially set to `None` [as of Python 3.4](https://docs.python.org/3/whatsnew/3.4.html); `__doc__` and `__name__` have always existed).

**Comment by brettcannon** [comment]
So I have a problem where mypy doesn't like the Liskov violation that was purposefully introduced into `importlib.abc` (it's all for minimal backwards-compatibility with the deprecated ABC). We have an ABC that defines the method:
```
@abc.abstractmethod
def find_module(self, fullname: str, path: Sequence[_Path] = None) -> Optional[Loader]: ...
```

One subclass overrides this method as:
```
def find_module(self, fullname: str, path: Optional[Sequence[_Path]]) -> Optional[Loader]: ...
```
Notice how `path` no longer has a default value.

The other subclass overrides the method as:
```
def find_module(self, fullname: str) -> Optional[Loader]: ...
```
Notice how `path` is no longer even accepted.

How do you want me to handle this to make mypy happy?

**Comment by tharvik** [comment]
Usually, I was doing in the sub classes
```python
def find_module(self,  # type: ignore
                fullname: str) -> Optional[Loader]: ...
```
That indeed remove the warning by telling mypy to stop caring about it. That may not be the best way to handle it, but I don't see any other which works with the current state of mypy.

**Comment by brettcannon** [comment]
Does mypy differentiate between instance, class, and static methods? I.e. is it worth redefining every method on a subclass if they are made e.g. classmethod?

**Comment by gvanrossum** [comment]
Mypy correctly distinguishes between the three types of methods (most of the time). I'm not sure what you're really asking -- if you really care, can you show a small example?

**Comment by brettcannon** [comment]
I'm just trying to be lazy. :) Basically I have an ABC that defines some method `def foo(self) -> None: ...` and a subclass that makes it a `classmethod`. I was trying to avoid copying the method from the ABC and adding the proper `@classmethod` and changing `self` to `cls` as I have a bunch of methods like that in `importlib.machinery`.
