### ISSUE TITLE
argparse.ArgumentParser should have a __getattr__ method

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#1890]
This class acts as an "on-demand" namespace, so mypy will constantly complain about missing attributes on its instances.

**Comment by JelleZijlstra** [comment]
Are you sure you're not confused with `argparse.Namespace`? I don't see anything in ArgumentParser's code about this.

**Comment by ilevkivskyi** [comment]
Sorry, indeed, I was looking in a wrong place. Everything seems to be right.
