### ISSUE TITLE
Match object methods should accept a string argument

### ISSUE THREAD

**Issue by detlefla** [python/typeshed#190]
The methods start, end, and span of a Match object accept either an integer as their first argument or a string which must be the name of a (named) group. The stubs require an integer.

**Comment by gvanrossum** [comment]
Good catch. Can you submit a PR to fix this? (Preferably for both Python 2.7 and Python 3.)

**Comment by phouse512** [comment]
Doesn't look like anyone is working on this - I'll make a fix!

**Comment by phouse512** [comment]
@gvanrossum after digging a little I didn't realize this issue was already fixed in e2ce50b525e227108d923c2e0e0ff14cf36cd3e6.  We should probably close this 😄

**Comment by gvanrossum** [comment]
Yes, sorry!
