### ISSUE TITLE
Document unittest.TestCase._feedErrorsToResult and _outcome

### ISSUE THREAD

**Issue by l0b0** [python/typeshed#1912]
These are needed for [working around unittest deficiencies](https://stackoverflow.com/a/39606065/96588).

**Comment by JelleZijlstra** [comment]
To document them, you'd want to ask http://bugs.python.org, not here. We might accept a pull request adding them in typeshed too, depending on our decision in #1902.

**Comment by l0b0** [comment]
[Reported](https://bugs.python.org/issue32927), thanks.
