### ISSUE TITLE
Teach typeshed about the default parameter ssl.SSLContext(protocol=PROTOCOL_TLS)

### ISSUE THREAD

**Issue by nodakai** [python/typeshed#1947]
https://docs.python.org/3.5/library/ssl.html#ssl.SSLContext

> Changed in version 3.5.3: PROTOCOL_TLS is the default value.

vs. https://github.com/python/typeshed/blob/master/stdlib/3/ssl.pyi#L210

```python
 def __init__(self, protocol: int) -> None: ...
```

But actually I don't know how to deal with the fact that it was added in v3.5.3...

**Comment by JelleZijlstra** [comment]
We should pretend that it was this way in all versions of 3.5.
