### ISSUE TITLE
boto stubs fail when running `mypy --strict`

### ISSUE THREAD

**Issue by mgilson-argo** [python/typeshed#1955]
The problem is that [`boto.compat.StandardError`](https://github.com/python/typeshed/blob/master/third_party/2and3/boto/compat.pyi#L7) is typed as `Any`, but elsewhere it is subclassed and `--strict` implies `--disallow-subclassing-any`.

```
typeshed/third_party/2and3/boto/exception.pyi:4: error: Class cannot subclass 'StandardError' (has type 'Any')
```

Perhaps it would be good enough to do the following for the stub?

```py
class StandardError(Exception):
    ...
```

Here's the boto code for anyone interested:  https://github.com/boto/boto/blob/develop/boto/compat.py#L62

**Comment by JelleZijlstra** [comment]
We should be able to replicate the implementation exactly (something like `if sys.version_info > (3, 0): StandardError = Exception else: StandardError = builtins.StandardError`).
