### ISSUE TITLE
StringIO.write as callback for ftplib.FTP.retrbinary fails

### ISSUE THREAD

**Issue by theseanathan** [python/typeshed#1970]
StringIO.write as callback is of type `Callable[[str], int]` whereas retrbinary callback requires `Callable[[bytes], Any]`

Suggest doing it as `Callable[[Union[str, bytes]], Any]`

**Comment by theseanathan** [comment]
Similarly but not exactly tied together:
FTP __init__ arguments for `user` and `password` only accept `str` but when passing in an environment var, I pass in `Optional[str]`, there may be some workaround by I think `Optional[str]` might be better?

**Comment by JelleZijlstra** [comment]
I tried passing `StringIO.write` as a callback to retrbinary in Python 3.7, and it fails at runtime because the retrbinary callback really does need a bytes, not a str. I don't think a change to the stubs is required.
