### ISSUE TITLE
math.isnan and math.isinf should allow Decimal type

### ISSUE THREAD

**Issue by brycepg** [python/typeshed#1975]
The isinf and isnan can process `decimal` types:
```
import math
from decimal import Decimal
math.isnan(Decimal("nan"))
```
evaluates to `True`

Also `isinf` and `isnan` do no error out when passed `int` types. (Just always return false) Should that mean the stub should allow `int` to be passed as well?

**Comment by gvanrossum** [comment]
When float is declared, int is always accepted. For the math module in
particular, it seems that it takes anything that can be converted to float.
Maybe the signatures need to be changed to use typing.SupportsFloat?
