### ISSUE TITLE
concurrent.futures.wait stub uses a tuple instead of DoneAndNotDoneFutures

### ISSUE THREAD

**Issue by bw-matthew** [python/typeshed#1976]
The [definition of wait](https://github.com/python/typeshed/blob/2c6296034fc107689c489b973e82959fe7d06807/stdlib/3/concurrent/futures/_base.pyi#L43) indicates that it returns `Tuple[Set[Future[_T]], Set[Future[_T]]]`. The actual return type is [a DoneAndNotDoneFutures namedtuple](https://github.com/python/cpython/blob/master/Lib/concurrent/futures/_base.py#L307).

The problem with this is that the type inference is not able to determine that `done` and `not_done` are members of the tuple. If you use the namedtuple by indexing it then type checking works, however I find that compromises readability.

There is a definition for `DoneAndNotDoneFutures` in the same file which appears to be unused, so perhaps it was overlooked?

**Comment by JelleZijlstra** [comment]
I tried implementing this with:
```
class DoneAndNotDoneFutures(Tuple[Set[Future[_T]], Set[Future[_T]]]):
    done: Set[Future[_T]]
    not_done: Set[Future[_T]]

def wait(fs: Iterable[Future[_T]], timeout: Optional[float] = ..., return_when: str = ...) -> DoneAndNotDoneFutures[_T]: ...
```
which is similar to what the linked pull request did.

Unfortunately, mypy does not support generic tuples, as an implementation detail. So our options are basically to not support the done/not_done attributes or return Any. We're going with the first solution for now.

**Comment by bw-matthew** [comment]
Thanks for trying to implement this. I'm pleased that your approach was similar to mine.

Are there plans to implement generic tuples in future? What would be required to do so?

If this will never be supported then this issue should be closed.

**Comment by Philipp91** [comment]
I'm getting errors for `wait(...).done`. Even if generic tuples are never supported, leaving `Tuple[Set[Future[_T]], Set[Future[_T]]]` in place doesn't seem like the right solution.

**Comment by Phlogistique** [comment]
Should we make it a NamedTuple of Future[Any] in the meantime? That turns a false positive problem into a false negative problem.

**Comment by srittau** [comment]
@Phlogistique Sounds like a good idea to me. We should also include a comment to explain what the problem is.

**Comment by lladhibhutall** [comment]
@srittau Can you explain what the problem is? I can submit a patch.
