### ISSUE TITLE
How to specify constants of type NoneType?

### ISSUE THREAD

**Issue by matthiaskramm** [python/typeshed#2]
PEP 484 says "By default, None is an invalid value for any type". However, in the Python standard library there are class-level and module-level constants that are legitimately None.

Examples:

```
  formatter.py.AS_IS
  hmac.digest_size
  cgi.FieldStorage.FieldStorageClass
  copy.PyStringMap
```

Should we allow these to be declared using e.g. something like

```
  AS_IS = Undefined(NoneType)
```

?

**Comment by vlasovskikh** [comment]
The variables could be of their concrete type or of an optional concrete type depending on whether it is desirable to have the check for `None` enabled for them.

For example, a PEP 484 compatible definition of `hmac.digest_size` could look like this:

```python
digest_size = ...  # type: int
```

or like this:

```python
digest_size = ... # type: Optional[int]
```

**Comment by gvanrossum** [comment]
Maybe one of the following should be declared best practice?
```
foo = None  # type: object
foo = None  # type: Optional[object]
```
All of these work today with mypy.

**Comment by matthiaskramm** [comment]
What about

```
foo = None  # type: None
```

It doesn't work in mypy yet, but mypy's error message sounds like it could, in the future.

**Comment by gvanrossum** [comment]
I was trying to avoid proposing that requires mypy changes, since it
looks like mypy treats the type `None` quite special. But sure, we'll
add that to the list of possibilities. @JukkaL, thoughts?

**Comment by gvanrossum** [comment]
This is almost(ish :-) over. With `--strict-optional`, mypy does not complain about
```
x = None # type: None
```
We'll just have to finish for the strict None checking flag in mypy to become the default.

**Comment by JelleZijlstra** [comment]
`x = None  # type: None` works fine in mypy with python/mypy#3024 merged.

I'm submitting a PR to fix the specific objects @matthiaskramm mentioned.
