### ISSUE TITLE
Question on the type signature of __radd__ for the float class

### ISSUE THREAD

**Issue by rmonat** [python/typeshed#2021]
I played with the following code:
```python
x = 3
y = 7.0 # so y is a float
z = x+y # and z too
```

From what I understand of the inner workings of Python, we know that x has field `__add__`, so we'll try to perform `x.__add__(y)`. This returns `NotImplemented`, so then Python tries `y.__radd__(x)`, which gives back 10.0. 

I don't think that `int` is a subtype of `float`, so why is the type [signature of `__radd__`](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L177) for the `float` class the following?
`    def __radd__(self, x: float) -> float: ...`

I thought it should be something like
`    def __radd__(self, x: Union[int, Maybe some other types]) -> float: ...`

**Comment by JelleZijlstra** [comment]
`int` is, in fact, implicitly a subtype of float for typing purposes. See https://www.python.org/dev/peps/pep-0484/#the-numeric-tower.

**Comment by rmonat** [comment]
Oh wow, that's confusing me a bit. Thank you for your answer!
