### ISSUE TITLE
math.ceil parameter should have type numbers.Real

### ISSUE THREAD

**Issue by maltek** [python/typeshed#2030]
Using `ceil` with rationals, mypy currently complains because rationals aren't floats:

    import fractions, math
    math.ceil(fractions.Fraction(0, 5))

I think [numbers.Real](https://docs.python.org/3/library/numbers.html#numbers.Real) is the correct ABC for `math.ceil`. The other functions (`floor`, `round`, `trunc`) mentioned in the `numbers.Real` documentation probably need to be fixed, too.

**Comment by gvanrossum** [comment]
Already fixed in master -- all functions in `math` now take `SupportsFloat` arguments instead of `float`.
