### ISSUE TITLE
sqlite3.connect's factory argument expects Optional[Connection]

### ISSUE THREAD

**Issue by wsanchez** [python/typeshed#2038]
I'm getting this error:

```console
error: Argument "factory" to "connect" has incompatible type "Type[Connection]"; expected "Optional[Connection]"
```

for this code:

```python
sqlite3.connect(endpoint, factory=Connection)
```

where `Connection` is a subclass of `sqlite3.Connection`.

My read of this error is that the type hints are expecting an (optional) instance of `sqlite3.Connection`, but the argument is meant to take a factory, meaning a callable that produces a connection.

So I think this should be expecting `Callable[..., sqlite3.Connection]`.

**Comment by JelleZijlstra** [comment]
I think I fixed this in #2026 (due to go out with this week's mypy release).
