### ISSUE TITLE
itertools.chain's T

### ISSUE THREAD

**Issue by ambv** [python/typeshed#2049]
Currently typeshed encodes `itertools.chain()` as follows:
```py3
class chain(Iterator[_T], Generic[_T]):
    def __init__(self, *iterables: Iterable[_T]) -> None: ...
    def __next__(self) -> _T: ...
    def __iter__(self) -> Iterator[_T]: ...
    @staticmethod
    def from_iterable(iterable: Iterable[Iterable[_S]]) -> Iterator[_S]: ...
```

What that means is that every iterable being part of the chain is required to be of the same type. This is not a runtime requirement.

What should happen instead is that for each iterable in `*iterables`, its own unique `T` should be added to a `Union` which the `chain()` then assumes as its own generic type. So that this becomes possible:
```
iter = itertools.chain([1, 2, 3], ("1", "2", "3"))
```

Note that the problem is not with the type annotation on `iter`, the problem is with typeshed's definition of `chain()` which will reject the call to `chain()` in the example above.

**Comment by ambv** [comment]
cc @revfried

**Comment by JelleZijlstra** [comment]
Shouldn't type checkers here infer `_T` to be the common base type of all arguments?

**Comment by gvanrossum** [comment]
Lots of things are valid at runtime but questionable for static type checking. We disallow `[0, 1] + ['a', 'b']` too, for the same reason we disallow this with `chain()` -- it's more likely a mistake than intentional.

**Comment by ambv** [comment]
Hm, I need to work on a nice minimal example of what I'm seeing because the ones I tried to make now work just fine (as long as you declare the type of the variable before-hand).

**Comment by gvanrossum** [comment]
Possibly your real-world code hit a bug in mypy. IIRC there's a bug somewhere in using context for inference of generic calls (IIRC it happens when the type solver has to backtrack in a certain way).

**Comment by JelleZijlstra** [comment]
So @ambv is there still a typeshed issue here that needs fixing?

**Comment by srittau** [comment]
Closing for now, please reopen if there is still a typeshed issue.
