### ISSUE TITLE
Add stubs for OpenSSL.SSL

### ISSUE THREAD

**Issue by ohemorange** [python/typeshed#2052]
[Certbot](https://github.com/certbot/certbot) is working on using mypy in our development process! We rely on OpenSSL.crypto and OpenSSL.SSL, and I only see stubs for the former. It would be great to have them for the latter as well.

**Comment by gvanrossum** [comment]
Can you take a stab at contributing these yourself?

**Comment by ohemorange** [comment]
Possibly!

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
