### ISSUE TITLE
OrderedDict views are reversible, but are not recognised as such

### ISSUE THREAD

**Issue by mjpieters** [python/typeshed#2078]
MyPy won't accept the following:

```
from collections import OrderedDict
d: OrderedDict = OrderedDict()
list(reversed(d.values()))
```

which results in 

```
odview.py:3: error: No overload variant of "reversed" matches argument types [typing.ValuesView[Any]]
```

The dict views produced by `OrderedDict` do implement `__reversed__` but do not inherit from `collections.abc.Reversed`.

**Comment by gvanrossum** [comment]
Sounds like a protocol would be the solution. Can you submit a PR?
