### ISSUE TITLE
Type for generic_visit of NodeTransformer is wrong

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#2085]
The stub for the `ast` module states that the `generic_visit(self, node: AST)` function of the `NodeTransformer` class returns `None`. However it returns something that is of the same type of `node`. So the signature should probably be changed to something like: `generic_visit(self, node: T) -> T`, where `T` is bound to `AST`.

**Comment by gvanrossum** [comment]
Thanks for the report -- do you have time to submit a PR that fixes it?

**Comment by srittau** [comment]
Fixed for Python 3 in #2486, the Python 2 version could probably use the same fix.
