### ISSUE TITLE
MutableSet.__ior__ signature

### ISSUE THREAD

**Issue by Copper-Head** [python/typeshed#2090]
Currently [this method](https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L294) expects an `AbstractSet[_S]` as an argument. However, if one takes a peek at its implementation, any `Iterable[_S]` would actually work too. This appears to be true for some other in-place dunder methods. Could we maybe adjust the typeshed signature?

Feedback especially welcome from @matthiaskramm, who (according to git) authored this.

Thanks in advance!

**Comment by matthiaskramm** [comment]
Not convinced:

```
$ python
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> x = {1,2,3}
>>> x |= (1,2,3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for |=: 'set' and 'tuple'
```

Which implementation are you talking about?

**Comment by gvanrossum** [comment]
I assume Ilia is referring to `MutableSet.__ior__` in collections.abc. This does indeed accept any iterable. But since (concrete) Set is supposed to be a subclass of this, and it doesn't support this, I don't think we should change the signature in typeshed.

**Comment by Copper-Head** [comment]
Hmm, so if I implement the `OrderedSet` [recipe](http://code.activestate.com/recipes/576694/) by Raymond Hettinger, I need to somehow override the type hints of the `__ior__` method on that class, otherwise `mypy` complains when I do this:
```python
OrderedSet([1, 2, 3])
```
Even though at run-time this is entirely valid.

Is it weird to find this counter-intuitive and unsatisfying?
