### ISSUE TITLE
ctypes windows only elements should be typechecked on linux

### ISSUE THREAD

**Issue by ostcar** [python/typeshed#2099]
We have an program that can be run on linux and windows. But we use `ctypes.WinDLL('shell32.dll')` in a function, that is only run on windows.

After you added the sub-file for ctypes, mypy (on linux) returns the error ` Module has no attribute "WinDLL"`.

Is it possible, to remove [this line](https://github.com/python/typeshed/blob/142c7488a579c3ab51e2bb6f6a180d5748fa8666/stdlib/2and3/ctypes/__init__.pyi#L30)? Even when the class does not exist on a non-windows machine, it should still be possible to statically check the code.

**Comment by gvanrossum** [comment]
You can type-check such code by passing `--platform win32` to mypy.

**Comment by jtpavlock** [comment]
Would this then uncover other platform related issues? I think the goal is to not show any platform-specific errors when creating cross-platform software.

**Comment by hauntsaninja** [comment]
Type checkers are expected to understand platform checks: https://www.python.org/dev/peps/pep-0484/#version-and-platform-checking
