### ISSUE TITLE
how to specifiy type for structural typing?

### ISSUE THREAD

**Issue by tharvik** [python/typeshed#210]
Sometimes, the documentation say that a given object should implement a givens set of method, to be valid as an argument, but not necesseraly extending from a given class. Is there a way to explicit it?

For example, take the [`http.cookiejar.CookieJar.add_cookie_header`](https://docs.python.org/3/library/http.cookiejar.html#http.cookiejar.CookieJar.add_cookie_header) method. It is said that

> The _request_ object (usually a urllib.request..Request instance) must support the methods `get_full_url()`, `get_host()`, `get_type()`, `unverifiable()`, `has_header()`, `get_header()`, `header_items()`, `add_unredirected_header()` and `origin_req_host` attribute as documented by urllib.request.

But I didn't find a better way than to simply write that _requets_ should extend from `urllib.request.Request`.

**Comment by JukkaL** [comment]
There is no way to do this right now. See https://github.com/python/typing/issues/11 for a proposal to fix the limitation. 

Sometimes you'll be able to use an ABC, but this ABC needs to live somewhere where users can import it so it is of limited use. Using a more specific type than strictly needed (such as an existing concrete class) or `Any` are sometimes the only options.

**Comment by tharvik** [comment]
Ok, I'll use a concrete class then, thanks.
