### ISSUE TITLE
Add thirdparty py module stubs

### ISSUE THREAD

**Issue by sashkab** [python/typeshed#211]
Add [py module](https://bitbucket.org/pytest-dev/py/)  stub:
### TODO
1. [ ] [ask permission](https://github.com/python/typeshed#third_party) from developer
2. [ ] create stub

**Comment by asottile** [comment]
Just an update here, the module has moved to https://github.com/pytest-dev/py/ and the pytest team has marked it as somewhat-deprecated:

> **NOTE**: this library is in **maintenance mode** and should not be used in new code.

(not saying that it shouldn't be typed! but perhaps it's less important to do so).

**Comment by gvanrossum** [comment]
Well, since nobody has apparently cared since this issue was filed in 2016, and you don't seem to be volunteering to do any of the stubs, I'm just closing the issue. If you want to help just follow up here once you've secured permissions from the `py` package owners.
