### ISSUE TITLE
Make IO and TextIO properties abstract

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#2146]
Currently several properties are concrete, even though `IO` and `TextIO` are ABCs.

Originally https://github.com/python/mypy/issues/266.

**Comment by JelleZijlstra** [comment]
If we do this, we should be careful to not accidentally make subclasses non-instantiable (#1476).

**Comment by AlexWaygood** [comment]
Note that #8726 tried to fix this, but the mypy_primer output indicated that it would have been hugely disruptive
