### ISSUE TITLE
Non-hashable types should declare __hash__: None in typeshed

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#2148]
Currently this passes mypy:
```python
from typing import Hashable

def f(x: Hashable):
    pass

f([])
```
A possible solution may be to add `__hash__: None` to non-hashable types like `list`.

**Comment by JelleZijlstra** [comment]
I tried doing this in #2221, but I get errors like:
```
stdlib/3/builtins.pyi:515: error: Incompatible types in assignment (expression has type "None", base class "object" defined the type as "Callable[[object], int]")
```
We probably need some more special casing in mypy first.

**Comment by ilevkivskyi** [comment]
> We probably need some more special casing in mypy first.

Yes. This particular one can be fixed by changing definition on `object` to `Optional[...]`, but there are other errors, for example one can define a hashable subclass of `dict`. Simplest solution is to just silence the error if is because of a dunder with `None` type in superclass.

**Comment by gvanrossum** [comment]
> We probably need some more special casing in mypy first.

Can you file a separate mypy issue for that? Having that fixes is a prerequisite for fixing this (and hence for #2221).

**Comment by srittau** [comment]
mypy issue is now python/mypy#4266.

**Comment by ilevkivskyi** [comment]
Note that this can also cause false positives, see https://github.com/python/mypy/issues/7328.

Honestly, I don't think having few `# type: ignore`s is a big problem, maybe we should revive https://github.com/python/typeshed/pull/2221 to mitigate this until we implement some special-casing in mypy?

**Comment by srittau** [comment]
So from what I understand we would add `__hash__ = None  # type: ignore` to unhashable classes? I'm fine with that. (Although not needing `# type: ignore` would be better, of course.)

**Comment by ilevkivskyi** [comment]
> So from what I understand we would add `__hash__ = None  # type: ignore` to unhashable classes?

Yes, or maybe better `__hash__: None  # type: ignore` (to have a consistent style, plus IIRC pytype likes the latter more).
