### ISSUE TITLE
Missing attributes found running mypy on the standard library

### ISSUE THREAD

**Issue by ethanhs** [python/typeshed#2149]
The following are missing from stubs:
- [x] codecs
- [x] pkgutil.read_code
- [x] inspect.CO_COROUTINE
- [x] inspect.CO_ASYNC_GENERATOR
- [x] pickle.bytes_types
- [x] pickle.decode_long
- [x] tkinter.simpledialog
- [x] pdb.Pdb
- [x] msvcrt.setmode
- [x] sre_compile.SRE_FLAG_*
- [ ] urrlib.request.HTTPError
- [ ] docutils.parsers.rst.Parser
- [ ] docutils.frontend
- [x] multiprocessing.get_start_method
- [x] multiprocessing.get_context
- [x] multiprocessing.TimeoutError
- [x] multiprocessing.AuthenticationError
- [x] multiprocessing.BufferTooShort

There also seem to be several uses of `_thread`, but I'm not familiar with typeshed's policy with "private" modules.

**Comment by srittau** [comment]
`msvcrt.setmode()` will be added in #4548.

**Comment by srittau** [comment]
I checked a few more items that exist now.

**Comment by srittau** [comment]
#4554 addresses most of these, with the exception of `tkinter.simpledialog` and `docutils.*`. The latter isn't part of the stdlib, so I wonder where this is referenced. There is already a stub for `_thread`, so this should also be fine.

**Comment by srittau** [comment]
@ethanhs Do you remember what you did to check the stdlib? Was it a simple mypy call or was it more involved? I think it would be good idea for us to run a check like this on a regular basis.

**Comment by ethanhs** [comment]
@srittau I'm pretty sure it was a direct invocation of mypy on typeshed

**Comment by hauntsaninja** [comment]
stubtest will find missing things (in CI we run with `--ignore-missing-stub`, so it doesn't)

**Comment by srittau** [comment]
Apart from the problem with `urllib.request.HTTPError` (for which I filed python/cpython#22304), all should be fixed, although `docutils` mostly consists of `__getattr__()` stubs.

**Comment by ethanhs** [comment]
Wow awesome! 🎉
