### ISSUE TITLE
urllib.request.OpenerDirector missing addheaders attribute

### ISSUE THREAD

**Issue by sushain97** [python/typeshed#2163]
`OpenDirector.addheaders` is referred to in https://docs.python.org/3/library/urllib.request.html#examples. However, the stubs do not include it:

https://github.com/python/typeshed/blob/2ba90a65c0cf4d196a971e1c0b0362bb735e8e6d/stdlib/3/urllib/request.pyi#L70-L74

Note that older stubs for Py2.x do in at least one place:

https://github.com/python/typeshed/blob/100a071729758207775fda2ee5c0982bc7deae2c/stdlib/2/urllib.pyi#L13-L19

Happy to submit a 1-line PR if that's not too small of a change:

```diff
diff --git a/stdlib/3/urllib/request.pyi b/stdlib/3/urllib/request.pyi
index 23e6e91..486a758 100644
--- a/stdlib/3/urllib/request.pyi
+++ b/stdlib/3/urllib/request.pyi
@@ -68,6 +68,7 @@ class Request:
     def header_items(self) -> List[Tuple[str, str]]: ...

 class OpenerDirector:
+    addheaders = ...  # type: List[Tuple[str, str]]
     def add_handler(self, handler: BaseHandler) -> None: ...
     def open(self, url: Union[str, Request], data: Optional[bytes] = ...,
              timeout: float = ...) -> _UrlopenRet: ...
```

I did not notice any other similar missing attributes for `OpenerDirector` from the docs and the source doesn't have any others that should unambiguously be public.

**Comment by JelleZijlstra** [comment]
Please do submit a PR!

We prefer using Python 3.6 syntax (`addheaders: List[Tuple[str, str]]`) though.

**Comment by JelleZijlstra** [comment]
It's fine to switch the whole file.
