### ISSUE TITLE
"BinaryIO" has no attribute "readinto"

### ISSUE THREAD

**Issue by blazewicz** [python/typeshed#2166]
I'm using `readinto` on a binary file in my project with static typing and I have a problem with `typing.BinaryIO` class.

Sample code reproducing error:

```Python
# foo.py
buf = bytearray(16)
with open('/dev/random', 'rb') as h:
    h.readinto(buf)
print(buf)
```

Script executes fine, but mypy complains about missing method "readinto".

```
$ python3 -V
Python 3.6.5
$ python3 -m mypy -V
mypy 0.600
$ python3 foo.py
bytearray(b'\x96\x91m\xe0\x8c\xcb\xa4h\xea\xe3.\x0c\xba\x04L7')
$ python3 -m mypy foo.py
foo.py:3: error: "BinaryIO" has no attribute "readinto"
```
The docs read as following:

> Even though IOBase does not declare read(), readinto(), or write() because their signatures will vary, **implementations and clients should consider those methods part of the interface**. Also, implementations may raise a ValueError (or UnsupportedOperation) when operations they do not support are called.
[source](https://docs.python.org/3/library/io.html#io.IOBase)

I've checked and this is already marked as a TODO `typing.pyi`, so I'm just bumping the issue.
https://github.com/python/typeshed/blob/97d9f2eb2c7c7f958ecb006c961d8872f2582802/stdlib/3/typing.pyi#L432

**Comment by gvanrossum** [comment]
Agreed, readinto() should be added to BytesIO in typing.py and to both
typing.pyi in typeshed.

**Comment by anderseknert** [comment]
Had the same error with getvalue() - at least I found this issue eventually. Just chipping in here to hopefully save others some time should they encounter it too.

**Comment by srittau** [comment]
This needs to be added to typing before it can be added to typeshed. Opened python/typing#659.

**Comment by JukkaL** [comment]
There may be some confusion between `BytesIO` and `BinaryIO` above. Should `readinto()` added to `BinaryIO` or `BytesIO`?

@anderseknert `getvalue()` is defined in `BytesIO` but not in `BinaryIO`, which I believe to be correct.

**Comment by anderseknert** [comment]
Oh, right, thanks for the correction @JukkaL - fortunately I found this issue due to @gvanrossum mentioning BytesIO above. The `getvalue()` method seems missing from `BytesIO` still, but perhaps that should be a separate issue.

**Comment by socketpair** [comment]
`error: "IO[bytes]" has no attribute "readinto" `

The same

**Comment by srittau** [comment]
Closing this here. This needs to be sorted out in `typing` first.
