### ISSUE TITLE
No stub for setuptools?

### ISSUE THREAD

**Issue by rbtcollins** [python/typeshed#2171]
I see one for pkg_resources, but setuptools is missing - seems like that would be useful, no?

**Comment by gvanrossum** [comment]
Unclear. Not a lot of people run a static type checker over their setup.py
script. What's *your* use case?

**Comment by rbtcollins** [comment]
My usecase is that I wanted to be sure all Python code we wrote (at work) was getting linted, and didn't do anything specific to avoid linting setup.py.

**Comment by JelleZijlstra** [comment]
The reason there's no stub for setuptools is that nobody has contributed one, and the reason nobody has contributed one is probably that type checking setup.py is not that useful for most people (as Guido says).

We'd likely accept a PR adding stubs for setuptools though.

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
