### ISSUE TITLE
updating os.environ from a dict gives: Incompatible types in assignment

### ISSUE THREAD

**Issue by anentropic** [python/typeshed#2177]
Some code:
```python
@contextmanager
def override_environment(**kwargs):
    old_env = os.environ
    new_env = os.environ.copy()
    new_env.update(kwargs)
    os.environ = new_env

    try:
        yield
    except Exception:
        raise
    finally:
        os.environ = old_env
```

mypy complains about `os.environ = new_env` with:

```
error: Incompatible types in assignment (expression has type "Dict[str, str]", variable has type "_Environ[str]")
```

I'm thinking either I need to cast `new_env` to `_Environ` (but where do I import `_Environ` from?)

or in typeshed the `_Environ` type should have some more magic in it to recognise that `os.environ` has setter as well as getter code

**Comment by gvanrossum** [comment]
But at runtime the *are* such things; assigning a regular dict will take
the magic away.

**Comment by srittau** [comment]
Whoops, indeed there is. For some reason I was under the impression `os.environ` is just a regular dict and didn't check. I blame the heat over here.

**Comment by anentropic** [comment]
If I was to prepare a PR implementing eg `__get__` and `__set__` methods on the `_Environ` definition, does that seem like a viable approach?

**Comment by JelleZijlstra** [comment]
I'm not sure that would work.

I don't think there's actually a bug here. Your original code has a type error: `os.environ` is not a dict.

**Comment by gvanrossum** [comment]
Right. Note that `os.environ.copy()` returns a `dict`, not an `os._Environ`. This is how it is at runtime, it's not a bug in mypy or typeshed. I'm guessing the code should just call `os.environ.update(kwargs)`.

**Comment by anentropic** [comment]
Ok I'm being dumb, I copied that pattern from somewhere and just assumed there was some setter magic to handle making it an environ object instead of just a plain dict.

In my case above I can call `os.environ.update` as suggested

It's also possible to `from os import _Environ` and create one from scratch if necessary

Thanks for the help!

**Comment by anentropic** [comment]
> It's also possible to `from os import _Environ` and create one from scratch if necessary

I found a couple of problems with this idea

```
In [1]: import os

In [2]: type(os.environ)
Out[2]: os._Environ
```

but mypy reports
```
error: Cannot instantiate abstract class '_Environ' with abstract attributes '__delitem__', '__getitem__', '__iter__', '__len__' and '__setitem__'
```

maybe I'm being dumb again but it looks like a concrete sub-class to me https://github.com/python/cpython/blob/v3.6.5/Lib/os.py#L654

also:
```
flexisettings/utils.py:48: error: Unexpected keyword argument "data" for "_Environ"
flexisettings/utils.py:50: error: "_Environ[Any]" has no attribute "encodekey"
flexisettings/utils.py:51: error: "_Environ[Any]" has no attribute "decodekey"
flexisettings/utils.py:52: error: "_Environ[Any]" has no attribute "encodevalue"
flexisettings/utils.py:53: error: "_Environ[Any]" has no attribute "decodevalue"
flexisettings/utils.py:54: error: "_Environ[Any]" has no attribute "putenv"
flexisettings/utils.py:55: error: "_Environ[Any]" has no attribute "unsetenv"
flexisettings/utils.py:48: error: Unexpected keyword argument "encodekey" for "_Environ"
flexisettings/utils.py:48: error: Unexpected keyword argument "decodekey" for "_Environ"
flexisettings/utils.py:48: error: Unexpected keyword argument "encodevalue" for "_Environ"
flexisettings/utils.py:48: error: Unexpected keyword argument "decodevalue" for "_Environ"
flexisettings/utils.py:48: error: Unexpected keyword argument "putenv" for "_Environ"
flexisettings/utils.py:48: error: Unexpected keyword argument "unsetenv" for "_Environ"
```
the typeshed stub does not fully reflect the actual `_Environ` object

**Comment by JelleZijlstra** [comment]
It's a private object, so you're not supposed to be using it and we make little effort in the stub to make it reflect the runtime object.

**Comment by HarryCaveMan** [comment]
> > It's also possible to `from os import _Environ` and create one from scratch if necessary
> 
> I found a couple of problems with this idea
> 
> ```
> In [1]: import os
> 
> In [2]: type(os.environ)
> Out[2]: os._Environ
> ```
> 
> but if I make this code
> 
> ```python
> def _copy_environ(environ):
>     # type: (os._Environ) -> os._Environ
>     return os._Environ(
>         data=environ.copy(),
>         encodekey=environ.encodekey,
>         decodekey=environ.decodekey,
>         encodevalue=environ.encodevalue,
>         decodevalue=environ.decodevalue,
>         putenv=environ.putenv,
>         unsetenv=environ.unsetenv,
>     )
> ```
> 
> then mypy reports:
> 
> ```
> error: Cannot instantiate abstract class '_Environ' with abstract attributes '__delitem__', '__getitem__', '__iter__', '__len__' and '__setitem__'
> ```
> 
> maybe I'm being dumb again but it looks like a concrete sub-class of `MutableMapping` to me https://github.com/python/cpython/blob/v3.6.5/Lib/os.py#L654
> 
> also:
> 
> ```
> flexisettings/utils.py:48: error: Unexpected keyword argument "data" for "_Environ"
> flexisettings/utils.py:50: error: "_Environ[Any]" has no attribute "encodekey"
> flexisettings/utils.py:51: error: "_Environ[Any]" has no attribute "decodekey"
> flexisettings/utils.py:52: error: "_Environ[Any]" has no attribute "encodevalue"
> flexisettings/utils.py:53: error: "_Environ[Any]" has no attribute "decodevalue"
> flexisettings/utils.py:54: error: "_Environ[Any]" has no attribute "putenv"
> flexisettings/utils.py:55: error: "_Environ[Any]" has no attribute "unsetenv"
> flexisettings/utils.py:48: error: Unexpected keyword argument "encodekey" for "_Environ"
> flexisettings/utils.py:48: error: Unexpected keyword argument "decodekey" for "_Environ"
> flexisettings/utils.py:48: error: Unexpected keyword argument "encodevalue" for "_Environ"
> flexisettings/utils.py:48: error: Unexpected keyword argument "decodevalue" for "_Environ"
> flexisettings/utils.py:48: error: Unexpected keyword argument "putenv" for "_Environ"
> flexisettings/utils.py:48: error: Unexpected keyword argument "unsetenv" for "_Environ"
> ```
> 
> the typeshed stub does not fully reflect the actual `_Environ` object

The args to `os._Environ.__init__` are positional, not kwargs. This should work:
```py
def _copy_environ(environ):
    # type: (os._Environ) -> os._Environ
    return os._Environ(
        environ.copy(),
        environ.encodekey,
        environ.decodekey,
        environ.encodevalue,
        environ.decodevalue,
        environ.putenv,
        environ.unsetenv,
    )
```

You can also create new from scratch with your own data like this:
```py
def _new_environ(data,environ):
    # type: (os._Environ) -> os._Environ
    return os._Environ(
        {environ.encodekey(k):environ.encodevalue(v) for k,v in data.items()},
        environ.encodekey,
        environ.decodekey,
        environ.encodevalue,
        environ.decodevalue,
        environ.putenv,
        environ.unsetenv,
    )
```
