### ISSUE TITLE
Help wanted: stubs needed for `six.moves`

### ISSUE THREAD

**Issue by o11c** [python/typeshed#22]
Some of these might be implemented for the opposite python version, or located in the wrong module for the given version.

Python2:
- attribute urllib.proxy_bypass
- 
- module BaseHTTPServer
- module CGIHTTPServer
- module ConfigParser
- module Cookie
- module Dialog
- module FileDialog
- module HTMLParser
- module ScrolledText
- module SimpleDialog
- module SimpleHTTPServer
- module SimpleXMLRPCServer
- module SocketServer
- module Tix
- module Tkconstants
- module Tkdnd
- module Tkinter
- module UserList
- module UserString
- module cookielib
- module copy_reg
- module dummy_thread
- module email.MIMEBase
- module email.MIMEMultipart
- module email.MIMENonMultipart
- module gdbm
- module repr
- module robotparser
- module tkColorChooser
- module tkCommonDialog
- module tkFileDialog
- module tkFont
- module tkMessageBox
- module tkSimpleDialog
- module ttk
- module urllib2
- module xmlrpclib

Python3:
- attribute urllib.request.AbstractBasicAuthHandler
- attribute urllib.request.AbstractDigestAuthHandler
- attribute urllib.request.CacheFTPHandler
- attribute urllib.error.ContentTooShortError
- attribute urllib.request.FTPHandler
- attribute urllib.request.FancyURLopener
- attribute urllib.request.FileHandler
- attribute urllib.request.HTTPBasicAuthHandler
- attribute urllib.request.HTTPCookieProcessor
- attribute urllib.request.HTTPDefaultErrorHandler
- attribute urllib.request.HTTPDigestAuthHandler
- attribute urllib.request.HTTPErrorProcessor
- attribute urllib.request.HTTPHandler
- attribute urllib.request.HTTPPasswordMgr
- attribute urllib.request.HTTPPasswordMgrWithDefaultRealm
- attribute urllib.request.HTTPSHandler
- attribute urllib.request.ProxyBasicAuthHandler
- attribute urllib.request.ProxyDigestAuthHandler
- attribute urllib.request.ProxyHandler
- attribute urllib.request.Request
- attribute urllib.request.URLopener
- attribute urllib.request.UnknownHandler
- attribute urllib.request.getproxies
- attribute urllib.request.pathname2url
- attribute urllib.request.proxy_bypass
- attribute urllib.request.url2pathname
- attribute urllib.request.urlcleanup
- attribute urllib.request.urlopen
- attribute urllib.request.urlretrieve
- 
- module configparser
- module copyreg
- module dbm.gnu
- module html.entities
- module html.parser
- module http.cookies
- module http.server
- module reprlib
- module tkinter
- module tkinter.colorchooser
- module tkinter.commondialog
- module tkinter.constants
- module tkinter.dialog
- module tkinter.dnd
- module tkinter.filedialog
- module tkinter.font
- module tkinter.messagebox
- module tkinter.scrolledtext
- module tkinter.simpledialog
- module tkinter.tix
- module tkinter.ttk
- module urllib.response
- module urllib.robotparser
- module xmlrpc.client
- module xmlrpc.server

**Comment by o11c** [comment]
To test:

* Clone https://github.com/o11c/mypy and checkout branch `wip-six`.
* In the submodule, clone https://github.com/o11c/typeshed and checkout branch `six`.
* Run `tox -e py27 -e py35 -- six.moves`

**Comment by gvanrossum** [comment]
See https://github.com/python/typeshed/pull/61 for a start!

**Comment by mgeisler** [comment]
I wrote stubs for `configparser` in #116. I'm unsure how it relates to this issue, if at all?

**Comment by gvanrossum** [comment]
It's probably a requirement because six.moves mentions it.

**Comment by asottile** [comment]
Probably a dupe or dupe target of #66

**Comment by gvanrossum** [comment]
It's a sub-task of #66 (it's mentioned in the bullet list there).

**Comment by cclauss** [comment]
+1 for a fix to __error: Module 'tkinter' has no attribute 'dnd'__

__tkinter.dnd__ is [marked as experimental](https://docs.python.org/3/library/tkinter.html?highlight=dnd#tkinter.Tcl) but it still [ships in Python](https://github.com/python/cpython/blob/master/Lib/tkinter/dnd.py) and it still works.

**Comment by JelleZijlstra** [comment]
PRs are welcome!

**Comment by srittau** [comment]
`six.moves` exists in typeshed for both Python 2 and 3.

**Comment by dthkao** [comment]
It exists but AIUI many of the names in six.moves are not fully stubbed out, hence the reason for the bug?
