### ISSUE TITLE
max of empty tuple or tuple of one element

### ISSUE THREAD

**Issue by dfroger** [python/typeshed#2204]
These errors are not cached by mypy:

    max(())  # error not cached by mypy
    max((1,))  # error not cached by mypy
    max((1,2))  # ok

But I don't think it's possible to specify a minimal length for the [first arg (Iterable) or max function](https://github.com/python/typeshed/blob/34b926008e74d563e014e3dcb91b6dd84d76d6b5/stdlib/3/builtins.pyi#L880-L883), could there be another way to make mypy catch the errors?

# Edit

Above description is wrong, actually, only `max(())` is not catched by mypy, and it's not about `Iterable` but `Tuple`:

    max(())  # error not cached by mypy
    max((1,))  # ok
    max((1,2))  # ok

**Comment by JelleZijlstra** [comment]
Yes, there's currently no way to specify that `max()` needs a non-empty iterable. I don't think there's anything to fix in typeshed.

**Comment by gvanrossum** [comment]
Note that max((1,)) is not a runtime error -- only max(()) is.

**Comment by JelleZijlstra** [comment]
Closing as there's nothing actionable in typeshed.
