### ISSUE TITLE
ast Module has no attribute "JoinedStr"

### ISSUE THREAD

**Issue by mbarkhau** [python/typeshed#2205]
Could it be that there is a gap for some of the newer python features?

```bash
$ cat joinedstr_test.py
import ast

def walker(tree: ast.Module):
    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef):
            print("function", node)
        if isinstance(node, ast.JoinedStr):
            print("joinedstr", node)
$ mypy joinedstr_test.py
joinedstr_test.py:7: error: Module has no attribute "JoinedStr"
$ python --version
Python 3.6.5 :: Anaconda, Inc.
$ pip freeze | grep mypy
mypy==0.600
$ python -c "import ast;ast.JoinedStr"
$ echo $?
0
```

**Comment by JelleZijlstra** [comment]
Looks like it. Feel free to submit a PR! JoinedStr and FormattedValue should be in stdlib/3/_ast.pyi.

**Comment by mbarkhau** [comment]
Thanks for the pointer, I hope this is correct. I'm a bit surprised that so much is simply `expr` in there. For example, I think in practice `JoinedStr.values` is `typing.List[typing.Union[ast.Str, ast.FormattedValue]]` and not just `typing.List[expr]`.
