### ISSUE TITLE
Message.WhichOneof should return Optional[str], not Optional[bytes]

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#2216]
This is a bug in third_party/2and3/google/protobuf/message.pyi.

Filing so I can reference it.

**Comment by nipunn1313** [comment]
https://github.com/google/protobuf/blob/fa5a69e73b0dd667ff15062adbc170310d440ee9/python/google/protobuf/internal/python_message.py#L1267

It returns the name of the field from the original `.proto` file. It is not arbitrary bytes - as that file has an encoding.

**Comment by gvanrossum** [comment]
Hm, in my mind `str` does not mean arbitrary bytes either (I use `bytes` for that :-). But if .proto files can have encodings, `Text` is indeed the right type. (I've not worked with .proto files much -- how would one specify an encoding?)

**Comment by nipunn1313** [comment]
https://github.com/google/protobuf/issues/1418 Is the best evidence I could find
