### ISSUE TITLE
Introduce AddrType

### ISSUE THREAD

**Issue by mcepl** [python/typeshed#222]
Address type is described in detail in [Python socket module documentation](https://docs.python.org/2.7/library/socket.html) as:

> Socket addresses are represented as follows: A single string is used for the AF_UNIX address family. A pair (host, port) is used for the AF_INET address family, where host is a string representing either a hostname in Internet domain notation like 'daring.cwi.nl' or an IPv4 address like '100.50.200.5', and port is an integer. For AF_INET6 address family, a four-tuple (host, port, flowinfo, scopeid) is used, where flowinfo and scopeid represents sin6_flowinfo and sin6_scope_id member in struct sockaddr_in6 in C. For socket module methods, flowinfo and scopeid can be omitted just for backward compatibility. Note, however, omission of scopeid can cause problems in manipulating scoped IPv6 addresses. Other address families are currently not supported. The address format required by a particular socket object is automatically selected based on the address family specified when the socket object was created.
> 
> For IPv4 addresses, two special forms are accepted instead of a host address: the empty string represents INADDR_ANY, and the string '<broadcast>' represents INADDR_BROADCAST. The behavior is not available for IPv6 for backward compatibility, therefore, you may want to avoid these if you intend to support IPv6 with your Python programs.
> 
> If you use a hostname in the host portion of IPv4/v6 socket address, the program may show a nondeterministic behavior, as Python uses the first address returned from the DNS resolution. The socket address will be resolved differently into an actual IPv4/v6 address, depending on the results from DNS resolution and/or the host configuration. For deterministic behavior use a numeric address in host portion.

This crazily complicated thing works perfectly well with the Python's duck typing, where just most of the time an address is taken as a black box and handed over from one to another function without much peeking into the true nature of such variable. However, it really doesn't work when the strict (or semi-strict) typing needs to be introduced. Typeshed uses `Union` type like in:

``` python
def bind(self, address: Union[tuple, str]) -> None: ...
```

but it seems to me that it is just one tiny step above `Any` and it actually more confuses the situation than helps in reasoning. Why in the world would one make `Union` from `tuple` and `str`? Does type of one variable just happens to be same as another one, or are they truly of the same type? For that reasons I would suggest introduce `AddrType` (or `NetAddrType`?).

I know that the similar reasoning can lead to the introduction of the zillion other types, but I really don't think it is the case. Most other similar types (e.g., `Element` in the XML universe) are actually objects, so they can be treated as such. Whether it is actually a design flaw of Python, that there is no `Address` class, is an interesting question, but the fact is that I cannot recall any other so complicated type in the standard library, which wouldn't be an object in the same time.

I am not sure whether this should be put into `typing` library itself, or just somewhere into `typeshed`.

**Comment by matthiaskramm** [comment]
AddrType isn't a bad idea, but should probably be kept local to the modules that need it. Consider adding

```
AddrType = Union[tuple, str]
```

to the top of such modules.

**Comment by mcepl** [comment]
Of course, I could and I do so, but it seems that this could be useful to add to ``typeshed`` or even to ``typing`` module.

**Comment by mcepl** [comment]
Actually, reviewer at https://gitlab.com/m2crypto/m2crypto/commit/9c7e74b2e90081c62515cbc3ecb24ecd190abf2b#note_12094513 noticed correctly, that it should be ``Union[Tuple[str, int]]`` instead.

**Comment by JelleZijlstra** [comment]
It seems that adding this to individual stubs (as Matthias) suggested is sufficient. That means there's nothing further to do here, so closing.
