### ISSUE TITLE
Incorrect stub for stdlib::traceback.format_exception()

### ISSUE THREAD

**Issue by nematsakis** [python/typeshed#224]
In the stdlib annotations for Python 2.7 and 3, the type of argument 1 for `traceback.format_exception()` is specified as `List[str]`.  This should be `BaseException` instead. 

This error causes this expression to fail typechecking:
`traceback.format_exception(*sys.exc_info())`

With the error:
`error: Argument 1 to "format_exception" has incompatible type *tuple(length 3); expected List[str]`

**Comment by gvanrossum** [comment]
Want to contribute a fix?

**Comment by phouse512** [comment]
@gvanrossum I can start working on this one if no one else has claimed it.

**Comment by gvanrossum** [comment]
Go for it! Tests are kind of weak here, please test manually and show your
test code and results in the PR (or here).

--Guido (mobile)

**Comment by phouse512** [comment]
Great! I think I have something that works, but I'm trying to figure out how to test it with my already installed version of `mypy`.  I did read [this section](https://github.com/python/mypy/wiki/Creating-Stubs-For-Python-Modules#using-and-testing-new-stubs-files), but it wasn't super clear on a few things..

1. do I create clones of the entire `traceback.pyi` file with my changes in it to override the current one?
2. how do versions work, do I need to put my custom `traceback.pyi` under `stdlib/2.7`, etc?

Thanks for the help! Once I get this figured out, I already have a test example that works.

**Comment by gvanrossum** [comment]
Hmm... those docs don't really apply. Instead, update your clone of the
typeshed repo and run run tests.py there.

--Guido (mobile)

**Comment by phouse512** [comment]
@gvanrossum we can close this now?

**Comment by gvanrossum** [comment]
Yes! The convention is to put "fixes #XXX" in the commit message for a PR that fixes an issue -- then when the PR is merged, GitHub will automatically close the issue. But sometimes we forget and then we close by hand, like now. :-)
