### ISSUE TITLE
imaplib.IMAP4.error is defined as Exception instance in stub

### ISSUE THREAD

**Issue by nakamuray** [python/typeshed#2268]
In `imaplib.pyi`, `IMAP4.error` is defined as Exception instance:
```
class IMAP4:
    error: Exception
    ...
```

but actually, it is a Exception **class**:
```
class IMAP4:
    ...
    class error(Exception): pass    # Logical errors - debug required
    ...
```

This mismatch cause type error (mypy say `error: Exception type must be derived from BaseException`) on code below:
```
import imaplib

try:
    ...
except imaplib.IMAP4.error:
    pass
```

**Comment by JelleZijlstra** [comment]
Would you be able to send a pull request?
