### ISSUE TITLE
Cover key and reverse parameters of heapq.merge (Python 3.5)

### ISSUE THREAD

**Issue by telendt** [python/typeshed#227]
I get the following errors when trying to use new `heapq.merge` arguments introduced in Python 3.5:

```
...: error: Unexpected keyword argument "key" for "merge"
...: error: Unexpected keyword argument "reverse" for "merge"
```

I would gladly contribute a fix, but I don't know how to do it yet. Answers to the following questions would help:
- most of the functions in heapq module did not change - should I start with copy of `stdlib/3/heapq.pyi` or is there a way of "importing" definition from other stub file?
- how about default values? I see them defined in some places (`key` and `reversed` of `builtins.sorted`) but replaced with ellipsis in others (like `key` in `heapq.nlargest`)
- what about optional types? I understand that type is considered optional if default value is None, but what if ellipsis is used (again, `key` in `heapq.nlargest`)?

**Comment by matthiaskramm** [comment]
Your three options are:

- copy&paste the stdlib/3/heapq.pyi stub to stdlib/3.5
- design a stub that works with both Python versions, by doing something like
```
  if sys.version_info >= (3, 5):
    def method(...)
  else
    def method(...)
```
- Add the new optional parameters to the stdlib/3/ stub. (The stub will still work with older Python versions.)

For default parameters, using Ellipsis is preferred. Every now and then, I go through and clean up stubs that use something else.

**Comment by telendt** [comment]
@matthiaskramm: Thanks, I went with option 2.

**Comment by telendt** [comment]
Closing, since this got already merged in https://github.com/python/typeshed/commit/9acc9b31ac9c4e824476cc8178436e9f3f8d117f
