### ISSUE TITLE
Standard library completion overview

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2272]
I have created a Google Docs spreadsheet that lists all Python modules in the standard library and whether they already have  a stub in typeshed: https://docs.google.com/spreadsheets/d/1fNhI-ys9GmjcL19GyMl9gHEOTM4zYcigkPT6uJ6a1CE/edit?usp=sharing

I think this can be useful to give an indication on how "complete" typeshed is. Currently, it only shows whether a stub exists or not, not whether the stub is complete. While I don't plan on systematically checking all stubs for completeness, I will update this spreadsheet occasionally.

Would it make sense to move this document somewhere into this repository, as a markdown or text file or maybe a Wiki page?

**Comment by gvanrossum** [comment]
There's not a lot of information in the spreadsheet yet.

I wonder if you could write a tool that, for each module, imports it and also (somehow) parses the stub and compares the two.

**Comment by srittau** [comment]
That's a good idea. I don't think this can be fully automated, since there are too many corner cases and things that have to be judged manually (for example stubs that are annotated with `Any`), but such a tool could help immensely with flagging (potential) problems. I'll see whether I find time for that in the next few weeks.

**Comment by JukkaL** [comment]
For better prioritization decisions, it would be useful to have some indication of how popular each package is, say by somehow looking at the number of imports in available open source Python code. Several years ago I compiled a small corpus of open source Python code by downloading random packages from PyPI, but my methodology was a bit suspect. Besides, the corpus is already stale, since a lot of things change already in few years.

**Comment by ethanhs** [comment]
FWIW, I came across this issue and remembered that I had downloaded the top ~5000 packages for testing pegen, the new parser for Python.

So I went ahead and gathered data on the most popular modules. Here is a summary of the top 25:

| Name        | % of total imports   |
|-------------|----------------------|
| sys         | 0.198427792570052    |
| os          | 0.18350608596424495  |
| logging     | 0.09608374540382908  |
| re          | 0.08865062761506276  |
| unittest    | 0.06987764676049195  |
| json        | 0.057887980220616204 |
| time        | 0.05407632813490554  |
| warnings    | 0.03979650057055915  |
| uuid        | 0.029431342715861543 |
| copy        | 0.02616647648028401  |
| datetime    | 0.02488271839736275  |
| ctypes      | 0.023519715988335237 |
| tempfile    | 0.022006149359705844 |
| os.path     | 0.019929948015722076 |
| subprocess  | 0.019644668441739573 |
| shutil      | 0.018860149613287688 |
| threading   | 0.018543172308862686 |
| socket      | 0.01819449727399518  |
| io          | 0.018170723976163306 |
| collections | 0.016031127171294537 |
| functools   | 0.016007353873462662 |
| itertools   | 0.01581716749080766  |
| random      | 0.015674527703816405 |
| traceback   | 0.014359071890452643 |

The setup is a little hard to replicate, if you run https://github.com/gvanrossum/pegen/blob/master/scripts/download_pypi_packages.py and untar all the files, and then count the number of imports (I used [this](https://stackoverflow.com/a/44988666) SO post and did some data munging).

**Comment by JukkaL** [comment]
That's very interesting information! It would be interesting to also all collect similar stats for third-party packages, and to find the top stdlib packages that are *not* covered by typeshed right now.

**Comment by CraftSpider** [comment]
Top stdlib packages not covered by typeshed (or even partially covered but marked incomplete) would be nice, as it would give me a place to focus my completion efforts. Previously I've just been working on things basically either alphabetically or by the incredibly scientific 'Whatever looks fun' method.

**Comment by srittau** [comment]
I am closing this as I don't think there is anything actionable here.
