### ISSUE TITLE
Give special objects in typing.pyi more forgiving types

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#2280]
Currently, several special types in `typing.pyi` are defined as `TypeVar = object()`. Therefore, if something goes wrong, then in addition to real errors in user code, mypy reports bogus errors like `"object" not callable`. Maybe we can instead define the special forms as `Any`?

cc: @JukkaL

**Comment by ilevkivskyi** [comment]
(This is a low priority, but still can be a usability improvement.)

**Comment by JukkaL** [comment]
Yeah, sounds good to me. Maybe something `TypeVar: Any` would work?

**Comment by hauntsaninja** [comment]
Most things are annotated as `_SpecialForm`, which isn't too bad. And eg, TypeVar has annotations that are accurate to the runtime.

**Comment by Matausi29** [comment]
﻿
