### ISSUE TITLE
Dict constructor typing is incorrect (too restrictive)

### ISSUE THREAD

**Issue by beamerblvd** [python/typeshed#2287]
The `dict` type has several supported constructor signatures. The one in question is this:

```
def __init__(self, iterable: Iterable[Tuple[_KT, _VT]], **kwargs: _VT) -> None: ...
```

I believe this signature is improperly restrictive. Consider this code:

```
parameters = dict(
    map(str.strip, p.split('=', 1)) if '=' in p else (p.strip(), None)
    for p in encoded_parameters.split(';')
) if encoded_parameters else {}  # type: Dict
```

This is perfectly valid and works well. The code in the `dict` constructor doesn't actually require the iterable argument to contain two-tuples. It merely requires the iterable argument to contain values that can be unpacked each into exactly two values. (It's `for k, v in iterable: ...`). It can be a tuple, a list, or any iterable. However, my static type checker (mypy) complains that the types are incompatible (says it must be an iterable of `Tuple[Any, Any]`).

I'm not, however, certain what the ideal signature would be. Unfortunately, there's no `Unpackable` type. Some possible options:

```
def __init__(self, iterable: Iterable[Iterable[Union[_KT, _VT]]], **kwargs: _VT) -> None: ...
def __init__(self, iterable: Iterable[Iterable[Any]], **kwargs: _VT) -> None: ...
```

Thoughts?

**Comment by srittau** [comment]
Unfortunately I don't think that there is anything that typeshed can do at the moment. Type checkers can not assert that `map()` returns an iterable with at least two items of the correct type. I have opened discussion about this in python/typing#592.
