### ISSUE TITLE
Many redundant methods in subclasses

### ISSUE THREAD

**Issue by rwbarton** [python/typeshed#229]
For example, `dict` is a subclass of `MutableMapping` and hence also `Mapping` and other classes, and almost all of `dict`'s methods are actually provided by one of those superclasses with the same signature. Is there a good reason to repeat the declarations of these methods in `dict`? (Perhaps they predate `dict`'s superclasses?) I tried removing `get` and there seemed to be no ill effects.

One possible reason: it's convenient to see the types of all of `dict`'s methods in one place. But it also creates more work when changing these types, as in #223. For being able to see all the methods of `dict` at once, we could have mypy automatically generate documentation (or perhaps a python documentation tool already understands function annotations).

**Comment by gvanrossum** [comment]
I think it's mostly a historical accident. I would generally discourage people from reading the stubs as a form of documentation, they're really not meant for that.

**Comment by srittau** [comment]
I am going to close this. While those redundant definitions are not harmful, we gladly accept patches that will remove these redundancies.
