### ISSUE TITLE
Fix install failure of pytype on CI

### ISSUE THREAD

**Issue by ymyzk** [python/typeshed#2295]
## Problem
As you can see in https://travis-ci.org/python/typeshed/jobs/398612482, the installation of pytype on CI is failing.

Recent change google/pytype#93 seems to cause this problem.  Now, pytype generates some codes using [a utility script](https://github.com/google/pytype/blob/cc535a1bf9605c4a55bbd0392f44f843db037b10/build_scripts/release.py), so it is not possible to install simply using `pip install -e  git+https://github.com/google/pytype.git@master#egg=pytype`

## Solution
I have some ideas to solve this problem. I think the first option is the most simple one. But if you want to use the latest version of pytype, we need more efforts.
1. Use pytype in PyPI.
2. Modify configuration of typeshed CI to install pytype correctly.
3. Propose a change to pytype which makes it easier to install a master version of pytype.

**Comment by gvanrossum** [comment]
Let's install pytype from PyPI. Can you submit a PR?

If we don't solve this soon (today) I will just push a change that disables the pytype tests until they work again.

**Comment by ymyzk** [comment]
I'll send a PR in a few minutes.

**Comment by rchen152** [comment]
Agh, sorry about that. @ymyzk, thank you for fixing the issue. We (pytype) realized a while ago that we needed to add typeshed testing to our GitHub import process and then never actually assigned anyone to do so. I'll get on it.
