### ISSUE TITLE
error: Enum() expects a string, tuple, list or dict literal as the second argument

### ISSUE THREAD

**Issue by sakurai-youhei** [python/typeshed#2305]
I got an error on following code through mypy.

```python
from enum import Enum

Key = Enum("Key", {k: k for k in map(str.strip, """\
  Home
  Left
  Up
  Right
  Down
  Page_Up
  Page_Down
  End
  Return
  BackSpace
  Tab
  Escape
  Delete
  Shift_L
  Shift_R
  Control_L
  Control_R
  Meta_L
  Meta_R
  Alt_L
  Alt_R
  Multi_key
""".splitlines())})
```

**environment**

```
C:\Users\sakurai>python -VV
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

C:\Users\sakurai>python -m pip list | findstr "mypy typed-ast"
mypy              0.610
typed-ast         1.1.0
```

Should need you any further information, please let me know.

Thanks.

P.S. I'm reporting this issue because of instruction given in mypy's issue template as below.

> Note: if you are reporting a wrong signature of a function or a class in
the standard library, then the typeshed tracker is better suited
for this report: https://github.com/python/typeshed/issues

**Comment by sakurai-youhei** [comment]
FYI: [documentation](https://docs.python.org/3/library/enum.html#functional-api) says:

> The second argument is the source of enumeration member names. It can be a whitespace-separated string of names, a sequence of names, a sequence of 2-tuples with key/value pairs, or a mapping (**e.g. dictionary**) of names to values.

**Comment by JelleZijlstra** [comment]
This seems to be a mypy issue, not a typeshed one; `Enum` is mostly handled through special logic in mypy.

The issue here would seem to be that mypy can't infer from your code what the members of the Enum are going to be, because it only knows how to turn dict literals into Enums. You can open an issue against mypy, but I think it's unlikely that this will be fixed.

**Comment by gvanrossum** [comment]
Yeah, it would be a bit too much to expect mypy to understand the effect of `dict(map(str.strip, "...".splitlines()))` -- that would require executing the code.

The work-around is to run that expression once in Python's REPL (the `>>>` prompt) and copy/paste the resulting dict literal back into your source code, perhaps formatting it a bit nicer.

**Comment by sakurai-youhei** [comment]
@JelleZijlstra Thank you for your giving me the direction.
@gvanrossum Thank you for your giving the idea around at the issue.

Thanks to you guys, I come to find minimal repro code for my further investigation. Once I'll have found out something more, I will report it to mypy. Have a nice day.

```python
from enum import Enum
repro = Enum("Repro", {i: i for i in range(10)})
```
