### ISSUE TITLE
unittest.TestCase.assertRegex should allow bytes

### ISSUE THREAD

**Issue by bmerry** [python/typeshed#2312]
The annotation for unittest.TestCase.assertRegex is currently
```python
def assertRegex(self, text: str, regex: Union[str, Pattern[str]], msg: Any = ...) -> None: ...
```
However, it's also legal to use `bytes`, as long as both `text` and `regex` are bytes. This also affects assertNotRegex and assertRegexpMatches.

**Comment by gvanrossum** [comment]
That should be an easy fix using generics, right? Can you submit a PR?

**Comment by JelleZijlstra** [comment]
You may run into python/mypy#3644 though. In that case, you'll need to use overloads instead (one for bytes and one for str).

**Comment by bmerry** [comment]
> That should be an easy fix using generics, right? Can you submit a PR?

Sure, will give it a try next week.

**Comment by bmerry** [comment]
I've submitted a PR. I gave it a quick test and didn't see any problems like #3644. The error messages in cases where one mixed bytes with str aren't the most informative (`error: Value of type variable "AnyStr" of "assertRegex" of "TestCase" cannot be "object"`), but it does get the right results.
