### ISSUE TITLE
asyncio stubs are missing Python 3.7 and 3.8 methods

### ISSUE THREAD

**Issue by hynek** [python/typeshed#2313]
I’ve tried to migrate a code base to 3.7 and noticed that the asyncio stubs need some love.

The ones I’ve noticed are:

- [x] `asyncio.create_task()`
- [x] `asyncio.run()`
- [x] `asyncio.current_task()`
- [x] `asyncio.all_tasks()`
- [x] `asyncio.get_running_loop()`
- [x] `loop.start_tls()`
- [x] `loop.sock_sendfile()`
- [x] `loop.sendfile()`
- [x] `loop.sock_recv_into()`
- [x] `BufferedProtocol`
- [x] `StreamWriter.wait_closed()`
- [ ] ~~`Task.get_loop()`~~ *(comment by @srittau: not in documentation or implementation)*
- [x] `Future.get_loop()`
- [x] `Server.get_loop()`
- [x] `start_serving` argument for
    - `loop.create_server(start_serving)`
    - `loop.create_unix_server(start_serving)`
- [x] `Server.start_serving()`
- [x] `Server.serve_forever()`
- [x] `Server.is_serving()`
- [ ] `ssl_handshake_timeout` argument for
    - [ ] `asyncio.open_connection()`
    - [ ] `asyncio.start_server()`
    - [x] `loop.create_connection()`
    - [x] `loop.create_server()`
    - [x] `loop.create_accepted_socket()`
- [x] `Handle.cancelled()`
- [x] `ReadTransport.is_reading()`
- [ ] “Loop methods which accept socket paths now support passing path-like objects. ” – that sounds like changes throughout the module?

But I suspect that everything new in 3.7 isn’t covered at all ATM.

Ref: https://docs.python.org/3/whatsnew/3.7.html#asyncio

*Added by @srittau via the report by @Mulugruntz:*

- [x] `asyncio.BaseEventLoop`
- [ ] `asyncio.WindowsProactorEventLoopPolicy`
- [x] `asyncio.windows_events`

*Added by @srittau via the report by @brianjyoung:*

- [ ] loop.create_task() now accepts a name
- [ ] loop.create_connection() supports happy_eyeballs_delay and interleave
New Task methods:
- [ ] get_coro()
- [ ] get_name()
- [ ] set_name()

**Comment by gvanrossum** [comment]
Thanks -- we're dependent on contributors for noticing these things (a systematic search would get unwieldy). Would you mind submitting a PR?

**Comment by hynek** [comment]
I have tried but I cannot run `mypy_selftest.py` ATM:

1. https://github.com/python/typeshed/blob/f582b53ff7de199bb3faabee02542efeb7b01690/tests/mypy_selftest.py#L14 fails on modern pips (`Could not find an activated virtualenv (required).`).
2. After commenting out that line I ran into https://github.com/python/mypy/issues/5329

It would be good if typeshed found a way to use tox for these tests? Trying to install something into my global Python installation (even if it’s just `--user`) is kinda rude. :)

I’ll revisit once I can run the tests.

**Comment by JelleZijlstra** [comment]
I suppose we wrote selftest.py mostly for use in Travis; it's fine to not use it for local development.

**Comment by hynek** [comment]
I’ve updated the bug with a list of things I found now; since this is massive, it will take more than one PR to fix and I’m not taking any ownership in it. I’ll try to fix the top-level functions ASAP.

**Comment by gvanrossum** [comment]
Thanks! Quite a list.

**Comment by Mulugruntz** [comment]
Hi,

I'm reporting here that some more are missing.
I first (wrongly) posted that issue there https://bugs.python.org/issue35987#msg335444 then was redirected here.

I've also opened a ticket there https://github.com/python/mypy/issues/6383
I'll close everything misplaced as soon as it's confirmed that it belongs here :).

**Comment by CraftSpider** [comment]
I think everything in this is completed except for possibly:
- [ ] ssl_handshake_timeout argument for
  * asyncio.open_connection()
  * asyncio.start_server()
- [ ] “Loop methods which accept socket paths now support passing path-like objects. ” – that sounds like changes throughout the module?

**Comment by brianjyoung** [comment]
I know the title says "Python 3.7" but now that we're in the future it feels like this might be an appropriate place to bring up the new 3.8 functionality:

- [ ] `loop.create_task()` now accepts a `name`
- [ ] `loop.create_connection()` supports `happy_eyeballs_delay` and `interleave`
- [ ] New `Task` methods:
  - `get_coro()`
  - `get_name()`
  - `set_name()`

**Comment by srittau** [comment]
All of these are missing from the release notes. 😕

**Comment by gvanrossum** [comment]
Can you report that in bugs.python.org?

**Comment by srittau** [comment]
Already reported in [issue38460](https://bugs.python.org/issue38460).

**Comment by srittau** [comment]
I have updated the original list and will start working on a patch now.

**Comment by hynek** [comment]
NICE! Thanks for picking up my slack!
