### ISSUE TITLE
Adding third-part stub of Leancloud python SDK 

### ISSUE THREAD

**Issue by DionysusG** [python/typeshed#232]
Hi,

I am working on [Leancloud python SDK  ](https://github.com/leancloud/python-sdk) to support static typing, and plan to pull the pyi file to typeshed to keep the codes clean. Is this an available option? I found typeshed haven't merge to add a third-part stub for a few months or so.

**Comment by gvanrossum** [comment]
Yes, that is an option as long as you have agreement of the module's
current developer(s).

--Guido (mobile)

**Comment by gvanrossum** [comment]
So do you have agreement from the module's current developer(s)? Have you even asked? If they have an issue tracker you could ask there and point to this issue and your PR (#317). If they respond positively please add a link here (actually to the PR would be better) and we'll merge it.

**Comment by DionysusG** [comment]
Yes, I do have the agreement. In fact, I am one of the module's current developer. Sorry for the previous confusion; I didn't display my membership info to the public.

**Comment by gvanrossum** [comment]
I'm sorry, we're going to close this. We prefer typehed/third_party to be used only for widely popular packages. In your case you can either instruct your users to point MYPYPATH to a directory containing your stubs, or use inline annotations (and ave them point MYPYPATH to the directory containing your original, annotated code).
