### ISSUE TITLE
encoding of fdopen() does not accept None as argument

### ISSUE THREAD

**Issue by rhysd** [python/typeshed#2321]
Hi team,

I was writing a code like below:

```python
def write_to_file(fd: int, data: Union[str, bytes], kind: str):
    encoding = None
    if kind != 'binary':
        encoding = 'utf8'
    with fdopen(fd, encoding=encoding) as f:
        f.write(data)
```

but type check failed

```
Argument "encoding" to "fdopen" has incompatible type "Optional[str]"; expected "str"
```

This is because `encoding` parameter of `fdopen` is specified as `str`. I wanted to specify `Optional[str]` since encoding is depending on `kind` parameter. So IMO type of `encoding` parameter should be `Optional[str]`. What do you think?

**Comment by JelleZijlstra** [comment]
Optional means that the argument can be None. I just tried running `os.fdopen(1, None)` in 3.7 and got a TypeError, so I don't think we need Optional here.

**Comment by srittau** [comment]
Running `os.fdopen(1, encoding=None)` work, though.

**Comment by JelleZijlstra** [comment]
Right, because the second argument is actually `mode`, not `encoding`. Thanks for catching that!

@rhysd feel free to submit a PR to fix this; it should be an easy change to make.
