### ISSUE TITLE
datetime.date.fromisoformat template missing

### ISSUE THREAD

**Issue by baszoetekouw** [python/typeshed#2328]
Python 3.7 introduced `datetime.datetime.fromisoformat`, `datetime.date.fromisoformat`, and `datetime.time.fromisoformat`.  A type hinting template for `datetime.datetime.fromisoformat` was added, but for the latter two (`date` and `time`) the isoformat template is missing.

**Comment by ceh** [comment]
`datetime.date.fromisoformat` was added in https://github.com/python/typeshed/pull/2393
