### ISSUE TITLE
No overload variant of "defaultdict" matches argument types [functools.partial[...]]

### ISSUE THREAD

**Issue by carver** [python/typeshed#2329]
Issue #1597 looks the same, and I saw

> you can continue to investigate in another issue where you posted.

but I couldn't find [any issues in the repo by @nicktimko ](https://github.com/python/typeshed/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Anicktimko)

If it's preferred to revive #1597 please let me know, and I'll close/copy this in there.

> This issue is fixed

I'm seeing what appears to be the same error in mypy==0.610 

```
No overload variant of "defaultdict" matches argument types [functools.partial[MyCustomClass]]
```

I'm running (something like):

```py
from collections import defaultdict
from functools import partial

class MyCustomClass:
  def __init__(self, myint: int) -> None:
    pass

defaultdict(partial(MyCustomClass, myint=3))
```

Am I doing something wrong? Any help is appreciated.

**Comment by gvanrossum** [comment]
Looks like this is fixed in 0.620.
