### ISSUE TITLE
Stubs for collections.abc

### ISSUE THREAD

**Issue by adamrothman** [python/typeshed#233]
It looks like there's already a `TODO` at https://github.com/python/typeshed/blob/master/stdlib/3/collections/__init__.pyi#L5 but I think it's worthy of a proper issue.

Running `mypy` over any file that imports (or imports from) `collections.abc` results in the following failure:

> error: No library stub file for standard library module 'collections.abc'

**Comment by aleksanb** [comment]
I hit into the same issue when attempting to stub tornado for python3.
Stubgen has recently been improved to handle async/def functions so it can be used to stub out _collections_abc.

I did this locally, but gave up on stubbing the entirety of tornado as it was quite a task,
but if anyone feels like stubbing out _collections_abc it should be 'easier' now :)

**Comment by gvanrossum** [comment]
Hopefully someone can help by adding a stub for collections.abc. This should probably be done by moving the definitions from `collections/__init__.pyi` into `collections/abc.pyi` and then updating `__init__.pyi` to import them back from abc.

**Comment by euresti** [comment]
I believe this is fixed by #671

PS. Sorry about pinging old tasks, I'm trying to find something to help with.  :)

**Comment by gvanrossum** [comment]
It's actually very helpful.
