### ISSUE TITLE
Should HTTPMessage return `Optional[str]` for `__getitem__`?

### ISSUE THREAD

**Issue by asottile** [python/typeshed#2333]
```pycon
>>> from urllib.request import urlopen
>>> urlopen('https://example.com')
<http.client.HTTPResponse object at 0x7fc608f39fd0>
>>> resp = urlopen('https://example.com')
>>> resp.headers['foo']
>>> resp.headers['connection']
'close'
>>> type(resp.headers['connection'])
<class 'str'>
```

```python
import urllib.request
from typing import Optional

resp = urllib.request.urlopen('https://example.com')
x: Optional[str] = resp.headers['connection']
```

```console
$ mypy t.py
t.py:5: error: Incompatible types in assignment (expression has type "Union[str, Header, None]", variable has type "Optional[str]")
```

If this sounds sane, I'd like to add `__getitem__` [here](https://github.com/python/typeshed/blob/cc45366ca5841153f3924037cb26c6dcfe648621/stdlib/3/http/client.pyi#L80)?

**Comment by JelleZijlstra** [comment]
Does it never return `Header`? I think we discussed this in some issue before.

**Comment by asottile** [comment]
I can't seem to find a situation where it returns `Header`, it's possible I'm overlooking something.

**Comment by OJFord** [comment]
> In a model generated from bytes, any header values that (in contravention of the RFCs) contain non-ASCII bytes will, when retrieved through this interface, be represented as [Header](https://docs.python.org/3.5/library/email.header.html#email.header.Header) objects with a charset of unknown-8bit.

from the last paragraph of intro, just above https://docs.python.org/3.5/library/email.message.html#email.message.Message.__len__

**Comment by asottile** [comment]
Interesting!  Though it doesn't appear to be true for `HTTPResponse`:

```bash
 while true; do echo -e "HTTP/1.1 200 OK\r\nContent-Length: 0\r\nWat: $(python -c 'print("\u2603")')\r\n" | nc -l localhost 1500; done
```

```pycon
$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.request import urlopen
>>> x = urlopen('http://localhost:1500')
>>> x.headers
<http.client.HTTPMessage object at 0x7f51af37ae80>
>>> x.headers['Wat']
'â\x98\x83'
>>> type(x.headers['Wat'])
<class 'str'>
```

Some pretty sick mojibake though :)

**Comment by srittau** [comment]
I think the right solution is to override `__getitem__()` et al. in `http.client.HTTPMessage` to not return `Header`.

**Comment by asottile** [comment]
this seems worse now, it's `Any` so all type checking is gone -- this appears to be due to #3045
