### ISSUE TITLE
socket.setsockopt typehints

### ISSUE THREAD

**Issue by mcepl** [python/typeshed#234]
It seems to me that these type hints in typeshed's socket file (at least for python 2.7) are wrong:
```
def getsockopt(self, level: int, optname: str, buflen: int) -> bytes: ...
def setsockopt(self, level: int, optname: str, value: Union[int, bytes]) -> None: ...
```
At least for ``setsockopt`` it seems to me obvious that ``optname`` parameter is defined as ``int``, not ``str`` in the C code (branch ``3.5``, line 663 of ``Modules/socketmodule.c``):

```c
if (PyArg_ParseTuple(args, "iii:setsockopt",                                
                         &level, &optname, &flag)) {                            
...
    }
```

**Comment by gvanrossum** [comment]
This was recently fixed.

--Guido (mobile)
