### ISSUE TITLE
DictReader row dictionaries can have None values

### ISSUE THREAD

**Issue by csvoss** [python/typeshed#2346]
Given CSV files where some rows are incomplete, it is possible for the dictionaries output by DictReader to have None in their values. 

Consider the following python3.6 code:

```python
import csv
from io import StringIO

csv_contents = """\
A,B,C
1,2,3
4,5
"""


def only_takes_strings(x: str) -> None:
    assert isinstance(x, str)


with StringIO(csv_contents) as input_file:
    reader = csv.DictReader(input_file)
    for row_dict in reader:
        print(repr(row_dict))
        for key, value in row_dict.items():
            # Mypy should warn about the following line because
            # value can be None. However, mypy does not warn.
            # The line produces a runtime error.
            only_takes_strings(value)
```

This file produces a runtime error:

```
$ python3.6 example_3.6.py
OrderedDict([('A', '1'), ('B', '2'), ('C', '3')])
OrderedDict([('A', '4'), ('B', '5'), ('C', None)])
Traceback (most recent call last):
  File "example_3.6.py", line 23, in <module>
    only_takes_strings(value)
  File "example_3.6.py", line 12, in only_takes_strings
    assert isinstance(x, str)
AssertionError
```

I would expect mypy to catch this and warn about it, but mypy does not produce an error:
```
$ mypy example_3.6.py

```
---
It looks like this is due to the following lines of [csv.pyi](https://github.com/python/typeshed/blob/6192cce9d93f06e8f4ceaaa5443826892c2f3b2a/stdlib/2and3/csv.pyi):

```python
if sys.version_info >= (3, 6):
    _DRMapping = OrderedDict[str, str]
else:
    _DRMapping = Dict[str, str]
```

These type annotations should presumably be `OrderedDict[str, Optional[str]]` and `Dict[str, Optional[str]]`, instead.

**Comment by csvoss** [comment]
Addendum: Since `csv.pyi` is in `stdlib/2and3`, here's the same issue reproduced in python2.7.

```python
import csv
from StringIO import StringIO

csv_contents = """\
A,B,C
1,2,3
4,5
"""


def only_takes_strings(x):  # type: (str) -> None
    assert isinstance(x, str)


input_file = StringIO(csv_contents)
reader = csv.DictReader(input_file)
for row_dict in reader:
    print repr(row_dict)
    for key, value in row_dict.items():
        # mypy should warn about the following line because
        # value can be None. However, mypy does not warn.
        # The line produces a runtime error.
        only_takes_strings(value)

input_file.close()
```


As before, this file produces a runtime error:
```
$ python2.7 example_2.7.py
{'A': '1', 'C': '3', 'B': '2'}
{'A': '4', 'C': None, 'B': '5'}
Traceback (most recent call last):
  File "example_2.7.py", line 23, in <module>
    only_takes_strings(value)
  File "example_2.7.py", line 12, in only_takes_strings
    assert isinstance(x, str)
AssertionError
```

And as before, mypy does not warn about it:
```
$ mypy example_2.7.py

```

**Comment by csvoss** [comment]
$ mypy --version
mypy 0.620

$ python3.6 --version
Python 3.6.2

$ python2.7 --version
Python 2.7.10

**Comment by JelleZijlstra** [comment]
Thanks for noticing this! I'm a bit worried about the proposed fix because I expect (although I don't have strong evidence) that in most real-world uses of DictReader, all rows are going to be consistent, so it would be unnecessary for users of DictReader to check for None.

**Comment by csvoss** [comment]
Thanks for these thoughts! In my case, we were providing users of a webapp with a tool they could use to upload custom data via a CSV file. The original implementation did not handle these Nones, and it happened once or twice that users tried to upload CSVs with an inconsistent number of commas per row, producing some 500 errors (which we then fixed by starting to handle the None case).

**Comment by csvoss** [comment]
I agree it seems uncommon/unlikely that a CSV file consumer would actually want to *use* those Nones for anything. As-is though, this type annotation may cause Nones to leak into parts of a codebase which we have assumed are safely statically typechecked by mypy.

**Comment by JelleZijlstra** [comment]
Sometimes there's a tradeoff between type safety and convenience. In this case I decided to go for safety and merge your change; we can revisit it if this turns out to be onerous in real-world codebases.

Thanks for your contribution!

**Comment by ilevkivskyi** [comment]
Unfortunately this causes loads of errors in some codebases. So I would propose to revert it for now.
