### ISSUE TITLE
multiprocessing.Process.daemon should be typed as property instead of bool?

### ISSUE THREAD

**Issue by kentavv** [python/typeshed#2361]
I'm just getting into mypy so I could be wrong, but in `stdlib/3/multiprocessing/__init__.pyi` bool is the expected type of multiprocessing.Process.daemon 

```
class Process():
    name: str
    daemon: bool
```

but daemon is a property type

```
$ python3
Python 3.6.6 (default, Jul 19 2018, 14:25:17) 
[GCC 8.1.1 20180712 (Red Hat 8.1.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
import multiprocessing
type(multiprocessing.Process.daemon)
<class 'property'>
```

causing the mypy error

`error: Incompatible types in assignment (expression has type "property", base class "Process" defined the type as "bool")`

on

```
class NoDaemonProcess(multiprocessing.Process):
    # make 'daemon' attribute always return False
    def _get_daemon(self):
        return False
    def _set_daemon(self, value):
        pass
    daemon = property(_get_daemon, _set_daemon)
```

Thank you

**Comment by srittau** [comment]
This is a bug in mypy: python/mypy#4125. For the moment the best solution is to use `# type: ignore`.
