### ISSUE TITLE
argparse.parse_args should have a generic return type

### ISSUE THREAD

**Issue by anowlcalledjosh** [python/typeshed#2366]
(sorry if generic is the wrong word to describe this)

`argparse.parse_args(namespace=MyNamespace())` returns an instance of `MyNamespace`, but it's annotated to always return an `argparse.Namespace`. This means that in order to have type-safety when accessing arguments by using a custom type-annotated class:

```python
class Arguments:
    verbose: bool
    ...
args = argparse.parse_args(namespace=Arguments())
```

you currently need to cast the return value of `argparse.parse_args`.

Also, the passed object doesn't actually have to be a (subclass of) `argparse.Namespace` – a simple subclass of object [is documented to work](https://docs.python.org/3/library/argparse.html#argparse.Namespace).

**Comment by PrajwalM2212** [comment]
@srittau   CPython's `parse_args`  method has 

`if namespace is None:
            namespace = Namespace()`  

so will this be good enough change for the stub
`namespace: Optional[object] = ...) -> object`
