### ISSUE TITLE
assertIn does not accept iterators

### ISSUE THREAD

**Issue by mitya57** [python/typeshed#2381]
Consider this simple test case:
```python
from unittest import TestCase

class MyCase(TestCase):
    def test_in_generator(self) -> None:
        g = (a**2 for a in range(5))
        self.assertIn(9, g)
```

It passes fine with unittest, but mypy reports an error:
```
$ mypy --strict ./test.py 
test.py:7: error: Argument 2 to "assertIn" of "TestCase" has incompatible type "Iterator[int]"; expected "Container[Any]"
```

Please change the argument type of `assertIn`/`assertNotIn` to allow iterators too.

**Comment by srittau** [comment]
@mitya57 Would you care to submit a pull request?

**Comment by JelleZijlstra** [comment]
I think we actually need a `Union[Iterable, Container]`, since there are Containers that are not Iterables.

**Comment by mitya57** [comment]
Ok, here is the pull request: #2447.
