### ISSUE TITLE
Adding lists of subtypes together

### ISSUE THREAD

**Issue by alanhdu** [python/typeshed#2383]
Using `mypy==0.620` and Python 3.6.6, the following code:

```python
from typing import List, Optional

x: List[Optional[int]] = [1, 2, 3]
[None] + x
```

fails with:

```
a.py:4: error: Unsupported operand types for + ("List[None]" and "List[Optional[int]]")
```

This is presumably because lists are invariant w.r.t their generic parameter, and the declration requires a `List` of the same type

https://github.com/python/typeshed/blob/4e40b035c8337cddcf4f94fcd83a2f0d454488b6/stdlib/3/builtins.pyi#L619.

I don't know what the right solution here is -- can we just replace the `x: List[_T]` with `x: List[_T_co]` and make it covariant? Or doe we need another typevar `_U = TypeVar("U", bound=_T)` or something?

**Comment by wy193777** [comment]
#2404 has been reverted. Do we have a solution for this issue?

**Comment by tamuhey** [comment]
+1 from https://github.com/microsoft/pyright/issues/1777
