### ISSUE TITLE
[Question] Is it possible to signal a function returns a specific value

### ISSUE THREAD

**Issue by sk-** [python/typeshed#2390]
Hi everyone, I'm trying to add type annotations for a third_party module, namely `more_itertools`. The function I'm having issues with is [`first_true`](https://more-itertools.readthedocs.io/en/stable/_modules/more_itertools/recipes.html#first_true), which is defined as 

```python
def first_true(iterable, default=False, pred=None): ...
```

This means that the return type would be either `Union[T, bool]` or `Union[T, U]` when there's an explicit default.

The problem is that in the case of an implicit default, the pattern

```python
element = find_true(elements, pred=....)
if element:
  # do something with the element
```
would not work as inside the if, `element` could still be `True`.

What I would like is to signal that the return type is either `T` or the value `False`, is there any idiom to do that?

Note that the same is true for builtin functions like `next`. See
https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L862

ps: I know this would be solved if the API changed to have `default=None` instead.

**Comment by JelleZijlstra** [comment]
That's not currently supported, but the mypy team is planning to add support for a feature like this ("final types") soon.

**Comment by srittau** [comment]
I think the question has been answered.

**Comment by sk-** [comment]
@srittau It would be great if you could add a link to the tracking issue for "the mypy team is planning to add support for a feature like this ("final types") soon."

**Comment by srittau** [comment]
Dependent types (I think this is what @JelleZijlstra was referring to) are discussed in python/mypy#3062.
