### ISSUE TITLE
The argument to urllib.parse.urlunparse/urlunsplit can contain None.

### ISSUE THREAD

**Issue by Solumin** [python/typeshed#2394]
urllib.parse.urlunparse and .urlunsplit take fixed-size sequences that may use None to fill in the missing values. For example:

```
>>> parse.urlunparse(('a', 'b', 'c', 'd', 'e', 'f'))
'a://b/c;d?e#f'
>>> parse.urlunparse(('a', 'b', 'c', 'd', 'e', None))
'a://b/c;d?e'
```

However, the pyi for this library does not account for this.
This problem is also present in the 2.7 urlparse.pyi.

**Comment by JelleZijlstra** [comment]
I tried this and `None` is supported for only some elements of the sequence (for example, it errors if the first element is `None`). There's also nothing in https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlunparse that suggests that support for None is anything but an accident, and the unit tests in CPython don't test for None.

So I'm inclined to say that the support for `None` is accidental and shouldn't be included in the typeshed stub. You should signal absence of a component by passing an empty string:
```
In [13]: urllib.parse.urlunparse(['a', 'b', 'c', 'd', 'e', ''])
Out[13]: 'a://b/c;d?e'
```

**Comment by Solumin** [comment]
It looks like the last three (or last two, for `urlunsplit`) values in the `components` sequence may be `None`, *or* all six (five) values may be None.

I agree that using empty strings is greatly preferable.

I do not agree that support for None shouldn't be included in typeshed. Two reasons:
- It is already being used with None in the wild.
- typeshed's own [CONTRIBUTING.md](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#what-to-do-when-a-projects-documentation-and-implementation-disagree) says that if the documentation does not match the implementation, then the pyi should match the implementation and the documentation updated.

(I don't dispute that support for None may be accidental.)

I think a good solution -- if we are to support None, at least -- would be to add:
`urlunparse(components: Tuple[None, None, None, None, None, None]) -> None`
and modify the existing signature to:
`urlunparse(components: Tuple[AnyStr, AnyStr, AnyStr, Optional[AnyStr], Optional[AnyStr], Optional[AnyStr]) -> AnyStr`. (Or perhaps the first signature should be `urlunparse(components: Sequence[None]) -> None` for simplicity's sake?)

**Comment by Solumin** [comment]
I've reflected on this since filing the bug and I agree with Jelle now. Disallowing None (in the type stubs, anyway) greatly simplifies the type hint for it.

**Comment by JelleZijlstra** [comment]
The current urlunparse and urlunsplit stubs allow None for all fields, so this can be closed.
