### ISSUE TITLE
`mode: unicode` should be `mode: Text` (stdlib/2/_io.pyi)

### ISSUE THREAD

**Issue by Solumin** [python/typeshed#2397]
https://github.com/python/typeshed/blob/b209a649a06d3f3ba38f0989a1b3eb5e7d8c8212/stdlib/2/_io.pyi#L178

The `mode` argument to `open()` is annotated as `mode: unicode`, even though other arguments to the method are `Text`. Unless there's a particularly good reason to make `mode` unicode-only, `Text` is a more correct annotation.

**Comment by JelleZijlstra** [comment]
They are aliases in Python 2 code, so it doesn't really matter. You can submit a PR to fix it if you feel strongly about it.

**Comment by Solumin** [comment]
Cool -- just wanted to make sure I wasn't missing anything. I'll send a PR.
