### ISSUE TITLE
typeshed/third_party/2and3/werkzeug/exceptions - call to untyped functions in typed context

### ISSUE THREAD

**Issue by kornicameister** [python/typeshed#2400]
Hello there,

Without further ado, I've already reported this issue here -> https://github.com/python/mypy/issues/5502. However one of the maintainers noted that it might be related to some missing types on `__init__`. 

Let me know if you need some more details. I figured link to `mypy` issue might be sufficient.

BTW. Shouldn't the `code` by typed as `int` as well as the description typed as `str` ?

**Comment by JelleZijlstra** [comment]
I'm guessing you're referring to https://github.com/python/typeshed/blob/master/third_party/2and3/werkzeug/exceptions.pyi#L7.

It should be easy to add some more types there; PRs are welcome!

**Comment by kornicameister** [comment]
@JelleZijlstra I've done my best in the PR, in fact it sounded as easy fix, but my journey with typing in Python just starts, so there is some room for error ;-).

Anyway, will appreciate review.
