### ISSUE TITLE
unittest.TestSuite _tests attribute has no stub

### ISSUE THREAD

**Issue by lbenezriravin** [python/typeshed#2410]
Right now, the only way to access a TestSuite's tests without accessing this attribute is to iterate over the TestSuite and essentially re-create the list. This is clearly inefficient and, I believe, provides sufficient motivation to access the protected attribute without being hounded by false-positives from mypy. May I open a PR adding that stub?

Thanks for your work here!

**Comment by srittau** [comment]
I am honestly not convinced for the need to access this undocumented, private attribute. While I agree that direct access to the tests would be better (that is a matter for the unittest maintainers, though), with the typical size of test suites, recreating the list should not matter significantly.

**Comment by lbenezriravin** [comment]
Thanks for your response. While I think I still disagree (I really don't like re-creating data that I already have in scope), I understand where you're coming from. For now, I'll just leave the `# type: ignore` on that line.

**Comment by voidspace** [comment]
What do you mean by "stub"? Wanting to fetch the tests out of a suite sounds like a reasonable request, so providing a method to fetch them sounds find to me. Perhaps even make suites iterable (that's without looking at the source to double check that would work)?

**Comment by srittau** [comment]
The question for typeshed is basically: Is `TestSuite._tests` considered public API? If it is, it should be included in stubs (and probably be documented in the library documentation). If it is not, we should not include it.

Having access to the tests makes sense to me, but that question is separate from typeshed.

**Comment by voidspace** [comment]
Thanks for the explanation. It is still a private attribute and wanting access to tests is a reasonable feature request but it wouldn't be done by making that attribute public.

**Comment by srittau** [comment]
Thanks!

**Comment by lbenezriravin** [comment]
Thanks for the resolution. @voidspace where would I make this request? The cpython repository?
