### ISSUE TITLE
 typeshed/stdlib/3/subprocess.pyi missing parameters new in 3.7

### ISSUE THREAD

**Issue by williamjacksn** [python/typeshed#2412]
`subprocess.run()` is missing parameters for `text` and `capture_output` added in 3.7.

The `text` parameter is also missing from `Popen.__init__()`.

**Comment by williamjacksn** [comment]
Oops, I didn't realize there was already a pull request for this: #2409.

**Comment by srittau** [comment]
Fixed in #2409.
