### ISSUE TITLE
stdlib/2and3/sqlite3 has a wrong type for `register_adapter`

### ISSUE THREAD

**Issue by WilliamHPNielsen** [python/typeshed#2429]
Currently, the `register_adapter` function is annotated like this:
https://github.com/python/typeshed/blob/19708fac61364844ae387a4a7ebef24e50d25fb8/stdlib/2and3/sqlite3/dbapi2.pyi#L102

but as far as I can see, it should include `memoryview` in that `Union`, since that is what `Binary` is (if we're on python 3);
https://github.com/python/typeshed/blob/19708fac61364844ae387a4a7ebef24e50d25fb8/stdlib/2and3/sqlite3/dbapi2.pyi#L24-L27

My usecase is that I have a small adapter for `numpy` arrays:
```python
def _adapt_array(arr: ndarray) -> sqlite3.Binary:
    out = io.BytesIO()
    np.save(out, arr)
    out.seek(0)
    return sqlite3.Binary(out.read())
```
that is then, according to the `Union` not containing `memoryview`, *not* allowed to be registered like this: 
```python
sqlite3.register_adapter(np.ndarray, _adapt_array)
```

**Comment by srittau** [comment]
According to the [sqlite documentation](), `register_adapter()` is not allowed to return a `memoryview`:

> `sqlite3.register_adapter(type, callable)`
> Registers a callable to convert the custom Python type type into one of SQLite’s supported types. The callable callable accepts as single parameter the Python value, and must return a value of the following types: int, float, str or bytes.

@ghaering as Python's sqlite3 maintainer.

**Comment by JelleZijlstra** [comment]
Now the adapter is allowed to return `str | ReadableBuffer | int | float | None`, which includes `memoryview`.

**Comment by jenshnielsen** [comment]
With mypy 1.11.0 I have started seeing this failing again with 
```
/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/qcodes/dataset/sqlite/database.py:164:48: error: Argument 2 to "register_adapter" has incompatible type "Callable[[complex | complexfloating[Any, Any]], memoryview]"; expected "Callable[[object], str | Buffer | int | float | None]"  [arg-type]
```
