### ISSUE TITLE
SpooledTemporaryFile is a class, not a function

### ISSUE THREAD

**Issue by ruuda** [python/typeshed#2431]
`tempfile.SpooledTemporaryFile` [currently has a stub as a function](https://github.com/python/typeshed/blob/dc27768401b09e22bcd9756ee8639eae06f55bab/stdlib/3/tempfile.pyi#L29), but [it is a class](https://github.com/python/cpython/blob/f9925d86c9d7a44b612576131cd5b84cfee36c4e/Lib/tempfile.py#L630).

See also https://github.com/python/mypy/issues/5586.

**Comment by srittau** [comment]
@ruuda Would you care to create a pull request?

**Comment by ruuda** [comment]
Done in #2452.
