### ISSUE TITLE
asyncio.async not found in Python < 3.7

### ISSUE THREAD

**Issue by matthchr** [python/typeshed#2434]
It looks like this issue was introduced in #2296

I see this problem in both Python 3.4 and 3.5.

The below snippet produces the error `Module has no attribute "async"` with mypy version `0.620` but is fine with `0.610`, presumably because between those two releases the version of `typeshed` bundled with mypy was updated.
```
import asyncio
from typing import (
    Generator
)

@asyncio.coroutine
def foo(a: int) -> Generator[None, None, int]:
    yield from asyncio.sleep(1)
    return a

def test() -> None:
    asyncio.async(foo(7))
```

It seems like `async = ensure_future` should be left but under a guard like `if sys.version_info < (3, 7):`?

**Comment by srittau** [comment]
As mentioned in #2435 there is unfortunately nothing that can be done in typeshed. The code above will also fail when run under Python 3.7.

**Comment by matthchr** [comment]
> The code above will also fail when run under Python 3.7.

I understand that... but not everybody is using Python 3.7 and typeshed generally seems to supports older Python versions by way of version guards using `version_info`. As far as I can tell typeshed aims to express the surface area of Python for more than just the latest version.

With that said, I guess the only solution is to pin to mypy 0.610 (which bundled the older version of typeshd which still has `asyncio.async`) until such a time as we can stop targeting Python <3.4.4.
