### ISSUE TITLE
External vs internal type stubs

### ISSUE THREAD

**Issue by bbc2** [python/typeshed#2438]
In `CONTRIBUTING.md`, I can read the following about asking maintainers for permission before submitting stubs here:

> This gives them the opportunity to consider adopting type hints directly in their codebase (which you should prefer to external type stubs).

As the developer of an application and user of Mypy, I always use `--ignore-missing-imports` because otherwise I get plenty of errors "Cannot find module named ..." because of dependencies.  As a result, unless there are stubs in typeshed or in my project, I don't get the benefits of Mypy for those dependencies.

If such a dependency were to adopt type hints, instead of them being in typeshed, how would that help in this scenario?  My impression is that they would still be ignored because of the `--ignore-missing-imports` option.  I'm thus curious about what "adopting type hints" means and how that would help the developer of an application with several other libraries that need to be "ignored".

**Comment by JelleZijlstra** [comment]
If they use a `py.typed` file, then mypy will use the inline type hints according to PEP 561.

**Comment by bbc2** [comment]
Ah, I didn't know.  This is awesome, thanks!
