### ISSUE TITLE
`fold` arguments for datetime/time added in Python 3.6 is not supported

### ISSUE THREAD

**Issue by kitsuyui** [python/typeshed#2448]
[PEP 495](https://www.python.org/dev/peps/pep-0495/) had added the new fold attribute.

Accordingly also `datetime.datetime()` and `datetime.time()` had started to support fold arguments from 3.6.
But its type hint is not updated except `replace()`.

## Reproducible

```python3
from datetime import time
time(hour=0, minute=0, second=0, fold=0)  # error: Unexpected keyword argument "fold" for "time"
```

## Reference

- https://www.python.org/dev/peps/pep-0495/

- https://docs.python.org/3/whatsnew/3.6.html#pep-495-local-time-disambiguation

- https://docs.python.org/3.5/library/datetime.html#datetime.datetime
- https://docs.python.org/3.6/library/datetime.html#datetime.datetime

- https://docs.python.org/3.5/library/datetime.html#datetime.time
- https://docs.python.org/3.6/library/datetime.html#datetime.time

**Comment by srittau** [comment]
Fixed in #2449
