### ISSUE TITLE
Unsupported operand types for &

### ISSUE THREAD

**Issue by twk** [python/typeshed#2454]
Mypy fails with error: `Unsupported operand types for & ("KeysView[Wrapper]" and "List[Wrapper]")` when I try to do this:

```
class Wrapper:
    def __init__(self, val):
        # type: (int) -> None
        self.val = val

def demo():
    # type: () -> None
    a = {Wrapper(1): 1, Wrapper(2): 2}
    b = [Wrapper(1)]

    a.keys() & b
```

I filed this on the mypy project but they suggested this is actually a typeshed issue: https://github.com/python/mypy/issues/5600

**Comment by srittau** [comment]
It seems that `typing.KeysView` inherits from `AbstractSet`, which only accepts other `AbstractSet`s as argument for `__and__` (and `__or__`, `__xor__`). These methods should probably be overridden in `KeysView` and accept more types.
