### ISSUE TITLE
Investigate CI failures

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2456]
Lately, some PRs are failing their CI checks with an error that seems unrelated to the PR, see for example #2455 and #2433 and #2436 (although that one also has genuine failures). It looks as if this was a problem with the wrong Python version (2.7 instead of 3.6) to be installed in the path. The only commonality I see between the three pull requests is that all three were submitted by Google employees, but that seems to be incidental.

**Comment by srittau** [comment]
Also #2439, which is not by a Google employee.

**Comment by ethanhs** [comment]
@msullivan this is likely from https://github.com/python/mypy/pull/5578. I will work out what is wrong and fix it tomorrow. Sorry all for the interruption.

**Comment by srittau** [comment]
The problematic change has been rolled back in python/mypy#5615, PRs work again.
