### ISSUE TITLE
ConfigParser.read type signature incorrect

### ISSUE THREAD

**Issue by scolby33** [python/typeshed#2476]
In typeshed, the `RawConfigParser.read` method is defined as
https://github.com/python/typeshed/blob/ea2122741faa0df576094584f869e9517a1115ce/stdlib/3/configparser.pyi#L93-L94

And, earlier,
https://github.com/python/typeshed/blob/ea2122741faa0df576094584f869e9517a1115ce/stdlib/3/configparser.pyi#L22

However, reading the [cpython source of configparser](https://github.com/python/cpython/blob/f6c8007a29b95b3ea3ca687a9b4924769a696328/Lib/configparser.py#L691) reveals that `bytes` are also accepted:
```python
if isinstance(filenames, (str, bytes, os.PathLike)):
```

Is it possible to add this to the annotation?

**Comment by JelleZijlstra** [comment]
Yes, feel free to submit a PR!
