### ISSUE TITLE
ipaddress module _BaseNetwork missing hostmask

### ISSUE THREAD

**Issue by spdkils** [python/typeshed#2481]
It seems that there is a missing property in the stdlib for ip address. I was just typing some of my code, and it was missing the hostmask.

I'm new to this, so I'm not sure if this is the correct resolution, but it fixed my type error.

```Python
class _BaseNetwork
  @property
  def hostmask(self) -> _A: ...
```

**Comment by JelleZijlstra** [comment]
Thanks for the report! Would you mind submitting a PR?

**Comment by spdkils** [comment]
https://github.com/python/typeshed/pull/2482 I think that will do it, about as simple as it gets.
