### ISSUE TITLE
A variable annotated with 'date' is not compatible with a value of type 'datetime'.

### ISSUE THREAD

**Issue by mvaled** [python/typeshed#2487]
`datetime` is a subclass of `date`.  In the stubs of 'datetime' there's the following TODO:

```python
class datetime:
    # TODO: Is a subclass of date, but this would make some types incompatible.
```
Is there any record of the incompatibilities?  Should we keep an issue open to address this TODO eventually?

**Comment by mvaled** [comment]
The following program is rejected by mypy:

```python
from datetime import date, datetime

class Date: ...
class Datetime(Date): ...

now: date = datetime.now()
rightnow: Date = Datetime()

assert isinstance(now, date)
```

```
$ mypy bug.py 
bug.py:6: error: Incompatible types in assignment (expression has type "datetime", variable has type "date")
```

**Comment by JelleZijlstra** [comment]
There's probably some incompatible methods. Try modifying the stub to make datetime inherit from date and run `tests/mypy_test.py`.

We could fix this by just `# type: ignore`ing the lines  with any incompatible methods.

**Comment by mvaled** [comment]
@JelleZijlstra I created a PR in https://github.com/python/typeshed/pull/2488
