### ISSUE TITLE
SplitResultBytes's computed properties should be bytes, not str

### ISSUE THREAD

**Issue by wiml** [python/typeshed#2501]
The type of `urllib.parse.urlsplit(b'blah...').hostname` is bytes, but typeshed currently indicates it as str.

Presumably this declaration of `_NetlocResultMixinBytes` should derive from `_NetlocResultMixinBase[bytes]`, not `_NetlocResultMixinBase[str]`:  https://github.com/python/typeshed/blob/bc3f9fe1d3c43b00c04cedb23e0eeebc9e1734b6/stdlib/3/urllib/parse.pyi#L37

**Comment by JelleZijlstra** [comment]
Looks like it, would you mind submitting a PR to fix this?

**Comment by srittau** [comment]
Fixed in #2503.
