### ISSUE TITLE
API's and pathlib.Path

### ISSUE THREAD

**Issue by belm0** [python/typeshed#2512]
e.g. logging.FileHandler() happily accepts pathlib.Path.  Should typing be loosened?

```python
logger = logging.getLogger(__name__)
log_dir = pathlib.Path(__file__).parents[2] / "log"
handler = logging.FileHandler(log_dir / "arbitrator.log")
```

> error: Argument 1 to "FileHandler" has incompatible type "Path"; expected "str"

**Comment by JelleZijlstra** [comment]
This particular one was fixed recently in #2500. If you find other functions that should accept PathLike but don't, feel free to accept a PR or an issue. We unfortunately don't have a good way to systematically find all of them.
