### ISSUE TITLE
Incorrect types are used to describe google.protobuf enums

### ISSUE THREAD

**Issue by vmagamedov** [python/typeshed#2521]
Let's take `google.protobuf.descriptor_pb2.FieldDescriptorProto` as an example.

In Python `FieldDescriptorProto.TYPE_DOUBLE` is instance of `int`
In mypy `FieldDescriptorProto.TYPE_DOUBLE` is instance of `FieldDescriptorProto.Type`

In Python `FieldDescriptorProto.Type` is instance of `EnumTypeWrapper`
In mypy `FieldDescriptorProto.Type` is subclass of `int` with additional methods

In Python `FieldDescriptorProto.Type.keys()` is of type `List[str]`
In mypy `FieldDescriptorProto.Type.keys()` is of type `List[bytes]`

In Python `EnumTypeWrapper.items` is an `instancemethod`
In mypy `EnumTypeWrapper.items` is a `classmethod`

In mypy this code works:
```python
from google.protobuf.descriptor_pb2 import FieldDescriptorProto
print(FieldDescriptorProto.TYPE_DOUBLE.values())
```
In Python it fails:
```python
Traceback (most recent call last):
  File "sandbox.py", line 5, in <module>
    print(FieldDescriptorProto.TYPE_DOUBLE.values())
AttributeError: 'int' object has no attribute 'values'
```
Currently this stub looks like this:
```python
class FieldDescriptorProto(Message):
    class Type(int):
        @classmethod
        def Name(cls, number: int) -> bytes: ...

        @classmethod
        def Value(cls, name: bytes) -> FieldDescriptorProto.Type: ...

        @classmethod
        def keys(cls) -> List[bytes]: ...

        @classmethod
        def values(cls) -> List[FieldDescriptorProto.Type]: ...

        @classmethod
        def items(cls) -> List[Tuple[bytes, FieldDescriptorProto.Type]]: ...
    TYPE_DOUBLE: Type
    ...
```
I think it is possible to change it into this:
```python
class FieldDescriptorProto(Message):
    FieldDescriptorProto_Type = typing.NewType('FieldDescriptorProto_Type', int)
    Type: EnumTypeWrapper[FieldDescriptorProto_Type]
    TYPE_DOUBLE: FieldDescriptorProto_Type
    ...
```
where `google.protobuf.internal.enum_type_wrapper.EnumTypeWrapper` looks like this:
```python
class EnumTypeWrapper(Generic[T]):
    def Name(self, number: T) -> str: ...
    def Value(self, name: str) -> T: ...
    def keys(self) -> List[str]: ...
    def values(self) -> List[T]: ...
    def items(self) -> List[Tuple[str, T]]: ...
```
The only problem I see is how to generate unique type name for enum values, in the example above I'm using concatenation of message name and enum name: `FieldDescriptorProto_Type`.

Is it ok to create PR with this fix?

**Comment by JelleZijlstra** [comment]
This looks reasonable. I would put the NewType in the global scope instead of within the class and give it a `_`-prefixed name to ensure that it is private.

**Comment by vmagamedov** [comment]
Great, so I'm going to submit PR soon.

**Comment by nipunn1313** [comment]
hi - mypy-protobuf recently made updates which fixes this issue - I can run mypy-protobuf on the google `google.protobuf` protos and try to commit them back into typeshed.

That'll make them more correct - though it might be a backward compatibility painpoint for those using them.
