### ISSUE TITLE
The `listen` method of the class `socket` is wrong

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#2526]
According to the (docs)[https://docs.python.org/3/library/socket.html] the `backlog` parameter is option for python 3.5+, however the types indicate that it is required.

**Comment by srittau** [comment]
Would you care to submit a pull request?

**Comment by PrajwalM2212** [comment]
@srittau  I would like to work on this.

**Comment by srittau** [comment]
Please go ahead, everybody is free to submit pull requests!
