### ISSUE TITLE
Rounded Decimal getting flagged when it shouldn't when using Mypy

### ISSUE THREAD

**Issue by YPCrumble** [python/typeshed#2528]
Thanks for maintaining typeshed! I'm hoping I'm able to give back to Python so if I could help with a PR to fix this issue please let me know?

I [reported this issue in Mypy](https://github.com/python/mypy/issues/5797) and was told that this would be the proper place for it:

Thank you for building mypy! I have a simple function that returns a rounded `Decimal` that I believe is making Mypy fail when it shouldn't. If I remove the `round` from my code and simply return a `Decimal` object it works as expected.

* Are you reporting a bug, or opening a feature request?
Reporting a bug.
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.

```
import decimal

cents = 1001


def cents_to_dollars(integer: int) -> decimal.Decimal:
    return round(decimal.Decimal(cents) / 100, 2)


print("The type is: " + str(type(cents_to_dollars(cents))))
```

* What is the actual behavior/output?
    error: Incompatible return value type (got "int", expected "Decimal")
* What is the behavior/output you expect?
I would expect no issues with this code.

* What are the versions of mypy and Python you are using?
mypy 0.641, python 3.7.0

* What are the mypy flags you are using? (For example --strict-optional)
None

**Comment by srittau** [comment]
Thank you for the report! It seems that `Decimal.__round__()` is missing overloads for when `ndigits` is provided, similar to the overloads in `builtins.pyi`:

https://github.com/python/typeshed/blob/703c03e4b094b6bcc01a6d2d7c08860a9c8dd0ee/stdlib/3/builtins.pyi#L898-L903

A pull request fixing this would be very welcome.

**Comment by utkarsh2102** [comment]
@srittau, not something like this in `decimal.pyi`?
https://github.com/python/typeshed/blob/703c03e4b094b6bcc01a6d2d7c08860a9c8dd0ee/stdlib/3/builtins.pyi#L190-L195

**Comment by srittau** [comment]
@utkarsh2102 Yes, except the last case returns `Decimal` instead of `float`.

**Comment by utkarsh2102** [comment]
Okay, will send a fix.
