### ISSUE TITLE
List of third-party stub distributions

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2531]
This came up in #2495. It would possibly be useful to have a list of third-party stub distributions in typeshed, at least as long as we don't implement #2491. I see two possibilities: Have a list in the main repository and update it via pull requests or enable the Wiki in this repository and create a Wiki page for anyone to edit.

**Comment by hauntsaninja** [comment]
Closing, since no progress has been made here and we're looking to implement #2491 soon-ish
