### ISSUE TITLE
itertools.product with no arguments support

### ISSUE THREAD

**Issue by lycantropos** [python/typeshed#2561]
It is [documented](https://docs.python.org/3/library/itertools.html#itertools.product) that `itertools.product` call with no arguments works fine and it is:

**test.py**
```python
from itertools import product

print(next(product()))  # ()
```

tested on *Python 3.3+* on *Linux* and on *Python 3.0+* on *Windows*, but running `mypy` raises error
```
> mypy test.py
test.py:3: error: All overload variants of "product" require at least one argument
test.py:3: note: Possible overload variants:
test.py:3: note:     def [_T1] product(iter1: Iterable[_T1]) -> Iterator[Tuple[_T1]]
test.py:3: note:     def [_T1, _T2] product(iter1: Iterable[_T1], iter2: Iterable[_T2]) -> Iterator[Tuple[_T1, _T2]]
test.py:3: note:     <6 more similar overloads not shown, out of 8 total overloads>
```
it happens because there is no support for this kind of call in `typeshed`, can be fixed by specifying that `repeat` parameter (added in [this PR](https://github.com/python/typeshed/pull/1410)) has default argument like
```python
@overload
def product(*iterables: Iterable[Any], repeat: int = ...) -> Iterator[Tuple[Any, ...]]: ...
```

**Comment by srittau** [comment]
Please note that PR #1410 adds that argument to the Python 2 version of `itertools`. The Python 3 version is missing an overload, though:

https://github.com/python/typeshed/blob/07bc1c99974d16ff99039a9989a8e0aa64700a6a/stdlib/3/itertools.pyi#L62-L99

Something like (untested):

```python
@overload
def product(*, repeat: int = ...) -> Iterable[Tuple[()]]: ...

**Comment by srittau** [comment]
I forgot to mention that PRs are welcome!
