### ISSUE TITLE
Reorganize bug labels

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2562]
I have recently gone through old bug reports and tried to triage them. In the process I added a few labels. Here are the labels as described in [CONTRIBUTING.md](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md):

* **bug**: It's a bug in a stub.
* **bytes-unicode**: It's related to bytes vs. unicode, usually Python 2.
* **feature**: It's a new typeshed feature.
* **priority-high**: This issue is more important than most.
* **priority-low**: This issue is less important than most.
* **priority-normal**: This issue has average priority.
* **question**: Not really an issue, but a question on how to do something.
* **size-large**: An issue of high complexity or affecting many files.
* **size-medium**: An issue of average complexity.
* **size-small**: An issue that will take only little effort to fix.

I have added a few labels:

* **missing-annotation**: Annotations or sub-modules are missing from an existing package or module.
* **needs-discussion**: A project discussion topic.
* **permission-pending**: Waiting for permission from upstream maintainers.

I would suggest to restructure the labels a bit to help with triaging:

* [x] Rename **bug** to **type-false-positive** and adapt description.
* [x] Add a **type-false-negative** label. I expect that many of these are non-actionable, though.
* [x] Rename **missing-annotation** to **type-missing-annotation**.
* [x] Rename **feature** to **type-stubs-request** (or something better) and adapt description to "Request to include stubs for a third-party package in typeshed."
* [x] Rename **bytes-unicode** to **topic-bytes-unicode**. We could then add further **topic-** labels when we need them and have them grouped. Alternatively, we could remove this label. It has been used historically for only 5 issues and I feel that my now the bytes/string/unicode problematic is well understood and "solved" and does not need to be tagged separately.
* [x] Rename **needs-discussion** to **project-discussion** to clarify its use.

* [ ] I would also suggest to remove the list of stubs from `CONTRIBUTING.md` and add the descriptions to the individual labels so that you find the information is where you need it and we prevent outdated information and redundancies.

**Comment by JelleZijlstra** [comment]
Thanks for doing this! I especially like renaming the "feature" label to the name you propose—the new name communicates intent much more clearly.

**Comment by srittau** [comment]
One more suggestion: Remove priority-normal and priority-low. The priorities have been used a total of 6 times in the past. While I think there is value in retaining priority-high, I don't think distinguishing between "normal" and "low" makes much sense for typeshed. Everything not tagged with "high" is priority normal by default.

**Comment by srittau** [comment]
I have added another label `type-improvement` and reshuffled the colors a bit to be thematically consistent.

**Comment by srittau** [comment]
I have now implemented the changes suggested above.
