### ISSUE TITLE
use monkeytype to generate types faster?

### ISSUE THREAD

**Issue by devdoomari3** [python/typeshed#2570]
instagram made https://github.com/Instagram/MonkeyType for faster type-annotation.

This basically works by collecting types at runtime, and applying the collected types to the codebase.

Wouldn't we save a lot of effort by using this? (preferrably by running libraries' test suites with monkeytype)

**Comment by srittau** [comment]
MonkeyType's README explicitly states:

> With MonkeyType, it's very easy to add annotations that reflect the concrete types you use at runtime, but those annotations may not always match the full intended capability of the functions. [...] MonkeyType's annotations are an informative first draft, to be checked and corrected by a developer.

Another problem is that it works well for applications, where most code paths are executed, while you will need to write a specially crafted program that uses all features in a library to produce useful annotations. This is probably more work than manually crafting stubs.

**Comment by srittau** [comment]
It could work for a first version when the library in question has extensive unit test coverage, though.

**Comment by hauntsaninja** [comment]
Closing, since there isn't anything actionable.
We could maybe maintain a list of useful tools for developing stubs somewhere.
