### ISSUE TITLE
Discrepancy in inspect.unwrap()'s stop argument

### ISSUE THREAD

**Issue by edgchen1** [python/typeshed#2574]
[inspect.unwrap()](https://docs.python.org/3/library/inspect.html#inspect.unwrap) has a stop argument with a default value of None. However, mypy indicates that it is required:

```python
import inspect
def foo(): pass
unwrapped_foo = inspect.unwrap(foo)
```

mypy output: `error: Missing named argument "stop" for "unwrap"`

**Comment by srittau** [comment]
Thank you for the report. Would you care to submit a pull request?

**Comment by edgchen1** [comment]
Sure, submitted pull request #2583.
