### ISSUE TITLE
'gzip.GzipFile' appears to be missing 'IO[...]'

### ISSUE THREAD

**Issue by software-opal** [python/typeshed#2580]
I'm not sure if this is a bug in MyPy or the typeshed, however tryngi to use a `gzip.GzipFile` where a file should be produces an error:

test.py
```
import gzip, typing
def my_test_writer(file: typing.IO[bytes]) : ...
my_test_writer(gzip.GzipFile("rb"))
```
Running `mypy test.py` (I ran from `/tmp` to ensure no config files were causing problems) gives:
```
test.py:4: error: Argument 1 to "my_test_writer" has incompatible type "GzipFile"; expected "IO[bytes]"
```

**Comment by srittau** [comment]
Unfortunately, the IO classes are not in the best shape in typeshed. Our long-term plan is to change arguments requiring IO classes to use protocols. I recommend to do the same in custom code-bases, i.e. write protocols for functions and classes that take IO classes as arguments. See python/typing#564 for more information.

**Comment by micimize** [comment]
A comment in this related [stackoverflow post](https://stackoverflow.com/questions/58394410/why-does-mypy-complain-about-textiowrapper-receiving-gzipfile-as-argument-1) references #4146 as either solving this or making it solvable.

Temporary workaround is to just `cast`:
```python
    with gzip.open(input_file, "rb") as unzipped_file:
      return pickle.load(cast(IO[bytes], unzipped_file))
```

**Comment by srittau** [comment]
Closing this here. I suggest using protocols in your own code. If `GzipFile` isn't accepted somewhere in the standard library, where it works, please file a separate bug report, or even better, submit a PR that changes the function in question to use protocols. If someone wants to experiment with deriving `GzipFile` from `IO`, I'd be open to review such a PR, but no need to keep the issue open.
