### ISSUE TITLE
deque maxlen needs type Union 

### ISSUE THREAD

**Issue by MatthewPScott81** [python/typeshed#2581]
maxlen can accept None type as well as int

Line in source code:
https://github.com/python/typeshed/blob/113eda289f54d12222e39e3f2dbfc21aab0d3c84/stdlib/3/collections/__init__.pyi#L193

Reference:
https://docs.python.org/3.7/library/collections.html#collections.deque.maxlen

**Comment by srittau** [comment]
I assume you are referring to the `maxlen` argument for `deque.__init__()`? This should indeed be marked as `Optional`. Pull requests are welcome!

**Comment by MatthewPScott81** [comment]
I apologize for the lack of clarity.  I was indeed referring to the the `maxlen` argument for `deque.__init__()`.  It appears the argument should be `Optional` and accept either an int or None, if I'm not mistaken.

I'd be glad to put in a pull request on it.
