### ISSUE TITLE
Python 3: unittest.TestCase.assertRaises() accepts BaseException, not just Exception

### ISSUE THREAD

**Issue by ppentchev** [python/typeshed#2593]
Hi,

Thanks *a lot* for maintaining this repository of type stubs!

Now, at least in Debian testing's Python 3.6.7 and 3.7.1, Ubuntu 16.04 LTS's Python 3.5.2, and Ubuntu 14.04 LTS's Python 3.4.2 (I could look at earlier versions if you'd like, if only to determine how far back any fixes should go), the definition of the _E type in stdlib/3/unittest/__init__.pyi is slightly wrong: assertRaises() and assertRaisesRegex() accept BaseException (e.g. SystemExit), not just Exception.  For Python 3.5, 3.6, and 3.7 this may be verified directly by looking at the respective unittest/case.py file: the _AssertRaisesContext class has a `_base_type = BaseException` definition.  For Python 3.4 it is not that obvious, but there are no checks at all there, so anything passed as an exception would be accepted.

This may be easily verified by the attached program (after renaming it to have a py extension)
[system_exit.txt](https://github.com/python/typeshed/files/2563025/system_exit.txt)
 that should pass flake8 and pylint3 and should run on Python 3.4, 3.5, 3.6, and 3.7 - both tests will pass.  `mypy --strict --py2` will also like it, since the definition in stdlib/2/unittest.pyi is based on BaseException, but `mypy --strict` will complain that SystemExit is not an acceptable type.

Thanks in advance for your time, and keep up the great work!

G'luck,
Peter

**Comment by srittau** [comment]
Thank you for the report and the analysis. Would you care to submit a pull request?
