### ISSUE TITLE
Style guide: one argument per line with long lines?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2598]
Currently our style guide prefers conciseness over multiple lines. On the other hand, black's pyi mode formats functions and methods that don't fit in 130 lines with one argument per line. I think we should be consistent here, one way or the other.

Personally, I prefer black's style for functions with many arguments for two reasons:

* With many arguments, putting multiple arguments on one line is quite hard to read and it is easy to make mistakes.
* Better diffs when arguments are changed.

(@ambv)

**Comment by srittau** [comment]
Also pinging contributors to the [type stub PEP](https://github.com/srittau/type-stub-pep): @JelleZijlstra @rchen152 @Solumin

**Comment by JelleZijlstra** [comment]
I agree; in general I prefer we just go with Black's style (except perhaps longer line length).

**Comment by Solumin** [comment]
I'm in favor of this.

I've found functions with lots of arguments also tend to have more complicated types for those args. Trying to grok `some_argument: List[six.string_types, Dict[six.string_types, LocalClass]]` is awful when it's buried in a long line of arguments. One argument per line is much easier to read.
