### ISSUE TITLE
Change unicode to Text in Python 2 stubs

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2609]
Per discussion in python/typing#208 and srittau/type-stub-pep#19, we should change most occurences of `unicode` in Python 2 and 2and3 stubs to `Text`. Type checkers are free to treat `unicode` as `Union[str, unicode]` or as just `unicode` and particularly pytype does the latter. A quick grep showed 425 lines containing the word `unicode` in those stubs, although there are many false positives.

**Comment by hauntsaninja** [comment]
Closing since the typing repo issue has been closed.
