### ISSUE TITLE
zlib.crc32() reports that it's first parameter is incompatible with array.array()

### ISSUE THREAD

**Issue by xNinjaKittyx** [python/typeshed#2611]
From MyPy
`error: Argument 1 to "crc32" has incompatible type "array[Any]"; expected "bytes"`

This function does work with array.array() objects, so I assume its a bug?

**Comment by lladhibhutall** [comment]
@srittau as a type for buffer protocol is not available, should I just put `array.array[Any]`? Solves the problem for now.

**Comment by JelleZijlstra** [comment]
That should be fine yes. Ideally the `Any` should be something more specific.
