### ISSUE TITLE
Incorrect type for xml.etree.ElementTree.iselement() argument?

### ISSUE THREAD

**Issue by mthuurne** [python/typeshed#2629]
The `xml.etree.ElementTree.iselement` function is stubbed as follows:
```py
def iselement(element: Element) -> bool: ...
```
This is the implementation of  `iselement()`: (from Python 3.6.5)
```py
def iselement(element):
    """Return True if *element* appears to be an Element."""
    return hasattr(element, 'tag')
```
If only `Element` instances can be passed, the function would always return `True`, as `Element` contains a variable named `tag`. I think it would make more sense for the argument to be of type `object`. 

That said, I wonder what the purpose of `iselement()` is: I assumed it would perform a kind of protocol check that decides whether a passed object is suitable as an element in an `ElementTree`, but `Element._assert_is_element()` will only accept `Element` instances, so duck typing is not supported here anyway. However, even if `iselement()` would only return `True` for `Element` instances, it would still make sense if you could pass other objects as well and get `False` returned.

**Comment by srittau** [comment]
I am not sure how it is used in practice. Maybe it's to be used to distinguish between `Element` and other elementtree objects such as `ElementTree`? Anyway, I am fine with it accepting `object`.
