### ISSUE TITLE
re.findall should support returned lists of tuples

### ISSUE THREAD

**Issue by galsondor** [python/typeshed#263]
In the following code, line 8 fails type checking.  The current `findall()` stubs in `stdlib/*/typing.pyi` and `stdlib/*/re.pyi`define the return type of the regular expression `findall()` functions as `List[AnyStr]`; however, `List[Tuple[AnyStr, AnyStr]]` is also a valid return type.  The stubs should be corrected to allow both types.  If the current maturity of mypy does not allow this, suggest changing the return types to `List[Any]` as a temporary work around.  I have made these changes in my fork and can provide a pull request.

```
1. import re
2. from typing import List, Tuple, TypeVar, AnyStr
3. 
4. re1 = re.compile(r'(\d), *')
5. li1 = re.findall(re1, '1, 2, 3, 4')  # type: List[str]             <= Okay
6. print('{!s} -> {!r}\n '.format(re1, li1))
7. re2 = re.compile(r'(\d)(, *)?')
8. li2 = re2.findall('1|2|3|4')         # type: List[Tuple[str, str]] <= Error
9. print('{!s} -> {!r}\n '.format(re2, li2))
```

**Comment by gvanrossum** [comment]
Ow, that's going to be painful. We'd have to make the return type `List[Union[str, Tuple[str, ...]]]` (or maybe using AnyStr) but then all code will be required to do an isinstance() check even though almost always the regex is a constant so the programmer *knows* the type.

We may have to special-case this in mypy similar to the way we do for % and .format().

Or maybe we'll have to make the return type `List[Any]` which also is far from ideal.

Any suggestions @JukkaL?

**Comment by JukkaL** [comment]
List[Any] is the only immediately available option that isn't painful. In
the future we can special case this and try to infer a more precise type
when possible. This would be similar to how we handle open().

**Comment by gvanrossum** [comment]
Can someone submit a typeshed PR that changes the return to List[Any]?

**Comment by galsondor** [comment]
https://github.com/python/typeshed/pull/269

**Comment by gvanrossum** [comment]
Let's keep this issue open until we've got a real solution.

**Comment by gvanrossum** [comment]
(For the real solution we should probably have a separate issue in mypy or even typing, depending on the solution chosen.)

**Comment by JelleZijlstra** [comment]
Should this be handled with a mypy plugin now?

**Comment by gvanrossum** [comment]
That would still be tricky if the regex is a variable -- plugins currently can't see values unless they are literals passed in to the same call. So I think this is not a great use case for a plugin. Maybe `re.findall(r'(\d)(, *)?', ...)` could be analyzed, but the code from the example would require some plugin gymnastics (e.g. returning a different type from `re.compile()` depending on the group count).

**Comment by JelleZijlstra** [comment]
I don't think there's anything actionable here to do in typeshed, so closing. (`re.findall` is currently marked as returning `List[Any]`.)
