### ISSUE TITLE
`bytes` should implement `__new__`

### ISSUE THREAD

**Issue by mystor** [python/typeshed#2630]
This seems like a similar issue to #2091. The `bytes` type implements `__init__` but doesn't appear to provide an overload for `__new__`. This makes it harder for subclasses of `bytes` to define their own behaviour for `__new__`.

https://github.com/python/typeshed/blob/9c3978e33739cef4b5b617a226c24cb4e1ba575b/stdlib/3/builtins.pyi#L344-L355

This also appears to be the case for some of the other builtins (e.g. `str`)

https://github.com/python/typeshed/blob/9c3978e33739cef4b5b617a226c24cb4e1ba575b/stdlib/3/builtins.pyi#L267-L272

**Comment by srittau** [comment]
Could you give an example where this is a problem? `bytes` and `str` should inherit `__new__` from `object` if I am not mistaken.

**Comment by srittau** [comment]
Thanks for the explanation. Makes sense. We appreciate pull requests!

**Comment by sproshev** [comment]
`str.__new__` had been added in #1352 but then reverted

**Comment by mystor** [comment]
Figure I should add a ref to the reason it was backed out: #1464

It appears it was backed out because the addition of __new__ to `str` caused problems for classes deriving from both `str` and `Enum`, as the `str`'s __new__ would now take priority rather than the `Enum`'s. I'm guessing this is caused by some magic wrt how `str` is actually implemented within python :-/

Perhaps there needs to be a special case for these builtins to make constructing them work correctly?

**Comment by hauntsaninja** [comment]
Closed by #4555 (and thank you for git-revise!)
