### ISSUE TITLE
argparse.ArgumentParser.parse_args() overload misfire

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#2641]
I had some code calling `parse_args(args, ns)` where the type of `ns` was `Optional[Namespace`. It then deduced that the return type was also `Optional[Namespace]`. I think this is a mistake -- I don't think `parse_args()` ever returns `None`. Perhaps `_N` should be constrained by `bound='Namespace'`?

**Comment by srittau** [comment]
The [argparse documentation](https://docs.python.org/3.7/library/argparse.html#namespace) gives an explicit example of a non-`Namespace` `namespace` argument. Personally, I prefer a false negative over a false positive, especially in this case.

**Comment by gvanrossum** [comment]
OK, but can we at least do something so that mypy understands that `parse_args(args, None)` does not return `None`? Surely that's a special case worth handling. My example code is roughly
```
def parse_args_wrapper(argv: List[Text], namespace: Optional[Namespace]) -> Namespace:
    return ...parse_args(argv, namespace)
```
and this gives an error on the `return` saying that it expects `Namespace` but got an `Optional[Namespace]` -- I can only explain this by asuming that this is because `_N` is unconstrained in the second and third overloads.

Maybe adding another overload with an explicit `None` will help?

**Comment by srittau** [comment]
Explicit `None` overloads are definitely missing, but would not help your use case, as far as I can tell, since that case would not match. Best idea I have is an overload for `Optional[_N]` -> `Any`, where `Any` is really `Union[Namespace, _N]`. (Another case the `AnyOf` (python/typing#566) would be useful.)

**Comment by gvanrossum** [comment]
Hm, I'm not so sure. Here's a simple test program:
```
from argparse import ArgumentParser, Namespace
from typing import Optional

def foo(p: ArgumentParser, ns: Optional[Namespace]) -> Namespace:
    return p.parse_args(namespace=ns)
```
This currently gives
```
t.py:5: error: Incompatible return value type (got "Optional[Namespace]", expected "Namespace")
```
But when I insert
```
    @overload
    def parse_args(self, *, namespace: None) -> Namespace: ...
```
in the list of `parse_args()` overloads (before the last one), it passes without errors.

(We'd also need an extra overload for `(Optional[Sequence[_Text]], None) -> Namespace`.)

**Comment by srittau** [comment]
Huh, learned something new today. That's definitely useful and in that case just overloading `None` seems like the correct fix.

**Comment by ilevkivskyi** [comment]
Union math kicks in soon on purpose, mypy now works much better with overloads :-)
