### ISSUE TITLE
It appears that yaml.safe_load() takes bytes in addition to strings

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#2644]
I found this out by experimenting briefly. Perhaps I'm wrong and it only takes bytes as long as they're pure ASCII (i.e. 7-bit characters)? Does it also take `IO[bytes]`?

**Comment by srittau** [comment]
Looking at the source, `safe_load()` takes anything `SafeLoader` takes, which is anything `Reader` takes, which is `str`, `bytes`, or an instance with a `read(size: int) -> str` or a `read(size: int) -> bytes` method according to a comment in the `Reader` class.

**Comment by gvanrossum** [comment]
That sounds like a job for protocols...

**Comment by JelleZijlstra** [comment]
Current stub is:
```
def safe_load(stream: bytes | IO[bytes] | str | IO[str]) -> Any: ...
```

Bytes are handled, we can switch to protocols if someone sends a PR.
