### ISSUE TITLE
staticmethod defined as taking function as arg, but accepts callable in reality

### ISSUE THREAD

**Issue by anentropic** [python/typeshed#2645]
In Python 2.7 I have some code like:

```python
class MyClass(object):
    transform_value = staticmethod(str)
```

mypy complains with:
```
Argument 1 to "staticmethod" has incompatible type "Type[str]"; expected "function"
```

the code works though

so I wonder if the signature of `staticmethod` should be defined as accepting `Callable`?
(assuming a `Type` is `Callable`...)

**Comment by JelleZijlstra** [comment]
Sounds like you are right. Would you mind submitting a PR?
