### ISSUE TITLE
Incomplete stubs

### ISSUE THREAD

**Issue by srittau** [python/typeshed#2648]
When stubs for new packages are submitted, they are often incomplete. I think that's okay, we can't contributors to annotate a complete, complex package when they use only a small part of it. Nevertheless these incomplete packages have value.

But they have one problem: Correct code that previously type checked with `--ignore-missing-imports` or similar flags will now flag errors if the new stub is incomplete. Similar, new code needs to be littered with `# type: ignore`s.

I suggest to add something like this to `CONTRIBUTING`:

* There must be a stub for each sub-module.
* Incomplete or empty modules must contain `__getattr__`, with a `# incomplete` comment.
* Same for incomplete classes.
* Functions and methods must have all arguments, but they can be left unannotated.

**Comment by ilevkivskyi** [comment]
Technically even some packages can be incomplete, if one puts `__getattr__` in `__init__.py`, then mypy will assume the package has any sub-module/sub-package. This may be useful for very large packages.

**Comment by srittau** [comment]
Good to know. This should then be included as an option.
