### ISSUE TITLE
Add logging.currentframe

### ISSUE THREAD

**Issue by erichiller** [python/typeshed#2663]
Currently there is no `logging.currentframe` present in the types, but the [actual code](https://github.com/python/cpython/blob/3.7/Lib/logging/__init__.py#L153) does contain this function.

Without this mypy will return `Module has no attribute currentframe` for `logging.currentframe()`

**Comment by s-kovacevic** [comment]
I could add this, @srittau is that OK?

**Comment by srittau** [comment]
@s-kovacevic Sure, we welcome pull requests.
