### ISSUE TITLE
utime(), _extract_member() for tarfile.TarFile are absent

### ISSUE THREAD

**Issue by mkurnikov** [python/typeshed#2673]
Encountered covering pip with stubs. 

I can add PR, but I'm not sure whether they should be included in stubs, both are undocumented and second one is private.

**Comment by srittau** [comment]
That `utime()` is not documented looks like an oversight to me. I'd probably accept it as stub (with either an `# undocumented` annotation or maybe a bpo documentation bug report). @gustaebel is listed as tarfile expert in the [expert index](https://devguide.python.org/experts/) and might have an opinion on that.

**Comment by createza** [comment]
https://github.com/users/createza/emails/64247020/confirm_verification/d2ea40fed9552ea4e1e5f13f88395d277c2c19b9?utm_campaign=github-email-verification&utm_content=html&utm_medium=email&utm_source=verification-email

**Comment by rohitkg98** [comment]
looks like `utime()` has been added to the stubs. Do we want to include private methods?

**Comment by JelleZijlstra** [comment]
We can add private methods if users request them. I'm not sure we need to keep the issue open for that, but we'll accept a PR adding more private methods.
