### ISSUE TITLE
Unexpected keyword argument "autocompletion" for argument using click

### ISSUE THREAD

**Issue by maxandersen** [python/typeshed#2678]
I'm using Python.click and it complains on this perfectly valid code:

```
from typing import List, Tuple
def autoentities(args: str, incomplete: str) -> List[Tuple[str, str]]:
    """bogus function."""
    return []


@click.argument(
    'entity', autocompletion=autoentities
)
def clix():
    pass
```

`error: Unexpected keyword argument "autocompletion" for "argument"`

I assume its some dynamic parameter mypy cannot handle but I've also not found any way to disable this check :/

**Comment by srittau** [comment]
This argument is simply missing from the argument list of `click.decorators.argument` (as well as `click.core.Parameter`). Pull requests are welcome!

**Comment by maxandersen** [comment]
If you could give a pointer to where needs adding  I'm happy to try.  I see click referenced in many places so not sure how many places needs changing.

**Comment by srittau** [comment]
@maxandersen Sure, the parameter needs to be added here:

https://github.com/python/typeshed/blob/0b49ce75b478fdf283dda5dd1368759ac342dfe2/third_party/2and3/click/decorators.pyi#L73-L87

Optionally you could also add it to `Parameter.__init__()`, which is defined in `third_party/2and3/click/core.pyi`. If you have any more questions, please let me know.

**Comment by maxandersen** [comment]
btw. is there a way to turn off this validation for this specific line until PR merged ? could not find any other way than disabling validation for the whole function with `@no_type_check` which I find unfortunate.

**Comment by srittau** [comment]
Yes, you can use `# type: ignore` on the line where the error is reported to ignore any type error.

**Comment by maxandersen** [comment]
No, that doesn't for some reason work for this. Tried multiple combinations.
