### ISSUE TITLE
int.__new__ needs a stub

### ISSUE THREAD

**Issue by DarwinAwardWinner** [python/typeshed#2686]
It seems that `int` doesn't have a method stub for `__new__`, which causes mypy to complain on code that attempts to subclass int. Unfortunately, I'm not sure exactly how to write this stub. If someone can give me some guidance, I can try to write a pull request.

**Comment by sproshev** [comment]
`int.__new__` had been added in #1352 but then reverted in #1464

**Comment by DarwinAwardWinner** [comment]
So I guess it's not possible to add a stub for `int.__new__` without breaking other things? Does this mean I just need to use `# type: ignore` on the call to `super(...).__new__()` when subclassing int?

**Comment by sproshev** [comment]
@Bhargavasomu see https://github.com/python/typeshed/issues/2630

**Comment by hauntsaninja** [comment]
Closed by #4555
