### ISSUE TITLE
Need stubs for boto3

### ISSUE THREAD

**Issue by thejohnfreeman** [python/typeshed#2706]
> There are no stub files (type declarations) for this library in typeshed yet. This does not depend on mypy, someone needs to contribute these stubs. (Btw there are stubs for boto under 2and3 folder). -- [@ilevkivskyi](https://github.com/python/mypy/issues/3498#issuecomment-306491193)

> You can actually open an issue about this on typeshed tracker. As I understand boto3 and boto are very similar, so that stubs can be made quite easily. -- [@ilevkivskyi](https://github.com/python/mypy/issues/3498#issuecomment-306499363)

**Comment by JukkaL** [comment]
I think boto3 is quite different in some ways, and providing good stubs may require literal types (which mypy will likely support in early 2019). For example, consider this example adapted from [here](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/migration.html):

```py
import boto3

s3 = boto3.resource('s3')  # Return type depends on string value?
boto3_bucket = s3.Bucket('mybucket')
```

**Comment by kojiromike** [comment]
Even with literal types I'm still curious how this would be expressible:

```python
>>> import boto3, botocore
>>> x=boto3.client('kinesis')
>>> y=boto3.resource('s3')
>>> type(x)
<class 'botocore.client.Kinesis'>
>>> type(y)
<class 'boto3.resources.factory.s3.ServiceResource'>
>>> botocore.client.Kinesis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'botocore.client' has no attribute 'Kinesis'
>>> boto3.resources.factory.s3.ServiceResource
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'boto3.resources.factory' has no attribute 's3'
```

The confusion I have is that the types themselves are dynamically defined, so not only do you have to enumerate all the possible types based on each `Literal` input to `boto3.client` and `boto3.resource`, but you also have to express them as dynamic types on the output side.

**Comment by JelleZijlstra** [comment]
We could simply define them in the stubs as (say) `botocore.client._Kinesis`, and define the overload for `boto3.client` that takes `Literal["kinesis"]` as returning `_Kinesis`. It's OK for stubs to contain private classes that are not quite accessible at runtime.

**Comment by JukkaL** [comment]
Another possible approach would be to create a separate 3rd party module that contains the relevant types, perhaps as protocol types. For example, `botocore_types` could define a `Kinesis` type. This may not be worth it, but it would make it easier to use the types in user code. Hypothetical example without the separate module:

```py
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from botocore.client import _Kinesis

def foo(x: '_Kinesis') -> None:  # Str literal escape required
    do_stuff(x)
```

This is how it would work with the separate types module:

```py
from botocore_types import Kinesis

def foo(x: Kinesis) -> None:
    do_stuff(x)
```

By the way, I also would like to have these stubs, and I've done a little bit of preliminary work on them. I have some stubgen improvements in my own branch that can generate somewhat reasonably-looking stubs for `botocore` and `boto3`, but the `Kinesis` class is not included in the stubs, as probably was expected. I wonder if the class is runtime-generated. Anyway, I can probably tweak stubgen to be able to generate stubs for `Kinesis` and other similar classes (with some extra manual work).

**Comment by James-Quigley** [comment]
Any update on this? Want to use mypy but also use boto3 extensively and ideally don't want to have to write our own stubs

**Comment by vemel** [comment]
It is not a real typeshed, but I created a modular type annotations library [mypy-boto3](https://mypy-boto3.readthedocs.io/en/latest/) that supports `mypy`. It is forked from `boto3-type-annotations` with some extra features:

- `mypy` compatibility as a main goal
- real type annotations. With `boto3` naming style string annotations do not work
- subresources are included
- modularity, so you can install only services you use with or without docs
- full boto3 docs included and cleaned up
- `black`-formatted source code for easier reading

I welcome any feedback. Also, if someone can help with adding typing for return values and dict arguments - that would be great!

**Comment by vemel** [comment]
And now we have `boto3-stubs` package, so you do not have to specify types explicitly. I annotated only `boto3.__init__` and `boto3.service`, but this is already a good start.

**Comment by vemel** [comment]
@JukkaL I have generated `boto3-stubs` package that depends on `mypy-boto3` that is also automatically generated from `botocore` documentation. I am not sure if it can be included to `typeshed` since it has an extra dependency and with all dependencies it is >100 MB. What could be the best way to do this?

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
