### ISSUE TITLE
Error in built-in list type model

### ISSUE THREAD

**Issue by kevinjacobs-progenity** [python/typeshed#2711]
Note: Moved from `mypy` to `typeshed`

* problem: `list.__iadd__` type model appears to be wrong
* Python version: CPython 3.6.6 and 3.7.1
* mypy version: 0.650

Examples:
```python3
from typing import List

class MyList1(list): pass
l1 = MyList1([1, 2, 3])
l1 += [4, 5, 6]
l1.extend([7, 8, 9])
print(type(l1), isinstance(l1, MyList1), l1)

class MyList2(List[int]): pass
l2 = MyList2([1, 2, 3])
l2 += [4, 5, 6]
l2.extend([7, 8, 9])
print(type(l2), isinstance(l2, MyList2), l2)
```

Note that both `MyList1` and `MyList2` are `list` subclasses, and all I'm attempting to do is initialize instances and use `+= (.__iadd__)` and `.extend` to extend them.

Running the above code results in the following mostly unsurprising output in Python 3.6.6:
```
<class '__main__.MyList1'> True [1, 2, 3, 4, 5, 6, 7, 8, 9]
__main__.MyList2 True [1, 2, 3, 4, 5, 6, 7, 8, 9]
```
and in Python 3.7.1:
```
<class '__main__.MyList1'> True [1, 2, 3, 4, 5, 6, 7, 8, 9]
<class '__main__.MyList2'> True [1, 2, 3, 4, 5, 6, 7, 8, 9]
```

Let's ignore the disparate type representations in Python 3.6.6 -- my concern is that `mypy` complains that the in-place extensions using `__iadd__` result in invalid result types in both cases and both versions:
```
test.py:5: error: Result type of + incompatible in assignment
test.py:11: error: Result type of + incompatible in assignment
```
 
My first reaction was that I am doing something wrong.  However, after scouring the internet, this problem doesn't appear to be an instance of one of the common typing pitfalls.  The `mypy` result simply does not match the actual runtime types produced by CPython, which suggests to me that the `mypy` type model for `list.__iadd__` is incorrect and resulting in a spurious error.  

I've attempted to use what little has been shared about self-types to propose a patch to builtins.pyi:
```
_ListSelf = Union[TypeVar('_ListSelf', bound=List), TypeVar('_MutableSequenceSelf', bound=MutableSequence)]

class list(MutableSequence[_T], Generic[_T]):
    def __iadd__(self, x: Iterable[_T]) -> _ListSelf[_T]: ...
```

However TypeVars are not sufficiently generic, so `_ListSelf[_T]` is not valid.  Unfortunately, I am at the limit of my skills here.

**Comment by srittau** [comment]
This could be sufficient (untested):

```python
    def __iadd__(self: _S, x: Iterable[_T]) -> _S: ...
```

**Comment by kevinjacobs-progenity** [comment]
Thanks, @srittau!  This diff below based on your suggestion seems to be doing the job.  Both my test case and the `pytest` suite pass cleanly.  I assume I'll have to make similar changes to the `stdlib/2/builtins.pyi`, add some extra test cases, and then open a PR.  

```diff
diff --git a/stdlib/3/builtins.pyi b/stdlib/3/builtins.pyi
index 242ae6d0..12f3955b 100644
--- a/stdlib/3/builtins.pyi
+++ b/stdlib/3/builtins.pyi
@@ -620,7 +620,7 @@ class list(MutableSequence[_T], Generic[_T]):
     @overload
     def __init__(self, iterable: Iterable[_T]) -> None: ...
     def clear(self) -> None: ...
-    def copy(self) -> List[_T]: ...
+    def copy(self: _S) -> _S: ...
     def append(self, object: _T) -> None: ...
     def extend(self, iterable: Iterable[_T]) -> None: ...
     def pop(self, index: int = ...) -> _T: ...
@@ -638,17 +638,17 @@ class list(MutableSequence[_T], Generic[_T]):
     @overload
     def __getitem__(self, i: int) -> _T: ...
     @overload
-    def __getitem__(self, s: slice) -> List[_T]: ...
+    def __getitem__(self: _S, s: slice) -> _S: ...
     @overload
     def __setitem__(self, i: int, o: _T) -> None: ...
     @overload
     def __setitem__(self, s: slice, o: Iterable[_T]) -> None: ...
     def __delitem__(self, i: Union[int, slice]) -> None: ...
-    def __add__(self, x: List[_T]) -> List[_T]: ...
-    def __iadd__(self, x: Iterable[_T]) -> List[_T]: ...
-    def __mul__(self, n: int) -> List[_T]: ...
-    def __rmul__(self, n: int) -> List[_T]: ...
-    def __imul__(self, n: int) -> List[_T]: ...
+    def __add__(self: _S, x: List[_T]) -> _S: ...
+    def __iadd__(self: _S, x: Iterable[_T]) -> _S: ...
+    def __mul__(self: _S, n: int) -> _S: ...
+    def __rmul__(self: _S, n: int) -> _S: ...
+    def __imul__(self: _S, n: int) -> _S: ...
     def __contains__(self, o: object) -> bool: ...
     def __reversed__(self) -> Iterator[_T]: ...
     def __gt__(self, x: List[_T]) -> bool: ...
```

**Comment by srittau** [comment]
Please note that in typeshed HEAD the Python 2 and 3 versions of `builtins.pyi` have been merged. But there is also `stdlib/2/__builtin__.pyi`, which is a verbatim copy of `stdlib/2and3/builtins.pyi`.

Also, my brief test shows that not all of the changes above are correct. For example, `copy()` will return a true `list` instance:

```python
class MyList(list): pass
type(MyList().copy)  # will return list
```

The same is true for everything, except `__iadd__()` and `__imul()__` as far as I can see.

**Comment by kevinjacobs-progenity** [comment]
Good to know!  That is why I am writing tests to make sure the declarations match the actual runtime types.

**Comment by kevinjacobs-progenity** [comment]
Thanks!
