### ISSUE TITLE
logging.handlers.RotatingFileHandler has no attribute "baseFilename" on python2.7

### ISSUE THREAD

**Issue by mkurnikov** [python/typeshed#2713]
https://github.com/python/typeshed/blob/f9f4e5000484c267a9c44e5867bcc83c3ff71429/stdlib/2and3/logging/handlers.pyi#L61
`RotatingFileHandler` should inherit from `BaseRotatingHandler`.

Found covering pip with types.

**Comment by srittau** [comment]
It seems that all or most version checks in that file are superfluous as Python 2.7 has `BaseRotatingHandler`, but the stubs assume it doesn't.
