### ISSUE TITLE
Possible incorrect typehint for asyncio.streams.StreamWriter

### ISSUE THREAD

**Issue by diogommartins** [python/typeshed#2718]
At https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/streams.pyi#L79 the `reader` parameter is annotated as `reader: StreamWriter`, but if we take a look at [the implementation](https://github.com/python/cpython/blob/master/Lib/asyncio/streams.py#L304), the 
`reader` parameter looks more like a `Optional[StreamWriter]` because of the line `assert reader is None or isinstance(reader, StreamReader)`: 

```python
class StreamWriter:
    """Wraps a Transport.

    This exposes write(), writelines(), [can_]write_eof(),
    get_extra_info() and close().  It adds drain() which returns an
    optional Future on which you can wait for flow control.  It also
    adds a transport property which references the Transport
    directly.
    """

    def __init__(self, transport, protocol, reader, loop):
        self._transport = transport
        self._protocol = protocol
        # drain() expects that the reader has an exception() method
        assert reader is None or isinstance(reader, StreamReader)
        self._reader = reader
        self._loop = loop
```

What do you guys think about that ?

**Comment by srittau** [comment]
Agreed, looks like `Optional` is missing here. Patches welcome!

**Comment by diogommartins** [comment]
PR opened :)
