### ISSUE TITLE
enum.IntEnum members should be valid tuple index

### ISSUE THREAD

**Issue by galsondor** [python/typeshed#272]
The error message "Tuple index must be an integer literal" is produced by the following code:

```
import enum

class X(enum.IntEnum):
    a = 0
    b = 1

t = ('a', 'b')
print(t[X.a])
```

**Comment by JukkaL** [comment]
This sounds like this might be a mypy issue. If you are using mypy, could you file this here: https://github.com/python/mypy/issues

**Comment by JelleZijlstra** [comment]
I also don't think there's a typeshed bug here. The mypy problem is closely related to python/mypy#3078, so I'm not going to open a new mypy bug.
