### ISSUE TITLE
sqlite3 "load_extension"

### ISSUE THREAD

**Issue by arlyon** [python/typeshed#2725]
I noticed that `enable_load_extension` and `load_extension` are missing from the [typeshed definitions for sqlite3](https://github.com/python/typeshed/blob/master/stdlib/2and3/sqlite3/dbapi2.pyi). I could understand if this is done deliberately given that these methods are missing from python by default [because sqlite is often compiled without extension support](https://docs.python.org/3/library/sqlite3.html#f1). 

Would you accept a PR to add them? Or, given that the methods only exist on a small number of python distributions, maybe it is best to just have mypy ignore the missing definitions on my end?

**Comment by srittau** [comment]
It's fine to have definitions for functions and other features that are not always available, although this should be documented in the stub as well. PR welcome!

**Comment by srittau** [comment]
Closed in #2728.
