### ISSUE TITLE
Missing "__" names

### ISSUE THREAD

**Issue by kamahen** [python/typeshed#2726]
The following names are in `dir(builtins)` but are missing from [stdlib/2and3/builtins.pyi](https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi):

- [x] `__build_class__`
- [x] `__debug__`
- [x] `__doc__`
- [x] `__import__`
- [x] `__loader__`
- [x] `__name__`
- [x] `__package__`
- [x] `__spec__`

**Comment by dorothykiz1** [comment]
Hello @kamahen  i would like to work on this issue

**Comment by srittau** [comment]
@dorothykiz1 We gladly accept pull requests in typeshed.

**Comment by kamahen** [comment]
`builtins.type` is missing `__weakref__`.

`builtins.function` is missing `__closure__`, `__globals__`, `__defaults__`, `__kwdefaults__`, __get__).

[These lists might not be correct; I got them by using the `dir` function]

**Comment by eggplants** [comment]
Any updates?

**Comment by JelleZijlstra** [comment]
PRs are welcome.

**Comment by AlexWaygood** [comment]
I've ticked off the following three attributes from the original list, as they are automatically inserted by mypy as implicit global attributes to every module. I think that's the proper approach for a type checker to take, as they're not specific to `builtins`; they appear in every module:

- `__doc__`
- `__name__`
- `__package__`

`__loader__` and `__spec__` are _not_ currently recognised by mypy as implicit global attributes, but I think they probably _should_ be (I don't think we should add them to the stub). So I'm ticking them off the original list as well.

**Comment by AlexWaygood** [comment]
Actually, looks like `__debug__` is [also special-cased by mypy](https://github.com/python/mypy/blob/0fecec8c72605ec7bae343b28d545c477c726e81/mypy/semanal.py#L381) in a similar way (but is only inserted into the `builtins` module). So I'll tick that one off the list as well.

That means the only remaining "missing dunder" identified in this issue is `builtins.type.__weakref__`. But that one's tricky:

```python
>>> class Foo: ...
... 
>>> Foo.__weakref__
<attribute '__weakref__' of 'Foo' objects>
>>> int.__weakref__
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    int.__weakref__
AttributeError: type object 'int' has no attribute '__weakref__'
```

**Comment by AlexWaygood** [comment]
> That means the only remaining "missing dunder" identified in this issue is `builtins.type.__weakref__`. But that one's tricky:
> 
> ```python
> >>> class Foo: ...
> ... 
> >>> Foo.__weakref__
> <attribute '__weakref__' of 'Foo' objects>
> >>> int.__weakref__
> Traceback (most recent call last):
>   File "<pyshell#3>", line 1, in <module>
>     int.__weakref__
> AttributeError: type object 'int' has no attribute '__weakref__'
> ```

I'm closing this issue as all other dunders have been added to the relevant stubs, no use case has been put forward for `type.__weakref__`, and adding `type.__weakref__` would be tricky for the reasons outlined above. If its absence from the stub is causing issues for anyone, they're free to open a new issue.
