### ISSUE TITLE
builtins.pyi leaks Typing (and other) names

### ISSUE THREAD

**Issue by kamahen** [python/typeshed#2727]
[builtins.pyi](https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi) leaks the names that it imports.

One possible solution is to specify an `__all__` value; this could also be used to distinguish between the Python 2 and Python 3 items (e.g., `apply`, `basestring`, `long`, etc.)

An alternative (that could break some tools) is to "import as", e.g.:

```python
    from typing import (TypeVar as _TypeVar, ... Any as _Any, ... Dict as _Dict)
    from types import TracebackType as _TracebackType, CodeType as _CodeType
    import sys as _sys
        ...
    class _function:
    # TODO not defined in builtins!
    __name__: str
    __module__: str
    if _sys.version_info >= (3,):
        __qualname__: str
        __code__: _CodeType
        __annotations__: _Dict[str, _Any]
```

**Comment by JukkaL** [comment]
Imported names in stubs have special semantics -- they aren't exported unless using "import as". For example the `os` module exports `path`, so it must import it like this: `from . import path as path`. However, most other imports aren't exported.
