### ISSUE TITLE
six.raise_from value type

### ISSUE THREAD

**Issue by RazerM** [python/typeshed#2742]
Currently:
https://github.com/python/typeshed/blob/a2c0f4b827b693c81b2daaf165da52add3ac5707/third_party/3/six/__init__.pyi#L99

This warns on raising an exception type rather than an instance:
```
six.raise_from(ValueError, None)
```

Should the type be `Union[BaseException, Type[BaseException]]`?

**Comment by srittau** [comment]
Yes I believe that is the correct solution. Would you like to submit a pull request?
