### ISSUE TITLE
`NamedTemporaryFile` / `mkstemp` appear to allow `Path` for `dir=` parameter though undocumented

### ISSUE THREAD

**Issue by asottile** [python/typeshed#2749]
```
>>> from pathlib import Path
>>> d = Path('/tmp/wat')
>>> d.mkdir(exist_ok=True, parents=True)
>>> import tempfile
>>> with tempfile.NamedTemporaryFile(dir=d) as f:
...     print(f.name)
... 
/tmp/wat/tmp68qwo9yy
```

**Comment by srittau** [comment]
Looking at the source, `NamedTemporaryFile` calls `mkstemp()`, which calls `os.path.join()`, `os.path.isdir()`, and `os.access`, which are all path-safe, starting with Python 3.6. Patches welcome.

**Comment by asottile** [comment]
I've created a bpo issue to document / test this since this appears untested and I wouldn't want it to regress: https://bugs.python.org/issue35803

**Comment by asottile** [comment]
here's the cpython PR: https://github.com/python/cpython/pull/11644
