### ISSUE TITLE
base64.b64encode allows `bytes-like` argument

### ISSUE THREAD

**Issue by joernheissler** [python/typeshed#2750]
```python3
from typing import ByteString
from base64 import b64encode

def func(data: ByteString) -> bytes:
    return b64encode(data)

# b64.py:5: error: Argument 1 to "b64encode"
# has incompatible type "ByteString"; expected "bytes"
```
https://docs.python.org/3/library/base64.html#base64.b64encode says it allows `bytes-like`.
Same for the other encode functions like `urlsafe_b64encode`.

**Comment by srittau** [comment]
This looks like a mypy bug to me. `bytes` as an argument [is documented](https://docs.python.org/3/library/typing.html#typing.ByteString) to be identical to the types `ByteString` represents. @ilevkivskyi

**Comment by JelleZijlstra** [comment]
I think this is a mypy bug if anything. My impression is that `typing.ByteString` isn't much use; maybe we should deprecate it.
