### ISSUE TITLE
Value of type "stat_result" should be indexable

### ISSUE THREAD

**Issue by Steap** [python/typeshed#2751]
Hello,

The following code snippet works perfectly:

```python
import stat
import os

os.stat('/tmp')[stat.ST_MODE]
```

But mypy returns an error:

```
$ mypy bug.py 
bug.py:4: error: Value of type "stat_result" is not indexable
```

I believe that stat_result should be indexable.

**Comment by srittau** [comment]
`class stat_result` is missing the `__getitem__()` method to implements this behaviour. Pull requests welcome!
