### ISSUE TITLE
Why is filter(None, it) special?

### ISSUE THREAD

**Issue by nekketsuuu** [python/typeshed#2757]
Currently, by [these lines](https://github.com/python/typeshed/blob/9e5816a5390302933b2444fcff345798e06fa784/stdlib/2and3/builtins.pyi#L1128), a type of `filter()` is overloaded:

* `filter(None, it: Iterable[Optional[_T]]) -> Iterator[_T]`
* `filter(f: Callable[[_T], Any], it: Iterable[_T]) -> Iterator[_T]`

This overload is discussed at python/mypy#3835 and #779.

Because of this implementation, a type of `filter(None, [0, 1, 2, None])` is inferred as `Iterator[int]`, not `Iterator[Optional[int]]`. But this is inconsistent with a type of `filter(lambda x: x, [0, 1, 2, None])`, which is an essentially same expression with that.

```python
it = [0, 1, 2, None]
reveal_type(filter(None, it))                     # typing.Iterator[builtins.int*]
reveal_type(filter(lambda x: x, it))              # typing.Iterator[Union[builtins.int, None]]
reveal_type(filter(lambda x: x is not None, it))  # typing.Iterator[Union[builtins.int, None]]
```

I don't understand why these are distinguished.

Also, this typing is misleading; `filter(None, it)` also removes `0` and `False` other than `None`. Therefore `filter(None, it)` should not be used for converting `Iterator[Optional[_T]]` to `Iterator[_T]`. Actually `filter(lambda x: x is not None, it)` does that work, although this returns a value of a type `Iterator[Optional[_T]]` (additional `map` is necessary).

I think no overload is needed here. Is there any reasons of this special treatment for `filter(None, it)`?

### Environment

* Python 3.6.6
* mypy 0.650

**Comment by srittau** [comment]
Type annotations only specify the type signature of a function, they make no statement about the semantics of that function. The iterator returned when the first argument is `None` will never contain `None` values. It makes sense to express that fact in the annotations. On the other hand, interpreting what a supplied callback does, is out of scope of type checking. I don't see any way to improve the annotations for this case and removing the first overload worsens the annotations.

**Comment by Michael0x2a** [comment]
@nekketsuuu -- I'm not sure if it makes much sense to talk about how "useful" a particular signature is. Rather, the goal is to make signatures in typeshed *accurate*.

In this case, the [documentation for `filter`][0] states that `filter(None, seq)` will strip out all false-y values, including None. So the closer we can make the type signature reflect this reality, the better. 

After all, there's a lot of Python code out there -- and so we can bet with almost 100% certainty that somebody out there will be relying on this behavior. It would be inconvenient for those users if they had to work around inaccurate or imprecise signatures to get their code to type check.

  [0]: https://docs.python.org/3/library/functions.html#filter
