### ISSUE TITLE
`typing.NamedTuple` should accept `unicode` names

### ISSUE THREAD

**Issue by mrhania** [python/typeshed#2761]
Currently, `NamedTuple` has the following signature associated with its constructor:

```python
def __init__(self, typename: str, fields: Iterable[Tuple[str, Any]] = ..., *,
             verbose: bool = ..., rename: bool = ..., **kwargs: Any) -> None: ...
```

This causes type checking to fail in Python 2 for modules where `unicode_literals` is enabled since this function is usually called this way:

```python
Foo = NamedTuple("Foo", (("bar", Bar), ("baz", Baz)))
```

Instead, `typename` should have type `AnyStr` and `fields` should have type `Iterable[Tuple[AnyStr, Any]]`.

**Comment by JelleZijlstra** [comment]
Thanks for the report and fix!

Just to be clear, there is no such thing as an AnyStr value, since AnyStr is a type variable.

**Comment by mrhania** [comment]
> Just to be clear, there is no such thing as an AnyStr value, since AnyStr is a type variable.

Ah, good to know. I was sure that `AnyStr` is just an alias for `Union[str, unicode]` but apparently I was wrong.
 
I think in this particular case `AnyStr` should work just fine for most real world scenarios: `NamedTuple` is used in a "static" way with string literals and people use either bytestring literals or unicode literals without mixing the two. Nevertheless, `Union[str, unicode]` is obviously more general so I have fixed the code.
