### ISSUE TITLE
`jwt.decode` return `Mapping`

### ISSUE THREAD

**Issue by Hanaasagi** [python/typeshed#2764]
Env:

- Python 3.7.1
- mypy 0.660

Test Code:

```Python
import jwt

encoded = jwt.encode({'some': 'payload'}, 'secret', algorithm='HS256')
res = jwt.decode(encoded, 'secret', algorithms=['HS256'])
res['some'] = 'another payload'
```

mypy will report:

```
t.py:5: error: Unsupported target for indexed assignment
```

In typeshed's master branch, [jwt.decode](https://github.com/python/typeshed/blob/master/third_party/3/jwt/__init__.pyi#L8) return a `Mapping[str, Any]`.

```pyi
def decode(jwt: Union[str, bytes], key: Union[str, bytes] = ...,
           verify: bool = ..., algorithms: Optional[Any] = ...,
           options: Optional[Mapping[Any, Any]] = ...,
           **kwargs: Any) -> Mapping[str, Any]: ...
```

From the Python doc [`collections.abc.Mapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.Mapping), `Mapping` is read-only. So it not supports indexed assignment.

I think `jwt.decode` should return `Dict[str, Any]` or `MutableMapping[str, Any]`.
If someone appoved this changing, I will pull request to solve it : )

**Comment by JelleZijlstra** [comment]
What do the docs for jwt say about this?

**Comment by Hanaasagi** [comment]
The API Reference in pyjwt doc is not complete. [https://pyjwt.readthedocs.io/en/latest/api.html](https://pyjwt.readthedocs.io/en/latest/api.html)

**Comment by srittau** [comment]
The implementation returns whatever is returned from either `json.loads()` (as long as it is a mapping), which returns a `dict`. Since we prefer concrete return types, I'd say `decode()` should actually return `Dict[str, Any]`.
