### ISSUE TITLE
mypy doesn't know Enum objects have  _name_ attribute

### ISSUE THREAD

**Issue by jimbo1qaz** [python/typeshed#2766]
```py
class _EnumMixin:
    @classmethod
    def to_yaml(cls, representer: Representer, node: Enum) -> Any:
        return representer.represent_str(node._name_)
```

When checking in mypy, I get false-positive `error: "Enum" has no attribute "_name_"; maybe "name"?`

https://docs.python.org/3/library/enum.html#supported-sunder-names describes `_name_` which works at runtime.

Python 3.7.2, mypy 0.660.

**Comment by srittau** [comment]
Thank you for the report. PRs are welcome!
