### ISSUE TITLE
collections.deque.__iadd__ missing

### ISSUE THREAD

**Issue by jrosdahl** [python/typeshed#2771]
Using mypy 0.660:

```
from collections import deque
from typing import Deque, MutableSequence

d1: MutableSequence[int] = deque([1])
d1.extend([2])  # works
d1 += [2]  # works

d2: Deque[int] = deque([1])
d2.extend([2])  # works
d2 += [2]  # error: Result type of + incompatible in assignment

d3 = deque([1])
d3.extend([2])  # works
d3 += [2]  # error: Result type of + incompatible in assignment
```

It works for me to simply add

```
def __iadd__(self, iterable: Iterable[_T]) -> deque[_T]: ...
```

to `deque` in `stdlib/3/collections/__init__.py`. However, I'm unsure about the return type since I noticed that the Python 2 version of `collections.deque.__iadd__` looks like this:

```
def __iadd__(self, other: deque[_T2]) -> deque[Union[_T, _T2]]: ...
```

I don't understand the reason for having a union return type. Any input here?

**Comment by srittau** [comment]
Where do you see that annotation for Python 2? `stdlib/2/collections.pyi` also does not include `deque.__iadd__()`. Anyway, I think annotating it like this is a better idea, so that sub-classing works as expected (untested):

```python
_S = TypeVar("_S")
class deque(...):
    ...
    def __iadd__(self: _S, value: Iterable[_T]) -> _S: ...
```

Patches welcome!
