### ISSUE TITLE
Mapping.{get,pop} can return default type

### ISSUE THREAD

**Issue by gnprice** [python/typeshed#278]
See #223. That PR was reverted because it caused some type errors that it shouldn't, but it's the right thing to do and we should figure out how to make it work.

@gvanrossum , what did the errors you saw (after python/mypy#1595 was fixed) look like?

**Comment by rwbarton** [comment]
See also https://github.com/python/mypy/issues/738 and https://github.com/python/mypy/issues/1114.

**Comment by euresti** [comment]
If I understand correctly this looks fixed by #822
@gnprice: Is it what you wanted?

**Comment by JelleZijlstra** [comment]
I think it's fixed for `get` but not `pop`.

**Comment by euresti** [comment]
Oh yeah.  And we use the pop version a lot.  That sounds like something I can help out with.
