### ISSUE TITLE
Flask app Protocol

### ISSUE THREAD

**Issue by macbeth322** [python/typeshed#2789]
First off, big thanks to @pcorpet for adding Flask stubs in #2740. I was updating one of my packages with to new type information and noticed something that stuck out to me.

One of the patterns that my team and I like to use is to create a set of endpoints that are bound to a `Flask` duck-type; basically this factory can take a `flask.Flask` instance or a `flask.Blueprint` instance since both support `add_url_rule`.

https://github.com/python/typeshed/blob/75581cf7da13dcea9ab5080e930530ecb5bc5ef3/third_party/2and3/flask/blueprints.pyi#L41
https://github.com/python/typeshed/blob/ca62cecd1422c4f68c051f326cc9bc4b28c781e2/third_party/2and3/flask/app.pyi#L98

I am not super familiar with typeshed practices or Flask internals but the solution I am using right now locally is to define `FlaskBlueprintType = Union[flask.Flask, flask.Blueprint]` and use that. A potentially more useful solution would be to define an ABC which Flask and Blueprint either explicitly implement or simply through https://docs.python.org/3/library/abc.html#abc.ABCMeta.register. Another option is to use https://www.python.org/dev/peps/pep-0544/ but Protocols are not fully finalized yet.

Does this make sense as type information to add or am I approaching this problem the wrong way?

**Comment by srittau** [comment]
Protocols seem like a good fit for this solution, but a union is fine as well. I don't think there is anything in typeshed we could or should do about this, though (unless this is a common pattern).
