### ISSUE TITLE
Flask typeshed: Blueprint.root_path is never None

### ISSUE THREAD

**Issue by afourmy** [python/typeshed#2791]
The `root_path` attribute of a Flask blueprint is set to `Optional[str]` here: https://github.com/python/typeshed/blob/75581cf7da13dcea9ab5080e930530ecb5bc5ef3/third_party/2and3/flask/blueprints.pyi#L27

Actually, it is defined in the `__init__` of `_PackageBoundObject` here: https://github.com/pallets/flask/blob/master/flask/helpers.py#L909-L910
___
Example:

We get the following error with `strict_optional` enabled :
```
from flask import Blueprint
from pathlib import Path
path_bp = Path(Blueprint('', '').root_path)
```

`error: Argument 1 to "Path" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"`
___
Fix:
I don't know mypy so I'm not sure if this needs to be fixed at all, but removing `Optional` in the flask typeshed: `root_path: str = ...` works.

**Comment by srittau** [comment]
Looking at the implementation, `root_path` can't be `None`, so it shouldn't be marked as `Optional`. Patches welcome!

**Comment by rusheb-brainlabs** [comment]
The class `Flask` also has `root_path` set to `Optional[str]`.
https://github.com/python/typeshed/blob/fd57aee5dae21bd962f9df5d0d1c427ff96c3670/third_party/2and3/flask/app.pyi#L45

---

Reproduced by adapting the original example:
```python
from flask import Flask
from pathlib import Path

path_flask = Path(Flask(__name__).root_path)
```

`mypy: Argument 1 to "Path" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"`

---

I don't know enough about how flask works to be sure, but it seems to me that this also can't be `None`. If so I think the same fix as above would be appropriate.

**Comment by rusheb** [comment]
For anyone else that's experiencing this - the class `Flask` in `app.py` also has `root_path` typed as `Optional[str]`:

https://github.com/pallets/flask/blob/c5c8bbc7f699de6b81ebd9893dc0a2289ae688dc/flask/helpers.py#L909-L910

---

This can be reproduced by adapting the original example:
```python
from flask import Flask
from pathlib import Path

path_flask = Path(Flask(__name__).root_path)
```

`mypy: Argument 1 to "Path" has incompatible type "Optional[str]"; expected "Union[str, _PathLike[str]]"`

---
This is what it says about `Flask.root_path` in the docs:
https://github.com/pallets/flask/blob/a74864ec229141784374f1998324d2cbac837295/flask/app.py#L163-L167

It seems that there are some cases where `Flask.root_path` can be `None` so the same fix is probably not appropriate, but I'm not sure.
