### ISSUE TITLE
Flask stubs: Return type of "dispatch_request" incompatible with supertype "View"

### ISSUE THREAD

**Issue by bbc2** [python/typeshed#2795]
Here's a Flask application using a pluggable view to return a string:

```python
from flask import Flask, Response, redirect
from flask.views import View

app = Flask(__name__)


class Hello(View):
    def dispatch_request(self) -> str:
        return "Hello, world!"


app.add_url_rule("/hello/", view_func=Hello.as_view("hello"))
```

Unfortunately, mypy complains about the return type being incompatible with that of the superclass:

```
> mypy app.py
app.py:8: error: Return type of "dispatch_request" incompatible with supertype "View"
```

Looking at the stubs, it looks like the declared return type for `dispatch_request` is `None`.  Is that expected?  In Flask, you can return a `Response`, or a `Tuple[str, int]`, so maybe it would be worth simplifying it to `Any` as a first step, and to avoid false positives.

**Comment by bbc2** [comment]
A similar error occurs when the method has arguments:

```python
from flask import Flask, Response, redirect
from flask.views import View

app = Flask(__name__)


class Hello(View):
    def dispatch_request(self, name: str):
        return "Hello, {}!".format(name)


app.add_url_rule("/hello/<name>", view_func=Hello.as_view("hello"))
```

```
> mypy app.py
app.py:8: error: Signature of "dispatch_request" incompatible with supertype "View"
```

**Comment by srittau** [comment]
The full list of allowed return values can be found here: https://github.com/pallets/flask/blob/0b5b4a66ef99c8b91569dd9b9b34911834689d3f/flask/app.py#L1909 Returning `Any` for now seems reasonable. Also, `dispatch_request()` needs to accept any arg and keyword arg. Patches welcome!

**Comment by layoaster** [comment]
I have mypy v0.710 (Python 3.7.2) but still getting the same signature error message:
```shell
aud_idp/views/health.py:19: error: Signature of "dispatch_request" incompatible with supertype "View"
```

```python
class LivenessProbe(View):
    """Liveness probe handler."""

    methods = ("GET",)

    def dispatch_request(self) -> Any:
        """
        The application is considered to be alive as long as it returns a
        response.

        :return: HTTP response with a status code of `200`.
        """
        return "Ok"
```

**Comment by srittau** [comment]
@layoaster `dispatch_request()` needs to accept any arguments (i. e. `*args: Any, **kwargs: Any`).
