### ISSUE TITLE
Readme should explain installation/use of typeshed when mypy is installed via pip

### ISSUE THREAD

**Issue by rswgnu** [python/typeshed#2798]
The Readme seems to assume installation of mypy and pytype via git clone and not through pip.
It would be good to add use of the type checkers with typeshed when they are installed via pip.

**Comment by srittau** [comment]
The README contains the following as first sentence of the "Using" section:

> If you're just using mypy (or pytype or PyCharm), as opposed to developing it, you don't need to interact with the typeshed repo at all: a copy of typeshed is bundled with mypy.

Suggestions on how to improve the wording are welcome.
