### ISSUE TITLE
Stub for flask

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#28]
I could make one. Will work with @mitsuhiko to vet it.

**Comment by nlyubchich** [comment]
Is there any progress for this issue? Any help is needed?

**Comment by zoidbergwill** [comment]
Additional offer to help.

**Comment by zoidbergwill** [comment]
Should I start working on a PR maybe, and mitsuhiko or @pallets folk can take a look at it?

**Comment by gvanrossum** [comment]
We would be happy to accept a PR as long as the current flaks maintainers
are okay with it. Usually asking in their tracker and posting a link to a
positive response works well.



-- 
--Guido (mobile)

**Comment by rowillia** [comment]
Flask folks gave permission here - https://github.com/pallets/flask/issues/2012

**Comment by gvanrossum** [comment]
Great! Get cracking!

**Comment by zoidbergwill** [comment]
I've started working on it, and will happily accept PRs or any input: https://github.com/zoidbergwill/typeshed

Is there any documentation on tips on creating new stubs?

I've used `stubgen`, and am working on each file one by one now.

**Comment by gvanrossum** [comment]
Hm, I think the best way to learn how to create stubs ATM is probably to read a bunch of existing stubs. Please do understand that stubgen doesn't infer argument types except if there's a default, so you should add those manually. Also, there's no way to test that the stubs you create match the real flask library -- the way to assess that is typically to add annotations to a mid-size app using flask and to verify that the app both runs correctly and type-checks cleanly.

**Comment by zoidbergwill** [comment]
Awesome, thanks. Browsing all the existing stubs in this repo have been how I've been figuring it out so far.

Thanks, will try that out. I have some Flask apps with some annotation coverage which I'll improve and then test it on.

**Comment by rowillia** [comment]
@zoidbergwill I've got a PR open that adds stubs to werkzeug - https://github.com/python/typeshed/pull/530

**Comment by zoidbergwill** [comment]
Thanks @rowillia Should I wait and then reuse some of your new types you're adding?

**Comment by kenzierocks** [comment]
Any progress on this? I'd like to use these.

**Comment by zoidbergwill** [comment]
I started work on it [here](https://github.com/zoidbergwill/typeshed) ages ago, but the tooling for starting a fresh stub might have improved since then.

**Comment by vivaldus** [comment]
It's disconcerting to me -- a new/prospective user of mypy -- that a python product as well-known as flask doesn't have typings after all this time.

**Comment by ilevkivskyi** [comment]
@vivaldus 
> It's disconcerting to me -- a new/prospective user of mypy -- that a python product as well-known as flask doesn't have typings after all this time.

Have you noticed that this issue is closed? The stubs were added couple weeks ago and actually went into the latest mypy release.

But more importantly, what was the purpose of this comment?
