### ISSUE TITLE
Wrong annotation in Flask for SessionInterface.open_session

### ISSUE THREAD

**Issue by MasterMind2k** [python/typeshed#2802]
The included type annotation for `SessionInterface.open_session` defined return type of `None`. By documentation this is not true:
http://flask.pocoo.org/docs/0.12/api/#flask.sessions.SessionInterface.open_session

By docs, the return value is more something like `Optional[flask.sessions.SessionMixin]`. I used the work "like" because the framework is expecting a dict interface ("implements a dictionary like interface + the methods and attributes on SessionMixin")

**Comment by srittau** [comment]
It sounds as if returning a newly defined protocol is the best option. But returning `Optional[Any]` as a stop-gap measure would also be fine. Patches welcome!

**Comment by srittau** [comment]
Closing as the flask stubs will be removed in a few months.
