### ISSUE TITLE
Missing methods for Calendar object on Python3.7

### ISSUE THREAD

**Issue by yasuyuky** [python/typeshed#2806]
`Calendar` class in std module `calendar` has some new methods on Python 3.7

https://docs.python.org/3.7/library/calendar.html#calendar.Calendar.itermonthdays3
https://docs.python.org/3.7/library/calendar.html#calendar.Calendar.itermonthdays4

These seem to be missing.

For example, mypy reports the following messages.
```
 error: "Calendar" has no attribute "itermonthdays3"; maybe "itermonthdays", "itermonthdays2", or "itermonthdates"?
```

**Comment by srittau** [comment]
These are indeed missing. Patches to add them are welcome!
