### ISSUE TITLE
Typing `ProactorEventLoop` on Multi Platform Code

### ISSUE THREAD

**Issue by cooperlees** [python/typeshed#2816]
Hi,

asyncio [pyi](https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/__init__.pyi) has the ProactorEventLoop defined in an `if` statement for Win32 only. This causes `mypy` runs on non Windows platforms to report:
```
ptr.py:33: error: Module has no attribute "ProactorEventLoop"
```

What harm is there in submitting a PR to remove this conditional around the definition?

**Comment by srittau** [comment]
I have no access to a computer right now, but I assume that `ProactorEventLoop` is not defined on non-Windows platforms. This would lead to false positives on the platforms. Do you have example code where this fails, although the code will run on non-Windows platforms?

**Comment by cooperlees** [comment]
Hi @srittau - Thanks for you response. I all open for smarter ideas than my removal of the conditional.

The code can be seen here: https://github.com/facebookincubator/ptr/blob/master/ptr.py#L34
The summary of important code for this issue is:
```
from platform import system
WINDOWS = system() == "Windows"
if WINDOWS:
    asyncio.set_event_loop(asyncio.ProactorEventLoop())  # type: ignore
```
With mypy.ini having `warn_unused_ignores = True` set causes mypy to fail on  Windows platforms with an error saying this ignore is not needed. The inverse, if I remove the comment, causes the error mentioned above.

Should this be a feature request for mypy to be more platform aware? Or is there a better way for me to check if we are on Windows that `mypy` can understand?

**Comment by cooperlees** [comment]
Sorry, I didn't know linking my PR would cause this much spam.

**Comment by msullivan** [comment]
mypy will understand a check of the form `if sys.platform == 'win32'`
Alternatively, you could specify `--always-true=WINDOWS` in your configuration for checking against windows and `--always-false=WINDOWS` for other platforms.

See https://mypy.readthedocs.io/en/latest/common_issues.html#python-version-and-system-platform-checks

**Comment by cooperlees** [comment]
Thankyou - Sorry I missed that. Will try.
