### ISSUE TITLE
non-writeable property `name` in IO

### ISSUE THREAD

**Issue by jolaf** [python/typeshed#2824]
I'm trying to create my own class that has IO capability.
The class instances would have names similar to file names, but specified at the moment of instance creation.
However when I try setting `name` field, `mypy` is protesting.

Here's the minimal repro:
```python
from typing import AnyStr, IO
class MyIO(IO[AnyStr]):
    def __init__(self, name: str) -> None:
        self.name = name
```

`mypy` output:
```
Test.py: note: In member "__init__" of class "MyIO":
Test.py:5: error: Property "name" defined in "IO" is read-only
```

**Comment by srittau** [comment]
`IO.name` is defined as a property in both the typing implementation and the stubs. You need to override this property in your sub-class if you want to provide a setter:

```python
from typing import AnyStr, IO

class MyIO(IO[AnyStr]):
    def __init__(self, name: str) -> None:
        self.name = name

    @property
    def name(self) -> str:
        ...

    @name.setter
    def name(self, name: str) -> None:
        ...
```
