### ISSUE TITLE
ConfigParser has incompatible type IO[Any]; expected TextIO

### ISSUE THREAD

**Issue by BoboTiG** [python/typeshed#283]
Hello,

This is a reference from python/mypy#1688.

I am testing mypy and cannot solve this error. I am using Python 3.5.1 and mypy 0.4.2 (same error with mypy 0.4.1). The snippet:

``` python
    #!/usr/bin/env python
    # coding: utf-8

    from configparser import ConfigParser


    def update_stats(ini_file: str, lines: int) -> None:
        ''' Statistics update. '''

        ini = ConfigParser()
        ini.read(ini_file)
        lines += ini.getint('stats', 'lines')
        ini.set('stats', 'lines', str(lines))
        ini.write(open(ini_file, 'w'))

        # Same error with io
        import io
        ini.write(io.open(ini_file, 'w'))


    update_stats('stats.ini', 10)
```

And `stats.ini`:

``` ini
    [stats]
    lines = 2
```

Using the command line:

``` shell
    $ mypy tests.py
    test.py: note: In function "update_stats":
    test.py:14: error: Argument 1 to "write" of "ConfigParser" has incompatible type IO[Any]; expected "TextIO"
    test.py:18: error: Argument 1 to "write" of "ConfigParser" has incompatible type IO[Any]; expected "TextIO"
```

Could you please tell me what is going wrong  here? Thank you in advance :)

**Comment by JukkaL** [comment]
Likely the stub for `configparser` should accept `IO[str]` instead of `TextIO`.

**Comment by JukkaL** [comment]
@BoboTiG Would you like to contribute a fix?

**Comment by BoboTiG** [comment]
Yes, of course. Thank you to give me that chance :)
I will send a patch soon.

**Comment by gvanrossum** [comment]
FWIW I've seen similar issues several times now. It's unfortunate that IO[str] and TextIO are not the same thing. Maybe we should make them the same, or else we should hunt down all uses of TextIO and change them to IO[str], or maybe we should just change open() and sys.std{in,out,err} to return TextIO?

**Comment by JukkaL** [comment]
This was discussed before. `TextIO` has a bunch of additional things not available in `IO[x]`, because binary streams don't support them. My suggestion is to move everything to `IO[x]` and then let tools worry about how to handle stuff that should not be available in `IO[bytes]`, for example.

**Comment by BoboTiG** [comment]
Which is better? Completly remove the TextIO type or to specify both are the same?

**Comment by BoboTiG** [comment]
OK, did not see you answer at time. Do you want I send a PR to replace all TextIO?

**Comment by JukkaL** [comment]
Let's start with fixing `configparser` to not use `TextIO` in arguments. Generally arguments should use `IO[x]` instead of `TextIO`, but return values may use `TextIO` without problems. The more general issue will likely need some more discussion.

**Comment by BoboTiG** [comment]
Good, I am working on.
