### ISSUE TITLE
In RawConfigParser "vars: _section" should be "vars: Optional[_section]"

### ISSUE THREAD

**Issue by jolaf** [python/typeshed#2847]
Methods `get*()` and `items()` of `RawConfigParser` and `SectionProxy` declare argument `vars=None`.

However in the stubs they're defined as `vars: _section`, where `_section = Mapping[str, str]`, which effectively creates problems when inheriting from `ConfigParser` and trying to follow the original defaults pattern.

Probably in all these methods it should be `vars: Optional[_section]`.

**Comment by srittau** [comment]
Patches welcome!

**Comment by jolaf** [comment]
https://github.com/python/typeshed/pull/2853
