### ISSUE TITLE
TypeVar stub is incorrect

### ISSUE THREAD

**Issue by peterhal** [python/typeshed#2882]
https://github.com/python/typeshed/blob/master/stdlib/3/typing.pyi#L13

Should be something like:

```
class TypeVar(object):
   __name__: str
  def __init__(self, name: str) -> None: ...
```

**Comment by JelleZijlstra** [comment]
Is this causing a concrete problem for you?

**Comment by peterhal** [comment]
Yes - the following doesn't type check:

```
def f() -> Any:
  return TypeVar('x')
```

Worth noting that the same with the other type constructors (List, Mapping, Optional, ...) all work fine.

**Comment by srittau** [comment]
I am not sure whether changing it in typeshed will help, since type checkers tend to ignore `typing.pyi`. That said, I am in favor of having `typing.pyi` match reality as best as possible anyway. Patches welcome!
