### ISSUE TITLE
typing.no_type_check_decorator is not stubbed in typeshed

### ISSUE THREAD

**Issue by lunixbochs** [python/typeshed#2884]
https://docs.python.org/3/library/typing.html#typing.no_type_check_decorator

I assume this also needs mypy support, as `no_type_check` is hardcoded there, but including in typeshed feels like a prereq.

```
from typing import no_type_check, no_type_check_decorator

@no_type_check_decorator
def test(fn):
    return fn

@test
def blah(x: {'x': 1}):
    pass

@no_type_check
def blah2(x: {'x': 1}):
    pass
```

```
$ mypy notypecheck.py 
notypecheck.py:1: error: Module 'typing' has no attribute 'no_type_check_decorator'
notypecheck.py:8: error: Invalid type comment or annotation
```

**Comment by JelleZijlstra** [comment]
Yes, we should add it to typeshed. You are right though that type checkers like mypy will need to do additional work in order to make this decorator actually work.

**Comment by JelleZijlstra** [comment]
I'd prefer if we make it closer to its runtime implementation, which I think would be something like:
```
_C = TypeVar("_C", bound=Callable[..., Any])

def no_type_check_decorator(decorator: _C) -> _C: ...
```

**Comment by CraftSpider** [comment]
This was added in #3460
