### ISSUE TITLE
Types from the typing module that don't exist in the specified Python version are not detected

### ISSUE THREAD

**Issue by matthewslouismarie** [python/typeshed#2890]
Hello there,

I'm using Mypy, but I've been told that this problem actually pertains to typeshed.
If I set the version of Python to 3.5, it doesn't report Deque imports but treat this type and import as valid, even though this type only appeared in Python 3.6.

mypy.ini:
```
[mypy]
python_version = 3.5
```

The python code:
```
from typing import Deque

...
```

This does not report any errors with mypy 0.670.

**Comment by ilevkivskyi** [comment]
As I mentioned in https://github.com/python/mypy/issues/6593 this can't be solved in typeshed.
