### ISSUE TITLE
Typo in FrameType

### ISSUE THREAD

**Issue by CraftSpider** [python/typeshed#2898]
https://github.com/python/typeshed/blob/0f5302b3b50702aba73effcffc7a07ae7742bab1/stdlib/3/types.pyi#L182

This line claims that FrameType has an attribute named `f_frace_lines`. The actual attribute name is `f_trace_lines`.
![image](https://user-images.githubusercontent.com/13342132/55492804-d7642300-5605-11e9-9cc5-a79c655b233c.png)

**Comment by JelleZijlstra** [comment]
Thanks! Would you mind submitting a fix?

**Comment by CraftSpider** [comment]
No problem, I'll open a PR shortly
