### ISSUE TITLE
quit() should be annotated with NoReturn

### ISSUE THREAD

**Issue by johnwspirent** [python/typeshed#2912]
MyPy is reporting a "Missing return statement" with the following:

```
def foo() -> str:
    try:
        with open('bar.txt') as file:
       return ''
    except FileNotFoundError as error:
    print(error)
quit()
```

I raised the issue with MyPy, https://github.com/python/mypy/issues/6661, but they  say that it is a typeshed problem, "quit() must be annotated with NoReturn".

**Comment by srittau** [comment]
Patches welcome!
