### ISSUE TITLE
`dis.dis` has incorrect annotation

### ISSUE THREAD

**Issue by Hanaasagi** [python/typeshed#2914]
### Env
- Python 3.7.2
- MyPy 0.700

### Problem Details

Following code

```Python
import dis


def f(a: int) -> int:
    return a + 2


dis.dis(f)
```

MyPy will report 

```
x.py:8: error: Argument 1 to "dis" has incompatible type "Callable[[int], int]"; expected "Union[MethodType, FunctionType, CodeType, type, str, bytes]"
```

It seems MyPy does not parse it as `types.FunctionType`, I'm not sure it's a bug of MyPy or typeshed. I check the code of `dis.dis` (https://github.com/python/cpython/blob/9a3ffc0492d1310ead9ce8f5ee678c26b20a338d/Lib/dis.py#L34-L77), I think implementing a `Protocol` is a workaround.

**Comment by JelleZijlstra** [comment]
This is arguably a mypy bug: mypy doesn't recognize that `f` is a `FunctionType` (python/mypy#3171). However, that's not easily fixable. A good workaround would be to make `dis.dis` accept `Callable[..., Any]`.
