### ISSUE TITLE
Correct positional-only builtins.

### ISSUE THREAD

**Issue by brandtbucher** [python/typeshed#2916]
A great many of the builtins take positional-only arguments, but are not `__marked` as such. I'm planning on correcting all of these this weekend, but want to get a blessing on this before I dive in!

**Comment by srittau** [comment]
I wonder whether it makes sense to wait until PEP 570 is implemented in the most common type-checkers. That said, this would also be welcome with the old syntax. Reviewing this might take a bit of time, though.

**Comment by brandtbucher** [comment]
I figure the heavy lifting will have to be done sooner or later... might as well be sooner. It should be straightforward to convert everything later, anyways.

I’ll try to keep commits atomic and clear to aid in reviewing. Thanks in advance!
