### ISSUE TITLE
Add NotImplementedType and tighten NotImplemented type

### ISSUE THREAD

**Issue by llchan** [python/typeshed#2929]
We curently have
https://github.com/python/typeshed/blob/fd57aee5dae21bd962f9df5d0d1c427ff96c3670/stdlib/2and3/builtins.pyi#L1096
but `type(NotImplemented)` is actually a built-in `NotImplementedType`.  As far as I can tell, `NotImplementedType` is not exposed anywhere in PY3 at static analysis time.  We should add that and also tighten the type of `NotImplemented` so that we can type special methods more precisely.  Otherwise it's difficult to distinguish between a special method that truly returns anything and one that always returns `NotImplemented`.

**Comment by JelleZijlstra** [comment]
The current `Any` type is intentional and changing it is problematic; see Guido's comments in python/mypy#6710. As the discussion there makes clear, it's not clear that the changes proposed in this issue are going to be net positives.

**Comment by llchan** [comment]
Yeah, this was ticket was filed before the responses in the other ticket indicated that this was intentional.  If you prefer to close this ticket and re-open if/when it becomes relevant again, feel free to do so.

**Comment by srittau** [comment]
I am going to close this for now. Thanks!
