### ISSUE TITLE
Function FunctionType.__init__ expects 1 arg(s), got 6 [wrong-arg-count]

### ISSUE THREAD

**Issue by benjolitz** [python/typeshed#2930]
The `__init__` for FunctionType inside types.py is incomplete.

Specifically, it lacks the following signature for the constructor:
```
    def __init__(self, code: CodeType, globals: dict, name: str, argdefs: dict, closure: _Cell) -> None: ...
```

Upon adding this definition and moving the type definition to below `CodeType`, pytype was able to type check the function appropriately.

**Comment by srittau** [comment]
Patches welcome. The definition above needs a few tweaks (such as optional parameters)., though.
