### ISSUE TITLE
itertools.combinations should return Iterator instead of Iterable

### ISSUE THREAD

**Issue by vaibhavkarve** [python/typeshed#2931]
Currently, all the functions in itertools.pyi have a return type of Iterator except for
`itertools.combinations` and `itertools.combinations_with_replacement`. Here are the relevant lines from the file:
```
def combinations(iterable: Iterable[_T],
                 r: int) -> Iterable[Tuple[_T, ...]]: ...
def combinations_with_replacement(iterable: Iterable[_T],
r: int) -> Iterable[Tuple[_T, ...]]: ...
```
I think the only change that needs to be made is to replace `Iterable` with `Iterator` (but I haven't really tried changing it).

**Comment by srittau** [comment]
Good catch! The Python 2 stubs actually have a return type of `Iterator` already, while the Python 3 stubs have the wrong one. Patches welcome.
