### ISSUE TITLE
Type definition for Enum is missing some attributes

### ISSUE THREAD

**Issue by jetpacktuxedo** [python/typeshed#2934]
The [attribute definition](https://github.com/python/typeshed/blob/master/stdlib/3/enum.pyi#L23-L27) skips a few attributes. For example [`_member_map_`](https://github.com/python/cpython/blob/8b914d2767acba3a9e78f1dacdc2d61dbfd7e304/Lib/enum.py#L166) and [`_value2member_map_`](https://github.com/python/cpython/blob/8b914d2767acba3a9e78f1dacdc2d61dbfd7e304/Lib/enum.py#L176).

**Comment by srittau** [comment]
Patches are welcome, but should include the `# undocumented` flag.
