### ISSUE TITLE
logging.config.listen returns None

### ISSUE THREAD

**Issue by Palpatineli** [python/typeshed#2938]
According to the 3.7 doc
logging.config.listen:
> Returns a Thread instance on which you can call start() to start the server, and which you can join() when appropriate. 

However in
[stdlib/2and3/logging/config.pyi](stdlib/2and3/logging/config.pyi)
It returns None for both version > 3.4 and version < 3.4.

The actual error message is thus "'listen' does not return a value". I assume this is a bug and not intentional?

**Comment by JelleZijlstra** [comment]
Sounds like a bug yes. Patches are welcome!

**Comment by utkarsh2102** [comment]
@JelleZijlstra, I am confused. Given the docs, should it be `Any` instead?

**Comment by JelleZijlstra** [comment]
Sounds to me like it returns a `threading.Thread`.
