### ISSUE TITLE
pyexpat.ExpatError.code contains str on Py < 3.2

### ISSUE THREAD

**Issue by gsnedders** [python/typeshed#2939]
This was a change in 3.2

**Comment by srittau** [comment]
I can't reproduce this with Python 2.7:

```python
>>> import pyexpat
>>> parser = pyexpat.ParserCreate()
>>> try:
...     parser.Parse(b"xxx", True)
... except Exception, e:
...     print(type(e.code))
... 
<type 'int'>
```

**Comment by gsnedders** [comment]
Oh, have I just been thrown off by the docs, which say:

> Expat’s internal error number for the specific error. This will match one of the constants defined in the errors object from this module.

`pyexpat.errors` contains strings (e.g., `pyexpat.errors.XML_ERROR_ABORTED` is `'parsing aborted'`), which in my view doesn't match an internal error number!
