### ISSUE TITLE
traceback has incomplete and incorrect stubs

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/typeshed#294]
The stubs for the standard library module `traceback` in python 3 (see [stdlib/3/traceback.pyi](https://github.com/python/typeshed/blob/master/stdlib/3/traceback.pyi)) are incomplete.

I also think some annotations in [stdlib/2.7/traceback.pyi](https://github.com/python/typeshed/blob/master/stdlib/2.7/traceback.pyi) are wrong as they don't use `Optional` for parameters that can be `None`. For example, according to [docs](https://docs.python.org/2/library/traceback.html#traceback.print_stack), `traceback.print_stack`'s `limit` argument can be `None` but limit is typed as `int` in stubs for 2.7. This is wrong because it would break the [planned feature of type checking `None`](https://github.com/python/mypy/blob/master/docs/source/planned_features.rst#type-checking-of-none)

**Comment by euresti** [comment]
Fixed by #465?

**Comment by sharmaeklavya2** [comment]
I reported this issue because I wanted to annotate some code which used the `traceback` module. But now I have forgotten where I wanted to do that and I have no way of verifying whether the current stubs are correct. So I think we can safely close this issue.
