### ISSUE TITLE
Unknown `__init__` arguments of `click.Choice` in subclass

### ISSUE THREAD

**Issue by konradkonrad** [python/typeshed#2942]
Not 100% sure, if this is the right place to report this.

It seems, that `mypy` fails to find the keyword arguments of `click.Choice.__init__`.

Example:
```python
from click import Choice


class MyChoice(Choice):
    def __init__(self, case_sensitive: bool = True):
        super().__init__(['a'], case_sensitive=case_sensitive)
```
mypy reports:
```
clicktest.py:6: error: Unexpected keyword argument "case_sensitive" for "__init__" of "Choice"
```

Environment:
```
mypy==0.701
mypy-extensions==0.4.1
Click==7.0
Python 3.7.3 (default, Mar 26 2019, 21:43:19)
```

**Comment by JelleZijlstra** [comment]
Yes, the `Choice` constructor is here: https://github.com/python/typeshed/blob/master/third_party/2and3/click/types.pyi#L30. I'm guessing this argument was added recently since I don't see it in Click 6.7.

**Comment by utkarsh2102** [comment]
@JelleZijlstra, yep!
Check here: https://github.com/pallets/click/blob/master/CHANGES.rst
Introduced in 7.x.
