### ISSUE TITLE
'sys' module has no attribute breakpointhook

### ISSUE THREAD

**Issue by Yobmod** [python/typeshed#2979]
Hi,
Per the title, i get a mypy error for the valid (3.7+) code:

```
import sys
sys.breakpointhook = lambda *x: None
```

--> 'sys' module has no attribute breakpointhook

Trying to edit the sys stub myself seems too risky for me!

**Comment by JelleZijlstra** [comment]
Patches are welcome, don't be scared :)

**Comment by Yobmod** [comment]
ok, I tried doing it myself. I just typed it according to the python docs though, my C is too old to be sure that matches sysmodule.c.
#2991
