### ISSUE TITLE
cmath module has no attribute "isclose"

### ISSUE THREAD

**Issue by sutorei** [python/typeshed#2984]
Looks like the stub for `isclose` is missing from `cmath` while being present in regular `math`. Probably copying it over should be enough.

**Comment by srittau** [comment]
Patches welcome!

**Comment by Hanaasagi** [comment]
And following is missing too.

```
[
    "inf",
    "infj",
    "isclose",
    "nan",
    "nanj",
    "tau"
]
```

I will work on this.
