### ISSUE TITLE
csv module typing of dialect parameters is not consistently correct

### ISSUE THREAD

**Issue by strubbly** [python/typeshed#2987]
This code

    import csv

    d = csv.excel
    d = csv.Sniffer().sniff("a")

    with open('eggs.csv', newline='') as csvfile:
        spamreader = csv.DictReader(csvfile, dialect=csv.excel)

gives me two errors:

    testmypy.py:4: error: Incompatible types in assignment (expression has type "Dialect", variable has type "Type[excel]")
    testmypy.py:7: error: Argument "dialect" to "DictReader" has incompatible type "Type[excel]"; expected "Union[str, Dialect]"

The problem seems to be that some bits of the stub for `csv` use type `Dialect` when they should be using `type[Dialect]`.  The return of `sniff` is one and so is the type of the `dialect` argument to the `DictReader` constructor.  There may be more ...

I'm using Python 3.7.3 and mypy 0.701 but I think the problems are general.

**Comment by srittau** [comment]
Patches welcome!

**Comment by Hanaasagi** [comment]
I think the return type of `Sniffer.sniff` should be `Type[Dialect]` instead of `Dialect`

https://github.com/python/typeshed/blob/6061ca404e6d4dc072e7f7f84ec1ca7f1456b40a/stdlib/2and3/csv.pyi#L92

From the doc, https://docs.python.org/3/library/csv.html#csv.Sniffer.sniff

>  sniff(sample, delimiters=None)
> 
>  Analyze the given sample and return a `Dialect` subclass reflecting the parameters found. If the optional delimiters parameter is given, it is interpreted as a string containing possible valid delimiter characters.

Test Code here

```Python
In [4]: import csv

In [5]: csvfile = open('example.csv')

In [6]: dialect = csv.Sniffer().sniff(csvfile.read(1024))

In [7]: import inspect

In [8]: inspect.isclass(dialect)
Out[8]: True

In [9]: dialect.__mro__
Out[9]: (csv.Sniffer.sniff.<locals>.dialect, csv.Dialect, object)
```
