### ISSUE TITLE
argparse add_argument's type should allow Callable[[AnyStr], _T]

### ISSUE THREAD

**Issue by orinatic** [python/typeshed#2988]
I have the following code: 
```python
    parser.add_argument("-L", "--loglevel", default="INFO",
                        type=string.upper,
                        help="Set log level output. (e.g., --log-level DEBUG)")
```

This fails to type-check because string.upper is ```Callable[[AnyStr], AnyStr]```, while the annotation for the type field is ```type: Union[Callable[[str], _T], FileType] = ...```.

I think it should be ```type: Union[Callable[[AnyStr], _T], FileType] = ...```?

**Comment by srittau** [comment]
Full test case (Python 2):

```python
import string
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("-L", "--loglevel", type=string.upper)
```
Probably the type should be `Union[Callable[[Text], _T], FileType]` or even `Union[Callable[[Text], _T], Callable[[str], _T], FileType]`. A lone `AnyStr` has no meaning. Patches welcome!

**Comment by utkarsh2102** [comment]
I think that latter would make more sense (at least does to me :P).  
I'll send a PR for the same.
