### ISSUE TITLE
urlparse can be passed None

### ISSUE THREAD

**Issue by PeterJCLaw** [python/typeshed#2990]
It looks like the type signature for the `urllib.parse.urlparse` method isn't quite right:

``` python
# /tmp/url.py
import urllib.parse

META = {'a': 'b'}
referer = META.get('HTTP_REFERER')
print(urllib.parse.urlparse(referer).path)  # prints: b''
```
```
$ mypy /tmp/url.py 
/tmp/url.py:5: error: Argument 1 to "urlparse" has incompatible type "Optional[str]"; expected "str"
```

This feels like a simple fix (I'd be happy to put up a PR), but not sure if there's some reason this is like this?

**Comment by JelleZijlstra** [comment]
The following also works at runtime:
```
In [33]: urllib.parse.urlparse(0.0)
Out[33]: ParseResultBytes(scheme=b'', netloc=b'', path=b'', params=b'', query=b'', fragment=b'')
```
This seems like an implementation accident to me. The documentation (https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) isn't explicit on the desired input type, but the argument is called `urlstring`, so I think it's safe to assume that `str` is the expected input type.

We could allow `None` if it's a common use case to pass None to this function and expect it to work, but I'm not sure it's worth it.

**Comment by srittau** [comment]
Related to #2394.

**Comment by PeterJCLaw** [comment]
Interesting regarding falsey values of other types. I agree that it doesn't make sense for the type signature to allow those. (Truthy values of other types mostly result in `AttributeError`s being raised).

Having looked at the source for `urlparse`, I agree its handling of falsey values is a little unusual. It's mostly trying to cope with being passed either `str` or `bytes`, though does have some falsey checks which hint that it might also be guarding against `None`.

There turns out to be a slightly complication to allowing `None` -- the return type is the `bytes` variant of the returned tuple, rather than the `str` variant. This could result in some slightly unexpected behaviour if users do pass `None` here. Testing out a modified typeshed, `mypy` can indeed correctly handle the merging of overloads (given a call to `urlparse` with `Optional[str]`, the return type is a union of `ParseResult` and `ParseResultBytes`), so we could support this correctly.

On the one hand, if we disallow it then users who find that it actually "works" might be inclined to `type: ignore` the typing error and could later get bitten by the `None` case (arguably what they've asked for).
On the other hand, if we allow it then users who try it do at least get back a type signature which is correct and protects their later code (that might otherwise assume that it was always going to get `str`s).

I'm not sure if that ends up being an argument in favour of allowing `None` or not, though I think it's marginally in favour of supporting `None` being passed.

I'd be interested to hear if others have existing code which is passing either `None` or (I assume more likely) `Optional[str]` to `urlparse`, to help guide this.
For reference: the codebase I found this in is fairly large, but uses Django so doesn't tend to do much with urls directly; it had one instance of this.

**Comment by JelleZijlstra** [comment]
We now have
```python
@overload
def urlparse(url: str, scheme: str | None = ..., allow_fragments: bool = ...) -> ParseResult: ...
@overload
def urlparse(url: bytes | None, scheme: bytes | None = ..., allow_fragments: bool = ...) -> ParseResultBytes: ...
```
so this is fixed.
