### ISSUE TITLE
Remove `function` from builtins

### ISSUE THREAD

**Issue by davidhalter** [python/typeshed#2999]
There's a `class function` in `builtins.pyi`. There's also a mention to remove it: `# TODO not defined in builtins!`. I feel like this was probably created for mypy? As an alternative I would suggest using `types.pyi`'s `FunctionType`.

I personally have to patch typeshed to remove this for Jedi. Why is this there and is it still needed? I'm happy to create a PR for this.

**Comment by davidhalter** [comment]
These are the test results for mypy if you try to remove it: https://travis-ci.org/davidhalter/typeshed/jobs/534417186. I'm still in favor of removing it. mypy is by far not the only software using typeshed.

**Comment by JelleZijlstra** [comment]
> mypy is by far not the only software using typeshed.
But it is among the most important users. We're not going to just break one of our most important current users.

There is an existing issue for this in mypy: python/mypy#3171. That issue will have to be addressed first before we can remove it from typeshed.

**Comment by AlexWaygood** [comment]
Closing as we now have #7580, and I don't think we need both issues to be open when they're about the same thing
