### ISSUE TITLE
Stub versioning

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#3]
Several people have expressed interest in versioning stub files.

Here are some reasons:

* A library maintainer is worried that stubs maintained by 3rd parties for his or her library will get out of date, and people will complain to the library maintainer instead of the one who maintains the stubs.
* A new version of a library breaks compatibility with earlier versions and it's no longer possible to use the same stub with all version of the library in any meaningful way.

**Comment by vlasovskikh** [comment]
TypeScript guys have created a set of tools for managing their stubs:

* https://github.com/DefinitelyTyped/tsd

This is [their contribution guide](http://definitelytyped.org/guides/contributing.html).

**Comment by matthiaskramm** [comment]
I like the TypeScript approach of putting the version into the file name. If we do the same thing, we might have something like 
  typeshed/python3/dist-packages/numpy-1.8.2.pyi

**Comment by gvanrossum** [comment]
Closing. We now have a policy for this.
