### ISSUE TITLE
PyPI lists an unmaintained version of typeshed

### ISSUE THREAD

**Issue by Apteryks** [python/typeshed#3001]
I was confused to find that this package: https://pypi.org/project/typeshed doesn't correspond to this repository. It seems it was made by the original author of typeshed, but has since been abandoned.

Could it be possible to make this copy of typeshed distributable through PyPI and supersede the current "typeshed" package found on PyPI? This would reduce confusion.

Thanks!

**Comment by srittau** [comment]
Distributing typeshed per pypi is quite a bit of work for not much gain, since typeshed is currently being vendored by type checkers. Since both the Python typing standards as well as the typecheckers are evolving fast, this situation is unlikely to change in the near future.

That said, there are some preliminary ideas about shipping third-party packages separately in #2491.

The typeshed project on pypi is not supported or endorsed by the typeshed maintainers, as far as I know.

**Comment by JelleZijlstra** [comment]
Several of the people on the typeshed package are still active in typeshed, so presumably we can at least get control of the package if and when we need it.

**Comment by Apteryks** [comment]
My use case is packaging typeshed for GNU Guix, a functional package manager. It is easy in this context to refer to a single, easy to update/maintain typeshed package rather than having it bundled at many places, such as with mypy, python-jedi, etc.

The work of packaging it is already done and can be retrieved from this branch: https://github.com/graingert/typeshed. Basically, copying three files from that branch into this project should make it packageable: MANIFEST.in, setup.cfg and setup.py.

The benefit this brings is that other Python packages can now refer to typeshed as a proper dependency (with versions if the need arise) instead of having to bundle it.

The API is very simple:

`import typeshed`

then using the "typeshed" symbol yields the location (path) of the root of the typeshed files. It simplifies locating typeshed and removes the need of a hardcoded path from the projects referring to it.

**Comment by srittau** [comment]
For reference, there are plans to distribute stubs for third-party packages as separate packages (see #2491). It would make some sense to then distribute the stdlib stubs as their own package as well, although type checkers may still opt to vendor them. In this case a `typeshed` package would not make much sense anymore.

**Comment by di** [comment]
Hi folks, PyPI administrator here. We got a request to remove this project from PyPI as it's confusing for users (https://twitter.com/okapies/status/1225604759752601600, https://github.com/pypa/pypi-support/issues/192).

What would you like to do here?

**Comment by JelleZijlstra** [comment]
I think it makes sense to remove the package. However, we should avoid opening up the hame, because that would make the name available to squatters.

**Comment by di** [comment]
Yes, we can also put a block on the name so it cannot be registered.

**Comment by di** [comment]
I've removed the project and blocked the name from being registered, this can be closed.

**Comment by srittau** [comment]
Thanks!
