### ISSUE TITLE
`MapResult` object is multiprocessing library is of wrong typing. 

### ISSUE THREAD

**Issue by yech1990** [python/typeshed#3006]
> moved from https://github.com/python/mypy/issues/6883

```python
import multiprocessing
import time


def worker(i):
    time.sleep(1)
    return f"hello {i}"


with multiprocessing.Pool(processes=8) as pool:
    result_objs = pool.map_async(worker, list(range(10)))
    while not result_objs.ready():
        print(f"num left: {result_objs._number_left}")
        time.sleep(0.2)
```

The code works fine, and the type if `map_async` return is `<class 'multiprocessing.pool.MapResult'>`, but mypy report this error message.

```shell
test_pool.py:25: error: "ApplyResult[List[Any]]" has no attribute "_number_left"
```

**Comment by yech1990** [comment]
https://github.com/python/cpython/blob/7c994549dcffd0d9d3bb37475e6374f356e7240e/Lib/multiprocessing/pool.py#L786

**Comment by srittau** [comment]
`Pool.map_async()` should return a `MapResult`, which does not yet exist in the stubs. Patches welcome!

**Comment by utkarsh2102** [comment]
@srittau, by taking a quick look it seems that an `__init__` method should be under `MapResult`.
However, I am not sure how to go about fixing this.
Could you help me understand how to include it in the stub?

**Comment by Hanaasagi** [comment]
I'm working on it.
