### ISSUE TITLE
re's Match does not support indexing: "Value of type "Optional[Match[str]]" is not indexable"

### ISSUE THREAD

**Issue by blueyed** [python/typeshed#3010]
The following is valid, but mypy complains about it:
```python
import re

m = re.search(".", "foo")
print(m[0])
```

> t-mypy.py:4: error: Value of type "Optional[Match[str]]" is not indexable

Seems to be similar to https://github.com/python/typeshed/issues/2751 (https://github.com/python/typeshed/pull/2753).

`mypy 0.710+dev.5f08ccf029aa3046b15e1afc60743ba692e4758d.dirty` (dirty due to using latest typshed master (53500c8750aaf46e05e30300d210944fc9298da6)

**Comment by JelleZijlstra** [comment]
That's because of the Optional part. It's telling you that if there is no match, this code will break. Mypy will show no errors if you first check that `m is not None`.

**Comment by blueyed** [comment]
@JelleZijlstra 
Thanks - figured this out with something else already (forgot to report back here).
`assert m` also works.

**Comment by dongweiming** [comment]
@JelleZijlstra if use `Assignment expressions` will  an error:
 
```
❯ cat a.py 
import re

if (m := re.search(".", "foo")):
    print(m[0])

❯ mypy a.py 
a.py:4: error: Value of type "Optional[Match[str]]" is not indexable
        print(m[0])
              ^
Found 1 error in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
This is a mypy problem:

```python
from typing import Optional

def foo() -> Optional[str]:
    pass

x = foo()
if x:
    x.lower()  # no error
    
if (y := foo()):
    y.lower()  # error: Item "None" of "Optional[str]" has no attribute "lower"
```

(mypy 0.761 with Python 3.8.0)

**Comment by JelleZijlstra** [comment]
Yes, python/mypy#7316.
