### ISSUE TITLE
Using multiprocessing manager as context manager returns the wrong value

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#3018]
When I use from `Manager` from multiprocessing as a context manager, the returned value is wrong. Example:

```python
from multiprocessing import Manager
with Manager() as m:
    reveal_type(m)
```

Output from mypy:
```
test.py:3: error: Revealed type is 'multiprocessing.managers.BaseManager*'
```

This is a problem as the `BaseManager` class misses many methods, such as `Queue`.

**Comment by JelleZijlstra** [comment]
Patches welcome! Presumably the `__enter__` method should be typed as `def __enter__(self: _T) -> _T:`.

**Comment by utkarsh2102** [comment]
@JelleZijlstra, I am assuming you're talking about `multiprocessing.pool.__enter__`, right?

**Comment by libre-man** [comment]
This is still a problem when you subclass `SyncManager`. An example:

```python
from multiprocessing import managers

class MyManager(managers.SyncManager):
    pass

with MyManager() as m:
    reveal_type(m)  # note: Revealed type is 'multiprocessing.managers.BaseManager*'
```
