### ISSUE TITLE
Update type hints for click 7.x?

### ISSUE THREAD

**Issue by cs-shadow** [python/typeshed#3020]
The current type hints for [`click`](https://github.com/python/typeshed/tree/master/third_party/2and3/click) are tagetting version 6.6. Click 7.0 was released last year and added a bunch of new features. Full changelog [here](https://click.palletsprojects.com/en/7.x/changelog/#version-7-0).

I was wondering if you would be open to updating the type hints corresponding to 7.x series of `click`? I would be happy to submit a patch for that, but I was not sure about which upstream releases this package follows, so thought about asking here first.

Also, in case it matters, Click 7.0 dropeed support for Python 2.6 and 3.3.

**Comment by srittau** [comment]
Generally, typeshed aims to follow the current release, although things are a bit murky. In the long run we probably need a was the to support multiple versions of a library.

Patches to update click stubs are certainly welcome, though!

**Comment by cs-shadow** [comment]
Thanks for the explanation!

I have submitted #3027 to update click stubs.
