### ISSUE TITLE
asyncio.Protocol connection_made should be Transport instead of BaseTransport

### ISSUE THREAD

**Issue by isidentical** [python/typeshed#3021]
```py
    def connection_made(self, transport: asyncio.transports.Transport):
        ...
```
Raises `Argument 1 of "connection_made" incompatible with supertype "BaseProtocol"`. And when we change to `BaseProtocol's type` (`BaseTransport`) it raises `error: "BaseTransport" has no attribute "write"`.

**Comment by srittau** [comment]
I don't think there is anything in typeshed that can be done. `BaseProtocol` sub-classes that implement `connection_made()`, but expect a sub-class of `BaseProtocol` should use `# type: ignore` to suppress this kind of warning.
