### ISSUE TITLE
_UrlopenRet gives error that addinfourl has no attribute status

### ISSUE THREAD

**Issue by ThrowsException** [python/typeshed#3026]
`_UrlopenRet` is defined `_UrlopenRet = Union[_HTTPResponse, addinfourl]` but `addinfourl` has to attribute status so when checking the status of an HTTPResponse you receive ` error: Item "addinfourl" of "Union[HTTPResponse, addinfourl]" has no attribute "status"
`

https://github.com/python/cpython/blob/3.7/Lib/urllib/response.py#L68-L80

**Comment by srittau** [comment]
`_UrlopenRet` should probably just be changed to `Any`, until something like python/typing#566 is implemented.
