### ISSUE TITLE
collections.abc.KeysView(foo) throws error

### ISSUE THREAD

**Issue by gsnedders** [python/typeshed#3029]
e.g., 

```
tools/manifest/typedata.py:228: error: Too many arguments for "KeysView"
```

See also this CPython issue: [collections.abc.MappingView mixins rely on undocumented _mapping](https://bugs.python.org/issue37145).

Now, relying on undocumented CPython behaviour is in many ways bad, but it does mean that anyone using MappingView needs to reimplement all the mixins given the default implementations rely on undocumented behaviour…

**Comment by srittau** [comment]
Sorry, I don't understand what the issue is. Can you give an example line of code that does not type check, although it should? For example `tools/manifest/typedata.py:228` mentioned above?

**Comment by gsnedders** [comment]
@srittau 

```
from collections.abc import KeysView
x = {}

view = KeysView(x)
```

This is because the `typing` definition of `MappingView` doesn't define an `__init__`, unlike that in CPython's `collections.abc`.

**Comment by srittau** [comment]
Thank you for the explanation. It seems that typeshed's `collections.abc.MappingView` et al. are just aliases for `typing.MappingView`, so this isn't too easy to solve. It might be best to have custom versions in `collections/abc.pyi` and fix there. (Or to actually follow stdlib and have a `_collections_abc.pyi` stub and import from there.)

**Comment by ateraz** [comment]
I have a similar issue. Running `mypy --disallow-any-generics test.py` produces
```
test.py:3: error: Missing type parameters for generic type "Iterable"
test.py:4: note: Revealed type is 'typing.Iterable[Any]'
```
when running on the following file:
```
import collections.abc

t: collections.abc.Iterable
reveal_type(t)
```

**Comment by mthuurne** [comment]
The following patch should make the errors about the constructor argument disappear:
```diff
--- a/typeshed/stdlib/3/typing.pyi	2019-12-05 04:17:27.201162529 +0100
+++ b/typeshed/stdlib/3/typing.pyi	2019-12-05 04:05:35.185450131 +0100
@@ -340,9 +338,11 @@
     def __isub__(self, s: AbstractSet[Any]) -> MutableSet[_T]: ...
 
 class MappingView:
+    def __init__(self, mapping: Mapping[Any, Any]) -> None: ...
     def __len__(self) -> int: ...
 
 class ItemsView(MappingView, AbstractSet[Tuple[_KT_co, _VT_co]], Generic[_KT_co, _VT_co]):
+    def __init__(self, mapping: Mapping[_KT_co, _VT_co]) -> None: ...
     def __and__(self, o: Iterable[Any]) -> Set[Tuple[_KT_co, _VT_co]]: ...
     def __rand__(self, o: Iterable[_T]) -> Set[_T]: ...
     def __contains__(self, o: object) -> bool: ...
@@ -357,6 +357,7 @@
     def __rxor__(self, o: Iterable[_T]) -> Set[Union[Tuple[_KT_co, _VT_co], _T]]: ...
 
 class KeysView(MappingView, AbstractSet[_KT_co], Generic[_KT_co]):
+    def __init__(self, mapping: Mapping[_KT_co, Any]) -> None: ...
     def __and__(self, o: Iterable[Any]) -> Set[_KT_co]: ...
     def __rand__(self, o: Iterable[_T]) -> Set[_T]: ...
     def __contains__(self, o: object) -> bool: ...
@@ -371,6 +372,7 @@
     def __rxor__(self, o: Iterable[_T]) -> Set[Union[_KT_co, _T]]: ...
 
 class ValuesView(MappingView, Iterable[_VT_co], Generic[_VT_co]):
+    def __init__(self, mapping: Mapping[Any, _VT_co]) -> None: ...
     def __contains__(self, o: object) -> bool: ...
     def __iter__(self) -> Iterator[_VT_co]: ...
     if sys.version_info >= (3, 8):
```
However, the `mapping` constructor argument is undocumented: there is no mention of it on `docs.python.org`. If you run `help(MappingView)` you will see it, but that's generated by introspection rather than by explicit documentation.

On the other hand, in the previously linked [BPO 37145](https://bugs.python.org/issue37145), Raymond Hettinger states that "dunder" methods like `__init__` are considered public, in which case it should be valid to call them.

So I'm not sure whether this argument should be added to typeshed. If you think it should be added, I can make a PR for it.

**Comment by srittau** [comment]
We usually include undocumented items in typeshed if they are used, but mark them with `# undocumented`. PR welcome!

**Comment by mthuurne** [comment]
The PR was submitted and passed CI.
