### ISSUE TITLE
Is the stdlib class abc.ABC missing in stub file for python 3.4+ ?

### ISSUE THREAD

**Issue by haakenlid** [python/typeshed#304]
mypy gives me an error when I try to subclass [`abc.ABC`](https://docs.python.org/3/library/abc.html#abc.ABC) from the standard library in python 3.5

> error: Module has no attribute 'ABC'

This class was added in python 3.4 

I couldn't find the documentation of how the pyi-file lookup works, but I would expect to find a stub for `abc.ABC` in `typeshed/stdlib/3.4/abc.pyi`, or something like that. There's no such file, but there is one called [`typeshed/stdlib/3/abc.pyi`](https://github.com/python/typeshed/blob/master/stdlib/3/abc.pyi)

Is this class missing from typeshed, or have I misunderstood how the stub files work?

**Comment by matthiaskramm** [comment]
Yes, https://github.com/python/typeshed/blob/master/stdlib/3/abc.pyi is the file mypy is using for Python 3.5. It doesn't seem to contain ABC yet. Could you submit a PR?

**Comment by haakenlid** [comment]
There are some other stuff missing from this module as well. 
`abc.get_cache_token()` was added in 3.4
`@abc.abstractclassmethod `and `@abc.abstractstaticmethod` were added in 3.2, but then deprecated in 3.3. But I guess they still should be included in the stubs?
