### ISSUE TITLE
Support TextIOWrapper.reconfigure()

### ISSUE THREAD

**Issue by grantwwu** [python/typeshed#3049]
I'm getting a

```
"TextIO" has no attribute "reconfigure"
```
 error for 
```
sys.stdin.reconfigure(encoding="latin-1")
```

It's a new Python 3.7 feature.  Was informed in Gitter that this hadn't been added to Typeshed yet and to open a ticket for it.

See https://docs.python.org/3/whatsnew/3.7.html#io

**Comment by srittau** [comment]
Currently `sys.stdin` et al. are typed as `TextIO`, not `TextIOWrapper`. This would need to be changed as well, although I am not sure that this does not cause complications. But adding `TextIOWrapper.reconfigure()` would be welcome in any case.

**Comment by serhiy-storchaka** [comment]
For the following code
```python
import sys, io

if isinstance(sys.stdout, io.TextIOWrapper) and sys.version_info >= (3, 7):
    sys.stdout.reconfigure(errors="replace")
```
I get the error:
```
reconfigure37.py:4: error: "TextIOWrapper" has no attribute "reconfigure"
```
MyPy understand that `sys.stdout` is a `TextIOWrapper` instance.

**Comment by serhiy-storchaka** [comment]
What is worse -- I cannot silence the error by adding `# type: ignore`, because on Python 3.6 I get `error: unused 'type: ignore' comment`.

**Comment by grantwwu** [comment]
I haven't touched MyPy in many months but your platform check might be too complex for https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks to understand. Try splitting it into two `if`s?

**Comment by srittau** [comment]
FWIW, I just checked the following with mypy 0.770 using `--warn-unused-ignores` under both Python 3.6.9 and 3.7.4 and it works or me:

```python
import sys, io

if isinstance(sys.stdout, io.TextIOWrapper) and sys.version_info >= (3, 7):
    sys.stdout.reconfigure(errors="replace")  # type: ignore
```

That said, we'll gladly accept a PR that adds `TextIOWrapper.reconfigure()` :)

**Comment by serhiy-storchaka** [comment]
It is the same if split on two `if`s.
