### ISSUE TITLE
`importlib.util.spec_from_file_location` accepts `pathlib.Path`s

### ISSUE THREAD

**Issue by thejohnfreeman** [python/typeshed#3052]
I don't know in what version of Python this started, but `importlib.util.spec_from_file_location` accepts a `pathlib.Path` as the second argument, not just a `str` as mypy 0.701 seems to believe. Probably a quick fix for someone who knows the codebase better.

**Comment by srittau** [comment]
Added in 3.6 according to the [docs](https://docs.python.org/3/library/importlib.html). Patches welcome!

**Comment by thejohnfreeman** [comment]
@srittau If you can point me to the source file where `spec_from_file_location` is typed, and to the preferred `PathLike` or whatever type we need, I'll happily make the pull request.

**Comment by srittau** [comment]
@thejohnfreeman `spec_from_file_location` is typed in [master/stdlib/3/importlib/util.pyi](https://github.com/python/typeshed/blob/5327484176f7d56dc72e68fc04f03bd3fd2cabdb/stdlib/3/importlib/util.pyi#L33). An example of how to type something like this, including the necessary version check can be found [here](https://github.com/python/typeshed/blob/5327484176f7d56dc72e68fc04f03bd3fd2cabdb/stdlib/3/os/__init__.pyi#L292).
