### ISSUE TITLE
No stubs for wrapper/descriptor types

### ISSUE THREAD

**Issue by CraftSpider** [python/typeshed#3064]
The types.py file has four types, listed below, that don't have any stubs at all. At least one of these is used in the `inspect` modules, and the lack of these stubs makes writing more reflection code and such quite annoying. 

* `WrapperDescriptorType`
* `MethodWrapperType`
* `MethodDescriptorType`
* `ClassMethodDescriptorType`

I'd be willing to make and PR a fix, if others agree that these types should be added.

**Comment by JelleZijlstra** [comment]
We should definitely add these. Patches are welcome!
