### ISSUE TITLE
Missing stubs for configparser in python 2 and six

### ISSUE THREAD

**Issue by timabbott** [python/typeshed#307]
While #116 added configparser for Python 3, it looks like we're still missing configparser on Python 2, and also six.moves.configparser.

**Comment by euresti** [comment]
Unless you're talking about something else in Python 2 it's called ConfigParser and it's there now.
And I just added it to six.moves in https://github.com/python/typeshed/pull/937

**Comment by timabbott** [comment]
Nice, yeah, I think #937 resolves this.
