### ISSUE TITLE
Why does `__slots__` allow a plain string?

### ISSUE THREAD

**Issue by kamahen** [python/typeshed#3079]
The definition for `object.__slots__` in `stdlib/2and3/builtins.pyi` is
```python
    __slots__: Union[Text, Iterable[Text]]
```

Why isn't it just `Iterable[Text]`? &mdash; using a string instead of a list of strings is one of the classic mistakes in Python, and we would want type checkers to catch that.

Also, if I understand [mypy standard duck types](https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html#standard-duck-types) correctly, this should be a `Sequence` and not an `Iterable`.

**Comment by brandtbucher** [comment]
This one dates back a while... `"__slots__ = "some_str"` has always created a single slot!

https://bugs.python.org/issue496240

"It's a feature!"

**Comment by CraftSpider** [comment]
I'm not a collaborator, but my thoughts: at least in python 3.7 and 2.7, a plain string works just fine.
```py
class A:
    __slots__ = "test"

A().test = "temp"
```
Works without error, while attempting to assign other attributes fails. However, I would agree that it should be an `Iterable` not a `Sequence`, as any passing any iterator of strings also works correctly.

**Comment by brandtbucher** [comment]
This can probably be closed, I think.
