### ISSUE TITLE
Incorrect typing for click.echo_via_pager

### ISSUE THREAD

**Issue by chronitis** [python/typeshed#3089]
The signature for `click.echo_via_pager` was updated incorrectly in 018ecb3f16867a88986c3c47969cb2779c6a276c (third_party/2and3/click/termui.pyi:65) - the default parameter for the second argument was dropped, so `mypy` is now (incorrectly) reporting a single-argument invocation as wrong.

The signature should correspond to:

    click.echo_via_pager(text_or_generator, color=None)

**Comment by srittau** [comment]
Thanks, patches welcome!

Cc @cs-shadow

**Comment by chronitis** [comment]
@srittau patch in #3090
