### ISSUE TITLE
PurePath methods ask for PurePath instead of os.PathLike[str]

### ISSUE THREAD

**Issue by fcolas** [python/typeshed#3095]
In Python 3.6+, [`PurePath.__truediv__`](https://github.com/python/typeshed/blob/master/stdlib/3/pathlib.pyi#L33) is currently defined as:
```python
def __truediv__(self: _P, key: Union[str, PurePath]) -> _P: ...
```
This prevent typing one's code with `Union[str, os.PathLike[str]]` since we get:
```
Unsupported operand types for / ("Path" and "_PathLike[str]")
```
However, the implementation does seem to accept a `Union[str, os.PathLike[str]]` since it calls [`os.fspath(a)`](https://github.com/python/cpython/blob/master/Lib/pathlib.py#L651). This `_parse_args` method is shared with [`__new__`](https://github.com/python/typeshed/blob/master/stdlib/3/pathlib.pyi#L24-L25), which does accept `Union[str, os.PathLike[str]]`.

Thus it seems to me it that, for Python>=3.6, `__truediv__` should be typed as:
```python
def __truediv__(self: _P, key: Union[str, os.PathLike[str]]) -> _P: ...
```

As far as I understand, it is the same for [`relative_to`](https://github.com/python/typeshed/blob/master/stdlib/3/pathlib.pyi#L42) and, unsurprisingly, [`joinpath`](https://github.com/python/typeshed/blob/master/stdlib/3/pathlib.pyi#L45).

By the way, shouldn't there be a less cumbersome way than `Union[str, os.PathLike[str]]` for type annotation of paths?

**Comment by srittau** [comment]
Sounds reasonable. Patches welcome!
