### ISSUE TITLE
missing annotation for tempfile._TemporaryFileWrapper in Python 3

### ISSUE THREAD

**Issue by redshiftzero** [python/typeshed#3096]
The [Python 2 annotations for `tempfile`](https://github.com/python/typeshed/blob/master/stdlib/2/tempfile.pyi#L20) include `_TemporaryFileWrapper` however in [Python 3's `tempfile` annotations](https://github.com/python/typeshed/blob/master/stdlib/3/tempfile.pyi) there is no corresponding annotation for `_TemporaryFileWrapper`.

**Comment by srittau** [comment]
Patches welcome!
