### ISSUE TITLE
argparse.ArgumentParser.add_argument doesn't allow type=os.path.abspath

### ISSUE THREAD

**Issue by andymwood** [python/typeshed#3107]
Running mypy on this code:
```python
import argparse,  os
reveal_type(os.path.abspath)
p = argparse.ArgumentParser()
p.add_argument("file", type=os.path.abspath)
```
I get:
```bash
mypy args.py 
args.py:2: note: Revealed type is 'Overload(def [AnyStr in (builtins.str, builtins.bytes)] (path: builtins._PathLike[AnyStr`-1]) -> AnyStr`-1, def [AnyStr in (builtins.str, builtins.bytes)] (path: AnyStr`-1) -> AnyStr`-1)'
args.py:4: error: Argument "type" to "add_argument" of "_ActionsContainer" has incompatible type overloaded function; expected "Union[Callable[[str], AnyStr], FileType]"
```
Should the type signature of `add_argument` be changed to allow functions that accept a `PathLike` argument?

**Comment by srittau** [comment]
I assume you are using Python 3.6+. If I'm not mistaken, the stubs are correct. `Callable[[str], _T]` matches the overload `def basename(path: AnyStr) -> AnyStr: ...` and `_T` constrained to `str`. Possibly a not supported edge case in mypy? pytype accepts this.

**Comment by andymwood** [comment]
Ok, thanks for that. I've reported the issue at the python/mypy repo instead.

**Comment by andymwood** [comment]
I'm re-opening this issue following the advice of [this comment](https://github.com/python/mypy/issues/7177#issuecomment-520405554).

**Comment by srittau** [comment]
I still think `add_argument` is typed correctly. Replacing `_T` with `Any` would actually reduce the strictness, since `_T` is deliberately used for both `type` and `choices`. By changing `_T` to `Any`, this wouldn't be caught:

```python
from argparse import ArgumentParser

def to_str(x: str) -> str:
    return x

arg = ArgumentParser()
arg.add_argument(type=to_str, choices=[1])
```

CC @ilevkivskyi

**Comment by ilevkivskyi** [comment]
The fact that mypy currently flags above code is a bug in mypy (quite subtle one). It should infer `_T = object` for the method and accept this call.

For example this code is correctly accepted:
```python
T = TypeVar('T')
def g(x: T, y: T) -> None: ...
g('yes', 42)
```

**Comment by JelleZijlstra** [comment]
Pyright allows the code in the original post and it also looks fine to me with the current stub, so I am going to say this is still a bug in mypy.
