### ISSUE TITLE
curses: export _CursesWindow in `curses/__init__.pyi`?

### ISSUE THREAD

**Issue by asottile** [python/typeshed#3116]
just noticed it's a little clunkier to use curses than I'd like due to the `*` import not including the underscored name (I realize that `_CursesWindow` is also a fake type so it has to be quoted anyway)

Currently I'm writing:

```python
import _curses
import curses


def c_main(stdscr: '_curses._CursesWindow') -> None:
    stdscr.getch()


def main() -> int:
    curses.wrapper(c_main)
    return 0


if __name__ == '__main__':
    exit(main())
```

I'd like to be able to write this instead:

```python
import curses


def c_main(stdscr: 'curses._CursesWindow') -> None:
    stdscr.getch()


def main() -> int:
    curses.wrapper(c_main)
    return 0


if __name__ == '__main__':
    exit(main())
```

**Comment by JelleZijlstra** [comment]
I agree with the proposal. `_CursesWindow` doesn't actually exist at runtime in either module, so in typeshed we might as well make it accessible in non-private module.
