### ISSUE TITLE
SyntaxError.text could be None

### ISSUE THREAD

**Issue by Hanaasagi** [python/typeshed#3118]
We defined `str` in typeshed.

https://github.com/python/typeshed/blob/f76b7b273b732f587a1f05b388dd35091b87523e/stdlib/2and3/builtins.pyi#L1522-L1527

#### How to reproduce it

```Bash
➜ cat t.py 
import ast

text = input()
try:
    ast.parse(text)
except SyntaxError as e:
    print(e.text)
➜ echo 'max(1 for i in range(10), key=lambda x: x+1)' | python t.py
None
```

#### Analysis

Check from Python 3.7 source code.
https://github.com/python/cpython/blob/c6b31061997526b31961ec34328408ca421f51fc/Python/ast.c#L681-L685

```C
    loc = PyErr_ProgramTextObject(c->c_filename, LINENO(n));
    if (!loc) {
        Py_INCREF(Py_None);
        loc = Py_None;
    }
```

https://github.com/python/cpython/blob/c6b31061997526b31961ec34328408ca421f51fc/Python/errors.c#L1203-L1215

```C
PyObject *
PyErr_ProgramTextObject(PyObject *filename, int lineno)
{
    FILE *fp;
    if (filename == NULL || lineno <= 0)
        return NULL;
    fp = _Py_fopen_obj(filename, "r" PY_STDIOTEXTMODE);
    if (fp == NULL) {
        PyErr_Clear();
        return NULL;
    }
    return err_programtext(fp, lineno);
}
```

let us make a special file to confirm

```Bash
➜ echo 'for test' > \<unknown\>
➜ echo 'max(1 for i in range(10), key=lambda x: x+1)' | python t.py
for test

```

**Comment by srittau** [comment]
Thank you for the analysis, patches welcome!
