### ISSUE TITLE
Drop Python 3.4 support

### ISSUE THREAD

**Issue by srittau** [python/typeshed#3123]
Python 3.4 has reached it's end of life, the last version was release in March. mypy has already dropped support for it, I think we should do so as well. I could provide a PR.

**Comment by bluetech** [comment]
Typeshed normally reaches users by being vendored with the type-checkers, right? If so, it makes sense that once the type checkers drop support for a Python version, typeshed will as well -- it no longer benefits anyone.

**Comment by rchen152** [comment]
Do we have any idea what % of Python users are still on 3.4? pytype still supports it, but I'd be comfortable discontinuing support if most users have moved on.

**Comment by sproshev** [comment]
Only 3% of our respondents told that they use Python 3.4 (among the ones using Python 3.x), https://www.jetbrains.com/research/python-developers-survey-2018/#python-3-adoption.

We no longer support it since 2019.1, https://youtrack.jetbrains.com/issue/PY-32814

**Comment by rchen152** [comment]
Thanks! I don't have any objections to dropping 3.4 support then :)
