### ISSUE TITLE
missing multiprocessing.managers BaseProxy

### ISSUE THREAD

**Issue by ikamensh** [python/typeshed#3140]
the https://github.com/python/typeshed/blob/master/stdlib/3/multiprocessing/managers.pyi has no code for the class BaseProxy, which is a public class of multiprocessing.managers .

**Comment by srittau** [comment]
PR welcome!

**Comment by lladhibhutall** [comment]
@srittau I can work on this, I just have to add the functions in `BaseProxy` class stub right?

**Comment by srittau** [comment]
@lladhibhutall Basically yes, although it's probably enough to add just `__init__`, `__deepcopy__`, `__reduce__`, `_callmethod`, and `_getvalue`. The other methods are private and undocumented, so unless someone specifically wants to have them, we don't need to add them.

**Comment by lladhibhutall** [comment]
@srittau How do I understand what is the type of an argument? Is there any trick to it, I am very new to typeshed, also there is a `Token` class mentioned in `__all__` but that is not there in the stub, will also add that.

**Comment by srittau** [comment]
@lladhibhutall Usually a mix of reading the documentation, reading the source code of the implementation, and possibly experiments, with focus on reading the source code.
