### ISSUE TITLE
mypy complains about base64: error: Module has no attribute "binascii"

### ISSUE THREAD

**Issue by dkg** [python/typeshed#3145]
Consider running `mypy` on this python script that confirms whether its first argument is a valid base64-encoded string:

```
#!/usr/bin/python3
import sys
import base64

def test(b: str) -> bool:
    try:
        base64.b64decode(b)
    except base64.binascii.Error as e:
        return False
    return True

if test(sys.argv[1]):
    exit(0)
exit(1)
```

`mypy` produces a warning:
```
test.py:8: error: Module has no attribute "binascii"
```

I don't really understand the `mypy` ecosystem, but i think this is likely just something small missing in typeshed.  Feel free to let me know if i should actually open a different bug against mypy itself.

Thanks for working on typeshed and mypy!  It's really nice to have some form of type-checking in python.

**Comment by Hanaasagi** [comment]
Maybe you can try

```Python
import sys
import base64
import binascii

def test(b: str) -> bool:
    try:
        base64.b64decode(b)
    except binascii.Error as e:
        return False
    return True

if test(sys.argv[1]):
    exit(0)
exit(1)
```

`binascii` is a module imported by `base64`, https://github.com/python/cpython/blob/93e8aa62cfd0a61efed4a61a2ffc2283ae986ef2/Lib/base64.py#L11

**Comment by JelleZijlstra** [comment]
Yes, this only works at runtime by accident. Typeshed shouldn't expose `base64.binascii`.

**Comment by dkg** [comment]
thanks for the feedback and the explanation of why this is happening.  Your suggestion for the right way to fix it works for me.
