### ISSUE TITLE
StringIO:  StringIO[str] has no attribute "len"

### ISSUE THREAD

**Issue by amitsaha** [python/typeshed#316]
The following will report the above error when run via `` mypy --py2``:

```
from StringIO import StringIO
s = StringIO()
s.write('hello')
s.len
```
Am I doing something wrong or Is something missing from https://github.com/python/typeshed/blob/5be96f78d855b270b4e6fe1a3bb9dabcc62c6746/stdlib/2.7/StringIO.pyi?

**Comment by matthiaskramm** [comment]
Yeah, StringIO.pyi is missing

```
len = ...  # type: int
```

Could you submit a PR?

**Comment by amitsaha** [comment]
Sure will do

**Comment by amitsaha** [comment]
Done: https://github.com/python/typeshed/pull/322
