### ISSUE TITLE
Definition of `asyncio.SelectorEventLoop` misses `selector` argument

### ISSUE THREAD

**Issue by sersorrel** [python/typeshed#3165]
The `SelectorEventLoop` can take an optional `selector` argument (see [documentation](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.SelectorEventLoop)):

```python
selector = selectors.SelectSelector()
loop = asyncio.SelectorEventLoop(selector)
```

but the typeshed definition just delegates to `AbstractEventLoop`:

https://github.com/python/typeshed/blob/3c4141982e22aba6966daba5785d1ba959d7fc49/stdlib/3/asyncio/__init__.pyi#L115

which does not take an argument:

https://github.com/python/typeshed/blob/3c4141982e22aba6966daba5785d1ba959d7fc49/stdlib/3/asyncio/events.pyi#L41-L44

so mypy complains at you if you try to pass a selector:

```
error: Too many arguments for "AbstractEventLoop"
```

**Comment by srittau** [comment]
It seems `SelectorEventLoop` should be an alias of either `_WindowsSelectorEventLoop` or `_UnixSelectorEventLoop`, depending on `sys.platform`, both subclasses of `selector_events.BaseSelectorEventLoop`. Patches welcome!

**Comment by Hanaasagi** [comment]
I'll work on it : )
