### ISSUE TITLE
Wrong signature for unix domain socket servers

### ISSUE THREAD

**Issue by nielsbuwen** [python/typeshed#3187]
This is about the `socketserver` module and the classes `UnixStreamServer` and `UnixDatagramServer`.

In `stdlib/3/socketserver.pyi` the signature is reported as follows:

```python
class UnixStreamServer(BaseServer):
        def __init__(self, server_address: Tuple[str, int],
                     RequestHandlerClass: type,
                     bind_and_activate: bool = ...) -> None: ...
```

According to the [documentation](https://docs.python.org/3/library/socket.html#socket-families) the sockets of the `AF_UNIX` family expect a string or bytes-like object and **not** a tuple of string and integer.

> The address of an AF_UNIX socket bound to a file system node is represented as a string, using the file system encoding and the 'surrogateescape' error handler (see PEP 383). An address in Linux’s abstract namespace is returned as a bytes-like object with an initial null byte; note that sockets in this namespace can communicate with normal file system sockets, so programs intended to run on Linux may need to deal with both types of address. A string or bytes-like object can be used for either type of address when passing it as an argument.

So the signatures of both classes should probably look like this:

```python
def __init__(self, server_address: AnyStr, RequestHandlerClass: type, bind_and_activate: bool = ...) -> None: ...
```

The `BaseServer`s signature also expects a `Tuple[str, int]`. But the [documentation](https://docs.python.org/3/library/socketserver.html#socketserver.BaseServer.server_address) states that:

> The format of addresses varies depending on the protocol family;

So maybe make it `Any` or `Union[Tuple[str, int], AnyStr, ...]`.

**Comment by srittau** [comment]
Please note that `AnyStr` is a generic, not an alias for `Union[str, bytes]`, a common error. PRs welcome!
