### ISSUE TITLE
`json` module missing encoder/decoder definitions

### ISSUE THREAD

**Issue by Diggsey** [python/typeshed#319]
Should be as simple as copying them from simplejson?

**Comment by gvanrossum** [comment]
Yeah, just make a PR.

On Wed, Jun 29, 2016 at 6:20 AM, Diggory Blake <notifications@github.com>
wrote:

> Should be as simple as copying them from simplejson?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/python/typeshed/issues/319>, or mute the thread
> <https://github.com/notifications/unsubscribe/ACwrMi0sjYkL3-gA8XCrizl_4-Wqx44yks5qQnEcgaJpZM4JBH8a>
> .
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by gvanrossum** [comment]
Fixed by 0ffe3abf701338b9f63f5be2f79df7149d386769.
