### ISSUE TITLE
Missing node attributes for jinja2

### ISSUE THREAD

**Issue by The-Compiler** [python/typeshed#3197]
It looks like the stubs for jinja2 are missing attributes for its node objects.

For example, this works fine:

```python
import jinja2
import jinja2.nodes

template = jinja2.Environment().parse('{{ foo.bar }}')
nodes = list(template.iter_child_nodes())
nodes = list(nodes[0].iter_child_nodes())
node = nodes[0]
assert isinstance(node, jinja2.nodes.Getattr)
print(node.attr)
print(node.node)
```

but mypy says:

```
x.py:9: error: "Getattr" has no attribute "attr"
x.py:10: error: "Getattr" has no attribute "node"
```

because of:

https://github.com/python/typeshed/blob/b2cd972b1760d850694772fe763e3027f131f223/third_party/2and3/jinja2/nodes.pyi#L160-L164

cc @rowillia who originally added them in #722

**Comment by srittau** [comment]
I guess that's true for all attributes that are added dynamically via the `fields` class var. Patches welcome!

**Comment by utkarsh2102** [comment]
Instead of `Any`, can't we define the `fields` for all the attributes? (45 such declarations at the moment).  
That is something like, `fields = ('node', 'attr', 'ctx')` instead of what it is now?

**Comment by srittau** [comment]
@utkarsh2102 I think this is what we need to do here.

**Comment by The-Compiler** [comment]
FWIW this would be obsoleted by #5423.

**Comment by srittau** [comment]
Closing as the jinja2 stubs will be removed in a few months.
