### ISSUE TITLE
os.PathLike[str] question

### ISSUE THREAD

**Issue by CTrando** [python/typeshed#3202]
Hi, I am an intern working on the python language server project by Microsoft.

I noticed that in the `pathlib.pyi` file, that typeshed uses `os.PathLike[str]` in various places - I checked however and that throws a runtime error in the Python interpreter because `os.PathLike` is not subscriptable, and we are having a hard time parsing the `Path` base class because of that. 

Admittedly, I don't know much about typeshed so I wanted to first ask if that was an issue - I looked around and tried to see if it was a convention - let me know and I'll submit a PR changing it.

Thanks!

**Comment by srittau** [comment]
`PathLike` not being subscriptable at runtime is of course no problem in stub files. To use it in implementation files, the type either needs to be quoted or `from __future__ import annotations` needs to be used on Python 3.7:

```python
def foo(path: "os.PathLike[str]") -> None: ...
```

Python 3.7+:

```python
from __future__ import annotations

def foo(path: os.PathLike[str]) -> None: ...
```

I think there is a general tendency to get rid of typing-specific generics, for example with [PEP 585](https://www.python.org/dev/peps/pep-0585/), so this is probably something to keep in mind.

**Comment by gvanrossum** [comment]
This is intentional. It is fairly common to have classes that are generic in typeshed but not in the stdlib; the intention is that these are only used in type annotations, as shown by srittau (an alternative is to use a type comment).
