### ISSUE TITLE
`requests.Response` is missing `.next`

### ISSUE THREAD

**Issue by jrheard** [python/typeshed#3207]
This field is documented [here](https://2.python-requests.org/en/master/api/#requests.Response.next) but is missing from [`Response`'s stub definition](https://github.com/python/typeshed/blob/efb67946f88494e5e9a273d59a3100a56514b15f/third_party/2and3/requests/models.pyi#L102). I'm not able to put together a PR this afternoon so I'm submitting this issue so I don't forget it :)

**Comment by tapaswenipathak** [comment]
Hi @jrheard, @srittau: interested, will be PRing.
