### ISSUE TITLE
None as an argument of contextlib.redirect_stdout

### ISSUE THREAD

**Issue by ateraz** [python/typeshed#3210]
I've got mypy error in valid python code:
```
$ python -V
Python 3.7.3
$ mypy --version
mypy 0.720
$ cat test.py
from contextlib import redirect_stdout

print("before")
with redirect_stdout(None):
    print("inside")
print("after")
$ python test.py
before
after
$ mypy test.py
test.py:4: error: Argument 1 to "redirect_stdout" has incompatible type "None"; expected "IO[str]"
```
According to [contextlib docs](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout) argument can only be file or file-like object, so typeshed is right. But according to [sys docs](https://docs.python.org/3/library/sys.html#sys.__stdin__) `stdout` can be `None`.
Looks like there's discrepancy between contextlib and typeshed, although I'm not sure whether it's typeshed or contextlib (either in code or docs) issue.

**Comment by srittau** [comment]
PRs for typeshed welcome. Possibly the CPython maintainers would accept a PR to clarify this in the docs as well.
