### ISSUE TITLE
ThreadingHTTPServer missing from http.server stub

### ISSUE THREAD

**Issue by stephen-dexda** [python/typeshed#3217]
Was added to http.server in 3.7: https://docs.python.org/3/library/http.server.html#http.server.ThreadingHTTPServer

Missing from https://github.com/python/typeshed/blob/master/stdlib/3/http/server.pyi

Looks like it got missed from https://github.com/python/typeshed/issues/1965?

**Comment by srittau** [comment]
Patches welcome!

**Comment by Hanaasagi** [comment]
If nobody is working on this, I am willing to do.
