### ISSUE TITLE
Add tuple of tuples to requests.api params

### ISSUE THREAD

**Issue by stephen-dexda** [python/typeshed#3218]
For params, requests.api supports nested tuples (i.e. `Tuple[Tuple[str, Tuple[str, ...]], ...]`, e.g. `(("param1", ("param1val1", "param1val2")),("param2", ("param2val",)))`, but this isn't currently covered by https://github.com/python/typeshed/blob/master/third_party/2and3/requests/api.pyi.

This is useful for e.g. using sorted params as part of a key for an HTTP cache, where hashability is needed.

**Comment by srittau** [comment]
Implementation in https://github.com/psf/requests/blob/3d968ff34dd9945f2a86396001408ba69c1ab3fd/requests/models.py#L83. It seems to work with any iterable. Patches welcome.

**Comment by tapaswenipathak** [comment]
Hi folks: Interested, I will be adding a PR.
