### ISSUE TITLE
`unittest.skip` functions can't be applied to classes

### ISSUE THREAD

**Issue by connorbrinton** [python/typeshed#3221]
The docs for `unittest` state that:

"Classes can be skipped just like methods:"

And give the following example:

```python
@unittest.skip("showing class skipping")
class MySkippedTestCase(unittest.TestCase):
    def test_not_run(self):
        pass
```

However, the type for `unittest.skip` defined in `typeshed` is:

```python
_FT = TypeVar('_FT', bound=Callable[..., Any])
...
def skip(reason: str) -> Callable[[_FT], _FT]: ...
```

Which seems like it shouldn't work to me. For some reason, `mypy` doesn't have any problems with the above example, but similar code which wraps `unittest.skip` results in errors. For example:

```python
import unittest
from typing import Any, Callable, Type, TypeVar, Union, cast


T = TypeVar('T', bound=Union[Callable, Type])


def noisy_decorator(decorator: Callable[[T], T]) -> Callable[[T], T]:
    def _decorator(arg: T) -> T:
        print("I'm decorating something!")
        return decorator(arg)

    return _decorator


@noisy_decorator(unittest.skip("showing class skipping"))
class MySkippedTestCase(unittest.TestCase):
    def test_not_run(self):
        pass
```

Results in the error `test45.py:17: error: Argument 1 has incompatible type "Type[MySkippedTestCase]"; expected "_FT"`.

I think the fix for this would be to change `_FT = TypeVar('_FT', bound=Callable[..., Any])` to `_FT = TypeVar('_FT', bound=Union[Callable[..., Any], Type])`

**Comment by srittau** [comment]
The `unittest.skip` method seems to be correctly annotated to me. Types are callables. I suspect a mypy problem, see this example:

```python
from typing import Any, Callable, Type, TypeVar, Union, cast

_T = TypeVar("_T")
_C = TypeVar("_C", bound=Callable[..., Any])

class Cls: ...
def wrap(decorator: Callable[[_T], _T]) -> Callable[[_T], _T]: ...

s: Callable[[_T], _T]
w = wrap(s)

s(Cls)
w(Cls)  # error: Argument 1 has incompatible type "Type[Cls]"; expected "_T"

reveal_type(s)
reveal_type(w)
```

I suspect that mypy is somehow "losing track" of the fact that `wrap()` contains the same type variable, but my understanding of mypy internals is very limited. Maybe @ilevkivskyi could shed some light on this?

**Comment by connorbrinton** [comment]
@srittau I moved this issue in the `mypy` issue tracker ([here](https://github.com/python/mypy/issues/7464)), since it seems like the type annotations are correct for the `unittest.skip*` functions. Thanks for the help! 😄
