### ISSUE TITLE
isinstance(x, mock.Mock) is broken since Mock is aliased to Any

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#3224]
#3182 changed `mock.Mock` to be an alias to `Any`, which resulted in mypy complaining about `isinstance(x, mock.Mock)`, which I believe should be valid. 

We can fix this by reverting #3182 or potentially by making `Mock` a class with an `Any` base class. `Mock` is a class at runtime, so making it an alias to `Any` (which is not a class) seems wrong to me.

**Comment by srittau** [comment]
Subclassing sounds to be the best solution to me, if it works. That also means we could add methods to it, which exist on the implementation. Cc @JelleZijlstra

**Comment by srittau** [comment]
Also `MagicMock` and `AsyncMock` (when my Python 3.8 patch gets merged).

**Comment by hauntsaninja** [comment]
I believe this is fixed by #3846 and others
