### ISSUE TITLE
Python 3.8: asyncio exceptions have extracted into a separate module

### ISSUE THREAD

**Issue by Hanaasagi** [python/typeshed#3231]
See this PR for more detail https://github.com/python/cpython/pull/9141

We will get `error: Module has no attribute "exceptions"` when use `asyncio.exceptions.IncompleteReadError`.

**Comment by Hanaasagi** [comment]
`asyncio/exceptions.py` only exists in Python 3.8. So copy exceptions to `stdlib/3.8/asyncio/exceptions.py` and make all exceptions in `stdlib/3/asyncio/` under a version check condition. Is this a good way to fix this?

**Comment by srittau** [comment]
I don't think there is a good way. I think the best we can do is to keep asyncio in `stdlib/3/asyncio`, add the `exception.pyi` file there, put all exceptions in there inside a version check. In the previous places also do a version check and import the exception for 3.8+ and use an inline version below. Maybe someone else has a better idea.

**Comment by Hanaasagi** [comment]
@srittau Is someone is doing this? If not, I can work on this.

**Comment by srittau** [comment]
Please go ahead.
