### ISSUE TITLE
Signature for NamedTuple in typing.pyi does not match typing.py

### ISSUE THREAD

**Issue by gribbg** [python/typeshed#3235]
The signature in `typing.pyi` has extra fields **verbose** and **rename,** which are not in `typing.py`.  From `typing.pyi`:

    def __init__(self, typename: str, fields: Iterable[Tuple[str, Any]] = ..., *,
                 verbose: bool = ..., rename: bool = ..., **kwargs: Any) -> None: ...

From `typing.py`:

    def __new__(self, typename, fields=None, **kwargs):

Which can also be seen in this example:

    >>typing.NamedTuple('Example', verbose=bool, rename=bool).__annotations__
    OrderedDict([('verbose', <class 'bool'>), ('rename', <class 'bool'>)])

Unsurprisingly, passing `verbose=True` (as implied by `typing.pyi`) causes an exception:

    typing.NamedTuple('Example', verbose=True, other_field=int).__annotations__
     Traceback (most recent call last):
      File "<input>", line 1, in <module>
      File "C:\Program Files\Python37\lib\typing.py", line 1411, in __new__
        return _make_nmtuple(typename, fields)
      File "C:\Program Files\Python37\lib\typing.py", line 1326, in _make_nmtuple
        types = [(n, _type_check(t, msg)) for n, t in types]
      File "C:\Program Files\Python37\lib\typing.py", line 1326, in <listcomp>
        types = [(n, _type_check(t, msg)) for n, t in types]
      File "C:\Program Files\Python37\lib\typing.py", line 139, in _type_check
        raise TypeError(f"{msg} Got {arg!r:.100}.")
     TypeError: NamedTuple('Name', [(f0, t0), (f1, t1), ...]); each t must be a type Got True.

**Comment by gribbg** [comment]
See also [issue38191](https://bugs.python.org/issue38191) which is changing the signature of `NamedTuple` to:

    '($cls, typename, fields=None, /, **kwargs)'

**Comment by gvanrossum** [comment]
Let's delete `verbose` and `rename` (I guess they were from some unimplemented idea?) and rename the other positional arguments to use the `__private` format, which PEP 484 gives the special meaning of "positional only". (We can't use the newfangled '/' syntax yet because not all tools reading .pyi files have a Python 3.8-capable parser.)

Can you submit a PR? Also please do the same for TypedDict, then your PR will close both issues.

**Comment by gribbg** [comment]
`verbose` and `rename` are part of `collections.namedtuple`, so I assume they came over from there when `NamedTuple` was first created.

**Comment by gvanrossum** [comment]
Oh, interesting. But since typing.NamedTuple doesn't support them, they should not be in the stubs.

**Comment by srittau** [comment]
PR welcome!
