### ISSUE TITLE
Module 'functools' has no attribute 'RLock'

### ISSUE THREAD

**Issue by wugifer** [python/typeshed#3255]
Hello,

when I use mypy with functools, it says "Module 'functools' has no attribute 'RLock'", but functools do have RLock.

I found mypy issue "https://github.com/python/mypy/issues/2590" has the same problem but with singledispatch and you fix it.

The following is my case:

$ cat a.py
from functools import RLock

$ mypy a.py
a.py:1: error: Module 'functools' has no attribute 'RLock'

$ python3 a.py

$

Thank

**Comment by srittau** [comment]
`functools` exporting `RLock` is just a side-effect of Python's import mechanic and should not be relied on. Please use `threading.RLock` from where it is imported.
