### ISSUE TITLE
codecs.register has wrong type definition

### ISSUE THREAD

**Issue by rmorshea** [python/typeshed#3262]
The `search_function` parameter of [`codecs.register`](https://github.com/python/typeshed/blob/master/stdlib/2and3/codecs.pyi#L68) function has the type:

```
Callable[[str], CodecInfo]
```

However the docs:

https://docs.python.org/3.7/library/codecs.html#codecs.register

Indicate that a search function should return `None` if it doesn't understand the encoding.

Thus, the correct `search_function` type should be:

```
Callable[[str], Optional[CodecInfo]]
```

**Comment by srittau** [comment]
Thanks, PRs welcome!

**Comment by parthsharma2** [comment]
Hi @srittau @rmorshea. Just made a PR #3271 that hopefully resolves this issue :)
