### ISSUE TITLE
Incorrect "Statement is unreachable" for asyncio.gather(..., return_exceptions=True) with --warn-unreachable

### ISSUE THREAD

**Issue by hh-h** [python/typeshed#3266]
Copied from https://github.com/python/mypy/issues/7561
with `warn_unreachable = true` setting mypy throws the error
```
something.py: note: In function "main":
something.py:10: note: Revealed type is 'Tuple[builtins.int*, builtins.int*]'
something.py:12: note: Revealed type is 'builtins.int'
something.py:14: error: Statement is unreachable
Found 1 error in 1 file (checked 1 source file)
```
example
```python
import asyncio


async def fn() -> int:
    raise Exception()


async def main() -> None:
    results = await asyncio.gather(fn(), fn(), return_exceptions=True)
    reveal_type(results)  # Revealed type is 'Tuple[builtins.int*, builtins.int*]'
    for result in results:
        reveal_type(result)  # Revealed type is 'builtins.int'
        if isinstance(result, Exception):
            print("exception")  # Statement is unreachable
        else:
            print("result")

asyncio.run(main())
```

**Comment by gvanrossum** [comment]
Thanks! It looks like this can be solved by doubling the overloads for `gather()`, replacing `return_exception: bool` with `return_exception: Literal[False]` for one of the overloads and `return_exception: Literal[True]` for the other, and changing the return type for the latter to `Tuple[Union[T1, BaseException], ...]`.

If you want to help, please submit a PR along those lines!

**Comment by gvanrossum** [comment]
Note that the root cause is that the return type is too narrow if `return_exceptions=True` is specified. The "Statement is unreachable" error is just one of the effects.

**Comment by hh-h** [comment]
Thank you, will submit PR on weekend
