### ISSUE TITLE
Turn --disallow-any-generics on when checking stubs with mypy

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#3267]
I have noticed several people recently forgot to specify type arguments. Should we try enforcing this?

**Comment by gvanrossum** [comment]
+1, assuming we don't have to fix 100s of places...

**Comment by srittau** [comment]
More strictness is a good thing for typeshed, in my opinion.

**Comment by ilevkivskyi** [comment]
I actually just tried this and it causes around 400 errors. On one hand this is not too many to do this in general, on other hand it is probably too many to do this right now.

**Comment by gvanrossum** [comment]
Could we incrementally fix those errors? Even if some more of the same type
of errors appear it would be less work to fix the final batch.

Possibly we could add `# mypy: disallow-any-generics` to files that have
been fixed (or create a mypy.ini file with sections for subdirectories
we've fixed).

**Comment by ilevkivskyi** [comment]
> Could we incrementally fix those errors? Even if some more of the same type of errors appear it would be less work to fix the final batch.

This is a good idea. @srittau what do you think about splitting the work, will you have time/energy? Also maybe @JelleZijlstra ?

**Comment by srittau** [comment]
Good idea indeed. I'll look into it tomorrow.
