### ISSUE TITLE
Missing methods on pkg_resources.VersionConflict

### ISSUE THREAD

**Issue by hawkowl** [python/typeshed#3279]
typeshed: https://github.com/python/typeshed/blob/caefaa6af9203a243709c21eeb5f2669af63b846/third_party/3/pkg_resources/__init__.pyi#L205

pkg_resources definition: https://github.com/pypa/setuptools/blob/master/pkg_resources/__init__.py#L258

**Comment by srittau** [comment]
PR welcome!

**Comment by utkarsh2102** [comment]
Hi @srittau,  
While trying to understand how this works, I came up with the following patch:  
```
--- a/third_party/3/pkg_resources/__init__.pyi
+++ b/third_party/3/pkg_resources/__init__.pyi
@@ -202,7 +202,15 @@ class IMetadataProvider:
 
 class ResolutionError(Exception): ...
 class DistributionNotFound(ResolutionError): ...
-class VersionConflict(ResolutionError): ...
+
+class VersionConflict(ResolutionError):
+    @property
+    def dist(self) -> List[Any]: ...
+    @property
+    def req(self) -> List[Any]: ...
+    def report(self) -> str: ...
+    def with_context(self, required_by: Dict[str, Any]) -> ContextualVersionConflict: ...
+
 class UnknownExtra(ResolutionError): ...
 
 class ExtractionError(Exception):
```

Though I am certain there'll be something missing/unwanted/wrong, I'd appreciate your help and review in this :D

**Comment by srittau** [comment]
@utkarsh2102 Could you open a PR? It's easier to review that way. You can mark it as a draft if you don't want it to be merged yet.

**Comment by utkarsh2102** [comment]
@srittau, done :)
