### ISSUE TITLE
errors in imaplib.pyi

### ISSUE THREAD

**Issue by lddubeau** [python/typeshed#3289]
I've noticed the following errors in [imaplib.pyi]( https://github.com/python/typeshed/blob/b336182b695b58ec6a0faa31794defcdc70ffb96/stdlib/2and3/imaplib.pyi)

1. Variable lists of parameters are incorrectly typed. Example:

   ```
   def uid(self, command: str, *args: List[str]) -> CommandResults: ...
   ```
  
   Right now it the elements that make up `args` have to be lists of strings, when they just should be strings. The declaration should be:

   ```
   def uid(self, command: str, *args: str) -> CommandResults: ...
   ```

   Other methods with the same bug: `setannotation`, `sort`, `thread` and `xatom`.

2. From Python 3.3 onwards [`IMAP4_SSL`'s constructor](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4_SSL) allows a `ssl_context=` named parameter but this parameter is not defined in the stub file.

**Comment by srittau** [comment]
PRs welcome!

**Comment by vVv-AA** [comment]
uid has the same issue too right?
