### ISSUE TITLE
stdlib's ssl module is missing enums

### ISSUE THREAD

**Issue by jlaine** [python/typeshed#3301]
The `ssl.VerifyMode` and `ssl.verifyFlags` enums seem to be missing from the standard library declarations which leads to:

`error: Module 'ssl' has no attribute 'VerifyMode'`

**Comment by srittau** [comment]
Both introduced in 3.6. PR welcome!

**Comment by jlaine** [comment]
I've made PR #3302 but I'm not sure how to test it?
