### ISSUE TITLE
Why are cryptography typings Python 2 only?

### ISSUE THREAD

**Issue by jlaine** [python/typeshed#3303]
I have been maintaining my own typings for `cryptography` as part of `aioquic` but would be quite keen to have these collaboratively maintained:

https://github.com/aiortc/aioquic/tree/master/stubs/cryptography

If the cryptography typings where marked "2and3" I'd be happy to contribute my definitions.

**Comment by srittau** [comment]
I wondered this myself yesterday. I will review them soon and move them to 2and3.
