### ISSUE TITLE
Provide ipaddress stub in third_party/2 ?

### ISSUE THREAD

**Issue by jlaine** [python/typeshed#3309]
For Python 3 we have stubs for the stdlib's `ipaddress` module. For Python 2, `ipaddress` is not part of the standard library but is available as third party package, much like `enum`.

Is the proper way to handle this to copy over ipaddress to `third_party/2`?

**Comment by JelleZijlstra** [comment]
Yes, assuming the backport's API is the same as the one in the stdlib. We could add a test in check_consistent.py to ensure that the two copies stay in sync.

**Comment by jlaine** [comment]
This was fixed in 57384ce0338e32763f148e3f493f78631c9b0740
