### ISSUE TITLE
Missing imaplib.IMAP4.enable()?

### ISSUE THREAD

**Issue by utkarsh2102** [python/typeshed#3313]
Hey,  
Python 3.5 introduced a new `enable()` method (document [here](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4_SSL)) which seems to be missing at the moment.

**Comment by gvanrossum** [comment]
Feel free to submit a PR.

**Comment by utkarsh2102** [comment]
> Feel free to submit a PR.

Sure thing!
