### ISSUE TITLE
NotImplemented is not callable

### ISSUE THREAD

**Issue by ltworf** [python/typeshed#3315]
I'm aware of this https://github.com/python/mypy/issues/6710

I understand the points raised here https://github.com/python/mypy/issues/6710

However the current issue is that

```
raise NotImplemented()
```

seems perfectly valid to mypy when in fact it isn't, since it's not callable.

So basically, it should have been a `NotImplementedError` but mypy didn't find it (I found it with pyflakes).

Do you think it is possible to make it an almost-but-non-callable-Any?

Otherwise it could perhaps be mypy to warn about odd uses?

**Comment by srittau** [comment]
We could try to make `NotImplemented` a sub-class of `Any` and override `__call__()`:

```
from typing import Any

class NotImplemented(Any):
    __call__: None
    
def bar() -> str:
    return NotImplemented()

x: NotImplemented
x()
```

Not very elegant and the error message is not correct, but maybe better than nothing?
