### ISSUE TITLE
Add support for Python 3.8

### ISSUE THREAD

**Issue by srittau** [python/typeshed#3319]
* [What's New](https://docs.python.org/3.8/whatsnew/3.8.html)
* [Changelog](https://docs.python.org/3.8/whatsnew/changelog.html)

**Comment by srittau** [comment]
The following PRs are everything according to the release notes:

* [X] #3337
* [ ] #3346 
* [X] #3347
* [ ] #3351 
* [X] #3356 
* [ ] #3358 
* [ ] #3359

**Comment by bluetech** [comment]
@srittau There is [functools.cached_property](https://docs.python.org/3.8/library/functools.html#functools.cached_property), if you know how to type this one...

**Comment by srittau** [comment]
@bluetech Thanks, #3439.

**Comment by bluetech** [comment]
While adding `sys.pycache_prefix` (#3454), I noticed a couple more new functions in sys: [`addaudithook`](https://docs.python.org/3/library/sys.html#sys.addaudithook) and [`audit`](https://docs.python.org/3/library/sys.html#sys.audit). I don't use this, and [the PEP](https://www.python.org/dev/peps/pep-0578/) is a bit too lengthy for me to dig into, but thought I'd mention it.

**Comment by srittau** [comment]
sys.audit et al: #3455
