### ISSUE TITLE
Linter for unused imports

### ISSUE THREAD

**Issue by srittau** [python/typeshed#3322]
We have a bunch of unused imports in the stubs. It would be nice if we could check for that. Unfortunately we can't enable flake8's F401 check, since we need to support re-exports. Adding a `noqa` comment would also not be practical. I think we could either add a check to flake8-pyi or see if we could get a relaxed version of F401 into flake8/pyflakes.

**Comment by srittau** [comment]
There already is PyCQA/pyflakes#474 open about this.

**Comment by JelleZijlstra** [comment]
I believe pyright does this for us now. It would be useful for flake8/flake8-pyi/pyflakes to support finding unused imports in stubs directly, but typeshed doesn't need it any more.
