### ISSUE TITLE
subprocess stubs only accept str

### ISSUE THREAD

**Issue by sharmaeklavya2** [python/typeshed#336]
`subprocess` accepts both `bytes` and `str` (or a sequence of these) (and `str` and `unicode` on python 2) as `args`, but the stubs only accept `str` (or a sequence of `str`).

To test this, I made a file named `u"\U0001f600.txt"` (😀.txt) and opened it with `cat` using `subprocess.check_call`. I then did `.encode('utf-8')` on the filename and then passed it to `subprocess.check_call` with `cat`. It worked in both cases on both python 2 and 3.

**Comment by gvanrossum** [comment]
Hm, okay. I guess I will accept a fix for this.

**Comment by JelleZijlstra** [comment]
This was fixed a while ago, I think in one of @euresti's PRs.
