### ISSUE TITLE
collections.namedtuple inferred as type tuple and not the (user-defined) class

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [python/typeshed#3394]
Reference: https://github.com/pandas-dev/pandas/pull/29114#discussion_r337152697

`collections.namedtuple()` should have its type inferred as the user-supplied argument. Instead, its type is inferred as tuple.

**Comment by srittau** [comment]
`namedtuple` is special cased by type checkers. I am not sure that its definition can be improved in typeshed. But if you have good ideas, please submit a PR and we will have a look at it. In the meantime I am going to close this issue.
