### ISSUE TITLE
list('abc') not inferred to be of type List[str]

### ISSUE THREAD

**Issue by AbhijeetKrishnan** [python/typeshed#3395]
Reference: https://github.com/pandas-dev/pandas/pull/29114#discussion_r337152697

`list('abc')` should be inferred to be of type List[str]. However, we still get errors if used as the argument to a function.

MRE -
```python
import collections
named_tuple = collections.namedtuple('Test', list('abc'))
```

Running mypy on the above gives the error `error: List or tuple literal expected as the second argument to namedtuple() `

**Comment by srittau** [comment]
This looks like a mypy error. Both `class list` and `namedtuple()` look to be correctly typed in typeshed and should work together. I assume that `namedtuple` is specially handled by mypy, because of its special semantics.

**Comment by AbhijeetKrishnan** [comment]
Would it be more helpful to raise this issue with mypy instead?

**Comment by AbhijeetKrishnan** [comment]
I've raised the same issue with mypy (https://github.com/python/mypy/issues/7766) This issue can be closed.
