### ISSUE TITLE
stub for multiprocessing.Queue wrongly supports join()

### ISSUE THREAD

**Issue by odedp** [python/typeshed#3404]
The following code type checks but results in a runtime error:

```python
import multiprocessing
q = multiprocessing.Queue()
q.join()
```

The problem seems to be that in `stdlib/3/multiprocessing/queues.pyi`, `class Queue` inherits from `queue.Queue` which contains the `join()` method.

**Comment by srittau** [comment]
The stub probably inherits `queue.Queue` so that it can be passed into functions that expect that. Now that we have protocols, we should remove the inheritance and use protocols where needed.
