### ISSUE TITLE
TCPConnector constructor, ttl_dns_cache and PEP-484

### ISSUE THREAD

**Issue by humkanet** [python/typeshed#3406]
Hello,

```
class TCPConnector
def __init__(
....
ttl_dns_cache: int=10
...)
```

but documentation (and code so):

> ttl_dns_cache (int) –
> 
> expire after some seconds the DNS entries, None means cached forever. By default 10 seconds.

Can you annotate as Optional[int], please?

**Comment by srittau** [comment]
I assume you are using aiohttp. In this case, please file a bug in their bug tracker, since aiohttp ships its own type stubs.
