### ISSUE TITLE
Enum.__module__ returns 'enum.Enum*' instead of str

### ISSUE THREAD

**Issue by tamias65** [python/typeshed#3407]
If I do:

```
# bar.py
from enum import Enum

class BarEnum(Enum):
    ENUM_1 = 1
    ENUM_2 = 2

# script.py
from bar import bar.BarEnum

print(type(BarEnum.__module__))  # prints 'str'
reveal_type(BarEnum.__module__) # Revealed type is 'bar.BarEnum*'
```
I would assume that .\__module\__ to return str? Otherwise doing
`print(BarEnum.__module__ + " is the module name") 
`
returns Unsupported left operand type for + ("bar.BarEnum")

**Comment by srittau** [comment]
`Enum` is missing both `__module__` and `__qualname__`, so I think mypy assumed that `__module__` is an enum value. Patches welcome!

**Comment by hoefling** [comment]
Not reproducible with `mypy==0.761` anymore.
