### ISSUE TITLE
Add join function in shlex module (new in 3.8)

### ISSUE THREAD

**Issue by gusmonod** [python/typeshed#3430]
A new function was added to the stdlib `shlex` in python 3.8, as stated here: https://docs.python.org/3/library/shlex.html#shlex.join and in the changelog here https://docs.python.org/3/whatsnew/changelog.html and here https://bugs.python.org/issue22454

At the moment, only split has a stub: https://github.com/python/typeshed/blob/87d7dd3d957a7571f8628ec381c44a4e77c770f5/stdlib/3/shlex.pyi#L4

Adding join would be quite simple, and would probably look a bit like this:

```python
def join(s: List[str]) -> str: ... 
```

I have not opened a PR yet because I wonder if this is something that you would want to add or not, because saying that join does not exist is true for python3.7 and lower. Surely there must be precedent, but I could not find an example of this in the issues yet.

**Comment by utkarsh2102** [comment]
Hi,
With #3319 already in progress, I think you could open a PR with:
`if sys.version_info >= (3, 8):`  :)
Also, @srittau would know better :)

**Comment by srittau** [comment]
Thanks for the report. `shlex.join()` was added in #3358.
