### ISSUE TITLE
memoryview __init__ missing some supported stdlib types

### ISSUE THREAD

**Issue by Road-hog123** [python/typeshed#3433]
The `__init__` method of `memoryview` takes one parameter - `obj` - which can be any object that supports the [buffer protocol](https://docs.python.org/3/c-api/buffer.html#buffer-protocol).

Currently in typeshed, `obj` is annotated as `Union[bytes, bytearray, memoryview]`, which gives support for both built-in objects that support the buffer protocol, but omits other types from the standard library extensions such as `array.array`.

`array.array` in particular is used multiple times in the [documentation for `memoryview`](https://docs.python.org/3/library/stdtypes.html#memoryview).

I don't know which other objects in the standard library support the buffer protocol to be able to add them all, let alone other libraries with type stubs here. Perhaps someone has a list, or a way to generate a list?

**Comment by srittau** [comment]
We need to fix python/typing#593.

**Comment by JelleZijlstra** [comment]
Now `memoryview.__init__` is annotated as taking `_typeshed.ReadableBuffer`, which includes `array`. That's as much as we can do in typeshed; we can revisit this if python/typing#593 ever moves forward.
