### ISSUE TITLE
Generic types that crash runtime

### ISSUE THREAD

**Issue by shannonzhu** [python/typeshed#3435]
https://github.com/python/typeshed/blob/86135edb6d3422473db1b6d1c054f1c086b15850/stdlib/3/subprocess.pyi#L42

https://github.com/python/cpython/blob/master/Lib/subprocess.py#L423

Stubs like this one make a class generic when the runtime class is not. 

This means any users of this annotation must wrap their type in quotes, or the runtime will throw a type error when evaluating them: `TypeError: 'type' object is not subscriptable`. 

We've had project owners confused by this when type checking their code, especially those who have strict typing on and are warned when using Anys or implicit Any type parameters. Is this a common pattern and a conscious choice? Without owning the source code, I can see this would limit expressivity of type stubs at least while annotations are still being evaluated at runtime. 

If not, I'm happy to submit a PR to fix this case.

**Comment by JelleZijlstra** [comment]
Yes, this is a conscious choice. It's mentioned in the mypy docs (I realize that is not very helpful for pyre users though): https://mypy.readthedocs.io/en/latest/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

How do you propose to fix this case? The only way I can see is to make the stub class not generic, which would lose some typing information.

**Comment by srittau** [comment]
Also, this is one of the reasons you can use `from __future__ import annotations` starting with Python 3.7.

**Comment by shannonzhu** [comment]
Yeah, the proposed fix was to lose the type information here. This is good to know, thanks for the extra context!

**Comment by SteveByerly** [comment]
@JelleZijlstra Updated link to mypy docs
https://mypy.readthedocs.io/en/latest/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime
