### ISSUE TITLE
weakref.proxy is not generic

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#3445]
As weakref.proxy is not generic which can be seen here [_weakref.py](https://github.com/python/typeshed/blob/e4677d9ed4aeb1ae9e094aa795fa6d616959ff2e/stdlib/2and3/_weakref.pyi#L10) what is the intended way to annotate it or is this impossible?
Normal weakproxy.ref's can be annotated as far as I think using
```
spam = ReferenceType[Class]
```
whereas
```
ham = ProxyType[Class]
```
does not work. Is one supposed to just
```
egg = Class
```
as it is a proxy and should behave the same?

**Comment by hatal175** [comment]
I belive this can be closed.
