### ISSUE TITLE
Running mypy on typeshed checkout on Widows results in errors

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#3446]
I just tried checking typeshed with mypy on Windows and I get:
```
stdlib\2and3\formatter.pyi:5: error: Need type annotation for 'AS_IS'
stdlib\3\asyncio\__init__.pyi:116: error: Name 'SelectorEventLoop' already defined (possibly by an import)
```
Not a big deal, but maybe we should fix these errors.

**Comment by srittau** [comment]
The second error makes sense, but I wonder why the first error is not flagged on other systems. There seems to be nothing Windows-specific about it. Both look easy to fix, though.

**Comment by JelleZijlstra** [comment]
#3425 should address this (at least the CI part of it).

**Comment by ilevkivskyi** [comment]
> but I wonder why the first error is not flagged on other systems.

This may indicate some bug in the test suite. Currently mypy test contains deeply nested cycles, I am wondering maybe there is some "indentation error" causing some files not being checked?

**Comment by JelleZijlstra** [comment]
It might be a similar issue to what I fixed in #3424, where an `import *` injects the name into scope only on Windows.

**Comment by ilevkivskyi** [comment]
Hm, it looks like this starts causing troubles in mypy, see CI failure in https://github.com/python/mypy/pull/7794, I will make a PR now.

**Comment by ilevkivskyi** [comment]
I think this can be closed now as both relevant PRs were merged.
