### ISSUE TITLE
re.Pattern and re.Match are not recognized (Python 3.7)

### ISSUE THREAD

**Issue by VideoPlayerCode** [python/typeshed#3447]
Using mypy, the following code claims that `Module has no attribute "Pattern" mypy(error)` and `Name 're.Pattern' is not defined mypy(error)`, and the same happens for `re.Match`:

```python
import re

def foo(bar: re.Pattern) -> None:
    pass

def foo2(bar2: re.Match) -> None:
    pass
```

The system only has Python 3.7 on it, and mypy.

**Comment by VideoPlayerCode** [comment]
Seems like there's an accepted workaround:

https://stackoverflow.com/questions/39521895/how-do-i-get-a-regex-pattern-type-for-mypy

https://docs.python.org/3/library/typing.html#typing.Pattern
https://docs.python.org/3/library/typing.html#typing.Match

Why is that workaround necessary, though?

**Comment by srittau** [comment]
It seems `Pattern` and `Match` were added in Python 3.7, basically as aliases for the sre_compile classes. That they were not also added to typeshed looks like a simple oversight. They should probably just be aliases for `typing.Pattern/Match` in typeshed, though, as that is what `sre_compile.compile()` returns.

PR welcome!

**Comment by VideoPlayerCode** [comment]
@srittau Ah I understand. Didn't realize they were that new in Python!
