### ISSUE TITLE
object.__reduce__ might return a string

### ISSUE THREAD

**Issue by MSeifert04** [python/typeshed#3452]
I have a type which returns a string in `__reduce__` which leads to a mypy failure:

> Return type "str" of "\_\_reduce\_\_" incompatible with return type "Tuple[Any, ...]" in supertype "object"

According to the [`__reduce__` documentation](https://docs.python.org/3/library/pickle.html#object.__reduce__) this method can return a string or a Tuple. 

Would it make sense to change the typing to `__reduce__(self) -> Union[str, Tuple[Any, ...]]: ...`?

**Comment by srittau** [comment]
Same for `__reduce_ex__`. Makes sense, PR welcome!
