### ISSUE TITLE
inspect._ParameterKind should derive from enum.IntEnum

### ISSUE THREAD

**Issue by aldanor** [python/typeshed#3467]
https://github.com/python/typeshed/blob/ec7960a8cb2e2ff465ee0fff841cd28fa85fe3ba/stdlib/3/inspect.pyi#L126-L127

The current implementation makes this fail the type check:

```python
parameter.kind.name
```

(whereas it's completely valid since `parameter.kind` is an `IntEnum`)

**Comment by srittau** [comment]
PR welcome!
