### ISSUE TITLE
Change type of queue.Queue.queue to Collection[Any]

### ISSUE THREAD

**Issue by 5uper5hoot** [python/typeshed#3472]
`Queue.queue` is typed as `Deque[Any]`:

https://github.com/python/typeshed/blob/c53bc5a7ab9737cf71ef6dd75f43ef2785ff11b5/stdlib/3/queue.pyi#L23

...and while the implementation of [`queue.Queue`](https://github.com/python/cpython/blob/6db2fb7c300ca79d5585f2ae524ff4ca2707a7b6/Lib/queue.py#L205-L206) sets `self.queue = deque()`, within the very same module, [`PriorityQueue`](https://github.com/python/cpython/blob/6db2fb7c300ca79d5585f2ae524ff4ca2707a7b6/Lib/queue.py#L226-L227) and [`LifoQueue`](https://github.com/python/cpython/blob/6db2fb7c300ca79d5585f2ae524ff4ca2707a7b6/Lib/queue.py#L242-L243) set `self.queue = []`.

I'm having trouble here:

```python
class DedupeQueue(queue.Queue):
    """Queue implementation built on a set type so it deduplicates."""

    def _init(self, maxsize: int) -> None:
        self.queue = set()

    def _put(self, item: Hashable) -> None:
        self.queue.add(item)

    def _get(self) -> Hashable:
        return self.queue.pop()
```
Which warns:

`error: Incompatible types in assignment (expression has type "Set[<nothing>]", variable has type "deque[Any]")`

Would it make sense to give `Queue.queue` a more permissive type, such as `Collection`? Or go even further as to say it should be typed `Any` given that it shouldn't really matter what the queue is built upon, just that it does the right thing within those methods?

I'm fairly new to typing, so apologies if I'm missing something obvious here, but if not I'd be happy to submit a PR.

**Comment by JelleZijlstra** [comment]
Your argument makes sense, so I'd be supportive of changing the annotation. We could also consider just removing the attribute from the stub, since it is undocumented (as the comment indicates) and its precise type apparently cannot be relied on.
