### ISSUE TITLE
Use Protocols to annotate  python3 <= 3.6 `compileall` argument

### ISSUE THREAD

**Issue by SKalt** [python/typeshed#3480]
in [stdib/3/compileall.pyi](https://github.com/python/typeshed/blob/master/stdlib/3/compileall.pyi#L14), there's a comment 
> `# rx can be any object with a 'search' method; once we have Protocols we can change the type`.

Since we have Protocols, we can do this.
 
<details><summary>history</summary>
The comment was introduced on Mar 18, 2017 by @JelleZijlstra in commit efdf2f1b1, and came up in the review of #3476.
</details>

**Comment by JelleZijlstra** [comment]
Looks like #5172 fixed this
