### ISSUE TITLE
itertools.accumulate() in Python 3.8 has an initial-value parameter

### ISSUE THREAD

**Issue by egnha** [python/typeshed#3494]
In Python 3.8, `itertools.accumulate()` acquired an optional initial-value parameter. Should its stub be updated, accordingly?

For instance:

```python
from typing import Callable, Iterable, Iterator, Optional, TypeVar, overload

_T = TypeVar("_T")
_S = TypeVar("_S")

@overload
def accumulate(iterable: Iterable[_T],
               func: Callable[[_T, _T], _T] = ...) -> Iterator[_T]: ...

@overload
def accumulate(iterable: Iterable[_T],
               func: Callable[[_S, _T], _S],
               initial: Optional[_S] = ...) -> Iterator[_S]: ...
```

(Would this go in a new `stdlib/3.8/itertools.pyi` file?)

**Comment by JelleZijlstra** [comment]
Thanks for bringing this up, PRs are welcome! You'd add an `if sys.version_info >= (3, 8)` check in the existing `itertools.pyi` file; no need for a new file.

See at https://docs.python.org/3/library/itertools.html#itertools.accumulate for docs. @srittau went over the 3.8 release notes to add new 3.8 features but I suppose the release notes weren't complete.

**Comment by srittau** [comment]
Unfortunately the release notes are quite incomplete. It seems there are no processes in place to ensure that all API changes are recorded there, so I would expect that there are more 3.8 changes that I didn't catch.
