### ISSUE TITLE
Trying to import TypedDict from typing of tpying_extensions fails

### ISSUE THREAD

**Issue by plannigan** [python/typeshed#3500]
I have code that runs on Python 3.8 and Python 3.7, but I'd rather not install `typing_extensions` when it isn't need.

Code:
```
from typing_extensions import TypedDict

# try:
#     from typing import TypedDict
# except ImportError:
#     from typing_extensions import TypedDict

class MyDict(TypedDict):
    name: str
    id: int

payload: MyDict = {
    "id": 1,
    "name": "test",
}
```

Environment:
```
>>python --version
Python 3.7.4
>> pip list
Package           Version
----------------- -------
mypy              0.740  
mypy-extensions   0.4.3  
pip               19.3.1 
setuptools        42.0.1 
typed-ast         1.4.0  
typing-extensions 3.7.4.1
```

The above code passes with mypy. However, if you reverse the commented out import statements, mypy fails.

```
>> mypy typeddict.py 
typeddict.py:4: error: Module 'typing' has no attribute 'TypedDict'; maybe "_TypedDict"?
typeddict.py:10: error: Variable "typeddict.MyDict" is not valid as a type
Found 2 errors in 1 file (checked 1 source file)
```
I was able to use this same import pattern successfully for `Protocol`, but for some reason it fails for `TypedDict`.

**Comment by JelleZijlstra** [comment]
`typing.TypedDict` doesn't exist at runtime in 3.7, so I'm not sure what the typeshed issue is here. You will need to install `typing_extensions` to use TypedDict in 3.7.

**Comment by ilevkivskyi** [comment]
> `typing.TypedDict` doesn't exist at runtime in 3.7, so I'm not sure what the typeshed issue is here. 

The issue is that this causes mypy to not understand the `try-except` import. The first import makes `TypedDict` a variable with type `Any`, and this subsequently breaks all the call sites, turning types into variables with `Any` type.

There is a precedent with `Protocol` (in typeshed it is exposed as if it is always present), this is why I said "you can try to convince people there".

**Comment by vemel** [comment]
@plannigan you can check Python version instead

```python
if sys.version_info >= (3, 8):
    from typing import TypedDict, Literal, overload  # pylint: disable=no-name-in-module
else:
    from typing_extensions import TypedDict, Literal, overload
```

**Comment by Caligatio** [comment]
To enforce what @plannigan said, checking against the version is the preferred method [per the documentation](https://mypy.readthedocs.io/en/stable/common_issues.html?highlight=import#python-version-and-system-platform-checks).

**Comment by srittau** [comment]
@vemel's version is the preferred idiom.

**Comment by Sushang-Agnihotri** [comment]
Try to Uninstall the related librarie(s) and install it again. 
it worked for me.

**Comment by adaklein** [comment]
It appears that typing_extensions is already native to Python 3.7. The solution I used was:
```
try:
    from typing import TypedDict
except ImportError:
    from typing_extensions import TypedDict
```
