### ISSUE TITLE
Fix the signature of unittest.TestCase.assertLogs

### ISSUE THREAD

**Issue by deliseev** [python/typeshed#3513]
According to the documentation for the [assertLogs](https://docs.python.org/3.8/library/unittest.html?highlight=assertlogs#unittest.TestCase.assertLogs) method, the first argument should be a `logging.Logger` object or a `str` giving the name of a logger.

However, the [method signature](https://github.com/python/typeshed/blob/615fa41c250b5d4baeefe8f2c890fb2285fa0100/stdlib/3/unittest/case.pyi#L117-L120) says something else:
```
def assertLogs(
        self, logger: Optional[logging.Logger] = ...,
        level: Union[int, str, None] = ...
    ) -> _AssertLogsContext: ...
```
IMHO should be:
```
def assertLogs(
        self, logger: Optional[Union[str, logging.Logger]] = ...,
        level: Union[int, str, None] = ...
    ) -> _AssertLogsContext: ...
```

**Comment by JelleZijlstra** [comment]
Fixed by #3514.
