### ISSUE TITLE
Bug in stub for tokenize.py

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#3515]
The type of `tokenize.generate_tokens()` is stated as a callable returning `bytes` (same as `tokenize.tokenize()`), but actually the (only) difference between the two is that `generate_tokens()` works on `str`, not `bytes`. (**UPDATE**: The return type is the same either way -- `TokenInfo` contains `str` values.)

**Comment by JelleZijlstra** [comment]
This was fixed in #3481 very recently.
