### ISSUE TITLE
asyncio.shield -> expecting Future of Future.

### ISSUE THREAD

**Issue by jonathanslenders** [python/typeshed#3518]
Take the following code:

```python
import asyncio

async def f() -> None:
    # error on line 8: Argument 1 to "shield" has incompatible type "Future[int]";
    #    expected "Union[Future[Future[int]], Generator[Any, None, Future[int]], Awaitable[Future[int]]]"
    f: asyncio.Future[int] = asyncio.Future()
    g: asyncio.Future[int] = await asyncio.shield(f)


    # Fine.
    c: asyncio.Future = asyncio.Future()
    d: asyncio.Future = await asyncio.shield(c)
```

It's not obvious why we would expect a future of a future.
I don't see anything wrong in the type annotations: https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/tasks.pyi#L87 so maybe a bug in mypy?

**Comment by jonathanslenders** [comment]
Closing this. The code above was wrong. It should have been:
```python
    g: int = await asyncio.shield(f)
```

Interesting though is that if the result of ``await asyncio.shield(...)`` is not captured in a variable, mypy expects ``asyncio.Future[<nothing>]`` for the input of shield. This means we have to assign the result, even when not used.

**Comment by srittau** [comment]
@jonathanslenders python/mypy#8051 might be related to your last paragraph.
