### ISSUE TITLE
socketserver.BaseRequestHandler __init__ hint missing

### ISSUE THREAD

**Issue by paravoid** [python/typeshed#3523]
(Still pretty new at this, so I may be misunderstanding causes and/or effects, apologies beforehand)

This piece of code:
```python
import socketserver
from typing import Any

class TestRequestHandler(socketserver.BaseRequestHandler):
    def __init__(self, request: Any, client_address: Any, server: Any) -> None:
        super().__init__(request, client_address, server)
```

Results into an error:
`error: Too many arguments for "__init__" of "object"`

This looks correct, as stdlib's socketserver has:
```python
class BaseRequestHandler:
    def __init__(self, request, client_address, server):
        …
```

From what I can see, the .pyi file in typeshed doesn't seem to include type hints for BaseRequestHandler's `__init__` (unlike other classes there). Perhaps that's the culprit?

**Comment by srittau** [comment]
Your analysis is correct, `__init__` is just missing. PR welcome!
