### ISSUE TITLE
"IMAP4_SSL" has no attribute "__enter__", "__exit__"

### ISSUE THREAD

**Issue by dkg** [python/typeshed#3537]
[imaplib's documentation](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4) clearly encourages the use of `with` for an `IMAP4` object, and yet:

```
0 dkg@alice:~/src/mypy$ cat test.py
#!/usr/bin/python3
from imaplib import IMAP4
with IMAP4("example.org", 143) as M:
    M.noop()
0 dkg@alice:~/src/mypy$ mypy --strict ./test.py
test.py:3: error: "IMAP4" has no attribute "__enter__"
test.py:3: error: "IMAP4" has no attribute "__exit__"
Found 2 errors in 1 file (checked 1 source file)
1 dkg@alice:~/src/mypy$ 
```

`mypy` should be more clever about this so that it doesn't throw an error on the example code.

**Comment by srittau** [comment]
Support added in Python 3.5. PR welcome!

**Comment by dkg** [comment]
wow that was fast!

@srittau, @reidswan, thanks!
