### ISSUE TITLE
Unsupported operand types for + ("timedelta" and "datetime")

### ISSUE THREAD

**Issue by lovasoa** [python/typeshed#3538]
`timedelta.__add__` can accept a `datetime` as argument and return a `datetime`, but it is declared as 

```py
def __add__(self, other: timedelta) -> timedelta: ...
```

in typeshed.

* Are you reporting a bug, or opening a feature request?
   * a bug
* Please insert below the code you are checking with mypy,
  or a mock-up repro if the source is private. We would appreciate
  if you try to simplify your case to a minimal repro.
```python
import datetime

t = datetime.datetime(2019,1,1)
dt = datetime.timedelta(days=2)

assert dt+t == t+dt
```
* What is the actual behavior/output?

```
$ python3 test.py
$ mypy test.py
test.py:6: error: Unsupported operand types for + ("timedelta" and "datetime")
```

* What is the behavior/output you expect?
The code should typecheck

* What are the versions of mypy and Python you are using?
```
$ python3 --version
Python 3.7.5
$ mypy --version
mypy 0.720
```
* What are the mypy flags you are using? (For example --strict-optional)
none

**Comment by srittau** [comment]
`datetime.__radd__()` (and `date.__radd__()`) is missing from the stubs. PR welcome!
