### ISSUE TITLE
CoroutineType should have __name__ and __qualname__ attributes

### ISSUE THREAD

**Issue by llchan** [python/typeshed#3561]
The built-in `CoroutineType` should have `__name__` and `__qualname__` attributes.  I can send up a PR sometime next week.

**Comment by llchan** [comment]
I suppose while we're at it, should also add `cr_origin` for 3.7+

**Comment by iwoloschin** [comment]
I've just run into this. Was there ever a PR for this?

**Comment by hauntsaninja** [comment]
Nope, but a PR would be welcome!

**Comment by srittau** [comment]
Actually, `__name__` and `__qualname__` are class attributes of `object` and need to be added there. `__qualname__` was only added in Python 3, see [PEP 3155](https://www.python.org/dev/peps/pep-3155/).

**Comment by Akuli** [comment]
I have used `type(foo).__name__` in the past without mypy complaints. Maybe mypy special-cases that?

**Comment by srittau** [comment]
Interesting. `__type__.__name__` exists. That could be removed, if `__name__` is added to `object`.

**Comment by Akuli** [comment]
not all objects have `__name__`

```
>>> object().__name__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'object' object has no attribute '__name__'
```

**Comment by JelleZijlstra** [comment]
Correct, `__name__` does not actually exist on all objects, only on types and some others.
