### ISSUE TITLE
Werkzeug `EnvironHeaders` is not considered a `Mapping`

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#3569]
It seems that the `EnvironHeaders` class of `werkzeug` (and probably the base class `Headers` too) is not compatible with `Mapping`, however it looks like it should be compatible (it implements all needed methods, and functions like one).

**Comment by srittau** [comment]
Do you have an example that you think should type check but doesn't?

**Comment by libre-man** [comment]
Here is small example:

```python
from flask import request
import typing as t

T = t.TypeVar('T')
Z = t.TypeVar('Z')

def get(kv: t.Mapping[T, Z], key: T) -> Z:
    return kv[key]

get(request.headers, 'a_header')
```

On which mypy errors with: `test.py:10: error: Argument 1 to "get" has incompatible type "EnvironHeaders"; expected "Mapping[str, <nothing>]"`.

**Comment by srittau** [comment]
I opened #3576 for the underlying issue. My best suggestion for now is to use a custom protocol for your own code and - depending on the outcome of the discussion in #3576 - submit PRs for code in typeshed.

**Comment by gward** [comment]
For posterity, here is a custom protocol that works for me in one particular place:
```
from typing import overload
import typing_extensions

class HeadersType(typing_extensions.Protocol):
    """common subtype of Mapping[str, str] and werkzeug.datastructures.EnvironHeaders"""
    @overload
    def get(self, k: str) -> Optional[str]:
        ...

    @overload
    def get(self, k: str, default: str) -> str:
        ...
```

This is not a general solution to the problem! But I just spent at least an hour banging my head against this until I got it working. Hopefully this can save someone else some time in the future.

I just had to change my code from 
```
headers: Mapping[str, str]
```
to
```
headers: HeadersType
```
and now mypy is happy.

**Comment by srittau** [comment]
A brief addendum on why we can't just derive `Headers` from `Mapping`: Since `Mapping` is not a protocol, the following code returns `False` at runtime:

```python
from collections.abc import Mapping
from werkzeug.datastructures import Headers

isinstance(Headers(), Mapping)  # False
```

Deriving `Headers` from `Mapping` would introduce a false negatives. For example, `cgi.FieldStorage` takes a `headers` arguments, but checks for `Mapping` explicitly:

```python
from cgi import FieldStorage
from werkzeug.datastructures import Headers

FieldStorage(headers=Headers())  # throws a TypeError
```

**Comment by srittau** [comment]
Closing as the werkzeug stubs will be removed in a few months.
