### ISSUE TITLE
Unexpected argument flask set_cookie samesite

### ISSUE THREAD

**Issue by danieldaeschle** [python/typeshed#3609]
# What steps will reproduce the problem?

1. Install flask
2. Create sample project
3. Create a response like in the screenshot below

# What is the expected result?
No linting error
According to https://flask.palletsprojects.com/en/1.1.x/security/#set-cookie-options

# What happens instead?
Linting error "Unexpected argument"
![image](https://user-images.githubusercontent.com/30751516/72293420-c7c54080-3653-11ea-8879-1a9c1a64c8e2.png)

# Cause
https://github.com/python/typeshed/blob/master/third_party/2and3/werkzeug/wrappers.pyi#L134
`samesite` is not presented

**Comment by srittau** [comment]
PR welcome!
