### ISSUE TITLE
stub for csv.writer can't accept subclass of csv.Dialect

### ISSUE THREAD

**Issue by Solumin** [python/typeshed#3611]
`csv.writer` is an [import](https://github.com/python/typeshed/blob/055a907e756ae3a8380845aa62c65b1da46ed610/stdlib/2and3/csv.pyi#L16) of `_csv.writer`. #3581 changed `_csv.writer` to take `dialect: Union[_csv.Dialect, str]`. This is correct, but now `csv.Dialect` -- which is distinct from `_csv.Dialect` -- is no longer a valid argument type for `csv.writer`.

For example, if someone was to define their own `class MyDialect(csv.Dialect)`, a type checker would be correct to raise a "wrong argument type" error for a call like `csv.writer(some_file, dialect=MyDialect())`.

As far as I can tell, the stub is technically correct, but `_csv.writer` should be able to take subclasses of `csv.writer`. (Or at least I assume that's the intention. Notably, `_csv.Dialect` has a `strict` attribute that `csv.Dialect` lacks.)

**Comment by hauntsaninja** [comment]
Thanks for finding!

It's confusing to me that there is csv.Dialect and _csv.Dialect. @JelleZijlstra suggested this was for performance reasons. Given that all the CPython code I can see seems to duck type around dialects, maybe the right thing to do is to just re-export _csv.Dialect in csv.

Seems like `strict` is documented for `csv.Dialect`, so maybe it's a bug in CPython that it's not mentioned in csv.py? (https://docs.python.org/3/library/csv.html#csv.Dialect.strict)
