### ISSUE TITLE
asyncio.AbstractChildWatcher missing

### ISSUE THREAD

**Issue by niklasf** [python/typeshed#3644]
```
error: Name 'asyncio.AbstractChildWatcher' is not defined
```

https://docs.python.org/3/library/asyncio-policy.html#asyncio.AbstractChildWatcher

**Comment by srittau** [comment]
There are a few FIXMEs in the asyncio stubs about this class missing. PR welcome!

**Comment by hoefling** [comment]
@srittau looks like this issue is resolved by #3664.
