### ISSUE TITLE
subprocess.Popen typing divergence

### ISSUE THREAD

**Issue by JasonGilholme** [python/typeshed#3646]
Hi.

I noticed the other day that the `stdin`, `stdout`, and `stderr` properties of the `subprocess.Popen` object were `Optional`.  A closer inspection showed that they are not `Optional` in the python 3 stubs, but the runtime implementations I looked at were.  is this an oversight or something done by design?

py2 stub:  https://github.com/python/typeshed/blob/master/stdlib/2/subprocess.pyi#L81
py3 stub: https://github.com/python/typeshed/blob/master/stdlib/3/subprocess.pyi#L837

If the python 3 stub needs to be updated just let me know and I'll be more than happy to make a quick change.

J

**Comment by srittau** [comment]
This looks like an oversight. PR welcome!
