### ISSUE TITLE
imaplib's CommandResults has unnecessary `Any`

### ISSUE THREAD

**Issue by dkg** [python/typeshed#3654]
In `imaplib`, `CommandResults` is too generic.

[`imaplib`'s documentation](https://docs.python.org/3/library/imaplib.html) says:

> Each command returns a tuple: `(type, [data, ...])` where type is usually `'OK'` or `'NO'` , and *data* is either the text from the command response, or mandated results from the command. Each *data* is either a string, or a tuple. If a tuple, then the first part is the header of the response, and the second part contains the data (ie: ‘literal’ value).

However, use of imaplib in python3 reveals this documentation to date from py2's confusion between bytes and strings, [because the "strings" are actually `bytes`](https://bugs.python.org/issue39447).

**Comment by hauntsaninja** [comment]
Closing based on discussion in #3655
