### ISSUE TITLE
range.index() takes exactly one argument

### ISSUE THREAD

**Issue by ilai-deutel** [python/typeshed#3660]
`range.index()` does not accept `start` and `stop` arguments (the documentation was fixed in python/cpython#13075):

```python
>>> range(1, 9).index(1, 0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: index() takes exactly one argument (3 given)
```

The stub file indicates that 3 arguments can be given. However, removing these extra arguments makes mypy complain about the signature of `index` being incompatible with supertype `Sequence`.

https://github.com/python/typeshed/blob/ce42c16e03b14106cdd41870a9782dce0bd17e42/stdlib/2and3/builtins.pyi#L1093
https://github.com/python/typeshed/blob/ce42c16e03b14106cdd41870a9782dce0bd17e42/stdlib/3/typing.pyi#L278

**Comment by srittau** [comment]
You can add a `# type: ignore` comment to the line mypy is complaining about. It will work.
