### ISSUE TITLE
socketserver: Missing (Forking/Threading)MixIn definitions

### ISSUE THREAD

**Issue by whonore** [python/typeshed#3666]
These classes have empty stubs, so something like
```
serv = ThreadedTCPServer(("localhost", 0), MyHandler)
serv.daemon_threads = True
```
raises a typechecking error.

**Comment by srittau** [comment]
I assume this is about socketserver. PR welcome, even if it just adds `__getattr__` methods to the classes or the module in question for now (see documentation).
