### ISSUE TITLE
Missing badmodules from ModuleFinder

### ISSUE THREAD

**Issue by Andrew1973** [python/typeshed#3667]
Python 3.7, seeing 

error: "ModuleFinder" has no attribute "badmodules"; maybe "modules", "add_module", or "load_module"?

modulefinder.py has 

class ModuleFinder:

    def __init__(self, path=None, debug=0, excludes=[], replace_paths=[]):
        if path is None:
            path = sys.path
        self.path = path
        self.modules = {}
        self.badmodules = {}
        self.debug = debug

    def _add_badmodule(self, name, caller):
        if name not in self.badmodules:
            self.badmodules[name] = {}
        if caller:
            self.badmodules[name][caller.__name__] = 1
        else:
            self.badmodules[name]["-"] = 1

**Comment by srittau** [comment]
PR welcome!
