### ISSUE TITLE
Incorrect re.compile type error? Argument 1 to "compile" has incompatible type "str"; expected "bytes"

### ISSUE THREAD

**Issue by Hubro** [python/typeshed#3671]
Here is my code:

```python
def generate_path_regex(tokens: List[str]) -> Pattern[AnyStr]:
    """(Pruned for brevity)"""

    segment_template = r'(?:[a-z0-9\-]+:)?%s(?:=\{[^/]+\})?'

    return re.compile(
        '^/' + '/'.join(segment_template % x for x in tokens)
    )
```

Running mypy on this file:

```
$ mypy my-file.py
my-file.py:204:9: error: Argument 1 to "compile" has incompatible type "str"; expected "bytes"
```

Am I wrong in assuming that re.compile should accept a `str` argument? :thinking: 

---

I'm using Python 3.8.0 with mypy 0.761.

~~I'm not entirely sure how typeshed fits together with mypy, so my apologies in advance if this is the wrong repo to file this under.~~ Ok apparently mypy includes typeshed, so this appears to be the right repo to file this under.

**Comment by srittau** [comment]
This is not a problem with mypy or typeshed. `AnyStr` is an typevar, bound to `str` and `bytes`. Type vars only make sense if you use at least two instances, which is not the case in your example, and this leads to problems. Since `re.compile()` will return a string pattern when passed a string pattern, you should annotate your function like this:

```python
def generate_path_regex(tokens: List[str]) -> Pattern[str]:
```

**Comment by Hubro** [comment]
@srittau Wow, that did it! I had no idea the return type annotation of the parent function could affect the parameter types of a function call... That kinda blows my mind!

Thanks for the tip :)

**Comment by JelleZijlstra** [comment]
If it helps, my understanding is that mypy typechecks the body of functions using type variables with value restrictions (such as AnyStr) twice: once with the TypeVar set to one of the restrictions, once to the other. So in this case, when it typechecks the function with AnyStr -> bytes, it expects the function to return `Pattern[bytes]` and produces the error you report.
