### ISSUE TITLE
stubs for ConfigParser.getint() etc are too strict

### ISSUE THREAD

**Issue by brianmaissy** [python/typeshed#3681]
Consider the following snippet:

`my_value: Optional[int] = config.getint('mysection', 'myoption', fallback=None)`

Mypy complains:

> error: Argument "fallback" to "getint" of "RawConfigParser" has incompatible type "None"; expected "int"

It is currently typed like this (in typeshed):

`def getint(self, section: str, option: str, *, raw: bool = ..., vars: Optional[_section] = ..., fallback: int = ...) -> int: ...`

While I can understand the desire to type it that way, it prohibits the (I think legitimate) use above. Couldn't it be typed something like this instead?

`def getint(self, section: str, option: str, *, raw: bool = ..., vars: Optional[_section] = ..., fallback: T = ...) -> Union[int, T]: ...`

The some goes for `getfloat` and `getboolean`

**Comment by srittau** [comment]
This will require an overload for the case where `fallback` is not supplied, because otherwise `T` is undefined. But apart from that it sounds reasonable. PR welcome!
