### ISSUE TITLE
wrong signature for param to `socket.getaddrinfo`

### ISSUE THREAD

**Issue by tikki** [python/typeshed#3688]
Hi,

the 4th param to [`socket.getaddrinfo` in py3](https://docs.python.org/3/library/socket.html#socket.getaddrinfo) is named `type`, but at one point in the typeshed stub it got [changed to `socktype`](https://github.com/python/typeshed/commit/70e39d9ad2ea90a330b12b0337c16f7a671ed0bc), which makes mypy wrongly report an error. It is only called [`socktype` in py2](https://docs.python.org/2/library/socket.html#socket.getaddrinfo).

**Comment by srittau** [comment]
PR welcome!
