### ISSUE TITLE
csv.DictReader.fieldnames should be Optional[Sequence[str]]

### ISSUE THREAD

**Issue by daveware-nv** [python/typeshed#3713]
`csv.DictReader.fieldnames` defaults to `None`, and gets set by reading the first line of data. However if there is no first line of data it remains `None`. Since `fieldnames` is not marked as `Optional` code doing `None` checks like the following will result in `error: Statement is unreachable`

```python
import csv

def check_reader(reader: csv.DictReader) -> None:
    if reader.fieldnames is None:
        msg = 'some error message'
        raise ValueError(msg)
```

**Comment by hauntsaninja** [comment]
Looks like it got missed in https://github.com/python/typeshed/pull/3534. PR welcome!
