### ISSUE TITLE
Py3k unittest stubs missing unittest.mock module

### ISSUE THREAD

**Issue by drakedevel** [python/typeshed#372]
Pretty self-explanatory, and probably impacts a lot of testsuites:

```
(app) vm:/tmp/test4$ echo 'from unittest import mock' > test.py; mypy test.py
test.py:1: error: Module has no attribute 'mock'
```

**Comment by matthiaskramm** [comment]
If we do add unittest.mock, it probably should be `Any`.

Could you submit a PR?

**Comment by mkurnikov** [comment]
Is there any specific reason why `unittest.mock` module isn't present, except for the fact that nobody've added it yet?

**Comment by gvanrossum** [comment]
Our labor force is limited. You're welcome to submit a PR!

**Comment by drakedevel** [comment]
Got distracted -- will try to submit a PR this weekend if nobody else gets to it
On Jul 20, 2016 10:12 AM, Guido van Rossum <notifications@github.com> wrote:Our labor force is limited. You're welcome to submit a PR!

**Comment by showell** [comment]
I recently found errors that are probably related.  Right now it's not blocking me, and I don't know enough to submit a PR, so this is just a data point.  Hope it helps!

```
tools/test-tools:6: error: Module has no attribute 'TestLoader'
tools/test-tools:24: error: "TextTestRunner" has no attribute "run"
```

These were both from a file with `import unittest`.
