### ISSUE TITLE
[3.8] int and fractions.Fraction report as having no `as_integer_ratio` member erroneously

### ISSUE THREAD

**Issue by Starwort** [python/typeshed#3730]
I would fix this if I understood the layout - but there is no builtins/fractions typing information in the /3/ folder that I can tell
Both `(1).as_integer_ratio()` and `fractions.Fraction().as_integer_ratio()` work in the console but throw errors with mypy

**Comment by srittau** [comment]
`as_integer_ratio()` was added in #3337 and your examples work with the latest mypy (0.761).

**Comment by JelleZijlstra** [comment]
As for your confusion about directory layout, the builtins module is in `stdlib/2and3/` because we use the same file for Python 2 and 3.

**Comment by hauntsaninja** [comment]
This is documented in https://github.com/hauntsaninja/typeshed/blob/master/CONTRIBUTING.md#stub-versioning
