### ISSUE TITLE
cryptography: `mode` argument to `Cipher.__init__` is optional

### ISSUE THREAD

**Issue by ra-kete** [python/typeshed#3735]
In the type stubs for the third-party lib cryptography, the `mode` argument of [`cryptography.hazmat.primitives.ciphers.Cipher`](https://github.com/python/typeshed/blob/39008d51c15906f86b57466fb8001f0031561e61/third_party/2and3/cryptography/hazmat/primitives/ciphers/__init__.pyi#L25) is specified to be of type `Mode`. However, looking at [the documentation](https://cryptography.io/en/latest/hazmat/primitives/symmetric-encryption/), there are ciphers that expect `mode=None` (`ChaCha20` and `ARC4`). So the type should be `Optional[Mode]` instead.

**Comment by srittau** [comment]
PR welcome!
