### ISSUE TITLE
Stub for `logging.Logger._log` is missing

### ISSUE THREAD

**Issue by AndreyMZ** [python/typeshed#3743]
### Problem description
Stub for `logging.Logger._log` is missing. (See the stub for [`logging.Logger`](https://github.com/python/typeshed/blob/91deb7a79f9eff58a8ff02566e7da9eb06a99ec6/stdlib/2and3/logging/__init__.pyi#L48).)

### Steps to reproduce
(E.g. in PyCharm.)
```test.py
import logging
def test(logger: logging.Logger, level, msg, *args, **kwargs):
	# noinspection PyProtectedMember
	logger._log(level, msg, *args, **kwargs)
```

#### Actual result
> Unresolved attribute reference '_log' for class 'Logger'

#### Expected result
No errors/warnings.

**Comment by srittau** [comment]
PR welcome (with an `# undocumented` comment)!
