### ISSUE TITLE
ipaddress.IPv6Network missing subnet_of member

### ISSUE THREAD

**Issue by kvdveer** [python/typeshed#3774]
Self-contained example, runs succesfully under python 3.7, but fails mypy tests:

```python
import ipaddress


net1: ipaddress.IPv6Network = ipaddress.ip_network('1234::/32')
net2: ipaddress.IPv6Network = ipaddress.ip_network('1234::/64')

assert net2.subnet_of(net1)
```

mypy output:
```
mypy_ipnetwork.py:7: error: "IPv6Network" has no attribute "subnet_of"
```

Same goes for ipv4 network.

**Comment by lladhibhutall** [comment]
This seems doable for a beginner, @srittau any pointer where to start?

**Comment by srittau** [comment]
@lladhibhutall `stdlib/3/ipaddress.pyi` has the definitions for `IPv4Network` and `IPv6Network`. The method needs to be added there in the correct class. It's possible that this method is defined on a common superclass of the two concrete classes, this needs to be checked against the implementation.

`supernet_of` is also missing and should be added at the same time. Both methods were added in Python 3.7, so they need to be guarded with a `version_info` check. (See other files for examples.)

**Comment by lladhibhutall** [comment]
@srittau In the same module, there is the function called `compare_networks` which has been deprecated in 3.7, should I put a `version_info` check on that as well?

**Comment by srittau** [comment]
As long as the functions are still available, they should stay in the stubs. We generally try to follow the implementation as close as possible.

**Comment by lladhibhutall** [comment]
@srittau `tests/check_consistent.py` is failing because `third_party/2/ipaddress.pyi` does not match file `stdlib/3/ipaddress.pyi`. Should I just copy the changes there as well?

**Comment by srittau** [comment]
@lladhibhutall Yes, please. They will ignored there anyway, because of the version_info check.
