### ISSUE TITLE
Missing tkinter.Variable.trace_add ...

### ISSUE THREAD

**Issue by petsuter** [python/typeshed#3778]
[Python 3.6 added](https://docs.python.org/3.6/whatsnew/3.6.html?highlight=trace_add#tkinter) methods `trace_add()`, `trace_remove()` and `trace_info()` in the `tkinter.Variable` class. These are still missing in typeshed.

**Comment by srittau** [comment]
PR welcome!

**Comment by hauntsaninja** [comment]
Fixed in #3797
