### ISSUE TITLE
Missing standard library xml

### ISSUE THREAD

**Issue by xorsyst-python** [python/typeshed#3787]
I'm getting

error: No library stub file for standard library module 'xml.dom.minidom'
note: (Stub files are from https://github.com/python/typeshed)
error: No library stub file for standard library module 'xml.dom'
error: No library stub file for standard library module 'xml.dom.expatbuilder'
error: No library stub file for standard library module 'xml.sax.expatreader'
error: No library stub file for standard library module 'xml.dom.pulldom'

I've updated mypy

**Comment by jermenkoo** [comment]
I can have a stab at some of them

**Comment by srittau** [comment]
@jermenkoo That would be appreciated!

**Comment by lladhibhutall** [comment]
@jermenkoo Are you still working on it?

**Comment by jermenkoo** [comment]
@lladhibhutall we can split it, just pick one of `xml` sub-modules and create a typestub for that

**Comment by lladhibhutall** [comment]
@jermenkoo Since you have been working on it for longer, you can tell me which ones you have already worked on so that I don't work on the same by mistake.

**Comment by jermenkoo** [comment]
I was working on `xml.dom.pulldom` - everything else is upforgrabs! Let me know which one you pick so that we sync about the work here

**Comment by lladhibhutall** [comment]
@jermenkoo Cool, I will pick up the `xml.sax.expatreader`

@srittau Should we just work on the modules mentioned in the issue? There are few other modules for which stubs are not present in typeshed.

**Comment by srittau** [comment]
@lladhibhutall Any additions are appreciated.

**Comment by hauntsaninja** [comment]
Progress has been made on this. The stubs that are very incomplete are:
```
xml.dom.pulldom
xml.dom.expatbuilder
xml.dom.xmlbuilder
```
There are missing type annotations in the others, but definitions should be more complete.
