### ISSUE TITLE
json's stubs are incomplete

### ISSUE THREAD

**Issue by rmcgibbo** [python/typeshed#38]
I just noticed that the stubs for `json.dump` and `json.dumps` do not include some of the keyword arguments, like `indent`.

**Comment by gvanrossum** [comment]
Can you sumbit a PR?

On Sunday, January 10, 2016, Robert T. McGibbon <notifications@github.com>
wrote:

> I just noticed that the stubs for json.dump and json.dumps do not include
> some of the keyword arguments, like indent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python/typeshed/issues/38>.
>


-- 
--Guido (mobile)

**Comment by rmcgibbo** [comment]
On its way :smile:.
