### ISSUE TITLE
Importlib's PathFinder has an incorrect interface definition

### ISSUE THREAD

**Issue by sangaline** [python/typeshed#3801]
The [`importlib.machinery.PathFinder`](https://github.com/python/typeshed/blame/256b3ce8aba6080f9a1c90c8c264e93e49e754cd/stdlib/3/importlib/machinery.pyi#L84) stub indicates that it has the same interface as `importlib.abc.MetaPathFinder`. This is incorrect because the `find_module()`, `invalidate_caches()`, and `find_spec()` methods are class methods in `PathFinder` and instance methods in `MetaPathFinder`. It also has additional `_path_hooks()`, `_path_importer_cache`, `_legacy_get_spec()`, `_get_spec()`, and `find_distributions()` methods that aren't included in the type definition.

A quick reproducible example:

```python
from importlib.machinery import PathFinder

PathFinder.find_module('exodus')
```

results in:

```
t.py:3: error: Too few arguments for "find_module" of "MetaPathFinder"
t.py:3: error: Argument 1 to "find_module" of "MetaPathFinder" has incompatible type "str"; expected "MetaPathFinder"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by hauntsaninja** [comment]
Yes, I believe some arguments to those methods are also missing default values in the stubs. PR welcome, it would be great if we could get to a point where we no longer have to whitelist these methods in tests: https://github.com/python/typeshed/blob/master/tests/stubtest_whitelists/py3_common.txt#L332

**Comment by lladhibhutall** [comment]
@sangaline @hauntsaninja Working on a patch, other than `find_module()`, `invalidate_caches()`, and `find_spec()` the remaining methods are undocumented, just wondering if we need stubs for those.
