### ISSUE TITLE
asyncio.create_task returns a Task of type Any

### ISSUE THREAD

**Issue by SKHecht** [python/typeshed#3803]
https://github.com/python/typeshed/blob/master/stdlib/3/asyncio/tasks.pyi#L126

The type annotation for `create_task` is:
```
        def create_task(
            coro: Union[Generator[Any, None, _T], Awaitable[_T]], *, name: Optional[str] = ...,
        ) -> Task[Any]: ...
```
Why not annotate the return as `Task[_T]`? It appears to me that the `Task` class supports this and it would be more correct. But given that this wasn't done in the first place makes me wonder perhaps there is a reason this doesn't work?

There's a couple other instances of this, in particular in the `Task` class itself

**Comment by JelleZijlstra** [comment]
Looks like the Any was added as part of a blanket change in https://github.com/python/typeshed/pull/3288/files#diff-3a5b272bf63f81e5766e3137d2eafd51. I think you're right and we should make it be `_T`.

**Comment by lladhibhutall** [comment]
@SKHecht @JelleZijlstra Anybody working on this? It seems like the issue is easy enough that a beginner can work on.

**Comment by lladhibhutall** [comment]
@JelleZijlstra I am working on it
