### ISSUE TITLE
Issue with function to customize argparse formatter class

### ISSUE THREAD

**Issue by lucatrv** [python/typeshed#3806]
I'm reopening here the issue originally opened for mypy, see [reply](https://github.com/python/mypy/issues/8487#issuecomment-594271309).

I'm using mypy 0.761 with Python 3.8.2 on Windows.

The suggested way to customize the argparse formatter class to control text width is to use a lambda function, as follows:

```python
formatter = lambda prog: argparse.HelpFormatter(prog, width=100)
parser = argparse.ArgumentParser(description=dummy_text, formatter_class=formatter)
```

but with that code mypy emits the following error:

```
541: error: Argument "formatter_class" to "ArgumentParser" has incompatible type "Callable[[Any], RawDescriptionHelpFormatter]"; expected "Type[HelpFormatter]"
```

I could not find any workaround, the only solution is to avoid a function and redefine the formatter class.

See [example](https://stackoverflow.com/questions/44333577/explain-lambda-argparse-helpformatterprog-width) and [discussion](https://bugs.python.org/issue39809?@ok_message=msg%20363254%20created%0Aissue%2039809%20message_count%2C%20messages%20edited%20ok&@template=item).

**Comment by srittau** [comment]
The `formatter_class` argument and `field` should be typed using a callable protocol. Its just called once like this:

```python
        return self.formatter_class(prog=self.prog)
```
