### ISSUE TITLE
math.nan is not a float

### ISSUE THREAD

**Issue by sleighsoft** [python/typeshed#3823]
I am using mypy to do type checking:

```python
import math
minimum = 0.0
def fn() -> float:
    if minimum == 0:
        return math.nan
    return 1.0 / minimum
```

And it outputs: `Returning Any from function declared to return "float"  [no-any-return]`.

But
```python
isinstance(math.nan, float) == True
```

I assume this is not an issue with mypy, but correct me if I am wrong.

**Comment by srittau** [comment]
I cannot reproduce the problem with mypy 0.761 and Python 3.5.3. What versions are you using?

**Comment by sleighsoft** [comment]
```python
mypy==0.761
mypy-extensions==0.4.3

python = 3.7.5
```

I am honestly confused. I copied my file that includes the error and when I execute `mypy` on the copy everything is green, but when I do it on the original I get the aforementioned error..

**Comment by sleighsoft** [comment]
Looking further into this I think it is not a bug within typeshed or mypy. It is an issue of how mypy resolves/installs my project to do type analysis. I'll close this for now and if I should have any further issue with this I'll just comment here. Thanks for confirming that it indeed works @srittau
