### ISSUE TITLE
format_map over specified

### ISSUE THREAD

**Issue by jaraco** [python/typeshed#3824]
The [definition of format_map](https://github.com/python/typeshed/blob/92d53086be540c3eb6ead1967b32854689e4e7c3/stdlib/2and3/builtins.pyi#L436) indicates that the input is a `Mapping[str, Any]` when a `Mapping` is over-specified. `format_map` only requires the `__getitem__` interface of a `Mapping` (not `__iter__` nor `__len__`). Requiring `Mapping` forces someone writing an adapter to supply a full `Mapping` implementation for no purpose.

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR changing the argument type to a Protocol that just has `__getitem__`.

**Comment by lladhibhutall** [comment]
@jaraco Are you working on this?

**Comment by jaraco** [comment]
I am not. I would be delighted if someone else would work on it.
