### ISSUE TITLE
typing.ForwardRef missing from stdlib stub

### ISSUE THREAD

**Issue by DMR-coding** [python/typeshed#3867]
The `ForwardRef` class is exported from the stdlib `typing` module, and is public per the documentation as of Python 3.7 (https://docs.python.org/3.7/library/typing.html#typing.ForwardRef). However, it is not included in the `typing` stub.

**Comment by JelleZijlstra** [comment]
PRs are welcome!

**Comment by lladhibhutall** [comment]
@DMR-coding Are you working on it?

**Comment by DMR-coding** [comment]
I don't have the domain knowledge to contribute code in Typeshed right now. I might be able to spin up at some point in the future if nobody's snagged this by then.
