### ISSUE TITLE
mimetypes.guess_type typing wrong for python 3.8

### ISSUE THREAD

**Issue by Mattwmaster58** [python/typeshed#3873]
Since python 3.8, [`mimetypes.guess_type()` supports a Path object as a well a str](https://docs.python.org/3/library/mimetypes.html?highlight=mimetypes#mimetypes.guess_type)

**Comment by lladhibhutall** [comment]
@Mattwmaster58 You are working on this? I can submit a patch!

**Comment by Mattwmaster58** [comment]
@lladhibhutall I'm not working on it ATM
