### ISSUE TITLE
[question] dictionary _KT typevar and hashability

### ISSUE THREAD

**Issue by BvB93** [python/typeshed#3884]
Dear all,

I recently noticed that the [``_KT``](https://github.com/python/typeshed/blob/71804c38fc07eb6cbab5ae38ef3d4c8651e4fef5/stdlib/2and3/builtins.pyi#L27) typevar used in annotating [``dict``](https://github.com/python/typeshed/blob/71804c38fc07eb6cbab5ae38ef3d4c8651e4fef5/stdlib/2and3/builtins.pyi#L964) has no upper ``bound`` specified, yet dictionary keys must (as far as I'm aware) always be hashable.

Is there a reason here as to why ``_KT`` is not defined as ``TypeVar('_KT', bound=Hashable)``?

Regards, Bas

**Comment by JelleZijlstra** [comment]
The `Hashable` type can't really be typechecked (because all types are hashable by default); see prior discussion in #2148, python/mypy#1746, python/mypy#2455.

**Comment by BvB93** [comment]
Thanks for the info!
I'd consider this question answered.

**Comment by ikonst** [comment]
Given that certain types are marked as non-hashable (#3219) wouldn't this have at least a fringe value?
