### ISSUE TITLE
ftplib.all_errors: invalid type definition

### ISSUE THREAD

**Issue by Kazy** [python/typeshed#3893]
Hello.

In `ftplib.pyi`, `all_errors` is defined as `Tuple[Exception, ...]` (see https://github.com/python/typeshed/blob/master/stdlib/2and3/ftplib.pyi#L40). This seems to be incorrect because `all_errors` doesn't contain instances of `Exception` but classes (see https://github.com/python/cpython/blob/master/Lib/ftplib.py#L66). It can't otherwise be used in an `except` clause. It should be I believe `Tuple[Type[Exception], ...]`.

Let me know if I should open a PR for that.

**Comment by srittau** [comment]
A PR would be appreciated!
