### ISSUE TITLE
statistics.median_low and median_high accept more than float, Decimal, Fraction

### ISSUE THREAD

**Issue by ramalho** [python/typeshed#3894]
Evidence:

```
>>> import statistics
>>> l = ['b', 'v', 'c', 'l']
>>> statistics.median_low(l)
'c'
```

However, the stub for `median_low` says:

```
def median_low(data: Iterable[_Number]) -> _Number: ...
```

The items must be comparable. I'll do some research and propose a pull request.

**Comment by srittau** [comment]
Same for `median()` and `median_high()`.

**Comment by ramalho** [comment]
@srittau `median()` is not as flexible: if there is an even number of items, it needs to interpolate, so the items need to support `+` and `/`. I'd say it's OK to annotate `median()` with type `_Number`. But not `median_high()` and `median_low()`.

```
>>> from statistics import *
>>> l = ['b', 'v', 'c', 'l']
>>> median_low(l)
'c'
>>> median(l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/statistics.py", line 435, in median
    return (data[i - 1] + data[i])/2
TypeError: unsupported operand type(s) for /: 'str' and 'int'
>>> median(l[:3])
'c'
```

**Comment by lladhibhutall** [comment]
@ramalho I can submit a patch if you want?

**Comment by ramalho** [comment]
Thanks for your patch, @lladhibhutall. However, I don't think it addresses the issue. It's not just a matter of adding support for `str`.

The real issue is that those functions work with any objects that can be ordered. I was told somewhere else that a PEP 544 protocol would solve this issue, but I haven't understood PEP 544 yet, so I don't know where to start... except studying PEP 544 which I will do but will take some time...

**Comment by hauntsaninja** [comment]
You'll also need a TypeVar, as mentioned in https://github.com/python/typeshed/pull/3912#issuecomment-610562644

A good place to read about Protocols, or in general, any typing feature which mypy supports is the mypy documentation: https://mypy.readthedocs.io/en/stable/protocols.html. Feel free to ask here if you have questions.

**Comment by lladhibhutall** [comment]
@ramalho I am closing the PR for now, couldn't find time to go through it. Please feel free to assign the issue to someone else.

**Comment by srittau** [comment]
@lladhibhutall Thank you for looking into this.

**Comment by ramalho** [comment]
I made some progress. This protocol satisfies the `sorted()` call inside `median_low` and `median_high`:

```python
class Sortable(Protocol):
    def __lt__(self, other):
        ...
```

However, if I declare `median_low` like below, I get back a `Sortable` which I need to cast to some useful type:

```python
def median_low(data: Iterable[Sortable]) -> Sortable: ...
```

How could I use a TypeVar to solve this problem? Thanks for any help!

**Comment by JelleZijlstra** [comment]
You'd need to define a `_SortableT = TypeVar("_SortableT", bound=Sortable)`, then use the typevar instead of both occurrences of Sortable in the definition you posted just now.
