### ISSUE TITLE
asyncio python 3.9 stub syntax error

### ISSUE THREAD

**Issue by Gelbpunkt** [python/typeshed#3901]
Hi,
I'm running mypy with python 3.9.0a5 and keep getting this error:
`/usr/local/lib/python3.9/site-packages/mypy/typeshed/stdlib/3/asyncio/__init__.pyi:97: error: syntax error in type comment`

I am not familiar with pyi formatting, I would have loved to fix this, but I cannot see the issue.
The related line is `DefaultEventLoopPolicy: Type[AbstractEventLoopPolicy]`.

**Comment by JelleZijlstra** [comment]
This is python/mypy#8614.
