### ISSUE TITLE
subprocess.CompletedProcess incompatibly redefined

### ISSUE THREAD

**Issue by GPHemsley** [python/typeshed#3909]
Typehinting with `subprocess.CompletedProcess` results in the following error:
>  error: Missing type parameters for generic type "CompletedProcess"

Adding a type parameter (like `bytes`), however, results in the following error at runtime:
> TypeError: 'type' object is not subscriptable

This is because the real `subprocess.CompletedProcess` is not a generic type; it is redefined as one in the type stub.

See also PyCQA/pylint#3240.

**Comment by srittau** [comment]
You need to either use `from __future__ import annotations` (Python 3.7+) or quote the type annotation to prevent runtime errors. pylint supports both forms IIRC.

**Comment by GPHemsley** [comment]
Oh. It is not clear in any of the `typing` documentation that a quoted string is a valid type hint. The only mention of it (in retrospect) is in the context of using `TYPE_CHECKING`.

**Comment by srittau** [comment]
This is documented in [PEP 484](https://www.python.org/dev/peps/pep-0484/#forward-references). I have to admit, though, that a comprehensive typing guide is missing. Currently the information is spread between PEP 484, the mypy documentation, and the typing module documentation.
