### ISSUE TITLE
`flask.request.input_stream` has `getvalue` but `mypy` says it does not

### ISSUE THREAD

**Issue by adamtheturtle** [python/typeshed#3911]
Take the following example code (`example.py`):

```python
from flask import Flask, request
app = Flask(__name__)

@app.route('/')
def hello_world() -> str:
    print(type(request.input_stream))
    print(request.input_stream.getvalue())
    return ''

client = app.test_client()
client.get('/')
```

`pip install flask mypy`

```sh
$ python example.py
<class '_io.BytesIO'>
b''
$ mypy example.py
example.py:16: error: invalid syntax
Found 1 error in 1 file (checked 1 source file)
```

As the code is valid, I expect there to be no error.

```
$ pip freeze
click==7.1.1
Flask==1.1.2
itsdangerous==1.1.0
Jinja2==2.11.1
MarkupSafe==1.1.1
mypy==0.770
mypy-extensions==0.4.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
Werkzeug==1.0.1
```

**Comment by srittau** [comment]
`request.input_stream` is just a wrapper around the `wsgi.input` field defined in [PEP 3333](https://www.python.org/dev/peps/pep-3333/). From what I understand, it's just an implementation detail that it is a `BytesIO` when flask is run from the command line.

**Comment by adamtheturtle** [comment]
Thank you for your response @srittau.

> when flask is run from the command line

I'm not sure what you mean by this but the Flask endpoint is being run here from its `werkzeug` test client.

I'm not an expert in this, but a few things lead me to think that I should not get a `mypy` error.

* The code works - my interpretation of the `mypy` error is that the code will not work

> From what I understand, it's just an implementation detail

I'm not sure how to differentiate between the types used in the application and implementation details. However, the tests and examples are maybe a good indicator,

* `werkzeug` examples and tests use objects for `input_stream` which have and *rely on* `getvalue()`

https://werkzeug.palletsprojects.com/en/1.0.x/quickstart/ -


```
request = Request.from_values(query_string='foo=bar&blah=blafasel',
...    content_length=len(data), input_stream=StringIO(data),
...    content_type='application/x-www-form-urlencoded',
...    method='POST')
```

**Comment by srittau** [comment]
When running tests, the tests control the WSGI environment and therefore the type of `Request.input_stream`. As a counter-example, the type of `Request.input_stream` when running a werkzeug app under Apache & mod_wsgi is `mod_wsgi.Input`.

**Comment by adamtheturtle** [comment]
I'll happily defer to your understanding if you wish to close this, and thank you for the explanation.

My expectation as a user is always that if my code works and thoroughly annotated, `mypy` should not complain. I understand that this might not be a perfect mindset. My expectation, if that were the perfect mindset, would be perhaps for the `input_stream` annotation to be a `Union` of what it currently is with whatever else is supported by `werkzeug`. However, yes, that might mean someone uses `getvalue`, `mypy` does not complain and then their code breaks.

**Comment by adamtheturtle** [comment]
@srittau I now understand what you were saying. You are right - when running this code as a server, and then running a request against the server, we get:

```
AttributeError: '_io.BufferedReader' object has no attribute 'getvalue'
```

I think that this is an issue with the test client not behaving as a real client would, rather than a typeshed issue.

**Comment by adamtheturtle** [comment]
Thank you for your insight!
