### ISSUE TITLE
Missing type information for cached_property decorator (new in Py3.8)

### ISSUE THREAD

**Issue by rmorshea** [python/typeshed#3915]
This was added in Python 3.8:

https://docs.python.org/3.8/library/functools.html?highlight=s#functools.cached_property

I don't see a Python 3.8 specific directory here yet so perhaps there's already an effort under way to add one.

**Comment by hauntsaninja** [comment]
`functools.cached_property` is present in the stubs, see https://github.com/python/typeshed/blob/master/stdlib/3/functools.pyi#L91
For more information on how typeshed does versioning, see https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#stub-versioning

**Comment by rmorshea** [comment]
Hmm maybe I have an old MyPy version and that's why it doesn't recognize it.
