### ISSUE TITLE
type for SSLContext.options is Enum and not int (at least in py3.8)

### ISSUE THREAD

**Issue by dimaqq** [python/typeshed#3920]
As far as I can see `typeshed` declares it as an int here:

https://github.com/python/typeshed/blob/b3c86bd7ff9fb5fa485d7f4ca2e9ecdb8bbe9ab8/stdlib/2and3/ssl.pyi#L249-L251

However, in modern Python it's actually an Enum, and I can use it like this here:

https://github.com/HENNGE/aapns/blob/5ae57478be8cf5438d631ec8c5b82526990af8c7/src/aapns/connection.py#L100-L105

Inlined: `OP_NO_TLSv1 not in ssl_context.options`

Upon which, `mypy` complains that `Unsupported right operand type for in ("int")`

**Comment by srittau** [comment]
According to the docs, `options` was changed in 3.6 to an enum. PR welcome!

**Comment by rohitkg98** [comment]
It works for me. An Enum Options was added in #4152. Should we close this issue now?
