### ISSUE TITLE
mypy complains about heapq: Module has no attribute "_heapify_max"

### ISSUE THREAD

**Issue by aabramovrepo** [python/typeshed#3926]
Hi All,

   running `mypy` over the piece of code:

```
# build max heap in place
def build_max_heap_inplace(nums: List[int]) -> None:
    heapq._heapify_max(nums)
```

reports the following error:

`error: Module has no attribute "_heapify_max"`

However, `_heapify_max` exists in the installed `heapq` module. Does anybody have an idea? The error arises as soon as I start annotating the function. Without any type annotation (for both return value and arguments) `mypy` does not complain.

Thanks a lot in advance!

Best,
Alexey

**Comment by JelleZijlstra** [comment]
This can be fixed by adding the function to the heapq stub at https://github.com/python/typeshed/blob/master/stdlib/3/heapq.pyi.

**Comment by hauntsaninja** [comment]
(You only get the error once you start annotating, because by default mypy does not check unannotated functions, see first point under https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code)
