### ISSUE TITLE
Remove typing.AwaitableGenerator

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#3932]
As mentioned in the code, AwaitableGenerator doesn't exist in typing.py or PEP 484.
https://github.com/python/typeshed/blob/626a0f3f7353e484e8a6c5d7a2b3f37e4694e132/stdlib/3/typing.pyi#L208

It appears it's an "intentionally undocumented" implementation detail of mypy, as mentioned in https://github.com/python/mypy/issues/2907. Ideally, these shouldn't leak into typeshed. I've created issue https://github.com/python/mypy/issues/8699 in mypy, since that's where action needs to be taken first, but keeping an issue here for tracking.

**Comment by hauntsaninja** [comment]
Similar to #3556 and #2999

**Comment by AlexWaygood** [comment]
I'm closing this as we now have #7580, and I don't think we need both issues to be open when they're about the same thing.
