### ISSUE TITLE
More precise typing of array.array

### ISSUE THREAD

**Issue by ethanhs** [python/typeshed#3946]
`array.array` could be more precisely typed based on the typecode passed in to the constructor:
https://docs.python.org/3/library/array.html

Should be pretty straight forward to fix with overloads and literal values.

Note that it is currently incorrect with code like:

```
from array import array

b = array('d')
reveal_type(b) # E: Revealed type is 'array.array[builtins.int*]'
```

**Comment by aannaassalam** [comment]
Can you please elaborate your problem that you are facing...

**Comment by ethanhs** [comment]
@aannaassalam the string specifier for the constructor decides whether the type of the elements are int, float or str (I'm not certain about the str). Ideally the type would be selected based on the argument
