### ISSUE TITLE
unitest.mock NonCallableMock.assert_has_calls with wrong arg `calls` type

### ISSUE THREAD

**Issue by rodrigondec** [python/typeshed#3949]
# Problem
On line 
https://github.com/python/typeshed/blob/f7d240f06e5608a20b2daac4e96fe085c0577239/stdlib/3/unittest/mock.pyi#L104
The arg `calls` is of type `_CallList` 
https://github.com/python/typeshed/blob/f7d240f06e5608a20b2daac4e96fe085c0577239/stdlib/3/unittest/mock.pyi#L59

But the expected arg is a `Iterable` such as `List`. [As is can be seen on implementation](https://github.com/python/cpython/blob/b8f704d2190125a7750b50cd9b67267b9c20fd43/Lib/unittest/mock.py#L932).

# Solution
Use `List[Call]` on the arg instead of `_CallList`.

# I volunteer to make this PR
just assign it to me if it's accepted.

**Comment by JelleZijlstra** [comment]
PRs would be welcome!
