### ISSUE TITLE
Missing BaseHTTPServer stub file

### ISSUE THREAD

**Issue by herenowcoder** [python/typeshed#395]
Hi,

I'd like to typecheck Python2 code using BaseHTTPServer, whose stub file is missing.

**Comment by gvanrossum** [comment]
We're dependent on contributions for stubs, in general. Perhaps you can submit a PR yourself?

**Comment by herenowcoder** [comment]
Guess it's possible.

Locally I use a hacked `BaseHTTPServer.pyi` which compensates for a lack of another stub, namely for `email.message.Message`. So I could post a PR with both when I will have both done properly.

**Comment by gvanrossum** [comment]
Looking forward to it! (It would be easier to review if they were two
separate PRs, but I can handle a combined PR too if that's your preference.)

**Comment by gvanrossum** [comment]
Oh, one more thing. The email package stubs are a lot more complete for
Python 3. Maybe you can crib something from there (though please also check
the docs and source to see what significant differences might exist).

**Comment by herenowcoder** [comment]
Thanks for the warning.
Luckily, upon checking Py2 sources & docs it occured that it's not `email.message.Message` referenced, but `mimetools.Message` - which has stub in the Py2 subtree already.

Here goes the [PR#397](https://github.com/python/typeshed/pull/397)

**Comment by herenowcoder** [comment]
Great. Now remaining question is how to get it into `mypy` :] ? I saw `typeshed` is a git submodule there. This needs another PR in `mypy` or you guys are syncing submodules periodically..?

**Comment by gvanrossum** [comment]
We sync regularly, 1-2 times weekly, so no more action required.

--Guido (mobile)

**Comment by herenowcoder** [comment]
Cool! That was a great coop, thanks.
