### ISSUE TITLE
issubclass does not support comparison against typing.Generic

### ISSUE THREAD

**Issue by sinback** [python/typeshed#3983]
Here's some code that works:

```
from typing import Tuple, Generic

class Test(Tuple[int]):
    pass


print(issubclass(Test, Generic))
```
(prints True, which is correct I think - Generic is in the mro and Test should be a subclass of it, tuple, and object).

but mypy doesn't like this:

```
example.py:7: error: Argument 2 to "issubclass" has incompatible type "_SpecialForm"; expected "Union[type, Tuple[Union[type, Tuple[Any, ...]], ...]]"
Found 1 error in 1 file (checked 1 source file)
```

which I think is wrong.

It's extra interesting/confusing to me because `type(Generic)` is `type`, not `typing._SpecialForm` :astonished: :question:

**Comment by JelleZijlstra** [comment]
Special forms like `Generic` are pretty magical and the stubs don't necessarily reflect the runtime structure very much. We could maybe make the `_SpecialForm` in typeshed inherit from `type`.

Maybe you should use https://github.com/ilevkivskyi/typing_inspect though? That's generally the more portable way to perform runtime inspection of typing-related stuff.

**Comment by sinback** [comment]
Ooh, thanks for the pointer! Looks like this library has all kinds of stuff in it which would have prevented me from having to learn typing library internals had I... known about the library in the first place 😅 I appreciate the suggestion!

I think it makes sense for `_SpecialForm` to inherit from `type`, but take my opinion with a grain of salt because I'm not overly familiar with how the typing library actually works on the inside...! But like, lots of times, I think typing things should have type as (one of) their type(s). Hehe

**Comment by hauntsaninja** [comment]
I'm not sure we should make `_SpecialForm` inherit from `type`:
```
>>> typing._SpecialForm.__mro__
(<class 'typing._SpecialForm'>, <class 'typing._Final'>, <class 'typing._Immutable'>, <class 'object'>)
>>> type(Union)
<class 'typing._SpecialForm'>
>>> isinstance(Union, type)
False
```
We could make `Generic` an instance of `type` instead of `_SpecialForm`, at least for Python 3.7 and later.
But overall, I'm a little reluctant to go down the rabbit hole of trying to match the magical runtime implementations.

**Comment by thomkeh** [comment]
I encountered a related problem with `Tuple[]` (and also `Union[]` and `Type[]`). The following raises a type error in mypy:
```python
t: type = Tuple[int, float]
```
which was surprising to me. I thought a tuple type is surely a type.

(This might be fixed in python 3.9 when using `tuple[int, float]`; I haven't checked.)

**Comment by hauntsaninja** [comment]
That might also be best fixed by PEP 613

**Comment by JelleZijlstra** [comment]
I don't think there's anything actionable for typeshed here. The TypeForm proposal (python/mypy#9773) may help some of the posters here.
