### ISSUE TITLE
Move __builtin__.pyi and typing.pyi into mypy?

### ISSUE THREAD

**Issue by matthiaskramm** [python/typeshed#399]
`__builtin__.pyi` and `typing.pyi` are files that tend to encode some knowledge of the type-checker that uses them.

Right now, typeshed has the mypy version of these files. (pytype has [it's own version](https://github.com/google/pytype/blob/master/pytype/pytd/builtins/__builtin__.pytd),  and I seem to remember that PyCharm has, as well)

If I'm right about PyCharm, do we want these files in typeshed? Or do we want just barebone versions in typeshed, and move the mypy specifc ones into http://github.com/python/mypy ?

**Comment by gvanrossum** [comment]
Ideally we wouldn't have mypy-specific stuff in there, of course. Do you
see specific things that you believe are not standard PEP 484? I'd hate to
have to maintain these files in even more places than we already do.

**Comment by JelleZijlstra** [comment]
I'd also prefer to keep these stubs in typeshed; I don't think they need to be mypy-specific. As a concrete data point, I recently wrote a tool to extract information from typeshed stubs at https://github.com/JelleZijlstra/typeshed_client, and it can handle builtins.pyi and typing.pyi fine.

I'm happy to review changes that make these files more compatible with pytype or PyCharm.

**Comment by JelleZijlstra** [comment]
@matthiaskramm any objections to closing this?
