### ISSUE TITLE
[distutils.log] Enforced variadic parameter in log func calls

### ISSUE THREAD

**Issue by wereii** [python/typeshed#3998]
**Description**
The second param of the logging calls (`log.info`, `log.debug`, ...) is a variadic argument `*args`, real signature looks something like:

```py
def _LogFunc(msg: str, *args: Any) -> None: ...
```

but the type hint is defined as
`_LogFunc = Callable[[Text, Iterable[Any]], None]`
(then ... `info: _LogFunc`)

which enforces the second argument and throws an error `error: Too few arguments` if only the first param is saturated.
Applies to all levels using `_LogFunc` as type hint in [log.pyi:L18@6dca3f7f](https://github.com/python/typeshed/blob/6dca3f7fc52e84e3c6b512bb4a6d462778d6a692/stdlib/2and3/distutils/log.pyi#L18)

**Reproduce**
- Run mypy on a file with these contents
```py
from distutils import log
log.set_verbosity(2)

log.info("I am not giving you more arguments!")
```
- But if you execute (python3) the file, it's valid and works.

**Expected behavior**
There should be no error when only one/first argument is passed.

**Environment**
- Python 3.8.2
- Ubuntu 20.04
- mypy 0.761 (apt package) | typeshed @ a06abc5 (?)

**Comment by wereii** [comment]
I am can't really say I understand the *.pyi format so please take this with a grain of salt as I might be very much wrong.

Fix proposal
```python
# This is already defined and stays the same
class Log:
    def __init__(self, threshold: int = ...) -> None: ...
    def log(self, level: int, msg: Text, *args: Any) -> None: ...
    def debug(self, msg: Text, *args: Any) -> None: ...
    def info(self, msg: Text, *args: Any) -> None: ...
    def warn(self, msg: Text, *args: Any) -> None: ...
    def error(self, msg: Text, *args: Any) -> None: ...
    def fatal(self, msg: Text, *args: Any) -> None: ...

# Change:
# This is actually exact to how it's done in the code
log: Log().log
debug: Log().debug
info: Log().info
warn: Log().warn
error: Log().error
fatal: Log().fatal
```

**Comment by srittau** [comment]
Good catch. Unfortunately your solution won't work in stubs. The good news is that nowadays we can use a callable protocol to solve this, though:

```python
class _LogFunc(Protocol):
    def __call__(self, __msg: Text, *args: Any) -> Any: ...
```

**Comment by JelleZijlstra** [comment]
The current `distutils.log` stub no longer has this problem. It was fixed before the directory reorg, but I didn't look further for the exact fix.
