### ISSUE TITLE
shutil.make_archive first argument: _AnyStr vs. _Path/ (_AnyPath)

### ISSUE THREAD

**Issue by zdog234** [python/typeshed#4037]
Hi, running mypy over this in python 3.8:

```python3
path = pathlib.Path.cwd() / "some_folder"
shutil.make_archive(path, "zip", root_dir=path.parent, base_dir=path)
```

This code runs fine, but mypy throws an error related to the first argument. When I [pull up typeshed](https://github.com/python/typeshed/blob/master/stdlib/2and3/shutil.pyi#L133), it seems like the first argument has been annotated as `_AnyStr`. This should probably be changed to `_Path` (at least for 3.8, I haven't checked 3.6/3.7 yet)

**Comment by JelleZijlstra** [comment]
PR welcome!

**Comment by zdog234** [comment]
Sweet! I wanted to post an issue first to make sure I wasn't missing something. I'll try to draft a PR soon to make this change (and test in 3.6/3.7 to make sure this isn't 3.8-specific)

**Comment by hauntsaninja** [comment]
https://github.com/python/typeshed/pull/4041#issuecomment-630529941
