### ISSUE TITLE
# type: ignore import not working for python-pytun 

### ISSUE THREAD

**Issue by mrkeuz** [python/typeshed#4039]
Follow instructions as described on section https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

```# type: ignore``` not working

seems lib have only pure c bindings (see: https://github.com/montag451/pytun)

helped only global --ignore-missing-imports flag.

## Environment
$: dmypy run -- --follow-imports=skip .
mypy 0.770
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
[GCC 8.4.0] on linux
Ubuntu 18.04.4 LTS
Linux ubnt 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

![pytun_test – mytun py_002](https://user-images.githubusercontent.com/6247921/82241680-405f4500-9945-11ea-9b05-32cdd598ea5e.jpg)

Thanks for great tooling! Python with typing is very cool!

**Comment by JelleZijlstra** [comment]
Your screenshot is very blurry so it's hard to see what's going on. In any case, this is an issue with mypy, not typeshed.

**Comment by mrkeuz** [comment]
Thanks!
