### ISSUE TITLE
operator.getitem(Sequence, slice) presents error

### ISSUE THREAD

**Issue by posita** [python/typeshed#4043]
When I try something like …

```
# test.py
import operator
print(operator.getitem([1, 2, 3], slice(1, 2)))
```

… I get the following …

```
% python test.py
[2]
% mypy test.py
test.py:3: error: No overload variant of "getitem" matches argument types "List[int]", "slice"
test.py:3: note: Possible overload variants:
test.py:3: note:     def [_T] getitem(Sequence[_T], int) -> _T
test.py:3: note:     def [_K, _V] getitem(Mapping[_K, _V], _K) -> _V
Found 1 error in 1 file (checked 1 source file)
```

Shouldn't this work? I couldn't find a matching issue, but I might have missed it.

**Comment by hauntsaninja** [comment]
Yeah, this should work. PR welcome!

I had a concern over whether this should work for Sequence in general, or only concrete types like list and tuple, but https://docs.python.org/3/reference/datamodel.html#object.__getitem__ states that on sequence types `__getitem__` should accept int and slice. So we should change the `operator` stub to reflect that.

**Comment by milapsheth** [comment]
Since this also affects `setitem` and `delitem`, I fixed those too.
