### ISSUE TITLE
Stub missing for multiprocessing.sharedctypes

### ISSUE THREAD

**Issue by lhfriedman** [python/typeshed#4047]
`
from multiprocessing.sharedctypes import Synchronized
`

when mypy'ed produces this error: 

> playground\mpscerror.py:2: error: No library stub file for standard library module 'multiprocessing.sharedctypes'  [import]
    from multiprocessing.sharedctypes import Synchronized

**Comment by JelleZijlstra** [comment]
Contributions are welcome!

**Comment by lhfriedman** [comment]
Hi, I am pretty new to github. I think this is something I can get started. Not sure how this meshes with government publication approval, but it’s probably OK. How does one do this?

Cheers,
Lawrence

**Comment by hauntsaninja** [comment]
A good resource is typeshed's CONTRIBUTING.md (https://github.com/python/typeshed/blob/master/CONTRIBUTING.md). The section https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#submitting-changes links to some resources that are a little bit more specific about the Github pull request workflow. Feel free to ask questions here if you run into trouble :-)

**Comment by lhfriedman** [comment]
OK. I am going to start on this.
