### ISSUE TITLE
multiprocessing.Pool under Python 2 is not a context manager

### ISSUE THREAD

**Issue by McSinyx** [python/typeshed#4055]
Hi!  I'm not sure about the status of Python 2 support, but currently in `stdlib/2/multiprocessing/pool.pyi` `Pool` is annotated as `ContextManager[Pool]`.  Thank you all for maintaining this BTW!

**Comment by JelleZijlstra** [comment]
Python 2 is still supported in typeshed, so a PR improving this would be welcome.
