### ISSUE TITLE
`statistics.mode` handles hashables, not just numbers as currently annotated

### ISSUE THREAD

**Issue by ramalho** [python/typeshed#4057]
The documentation for [`statistics.mode`](https://docs.python.org/3/library/statistics.html#statistics.mode) says "Return the single most common data point from discrete or nominal data." and includes this example:

```
    >>> mode(['red', 'red', 'green', 'blue', 'blue'])
    'red'
```
The [implementation](https://github.com/python/cpython/blob/822efa5695b5ba6c2316c1400e4e9ec2546f7ea5/Lib/statistics.py#L534) uses `collections.Counter` so the signature for `mode` could be:

```
_HashableT = TypeVar("_HashableT", bound=Hashable)

def mode(data: Iterable[_HashableT]) -> _HashableT: ...
```

Instead of what we have now:

```
def mode(data: Iterable[_Number]) -> _Number: ...
```

I can send a PR if you agree with the problem. Please let me know if the solution I propose is sensible and/or can be improved.

Thanks!

**Comment by JelleZijlstra** [comment]
That seems right. Please send a PR!
