### ISSUE TITLE
The case of Match vs Optional[Match] in re

### ISSUE THREAD

**Issue by jstasiak** [python/typeshed#407]
At the moment all relevant `re` functions apart from `fullmatch` are marked as returning `Match[AnyStr]`[1] while they can return `None` in case of no match. Newly added `fullmatch` stub declares `Optional[Match[AnyStr]]` as the return type[2].

Should `Optional` be added to the rest of the functions?

[1] https://github.com/python/typeshed/blob/cd413c502c533c54556ba2066527409a3d2c3df0/stdlib/3/re.pyi
[2] https://github.com/python/typeshed/pull/381

**Comment by gvanrossum** [comment]
I think so, yes. Carefully check everything with the docs (I'm not sure
*all* functions/methods in the re module have optional results).

**Comment by JelleZijlstra** [comment]
`re.match` and `re.search` now return Optional in typeshed; they appear to be the only affected functions.
