### ISSUE TITLE
Make argument of logging.disable() optional

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#4076]
This was changed in Python 3.7 to be optional and defaults to `logging.CRITICAL`

https://docs.python.org/3/library/logging.html#logging.disable
https://bugs.python.org/issue28524
https://github.com/python/typeshed/blob/6028226750af927e1d728788480c15335d67c26b/stdlib/2and3/logging/__init__.pyi#L470

**Comment by srittau** [comment]
PR welcome!

**Comment by hauntsaninja** [comment]
The parameter name should also be changed to `level`, in case someone wants to pass it in via keyword.
