### ISSUE TITLE
stat.S_IRWXG is not defined for Python 2

### ISSUE THREAD

**Issue by johnklai1** [python/typeshed#408]
S_IRWXG is available in the stat module, but it doesn't appear to be in the pyi file for stat in Python 2.  It is in the pyi files for Python 3:

https://github.com/python/typeshed/blob/master/stdlib/2.7/stat.pyi
https://github.com/python/typeshed/blob/master/stdlib/3/stat.pyi

**Comment by gvanrossum** [comment]
I'll happily accept a PR to add it. Maybe there are other symbols that could be added at the same time? Also, do you know if this is available on Windows? If not, maybe put it inside `if sys.platform != 'win32':` (which will soon start to work, I hope).

**Comment by johnklai1** [comment]
Looks like it does work on Windows, will create a PR.
