### ISSUE TITLE
StrongIO is not considered as a TextIOBase

### ISSUE THREAD

**Issue by sbrunner** [python/typeshed#4162]
For the following code:
```
from io import StringIO
from xml.sax.saxutils import XMLGenerator

result = StringIO()
generator = XMLGenerator(result, "utf-8")
```
I get the error `Argument 1 to "XMLGenerator" has incompatible type "StringIO"; expected "Union[TextIOBase, RawIOBase, StreamWriter, StreamReaderWriter, _Writable, None]"prospector - mypy(error)`

But, when I run:
```
from io import StringIO, TextIOBase
print(isinstance(StringIO(), TextIOBase))
```
I get `True`

Then the `StringIO` should match with `TextIOBase` when with `Union[TextIOBase, ...]`, did I miss something?

**Comment by JelleZijlstra** [comment]
I believe this is fixed in master.

**Comment by sbrunner** [comment]
OK, thanks :-)

**Comment by sbrunner** [comment]
As I understand with this commit 3058bec873ef8b2b5630df36c4cbea0e3734dc5f :-)
