### ISSUE TITLE
asyncio.Handle.__init__ args parameter too strict

### ISSUE THREAD

**Issue by Hawk777** [python/typeshed#4171]
`asyncio.Handle.__init__` has an `args` parameter which is defined as being of type `List[Any]`. But actually the only thing done with it is it is stashed in a member variable and then expanded into another function with `*` (iterable unpacking), so really any iterable would be acceptable there.

**Comment by srittau** [comment]
It's also ultimately passed to `_format_args_and_kwargs`, when `repr` is called. This does:

```python
    if args:
        items.extend(reprlib.repr(arg) for arg in args)
```

So it needs to be a `Sequence`, but a `List` is definitely to narrow.
