### ISSUE TITLE
Completion statistics

### ISSUE THREAD

**Issue by srittau** [python/typeshed#4179]
I am just throwing this out here as an idea: It would be useful to generate per-file statistics about their completion. I.e. the number of annotated arguments, fields, and return values vs. the unannotated number. This would obviously not count `Any` annotations as unused, although `Any` annotations could possibly be counted separately as well. This could also mark files that have an `incomplete` comment.

**Comment by srittau** [comment]
This could be a GitHub action that runs once per day on master and generates a GitHub pages webpage. Maybe it could also store historical data somewhere.

**Comment by hauntsaninja** [comment]
I believe we can use mypy to at least report missing annotations by running with `--disallow-untyped-defs --warn-incomplete-stub` (https://github.com/python/mypy/issues/8917#issuecomment-635816984).
We can also run stubtest without `--ignore-missing-stub` to track things that are missing entirely from the stubs (although this can't work reliably for missing fields).

**Comment by AlexWaygood** [comment]
This information is now collected, and updated twice every day, at https://alexwaygood.github.io/typeshed-stats/
