### ISSUE TITLE
warnings.WarningMessage.__init__(message, …) and warnings.showwarning(message, …) have incompatible types

### ISSUE THREAD

**Issue by jmehnle** [python/typeshed#4211]
The `message` arguments of `warnings.WarningMessage.__init__` and `warnings.showwarning` have different types: `Warning` vs. `str`. Yet, [`showwarning` passes `message` to `WarningMessage()` as-is](https://github.com/python/cpython/blob/0383be4666905f9e24ca791afda845a7686b3fe3/Lib/warnings.py#L10-L13):

```
def showwarning(message, category, filename, lineno, file=None, line=None):
    """Hook to write a warning to a file; replace if you like."""
    msg = WarningMessage(message, category, filename, lineno, file, line)
    _showwarnmsg_impl(msg)
```

[According to `warnings.warn_explicit`](https://github.com/python/cpython/blob/0383be4666905f9e24ca791afda845a7686b3fe3/Lib/warnings.py#L340-L345) this can be either a `Warning` or a `str`-like object (it doesn't test for the `str` type explicitly, but that seems like a bug):

```
    if isinstance(message, Warning):
        text = str(message)
        category = message.__class__
    else:
        text = message
        message = category(message)
```

Would it make sense to change the `message` argument types for both `warnings.WarningMessage.__init__` and `warnings.showwarning` to `Union[str, Warning]`?

**Comment by JelleZijlstra** [comment]
That seems right. Thanks for the report!
