### ISSUE TITLE
Regression in determining return type of zip() on tuples

### ISSUE THREAD

**Issue by mthuurne** [python/typeshed#4226]
On the following code:
```py
z = zip((1, 2, 3), ('a', 'b', 'c'))
reveal_type(z)
```
mypy 0.770 will output:
```
Revealed type is 'typing.Iterator[Tuple[builtins.int*, builtins.str*]]
```
while mypy 0.780 will output:
```
Revealed type is 'Tuple[builtins.tuple[builtins.object*], builtins.tuple[builtins.object*], builtins.tuple[builtins.object*]]'
```
The output from 0.770 is both more correct (since the `zip` object is not a tuple) and more useful (since the types of the elements are known).

The fix for python/mypy#8454 adds additional overloaded definitions for `zip(*...)` in typeshed, which in itself is useful. However, for some reason mypy seems to prefer the new 'star' definitions to the older and more correct 'non-star' definitions, which causes this regression.

**Comment by mthuurne** [comment]
I don't think there is an easy solution.

Reverting would fix my use case, but people using `zip()` on heterogeneous tuples would then have to add extra annotations or casts to their code.

Tweaking overlapping rules, as @hauntsaninja proposed above, might work for small inputs, but I think any star rule will be matching too much and forcing the types to `object`. And then there is also the point that those rules are technically lies that might hide bugs, for example the returned `zip` object does not support `len()`, while `Tuple` does.

Having more advanced rules for handling overlapping overload declarations is likely to indeed get unpredictable if it ends up being some kind of scoring system. And I can't think of anything simpler that still solves the issue.

A special case or plugin in mypy specifically for `zip` would work, but then someone would have to be willing to invest time into that.

**Comment by JelleZijlstra** [comment]
The zip change also caused a performance regression in mypy (python/mypy#9016). Maybe reverting is the right call? The old behavior maybe caused fewer issues.

**Comment by staticdev** [comment]
I also got a problem with that and opened [a question](https://stackoverflow.com/questions/62574831/why-do-i-get-mypy-no-overload-variant-of-zip-matches-argument-error) on SO.

**Comment by hauntsaninja** [comment]
staticdev's issue is unrelated, see https://github.com/python/mypy/issues/9048

We reverted #3830, so mthuurne's issue should be fixed https://github.com/python/typeshed/pull/4254. If more people report issues like https://github.com/python/mypy/issues/8454, we could reconsider the overloads or maybe preferably write a mypy plugin.
