### ISSUE TITLE
Why it is called typeshed?

### ISSUE THREAD

**Issue by summer-wu** [python/typeshed#4235]
I'm not a native english speaker, so i want to know why this project is called typeshed? Accurately, the word "shed" is hard to understand for me. From my own experience, I never seen who had used this word.

From a english dictionary, 'shed' means 'a small buiding used for storing things'.It seems that shed is similar to house,container.

So typeshed is literally means a container of types. Am I right?

**Comment by srittau** [comment]
I was not involved in naming, but I think it's mostly just a name. "typeshed" seems to be a pun on "bikeshed" (a small building to store bicycles), or more specifically the term "bikeshedding". See the [law of triviality](https://en.wikipedia.org/wiki/Law_of_triviality) entry on Wikipedia for more background in that term.
