### ISSUE TITLE
Using mock as value type in dictionary produces false positives starting in 0.780

### ISSUE THREAD

**Issue by nipunn1313** [python/typeshed#4237]
https://mypy-play.net/?mypy=latest&python=3.8&flags=strict&gist=022d2ee02a238fac44fef6c83fbfb0e3

```
from mock import MagicMock, Mock
from typing import Any, Dict

def function(a: Dict[str, str]) -> None:
    pass


function({"abc": "def"})
function({MagicMock(): MagicMock()})

inp: Dict[MagicMock, MagicMock] = {}
function(inp)
```

Gives

```

main.py:12: error: Argument 1 to "function" has incompatible type "Dict[MagicMock, MagicMock]"; expected "Dict[str, str]"
Found 1 error in 1 file (checked 1 source file)
```

I believe the usage of function above is canonical expected usage of Mock/MagicMock in a test

**Comment by srittau** [comment]
This is surprising and I believe a bug in mypy. `MagicMock` indirectly inherits `Any`, so it should be able to be used in place of `str`.

**Comment by srittau** [comment]
Filed as python/mypy#9013, with a repro, not depending on typeshed.

**Comment by JukkaL** [comment]
As I mentioned in the related mypy issue (https://github.com/python/mypy/issues/9013#issuecomment-645280749), mypy is behaving as expected, since `dict` is invariant.
