### ISSUE TITLE
Generator 'throw' should accept instances

### ISSUE THREAD

**Issue by matthewvalentine** [python/typeshed#4241]
Generator's `throw` method should be able to take in an exception instance, and not just a type. The following code runs into a mypy error, but runs perfectly fine.

```python
from typing import Generator

def foo(x: Generator[int, None, None]):
    x.throw(AssertionError('Exception values are OK too'))
```
`Argument 1 to "throw" of "Generator" has incompatible type "AssertionError"; expected "Type[BaseException]"`

See on [mypy-play](https://mypy-play.net/?mypy=latest&python=3.8&gist=cc3cbdd00b00a8d079f3502759ccb28b)

**Comment by srittau** [comment]
True. PR welcome!

**Comment by milapsheth** [comment]
Haha, quite the timing. I noticed that the implementation can support additional ways of calling the function as listed [here](https://github.com/python/cpython/blob/3.6/Lib/test/test_generators.py#L1899).
This also affects `Coroutine` and `AsyncGenerator` types. Feel free to include these changes in your pull request instead if you prefer.
