### ISSUE TITLE
ssl typeshed stub Options regression

### ISSUE THREAD

**Issue by nipunn1313** [python/typeshed#4246]
With #4152, module attributes OP_NO_SSLv2 were removed.

The claim was "In Python 3.6, the SSLContext.options flags were converted from int to
EnumFlag values."

```
nipunn-mbp:typeshed nipunn$ python3 --version
Python 3.7.6

>>> ssl.OP_NO_SSLv2
<Options.OP_NO_SSLv2: 0>
>>> ssl.Options.OP_NO_SSLv2
<Options.OP_NO_SSLv2: 0>
```

However, I believe they still exist as global flags for compatibility.
With the upgrade, we're seeing mypy errors here.

**Comment by nipunn1313** [comment]
Would be asking for the global flags to be reinstated

**Comment by JelleZijlstra** [comment]
Confirmed, let's reinstate the global flags.
