### ISSUE TITLE
context_vars.copy_context() signature problem

### ISSUE THREAD

**Issue by rodrigc** [python/typeshed#4249]
I have been working on running mypy over the Twisted source code, and integrating mypy into Twisted's CI.

I am running some tests with:
* Python 3.9.0b3
* mypy 0.781

I have a section of code in Twisted that looks like this:

```
try:
    from contextvars import copy_context as _copy_context
    _contextvarsSupport = True
except ImportError:
    _contextvarsSupport = False

    class _NoContext:
        @staticmethod
        def run(f, *args, **kwargs):
            return f(*args, **kwargs)

    def _copy_context():
        return _NoContext
```

and am getting this with mypy:

```
test.py:7: error: All conditional function variants must have identical signatures
Found 1 error in 1 file (checked 1 source file)
```

I also came up with another test case:

```
try:
    from os import kill
except ImportError:
    def kill(pid, signal, /):
        pass
```

I get this:

```
b.py:4: error: All conditional function variants must have identical signatures
Found 1 error in 1 file (checked 1 source file)
```

Is this a problem with mypy or typeshed?

**Comment by srittau** [comment]
I'm on the phone right now, so I can't check, but it's possible that the typeshed functions are incorrectly defined.

**Comment by JelleZijlstra** [comment]
The stub is simply `def copy_context() -> Context: ...`. Does it work if you add that return annotation to the fallback?

Maybe mypy should be less strict here, but that's an issue for mypy, not typeshed.

**Comment by rodrigc** [comment]
The full example from Twisted is here: https://github.com/twisted/twisted/blob/9646db406454def1d5d5ce0ac89e01941450567f/src/twisted/internet/defer.py#L34

```
try:
    from contextvars import copy_context as _copy_context
    _contextvarsSupport = True
except ImportError:
    _contextvarsSupport = False

    class _NoContext:
        @staticmethod
        def run(f, *args, **kwargs):
            return f(*args, **kwargs)


    def _copy_context():
        return _NoContext
```

If I change to:

```
try:
    from contextvars import copy_context as _copy_context, Context
    _contextvarsSupport = True
except ImportError:
    _contextvarsSupport = False

    class _NoContext:
        @staticmethod
        def run(f, *args, **kwargs):
            return f(*args, **kwargs)


    def _copy_context() -> Context:
        return _NoContext
```

I get this from mypy:

```
test.py:14: error: Incompatible return value type (got "Type[_NoContext]", expected "Context")
Found 1 error in 1 file (checked 1 source file)
```

Do you have any advice on how I can properly implement the override?

**Comment by JelleZijlstra** [comment]
You might be able to get something to work with `if TYPE_CHECKING`, but honestly I'd just `# type: ignore` it.

**Comment by rodrigc** [comment]
I agree, I just went with the `#type: ignore` approach for simplicity:
https://github.com/twisted/twisted/blob/trunk/src/twisted/internet/defer.py#L47

**Comment by rodrigc** [comment]
One additional question:

```
from contextvars import copy_context
help(copy_context)
```

shows:

```
Help on built-in function copy_context in module _contextvars:

copy_context()
```

What needs to change to have the help output show:

```
copy_context() -> Context
```

I'm not familiar with how annotations work with C functions.

**Comment by JelleZijlstra** [comment]
That would be a CPython issue. I don't know much about where `help()` get its data from, but maybe there's some way to use Argument Clinic in the C code for contextvars that will make `help()` understand the return type.

**Comment by hauntsaninja** [comment]
As far as I know, there isn't currently a way of doing that in CPython (note CPython doesn't really use type annotations). You can modify the docstring to mention the return type, though. Relevant bpo:  https://bugs.python.org/issue31939

**Comment by JelleZijlstra** [comment]
Nothing actionable for typeshed here
