### ISSUE TITLE
Incompatible types of collections.UserList and random.shuffle()

### ISSUE THREAD

**Issue by helafumpek** [python/typeshed#4255]
The following code produces a warning regarding incompatible types.
```python
from collections import UserList
from random import shuffle

shuffle(UserList([1, 2, 3]))
```
The reason is that `UserList` is subclassing from type `MutableSequence`, while `shuffle()` method requires more narrow argument of type `List[Any]`. I would like to submit a PR fixing this, but I've never done this before and I'm not sure if I should suggest changing:
- argument type for `shuffle()` method to `MutableSequence`, since - according to python docs - `List` is more suitable for annotating return values, while `Sequence` and `MutableSequence` fits better as argument types
- parent type for `UserList` class to `List[Any]`, since `UserList` is exactly 1 to 1 wrapper of this class.
- or submit two separate PR's for each change

**Comment by JelleZijlstra** [comment]
Welcome to typeshed! Changing the argument type of `shuffle` to `MutableSequence` sounds right.

I don't think `UserList` should inherit from `List`, since at runtime `isinstance(UserList(), list)` is false.
