### ISSUE TITLE
add third part package peewee

### ISSUE THREAD

**Issue by Trim21** [python/typeshed#4261]
https://github.com/coleifer/peewee

I'd like to start adding this package stubs to typeshed. I'm creating this issue to see if it's ok.

(I'm not a native English speaker, sorry for my poor English)

**Comment by srittau** [comment]
Stubs for third-party libraries are definitely welcome in typeshed. That said, did you contact the peewee developers to see whether they are interested in adding stubs directly to the package? We are glad to help and review stubs in other repositories as well.

**Comment by Trim21** [comment]
they have refused in 2017.





------------------ Original ------------------

**Comment by JelleZijlstra** [comment]
That's a while ago, so it might be worth asking again.

**Comment by dargueta** [comment]
They've refused twice more since then, I just looked.

**Comment by JukkaL** [comment]
I think that in this case adding stubs to typeshed seems reasonable. The project maintainers don't want to deal with type annotations but aren't opposed to hosting stubs elsewhere, as far as I can tell.

**Comment by dargueta** [comment]
@Trim21 I've gotten started on this. I'll open a PR on typeshed and you can contribute if you want to help. It's quite the task :grimacing:

**Comment by dargueta** [comment]
Here's the PR if anyone wants to help out. It's nowhere near done yet -- peewee is a single file with > 7KLOC

**Comment by Trim21** [comment]
I  didn't use peewee anymore, thanks everyone and please checkout @dargueta 's PR.

**Comment by Trim21** [comment]
6
