### ISSUE TITLE
Missing ParserError in dateutils.parser

### ISSUE THREAD

**Issue by lulivi** [python/typeshed#4299]
It seems the ParserError is missing in [`dateutil/parser`](https://github.com/python/typeshed/blob/master/third_party/2and3/dateutil/parser.pyi) stubs file.

### Error:

```
module.py:12: error: Module 'dateutil.parser' has no attribute 'ParserError'
Found 1 error in 1 file (checked 1 source file)
```

### Dateutil dir:

```
>>> import dateutil.parser
>>> dir(dateutil.parser)
['DEFAULTPARSER', 'DEFAULTTZPARSER', 'ParserError', 'UnknownTimezoneWarning', '__all__', '__builtins__', '__cached__', '__deprecate_private_class', '__deprecated_private_func', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_parser', '_parsetz', '_resultbase', '_timelex', '_tzparser', 'isoparse', 'isoparser', 'parse', 'parser', 'parserinfo']
```

### Packages versions

```
mypy==0.770
mypy-extensions==0.4.3
```
```
> python --version
Python 3.8.3
```

Edit: add Python version

**Comment by srittau** [comment]
Indeed, PR welcome!

**Comment by lulivi** [comment]
I'll try in a week or two!

**Comment by abrahamfrancis** [comment]
Is this issue still open? Can I take it up if it is? I'm new here.

**Comment by JelleZijlstra** [comment]
Anyone reading this feel free to submit a PR.

**Comment by abrahamfrancis** [comment]
I have a doubt. Is this as simple as adding a line in the respective file?
I found that ParseError was added in dateutil 2.8.1 according to [this](https://github.com/dateutil/dateutil/pull/974). So wouldn't it make a mistake if the user were using an older version of dateutil?

**Comment by JelleZijlstra** [comment]
Yes, it's probably just adding a single line to the stub file. typeshed generally tries to reflect the latest version of each library.

**Comment by abrahamfrancis** [comment]
I've done it. Could someone review it?
