### ISSUE TITLE
Libvirt type hints

### ISSUE THREAD

**Issue by javierhonduco** [python/typeshed#4310]
Hello there,

In my team at work we heavily use [Libvirt](https://github.com/libvirt/libvirt) and we maintain our own type hints file in our internal typeshed. We started with a version based off [this fork](https://github.com/univention/typeshed/blob/libvirt/third_party/2and3/libvirt.pyi) and have augmented it over time (thanks @pmhahn!).

We were wondering if this would be an addition folks would be interested in for the typeshed! :) I am mainly concerned about not being complete / some type hints we don't use being wrong and the possibility of diverging from the source, but happy to hear what your thoughts are! 

cc @jermenkoo 
cc @andreabolognani @berrange

Cheers,

**Comment by srittau** [comment]
We'd gladly accept those type hints into typeshed. For incomplete stubs, please see the note in CONTRIBUTING. Stubs don't need to be perfect and can always be improved iteratively.

**Comment by berrange** [comment]
Assuming these type hints are going to be a standard expected part of the python ecosystem from now onwards, then it would make sense to incorporate them into libvirt upstream. 

Most of the libvirt python binding is auto-generated, and so manually writing type hints is pretty undesirable. It looks like it should be possible to auto-generate the type hints which would make it less error prone and easier to keep up to date. If someone wants to work on this feel free to open an issue https://gitlab.com/libvirt/libvirt-python/ to discuss it further and send merge requests with any proposals

**Comment by pmhahn** [comment]
I already extended the generator of `libvirt-python` to also generate the type hints in my branch https://github.com/univention/libvirt-python/tree/typing and asked @berrange for a first review through the [libvirt mailing list](https://patchew.org/Libvirt/cover.1587993402.git.hahn@univention.de/), but never herd back - most probably because libvirt was just doing the move to gitlab then.

I need to rebase the branch and do a proper pull request.

**Comment by berrange** [comment]
Oh, yes, thanks for reminding me, sorry we dropped the ball on reviewing that. Do send a pull request for it when you have time to rebase

**Comment by javierhonduco** [comment]
@pmhahn That's great, thanks a lot! Let me know if I can help with anything :)

**Comment by pmhahn** [comment]
As libvirt moved from github.com to [gitlab.com](https://gitlab.com/libvirt/libvirt-python/) my current code is at [phahn/libvirt-python](https://gitlab.com/pmhahn/libvirt-python/-/tree/typing).
See my [merge request](https://gitlab.com/libvirt/libvirt-python/-/merge_requests/9) for some open issues.

**Comment by AlexWaygood** [comment]
I'm closing this issue as there hasn't been any activity in 2 years, but feel free to submit a PR if you'd still like to have these stubs added to typeshed :)
