### ISSUE TITLE
pyzmq

### ISSUE THREAD

**Issue by K0ertis** [python/typeshed#4312]
Using **pyzmq**:17.0.0 and **mypy**: 0.782 and got the error `No library stub file for standard library module`:
```
gui.py:19: error: Skipping analyzing 'zmq': found module but no type hints or library stubs
gui.py:19: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 1 error in 1 file (checked 1 source file)
```

As mentioned in https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports 
I report it here

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
