### ISSUE TITLE
Tornado typeshed lacks HTTPClientError class; status of Tornado typeshed

### ISSUE THREAD

**Issue by shamrin** [python/typeshed#4318]
Tornado typeshed doesn't provide `tornado.httpclient.HTTPClientError` class, only the deprecated `HTTPError`:

https://github.com/python/typeshed/blob/03d879540382e6708058553830577a236aa55f44/third_party/2and3/tornado/httpclient.pyi#L116

It was introduced in Tornado 5.1:

> _Changed in version 5.1:_ Renamed from `HTTPError` to `HTTPClientError` to avoid collisions with `tornado.web.HTTPError`. The name `tornado.httpclient.HTTPError` remains as an alias.

Separately, what is the status of Tornado typeshed? Tornado provides high-quality inline types. Are there cases where typeshed is preferable to inline types?

[1]: https://www.tornadoweb.org/en/stable/httpclient.html#tornado.httpclient.HTTPClientError

Related issue: https://github.com/microsoft/pyright/issues/813

**Comment by srittau** [comment]
Good to hear that tornado now ships their own annotations. We should just remove it from typeshed. I will open a PR.

**Comment by JelleZijlstra** [comment]
Fixed by #4321.
