### ISSUE TITLE
Type check does not support Enum function api

### ISSUE THREAD

**Issue by charnugagoo** [python/typeshed#4324]
Hi, there,

I am facing warnings of type checks when using function call of Enum.

You can take a look at this mypy playground.
https://mypy-play.net/?mypy=latest&python=3.8&gist=39161e33d3466390d6bf30a42e4615f7

My peer guesses this is a limitation of the stub in typeshed at
here https://github.com/python/typeshed/blob/master/stdlib/3/enum.pyi#L23
Not sure how to type this.

```
# Enum functional call documentation:
# https://docs.python.org/3/library/enum.html#functional-api

fake_enum1 = Enum('fake_enum1', ['a', 'b'])
fake_enum2 = Enum('fake_enum1', names=['a', 'b'])
fake_enum3 = Enum(value='fake_enum1', names=['a', 'b'])

fake_enum4 = Enum(value='fake_enum1', names=['a', 'b'] , module=__name__)


# main.py:7: error: Unexpected arguments to Enum()
# main.py:8: error: Unexpected arguments to Enum()
# main.py:10: error: Too many arguments for Enum()
# Found 3 errors in 1 file (checked 1 source file)
```

**Comment by JelleZijlstra** [comment]
This is a mypy issue, python/mypy#9079.

It's true though that there's nothing in typeshed that directly supports the functional Enum API. Type checkers would special case this API, but it'd still be good to follow the runtime implementation more closely in our stub.

**Comment by charnugagoo** [comment]
Thanks for pointing!

**Comment by sobolevn** [comment]
Worth noting that `Enum()` call is still handled by a mypy plugin.
