### ISSUE TITLE
tempfile stubs incorrectly typed

### ISSUE THREAD

**Issue by qaphla** [python/typeshed#434]
Many of the stubs for `tempfile` functions are typed to return `BinaryIO` in python 3, or `IO[str]` in python 2, despite having a mode string. It seems likely that their return types should (for now, at least) be `IO[Any]`, matching the type of `open()`.

For example, from the python3 stubs:

```
def TemporaryFile(
            mode: str = ..., buffering: int = ..., encoding: str = ...,
            newline: str = ..., suffix: str = ..., prefix: str = ...,
            dir: str = ...) -> BinaryIO:
    ...
```

**Comment by gvanrossum** [comment]
For Python 2, IO[str] is probably fine, as that is the type returned by open() regardless of the mode. (The only way to open an IO[unicode] is to use io.open().)

**Comment by JelleZijlstra** [comment]
`IO[str]` in Python 2 is fine as Guido mentioned, and the Python 3 tempfile stubs now consistently use `IO[Any]`, so this can be closed.
