### ISSUE TITLE
pyenchant type hints

### ISSUE THREAD

**Issue by pmhahn** [python/typeshed#4342]
[pyenchant](https://github.com/pyenchant/pyenchant) is a library interface for Python to interface with spell-checkers. Currently there are no [PE 484](http://www.python.org/dev/peps/pep-0484/) annotation for it within typeshed.

I wrote annotations for it as I use it for one of my employees projects. They are available from my branch <https://github.com/univention/typeshed/tree/enchant>.

It is complete but for some pending issues:
- the library carries some magic to handle `bytes()`, `unicode`, `bytearrays()`  internally, which makes it hard to to select the proper type for input and output parameters.
- I use plain `Dict` in many cases as the is little to no specification on what is stored within.
- I'm currently using it only with Python 3, but previously used it with Python 2, but did not check for correctness there.

It's not perfect but is a good start and works completely for my project.

What is needed to get it merged? Do you want me to just create a pull request?

**Comment by srittau** [comment]
Yes, just a PR. The first version of library stubs don't need to be perfect, we can always improve on things later.

**Comment by pmhahn** [comment]
I was ready to create a pull request but checked my version again and just noticed, that there is a new upstream version 3.x available from <http://pyenchant.github.io/pyenchant/changelog.html#id4>, which dropped Python 2 compatibility. It also added some new functions, which I just added.

How is an evolving API handled in typeshed, e.g. is there some annotation to document a function is only available with library version 3.x? For Python there is `sys.version_info`, but that is orthogonal to the version of [pyenchant](https://github.com/pyenchant/pyenchant).

I'm currently still using `pyenchant-2.0` from Debian-10-Buster and only with Python 3, but that version is also still usable with Python 2 and carries some internal code to handle `bytes()`, `unicode`s and `bytearray()`s and `chararray()`s.

The source code for `pyenchant` is on [GitHub.com](https://github.com/pyenchant/pyenchant/tree/master/enchant)

**Comment by srittau** [comment]
At the moment, there is no handling of multiple versions. Typeshed generally accepts patches that make stubs conform to the latest released version. There are some plans to split typeshed into separately distributable packages, though. That will enable us to support multiple versions of a package in the future.

**Comment by AlexWaygood** [comment]
I'm closing this issue, as there hasn't been any activity in two years. It also looks as though OP has started contributing type hints upstream instead of adding them to typeshed (which is great!).

PRs to typeshed adding third-party stubs are in general always welcome, though, so if adding the type hints upstream goes badly for any reason, and you do want to add stubs for `pyenchant` at any point, feel free to open a PR!
