### ISSUE TITLE
asyncio.subprocess is not marked as being re-exported from asyncio

### ISSUE THREAD

**Issue by Leedehai** [python/typeshed#4345]
Please see [https://github.com/microsoft/pyright/issues/859](https://github.com/microsoft/pyright/issues/859), and the [2nd comment](https://github.com/microsoft/pyright/issues/859#issuecomment-660770282) under that issue:

> Typeshed does include the submodule definition, but it doesn't indicate that this submodule is automatically imported by (and re-exported by) the top-level module. As such, you would need to use import asyncio.subprocess to access this submodule.

**Comment by hauntsaninja** [comment]
I think this is an issue with Pyright, refer to https://github.com/python/typeshed/pull/4300#issuecomment-652600517
