### ISSUE TITLE
pandas stubs

### ISSUE THREAD

**Issue by gramster** [python/typeshed#4355]
Is there an interest in having pandas stubs in typeshed? We have stubs we have created at Microsoft that we can contribute, but they would require a fair amount of work to meet the typeshed guidelines and pass the tests. If there is no interest we'd prefer not to have to do the work of meeting typeshed guidelines; we could release them through a separate repo in that case.

**Comment by srittau** [comment]
All stubs for third-party software available on pypi are welcome. Pandas stubs would be great to have, considering the popularity of the package.

**Comment by hauntsaninja** [comment]
Just seconding the interest :-) Let us know if there's something you'd need help with!

**Comment by hoefling** [comment]
For reference: https://github.com/predictive-analytics-lab/data-science-types, contains stubs for `numpy`, `matplotlib` and `pandas`.

**Comment by EricCousineau-TRI** [comment]
FWIW I'm taking a gander at NumPy's builtin type annotations, and `nptyping`:
https://github.com/ramonhagenaars/nptyping/issues/27

**Comment by AlexWaygood** [comment]
I'm closing this issue since there hasn't been any activity in over 2 years.

If anybody wants to submit a PR adding pandas stubs to typeshed, they're very welcome to, at any point :) However, note that there's now also the https://github.com/pandas-dev/pandas-stubs project independent of typeshed.
