### ISSUE TITLE
Can not use argparse add_argument with type=Path

### ISSUE THREAD

**Issue by knzivid** [python/typeshed#4356]
```
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument(type=Path)
```

PyCharm complains about this with

>Expected type 'Union[(str) -> Any, (str) -> Any, FileType]' (matched generic type 'Union[(str) -> _T, (str) -> _T, FileType]'), got 'Type[Path]' instead 

Is this an issue with the type or how PyCharm interprets this?

**Comment by srittau** [comment]
`PurePath` (`Path`'s base class) has the following constructor (for Python 3.6+):

```python
def __new__(cls: Type[_P], *args: Union[str, os.PathLike[str]]) -> _P: ...
```

This matches the expected type `(str) -> Any`. I assume, PyCharm doesn't handle `__new__` correctly.

**Comment by sproshev** [comment]
Please vote for https://youtrack.jetbrains.com/issue/PY-37095 (thumbs up near the title)
