### ISSUE TITLE
How to type annotate __main__?

### ISSUE THREAD

**Issue by PeterJCLaw** [python/typeshed#4360]
At run-time you can import `__main__` and it's occasionally useful to do so (for example: `jedi` does this in utils for setting up REPLs).

While `__main__` likely doesn't have a useful members we can put in the typeshed, it could be useful to have it present and importable.

**Comment by JelleZijlstra** [comment]
What could we put in a stub for `__main__` in typeshed? I suppose we could make it an empty file.

**Comment by CraftSpider** [comment]
Would make sense to have a top-level `__getattr__`, so it there won't be type complaints. Otherwise yeah, I'd suspect just an empty stub.
