### ISSUE TITLE
Missing stub package for Pony ORM

### ISSUE THREAD

**Issue by Ryuno-Ki** [python/typeshed#4361]
The ORM [Pony](https://pypi.org/project/pony/) is missing type annotation.

Although it seems, that one can work around it (see https://github.com/ponyorm/pony/issues/479 )
running mypy on [my repo using Pony](https://github.com/Ryuno-Ki/crimpy/tree/20262e4e639cd58d6b18518d59b51045047773ad) yields

```sh
$ mypy crimpy
crimpy/repositories/db.py:1: error: Skipping analyzing 'pony': found module but no type hints or library stubs
crimpy/repositories/twitter.py:5: error: Skipping analyzing 'pony': found module but no type hints or library stubs
crimpy/models/twitter.py:3: error: Skipping analyzing 'pony': found module but no type hints or library stubs
crimpy/models/twitter.py:3: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
crimpy/views/contexts/root.py:24: error: "Slot" not callable
crimpy/views/contexts/root.py:36: error: Argument "notify" to "Property" has incompatible type "Signal"; expected "Optional[Callable[..., Any]]"
Found 5 errors in 4 files (checked 13 source files)
```

(The last two errors are unrelated to this issue).

I followed https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-type-hints-for-third-party-library but couldn't find the definitions here.

My system (with `pony v0.7.13`):

```sh
$ python --version
Python 3.6.10
$ mypy --version
mypy 0.782
```

**Comment by srittau** [comment]
Contributions welcome!

**Comment by srittau** [comment]
We are closing all third-party stub requests issues without recent activity. We still welcome pull requests that add these to typeshed, although distributing the stubs with the the third-party package itself is preferable.
