### ISSUE TITLE
Feed PickleBuffers to hashlib

### ISSUE THREAD

**Issue by crusaderky** [python/typeshed#4362]
Python 3.8.5
mypy 0.782

```python
h = hashlib.sha1()
pickle.dumps(obj, protocol=5, buffer_callback=h.update)
```
mypy output:
2: error: Argument "buffer_callback" to "dumps" has incompatible type "Callable[[Union[bytes, bytearray, memoryview]], None]"; expected "Optional[Callable[[PickleBuffer], Any]]"

Expected output:
No error

**Comment by hatal175** [comment]
I think this needs https://github.com/python/typing/issues/593 for a good fix. PickleBuffer implements the buffer protocol and not much more.

**Comment by srittau** [comment]
We have `_typeshed.ReadableBuffer` as a stopgap measure.

**Comment by hatal175** [comment]
But ReadableBuffer doesn't contain PickleBuffer

**Comment by JelleZijlstra** [comment]
@hatal175 but we could add it in the `_typeshed` stub.
