### ISSUE TITLE
Deque.pop() takes no arguments

### ISSUE THREAD

**Issue by KmolYuan** [python/typeshed#4364]
According to:
https://docs.python.org/3.8/library/collections.html#collections.deque.pop
But still an argument "i" there:
https://github.com/python/typeshed/blob/master/stdlib/3/collections/__init__.pyi#L215

**Comment by hauntsaninja** [comment]
Good spot, PR welcome. One issue is that MutableSequence's pop takes an argument (https://github.com/python/cpython/blob/3.8/Lib/_collections_abc.py#L985), so you might run into issues or need to type ignore incompatible override complaints

**Comment by Akuli** [comment]
I wonder if `deque.pop(index)` is supposed to raise an exception. You can `del deque[index]`, for example, so why would `deque.pop(index)` be supported, other than by accident?

**Comment by JelleZijlstra** [comment]
@Akuli that does sound accidental; feel free to submit an issue to CPython.

**Comment by Akuli** [comment]
https://bugs.python.org/issue41409
