### ISSUE TITLE
subprocess needs to be updated for python 3.5 

### ISSUE THREAD

**Issue by wreed4** [python/typeshed#437]
They added a "run" method in 3.5.  Because this stub is out of date, mypy doesn't know about this "run" method.

**Comment by gvanrossum** [comment]
Thanks for noticing! Do you feel up to submitting a PR? It should probably
check for sys.version_info.

--Guido (mobile)

**Comment by wreed4** [comment]
I'd just change the .pyi file in stdlib/3, right? Wouldn't make one in stdlib/3.5?

**Comment by gvanrossum** [comment]
Correct, no new file.

--Guido (mobile)

**Comment by wreed4** [comment]
There's also the CompletedProcess object and the DEVNULL attribute (added in 3.3).  Should these be added under a sys.version_info check as well?

**Comment by gvanrossum** [comment]
Might as well clean it up...

**Comment by wreed4** [comment]
sorry if this is a dumb question, but is that a yes? or are you saying I shouldn't submit a pull request and you'll clean it up?

**Comment by gvanrossum** [comment]
Sorry, that was a yes!

**Comment by jdelic** [comment]
I just want to mention that I'm working on a more elaborate update in #426

**Comment by JelleZijlstra** [comment]
`subprocess.run` is in the stub now.
