### ISSUE TITLE
contextlib.ContextDecorator.__call__ incorrect type

### ISSUE THREAD

**Issue by ap--** [python/typeshed#4382]
Dear typeshed team,

I have run into the following typing issue when using `contextlib.ContextDecorator` and analysing via mypy:

```python
# minimal example
from contextlib import ContextDecorator

class MyDecorator(ContextDecorator):
    def __enter__(self):
        pass
    def __exit__(self, exc_type, exc_val, exc_tb):
        pass

@MyDecorator()
def func() -> int:
    return 1
```
Returns the following Error:

```python
/scratch.py:10: error: Argument 1 to "__call__" of "ContextDecorator" has incompatible type "Callable[[], int]"; expected "Callable[..., None]"
Found 1 error in 1 file (checked 1 source file)
```

<br>
I believe the current typeshed annotation is incorrect:

https://github.com/python/typeshed/blob/5d553c9584eb86793cfa61019ddee5c7b62bc286/stdlib/2and3/contextlib.pyi#L67-L68

I think it should be:
```python
 class ContextDecorator: 
     def __call__(self, func: Callable[..., Any]) -> Callable[..., Any]: ... 
```

<br>
That would make it consistent with the `functool.wraps` annotation:

https://github.com/python/typeshed/blob/5d553c9584eb86793cfa61019ddee5c7b62bc286/stdlib/3/functools.pyi#L56-L58

which is used in the `contextlib.ContextDecorator.__call__` implementation:
https://github.com/python/cpython/blob/cadda52d974937069eeebea1cca4229e2bd400df/Lib/contextlib.py#L75-L80

I'd be happy to submit a PR if my error analysis is correct.
Cheers,
Andreas 😃

**Comment by JelleZijlstra** [comment]
Thanks for the report! It looks like the decorated function always returns the return value of the original function and has the same arguments as the original, so I believe it should be:
```
_CallableT = TypeVar("_CallableT", bound=Callable[..., Any])

 class ContextDecorator: 
     def __call__(self, func: _CallableT) -> _CallableT: ... 
```

**Comment by ap--** [comment]
👍  awesome.
Let me know if I can help by adding this and some tests in a PR.

Cheers,
Andreas 😃

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR! We currently don't have tests for specific stubs, so just making this change in the stub is sufficient.
