### ISSUE TITLE
os.open should not have AnyStr in its type

### ISSUE THREAD

**Issue by gnprice** [python/typeshed#439]
See https://github.com/python/mypy/issues/1943 -- `AnyStr` shouldn't be used when it only appears once in the type, because it complicates the semantics without adding anything.

**Comment by matthiaskramm** [comment]
Should type checkers just detect a single usage and optimize for it? AnyStr *is* a pretty convenient shortcut.

**Comment by gnprice** [comment]
I'm not convinced that would actually be correct, under the semantics specified in PEP 484.

The semantics of `AnyStr` is that it's a type variable which has to specifically take on (in Python 3) either the value `str` or the value `bytes`. So in code like this:
```
AnyStr = TypeVar('AnyStr', constraints=[str, bytes])

def f(x: AnyStr) -> None: ...

x = 'a'  # type: Union[str, bytes]

f(x)  # error?
```

We're trying to use a value of type `Union[str, bytes]` in a generic function which requires an `AnyStr`. What value should the type variable `AnyStr` take there to make that well-typed?

The type `Union[str, bytes]` isn't equal to either `str` or `bytes`, and in fact it isn't usable as either a `str` or a `bytes`. So neither possible way to instantiate the type variable makes this code well-typed.

Does that match your interpretation of the semantics? How would you interpret PEP 484 in the context of this code that makes it well-typed?

**Comment by matthiaskramm** [comment]
I had assumed that `TypeVar("T", X, Y)` is equivalent to `TypeVar("T", Union[X, Y])`.

With that, your code sample passes checking, based on `Union[str, bytes] <: Union[str, bytes]`?

**Comment by gvanrossum** [comment]
No, `TypeVar('T', X, Y)` cannot be reduced to `TypeVar('T', Union[X, Y])`. The latter is actually an error according to PEP 484 (and mypy) -- it requires at least two constraint values if there are any. A single constraint would be indistinguishable from the bare constraint type.

(Constrained type variables are tricky that way. It took me a long time to grok them. And I still haven't found an example besides `AnyStr`. But that's indispensible -- just not for `os.open()`. :-)

I'm still not sure how to express what I'd like to see, and maybe it's not worth it. We can't exactly say that `Union[str, bytes] <: AnyStr`. It's only the case that if there's exactly one parameter of type exactly `AnyStr`, and no other use of `AnyStr` in the signature, then `Union[str, bytes]` should be acceptable. But that seems excessively specific. In the meantime we should just change typeshed.
