### ISSUE TITLE
Adding stubs for cachetools

### ISSUE THREAD

**Issue by judej** [python/typeshed#4406]
I have created typestubs for cachetools (https://github.com/tkem/cachetools). Emailed the author and he is ok with me checking the stubs in here. 

Will use this issue to submit the PR

Please let me know if you have questions. 
Thanks,
Jude

**Comment by srittau** [comment]
Sounds good to me.

**Comment by srittau** [comment]
Closing this. Please reopen if there are things to discuss before submitting the PR, but all subsequent discussion should happen in that.

**Comment by hauntsaninja** [comment]
We also recently added stubs for cachetools in https://github.com/python/typeshed/pull/4422. If you see improvements to be made to them, that is of course still welcome.
