### ISSUE TITLE
Directly call @singledispatch-registered functions

### ISSUE THREAD

**Issue by crusaderky** [python/typeshed#4408]
A somewhat common pattern for functions decorated by ``@singledispatch`` is for a function that handles a subclass to apply some pre/postprocessing and pass the ball to the function that handles the parent class - conceptually the same as calling ``super()`` in a method.

mypy 0.782 doesn't like it:
```python
from functools import singledispatch

class C: pass
class D(C): pass

@singledispatch
def f(x: object) -> str:
    return "base"

@f.register
def fd(x: D) -> str:
    return "preprocessed " + fc(x)

@f.register
def fc(x: C) -> str:
    return "C"

print(f(D()))
```
python output:
```
preprocessed C
```

mypy output:
```
17: error: Unsupported operand types for + ("str" and "Callable[..., str]")
17: error: Argument 1 to "fc" has incompatible type "D"; expected "Callable[..., str]"
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
I did not know about `@singledispatch` before. Not a fan of this convoluted decorator, and I think it will be hard to get typing right here. That said, the second overload of `_SingleDispatchCallable.register` seems to have an extra `cls` argument, and probably needs to be the first overload to work correctly. The first overload on the other should probably be typed using `Type[Any]`. I have not tested any of this, though.
