### ISSUE TITLE
get_origin is missing in typing_extensions

### ISSUE THREAD

**Issue by sk-** [python/typeshed#4430]
`get_args` was recently added to `typing_extensions` in https://github.com/python/typeshed/pull/4373, however, the file is still missing the stub for the function `get_origin`.

See https://github.com/python/typing/blob/ffebbecbf4ad162572050ecfaac4335cc5431c24/typing_extensions/src_py3/typing_extensions.py#L156-L157

**Comment by hauntsaninja** [comment]
PR welcome!
