### ISSUE TITLE
tkinter.Event is not generic at runtime

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#4431]
In #4347 I made tkinter.Event generic, so that you could write

```
def event_handler(event: tkinter.Event[tkinter.Label]) -> None:
    label_stuff(event.widget)
```

instead of

```
def event_handler(event: tkinter.Event) -> None:
    assert isinstance(event.widget, tkinter.Label)
    label_stuff(event.widget)
```

This doesn't actually work because `tkinter.Event` is not generic at runtime, so you need to use a string instead (or on 3.8+, `from __future__ import annotations`):

```
def event_handler(event: "tkinter.Event[tkinter.Label]") -> None:
    label_stuff(event.widget)
```

The assert code still works though because plain `tkinter.Event` is equivalent to `tkinter.Event[Any]`. So the stubs currently allow writing `event: tkinter.Event` or `event: "tkinter.Event[Foo]"`, but I didn't realize the need for using a string when I made the pull request.

What we can do about this:
- Do nothing and recommend using `tkinter.Event` or `"tkinter.Event[Foo]"`.
- Create a pull request to cpython that makes `tkinter.Event` generic at runtime. This won't actually help because 3.8+ has `from __future__ import annotations` and `tkinter.Event` wouldn't become generic in older pythons.
- Revert #4347 and just require `assert isinstance(event.widget, Foo)`.

Also, what else can go wrong with making something generic in stubs but not at runtime?

**Comment by srittau** [comment]
Stubs can be generic, even if the runtime is not. I didn't check, but I wouldn't be surprised if nearly all generic types outside of `typing` aren't generic at runtime. Quoting or using the future import are the best way to handle this.

**Comment by hauntsaninja** [comment]
I believe future annotations is 3.7+ :-)
This comes up often in mypy issues, going to link https://mypy.readthedocs.io/en/stable/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime here in case it helps people stumbling onto this issue

**Comment by gvanrossum** [comment]
Oh, we may need to revise that page. In the wake of PEP 585 we made every stdlib class that’s generic in typeshed also generic in the stdlib. Of course this only affects 3.9+.
