### ISSUE TITLE
Flask's request object type can be overridden

### ISSUE THREAD

**Issue by leecbaker** [python/typeshed#4434]
#### Overview
Flask allows the Request class to be overridden, as seen in [this example](https://flask.palletsprojects.com/en/1.1.x/patterns/subclassing/); however, type errors are encountered whenever you use this functionality.

#### Details
`request` (lower case) is a [proxy object](https://werkzeug.palletsprojects.com/en/1.0.x/local/#werkzeug.local.LocalProxy) used to access the [request context](https://flask.palletsprojects.com/en/1.1.x/reqcontext/), which stores information about the request currently being made. The request context is by default of type `Request`, but this can be overridden, and is commonly done to associate additional information with the current request.

When the request object type is overridden, type checking incorrectly assumes that the `request` object is (or, more correctly, is a proxy to) an object of type `Request`, when it is instead another class. The type stub [declares in this stub](https://github.com/python/typeshed/blob/master/third_party/2and3/flask/globals.pyi) `request` to simply be of type `Request`, rather than whatever type Flask.request_class is.

A similar issue exists for flasks' `current_app` global variable, whose type can also be overridden (also in the example below).

#### Desired behaviour
The type stub should allow the type of the request context and of the application context to be overridden. The example below should be able to be type checked with no errors.

#### Example

```
from flask import current_app, Flask, Request, request, Response
import typing

# based on https://flask.palletsprojects.com/en/1.1.x/patterns/subclassing/


class MyRequest(Request):
    def __init__(self, import_name: typing.Dict[str, typing.Any]):
        super(MyRequest, self).__init__(import_name)
        self.my_value: typing.Optional[int] = None


class MyFlask(Flask):
    request_class = MyRequest
    my_value = 4321


app = MyFlask(__name__)


@app.before_request
def add_request_value() -> None:
    request.my_value = current_app.my_value + 4321


@app.route("/")
def hello() -> Response:
    return Response(f"App value: {current_app.my_value} request value: {request.my_value}")


if __name__ == "__main__":
    app.run()

```

Type errors from `mypy`:
`"Request" has no attribute "my_value"`

**Comment by JelleZijlstra** [comment]
This seems difficult to support in typeshed without just typing `flask.request` as Any, which would be unfortunate. Perhaps it's possible to do better with a mypy plugin, but dynamically typed globals don't generally seem like a good match for typing.

**Comment by srittau** [comment]
Closing as the flask stubs will be removed in a few months.
