### ISSUE TITLE
Drop all use of the name whitelist in the codebase

### ISSUE THREAD

**Issue by gpshead** [python/typeshed#4436]
https://github.com/python/typeshed/pull/4297 changed `blacklist` to `exclude_list` in the typeshed codebase. 👍 

But `whitelist` remains.  Please rename all `whitelist` references to `allow_list` or similar.

**Comment by gpshead** [comment]
in particular `scripts/update-stubtest-whitelist.py` and `tests/stubtest_whitelist` (I didn't grep, just poked around the tree)

**Comment by Nikhil1O1** [comment]
Does this still require improvements? If yes then I'm in else why don't you mark it closed
@gpshead

**Comment by hauntsaninja** [comment]
It was blocked on changes^ to mypy, which have been made but need to be released before it makes sense to change typeshed
