### ISSUE TITLE
Missing `unsafe_` functions for PyYAML

### ISSUE THREAD

**Issue by Hakuyume** [python/typeshed#4439]
Latest PyYAML provides `unsafe_load` and `unsafe_load_all`.
https://github.com/yaml/pyyaml/blob/5.3.1/lib/yaml/__init__.py#L174-L192

Those functions do not have type annotations in typeshed.
https://github.com/python/typeshed/blob/master/third_party/2and3/yaml/__init__.pyi

**Comment by srittau** [comment]
PR welcome!
