### ISSUE TITLE
stubtest on windows isn't doing anything

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#4448]
I think this has been the case for a while, I suspect since they were moved to Github actions in #4223 
Example in https://github.com/python/typeshed/pull/4447

**Comment by srittau** [comment]
@hauntsaninja Do you have any idea why that might be? The output ([example](https://github.com/python/typeshed/pull/4447/checks?check_run_id=988994469)) indicates a successful run.

**Comment by JelleZijlstra** [comment]
I put some debug prints in #4454 and apparently we just never execute any part of stubtest_test.py. There must be something wrong with how we invoke the script in the GitHub action (https://github.com/python/typeshed/blob/master/.github/workflows/stubtest.yml#L27).

**Comment by Akuli** [comment]
This runs the script correctly on windows and ubuntu: https://github.com/python/typeshed/commit/2dc3d100116dafab112f9faef997a2b3bdd1837b

but after adding that, stubtest fails to import something on windows: https://github.com/Akuli/typeshed/runs/994228956

**Comment by srittau** [comment]
Makes sense that it didn't run with Python, since I assume that the default Windows shell doesn't look at the hashbang. It's just strange that there were no errors reported.

**Comment by Akuli** [comment]
welcome to windows lol

**Comment by hauntsaninja** [comment]
Thanks for figuring it out Akuli! It looks like we removed dbm.ndbm from the whitelists in #4225, shortly after moving to Github Action. I opened #4455, since stubtest should print "stubtest succeeded" we'll be able to figure out if it ran.

**Comment by Akuli** [comment]
maybe put it to tests/stubtest_whitelists/win32.txt? `dbm.gnu` is already there
