### ISSUE TITLE
[FR] Improve literal_eval type definition

### ISSUE THREAD

**Issue by sk-** [python/typeshed#4452]
[`ast.literal_eval`](https://github.com/python/cpython/blob/97003466d481670b9234b343319c6e02f9c5d732/Lib/ast.py#L54) can only return `Dict`, `Set`, `Tuple`, `int`, `str`, `bool`, `float`, `complex` and `None`. However its return type is set as `Any`.

The problem with that type definition is that mypy (with `warn_return_any`) complains when you compare against `Any`, and the following code:

```py
def comparator(value: str) -> bool:
    return ast.literal_eval(value) == expected_value
```

raises

```
Returning Any from function declared to return "bool"
```

**Comment by hauntsaninja** [comment]
Generally speaking, Union return types are problematic. For more discussion, see https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions I don't think `literal_eval` is an exception here, anecdotally and based on https://grep.app/search?q=literal_eval%28&filter[lang][0]=Python

**Comment by srittau** [comment]
Another example where something like python/typing#566 could help, but at the moment there is not much we can do in typeshed, unfortunately.
