### ISSUE TITLE
Question on typing Coroutines that return async generator "objects"

### ISSUE THREAD

**Issue by yuyupopo** [python/typeshed#4461]
I have a question on adding types to a function that returns `async_generator object`
Here's a simple snippet that carries the issue.

```
async def gen() -> AsyncGenerator[int, None]:
    for idx in range(100):
        yield idx

async def func():
    await asyncio.sleep(1)
    return gen()

generator = await func()
async for idx in generator:
    print(idx)

```

In the snippet above, what would be the return type of `func`? 
Setting as `AsyncGenerator` seems weird cause you need an `await` keyword to get the generator.
And setting as `Awaitable[AsyncGenerator]` is also weird, as `func` itself is already a coroutine.

The reason `func` returns a `async_coroutine object` and not just iterate through it (`async def func(): async for idx in gen(): ...`) is that I wanted to make sure `await asyncio.sleep` gets called when the generator is created.

**Comment by hauntsaninja** [comment]
As it happens, also `AsyncGenerator[int, None]`! (Although, as in the sync world, you may wish to use `AsyncIterator[int]` in both cases.

See https://github.com/python/mypy/issues/5070 and https://github.com/python/mypy/issues/5385 for equivalent issues (though somewhat coming from the other side of things).
