### ISSUE TITLE
Add stubs for zxcvbn

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#4462]
https://github.com/dwolfhub/zxcvbn-python

_Should_ be fairly small as it has a comparatively small API surface

**Comment by srittau** [comment]
We'd accept a contribution, although preferably the project should ship its own type hints. See also dwolfhub/zxcvbn-python#56.

**Comment by gvanrossum** [comment]
Honestly is it worth keeping an issue open for this? We can't afford to have an open issue for every package on pypi...

**Comment by srittau** [comment]
Probably not. We have quite a few [other similar issues](/python/typeshed/labels/type-stubs-request). If no one objects, I am going to close them.
