### ISSUE TITLE
Missing Types for Google Protobuf

### ISSUE THREAD

**Issue by crockeo** [python/typeshed#4465]
Hey all, sorry if this is a duplicate; I was unable to find a relevant ticket.

I recently ran into a type error around protobuf `Duration` and `Timestamp` types that wasn't caught by mypy. After digging around, I noticed they don't have return types described on most of their `ToXXX` functions, e.g. [Duration](https://github.com/python/typeshed/blob/f093466ad67e5fccfe5aace1b3a658a75d18b929/third_party/2and3/google/protobuf/internal/well_known_types.pyi#L39-L42).

Similarly, I've found that when iterating through `RepeatedCompositeFieldContainer` (and probably `RepeatedScalarFieldContainer`, but I haven't tested it) types are erased, even though they [indirectly sublclass `Sequence`](https://github.com/python/typeshed/blob/f093466ad67e5fccfe5aace1b3a658a75d18b929/third_party/2and3/google/protobuf/internal/containers.pyi#L25).

I was thinking of going through and annotating these type definitions. Is there anything I should know before I do this?

**Comment by gvanrossum** [comment]
That would be appreciated. Be sure to read through https://github.com/python/typeshed/blob/master/CONTRIBUTING.md

**Comment by Akuli** [comment]
is #4341 related?

**Comment by crockeo** [comment]
@Akuli hm, I'm not sure. I'm not an expert on the codebase, but it looks like there's the mypy-protobuf codegen for [Timestamp](https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/timestamp_pb2.pyi) and [Duration](https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/duration_pb2.pyi), along with a hand-written type interface for many [well-known types](https://github.com/python/typeshed/blob/master/third_party/2and3/google/protobuf/internal/well_known_types.pyi). I think my job is just to add more annotations for that hand-written file.

Also, according to `mypy` types are _not_ erased while iterating through `RepeatedCompositeFieldContainer` and `RepeatedScalarFieldContainer` (via `reveal_type`). I'm guessing it's just a mspyls bug instead. Sorry for the false report on that end.
