### ISSUE TITLE
Accidentally pushed straight to master

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#4477]
Hey @srittau or @JelleZijlstra, I accidentally pushed a small commit straight to master: https://github.com/python/typeshed/commit/351a971b1dec75fe8accefea83a30a8fc261e656

I think it's okay. It adds a definition of `EXACT_TOKEN_TYPES` to `token.pyi`, conditionally for Python 3.8+. If you've reviewed it just close this issue.

**Comment by hauntsaninja** [comment]
Looks good to me. I guess I must have missed it when I updated `token` for py38 since it's undocumented / not part of `__all__`.

**Comment by JelleZijlstra** [comment]
Looks good to me too. The discussion in the issue (https://bugs.python.org/issue24622) suggested it's also present in 3.7, but I confirmed that it's not.

**Comment by gvanrossum** [comment]
Oh, it used to live in tokenize.py; Serhiy moved it to token.py and caused it to be auto-generated from Grammar/Tokens. I honestly think it was an oversight that it's not listed in `__all__` but I think it's too late to fix (it's a little unfortunate that `__all__` both means "this is public" and "include this on `import *`" but that's a bigger issue).
