### ISSUE TITLE
Why does ast.NodeTransformer.generic_visit() return Optional[AST] instead of AST?

### ISSUE THREAD

**Issue by MapleCCC** [python/typeshed#4482]
Sorry if I make some conceptual mistakes, because I am not super familiar with the type annotation theory. I digged into the [source of `ast.NodeTransforer.generic_visit()`](https://github.com/python/cpython/blob/8e19c8be87017f6bef8e4c936b1e6ddacb558ad2/Lib/ast.py#L477) and saw that it always return an `AST` object. It won't return `None`. So why make the return annotation `Optonal[AST]`? This make me have to write additional code to convince static type checker that it always returns an `AST` object. Thanks in advance for any kind clarification.

The corresponding line in typeshed: https://github.com/python/typeshed/blob/142aed3838e7a1ee812c0e21f3eedb48770e168c/stdlib/3/ast.pyi#L147

**Comment by srittau** [comment]
Unless I am overlooking something, I assume that's a copy and error mistake, since the superclass `NodeVisitor` returns `None`. PR welcome!

**Comment by MapleCCC** [comment]
Closed by #4483
