### ISSUE TITLE
Incorrect type for first argument of concurrent.futures.wait

### ISSUE THREAD

**Issue by absassi** [python/typeshed#4508]
First argument of `concurrent.futures.wait` is declared here as `fs: Iterable[Future[_T]]`.
However, CPython calls `len(fs)` (to check if all futures are already done), which fails at runtime for iterables that doesn't have `__len__`, such as generators.

The [documentation](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.wait) doesn't say anything about this argument type:

> Wait for the `Future` instances (possibly created by different `Executor` instances) given by *fs* to complete.

But, based on CPython implementation, `Iterable` is too broad for this argument.

**Comment by srittau** [comment]
Sounds like `Sequence` is the correct type. (I didn't double check.)
