### ISSUE TITLE
Perhaps declare a `__new__` instead of an `__init__` for `str` and other similar types

### ISSUE THREAD

**Issue by Hibou57** [python/typeshed#4514]
At https://github.com/python/typeshed/blob/23300837329ec7f14578344f40f72d866b342dd8/stdlib/2and3/builtins.pyi#L446 , an `__init__` is declared for `str`

As I understand it, `str` has no proper `__init__`, it only has a proper `__new__`.

I came to this, thinking again about this issue in another repository: https://github.com/python/mypy/issues/9405

**Comment by srittau** [comment]
A short test indicates to me that `str` has both `__init__()` and `__new__()`, so we should define both in typeshed. (After checking with the implementation, of course.)

**Comment by srittau** [comment]
@JelleZijlstra pointed to #1352 and #1464, where this was (unsuccessfully) tried before.

**Comment by srittau** [comment]
FWIW, I just checked the following example from #1464:

```python
from enum import Enum
from typing import TYPE_CHECKING

if not TYPE_CHECKING:
    reveal_type = print

class I(int, Enum):
    a = 1
reveal_type(I['a'])  # E: Revealed type is '__main__.I'

class S(str, Enum):
    a = '1'
reveal_type(S['a'])  # E: Revealed type is '__main__.S'

class F(float, Enum):
    a = 1.0
reveal_type(F['a'])  # E: Revealed type is '__main__.F'
```

It still works when I add the following definitions to `str`:

```python
        @overload
        def __new__(cls: Type[_T], o: object = ...) -> _T: ...
        @overload
        def __new__(cls: Type[_T], o: bytes, encoding: str = ..., errors: str = ...) -> _T: ...
```

(No guarantee that these are the correct definitions for `str`, though.) This makes me hopeful that the original underlying problem is solved.
