### ISSUE TITLE
Why Can't NoReturn Be the Reutrn Type of _HANDLER?

### ISSUE THREAD

**Issue by Congee** [python/typeshed#4517]
Here is the type definition of _HANDLER, and I have a problem using it.
https://github.com/python/typeshed/blob/7b29927c4b107b68bba127495747f9a97303c4fc/stdlib/3/signal.pyi#L85 

Is there anything wrong for the handler to throw an exception?

```python
def handler(*args) -> NoReturn:
    raise SystemExit(1)

signal.signal(signal.SIGINT, handler)  # type mismatch due to NoReturn
```

**Comment by JelleZijlstra** [comment]
We should probably make it return `Any` if the return value is ignored. Feel free to submit a PR.
