### ISSUE TITLE
Hints for python-magic

### ISSUE THREAD

**Issue by rmspeers** [python/typeshed#4520]
Requesting type hints for python-magic, as can be found at https://pypi.org/project/python-magic/.

**Comment by srittau** [comment]
We gladly accept contribution for third-party stubs.

**Comment by rmspeers** [comment]
If I'm interpreting this right, it sounds like it may make sense to update the guidelines in the docs that say to submit a ticket requesting coverage _OR_ PR? It sounds like you are looking for people to submit PRs and not tickets requesting coverage? I was following the docs that said ticket _or_ PR in this project.

**Comment by srittau** [comment]
@rmspeers Could you point me to where this is still mentioned so we can fix the wording?

**Comment by rmspeers** [comment]
Sure, it's at this page where the mypy error's mention to go look at:
https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-type-hints-for-standard-library-module

```
Filing a bug report or submitting a pull request to typeshed, the repository of type hints for the standard library that comes bundled with mypy.
```

**Comment by srittau** [comment]
Thank you! That refers to standard library stubs, though, not third party stubs.

I just had a look and python-magic seems to include a stubs file, although it might not be installed at runtime, and no py.typed file is added. Considering this, I think the best way forward is to fix those issues in the upstream package. Distributing the stubs directly with a package is the best solution.

**Comment by JelleZijlstra** [comment]
Perhaps the mypy documentation should also be updated; it's rather unlikely now for users to run into a standard library module that doesn't exist in typeshed.
