### ISSUE TITLE
Missing SortKey type in pstats

### ISSUE THREAD

**Issue by adamlichtl** [python/typeshed#4521]
Between Python 3.6 and 3.7, the pstats module introduced a new exported type "SortKey", but this isn't reflected in `typeshed/stdlib/2and3/pstats.pyi`

See also:

3.6, no SortKey: https://docs.python.org/3.6/library/profile.html

3.7, with SortKey: https://docs.python.org/3.7/library/profile.html

And from line 31 of pstats.py: ```__all__ = ["Stats", "SortKey"]```

**Comment by hauntsaninja** [comment]
Thanks again for the patch! By the way, it looks like Python 3.9 has added some more stuff to pstats, how would you feel about submitting another PR? :-)

```
λ python3.9 -m mypy.stubtest --custom-typeshed-dir ~/dev/typeshed pstats --concise
pstats.FunctionProfile is not present in stub
pstats.Stats.get_stats_profile is not present in stub
pstats.StatsProfile is not present in stub
```

**Comment by adamlichtl** [comment]
Thanks for the code review! I'm using Conda which doesn't support Python 3.9 environments yet... so I think I'll let someone else have a turn at a PR for this. :-)
