### ISSUE TITLE
gc does not contain type information for gc.freeze()

### ISSUE THREAD

**Issue by nobillygreen** [python/typeshed#4529]
gc.freeze() was introduced in python 3.7. Typeshed does not contain proper typing for it yet:

https://github.com/python/typeshed/blob/04f7d7a2fdafba7b91265f5d0e3fc2215316e6af/stdlib/3/gc.pyi

**Comment by gvanrossum** [comment]
Thanks for the report. If you're interested in submitting a simple PR to fix this, please go ahead! If you don't feel up to that, we'll probably close the issue (we don't want to have a separate issue open for every missing API in every stdlib module, and we just don't have the bandwidth to fix every nit that's reported).
