### ISSUE TITLE
xml.etree.ElementTree.XMLParser constructor: too strict type for target

### ISSUE THREAD

**Issue by yurikhan** [python/typeshed#4537]
The constructor for `xml.etree.ElementTree.XMLParser` is stubbed as taking an argument `target: Optional[TreeBuilder]`.

However, actual code of `XMLParser` does not require that the `target` argument be a subclass of `TreeBuilder`. In particular, it does not require the target’s `start` and `end` methods to return `Element`, because it does not use the return values.

An important use case of `XMLParser` is incremental parsing without building a hierarchy of `Element`s. In this case, the client supplies a `target` that handles `start`, `end` and `data` events as it sees fit.

In fact, the `target` object is not even required to have all the needed methods. `XMLParser` dynamically inspects whether it has attributes named `start`, `end`, `data`, `comment`, and/or `pi`, and if so, assigns them (or adapters over them) to the corresponding callback attributes of the underlying instance of `pyexpat.XMLParserType`.

How should this be solved? The ideal annotation for `target` would say:
* if the object has a `start` attribute, it must be `Callable[[str, Dict[str, str]], Any]`;
* if the object has any of `end`, `data`, or `comment` attributes, they must be `Callable[[str], Any]`;
* if the object has a `pi` attribute, it must be `Callable[[str, str], Any]`.

Looks vaguely like a `Protocol`, but I’m not sure how to specify that the methods might not be present. Having to write out 32 possible method combinations would be unfortunate.

**Comment by gvanrossum** [comment]
Maybe it should just be typed `Any` or `object`? Are there types for `target` that definitely don't work at runtime? Can you show an example in the REPL?

**Comment by yurikhan** [comment]
Depends. Construction of `XMLParser` will succeed with any `target` object, I think. However, if the attributes listed above are not callable with the corresponding signatures, the parser will fail trying to call them.

If the idea “attribute is optional but if present must have a compatible type” is not representable in `typing`, I’d say `Any` is a better side to err than `Optional[TreeBuilder]`.

```
$ ipython3
Python 3.8.2 (default, Jul 16 2020, 14:00:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from xml.etree.ElementTree import XMLParser

In [2]: class BadTarget: 
   ...:     def start(self): 
   ...:         pass 
   ...:

In [3]: p = XMLParser(target=BadTarget())

In [4]: p.feed('<root />')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-6b1e967a1a6e> in <module>
----> 1 p.feed('<root />')

TypeError: start() takes 1 positional argument but 3 were given
```

**Comment by gvanrossum** [comment]
Yeah, I don't think there's a way in the current type system to express "this attribute could either be missing or it should have type T" -- that's is different from `attr: Optional[T]` because there `attr` must still exist.

If you want to submit a PR that changes the type to `Any` that sounds like the best approach.

**Comment by yurikhan** [comment]
Yeah, `Optional` is not an option. That would mean “must be present but can be `None`”.
