### ISSUE TITLE
Incorrect type for fd argument of os.fchdir, os.fsync, and os.fdatasync

### ISSUE THREAD

**Issue by Cebtenzzre** [python/typeshed#4539]
Since their addition in Python 2.3 (python/cpython@4d1e64bb4606c76770af8e66e699220a3d146631), the CPython implementations of `os.fchdir`, `os.fsync`, and `os.fdatasync` have called `PyObject_AsFileDescriptor` on their `fd` argument, to support both `int` and objects with a `fileno()` method. But in stubs, fd is declared as `int`:
https://github.com/python/typeshed/blob/81d067618c74ed5c734ab0179904db77d0028142/stdlib/2/posix.pyi#L108
https://github.com/python/typeshed/blob/81d067618c74ed5c734ab0179904db77d0028142/stdlib/2/os/__init__.pyi#L222
https://github.com/python/typeshed/blob/81d067618c74ed5c734ab0179904db77d0028142/stdlib/3/os/__init__.pyi#L554

Many other builtin functions (e.g. [fcntl.fcntl](https://docs.python.org/3/library/fcntl.html#fcntl.fcntl), [termios.*](https://docs.python.org/3/library/termios.html)) are documented to accept objects with `fileno()`, and take a `FileDescriptorLike` in stubs. In the case of these three os builtins, the [docs](https://docs.python.org/3/library/os.html#os.fchmod) do not clearly define the type of `fd`:
> Change the mode of the file given by _fd_ to the numeric _mode_.

**Comment by srittau** [comment]
In typeshed we generally try to follow implementation rather than documentation. So PRs that fix those argument types are very welcome!
