### ISSUE TITLE
flask.testing.EnvironBuilder missing

### ISSUE THREAD

**Issue by ikonst** [python/typeshed#4541]
`make_test_environ_builder` is deprecated and we're supposed to use `EnvironBuilder` directly but it's missing from the typestub.

**Comment by gvanrossum** [comment]
Thanks for the report. Do you want to submit a PR?

**Comment by ikonst** [comment]
I probably will -- this is just so I'd have something to slap by the `# type: ignore` :)

**Comment by mitch292** [comment]
Hi - Hope you don't mind, but I went ahead and submitted a PR.
