### ISSUE TITLE
plistlib: load* can return something other than dictionaries

### ISSUE THREAD

**Issue by madig** [python/typeshed#4542]
Note how in https://github.com/python/typeshed/blob/5d553c9/stdlib/2and3/plistlib.pyi#L16-L34, all return types are dictionaries, but a plist file can contain other object types as well.

```
In [1]: import plistlib

In [2]: plistlib.dumps(1)                                                                  
Out[2]: b'<?xml version="1.0" encoding="UTF-8"?>\n<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n<plist version="1.0">\n<integer>1</integer>\n</plist>\n'

In [3]: plistlib.loads(_2)                                                                      
Out[3]: 1  # Not a dictionary :O
```

**Comment by gvanrossum** [comment]
I guess it's like pickle and json?

**Comment by madig** [comment]
I suppose! So, should the return type be `Any` in general? I don't think one can register custom types, so for our internal copy of plistlib, I have so far gathered the supported types to be

```python
# Mypy does not support recursive type aliases as of 0.782, Pylance does.
# https://github.com/python/mypy/issues/731
# https://devblogs.microsoft.com/python/pylance-introduces-five-new-features-that-enable-type-magic-for-python-developers/#1-support-for-recursive-type-aliases
PlistEncodable = Union[
    bool,
    bytes,
    Data,
    datetime,
    float,
    int,
    List[Any],
    MutableMapping[str, Any],
    str,
    Tuple[Any, ...],
]
```

Though that may be optimized further. For my `loads` copy, I use the signature

```python
def loads(
    value: bytes,
    use_builtin_types: Optional[bool] = None,
    dict_type: Type[_D] = dict,  # type: ignore
) -> Union[PlistEncodable, _D]:
   ...
```

where `_D` is the same thing as in the typeshed stub file.

**Comment by hauntsaninja** [comment]
Thanks for reporting, I'd accept a PR changing the return type to Any.

We generally avoid Union return types (https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions). For instance in this case changing to a Union return type would mean all existing users of (typed) plistlib would need to add assertions so they can once again use the return value as a dict.

**Comment by madig** [comment]
Ok, thanks for pointing that out. I assume that once the API returns `Any`, the `_D` stuff can be dropped because it is subsumed by `Any`?

**Comment by hauntsaninja** [comment]
I'd leave those overloads in. If you're passing in `dict_type`, you're probably expecting some sort of dict back, and it's nice for it to be the type you wanted.
That said, grepping the internet indicates `dict_type` is not really used, so I'd also be okay with collating the overloads.
