### ISSUE TITLE
Types for `os.statvfs_result` initializer are incorrect

### ISSUE THREAD

**Issue by Wallacoloo** [python/typeshed#4572]
**Repro:**
1. Put the following in `statvfs.py`
```statvfs.py
#!/usr/bin/python3.6
import os
os.statvfs_result((4096, 4096, 100, 11, 10, 0, 0, 0, 4100, 255))
```
2. Run the above code, to demonstrate that the types for it are correct.
3. Run mypy or some other type-checker using typeshed annotations. The tool will complain about incorrect arguments. Something like:
```
statvfs.py:3: Too few arguments for "statvfs_result"  [call-arg]       
statvfs.py:3: Argument 1 to "statvfs_result" has incompatible type "Tuple[int, int, int, int, int, int, int, int, int, int]"; expected "int"  [arg-type]
```

**Expectation:**
Since the code runs fine, it should type-check without errors. The Typeshed bindings should be made to be compatible with the above code.

**Explanation:**
The type bindings for this file live [here](https://github.com/python/typeshed/blob/master/stdlib/3/os/__init__.pyi#L318). It shows as inheriting from NamedTuple, which is accurate for _indexing_ the type, but not for instantiating the type. It seems the type must be instantiated from a single sequence-like argument of length 10.

**Comment by srittau** [comment]
I have no experience with namedtuples, so I don't know what the best approach is, but I agree that this should be fixed if possible.

**Comment by JelleZijlstra** [comment]
We dealt with a similar issue for another structsequence in the os module before: `os.stat_result`. Perhaps we need something similar to https://github.com/python/typeshed/pull/2753/files#diff-f8be19bba87ef5799f28ce9d8842ac69R198

**Comment by hauntsaninja** [comment]
I'd do something like `pwd.struct_passwd` and just inherit from tuple, not namedtuple. Matches the runtime MRO as well. It's actually been at the back of my TODO list, since stubtest doesn't like the namedtuple lie either.
