### ISSUE TITLE
[FYI] mypy_primer

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#4580]
With apologies to black_primer, I jotted down a script that lets us run mypy over a large amount of open source Python code. Hopefully this helps democratise the process of identifying regressions and evaluating risky changes.

Something like this was brought up in https://github.com/python/typeshed/issues/4332
This could also serve as a way of decentralising something like https://github.com/python/typeshed/issues/1339

This has informed:
https://github.com/python/typeshed/pull/4579
https://github.com/python/typeshed/pull/4574
https://github.com/python/typeshed/pull/4582
https://github.com/python/typeshed/pull/4583
And you can see it in action at:
https://github.com/python/mypy/pull/9275

More details at: https://github.com/hauntsaninja/mypy_primer

Feel free to close or discuss!

**Comment by CraftSpider** [comment]
Like this idea, also reminds me of Rust's crater tool. Helps compare the (possibly biased) view of the typeshed collaborators with the practical usage of the types in the ecosystem.

**Comment by JelleZijlstra** [comment]
This is great, thank you! I wonder if we can incorporate it into typeshed CI.

**Comment by hauntsaninja** [comment]
Yeah, it would be nice to get it into CI in some form. 

One concern is speed. A Github runner has two cores. `rm -rf $(python3 -m pip cache dir); time python -m primer --clear -j 2 --debug` takes 17 minutes on my machine (which probably has better per core perf). Plus hopefully the time taken will increase over time (although we could always restrict to a subset of projects).
However, mypy_primer currently installs mypy from source. For typeshed we don't care too much about mypy version, so things would be faster if we installed from pip and got a mypyc-compiled mypy.

It's also worth noting that there'll be a class balance of errors: since most of the projects are well established, I assume most errors will be false positives.

**Comment by srittau** [comment]
Thanks, that is very useful indeed. Maybe at first we could have a daily or weekly run that just informs us when there are problems, but doesn't cause CI to fail.

**Comment by JukkaL** [comment]
> For typeshed we don't care too much about mypy version, so things would be faster if we installed from pip and got a mypyc-compiled mypy.

I'd recommend using a compiled mypy -- it's often 3-4x faster than interpreted.

**Comment by hauntsaninja** [comment]
Just measured, it's 3.5x over the corpus. I've made the change to mypy_primer: if you explicitly specify a version, it'll first look for it on PyPI.

**Comment by hauntsaninja** [comment]
mypy_primer now runs in CI
