### ISSUE TITLE
🐑 Stubs for redis library are missing `unlink` function

### ISSUE THREAD

**Issue by coiax** [python/typeshed#4623]
Steps to reproduce:

```
import redis
client = redis.Redis()
client.unlink(b"keyname") # error: "Redis" has no attribute "unlink"  [attr-defined]
```

Looks like `unlink` has been in the library for [around three years](https://github.com/andymccurdy/redis-py/commit/7b7d6c4be51ac12934d5dc47df1bc2d052869898), must just be an oversight.

**Comment by srittau** [comment]
PR welcome!

**Comment by coiax** [comment]
@srittau Done.
