### ISSUE TITLE
Suggestion to loosen the wrapper type restriction in functools.update_wrapper

### ISSUE THREAD

**Issue by hoefling** [python/typeshed#4626]
Right now, the stub for `functools.update_wrapper` is:
https://github.com/python/typeshed/blob/714135f91b2d245f9c333a64d09a0fb1f320a743/stdlib/3/functools.pyi#L54-L56

Are there any reasons not to loosen this to a

```py
_T = TypeVar("_T")

 def update_wrapper( 
     wrapper: _T, wrapped: _AnyCallable, assigned: Sequence[str] = ..., updated: Sequence[str] = ... 
 ) -> _T: ...
```
since `functools.update_wrapper` isn't tied to functions only?

```py
>>> import functools
>>> class C: pass
... 
>>> def f(): pass
... 
>>> functools.update_wrapper(C(), f).__name__
'f'
```
I'll gladly submit a PR if the maintainers agree on the proposed change - asking for permission first, not that I'm making a mistake with that.

**Comment by srittau** [comment]
While `update_wrapper()` is intended for functions, I don't see anything that speaks against widening the types.

**Comment by hoefling** [comment]
@srittau the only objection that comes to my mind is that the new signature wouldn't check for obvious errors like

```python

def f(): pass
functools.update_wrapper("foo", f)
```

but this currently isn't the case for e.g. builtins either: `functools.update(abs, f)` will also raise an `AttributeError`.
