### ISSUE TITLE
Typeshed maintainers: do you want to opt in to HacktoberFest?

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#4631]
HacktoberFest changed to opt-in: https://hacktoberfest.digitalocean.com/hacktoberfest-update

Since contributing to typeshed is pretty simple, I expect the typical HF contributor to be more successful trying to contribute to typeshed than to e.g. mypy or cpython.

**Comment by JelleZijlstra** [comment]
Sounds worth it to opt in, yes!

Though reading those blog posts, I remember seeing an uptick in PRs on various repos that didn't seem like they'd fix anything useful. I wonder whether those were from Hacktoberfest participants. Anyway, we can deal with those PRs pretty easily.

**Comment by gvanrossum** [comment]
Digital Ocean's HacktoberFest is infamous for encouraging kids to spam
projects, but this year it seems they are (finally!) listening to
maintainers, and the rules to prevent spam have been tightened (I think if
maintainers mark a PR as spam that counts doubly against the contributor's
reputation or something).

For typeshed I think the reward will be higher than the risk.

**Comment by srittau** [comment]
While a bit cautious, I think we could give it a try.

**Comment by gvanrossum** [comment]
Okay, let’s do it. Can one of you do the honors?

**Comment by srittau** [comment]
Done. I also added more topics (we had none yet). Let's leave this issue open until October is over, so we remember to remove the topic again.

**Comment by hauntsaninja** [comment]
I pinned #4641 so that potential contributors can be a little bit more self sufficient when it comes to finding easy improvements to make. (As I mentioned in that issue, feel free to edit the text!)

I think it's [pretty savvy of us](https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama) to make this change two weeks into October :-)

**Comment by gvanrossum** [comment]
> I think it's [pretty savvy of us](https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama) to make this change two weeks into October :-)

Well, I had been watching the drama via a GitHub focus group for high-profile open source maintainers, and opened this issue once DigitalOcean announced they would make it opt-in *and* changed other rules to discourage spam.

Thanks for the pinned issue!

**Comment by srittau** [comment]
October is over and I have removed the label. Thanks for the suggestion!

**Comment by gvanrossum** [comment]
Did we get any good PRs?

**Comment by JelleZijlstra** [comment]
I don't recall any PRs that were labeled as being from hacktoberfest.

**Comment by srittau** [comment]
Me neither, unfortunately.

**Comment by vbarbaresi** [comment]
I opened a few PRs that were incentivized by Hacktoberfest, I have to say (also opened some on mypy even if it wasn't counting)
Thanks hauntsaninja for the pinned issue about Good ways to contribute, that was really helpful.

So I'm encouraging you to keep doing this next year!

**Comment by vbarbaresi** [comment]
I just discovered that removing the hacktoberfest topic makes digitalocean consider you opted out, so PRs don't count anymore.
Would it be too much to ask that you keep the topic for ~2 weeks? There's a review period that lasts 14 days (even if the PR are already merged)

**Comment by srittau** [comment]
Sure, I re-added it for now.

**Comment by cy** [comment]
Yes, I submitted two redis-py stub PRs here incentivized by Hacktoberfest although I've submitted before :) Unfortunately, because the tag was removed the PRs were invalidated and didn't become valid again after it was re-added.

At least my PRs were merged and I contributed to open source even if they didn't count for Hacktoberfest, thanks @srittau for reviewing me, I learned a few things ✨

**Comment by srittau** [comment]
It's unfortunate the PRs were invalidated. If I can do anything to help make them valid again, please let me know.

**Comment by srittau** [comment]
For the record, I removed the hacktoberfest for good now.
