### ISSUE TITLE
Name 'typing.io.IO' is not defined

### ISSUE THREAD

**Issue by FichteFoll** [python/typeshed#4639]
The [Python 3.5 docs](https://docs.python.org/3/library/typing.html?highlight=typing.io#typing.io) list a `typing.io` _something_ ("wrapper namespace" according to docs, class according to interpreter), which you can access with `IO` to get an IO type, or for example `TextIO`. Using this in an interpreter works fine, but mypy complains about this.

``` py
>>> typing.io.IO[str]
typing.IO[str]
>>> typing.io.TextIO
typing.TextIO[str]
```

```
prettify.py:40: error: Name 'typing.io.IO' is not defined
```

I understand (now) that `typing.IO` is also possible, but the docs are _very_ vague about that being a possibility, which is why I didn't even try it. Docs aside, since this works in the interpreter I think it should also work in mypy, which is why I'm reporting it.

**Comment by gvanrossum** [comment]
It's a passive-aggressive way of telling people that using `typing.io.IO` is deprecated. :-)

Seriously, we should add it, but I'd also like to deprecate it, at least in the docs.

**Comment by rohitkg98** [comment]
How do we go around adding type aliases inside the `io` module.
I tried doing something like this:
```python
class io:

    __all__ = ['IO', 'TextIO', 'BinaryIO']

    IO = Union[IO]
    TextIO = Union[TextIO]
    BinaryIO = Union[BinaryIO]
```
but this introduces cyclic definition error in mypy

Also, the Union is used as workaround for [this](https://github.com/python/mypy/issues/9238)

**Comment by JelleZijlstra** [comment]
We should probably just give up on `typing.io`. It's never worked with mypy and I haven't seen a lot of demand for it.

**Comment by gvanrossum** [comment]
> We should probably just give up on `typing.io`. It's never worked with mypy and I haven't seen a lot of demand for it.

Okay, let's close this then. Can someone file an issue with cpython to deprecate typing.io?

**Comment by rohitkg98** [comment]
Created the issue to deprecate: https://bugs.python.org/issue42001
