### ISSUE TITLE
Cachetools stubs are missing types

### ISSUE THREAD

**Issue by jd** [python/typeshed#4652]
The new `cachetools` stubs are incomplete and fail in such a case:
```python
    @cachetools.cachedmethod(
        cache=operator.attrgetter("_write_permission_cache"),
        key=functools.partial(cachetools.keys.hashkey, "has_write_permissions"),
    )
```
Returns:

```
error: Argument "cache" to "cachedmethod" has incompatible type "Callable[[Any], Any]"; expected "Cache[partial[Any], <nothing>]"
```
`cache` argument can be a callable as can been seen in the example in the docs: https://cachetools.readthedocs.io/en/stable/#cachetools.cachedmethod

**Comment by srittau** [comment]
If I understand the documentation correctly, `cache` must be a `Callable`, so `Cache` is just wrong here? Anyway, any improvements are welcome. Cc @erictraut

**Comment by jd** [comment]
Yes, reading the code, it seems it has to be a `Callable`, not anything else.
