### ISSUE TITLE
termios: Definition of tcgetattr causes false positives

### ISSUE THREAD

**Issue by Cebtenzzre** [python/typeshed#4661]
#### Example Code
The example from [the termios docs](https://docs.python.org/3/library/termios.html#example):
```python
def getpass(prompt="Password: "):
    import termios, sys
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    new = termios.tcgetattr(fd)
    new[3] = new[3] & ~termios.ECHO          # lflags
    try:
        termios.tcsetattr(fd, termios.TCSADRAIN, new)
        passwd = input(prompt)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)
    return passwd
```

#### Actual Behavior
```
$ mypy --pretty --show-error-codes --check-untyped-defs example.py
example.py:6: error: Unsupported operand types for & ("List[bytes]" and "int")  [operator]
        new[3] = new[3] & ~termios.ECHO          # lflags
                 ^
example.py:6: note: Left operand is of type "Union[int, List[bytes]]"
Found 1 error in 1 file (checked 1 source file)
```

#### Expected Behavior
The code typechecks successfully, because it is correct. In the reality of runtime, I never have to worry that `new[3]` will be a list, because it won't.

---

The mypy error is caused by the definition of _Attr, which is the return type of tcgetattr:
https://github.com/python/typeshed/blob/0142a87da886645c4a7186edcc71f7b3dcf8dc1e/stdlib/2and3/termios.pyi#L4

Typeshed's own [contribution guidelines](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions), python/mypy#1693, and  [mypy's docs](https://mypy.readthedocs.io/en/stable/kinds_of_types.html#union-types) agree that union return types are bad news. I can get around this with an `assert isinstance(new[3], int)`, but at runtime `new[0]` through `new[5]` will always be `int`, and `new[6]` will always be `List[bytes]` *, so the assertion is pointless.

It would be clearer if tcgetattr returned an object so the different values could have their own names and types, but that decision predates typeshed. It would be nice if we at least had an AnyOf type (python/typing#566) so we could write `List[AnyOf[int, List[AnyOf[bytes, int]]]]`, but we don't. So we are left with `List[Any]`, which is not very specific but is at least not incorrect.

\* Except for `new[6][termios.VTIME]` and `new[6][termios.VMIN]`, which are int in noncanonical mode (when `new[3] & termios.ICANON` is zero). The stubs currently ignore this possibility.

**Comment by hauntsaninja** [comment]
Thanks for the report! I'd merge a PR changing this to `List[Any]` :-)
