### ISSUE TITLE
Stubs for `google.protobuf.symbol_database` are incorrect and incomplete

### ISSUE THREAD

**Issue by panhania** [python/typeshed#4666]
The [`SymbolDatabase`] class is missing multiple methods (e.g. `RegisterMessageDescriptor`, `RegisterServiceDescriptor`). Moreover, these that are declared, are incorrectly typed:

```python
def RegisterEnumDescriptor(self, enum_descriptor: Type[EnumDescriptor]) -> EnumDescriptor: ...
def RegisterFileDescriptor(self, file_descriptor: Type[FileDescriptor]) -> FileDescriptor: ...
```

The problem is, `Register*Descriptor` methods expect descriptor instances, not classes.

[`SymbolDatabase`]: https://github.com/protocolbuffers/protobuf/blob/ce66f6047db44df3234bccd6fcf468bccc14a760/python/google/protobuf/symbol_database.py#L66-L186

**Comment by srittau** [comment]
PRs welcome!
