### ISSUE TITLE
tkinter.FALSE doesn't work

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#4669]
In #4658 I saw [this commit](https://github.com/EDCD/EDMarketConnector/commit/958f277fde0ba625bf3b87985c7c906a05b8f3a4), which replaces `tkinter.FALSE` usages with `False`. This is because typeshed currently expects many things to be `bool` even though `tkinter.FALSE` has type `Literal[0]`.  The same applies to `NO`, `YES`, `TRUE`, `ON` and `OFF` defined in `tkinter/constants.py`.

I think the correct fix is to change the types from `Literal[0]` and `Literal[1]` to `bool`. In the past, @srittau has mentioned that it's fine to "cheat" and just use `bool` when the value is known to be `0` or `1`.

**Comment by srittau** [comment]
While I was mostly talking about argument types, I agree that just using `bool` here would be the most pragmatic solution. That said, maybe it would make sense for type checkers to accept `Literal[0]` and `Literal[1]` where `bool` is expected (because `0 == False` and `1 == True`).
