### ISSUE TITLE
Invalid 'UnicodeError' has no attribute 'X' messages

### ISSUE THREAD

**Issue by scaramallion** [python/typeshed#4676]
**Bug Report**
[UnicodeError's](https://docs.python.org/3/library/exceptions.html#UnicodeError) attributes are causing mypy errors

**To Reproduce**

```python
try:
    pass
except UnicodeError as err:
    err.encoding
    err.reason
    err.object
    err.start
    err.stop
```

**Expected Behavior**
No error message for `UnicodeError` attributes

**Actual Behavior**
These attributes all have `"UnicodeError" has no attribute "x"`, where "x" is the attribute name

**Your Environment**

- Mypy version used: 0.790
- Python version used: 3.8
- Operating system and version: Ubuntu 20.04

**Comment by JelleZijlstra** [comment]
The relevant stubs are in https://github.com/python/typeshed/blob/master/stdlib/2and3/builtins.pyi#L1914.

I guess what's going on here is that `UnicodeError` itself doesn't have these attributes, but the only UnicodeErrors you'll ever find are instances of its subclasses Unicode(En|De)codeError, which do.

**Comment by scaramallion** [comment]
OK, I'll narrow the exception. Thanks!
