### ISSUE TITLE
get_type_hints `obj` argument type seems too restrictive

### ISSUE THREAD

**Issue by jd** [python/typeshed#4678]
The current type hints is:
```python
def get_type_hints(
    obj: Callable[..., Any], globalns: Optional[Dict[str, Any]] = ..., localns: Optional[Dict[str, Any]] = ...
) -> Dict[str, Any]: ...
```

The `Callable[..., Any]` seems really restrictive. The function works for example on an entire module, if you have a module such as:

```
# foo.py
VAR: str
```

The following code works fine and as expected:
```
import typing
from . import foo

typing.get_type_hints(foo)
# {'VAR': <class 'str'>}
```

However, there's a warning raised:
```
Argument 1 to "get_type_hints" has incompatible type Module; expected "Callable[..., Any]"
```

The fix seems easy, but I'm also wondering if there are other cases not covered by `Callable`. The function body seems to just call `getattr(obj, '__annotations__')` so I'm wondering if setting a type other than `Any` is even doable?

**Comment by srittau** [comment]
It seems as if a custom protocol could handle this.

**Comment by jd** [comment]
What do you mean by "custom protocol"? 🤔 
Do you mean a `typing.Union`?

**Comment by srittau** [comment]
Something like this (untested):

```python
class SupportsAnnotations(Protocol):
    __annotations__: Dict[str, Any]
```
