### ISSUE TITLE
stdlib/2/distutils is empty, drop in favour of stdlib/2and3/distutils?

### ISSUE THREAD

**Issue by StefanCardnell** [python/typeshed#4679]
Hi all. I notice the [stdlib/2/distutils](https://github.com/python/typeshed/tree/master/stdlib/2/distutils) folder is practically empty which is causing knock-on type-hinting issues in pycharm [(see my ticket)](https://youtrack.jetbrains.com/issue/PY-45005).

I wonder if this folder should be dropped in favour of [stdlib/2and3/distutils](https://github.com/python/typeshed/tree/master/stdlib/2and3/distutils) which contains all of `distutils` modules?

**Comment by JelleZijlstra** [comment]
Yes, that sounds right. Feel free to submit a PR.

**Comment by StefanCardnell** [comment]
Actually I see the reason. 2/distutils is not quite empty supplies type hinting for `emxccompiler` which is not available in python 3, hence the need to split them. I think this is pycharm's issue with not properly handling the fact that a module can be segmented out between 2/distutils and 2and3/distutils.
