### ISSUE TITLE
Why does mypy not treat DictReader as iterable?

### ISSUE THREAD

**Issue by timrichardson** [python/typeshed#47]
I have cloned the latest git on mypy and I'm on master
Python 3.5.1

    with open(billto_shipto_file) as csvfile:
                reader = csv.DictReader(csvfile)
                for row in reader:
                     ...

mypy says: error: Iterable expected in the 'for row in reader' line.

**Comment by gvanrossum** [comment]
It looks like there's no stub file for the cvs module in the typeshed repo (github.com/python/typeshed). Maybe you'd like to contribute one?

**Comment by JukkaL** [comment]
Actually, there is a csv module stub:

```
typeshed $ find . -name "*csv*"
./stdlib/2.7/csv.pyi
./stdlib/3/csv.pyi
```

However, there is a missing `Iterator` base class:

```
class DictReader:
    restkey = ...  # type: Any
    restval = ...  # type: Any
    reader = ...  # type: Any
    dialect = ...  # type: Any
    line_num = ...  # type: Any
    fieldnames = ...  # type: Any # Actually a property
    def __init__(self, f, fieldnames=..., restkey=..., restval=..., dialect=...,
                 *args, **kwds): ...
    def __iter__(self): ...
    def __next__(self): ...
```
