### ISSUE TITLE
parsedate accepts None

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/typeshed#4713]
Functions `parsedate()`, `parsedate_tz()` and `parsedate_to_datetime()` in `email.utils` accept not only strings but also `None`. https://github.com/python/cpython/blob/master/Lib/email/_parseaddr.py#L67-L68

Actually they accept arbitrary false value, but None is the most common, because they are used in code like
```python
server_timetuple = parsedate(resp.headers.get("Date"))
```

**Comment by hauntsaninja** [comment]
Thanks, looks like `parsedate_to_datetime` cannot take None, but the others can. Easy overload to add.

**Comment by utsav00** [comment]
I'd like to work on this issue.

As I understand, all I have to do is cover the parameter/s with `Optional`, right?

**Comment by hauntsaninja** [comment]
It would be slightly better to use an overload, since if you pass in None, you'll always get None back (you'll never get a tuple)

**Comment by utsav00** [comment]
That makes sense.
I'll make changes this way then. Thank you!

**Comment by serhiy-storchaka** [comment]
> Thanks, looks like `parsedate_to_datetime` cannot take None, but the others can.

Indeed. And it seems a bug in Python. https://bugs.python.org/issue30681

**Comment by hauntsaninja** [comment]
With the fix merged 7 hours ago (and a decision made to not backport)! So we can add the overload for `parsedate_to_datetime` in 3.10 as well
