### ISSUE TITLE
PyJWT Exceptions

### ISSUE THREAD

**Issue by NovaNekmit** [python/typeshed#4745]
Problems:

The exceptions are stubbed in `jwt` (ie. `jwt.MissingRequiredClaimError`), but not the more explicit `jwt.exceptions` (ie  `jwt.exceptions.MissingRequiredClaimError`).  
Definitions are here: https://github.com/python/typeshed/blob/master/third_party/3/jwt/__init__.pyi#L25

`PyJWK{,Set,Client}Error` Exceptions are missing (see https://github.com/jpadilla/pyjwt/blob/master/jwt/exceptions.py#L57)

`MissingRequiredClaimError` is missing the `claim` attribute (see https://github.com/jpadilla/pyjwt/blob/master/jwt/exceptions.py#L51).
 Definition is here: https://github.com/python/typeshed/blob/master/third_party/3/jwt/__init__.pyi#L35)

**Comment by srittau** [comment]
In typeshed we usually try to follow the implementation in cases like this, so some reshuffling of the exceptions seem in order. (I didn't check.) PRs welcome for these (and any other) issues.

**Comment by jdufresne** [comment]
FWIW, the PyJWT has started including its own type annotations. Perhaps efforts would be better spent updating them in the library rather than in typeshed.

**Comment by hauntsaninja** [comment]
Closing as per https://github.com/python/typeshed/issues/4856
