### ISSUE TITLE
Return type of some pathlib.Path methods are too strict.

### ISSUE THREAD

**Issue by domdfcoding** [python/typeshed#4746]
Some methods of pathlib.Path return the same type as the class (e.g. `resolve`, `glob`). The stubs are correct for `resolve`:

```python
def resolve(self: _P, strict: bool = ...) -> _P: ...
```
but for `glob` they're down as always returning `Path`:

```python
def glob(self, pattern: str) -> Generator[Path, None, None]: ...
```

That should instead be:

```python
def glob(self: _P, pattern: str) -> Generator[_P, None, None]: ...
```

The same applies to `__enter__`, `iterdir` and `rglob` from what I can tell.

.

Happy to submit a PR for this.

**Comment by srittau** [comment]
PRs are always welcome!
