### ISSUE TITLE
ctypes stubs incomplete

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#475]
Sadly #454  leaves our code using ctypes a bunch of errors, not all of which are our fault. A few examples:
- `wintypes.pyi` is empty?!
- offset in `from_buffer_copy()` is optional
- apparently `c_char*16` is valid to declare a 16-byte buffer

**Comment by euresti** [comment]
Couple of others:
* offset in `from_buffer` is optional
* As typed `from_buffer` and `from_buffer_copy` expect _CData as first argument
* `from_buffer` and `from_buffer_copy` return _CData instead of the class that is being created.
(e.g.  
```
 from ctypes import Structure, c_ulong, c_ushort

class POINT(Structure):
   _fields_ = [(u"x", c_ulong),
               (u"y", c_ulong),
               ]

p = POINT()

buf = bytearray(b'\00' * 8 + b'\01' + b'\00' * 7)
p2 = POINT.from_buffer_copy(buf)

reveal_type(p)    # Point
reveal_type(p2)  # _CData
```
* The attributes of Structure can't be accessed.  So in the above `p.x` yields a type error.

**Comment by gvanrossum** [comment]
Fixing the return type of from_buffer()/from_buffer_copy() would require fixing python/mypy#1212; I think I'll use Any for now. This isn't great, but that bug is pretty subtle. Most other things are doable.

**Comment by gvanrossum** [comment]
Fixing `c_char*16` is also problematic, because `c_char` is a class! The `__mul__` operation is overloaded on the metaclass. But mypy doesn't support that yet. I think that's another case of python/mypy#1267.

**Comment by gvanrossum** [comment]
@matthiaskramm @tharvik How bad would it be if I just reverted #454? There's no way I can get our internal usages of ctypes to pass without fixing some tricky mypy issues (see previous comments). Putting `# type: ignore` in the stub won't be possible for these -- we'd have to ignore each call site of those features.

**Comment by tharvik** [comment]
> wintypes.pyi is empty?!

It is not documented and only available on Windows (which I don't have).

> Fixing c_char*16 is also problematic, because c_char is a class!

I found a way by using (not pretty, but working)
```python
class _MulType(Generic[_T]):
    def __call__(self, *args: Any, **kwargs: Any) -> _T: ...
    def __mul__(self, size: int) -> _MulType[_T]: ...

c_int = ...  # type: _MulType[_SimpleCData[int]]
```

@gvanrossum I guess we can revert it but keep this issue open to have a remainder to do something when mypy is fixed.

**Comment by gvanrossum** [comment]
I've deleted the ctypes stub for now. After mypy 0.4.4 has been released (tomorrow?) I'll try to restore the previous version and improve it to the point where our internal code can pass with it.

**Comment by JukkaL** [comment]
There's also the option of annotation `c_char` with type `Any`. Again, not optimal, but some type checking is better than nothing.

**Comment by gvanrossum** [comment]
I think @tharvik's solution can be made to work, I just don't want to do it so close to the 0.4.4 release.

**Comment by JelleZijlstra** [comment]
We have pretty good ctypes stubs now.
