### ISSUE TITLE
importlib.resources should be in 3.7/ ?

### ISSUE THREAD

**Issue by AllSeeingEyeTolledEweSew** [python/typeshed#4759]
Not sure how much this is a bug in typeshed, and how much in mypy, or whether I have missed something.

`importlib.resources` was introduced in 3.7. [The official docs reference a backport hosted in pypi](https://docs.python.org/3.9/library/importlib.html#module-importlib.resources).

I'd like to:
* Use `importlib.resources`
* Depend on the backport as needed, with a dependency like `importlib-resources>=3.3.0;python_version<3.7`
* Use mypy

But `importlib.resources` (exists in typeshed/stdlib/3)[https://github.com/python/typeshed/blob/master/stdlib/3/importlib/resources.pyi#L4], with all functions gated by a `sys.version_info` test.

So if I `mypy --python-version 3.6`, it checks typeshed instead of following the import. Using functions like `importlib.resources.read_text()` fails with undefined function errors.

I can't seem to tell mypy to follow the import instead of using typeshed. I could only solve this by `# type: ignore` on the line. This is frustrating because `mypy --python-version 3.7 --warn-unused-ignores` then complains about the ignore. The only code that passes in all versions looks like

```python
if sys.version_info < (3, 7):
    value = importlib.resources.read_text(...)  # type: ignore
else:
    value = importlib.resources.read_text(...)
```

I expect the problem might be fixed by moving `importlib.resources` into the `3.7` directory, but I haven't tested this.

**Comment by srittau** [comment]
If I understand correctly, the backport provides a `importlib_resources` module, not a `importlib.resources` module. We currently have no stubs for the former, but would accept gladly accept such stubs into typeshed. They would live in `third_party/3`. Your own code needs to either use `importlib_resources` exclusively or use a version check:

```python
if sys.version_info >= (3, 7):
    value = importlib.resources.read_text(...)
else:
    value = importlib_resources.read_text(...)
```

**Comment by AllSeeingEyeTolledEweSew** [comment]
Oh, you are right.

I'll make a PR for `third_party` when I get around to it.
