### ISSUE TITLE
threading: ExceptHookArgs funkiness

### ISSUE THREAD

**Issue by bluetech** [python/typeshed#4767]
The [`threading.excepthook`](https://docs.python.org/3/library/threading.html#threading.excepthook) variable (added in Python 3.8) accepts a `threading.ExceptHookArgs` argument (available at runtime). The typing around it in typeshed is not straightforward:

https://github.com/python/typeshed/blob/8c20938ba1118a9214265d7b5ae4ce1db4e322a5/stdlib/2and3/threading.pyi#L157-L164

Sorry but I guess I have to ask :grinning: 

The `_thread` part is:

https://github.com/python/typeshed/blob/8c20938ba1118a9214265d7b5ae4ce1db4e322a5/stdlib/3/_thread.pyi#L30-L38

My practical issue is that this:

```py
import threading

def my_hook(args: threading.ExceptHookArgs) -> None:
    ...
```

results in

```
Function "_thread._ExceptHookArgs" is not valid as a type  [valid-type]
```

**Comment by hauntsaninja** [comment]
I believe this goes back to https://github.com/python/typeshed/pull/3358 , cc @srittau

**Comment by srittau** [comment]
What I a useful comment I left there. The stubs try to follow the implementation ([starting here](https://github.com/python/cpython/blob/cd9fed6afba6f3ad2e7ef723501c739551a95fa8/Lib/threading.py#L1157)) and I guess I wanted to express my consternation about the weird renaming going on there. That said, I don't think the stubs are accurate. `_threading` contains the namedtuple `_ExceptHookArgs` (although the docstrings refer to it as `ExceptHookArgs`). This gets imported into `typing.pyi` as ExceptHookArgs` (making the docstrings correct).

(In case `_thread` is not available, `threading` does some weird things, but I think we should ignore that.)

What we should probably do:

* `_thread.pyi`:
    + Remove `_ExceptHookArgs`.
    + Rename `ExceptHookArgs` to `_ExceptHookArgs`.
    + Change the argument type of `_excepthook` to `_ExceptHookArgs`.
* `threading.pyi`:
    + Remove the import of `_thread.ExceptHookArgs`.
    + Change the argument type of `excepthook` to _ExceptHookArgs`.
