### ISSUE TITLE
README.md doesn't have instructions for running the tests

### ISSUE THREAD

**Issue by nicholasbishop** [python/typeshed#478]
I assume that running `./runtests.sh` is the right thing to do, but it would be helpful to have that noted in the README along with a list of requirements. For example, it seems the version of `mypy` I had installed was too old.

It would also help to document the expected output of the tests. I'm seeing lots of errors when running the tests, but I'm not sure if these errors are expected or indicate a problem with my environment. (If the errors are not expected let me know and I'll file a separate bug report for that.)

**Comment by gvanrossum** [comment]
Thanks for pointing this out -- it seems the README is out of date. The actual clues to running the tests are in .travis.yml, but we should really explain this better in the README. runtests.sh is really just a backwards compatibility hack; we now have separate test programs for mypy and pytype. And they should always be run with the latest of each package, and produce little or no output (certainly nothing that could be mistaken for an error :-).

**Comment by ambv** [comment]
This is solved AFAICT, the README now correctly points out how to run tests.

**Comment by gvanrossum** [comment]
(Yes, by fed966cf7f5b3cddb731b846f7781b863b47a7cc)
