### ISSUE TITLE
collections.UserString.encode() still broken?

### ISSUE THREAD

**Issue by LourensVeen** [python/typeshed#4786]
Last week I submitted #4781, which was promptly reviewed and applied (thanks again!), but now I think that's it's not good enough. I figured I'd make an issue and discuss before making even more of a mess.

When I made that PR, I had noticed that the return type was incorrect, and I verified that it returns bytes against the [latest CPython source](https://github.com/python/cpython/blob/master/Lib/collections/__init__.py#L1430). Then it occurred to me that I should check if Python 2 had a `UserString` class (I started Python programming with 3.4, and I've never done Python 2.7), and it turns out it does. I knew Python 2 didn't have `bytes`, but I found the [Python 2 Unicode HOWTO](https://docs.python.org/2/howto/unicode.html) which suggested that the return type of `encode()` is `str`. I never did check the implementation of its `UserString` however.

As it turns out, `UserString.encode()` has returned an object of the corresponding user string class for most of its existence. This was [recognised as a bug in 2019](https://bugs.python.org/issue36582), and fixed in Python 3.8. But that means that as per #4781, the types are correct for Python >= 3.8, but wrong for Python <3.8, whereas before they correctly described the buggy code in Python <3.8 but were wrong for Python >=3.8.

I'm not sure how to fix this now. Should the `3/` directory have the original code, and a new `3.8/` directory hold the new version? (As for my code, I'll switch to directly deriving from str rather than using UserString, but I want to clean up this mess I made.)

**Comment by srittau** [comment]
@LourensVeen Thanks for checking! Version checks within a file can be done like this:

```python
if sys.version_info >= (3, 8):
    foo
else:
    bar
```
