### ISSUE TITLE
codecs.StreamWriter is not recognized as a SupportsWrite

### ISSUE THREAD

**Issue by jwodder** [python/typeshed#4793]
Consider the following code:

```python
import codecs
from typing import BinaryIO

def print_to_bytes(fp: BinaryIO, s: str, encoding: str = "utf-8"):
    fptxt = codecs.lookup(encoding).streamwriter(fp, errors='surrogateescape')
    print(s, file=fptxt)
```

When type-checked with mypy (both version 0.790 and commit fc212ef893a0c3e6d500be89aa4d9302c1219595 from GitHub), the following error is produced:

```
stream-writer.py:6: error: Argument "file" to "print" has incompatible type "StreamWriter"; expected "Optional[SupportsWrite[str]]"
```

I believe this is an error (though I'm not sure if it's on the part of mypy or typeshed), as `StreamWriter` should *obviously* support `write()`; the declaration is [right here](https://github.com/python/typeshed/blob/9af49c0b69da063b6dc11eabb589691fa10d1607/stdlib/2and3/codecs.pyi#L200).

**Comment by hauntsaninja** [comment]
The issue is that the SupportsWrite protocol typeshed is using has an `int` return type on write, whereas StreamWriter.write returns None. The two options here seem to be a) relax the return type of SupportsWrite.write, or b) use a different, relaxed protocol for `print`'s file argument.

**Comment by Akuli** [comment]
I grepped for `SupportsWrite` in typeshed and checked the source codes of each usage. None of them use the return value of `write`, so it should be safe to change it to `Any`.

**Comment by hauntsaninja** [comment]
Thanks for checking that!
