### ISSUE TITLE
Error with memoryview.hex

### ISSUE THREAD

**Issue by hochl** [python/typeshed#4798]
**Bug Report**

MyPy detects an error when using `memoryview.hex`, when it shouldn't.

**To Reproduce**

---- test.py ----
a = bytes(16)
b = memoryview(a)
print(b.hex(" ", -2))
-----------------

$ mypy test.py
test.py:5: error: Too many arguments for "hex" of "memoryview"
Found 1 error in 1 file (checked 1 source file)

**Expected Behavior**

This should work, the arguments to hex are ok following the documentation.

**Actual Behavior**

You get the above error message.

**Your Environment**

- Mypy version used: mypy 0.790
- Mypy command-line flags: mypy test.py
- Mypy configuration options from `mypy.ini` (and other config files): no configuration files.
- Python version used: 3.8.6
- Operating system and version: current Debian testing.

**Comment by hauntsaninja** [comment]
Looks like this was added in 3.8, and typeshed adjusted stubs for bytes, but not for bytearray and memoryview (inspect.signature doesn't work on these builtins, which is why stubtest hasn't complained). Easy to fix, if you're willing to submit a PR.

**Comment by hochl** [comment]
Unfortunately I have no knowledge about these internals and cannot help with it. Maybe someone who has wants to fix it nonetheless? Additionally, if you use memoryview with the supplied named arguments, mypy does not understand these also.

**Comment by Akuli** [comment]
For anyone who wants to fix it (hochl or someone else), it's likely enough to copy the `def hex` stuff in `stdlib/3/builtins.pyi` from `class bytes` to `class bytearray` and `class memoryview`.
