### ISSUE TITLE
cryptography.hazmat.primitives.kdf.scrypt.Scrypt backend argument is optional, not required

### ISSUE THREAD

**Issue by HarrySky** [python/typeshed#4801]
I believe that here instead of `...` should be `None` for backend argument:
https://github.com/python/typeshed/blob/3d8a29705e939fc626c09381d36fdc380e041577/third_party/2and3/cryptography/hazmat/primitives/kdf/scrypt.pyi#L7

It is `None` in `cryptography` and you can just create Scrypt without it:
https://github.com/pyca/cryptography/blob/1be144acc6b46ae2ece459d80a20831ac2ac1c74/src/cryptography/hazmat/primitives/kdf/scrypt.py#L29

But mypy and other tools that depend on typeshed give me errors. Ready to send a PR switching `...` to `None`.

**Comment by srittau** [comment]
Default arguments should always be `...` in type stubs, the stubs look correct. But the argument was only changed to `Optional` two months ago in typeshed, so mypy's latest version has possibly not picked up the latest version of the stubs yet.

**Comment by HarrySky** [comment]
Thanks for explanation, waiting for new mypy release then :smile:
