### ISSUE TITLE
`datetime.datetime` should not inherit `datetime.date`

### ISSUE THREAD

**Issue by tomasaschan** [python/typeshed#4802]
`datetime.datetime` and `datetime.date` types cannot be used interchangeably, but the inheritance specified by the types in this project imply that they can. Consider the following code:
```
import datetime

def foo(d: datetime.date):
    return d < datetime.date.today()

foo(datetime.datetime.now()) # raises TypeError: can't compare datetime.datetime to datetime.date
```
Typechecking _should_ indicate a problem - but it doesn't, resulting in a runtime exception instead.

I [raised this issue with the Pyright project](https://github.com/microsoft/pyright/issues/1240), but was redirected here.

**Comment by srittau** [comment]
`datetime` inherits from `date` at runtime. In my opinion that's a mistake, but in typeshed we follow the implementation. Not inheriting in typeshed causes other problems.

**Comment by srittau** [comment]
Previous discussions in #3805 and python/mypy#9015.

**Comment by tomasaschan** [comment]
Thanks for linking me to those discussions! I'm glad that at least python/mypy#9015 is not closed yet, even if it also is not seeing much activity...
