### ISSUE TITLE
'cast' is missing overload for type 'builtins.object'

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#4810]
`cast` also accept arguments like `Optional[int]` and `Union[str, bytes]` which are not of type `Type` but instead are of type `builtins.object`. Such an overload however is missing from the typeshed which only lists overloads for `Type` and `str`

**Comment by septatrix** [comment]
Mypy currently does not generate warnings for such usage of `cast` as it handles it in a way which apparently also seems to suppress this error. Manually creating a new method with the same signature as is currently provided for `cast` however leads to errors from mypy when using such a method in the same places as `cast`.

**Comment by hauntsaninja** [comment]
See also: https://github.com/python/mypy/issues/9773

**Comment by septatrix** [comment]
Thanks for pointing me towards that issue. The example given there is also how I stumbled upon this bug (implementing a `cast`-like function). Even if that proposal leads to something the signature for `cast` should be adjusted for current versions.

**Comment by srittau** [comment]
True, `cast` should probably get another overload to handle these cases. PR welcome as always.
