### ISSUE TITLE
Missing type in function argument in tabulate package stubs

### ISSUE THREAD

**Issue by alexander-held** [python/typeshed#4829]
Hi, the [tabulate package](https://pypi.org/project/tabulate/) includes support for formatting tables given as lists of dictionaries. Such a table can be shown with custom headers, and [one of the supported formats for these headers are dictionaries](https://github.com/astanin/python-tabulate/blob/2552e6dfb23cac990aeabb27b86745878d62247e/tabulate.py#L1090).

Example:

```python
import tabulate

table = [{"name": "row 1", "val": 5}, {"name": "row 2", "val": 3}]
headers = {"name": "row names", "val": "number"}

print(tabulate.tabulate(table, headers=headers))
```

This outputs (with latest release `tabulate` 0.8.7, same behavior with [github master](https://github.com/astanin/python-tabulate), Python 3.8.3):

```
row names      number
-----------  --------
row 1               5
row 2               3
```

However, running `mypy` 0.790 on the above example results in
```
test.py:6: error: Argument "headers" to "tabulate" has incompatible type "Dict[str, str]"; expected "Union[str, Sequence[str]]"  [arg-type]
    print(tabulate.tabulate(table, headers=headers))
                                           ^
Found 1 error in 1 file (checked 1 source file)
```

#3391 removed `Dict[str, str]` from the possible types for the `headers` argument of `tabulate.tabulate`. I believe this should be added back. The addition of `Dict[str, str]` fixes the above `mypy` error.

The issue was also reported here https://bitbucket.org/astanin/python-tabulate/issues/184/headers-for-a-list-of-dicts-resulting-in.

I am happy to contribute a PR with this proposed change.

**Comment by srittau** [comment]
Cc @ilai-deutel as author of that PR. That said, it seems to me we should add it back. PR welcome. As a side note, we could replace `str` with `Literal["keys", "firstrow"]` if I understand the source code correctly. But that doesn't need to be part of this PR.

**Comment by alexander-held** [comment]
Thank you, I will open a PR shortly.

I agree that replacing `str` with `Literal["keys", "firstrow"]` seems correct for this argument. I am not familiar with the development of `tabulate`, and do not know how likely the addition of options in the future for this argument may be. It looks like in principle a few other arguments could be updated in a similar fashion as well.

I do not know the preferred approach for this type of issue - the more restrictive `Literal` may require more frequent updates but could catch additional issues now. If you prefer the restrictive approach, I am happy to include that as well, but will open the PR without that update first.
