### ISSUE TITLE
tkinter padx and pady

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4830]
This code
w = tk.Label(root)  # type: tk.Label
w.grid(row=0, column=0, padx=(0, 1))

gives this error:

: error: Argument "padx" has incompatible type "Tuple[int, int]" ; expected "Union[str, float]"

But padx and pady permit tuple values

**Comment by srittau** [comment]
Any PR to improve things are welcome!

**Comment by melassa** [comment]
It is my first attempt to use mypy. I don't know enough how it works.

**Comment by Akuli** [comment]
To fix this properly, you need to find all occurences of `padx` in the stubs, and figure out which of them need to be changed and how. Also change `pady` in exactly the same way.

**Comment by melassa** [comment]
Added a PR
