### ISSUE TITLE
tkinter Widget children

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4834]
This code is working without problems but mypy output is:
  error: "Frame" has no attribute "children"
  error: "Label" has no attribute "children"

Every Widget has the field 'children', but I see it only in Tk class not in Widget class

```

from typing import *
import tkinter as tk
root = tk.Tk()
print(type(root.children), repr(root.children))
fr = tk.Frame(root) # type: tk.Frame
print(type(fr.children), repr(fr.children))
lb = tk.Label(root)  # type: tk.Label
print(type(lb.children), repr(lb.children))

```

**Comment by Akuli** [comment]
Would you like to create a PR to fix this? The correct type for `children` is `Dict[str, Widget]`, where `Widget` represents any widget that goes inside another widget (and not literally any widget, like you would expect).

**Comment by melassa** [comment]
I am new in mypy stuff, can you tell me how i can change mypy to test changes? There is an how-to doc somewhere?

**Comment by Akuli** [comment]
I just tell mypy to use the typeshed repo I cloned with `--custom-typeshed-dir`:

```
$ mypy my_code.py --custom-typeshed-dir /path/to/the/typeshed/that/you/cloned
```

This doesn't seem to be the official way to do it though. There's some documentation in README.md and CONTRIBUTING.md.

**Comment by melassa** [comment]
Thanks for tips Akuli.
The type for in children in Tk is
   ` children: Dict[str, Any]`
you say:
   `Dict[str, Widget]`

What to do?

**Comment by melassa** [comment]
I think that children should be added to Misc and removed from Tk.

**Comment by Akuli** [comment]
Right. It's a thing that all widgets have, and those things should go to `Misc` because all widgets inherit `Misc`.

**Comment by melassa** [comment]
I have seen that `children` is added in BaseWidget (method `_setup`) in the `tkinter` module, perhaps we must follow it. 

I ask again:
The type for in children in Tk is
`children: Dict[str, Any]`
you say:
`Dict[str, Widget]`

What to do? Widget or Any?

**Comment by Akuli** [comment]
Tkinter's source code creates a `children` dict in two places:
- `BaseWidget._setup` adds it to every `_BaseWidget`
- `Tk.__init__` adds it to `Tk` widgets

So technically, you should copy/paste the exactly same definition of `children` to both `BaseWidget` and `Tk`, but it's better to add it to `Misc` instead and avoid the copy/pasta. That works because Tkinter widgets inherit from each other like this:

```
Misc
|-- BaseWidget
|   `-- all widgets except Tk
`-- Tk
```

You should just use `Dict[str, Widget]`. The current `Dict[str, Any]` was generated with stubgen and can be ignored.

**Comment by melassa** [comment]
Ok, but now this pass mypy and fails in python:

```
m=tk.Misc()
c=m.children

AttributeError: 'Misc' object has no attribute 'children'

```

**Comment by Akuli** [comment]
Because you are not supposed to create instances of `Misc` like that, I think that's much less bad than copy/pasting.
