### ISSUE TITLE
tkinter grid_info missing 'in' field

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4836]
This working code gives this mypy error:

`error: Extra argument "in" from **args`

`in` is missing from class `_GridInfo`
```
from typing import *
import tkinter as tk
root = tk.Tk()
lb = tk.Label(root, text='foo')
lb.grid(row=0, column=0)
gridinfo = lb.grid_info()
print(gridinfo)
lb.grid(**gridinfo)

```

**Comment by Akuli** [comment]
The problem is that `.grid()` should take an argument named `in`, corresponding to the `in` key of the TypedDict. But we can't literally write `in: SomeType` to the stubs, because `in` is a Python keyword. Currently the stubs only accept `in_`, but tkinter itself accepts both `in` and `in_`.

**Comment by JelleZijlstra** [comment]
Yes, not sure this is something we can support in stubs. If you really want to, you could probably write a mypy plugin that supports `in`.

**Comment by Akuli** [comment]
A workaround might be to define `.grid()` to take `**kwargs`

**Comment by JelleZijlstra** [comment]
Right, should have thought of that :) Feels like we should just do that.

**Comment by melassa** [comment]
Another thing, adding this working line of code in the above example:

`lb.grid(lb.grid_info())`

gives this error:

`error: Argument 1 has incompatible type "_GridInfo"; expected "Optional[Dict[str, Any]]"`

**Comment by Akuli** [comment]
To fix that one, `Dict[str, Any]` should be replaced with `Mapping[str, Any]`. This should allow it to be any dict with string keys, including all `_GridInfo`s.

**Comment by melassa** [comment]
Made a PR for Mapping but forgot to use isort...

**Comment by melassa** [comment]
OK now.

**Comment by Akuli** [comment]
Mapping PR is #4859
