### ISSUE TITLE
tkinter pack ipadx ipady do not accept Tuple[_ScreenUnits, _ScreenUnits]

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4861]
Pack ipadx and ipady in python do not accept tuple of ints as arguments.
But signature in typeshed is:
```
        ipadx: Union[_ScreenUnits, Tuple[_ScreenUnits, _ScreenUnits]] = ...,
        ipady: Union[_ScreenUnits, Tuple[_ScreenUnits, _ScreenUnits]] = ...,

```
Example:
```

import tkinter as tk
root = tk.Tk()
lb: tk.Widget = tk.Label(root, text='foo')
lb.pack(ipadx=(1, 10), ipady=(1, 5))

```
Gives this error under python 3.8.6:

`_tkinter.TclError: bad ipadx value "1 10": must be positive screen distance`

**Comment by melassa** [comment]
Things are more complex. This:

`lb.pack(ipadx=('1p', 10), ipady=('1p', 5))`

does not gives an error in python. 

But pack_info() return for ipadx and ipady is always an int, not a tuple. Seems a tkinter oddity.

**Comment by Akuli** [comment]
This is the same behaviour as for `padx` and `pady`: you can specify any screen units when setting it, but it's always returned as `int` or `Tuple[int, int]`.

To fix this, we should change `ipadx` and `ipady`, just like we changed `padx` and `pady` in #4830.

**Comment by melassa** [comment]
It is not the same thing.
This is tcl manual:

-**ipadx** amount
    Amount must be a valid screen distance, such as 2 or .5c.

-**padx** amount
    Amount may be a **list of two values** to specify padding for
    left and right separately.

**Comment by Akuli** [comment]
I read this issue wrong. You are right, ipadx and ipady should not be tuples in `pack` or `grid`.
