### ISSUE TITLE
tkinter BaseWidget is missing some method and fields

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4862]
Is missing: `def _setup(self, master, cnf)`
Is missing also the `_name` field defined in _setup().
Is missing also the `_w` field defined in _setup().

Is missing also the deprecated `_do` method.
See also #4834 for `children`

**Comment by Akuli** [comment]
I think this can be closed. We already have #4834 for children, and other attributes are non-public.

We also have #4658, related to `_name`

**Comment by JelleZijlstra** [comment]
Our policy is to add even private attributes if users request them. Feel free to submit PRs to add the ones mentioned here if you actually need them.

**Comment by melassa** [comment]
I don't need them. Can be closed for me.
