### ISSUE TITLE
hex() is missing from builtin bytes definition

### ISSUE THREAD

**Issue by claws** [python/typeshed#488]
Mypy (mypy-lang (0.4.3) is complaining about ``.hex()`` not being a valid method on a ``bytes`` object.

I have something like this in my Python 3.5 code.

``` python
a = b'test'
a.hex()
```

When I run ``mypy`` on the module the following error is generated.

``` console
$ mypy example.py 
example.py:3: error: "bytes" has no attribute "hex"
```

The ``.hex()`` method was added to a few objects in Python 3.5 ([Issue9951](https://bugs.python.org/issue9951)) and appears to be missing from few type definitions in the typeshed builtins. 

To resolve this issue I think that the ``typeshed/stdlib/3.5`` area needs to be updated to add the ``hex`` method to at least the ``bytes`` and ``bytearray`` objects .

**Comment by gvanrossum** [comment]
Thanks! You're absolutely right, and this is still a problem.

Could you try to submit a PR yourself? Because this is builtins.pyi, I recommend not using stdlib/3.5, but instead add the new methods to the existing builtins.pyi protected by
```
if sys.version_info >= (3, 5):
```

**Comment by claws** [comment]
Sure, will do.

**Comment by claws** [comment]
I've submitted PR #507.
