### ISSUE TITLE
tkinter Widget do not accept .cget

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4889]
With this code:

```
def func(w: tk.Widget) -> Any:
    return w.cget()
```
 Mypy output is:
```
error: "Widget" has no attribute "cget"
```
I think that Misc should have a generic definition of cget() . 
Something like this::

```def cget(self, key: str) -> Any: ...```

I tried this change and got no problem. 

This case, indeed, is problematic:
```

def func(w: Union[tk.Widget,tk.Toplevel,tk.Tk]) -> str:
    return w.cget('cursor')

```
Mypy output:

`
error: Cannot determine type of 'cget'
`

The workaround:

```
def func(w: Union[tk.Widget, tk.Toplevel, tk.Tk]) -> str:
    w = cast(tk.Widget, w)
    return w.cget('cursor')

```

.configure has the same problem, but is more hard to fix.

**Comment by Akuli** [comment]
Currently `.cget()` behaves quite weirdly, and only accepts strings that are known to be valid, so `label.cget("lol")` will fail but `label.cget("text")` works. This was my idea, and it was introduced in #4363. Now I think that's dumb and `cget()` should instead take `str` and return `Any`, just like you suggested.

You can already treat the widget as a dict, as in `return w['cursor']`, and that should work.

**Comment by melassa** [comment]
`return w['cursor']`

Yes it works and i use it  a lot. I changed all my .config .configure and .cget to dict access just to use mypy...

**Comment by Akuli** [comment]
>I changed all my .config .configure and .cget to dict access just to use mypy...

Seems like #4363 is not working as intended at all. I changed all of my dict access code to use `.cget()` and `.configure()` just to use mypy, and I found some bugs that way.

**Comment by melassa** [comment]
What a change!
