### ISSUE TITLE
Template has no attribute "pattern"

### ISSUE THREAD

**Issue by jukebox** [python/typeshed#491]
```
[juke@jhebert:~/snip/python/template] % cat template.py 
from string import Template 

class MyTemplate(Template):
    pass

mt = MyTemplate("foo ${foo}")
print(mt.pattern)
[juke@jhebert:~/snip/python/template] % mypy template.py 
template.py:7: error: "MyTemplate" has no attribute "pattern"
```

**Comment by ddfisher** [comment]
Good catch.  Would you be interested in submitting a PR?

**Comment by elazarg** [comment]
This attribute is not mentioned in the docs.

**Comment by gvanrossum** [comment]
Let's close this. If you can file a doc bug on bugs.python.org maybe we can get a ruling on whether this is a doc oversight or intentionally omitted; if they accept it as a doc bug you can reopen here.
