### ISSUE TITLE
Some overrides for memoryview.__setitem__ are incorrect

### ISSUE THREAD

**Issue by monkeyman79** [python/typeshed#4940]
The following lines from [builtins.pyi](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi):
```python
class memoryview(Sized, Container[int]):
...
    @overload
    def __setitem__(self, i: int, o: bytes) -> None: ...
    @overload
    def __setitem__(self, s: slice, o: Sequence[bytes]) -> None: ...
```
imply that this incorrect code is valid:
```python
b=bytearray(12)
mv=memoryview(b)
mv[5]=b'a'
mv[2:4]=(b'a', b'b', b'c')
```

Instead it should read:
```python
class memoryview(Sized, Container[int]):
...
    @overload
    def __setitem__(self, i: int, o: int) -> None: ...
    @overload
    def __setitem__(self, s: slice, o: bytes) -> None: ...
```
so that mypy won't complain about this valid code:
```python
b=bytearray(12)
mv=memoryview(b)
mv[5]=65
mv[2:5]=bytes((65, 66, 67))
mv[2:5]=b'xyz'
```

**Comment by Akuli** [comment]
Maybe it should be same as in `class bytearray`, like this?

```python3
    @overload
    def __setitem__(self, i: int, x: int) -> None: ...
    @overload
    def __setitem__(self, s: slice, x: Union[Iterable[int], bytes]) -> None: ...
```

**Comment by Akuli** [comment]
Also, I think that `Union` in `class bytearray` is unnecessary, because `bytes` inherits from `typing.ByteString` which inherits from `Sequence[int]`.

**Comment by hauntsaninja** [comment]
`Iterable[int]` is looser than `Sequence[int]`, so not redundant (if correct)

**Comment by Akuli** [comment]
I was wondering whether it could be just `Iterable[int]` instead of `Union[Iterable[int], bytes]`.

**Comment by monkeyman79** [comment]
`Sequence[int]` is not good for `memoryview`:
```
>>> b=bytearray(5)
>>> mv=memoryview(b)
>>> mv[:]=(1,2,3,4,5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: a bytes-like object is required, not 'tuple'
```

**Comment by hauntsaninja** [comment]
That settles that :-) Anyway, PR welcome!

**Comment by monkeyman79** [comment]
While we are at it. Should it be this:
```python
    @overload
    def __setitem__(self, s: slice, o: memoryview) -> None: ...
    @overload
    def __setitem__(self, i: int, o: int) -> None: ...
    @overload
    def __setitem__(self, s: slice, o: bytes) -> None: ...
```
Or this:
```python
    @overload
    def __setitem__(self, s: slice, o: Union[memoryview, bytes]) -> None: ...
    @overload
    def __setitem__(self, i: int, o: int) -> None: ...
```
What's the difference between those?

Also, will that cover the case of assigning `bytearray`?

**Comment by hauntsaninja** [comment]
bytes will cover bytes, bytearray and memoryview https://github.com/python/typing/issues/552#issuecomment-684011804

There isn't a difference between your two options. Prefer the version with Union.
