### ISSUE TITLE
Missing email.errors classes

### ISSUE THREAD

**Issue by The-Compiler** [python/typeshed#4941]
The `email.errors` module has various error classes which are not in the stubs:

https://github.com/python/cpython/blob/master/Lib/email/errors.py
https://github.com/python/typeshed/blob/master/stdlib/3/email/errors.pyi

However, at least some of those don't actually seem to be documented:

https://docs.python.org/3/library/email.errors.html

Should those be in the stubs? Is it perhaps a Python bug that those aren't documented?

**Comment by JelleZijlstra** [comment]
We should definitely add all the documented ones, and we should add undocumented ones if they're useful to people writing code.

The Python bug tracker may give you a different answer, but I'd say the Python docs should include every error class that may be raised from the public interface of the email package. I haven't checked whether that's true for all of these classes.
