### ISSUE TITLE
Make e.g. `float.__add__` generic?

### ISSUE THREAD

**Issue by tyralla** [python/typeshed#4946]
Mypy currently reports the following error:

```
from typing import TypeVar, Union

T1 = TypeVar("T1", bound=float)
T2 = TypeVar("T2", bound=float)

def add(x: T1, y: T2) -> Union[T1, T2]:
    return x + y  # Incompatible return value type (got "float", expected "Union[T1, T2]")
```

In my understanding, this is due to the non-generic typing of `float.__add__` in `builtins.pyi`.

Annotating this method (and the similar ones of float, int, bool...) also with bounded type variables seems to fix this issue:

```
T1 = TypeVar("T1", bound=float)
T2 = TypeVar("T2", bound=float)

class float:
    def __add__(self: T1, x: T2) -> Union[T1, T2]: ...

class int:  # why not a subclass of int?
    def __add__(self: T1, x: T2) -> Union[T1, T2]: ...

class bool(int):
    ...  # no need to redefine __add__, inherited from int
```` 

If that's considered useful, I could do it in the near future. However, I did not contribute to Typeshed so far (only to Mypy), and so far I don't really see the best way to define (or change) the related test cases.

**Comment by JelleZijlstra** [comment]
Union return types are a risky proposition because they often make user code annoying to write (since mypy will force you to narrow down the union). In CI we run a tool (mypy-primer) that tries out the change on various open-source projects, so you could make a PR and see what mypy-primer has to say.

**Comment by tyralla** [comment]
In my test calculations, Mypy narrows the union automatically. But maybe I miss some important cases. Searching for potential problems with mypy-primer is certainly a good idea. Great to have such a tool readily set up. I will try it.

**Comment by JukkaL** [comment]
The proposed signature for `__add__` does not match runtime behavior:

```py
>>> class F(float): pass
>>> type(F() + F())
<class 'float'>
```

If the generic signature was correct, the type of the result should be `F`, but it's actually `float`. So `float` seems like the best return type for `float.__add__`. `int`, `str` and others are similar.

**Comment by tyralla** [comment]
Oh, I see, you are right.  I only work with `float`, `int`, and `bool` directly and do not subclass them. Hence, I did not see this problem.

Even worse: 

```
>>> type(False + False)
<class 'int'>
```

It seems like I need to use constrained type variables instead of bounded type variables to annotate the `add` function of my original problem correctly:

```
from typing import TypeVar, Union, TYPE_CHECKING

T1 = TypeVar("T1", float, int)
T2 = TypeVar("T2", float, int)

def add(x: T1, y: T2) -> Union[T1, T2]:
    return x + y

z1 = add(x=True, y=1.0)
z2 = add(x=True, y=1)
z3 = add(x=True, y=True)

print(type(z1))  # <class 'float'>
print(type(z2))  # <class 'int'>
print(type(z3))  # <class 'int'>
if TYPE_CHECKING:
    reveal_type(z1)  # Revealed type is 'builtins.float*'
    reveal_type(z2)  # Revealed type is 'builtins.int*'
    reveal_type(z3)  # Revealed type is 'builtins.int*'
```

Thank you very much for your help!
