### ISSUE TITLE
tkinter configure state does not accept 'readonly'

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4947]
```
root = tk.Tk()
sp = ttk.Spinbox(root)
sp.configure(state='readonly')

```
error:
`Mypy: No overload variant of "configure" of "Spinbox" matches argument type "str"`

This happens also with other ttk widgets and, i think, with others values.

**Comment by Akuli** [comment]
The problem is [here](https://github.com/python/typeshed/blob/b4e447d70af36d7a216f002ecfd9df0d8745045d/stdlib/3/tkinter/ttk.pyi#L828). It should also allow `"readonly"`. I haven't read the manual page carefully enough when making the stub.

Can you check which ttk widgets support `"readonly"`? I don't think they all support it.

**Comment by melassa** [comment]
From doc:
Spinbox: Dynamic states: active, disabled, focus, readonly. 
Combobox: disabled, focus, pressed, readonly. 
Checkbox:  active, alternate, disabled, pressed, selected, readonly. 

I do not know if all can be set.

**Comment by melassa** [comment]
ttk.Entry: : disabled, focus, readonly.

**Comment by Akuli** [comment]
>I do not know if all can be set. Doc are not clear about them.

Tkinter things like this require just trying it out yourself.

**Comment by Akuli** [comment]
I think it might be best to allow all strings. I tried to write a script to check which states are supported, but setting a bad state to a ttk widget is not an error.

Also, I think the state can be an arbitrary string, as long as the ttk theme supports it, but I can't find this from the documentation now.

**Comment by melassa** [comment]
Could be.
I see in configure() state these flags: normal active disabled readonly

Il giorno mar 19 gen 2021 alle ore 17:30 Akuli <notifications@github.com>
ha scritto:
