### ISSUE TITLE
Stubs for pyVmomi no longer export many important types

### ISSUE THREAD

**Issue by tomaciazek** [python/typeshed#4957]
Looks like [this](https://github.com/python/typeshed/pull/4390) change removed some import statements, so that now IDEs using Typeshed no longer recognize most of the types under `vim` and `vmodl`.

I suppose that change was misguided by an empty root __init__.py file?

**Comment by srittau** [comment]
The imports in question were not re-exported, so if an IDE recognized them before it was ignoring PEP 484. That said, if some of those imports should be re-exported from the stubs in question, we gladly accept PRs that add those re-exports (using the `from X import Y as Y` syntax.)

**Comment by srittau** [comment]
Closing per my last comment.
