### ISSUE TITLE
tkinter ttk.Scale variable does not accept IntVar and Variable

### ISSUE THREAD

**Issue by melassa** [python/typeshed#4959]
```
import tkinter as tk
from tkinter import ttk
root = tk.Tk()
ttk.Scale(from_=-100, to=100, variable=tk.IntVar())

```
Mypy error:

`Mypy: Argument "variable" to "Scale" has incompatible type "IntVar"; expected "DoubleVar"`

It accepts any Var also tk.Variable()

**Comment by Akuli** [comment]
Same in `tkinter.Scale`
