### ISSUE TITLE
pytype has a new stub parser

### ISSUE THREAD

**Issue by rchen152** [python/typeshed#4962]
Hi folks!

Apologies if this isn't the right venue for this sort of announcement. I just wanted to give a heads-up that the pytype stub parser might be a little buggy for a bit, as we've just swapped out pytype's old parser for a shiny new one based on typed_ast (developed by @martindemello over many tireless months!). If you encounter any issues, you can report them on https://github.com/google/pytype/issues/816 (or just ping me on the typeshed PR if that's easier).

In the long term, we hope that using typed_ast will be a considerable improvement, as there shouldn't be any more weird errors involving Python syntax that pytype can't parse.

**Comment by srittau** [comment]
This also probably means that the pytype exclude list can be whittled down a bit.

**Comment by rchen152** [comment]
That's a good point! I'll look into that after the typeshed restructure.

**Comment by Akuli** [comment]
Currently pytype_test seems to work only on Python 3.6 (errored for me on 3.7). Should we change the CI to run it on newer pythons too, and change the exclude list accordingly?

**Comment by rchen152** [comment]
Huh, those are some weird errors. Since they're in stdlib, I'd prefer to fix them rather than exclude the files - I'll take a look this weekend. Thanks for bringing this to my attention.

**Comment by rchen152** [comment]
Ok, with pytype 2021.05.11, pytype_test passes in 3.7 and 3.9 (and hopefully 3.8).
