### ISSUE TITLE
PEP 570 (Positional-only Argument Syntax) tracker

### ISSUE THREAD

**Issue by srittau** [python/typeshed#4972]
This issue is supposed to track when we can start to use Python's standard positional-only argument syntax ([PEP 570](https://www.python.org/dev/peps/pep-0570/)) in typeshed. Support is needed in released versions of:

* [x] mypy (supported when running under Python 3.8+)
* [x] pytype
* [x] pyright
* [x] pyre
* [X] PyCharm

**Comment by sproshev** [comment]
Supported in PyCharm more than a year https://youtrack.jetbrains.com/issue/PY-35512

**Comment by layday** [comment]
This appears to be supported in Pyright at least since 1.1.0 released in November 2019.

**Comment by srittau** [comment]
@pradeep90 Are PEP 570-style positional arguments (i.e. `def foo(arg, /): ...`) supported in pyre?

**Comment by pradeep90** [comment]
@srittau  Yes, they're supported in Pyre.

**Comment by AlexWaygood** [comment]
@rchen152, does https://github.com/google/pytype/commit/3e228a03c7428ee03e33460ca239155063b91689 mean that pytype now supports PEP 570? :)

**Comment by hauntsaninja** [comment]
I believe PEP 570 requires 3.8 for mypy / ast, not 3.7

**Comment by AlexWaygood** [comment]
> I believe PEP 570 requires 3.8 for mypy / ast, not 3.7

mypy seems able to cope on 3.6 [on the playground](https://mypy-play.net/?mypy=latest&python=3.6&gist=77c1ce5e550248c1663f6caee8b2c4e2).

**Comment by srittau** [comment]
> I believe PEP 570 requires 3.8 for mypy / ast, not 3.7

Fixed (without testing).

**Comment by rchen152** [comment]
@AlexWaygood Yes, it's supported now!

**Comment by AlexWaygood** [comment]
> @AlexWaygood Yes, it's supported now!

Awesome!
