### ISSUE TITLE
Fix minimum supported versions in METADATA.toml

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#4981]
This is a follow up from #2491

It looks like we set `version = "0.1"` for all third party packages. We should try and get these up to date.
A possible idea for determining the oldest supported package version via automation are is by using stubtest to quantify how compatible the stubs are with a given package version relative to latest.

**Comment by ilevkivskyi** [comment]
> It looks like we set version = "0.1" for all third party packages.

For half dozen packages, I already set them manually to some known versions. But yes, doing this in some automated way would be great, otherwise it would be a lot work.
