### ISSUE TITLE
IO[AnyStr] or IO[Any]?

### ISSUE THREAD

**Issue by xuhdev** [python/typeshed#4984]
I see that both `IO[AnyStr]` and `IO[Any]` are used in typeshed. Are they the same? Seems like `IO[Any]` is not [documented](https://docs.python.org/3/library/typing.html#typing.IO).

**Comment by JelleZijlstra** [comment]
`IO[AnyStr]` only makes sense in the context of a signature that helps type checkers figure out whether `str` or `bytes` is meant. `IO[Any]` just means it could be either bytes or str and we have no way to figure it out.
