### ISSUE TITLE
Support more flexible dependencies in METADATA.toml?

### ISSUE THREAD

**Issue by ilevkivskyi** [python/typeshed#4995]
Currently only simple dependencies like `types-foo` or `types-bar>=1.2` are supported. Here are some ideas for more flexibility (both format and logic):
* Allow spaces and/or quotes for versions
* Allow multiple version conditions, like `types-foo>1,<2` (supported by pip)
* Allow python-version-specific dependencies, like `types-foo>=1.2; python_version>3.7`
* Allow depending on trusted third party inline packages

Last one (or two?) may require some non-trivial work w.r.t. to mypy/pytype tests.

**Comment by srittau** [comment]
I think especially the second and fourth point will eventually be necessary. But we can implement this when we need it, I guess.

**Comment by hauntsaninja** [comment]
Yeah, agreed on implementing things as they come up, e.g. we have #5768

Note that [packaging](https://pypi.org/project/packaging/) makes parsing specifiers easy, so we should minimise doing things ourselves with regex.
