### ISSUE TITLE
Type annotation for _weakref.getweakrefs() is wrong

### ISSUE THREAD

**Issue by dargueta** [python/typeshed#4999]
Currently, the type annotation for `weakref.getweakrefs()` is:

```py
def getweakrefs(object: Any) -> int: ...
```

The return type is wrong. [The documentation](https://docs.python.org/3/library/weakref.html#weakref.getweakrefs) states that it returns a list of all weak references and proxies to the object. Thus, the annotation should be something along the lines of:

```py
def getweakrefs(__object: _T) -> List[Union[ReferenceType[_T], ProxyType[_T], CallableProxyType[_T]]]: ...
```

**Comment by srittau** [comment]
It's probably better to just return `list[Any]`, due to the typical complications with returning unions. RP welcome.
