### ISSUE TITLE
tkinter text tag_config with font

### ISSUE THREAD

**Issue by melassa** [python/typeshed#5011]
This is the working code:

```
t = tk.Text()
t.tag_config('helv', font=('helvetica', 12, 'bold', 'italic'))

```
This is mypy error:

`Mypy: Argument "font" has incompatible type "Tuple[str, int, str, str]"; expected "Union[str, Font, Tuple[str, int], Tuple[str, int, str], Tuple[str, int, Union[List[str], Tuple[str, ...]]]]"`

Probably it is a problem everywhere _FontDescription is used.

(I made the test with the mypy version of typeshed, mypy does not accept the new directory structure of typeshed AFAIK)

**Comment by JelleZijlstra** [comment]
cc @Akuli as our tk expert

**Comment by hauntsaninja** [comment]
You'll need to use mypy master to get it to recognise the new typeshed structure

**Comment by Akuli** [comment]
The correct type of _FontDescription would be some kind of big `Union` of many different possibilities, to accept e.g. all of these:

```
('Helvetica', 12)
('Helvetica', 12, '')
('Helvetica', 12, 'bold italic')
('Helvetica', 12, 'bold', 'italic')
('Helvetica', 12, ('bold', 'italic'))
('Helvetica', 12, ['bold', 'italic'])
['Helvetica', 12]
['Helvetica', 12, '']
['Helvetica', 12, 'bold italic']
['Helvetica', 12, 'bold', 'italic']
['Helvetica', 12, ('bold', 'italic')]
['Helvetica', 12, ['bold', 'italic']]
```

Instead of `bold` and `italic`, there could be any number of strings.

Unfortunately we can't use `_TkinterSequence2D[Union[str, int]]`, because that can't contain `int`s or `str`s directly.

**Comment by melassa** [comment]
List[] accepts only an argument.

**Comment by melassa** [comment]
Working example with many strings:

`('helvetica', 12, 'bold', 'italic', 'underline', 'overstrike')`
