### ISSUE TITLE
Should unittest.mock.assert_has_awaits() take a List[_Call] instead of _CallList?

### ISSUE THREAD

**Issue by JonathanMeans** [python/typeshed#5012]
I've been dealing with a mypy error, and I believe it could be due to a typing bug.

The docs for the function suggest that it should be able to take a regular list: https://docs.python.org/3/library/unittest.mock.html#unittest.mock.AsyncMock.assert_has_awaits

```
calls = [call("foo"), call("bar")]
mock.assert_has_awaits(calls)
```

But mypy is complaining when I do it about getting a List[_Call] instead of a _CallList.

**Comment by srittau** [comment]
You are correct, this is a bug in typeshed. Looking at the implementation of `assert_has_awaits`, it accepts any kind of iterable, actually. PR welcome.
