### ISSUE TITLE
Missing type annotations for properties on logging.LoggerAdapter

### ISSUE THREAD

**Issue by yoavp10** [python/typeshed#5015]
Hi,
LoggerAdapter class have 2 new properties starting from version 3.6*:
manager (getter and setter)
name (getter)

This have no equivalent in typeshed, I'd like to create them. What do you think?

*Unfortunately these properties can't be found on the official cpython docs, however I found the relevant python bug and pr's:
https://bugs.python.org/issue31457
https://github.com/python/cpython/pull/3551/commits/cf2a4f96d68201e1ab9602eeaa6eff44cbae50c9
https://github.com/python/cpython/pull/4050/commits/fee0475bf285a2886f98a7422ceef0dc3ac46525
I opened a [docs bug](https://bugs.python.org/issue43184?) for cpython and plan on making a PR on this front too.

**Comment by Akuli** [comment]
I believe the typeshed convention is to add attributes like this with a comment `# undocumented`. Even pull requests adding `_non_public` attributes are accepted when someone needs those non-public attributes.

**Comment by Akuli** [comment]
fixed in #5388
