### ISSUE TITLE
Incorrect return type for FlaskClient::session_transaction

### ISSUE THREAD

**Issue by nbhargava** [python/typeshed#5016]
The current typeshed types for Flask seem to indicate that `FlaskClient`'s `session_transaction` does not return a value, but the [current flask docs](https://flask.palletsprojects.com/en/1.1.x/api/?highlight=session_transaction#flask.testing.FlaskClient.session_transaction) give an example where this is not the case:
```
with client.session_transaction() as session:
    session['value'] = 42
```

For accurate typing in tests, I believe this should be updated with a return type.

**Comment by srittau** [comment]
PRs welcome!

**Comment by Akuli** [comment]
It might be worth noting that the code example doesn't assign `session` to `client.session_transaction()`. It instead expects it to have `__enter__` and `__exit__` methods, and assigns `session` to return value of `client.session_transaction().__enter__()`. (Often `__enter__` returns `self` unchanged.)

**Comment by srittau** [comment]
Closing as the flask stubs will be removed in a few months.
