### ISSUE TITLE
No module named '_typeshed'

### ISSUE THREAD

**Issue by alexreg** [python/typeshed#5021]
I'm getting this error from the line `from _typeshed import AnyPath` -- surely that's valid?

```
Traceback (most recent call last):
  File "/Users/alex/foo/script", line 23, in <module>
    from common import *
  File "/Users/alex/foo/common.py", line 1, in <module>
    from _typeshed import AnyPath
ModuleNotFoundError: No module named '_typeshed'
```

Running Python 3.9.1 on macOS 11.2.1.

**Comment by hauntsaninja** [comment]
Nope, no such module exists at runtime. https://github.com/python/typeshed/blob/0b1cd5989669544866213807afa833a88f649ee7/stdlib/_typeshed/__init__.pyi#L3

**Comment by alexreg** [comment]
Ah, sorry. I suppose I should avoid using `AnyPath` then, and use `PathLike` or such instead.

**Comment by srittau** [comment]
@alexreg: You can also use a guard:

```python
from __future__ import annotations
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from _typeshed import ...
```

**Comment by alexreg** [comment]
@srittau Thanks, that's a good idea!
