### ISSUE TITLE
tarfile gzopen name=None

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5027]
Passing in `None` to `gzopen` is useful for extracting files without saving them to disk, but currently the stubs don't support it:

```
import tarfile
import io
import requests

response = requests.get(...)
response.raise_for_status()
tarfile.TarFile.gzopen(None, fileobj=io.BytesIO(response.content)).extractall('lib')
```

**Comment by 01-vyom** [comment]
I have a solution for this issue.
Change `name:` parameter type to the following:
```diff
+name: Optional[AnyPath] 
```

Can I make a PR to solve this issue?

**Comment by srittau** [comment]
Yes, PRs are always welcome.

**Comment by Akuli** [comment]
Other methods may need a similar fix too

**Comment by 01-vyom** [comment]
You can create a new Issue that tracks all the `classmethod` of `TarFile` stub class altogether for the `None` type argument change.
