### ISSUE TITLE
Subclass of float with its own __round__ method reports the wrong type returning from round()

### ISSUE THREAD

**Issue by hudcap** [python/typeshed#5029]
Original issue reported here: https://github.com/microsoft/pylance-release/issues/958

I have a custom number class that subclasses `float` and overrides `__round__` (among other methods) to return my custom class. When I use `round` on an instance of my class, it correctly returns another instance of said class.

However, when I call `round()` on an instance of my class, the type is considered to be a `float` instead. This seems to be because the overload for `float` comes before the overload for `SupportsRound[_T]` and my class inherits `float`, so `round` gets matched too early.

I'll quote @erictraut here:

> Arguably, the first of the two overloads (the one with the float) is unnecessary because the float class implements the SupportsRound protocol. So maybe the right answer here is to delete the unnecessary one.

Happy to open a PR if this is the way to go.

There is another issue open on the topic of `SupportsRound` that is somewhat related: https://github.com/python/typeshed/issues/2638

## MWE

```python
from typing import SupportsRound


class MyNumber(float, SupportsRound["MyNumber"]):
    def __new__(cls, value: float):
        return super().__new__(cls, value)

    def __round__(self, ndigits: int = 0):
        return MyNumber(super().__round__(ndigits))


n: MyNumber = round(MyNumber(3.14), 0) # pylance error
# Expression of type "float" cannot be assigned to declared type "MyNumber"
#     "float" is incompatible with "MyNumber"

assert isinstance(n, MyNumber) # no problem here
```

**Comment by srittau** [comment]
Deleting the `float` overloads sounds right to me. If you open a PR, our tests and mypy_primer should give a good indication whether this will cause any problems.

**Comment by JelleZijlstra** [comment]
(Note for next time "Solves" is not among the words github recognizes to auto-close an issue.)
