### ISSUE TITLE
binascii functions should take Union[bytes, str]

### ISSUE THREAD

**Issue by johnthagen** [python/typeshed#503]
This code seems valid (tested on Python 3.5):

```python
>>> import binascii
>>> binascii.a2b_hex('12ff')
b'\x12\xff'
```

But Mypy 0.4.4 complains:
```
a.py:3: error: Argument 1 to "a2b_hex" has incompatible type "str"; expected "bytes"
```

Should we be accepting `Union[bytes, str]` for these functions?

**Comment by gvanrossum** [comment]
Can you come up with a PR for this? Also please put a reference to the docs that say this is supposed to work there.

**Comment by johnthagen** [comment]
Sure thing.
