### ISSUE TITLE
How to properly stub a type defined in C by a library?

### ISSUE THREAD

**Issue by j2kun** [python/typeshed#5031]
I'm working with the gmpy2 library, which defines (in C) a new type called `mpz`, which is also the type constructor, e.g.

```python
>>> from gmpy2 import mpz
>>> x = mpz(2)
>>> x
mpz(2)
>>> type(x)
<class 'mpz'>
>>> type(type(x))
<class 'type'>
>>> type(mpz)
<class 'builtin_function_or_method'>
```

But when I try to create a stub for this function, mypy complains.

```
def mpz(n: int) -> mpz: ...

# run mypy...
stubs/gmpy2.pyi:1: error: Function "gmpy2.mpz" is not valid as a type
```

I've also tried a stub like

```
import gmpy2

mpz_t = type(gmpy2.mpz(1))

def mpz(n: int) -> mpz_t: ...
```

What am I doing wrong? Is there another example of a C-defined type that has stubs I could model mine after?

**Comment by j2kun** [comment]
BTW, this is with Python 3.7.2, and

gmpy2==2.0.8
mypy==0.800
mypy-extensions==0.4.3

**Comment by srittau** [comment]
There are two alternatives I can see:

* Cheat a bit and make `mpz` a class.
* Introduce a class `_mpz` (or similar) and return that from `mpz` and use it for type annotations.

That said, such questions are more suited for gitter: https://gitter.im/python/typing.
