### ISSUE TITLE
jwt.algorithms.RSAAlgorithm.to_jwk(...) says "expected _K"

### ISSUE THREAD

**Issue by euresti** [python/typeshed#5034]
My code is trying to call:
```
jwt.algorithms.RSAAlgorithm.to_jwk(public_key)
```

But I get this error:`Argument 1 to "to_jwk" of "Algorithm" has incompatible type "RSAPublicKey"; expected "_K"`

This seems to happen because `@staticmethod` does not participate in the Generic.  I'm not sure if this is by design in mypy or whether the stub needs to be modified.  I'll start here.

Hmm. It does work if you create the instance first.  
```
jwt.algorithms.RSAAlgorithm().to_jwk(public_key)
```

**Comment by srittau** [comment]
Interesting case. I think in this particular case mypy should recognize that `_K` is aliased to `Any`. That said, we can easily work around this problem in typeshed by providing a definition for `to_jwk()` in `RSAAlgorithm`.

**Comment by 01-vyom** [comment]
I got the gist of the problem and I would like to work on this issue.

**Comment by srittau** [comment]
As always, PRs are welcome!

**Comment by 01-vyom** [comment]
This issue can be closed as I solved it in the PR.
