### ISSUE TITLE
Argument type of `set_cookie` is wrong for werkzeug

### ISSUE THREAD

**Issue by libre-man** [python/typeshed#5058]
The argument type of `set_cookie` is incorrect for werkzeug (see [here](https://github.com/python/typeshed/blob/master/stubs/Werkzeug/werkzeug/wrappers.pyi#L147)). According to [this](https://flask.palletsprojects.com/en/1.1.x/api/#flask.Response.set_cookie) and [this](https://werkzeug.palletsprojects.com/en/1.0.x/wrappers/#werkzeug.wrappers.BaseResponse.set_cookie) the `expires` parameter can be both a `datetime` and a `int`, however typeshed only allows ints.

**Comment by 01-vyom** [comment]
I have made a PR to solve this issue.
