### ISSUE TITLE
Using a pathlib path with __truediv__ returns  a purepath instead of a path

### ISSUE THREAD

**Issue by thomascellerier** [python/typeshed#506]
This is problematic, let me show with some sample code:
```Python
$ cat pathproblems.py 
from pathlib import Path

def pathproblems(a: Path) -> bool:
    return (a / 'hello').exists()

if __name__ == '__main__':
    print(pathproblems(Path('/')))
```

And the output from mypy:
```bash
$ mypy pathproblems.py 
pathproblems.py: note: In function "pathproblems":
pathproblems.py:4: error: "PurePath" has no attribute "exists"
```

Here is the signature for PurePath.__truediv__:
```Python
def __truediv__(self, key: Union[str, PurePath]) -> PurePath: ...
```

The solution would be for __truediv__ to return the type of self isntead of PurePath, is that possible to express using mypy? In my imagination:

```Python
def __truediv__(self, key: Union[str, PurePath]) -> typing.typeof(self):
```

I've had this issue several times when subclassing where I lose access to my subclass's methods whenever i chain methods from the parent class along the way.

**Comment by JukkaL** [comment]
This seems to work for me using the latest typeshed. Adding another method stub to the subclass with a different return type works. The fix was here: https://github.com/python/typeshed/pull/483

**Comment by thomascellerier** [comment]
I see, 3 days ago. I guess this hasn't been released yet to pypi. Thanks for the quick response.
