### ISSUE TITLE
typing_extensions-stubs shadowing typing_extensions

### ISSUE THREAD

**Issue by chdsbd** [python/typeshed#5065]
I tried installing `types-redis`, but when I ran `mypy` I encountered an error:

```
❯ .venv/bin/mypy main.py 
mypy: ".venv/lib/python3.7/site-packages/typing_extensions-stubs/__init__.pyi" shadows library module "typing_extensions"
note: A user-defined top-level module with name "typing_extensions" is not supported
```

Here's an example repository that reproduces this issue: https://github.com/chdsbd/mypy-types-issue/blob/main/main.py

I'm not sure, but I think we want make `typing-extensions` a peer dependency instead of an installed package: https://github.com/python/typeshed/blob/cb90edabd99d0761a61d3dc04cb89da398b4b89f/stubs/redis/METADATA.toml#L3

**Comment by srittau** [comment]
I wonder whether the best approach would be to have typing-extensions ship its own stubs.

**Comment by traviscook21** [comment]
also experiencing this trying to install `types-Flask`.  Not entirely sure what a workaround would look like.

**Comment by chdsbd** [comment]
I think we should be requiring `typing-extensions` instead of `types-typing-extensions`. Mypy and Pyright have internal types for `typing-extension`, so we probably don't need to add the type stubs.

I tested modifying the wheel for `types-redis` to use `typing-extensions` instead of `types-typing-extensions` and mypy stopped complaining.

**Comment by chdsbd** [comment]
I opened #5109 and it seems to fix the issue when I tested with a wheel made by https://github.com/typeshed-internal/stub_uploader

**Comment by hauntsaninja** [comment]
Fixed by https://github.com/python/typeshed/pull/5233

**Comment by chdsbd** [comment]
Thanks @hauntsaninja! I just installed `types-redis` without issue.
