### ISSUE TITLE
mypy cannot find stubs on more recent checkout

### ISSUE THREAD

**Issue by limburgher** [python/typeshed#5071]
I'm the Fedora maintainer for mypy and typeshed. I recently updated our snapshot from d82d339 to bf583da2, and at that point mypy could no longer find the stubs. I've reverted for now, but I'm wondering what might have changed to cause this, and how I can work about it.

**Comment by srittau** [comment]
@limburgher The layout of typeshed was completely reshuffled recently. See #2491 for details. The latest released mypy versions do not yet support the reshuffling, but mypy HEAD does. I would assume that this is the reason for your problems.

**Comment by limburgher** [comment]
Ah, thank you!
mypy HEAD requires git submodule use, which we can't do in RPMs. DO you know when mypy might cut a release that supports the reshuffle?

**Comment by srittau** [comment]
Maybe @ilevkivskyi or @JukkaL can help with that.

**Comment by ilevkivskyi** [comment]
We don't have an exact date yet, but most likely in the next few weeks.

**Comment by limburgher** [comment]
Thanks, I'll watch for it!

**Comment by hauntsaninja** [comment]
You can follow https://github.com/python/mypy/issues/10116 Also I believe mypy HEAD no longer uses a submodule.

**Comment by srittau** [comment]
Closing this here as there is nothing actionable for typeshed to be done.
