### ISSUE TITLE
Fix __exit__ annotation

### ISSUE THREAD

**Issue by decaz** [python/typeshed#5073]
Currently annotated `__exit__` methods have `None` return type. It's incorrect and should be changed to `Optional[bool]`. From [here](https://docs.python.org/3/reference/datamodel.html#object.__exit__):

> If an exception is supplied, and the method wishes to suppress the exception (i.e., prevent it from being propagated), it should return a true value. Otherwise, the exception will be processed normally upon exit from this method.

I think that ideally all `__exit__` methods should be annotated as follows:
```python
def __exit__(
    self, exc_type: Optional[Type[BaseException]], exc: Optional[BaseException], traceback: Optional[TracebackType]
) -> Optional[bool]: ...
```

**Comment by JelleZijlstra** [comment]
Can you be more specific? We shouldn't change all `__exit__` methods, because some really never return a bool, and mypy uses the `None` annotation for reachability analysis.

**Comment by decaz** [comment]
> some really never return a bool

That's why `bool` is `Optional`.

**Comment by JelleZijlstra** [comment]
Right. The issue is that this return type annotation is often too broad, since many (most?) context managers in fact always return None. This is discussed in https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions (search for "exit").

**Comment by JelleZijlstra** [comment]
Though looking at that again now, seems like we made `Optional[bool]` mean the same as `None` (does not suppress the exception). I still don't see much value in changing typeshed annotations to not use `-> None`.

**Comment by decaz** [comment]
Docs on `object.__exit__` and `contextmanager.__exit__` are pretty clear about types this method can return. Why can't we just follow them?

The value in changing is the following: for instance if you inherit some annotated class and return boolean within `__exit__` method that have `None` return type then you'd run into incompatibility of return type. `FlaskClient.__exit__` as an [example](https://github.com/python/typeshed/blob/master/stubs/Flask/flask/testing.pyi#L18).

**Comment by JelleZijlstra** [comment]
It's true that `__exit__` methods can return bool, but that doesn't mean they all do. It's useful to annotate them as `None` to indicate that the context manager never swallows the exception.

But you are right about subclasses; we could change the annotations in individual cases to accommodate subclasses that use a different return type. We can consider that in individual PRs.

**Comment by decaz** [comment]
If I understood you correctly you mean making return type of `__exit__` in base classes more broad within individual PRs. But isn't it contradicts to annotation them as `None` in base classes "to indicate that the context manager never swallows the exception"? Because broad return type may be needed only in private cases.

**Comment by srittau** [comment]
I agree with @JelleZijlstra. We tend to annotate return types narrowly with what the actual implementation returns. In the case of `__exit__()` this is very often `None`. When a class is intended to be sub-classed and it makes sense for the sub-class to override `__exit__()` we can consider using a more broad return type. For other cases there is `# type: ignore`.
