### ISSUE TITLE
numbers.Number vs. implementations

### ISSUE THREAD

**Issue by crusaderky** [python/typeshed#5074]
I need to define a variable to be Union[int, float, numpy.float64, numpy.float32, numpy.int64, numpy.int32, ...].
```python
from numbers import Number
import numpy

a: Number = 1
b: Number = 1.0
c: Number = numpy.int64(1)
```
mypy 0.812:
```
4: error: Incompatible types in assignment (expression has type "int", variable has type "Number")
5: error: Incompatible types in assignment (expression has type "float", variable has type "Number")
6: error: Incompatible types in assignment (expression has type "signedinteger[_64Bit]", variable has type "Number")
```
for all of the above, ``isinstance(..., Number)`` returns True at runtime as expected.

Unsure if the match vs. int/float can be fixed in typeshed or if it has to be hardcoded in mypy?
Unsure if the numpy part also requires to be addressed in the numpy code itself.

**Comment by adamchainz** [comment]
I have a related issue.

This code:

```python
from numbers import Integral

x: int = 1

if isinstance(x, Integral):
    print("It's integral")
```

At runtime the `isinstance` check is happy:

```
$ python example.py
It's integral
```

But `mypy --warn-unreachable` complains because it doesn't believe `int` and `Integral` could be combined:

```
$ mypy --warn-unreachable example.py
example.py:5: error: Subclass of "int" and "Integral" cannot exist: would have incompatible method signatures
example.py:6: error: Statement is unreachable
Found 2 errors in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
The `numbers` module has always been problematic when it comes to type annotations. As the concrete types `int`, `float`, etc. don't inherit from the ABCs in `numbers`, and there is either special handling in Python for them, or they use `register()`, there is nothing typeshed can do, although this could be special-cased by type checkers.

**Comment by adamchainz** [comment]
Well fair enough :)
