### ISSUE TITLE
Argument 1 to "ensure_future" has incompatible type "CoroutineType"

### ISSUE THREAD

**Issue by wsanchez** [python/typeshed#5082]
With this code:

```python
from asyncio import ensure_future
from types import CoroutineType

from twisted.internet.defer import Deferred

def futureCoroutineAsDeferred(f: CoroutineType) -> Deferred:
    return Deferred.fromFuture(ensure_future(f))
```

I get this error from Mypy:

```console
error: Argument 1 to "ensure_future" has incompatible type
"CoroutineType"; expected "Union[Future[<nothing>], Generator[Any, None, <nothing>], Awaitable[<nothing>]]" 
[arg-type]
```

This surprises me, since `ensure_future` is accepts a (Future-yielding) coroutine as one of its three use cases (`Future`-like, coroutine, and awaitable).

`Python==3.9.1`
`mypy==0.812`
`mypy-extensions==0.4.3`

**Comment by srittau** [comment]
`CoroutineType` is not intended to be used as a type annotation, similar to `FunctionType`. The following will not work either:

```python
from types import FunctionType

def foo(f: FunctionType) -> None: pass
def bar() -> None: pass
foo(bar)  # Argument 1 to "foo" has incompatible type "Callable[[], None]"; expected "FunctionType"
```

Maybe it would make sense to extend the functionality of `FunctionType` and `CoroutineType` and make them generic, similar to how `Callable` works. But this decision is out of scope for typeshed and should probably be discussed on typing-sig.

That said, for now the correct way to make this work is:

```python
from collections.abc import Coroutine  # or from typing import Coroutine
from typing import Any

def futureCoroutineAsDeferred(f: Coroutine[Any, Any, Any]) -> Deferred:
    return Deferred.fromFuture(ensure_future(f))
```

**Comment by wsanchez** [comment]
aha, ok thanks.

**Comment by wsanchez** [comment]
FWIW I do think that "don't use types as type hints" is confusing.

I wonder if the same "is not intended to be used as a type annotation" applies to `MethodType`, which is another one I've used in the past, and I'm not aware of an alternative.
