### ISSUE TITLE
Why aren't the standard library type annotations just in the standard library?

### ISSUE THREAD

**Issue by Timmmm** [python/typeshed#5085]
Why doesn't the Python 3.9 standard library just have type annotations in its code directly rather than keeping them here?

I couldn't find anything about it on Google. It would be good to add an explanation to the readme.

**Comment by srittau** [comment]
It's my personal goal to eventually add type annotations to cpython directly. For a long time the annotations were incomplete (and still partly are) and buggy. Type annotations are still a fast moving target with new features being added constantly, so the fairly slow moving stdlib isn't the best place for them at this point.

**Comment by Akuli** [comment]
Please don't move the type annotations to cpython. Getting even a tiny bugfix contributing to cpython is difficult:
- You need to sign a CLA (including writing your street address onto it, which is just ridiculous).
- You need to file a bug on bugs.python.org.
- The pull requests and issues need to be written following precise templates very exactly. Make sure to start your issue title with `bpo-nnnnn`, where `nnnnn` is the bugs.python.org number.
- You need to read long walls of text describing this process.
- I'm sure I forgot some other boilerplate?

On the other hand, contributing stub fixes to typeshed involves no boilerplate: you can just make a pull request on github, and that's it. Of course, typeshed has contributing guidelines too, but much of them are more or less common sense.

**Comment by Timmmm** [comment]
That does sound very annoying. But it still feels like standard library type annotations belong in the standard library eventually. That way people navigating the code see them, tools can more easily take advantage of them, they'll stay in sync and new code is more likely to get type annotations.

But I definitely agree that process sounds like it is designed to put people off contributing.
