### ISSUE TITLE
dict copying

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5089]
This example causes an error because of invariance:

```
from typing import Dict
a = {'b': 'c'}
b: Dict[str, object] = a.copy()
```

However, invariance doesn't matter here, because a copy is being made. Ideally this would not be an error.

**Comment by JelleZijlstra** [comment]
I'm not sure this is something we can fix in typeshed.

**Comment by Akuli** [comment]
Looking at mypy primer output in #5091, this doesn't seem to be a commonly occurring problem.

**Comment by srittau** [comment]
@Akuli Can this be closed or do we have an idea how to fix this?

**Comment by Akuli** [comment]
Maybe this could be labeled "inexpressible". To me, the problem seems to be that there's no way to express "invariance rules don't matter because we are creating a copy".

**Comment by srittau** [comment]
I am going to close this for now, as is standard for issues labeled "inexpressible".
