### ISSUE TITLE
Wrong return type for pkg_resources.parse_version

### ISSUE THREAD

**Issue by HarrySky** [python/typeshed#5093]
Right now type is defined as `Tuple[str, ...]` :
https://github.com/python/typeshed/blob/16ae4c61201cd8b96b8b22cdfb2ab9e89ba5bcf2/stubs/pkg_resources/pkg_resources/__init__.pyi#L257

But in reality it returns either `packaging.version.Version` or `packaging.version.LegacyVersion` (tested on Python 2.7 and Python 3.x)

How to test in Python REPL:
```python
>>> from pkg_resources import parse_version
>>> parse_version("5.0.0")
<Version('5.0.0')>
```

Maybe I am missing something? Ready to create a PR fixing this type annotation

**Comment by JelleZijlstra** [comment]
Confirmed with the implementation too, feel free to submit a PR!

**Comment by HarrySky** [comment]
@JelleZijlstra I created PR #5098 , but I have one problem I described there, need advice, if you have some time - give it a look :smile:
