### ISSUE TITLE
Missing attribute "policy" for email.message.Message

### ISSUE THREAD

**Issue by domdfcoding** [python/typeshed#5094]
Although it it not explicitly documented in [the docs](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage), the attribute is mentioned in the documentation for the [`__str__` method](https://docs.python.org/3/library/email.message.html#email.message.EmailMessage.__str__).

The stubs used to include this attribute, but it was removed in #207. I couldn't find any discussion as to why it was removed.

**Comment by JelleZijlstra** [comment]
It was probably removed because it is undocumented. Our policy is now to add undocumented (or semi-documented) attributes if users request them, so feel free to submit a PR to add it back.
