### ISSUE TITLE
Incorrect return type for asyncio.wait? 

### ISSUE THREAD

**Issue by cassiobotaro** [python/typeshed#5095]
The stub of the wait function has a set of futures in return, but when the type passed is a Task, and then we use the return through the task interface and not futures, `mypy` accuses a type error.

```python
import asyncio


async def async_function() -> None:
    await asyncio.sleep(1)
    print("done")


async def main() -> None:
    completed, _ = await asyncio.wait(
        [asyncio.create_task(async_function()) for _ in range(5)]
    )
    for task in completed:
        # Future[None] has no attribute "get_name"
        print(task.get_name())
 

asyncio.run(main())
```
How can I handle it properly? Is there a legal way to do it without overloading typeshed?

**Comment by srittau** [comment]
The implementation of `wait()` will call `ensure_future()` on the elements of `fs`. We could use `@overload`s for `wait()` to improve the return type. I will submit a PR to improve the return type of `ensure_future()` later today, which has a similar issue.

**Comment by cassiobotaro** [comment]
@srittau I will submit a PR based on your, ok?

**Comment by srittau** [comment]
@cassiobotaro Please go ahead!
