### ISSUE TITLE
Use protocol for GzipFile fileobj parameter

### ISSUE THREAD

**Issue by jlost** [python/typeshed#5099]
```
sftp_client = paramiko.SFTPClient.from_transport(...)
out_gz = sftp_client.file(filename)
out = gzip.GzipFile(fileobj=out_gz, filename=filename)
                               ^
Argument of type "SFTPFile" cannot be assigned to parameter "fileobj" of type "IO[bytes] | None" in function "__init__"
  Type "SFTPFile" cannot be assigned to type "IO[bytes] | None"
    "SFTPFile" is incompatible with "IO[bytes]"
    Cannot assign to "None"
```

It seems like it should be compatible. Should I cast here? Any thoughts?

**Comment by srittau** [comment]
`GzipFile` is still using `IO` as argument type, which is discouraged. We prefer custom protocols for argument types, and that would hopefully fix the problem above. Using `cast()` or `# type: ignore` is probably the best "quick" solution, until we land a proper fix in typeshed.
