### ISSUE TITLE
Make Mapping covariant

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#510]
I think that `Mapping[KT, VT]` should be covariant in both `KT` and `VT`. The argument for this is that it doesn't have any mutation operations. Mypy might complain (or may eventually start to complain) about having covariant type variables in argument types but in this case it's okay so we can probably just `# type: ignore` them.

(It wouldn't be safe since somebody can write a `get` method that actually mutates the mapping, but consenting adults...)

**Comment by gvanrossum** [comment]
Indeed mypy complains if I make this change, "Cannot use a covariant type variable as a parameter". But adding a `# type: ignore` works, so I'll do that.
