### ISSUE TITLE
Unexpected keyword argument "no_args_is_help" for "command" using click

### ISSUE THREAD

**Issue by Pagliacii** [python/typeshed#5113]
I am using [click](https://github.com/pallets/click) to parse command-line arguments. But when running `mypy test.py`, it complains an unexpected keyword argument `no_args_is_help`.

Codes below are in the "test.py" file:

```python
#!/usr/bin/env python3
# _*_ coding: utf-8 _*_

import click


@click.command("hello", no_args_is_help=True)
def hello():
    click.echo("Hello")


if __name__ == "__main__":
    hello(prog_name="hello")

```

And I found that the stubs file of `click.decorators.command` wasn't contains `no_args_is_help`.

https://github.com/python/typeshed/blob/30fc2b8cd0420a662615e2a2b6dd28d091618239/stubs/click/click/decorators.pyi#L21-L33

This is the [documentation](https://click.palletsprojects.com/en/7.x/api/#click.Command) of `no_args_is_help`.

**Comment by srittau** [comment]
Also missing from `Command.__init__()`. PR welcome!

**Comment by Pagliacii** [comment]
Ok, I will try it.
