### ISSUE TITLE
Wrong signature of "importlib.util.spec_from_loader" and "spec_from_file_location"

### ISSUE THREAD

**Issue by KmolYuan** [python/typeshed#5117]
`spec_from_loader` and `spec_from_file_location` should return `Optional[importlib.machinery.ModuleSpec]`, just like `find_spec` does.

Currently, MyPy complains that my none check is unreachable.

**Comment by srittau** [comment]
If I read the implementation correctly, the only case where these functions return `None` is if a file is being loaded and the suffix of the file is unknown. I fear that changing the functions to return `Optional` could make the usual case (loading *.py files) more cumbersome, but I have no strong feelings about this.

**Comment by 01-vyom** [comment]
Created a PR @srittau
