### ISSUE TITLE
shutil.copyfileobj constrained to AnyStr

### ISSUE THREAD

**Issue by ehandal** [python/typeshed#5119]
The current stub for copyfileobj: `def copyfileobj(fsrc: SupportsRead[AnyStr], fdst: SupportsWrite[AnyStr], length: int = ...) -> None: ...`

The fact that the stub uses AnyStr causes issues with code like this:
```
with open('read', 'rb') as fr, open('write', 'wb') as fw:
    shutil.copyfileobj(fr, fw)
```
For example, pyright reports: `Type "ReadableBuffer" is incompatible with constrained type "AnyStr"`

Since copyfileobj only cares that the return type of fsrc.read can be passed as input to fdst.write, this should be loosened to allow SupportsRead[T] and SupportsWrite[T] (or at least to allow bytes-like objects through).

**Comment by JelleZijlstra** [comment]
That sounds like a bug to pyrite to me: the return type to `open` with a binary mode should be assignable to `SupportsRead[bytes]`. I'm not sure where the ReadableBuffer comes from; `open` doesn't return that.

**Comment by JelleZijlstra** [comment]
Looking at it some more, the ReadableBuffer is the argument type to `FileIO.write`. ReadableBuffer is a union that contains `bytes`, so it seems like it should be compatible with `AnyStr`.

**Comment by ehandal** [comment]
Sorry, I accidentally left out part of the pyright error:

```
error: Argument of type "BufferedWriter" cannot be assigned to parameter "fdst" of type "SupportsWrite[AnyStr@copyfileobj]" in function "copyfileobj"
    TypeVar "_T_contra@SupportsWrite" is contravariant
      Type "ReadableBuffer" is incompatible with constrained type "AnyStr" (reportGeneralTypeIssues)
```
I wasn't sure if this was a pyright or typeshed bug, so I'd be fine creating an issue in pyright for this error.

That said, it still seems like the typeshed stub isn't quite right here. `shutil.copyfileobj` just cares that `fdst.write(fsrc.read(length))` works, so typeshed is artificially limiting what types are accepted here by using AnyStr here.

**Comment by ehandal** [comment]
Resolved in pyright: https://github.com/microsoft/pyright/issues/1633
