### ISSUE TITLE
Adding TypedDict to _Body Type

### ISSUE THREAD

**Issue by JingLi1998** [python/typeshed#5122]
Hey, this is my first time ever raising an issue on an open-source project!

Was wondering what the implications of adding the Python `TypedDict` to the `_Body` Union type. 

This is because the `Dict[Text, Any]` type is incompatible with `TypedDict`. (This is further discussed in https://www.python.org/dev/peps/pep-0589/#id20)

So far, editing `_Body` to be:
```
_Body = Union[Text, ByteString, Dict[Text, Any], Response, _WSGICallable, TypedDict
```
Has resolved the issue, and `mypy` raises no errors. Should this be something that should be included as part of the `flask-stubs` module?

**Comment by JelleZijlstra** [comment]
I don't think TypedDict by itself is valid as a type; do type checkers accept that?

Maybe we can use Mapping instead, unless this dict is expected to be mutated.

**Comment by JingLi1998** [comment]
Hey thanks for getting back to me

As of Python 3.8 `TypedDict` is a valid type https://www.python.org/dev/peps/pep-0589/

Additionally it is backwards compatible via `typing-extensions`

Type checkers such as `mypy` do check for it as well. At runtime it compiles down to a normal `dict` object.

**Comment by JingLi1998** [comment]
Ahh wait I see what you mean about whether it is valid on it's own.  As far as I know, including TypedDict works because all user defined classes must inherit TypedDict, so they will always be structurally compatible. (I'm not too well-versed with Python's typing system so please correct me if I'm wrong)

Neither Mapping nor Dict types are compatible with TypedDict. So the only solution is the extend the `_Body` Union with the `TypedDict`

**Comment by JelleZijlstra** [comment]
The trouble with that is that TypedDict is not a type, it's a special form, even if you use class-like syntax to create one. I just confirmed that in mypy: https://mypy-play.net/?mypy=latest&python=3.9&gist=a39c2bc656ca807db76fd7989529f2f0. There's no way to say "any TypedDict" in the type system.

Maybe we could reconsider the rule that makes TypedDict not compatible with `Mapping` or `Dict[str, Any]`. I suppose that could lead to some soundness issues, though.

**Comment by JingLi1998** [comment]
Hmm that's interesting, I wasn't receiving that error in my IDE. I'll trust your judgment in this case, seems like there's not much else that can be done.

Thanks for taking to the time to look at this issue tho!

**Comment by srittau** [comment]
Closing as the flask stubs will be removed in a few months.
