### ISSUE TITLE
"addresses" constructor argument to email.headerregistry.Group has overly restrictive type

### ISSUE THREAD

**Issue by jwodder** [python/typeshed#5123]
Currently, typeshed annotates the constructor for `email.headerregisty.Group` as follows:

https://github.com/python/typeshed/blob/e380432825d92acf9ca6a0b011942705cc47ec52/stdlib/email/headerregistry.pyi#L89

However, [if we look at the implementation, going all the way back to Python 3.6.0](https://github.com/python/cpython/blob/v3.6.0/Lib/email/headerregistry.py#L125), we see:

```python
self._addresses = tuple(addresses) if addresses else tuple()
```

Thus, the `addresses` argument can actually be any iterable of `Address` objects, not just a tuple.  I thereby request that the annotation for `addresses` be changed to `Optional[Iterable[Address]]`.

**Comment by srittau** [comment]
Sounds reasonable, PR welcome!

**Comment by jwodder** [comment]
@srittau PR submitted: #5124
