### ISSUE TITLE
first release

### ISSUE THREAD

**Issue by kloczek** [python/typeshed#5136]
Looks like typeshed have not been so far released.
Is it possible to tag first version?
Versioning is needed to package typeshed python module.

If may I ask to use exact tagging pattern of the version string which should consist only out of numbers and dots.

**Comment by srittau** [comment]
Typeshed is not released in the traditional sense and having a version number for typeshed would make no sense. Previously, it was packaged with type checkers that often used a particular point that was suitable to them. This is still the case with stdlib and a few type checkers that decided to ship all of typeshed. With modular typeshed, individual packages are created and released whenever there are changes to the source. They are versioned independently and automatically.
