### ISSUE TITLE
singledispatch: error when calling registered function directly

### ISSUE THREAD

**Issue by joelberkeley** [python/typeshed#5152]
If I register a function as a `singledispatch` case by using a decorator
```python
@singledispatch
def foo(o: object) -> None:
    ...

@foo.register
def _float(o: float) -> None:
    ...
```
and then call the function directly
```python
_float(1.0)
```
mypy complains with

> error: Argument 1 to "_float" has incompatible type "float"; expected "Callable[..., object]"

However, I don't get this error if I register the function without using a decorator
```python
@singledispatch
def foo(o: object) -> None:
    ...

def _float(o: float) -> None:
    ...

foo.register(float, _float)
```
I'd expect there to be no error in either case

I'm using mypy 0.800

**Comment by hauntsaninja** [comment]
I fixed this a month or two ago in https://github.com/python/typeshed/pull/4942

**Comment by joelberkeley** [comment]
that was fast ;)
