### ISSUE TITLE
Missing type annotations for undocumented attributes in logging.__init__.py

### ISSUE THREAD

**Issue by dod-wdwilcox** [python/typeshed#5159]
In python standard library ```logging```, there are two missing attribute type stubs: ```Logging.root``` and ```Logging.manager``` are defined at the bottom of the file.

https://github.com/python/cpython/blob/master/Lib/logging/__init__.py#L1925

I need these stub hints to access logging.Logger.manager.dictValues without needing to smother MyPy with an ignore.

**Comment by srittau** [comment]
PRs always welcome! If these attributes are not documented, they should be marked with a `# undocumented` comment.

**Comment by dod-wdwilcox** [comment]
@srittau Also, I'm seeing the entire ```Manager``` class is undocumented and unavailable.  I'm working on the PR now.
