### ISSUE TITLE
Allow path-like objects for POSIX subprocess env

### ISSUE THREAD

**Issue by ehandal** [python/typeshed#5181]
Code like this works fine on POSIX:
```
import subprocess
from pathlib import Path
subprocess.call('env', env={'HOME': Path.home()})
```
However, typeshed allows only str and bytes for the env argument: https://github.com/python/typeshed/blob/master/stdlib/subprocess.pyi#L29

**Comment by hauntsaninja** [comment]
PR welcome! :-)
