### ISSUE TITLE
`resource.struct_rusage` stub is named `resource._RUsage` for some reason

### ISSUE THREAD

**Issue by rijenkii** [python/typeshed#5183]
The first occurrence of the name `resoruce._RUsage` that I was able to find was commited into `python/mypy` stubs on [21 Aug 2015](https://github.com/python/mypy/commit/6282eb0a04dc254c3531a1dbe482b8633dad09ec#diff-de44ba7f37f2aedfcdd858a825291f635d980726e807a278e66ca6d63070e880R22). It was later copied over to this repo on [30 Sep 2015](https://github.com/python/typeshed/commit/337abed05a35f0c5b67c02d42bca0af1e2adc76e#diff-a5943a811cac3726f5cb299498819dd9412dbb6d3ef392444c690b4f2861a426R22) and then copied to the Python 3 stubs on [22 Aug 2017](https://github.com/python/typeshed/commit/485c232409533982369e5d56493540d00519a2b9#diff-5a0da7d8759b759be9d2b61c2ef947cf8a246376492727e75d66f56a6ce9edf6R28).

Type `resource.struct_rusage` that aformentioned stub describes has been added to the Python source code on [9 Apr 2002](https://github.com/python/cpython/commit/688357e035d9cb291c834d14ac5acc03905b1665#diff-510472560baed5d8506ea0cde42fbb06c286a90dc85ce3e6172cb088de5d5ad8R47), and has never been named `_RUsage`.

**Comment by rijenkii** [comment]
Because of this, files that use `resource.struct_rusage` get yelled at by `mypy`:
```
$  cat test2.py
from resource import struct_rusage
$  python test2.py
$  mypy test2.py
test2.py:1: error: Module 'resource' has no attribute 'struct_rusage'
Found 1 error in 1 file (checked 1 source file)
```
And files that use `resource._RUsage` get yelled at by `python`:
```
$  cat test1.py
from resource import _RUsage
$  mypy test1.py
Success: no issues found in 1 source file
$  python test1.py
Traceback (most recent call last):
  File "/tmp/test1.py", line 1, in <module>
    from resource import _RUsage
ImportError: cannot import name '_RUsage' from 'resource' (/usr/lib/python3.9/lib-dynload/resource.cpython-39-x86_64-linux-gnu.so)
```

**Comment by JelleZijlstra** [comment]
Feel free to submit a PR.

There's an additional complication: our stub claims that it is a NamedTuple, but in fact it's a struct sequence object. The main observable difference is that you construct them by passing a tuple, not by passing each field as a separate argument. For some similar classes in `os`, we have adjusted the stubs to be classes with explicit stubs for the constructor: https://github.com/python/typeshed/blob/master/stdlib/os/__init__.pyi#L230.

**Comment by rijenkii** [comment]
I have submitted #5184
