### ISSUE TITLE
Test Python's stdlib regularily

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5191]
We should test Python's standard library with the latest mypy/typeshed combination on a regular basis. Maybe once after each mypy release would be a good idea. This could be done with GitHub Actions and a cron trigger that checks for a new mypy release since the last run.

**Comment by srittau** [comment]
See #2149 for the last manual run.

**Comment by JelleZijlstra** [comment]
Would this add much over mypy-primer, beyond giving us more code to check?

**Comment by srittau** [comment]
I guess it's just more code to check, although it's code that's highly relevant to our stubs.

**Comment by JelleZijlstra** [comment]
I think stubtest basically solves this. Actually typechecking the standard library would be much more difficult and probably better left to a type checker.
