### ISSUE TITLE
wrong return type in xxhash intdigest and hexdigest ?

### ISSUE THREAD

**Issue by PASUNX** [python/typeshed#5200]
```python
from xxhash import xxh32_hexdigest, xxh32_intdigest

result = xxh32_hexdigest(b"input") # (variable) result: bytes
print(type(result)) # <class 'str'>

result = xxh32_intdigest(b"input") # (variable) result: bytes
print(type(result)) # <class 'int'>
```

**Comment by Akuli** [comment]
`hexdigest` [seems](https://github.com/ifduyue/python-xxhash/blob/01ff744290089a6fa5c280dd25c3173d5e5ffb2f/src/_xxhash.c#L50-L55) to return `bytes` on Python 2 and `str` on Python 3, but `intdigest` returns `int` on both.

**Comment by ayushi-get** [comment]
I would love to contribute . May i

**Comment by Akuli** [comment]
Yes!

**Comment by woodsman1** [comment]
hello @Akuli,  I am getting all checks passed on my forked repository but when I am trying to make a pull request, I am getting checks fail each time. Please help me I am a complete beginner.

**Comment by Akuli** [comment]
@woodsman1 Reopen one of your closed pull requests. Don't close it. We can fix the failing checks without making a new pull request.

**Comment by woodsman1** [comment]
I reopened the pull request
