### ISSUE TITLE
Incorrect annotation for smtpd.SMTPServer.process_message

### ISSUE THREAD

**Issue by sbp** [python/typeshed#5202]
The `data` argument of `smtpd.SMTPServer.process_message` is [annotated as `str`](https://github.com/python/typeshed/blob/master/stdlib/smtpd.pyi#L82) in typeshed, but its value [can be a `bytes` instance](https://docs.python.org/3/library/smtpd.html?highlight=smtpd#smtpd.SMTPServer.process_message) if `decode_data` is set to `False` in the `smtpd.SMTPServer` constructor:

> If the *decode_data* constructor keyword is set to `True`, the *data* argument will be a unicode string. If it is set to `False`, it will be a bytes object.

Causing mypy, for example, to wrongly complain about a violation of the Liskov substitution principle.

**Comment by srittau** [comment]
For simplicity's sake, we should just annotate it as `Union[str, bytes]`. PR welcome!
