### ISSUE TITLE
Wrong signature in typeshed/stubs/protobuf/google/protobuf/json_format.pyi 

### ISSUE THREAD

**Issue by heroesm** [python/typeshed#5225]
The argument `descriptor_pool` is missing in json_format.pyi .

For example:

https://github.com/protocolbuffers/protobuf/blob/master/python/google/protobuf/json_format.py#L437

```
def ParseDict(js_dict,
              message,
              ignore_unknown_fields=False,
              descriptor_pool=None):
```

https://github.com/python/typeshed/blob/16ae4c61201cd8b96b8b22cdfb2ab9e89ba5bcf2/stubs/protobuf/google/protobuf/json_format.pyi#L25

```
def Parse(text: Union[bytes, Text], message: _MessageT, ignore_unknown_fields: bool = ...) -> _MessageT: ...
```

**Comment by srittau** [comment]
Indeed, PR welcome.

**Comment by heroesm** [comment]
> Indeed, PR welcome.

PR created.
