### ISSUE TITLE
Allow heterogeneous concatenation for list

### ISSUE THREAD

**Issue by tamuhey** [python/typeshed#5234]
From https://github.com/microsoft/pyright/issues/1777

`[0] + ["a"]` is not allowed in any type checker (e.g. `pyright`, `mypy`) because the type annotation of  `list.__add__` is defined as follows:

```python
class list(MutableSequence[_T], Generic[_T]):
    ...
    def __add__(self, x: List[_T]) -> List[_T]: ...
```

This annotation prohibits heterogeneous concatenation, although it is actually allowed in runtime.
I think the annotation should be as follows to solve this problem:

```python
class list(MutableSequence[_T], Generic[_T]):
    ...
    def __add__(self, x: List[_S]) -> List[Union[_T, _S]]: ...
```

**Comment by JelleZijlstra** [comment]
See #3183 for some past attempts.

**Comment by tamuhey** [comment]
Also related: https://github.com/python/typeshed/issues/2383
