### ISSUE TITLE
tkinter.Canvas.moveto doesn't accept numbers

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5244]
https://github.com/python/typeshed/blob/b91b0615bf69a8c19e70c747aa3794d01e4c1c2c/stdlib/tkinter/__init__.pyi#L1300

Maybe should be `Union[Literal[""], float]` instead of `str`? Tk manual says "xPos  and  yPos               may be the empty string, in which case the corresponding coordinate will be unchanged."

**Comment by srittau** [comment]
Sounds like it's worth trying.
