### ISSUE TITLE
Add license information to package metadata

### ISSUE THREAD

**Issue by RobbeSneyders** [python/typeshed#5263]
The typeshed packages pushed to Pypi don't have any license information in their metadata ([types-pyyaml example](https://pypi.org/pypi/types-PyYAML/json)).

We automatically check the licenses of all our dependencies, and currently need to add an exception for every typeshed package we use. It would be great if the license information could be added to the package metadata instead.

The fix would be to add the following to the base `setup.cfg` file.
```
[metadata]
license = Apache-2.0 license
classifier =
    License :: OSI Approved :: Apache Software License
```

I looked for the relevant code to submit a PR, but it seems like it's not a part of this repository. If I missed it, or it is available somewhere else, please point me to it and I'll happily submit a PR.

**Comment by Akuli** [comment]
Seems like it should go to [empty_package/setup.py in typeshed-internal/stub_uploader](https://github.com/typeshed-internal/stub_uploader/blob/main/data/empty_package/setup.py).

**Comment by JelleZijlstra** [comment]
That's right.

Note that typeshed as a whole is partially licensed under Apache and partly under the MIT License according to https://github.com/python/typeshed/blob/master/LICENSE. I don't have context on why that is, but perhaps @JukkaL remembers. For simplicity in setup.py it'd be better to have only one license.

**Comment by RobbeSneyders** [comment]
Thanks for the info! I submitted a PR to that repo.

**Comment by srittau** [comment]
The MIT license was added in 337abed05a35f0c5b67c02d42bca0af1e2adc76e by @matthiaskramm. Maybe Matthias has some insights? But if in doubt, we need to dual-license the stubs themselves.

**Comment by JukkaL** [comment]
I recognized some of the stubs added in that commit as coming from mypy. So my hypothesis above seems right. 

The individual authors of those stubs should be visible in the mypy commit history, if we want to ask all the authors if they are fine with changing the license to Apache. Unfortunately we lost the commit history and author attribution as they were merged to typeshed.
