### ISSUE TITLE
sys.meta_path has incorrect type

### ISSUE THREAD

**Issue by mniip** [python/typeshed#5276]
The docs aren't super clear about this, but in practice the list actually contains classes (not objects), that implement `MetaPathFinder`, meaning `meta_path : List[Type[MetaPathFinder]]` instead of `List[MetaPathFinder]`.

**Comment by Akuli** [comment]
I think objects in `sys.meta_path` don't have to be classes, so `Type[MetaPathFinder]` isn't adequate either. Maybe we should use a Protocol? That way we could say "the objects in `sys.meta_path` have these methods, whatever type they actually have".
