### ISSUE TITLE
Drop mypy self check?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5303]
A continuation from #4333: Now that mypy_primer is integrated into CI, I propose to drop the mypy self check. We already check the mypy code base with primer anyway, so we will find potential problems with that. Advantages:

* Less maintenance needed.
* Builds are a bit more robust.
* A bit easier to understand our various tests.
* Less CI minutes (and computing power) used.

**Comment by hauntsaninja** [comment]
I like having the self check. In practice I find it to be a low maintenance and high precision check. mypy primer isn't fully reliable / it's not a red cross, so it's easy to merge past.

**Comment by Akuli** [comment]
Does someone remember a pull request where the self-check helped to find a problem but other checks didn't?

**Comment by srittau** [comment]
I don't. :)

**Comment by JelleZijlstra** [comment]
It most frequently finds places where the mypy test suite relies on a typeshed detail and needs to be fixed to land a typeshed change. I suppose those could also be fixed when mypy syncs its typeshed copy though; they're usually not real problems but just adjustments to error messages and the like.

**Comment by srittau** [comment]
> It most frequently finds places where the mypy test suite relies on a typeshed detail and needs to be fixed to land a typeshed change. I suppose those could also be fixed when mypy syncs its typeshed copy though; they're usually not real problems but just adjustments to error messages and the like.

That's the mypy-test-suite, though, not the mypy-self-check! Dropping that was discussed previously in #4333 and I think the resolution was to decrease the test suite in scope, but not drop it completely.

**Comment by JelleZijlstra** [comment]
Oh, you're right! Yes, I don't see much point in a check that typechecks mypy itself if we also have mypy-primer.
