### ISSUE TITLE
stdlib: Maximum supported version

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5304]
This came up in #5284 and at other places before: Currently we have no way to signal that a stub was removed from the stdlib. We hack around this by using a top-level version_info check, but that's not ideal.

I suggest we make use of the `stdlib/VERSIONS` file we have since the restructuring. Extend it a little so that no only versions are allowed, but also version ranges:

```
foo: 3.8
bar: 2.7-3.8
```

This would need a change in type checkers to parse the new format, but a simple first solution is to just add an equivalent of `version = version.split("-")[0]`.

Cc @rchen152 @erictraut @mrkmndz

**Comment by erictraut** [comment]
I didn't realize there was a VERSIONS file, so pyright doesn't currently pay attention to it. I should add that support. I'm fine with extending the format to include ranges.

**Comment by Akuli** [comment]
While we're at it, I think we could change the notation for "new in Python 3.8". Instead of `foo: 3.8`, how about `foo: 3.8+` (very obvious) or `foo: 3.8-` (consistent with range notation)?

**Comment by rchen152** [comment]
Allowing version ranges sounds useful. Shouldn't be difficult to support in pytype.

I like @Akuli's proposal to change the "new in 3.x" notation.

```
foo: 3.8
bar: 2.7-3.8
```

looks like it would mean that the `foo` stub is for `3.8` exactly and no other versions. I don't have a preference between `3.8+` and `3.8-`.

**Comment by srittau** [comment]
I have implemented the `3.8-` format in my mypy PR for simplicity of implementation.

**Comment by srittau** [comment]
I submitted PR to mypy (python/mypy#10402) and pytype (google/pytype#903). Since pyright and as far as I can see pyre don't support `VERSIONS` yet, we can implement this once the two PRs are merged.

**Comment by erictraut** [comment]
I have a PR that implements this support in pyright: https://github.com/microsoft/pyright/pull/1819. It handles the following formats: `3.8`, `3.8-`, `3.8+`, `3.6-3.9`.

**Comment by hauntsaninja** [comment]
One other edge case here is submodules that were added or removed in Python versions, e.g. asyncio.compat (removed in 3.7) or asyncio.threads (added in 3.9). Currently we don't list any submodules in VERSIONS.

**Comment by JelleZijlstra** [comment]
We could extend the format to say `asyncio.compat: 3.5-3.7`. Existing implementations would (I believe) just silently ignore such bounds for now.

**Comment by srittau** [comment]
Jelle's suggestion sounds good, but we should double check.

**Comment by srittau** [comment]
pyright's open PR at microsoft/pyright#1819 also just adds useless entries, so it should be fine.

**Comment by srittau** [comment]
This is implemented. We can also add submodules as needed.
