### ISSUE TITLE
CI: mypy_primer api rate error

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5308]
Part of error in #5307:

```
...
Waiting for mypy_primer to complete...
Waiting for mypy_primer to complete...
Waiting for mypy_primer to complete...
Waiting for mypy_primer to complete...
RequestError [HttpError]: API rate limit exceeded for installation ID 1538525.
...
```

**Comment by Akuli** [comment]
This seems to have something to do with CI failures on master, they fail with a similar error

**Comment by srittau** [comment]
Since we know about how long the mypy_primer run is going to last, maybe we can just sleep() for an amount of time before starting the API calls.

**Comment by Akuli** [comment]
No longer happens after reverting #5305
