### ISSUE TITLE
missing 2.7 modules

### ISSUE THREAD

**Issue by matthiaskramm** [python/typeshed#531]
The following modules have yet to be added to typeshed:

stdlib/2.7/cgi
stdlib/2.7/curses
stdlib/2.7/formatter
stdlib/2.7/htmllib
stdlib/2.7/xmlrpclib
stdlib/2.7/commands
stdlib/2.7/pstats
stdlib/2.7/cProfile
stdlib/2.7/ctypes
stdlib/2.7/SimpleHTTPServer

[edit: added items]

**Comment by JelleZijlstra** [comment]
We're also missing profile.

**Comment by gvanrossum** [comment]
Not everything listed in this issue has been added yet, so reopening.

**Comment by JelleZijlstra** [comment]
I have stubs for pstats ready, will open a pull request soon.

**Comment by matthiaskramm** [comment]
Closing in favor of #1147 1147
