### ISSUE TITLE
logging module annotations are incomplete

### ISSUE THREAD

**Issue by timabbott** [python/typeshed#532]
I noticed while annotating a script that while  `logging.critical({5: 1})` (or anything similar where you pass an object that can be converted to a string to the logging functions) works fine in Python, it isn't supported by the stubs in typeshed.

As a thing to test, mypy flags it as invalid with this error:

`/home/tabbott/foo.py:3: error: Argument 1 to "critical" has incompatible type Dict[int, int]; expected "str"`

**Comment by gvanrossum** [comment]
Is there any indication in the docs or docstrings that that's intentional?
Or is the right thing to do just to call str() on that dict? (Maybe the
idea is that if the logging level causes the call to be ignored you don't
pay for the object's __str__()?)

**Comment by timabbott** [comment]
The docs at least are pretty clear that these methods should expect to take a format string as the first argument, not an arbitrary object :).  

I have only one instance of the issue in the entire Zulip codebase, so it's easy enough to resolve with `str()` for my use case.  Your performance use case seems kinda vaguely plausible, though unlikely to be relevant except in unusual circumstances.

**Comment by gvanrossum** [comment]
OK, then I'll close this and we'll say that mypy found a questionable line in your code. :-)
