### ISSUE TITLE
Protobuf `FromString` argument 1 incompatible with supertype `Message`

### ISSUE THREAD

**Issue by kailin-lu** [python/typeshed#5333]
When using `types-protobuf` 0.1.9 `FromString` gives error `error: Argument 1 of "FromString" is incompatible with supertype "Message"; supertype defines the argument type as "ByteString"`

It looks like this error message was fixed  in mypy-protobuf 1.23 https://github.com/dropbox/mypy-protobuf/blob/master/CHANGELOG.md

**Comment by Avasam** [comment]
Is this issue still relevant? `types-protobuf` is now generated against `4.21.8`, and as OP mentioned, this issue seems to have been fixed upstream in `1.23`.
