### ISSUE TITLE
Support sys.platform.startswith 

### ISSUE THREAD

**Issue by hatal175** [python/typeshed#5336]
Currently none of the type checkers support startswith with regards to sys.platform. It is however necessary for some platform dependent constants - the sys.platform value for openbsd is openbsd{version} so comparison alone is not enough.
Note that this is the recommended way to check for other operating systems in the docs.

In addition, the flake8 linter will actually not accept any other os values, let alone startswith on sys.platform.

Examples for such constants:
mmap.ADV_*
time.CLOCK_PROF
time.CLOCK_UPTIME

This will probably stay open until the type checkers support this.

**Comment by srittau** [comment]
I think this proposal makes sense, but it should be brought up on typing-sig for discussion with type checker implementors. Until our supported type checkers support this, we can't use it in typeshed. I am going to close this for now, as is standard for issues labeled "inexpressible".
