### ISSUE TITLE
pallet projects get type hints: Click, Werkzeug, MarkupSafe, ItsDangerous, Flask, Jinja

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5337]
I asked on pallets projects discord:

>The next versions of all 6 projects will be released in a few weeks, and they'll all be fully typed and provide the py.typed marker. Click, Werkzeug, MarkupSafe, ItsDangerous, and Flask are done already, and I'm working on Jinja right now.

>I was going to open an issue in typeshed notifying about this once they were released. It's my understanding that py.typed will be preferred over typeshed, and typeshed will drop support after 6-12 months.

For now, should we keep accepting pull requests for these projects or just tell people to wait?

**Comment by srittau** [comment]
It's fine to accept PRs still.

**Comment by Akuli** [comment]
Duplicate of #5423
