### ISSUE TITLE
runtime_checkable is new in Python 3.8

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5352]
typeshed still makes it available for all Python versions.

I'm not sure how this should be fixed. The problem is that `typing.pyi` has code like this:

```
def runtime_checkable(cls: _TC) -> _TC: ...
@runtime_checkable
class SupportsInt(...):
    ...
```

It is tempting to change it to this:

```
if sys.version_info >= (3, 8):
    def runtime_checkable(cls: _TC) -> _TC: ...
    _runtime_checkable = runtime_checkable
else:
    def _runtime_checkable(cls: _TC) -> _TC: ...

@_runtime_checkable
class SupportsInt(...):
    ...
```

But the problem is that type checkers special-case `typing.runtime_checkable` and `typing_extensions.runtime_checkable`, and I don't know whether they would understand that `_runtime_checkable` refers to `runtime_checkable`.

**Comment by srittau** [comment]
There is a bit of a tradition that `typing.pyi` included things without a version check, especially during the time when `typing` was still provisional. We (rightly) stopped doing that for newer additions, though.

**Comment by JelleZijlstra** [comment]
I wonder if `from typing_extensions import runtime_checkable as _runtime_checkable` will work.

**Comment by hauntsaninja** [comment]
Protocol itself suffers from this problem too

**Comment by hauntsaninja** [comment]
I don't think we've gotten any user complaints about this + solving this for Protocol itself will likely be much more annoying.
