### ISSUE TITLE
tests/pyright_test.py

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5355]
This is no longer a part of our CI, because the CI uses pyright-action. Should we delete it?

**Comment by JelleZijlstra** [comment]
cc @jakebailey. I'd be a bit concerned about this test breaking or behaving differently from the GitHub Action if we don't run it in CI. On the other hand, it likely won't change much.

**Comment by srittau** [comment]
I think we should keep it so that the tests can easily be run locally, although I share Jelle's concern.

**Comment by jakebailey** [comment]
Both are thin wrappers over running pyright with args, but the script does automate running npx and hiding that pyright is in Node.

I don't mind reviewing and keeping the two up to date and consistent, personally. The action has its benefits in terms of performance and the commenting (though we had to scale that back a bit, sorry).
