### ISSUE TITLE
concurrent.futures.ProcessPoolExecutor's single argument is optional

### ISSUE THREAD

**Issue by dgoldstein0** [python/typeshed#538]
using `concurrent.futures.ProcessPoolExecutor()` with no arguments is legal, but mypy currently gives a type error.  Discovered in python 2.7 but it appears that it should repro in python 3 as well.

https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor

**Comment by phouse512** [comment]
@gvanrossum this can be closed!

**Comment by JukkaL** [comment]
Yeah, this looks fine in both Python 2 and 3 now.
