### ISSUE TITLE
Stubtest CI doesn't run on macos platform

### ISSUE THREAD

**Issue by hatal175** [python/typeshed#5380]
Wondering why it currently only runs on linux and windows.

**Comment by hauntsaninja** [comment]
We just haven't gotten around to it. In practice macOS is very similar to Linux; I estimate it'd be very rare that a PR would trigger a failure not caught by other stubtests.

**Comment by hatal175** [comment]
Mind if I add it?

**Comment by hauntsaninja** [comment]
Not at all, go for it! :-)
Btw, the big stubtest hole, if you're feeling up for it, is that we currently don't test any third party stubs.
