### ISSUE TITLE
"int" and "float" are not object subclasses in builtins.pyi

### ISSUE THREAD

**Issue by drewm1980** [python/typeshed#5421]
I discovered this while triaging some broken typechecking in pycharm:

https://youtrack.jetbrains.com/issue/PY-48566

I traced it down to a stub file in typeshed:

https://github.com/python/typeshed/blob/6bb1d885c696914e5900329c3d0b6bf2bfefee81/stdlib/builtins.pyi#L168

This is inconsistent with:
(in Python 3.7.9 (default, Aug 31 2020, 12:42:55) )
isinstance(int,object)
Out[2]: True

**Comment by srittau** [comment]
In Python 3, `class X:` and `class X(object):` are equivalent. Everything derives from `object`. For brevity and consistency reasons, we prefer to leave out the explicit superclass in typeshed.
