### ISSUE TITLE
README vs CONTRIBUTING

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5422]
I just wanted to add information about the new supported `METADATA` fields, but I was a bit unsure on where to add them. We have a certain duplication between `README` and `CONTRIBUTING`. For example, the directory structure and the `VERSIONS` file is described in both files.

My suggestion: Move the sections "Directory structure" and "Running the tests" into `CONTRIBUTING`. Split "Directory structure" into "Stubs for the Python Standard Library" and "Stubs for Third-party Library" and partly merge the "Stub versioning" section into those sections. Then we can description `VERSIONS` in the stdlib section and `METADATA` in the third-party section. README will be kept fairly short, and everything to do with development is in `CONTRIBUTING`.

**Comment by JelleZijlstra** [comment]
Sounds good, I'd also prefer to keep README short. Thanks for bringing this up! We could even add a third file (say SPECIFICATION.md) for the exhaustive detail on things like METADATA and VERSIONS, which isn't relevant to most contributors.
