### ISSUE TITLE
phase out Pallets library stubs (not before December 2021)

### ISSUE THREAD

**Issue by davidism** [python/typeshed#5423]
I have just released new major versions of Flask, Werkzeug, Jinja, Click, ItsDangerous, and MarkupSafe. They all include full type annotations and `py.typed` markers. Typeshed's stubs should be phased out since the versions they were written for are no longer supported.

**Comment by srittau** [comment]
Our current policy is to remove stubs 6-12 months after upstream released a typed version. Due to our latest restructuring I don't know if this policy still makes sense. I opened a discussion about this in #4608.
