### ISSUE TITLE
Request to add new stubs for pymmcore

### ISSUE THREAD

**Issue by tlambert03** [python/typeshed#5437]
Hi, I'd like to add stubs for [pymmcore](https://github.com/micro-manager/pymmcore) (python bindings for the C++ core of [micro-manager](https://github.com/micro-manager/micro-manager)).

I have a decent idea of what needs to be done, and stubs that are working pretty well for me locally, but just wanted to check in before posting a PR for a new repo, as per the contributing guide.  The python bindings are SWIG-generated... so if there are any specific tips or existing SWIG-based projects in typeshed that serve as a good example, please let me know.

thanks!

**Comment by srittau** [comment]
The stubs would certainly be welcome, although ideally third-party libraries are developed and shipped alongside the upstream package. If this is not desired and not possible at the moment, we gladly accept them here, though.

**Comment by tlambert03** [comment]
Thanks for the prompt reply!  I will pursue that and then close this issue if successful.
