### ISSUE TITLE
Guidelines for new third-party stubs

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5438]
Along our policy changes regarding new third-party stubs, our guidelines for them seem to have gone missing. I think we should have a (short) section about them. My ideas:

* Third-party stubs generally accepted as long as third-party package supports Python versions supported by typeshed.
* Preferably should go directly into upstream package, but we will add them if not desired by upstream or not possible at the moment.
* Typeshed can also be used as an "incubator" for third-party stubs, where they can mature here before being added upstream.

**Comment by JukkaL** [comment]
I'd prefer to make it very easy to contribute new stubs, and to make the rules clear and simple to follow. I only have anecdotal evidence, but I've heard that some third-party projects are pretty skeptical about stubs, and if we ask would-be contributors to start asking for permissions, they may get discouraged. It can feel awkward to ask total strangers for a permission. Here are some ideas:

* If a third-party project doesn't support type checking (no py.typed), we will accept stubs to typeshed.
* It can be enough to run stubgen + Black and contribute the auto-generated stubs [also include more detailed instructions].
  * If the generated stubs are big or messy, they need to be manually trimmed down.
  * We recommend first contributing auto-generated stubs in a PR, and (optionally) manually improving types in a separate PR, to simplify review.
* If you wish, you can ask upstream project maintainers if they'd like to bundle stubs instead. 
  * Maintaining stubs in the upstream package is preferred if the maintainers are actively interested in this. If there is little interest, the stubs may get stale and typeshed may be a better option.

**Comment by srittau** [comment]
That sound good. I agree with all the points you made, especially with not discouraging contributors by requiring them to ask upstream, but also encouraging them to at least consider the possibility. (Especially if they are part of the upstream maintainer team.)
