### ISSUE TITLE
flake8 ignores @python2 dir

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5454]
>We should probably remove it after this PR, since I expect many new errors.

_Originally posted by @srittau in https://github.com/python/typeshed/pull/5451#discussion_r632825913_

**Comment by JelleZijlstra** [comment]
Are there more errors after your round of unused import fixes?

**Comment by Akuli** [comment]
Besides unused imports fixed in #5453 , there were no errors. I think this is because most Python 2 stubs are copies of flake8 checked Python 3 stubs.
