### ISSUE TITLE
mypy_primer commenting is still broken

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5459]
See #5458 for example. Now mypy_primer runs but it fails to post comment. Previous fix attempt was #5452.

**Comment by Akuli** [comment]
Can't reproduce on my fork. I have the same exact config, but the comment still appears in my test PR.

**Comment by srittau** [comment]
Reopening for now, not sure this is really closed.

**Comment by JelleZijlstra** [comment]
It's still broken with `Error: Unhandled error: HttpError: Resource not accessible by integration`. https://github.com/python/typeshed/pull/5473/checks?check_run_id=2595427742

**Comment by srittau** [comment]
If that doesn't help, the only thing left to try is to remove the permissions block and reset the repository permissions to default to "write", not "read".

**Comment by JelleZijlstra** [comment]
It works again now, see #5473. Thanks to both of you for all the work getting this running again!
