### ISSUE TITLE
Use Protocol for pickle.load

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#5477]
The file argument to `pickle.load` is annotated as `IO[bytes]`, but should be annotated using a `Protocol` instead. The stub is at https://github.com/python/typeshed/blob/master/stdlib/pickle.pyi#L28.

This caused concrete problems for two people on Gitter who were trying to pass a `GzipFile`.

**Comment by pcm91** [comment]
Thank you @JelleZijlstra  for filing the issue.
