### ISSUE TITLE
os Module has no attribute "sys"

### ISSUE THREAD

**Issue by peteris-zealid** [python/typeshed#5484]
Running this:
```
mypy <(echo "import os; os.sys")
```
Got this:
```
/dev/fd/11:1: error: Module has no attribute "sys"
Found 1 error in 1 file (checked 1 source file)
```

**Comment by srittau** [comment]
Is there a reason why you can use `import sys`? `os` importing `sys` is just an implementation detail and we generally don't explicitly re-export imports.

**Comment by peteris-zealid** [comment]
Thank you, I will import sys. Somehow I was blind to this obvious solution. Not re-exporting seems smart.
