### ISSUE TITLE
add package_name to click.version_option stub

### ISSUE THREAD

**Issue by nicoa** [python/typeshed#5503]
This is a followup on https://github.com/pallets/click/pull/1582/files.

Occured in https://github.com/jazzband/pip-tools/pull/1400, yielding the following errors: https://results.pre-commit.ci/run/github/5746963/1621426072.IWTYTW7yT92q-jM6HMVwnQ

Maybe it makes sense to change this issue to adjust the whole click stub to be adapated to click 8.0.

**Comment by Akuli** [comment]
Click 8 has its own type hints, and type checkers don't use typeshed at all when checking Click 8 code. Therefore, it's better to keep our stubs at Click 7. See #5423.

If you are using Click 8, maybe report this directly to click instead?

**Comment by nicoa** [comment]
Hey,

thanks for the information, that for sure makes sense - I'll report it over there at click!
