### ISSUE TITLE
Update to click 8.x

### ISSUE THREAD

**Issue by fubuloubu** [python/typeshed#5537]
Click released v8.0.0 on May 11, 2021, but this library still is for v7.x series

I am seeing some errors from this package that are handled inconsistently using `pre-commit` vs. running `mypy` directly, using the same version of `mypy`

**Comment by srittau** [comment]
click 8 is type annotated, which supersedes typeshed's annotations. Therefore, typeshed won't be updated for click 8 and the click stubs will be removed. See #5423.

**Comment by fubuloubu** [comment]
@srittau is there a way to disable that check?

**Comment by JelleZijlstra** [comment]
@fubuloubu the issue you report sounds like `click` is not properly installed in one of the environments you're running in.

**Comment by fubuloubu** [comment]
@JelleZijlstra that is probably the case. When I run `mypy` in my local venv I get no issue because 8.x is installed. However, when running with `pre-commit` there is an issue, most likely because there is *no* version of `Click` installed and thus it defaults to the typeshed bindings.

I was curious if there was a way to disable typeshed in how `mypy` operates via command line flag. That would be a much easier solution than hacking the venv that `pre-commit` installs `mypy` in

**Comment by JukkaL** [comment]
@fubuloubu In mypy 0.900 (to be released soon) stubs for third-party libraries won't be installed with mypy automatically, so they will be disabled by default.

**Comment by fubuloubu** [comment]
@JukkaL awesome, thanks that helps!

**Comment by fubuloubu** [comment]
Note: if anyone ends up here from tracing a `pre-commit` issue, this is the resolution:

```diff
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
      -   id: mypy
+         # NOTE: Until mypy drops typeshed for Click, it will still try v7.x by default
+         # HACK: Until mypy 0.900 is released and typeshed is opt-in
+         additional_dependencies: [Click==8.0.1]
```
