### ISSUE TITLE
Incorrect annotation for Match.__getitem__

### ISSUE THREAD

**Issue by jwodder** [python/typeshed#5546]
[The annotation for `typing.Match.__getitem__`](https://github.com/python/typeshed/blob/9795bae6f7bca95efcc96a7b470c92d0ad2b9e4e/stdlib/typing.pyi#L578) states that it returns an `AnyStr`.  However, it can also return `None` when the specified group was not captured.

**Comment by srittau** [comment]
Basically a duplicate of #3902.
