### ISSUE TITLE
Run primer only if other tests are successful

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5548]
Otherwise, there is a lot of primer spam, like in #5545. Also, it wastes CI minutes and the output is not particularly useful if there are still errors in the stubs. The disadvantage is that it will take longer until CI is green.

**Comment by Akuli** [comment]
Ideally we would run mypy_primer if black or isort fails but otherwise everything succeeds.

It might be possible to do this by specifying `needs:`, although I don't know whether `mypy_primer.yml` can need something from `tests.yml`.

**Comment by Akuli** [comment]
It would also help if the primer would stop when a new commit is pushed. The new commit starts a new primer run anyway, and then the old run is no longer meaningful

**Comment by jakebailey** [comment]
FWIW I use this to cancel old CI runs, and it should have the ability to cancel other workflows.

https://github.com/styfle/cancel-workflow-action

**Comment by hauntsaninja** [comment]
We currently have comment collapsing + I think we automatically cancel primer runs for pre-commit failures.
