### ISSUE TITLE
LoggerAdapter.__init__(logger) should accept LoggerAdapter in argument

### ISSUE THREAD

**Issue by aaugustin** [python/typeshed#5561]
The documentation for [logging.LoggerAdapter](https://docs.python.org/3/library/logging.html#loggeradapter-objects) says:
> you can use the two types of instances [Logger and LoggerAdapter] interchangeably

I have a use case from wrapping a LoggerAdapter in another LoggerAdapter.

Currently typeshed doesn't allow this because the first argument has to be a `Logger`: https://github.com/python/typeshed/blob/2a9f081abbf01134e4e04ced6a750107db904d70/stdlib/logging/__init__.pyi#L372

I'd like to change it to `Union[Logger, LoggerAdapter]` but this creates a circular definition and I'm not sure about the best practice for handling this case. Should I try `Union[Logger, "LoggerAdapter"]`?

**Comment by JelleZijlstra** [comment]
Forward references are fine in typeshed, and so are PEP 604 `|` Unions. You can just write `Logger | LoggerAdapter`.

**Comment by aaugustin** [comment]
Thanks for the guidance! I'll submit a PR.
