### ISSUE TITLE
_typeshed.tkinter

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#5575]
This is a weird module. We should consider removing it, because it's only used in one file.

_Originally posted by @Akuli in https://github.com/python/typeshed/pull/5573#discussion_r645569819_

**Comment by srittau** [comment]
Cc @CraftSpider as original author.

**Comment by CraftSpider** [comment]
Its been a while and I forget exactly what my reasoning was, I believe it was probably about it not being a 'real' type or such. I'm fine with removing it.
