### ISSUE TITLE
Remove attrs (March 2019)

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5581]
`attrs` ships its own stubs since [version 18.2.0](https://github.com/python-attrs/attrs/blob/main/CHANGELOG.rst#1820-2018-09-01), released in September 2018. After #5580 is merged and auto-uploaded to pypi, we should remove the attrs stubs per our policy.

Cc @hynek for any potential gotchas.

**Comment by hynek** [comment]
I don't think so but I'd like @euresti to quickly confirm. :)

**Comment by euresti** [comment]
No gotchas that I can think of.  Please remove.
