### ISSUE TITLE
mimetypes stubs are incorrect on Python 2

### ISSUE THREAD

**Issue by timabbott** [python/typeshed#559]
The stubs for mimetypes.guess_type only accept str.

On Python 2, mimetypes.guess_type accepts an AnyStr as its argument:

```
In [1]: import mimetypes

In [2]: mimetypes.guess_type(u"test☃.xml")
Out[2]: ('application/xml', None)

In [3]: mimetypes.guess_type(u"test☃.xml".encode("utf-8"))
Out[3]: ('application/xml', None)
```

On Python 3, mimetypes.guess_type() expects str only, so the stubs are correct for that.

**Comment by phouse512** [comment]
@timabbott I'm looking at the current typeshed code, and this looks correct to me:

```
# stdlib/2and3/mimetypes.pyi
def guess_type(url: str,
               strict: bool = ...) -> Tuple[Optional[str], Optional[str]]: ...
```

Should this issue be closed?

**Comment by gvanrossum** [comment]
No, if you try that in `mypy --py2` you get `Argument 1 to "guess_type" has
incompatible type "unicode"; expected "str"`.

**Comment by phouse512** [comment]
@gvanrossum that makes sense. since this definition is in `2and3`, what do you think is the best approach here: splitting this into different 2.7 and 3 definitions or adding a special conditional for this method?

**Comment by gvanrossum** [comment]
I'd use Text -- in PY2 that's unicode but str implicitly promotes to unicode.
