### ISSUE TITLE
third-party: version field

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5591]
Currently the `version` field in `METADATA.toml` is defined as follows:

> `version`: The oldest version of the library for which the stubs are still applicable (i.e. reflect the actual runtime behaviour). Note that only two most significant version levels are supported (i.e. only single dot). When a significant change is made in the library, the version of the stub should be bumped (note that previous versions are still available on PyPI).

After working a bit with the new typeshed layout, I have found a few problems with this. I think it would be better both for stub authors and also for stub users to change it to something like this:

> `version`: The latest version of the library that the stubs support. Note that only two most significant version levels are supported (i.e. only single dot). When the stubs are updated to a newer version of the library, the version of the stub should be bumped (note that previous versions are still available on PyPI).

With the old scheme, a library following semver (arguably the most used versioning scheme) would always stay at version `X.0` for a given major version `X`.

Advantages for stub authors: It's hard to determine whether changes you make will make the stubs "inapplicable" to older versions, and which is the first version that still works with the changes. This burden leads to people leaving the version number unchanged. Case in point:

```
$ grep "version ="  stubs/*/METADATA.toml | cut -d "=" -f 2 | sort | uniq -c
     75  "0.1"
      3  "0.2"
      2  "0.4"
      1  "0.6"
      1  "1.17"
      1  "1.2"
      1  "1.4"
      1  "19.1"
```

Using the new scheme it's usually fairly trivial, especially since changes are often made in response to a library's new release.

For users it's much easier to find the correct version of types to install, since the types's version number communicates it much more clearly: Just look for the version that matches your library's version in the first two digits. The requirements can actually be identical between the library and the types now. Types have a higher minor number? It will probably work, but there could be false positives. Types have a smaller minor number? Stubs will not necessarily support all features of the library. With the old scheme it was often not clear which version of stubs you should best install.

**Comment by JelleZijlstra** [comment]
Agree that this would work better. The previous system is fairly hard to understand.

**Comment by srittau** [comment]
Cc @JukkaL as original author of the current policy.

**Comment by JukkaL** [comment]
Yeah, the proposed new policy sounds better. I think that we may want an exception for 0.1.x, which is currently used for most stub packages. It could mean "supported library version unknown".
