### ISSUE TITLE
mypy and pyright disagree on variance

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5599]
https://github.com/python/typeshed/blob/c601d5cf3d8968f3dc1fe792bc1da5b43c6a9ed9/stubs/Jinja2/jinja2/utils.pyi#L11-L23

mypy wants this to be invariant, pyright wants it to be covariant. Find out what's right and file a bug with the type checker that's wrong.

**Comment by jakebailey** [comment]
Was there a typo in the title and this was meant to reference pyright? (I did see this ignore in the recent PR.)

@erictraut

**Comment by JelleZijlstra** [comment]
Yes, pretty sure pyright is meant here. I will update the issue title. Not the first time I've seen people confuse the names :)

**Comment by jakebailey** [comment]
`*py*` 🙂

**Comment by srittau** [comment]
Oops, thanks Jelle.

**Comment by Avasam** [comment]
Is this still the case? Am I supposed to see any error from your code snippet?
![image](https://github.com/python/typeshed/assets/1350584/5f1aa6e5-ec3c-4e24-bede-1b680e6997b1)

**Comment by srittau** [comment]
Thanks, I'm going to close it, assuming this has been fixed.
