### ISSUE TITLE
Update protobuf generation script

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5603]
* [ ] Use `...` as default.
* [x] Run black and isort after generation.
* [ ] Use PEP 604 and PEP 585.

Diff against manually modified stubs for further changes.

**Comment by srittau** [comment]
#5605 now fixes the script and runs black and isort. But the generation itself must be fixed elsewhere.

**Comment by AlexWaygood** [comment]
The generated protobuf stubs are now (nearly) fully compliant flake8-pyi — is there anything left to do here?
