### ISSUE TITLE
Run pyright with stricter options for "known-good" stubs

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5607]
See #5597 for background. To quote @erictraut:

> Here's an idea. Pyright allows you to specify a config file by path. By default it looks for a config file called "pyrightconfig.json" in the root directory, but you can specify a different config file. We could define two separate config files and run two separate passes. The first pass would use stricter settings and would exclude libraries that are not complete, the second pass would use laxer settings and would include all libraries. Thoughts?

**Comment by erictraut** [comment]
Would you like help with this? @jakebailey wrote the pyright test scripts for typeshed, so he could probably do this most efficiently.

**Comment by jakebailey** [comment]
Likely we can have two configs where the stricter one includes the stdlib and some specific libs in the stubs dir, ignoring the rest, then have the more generic one run on everything (I don't think it will be any faster to restrict things on the non-strict end). Then, a flag to run the stricter config can be documented for local use (for those using that wrapper script).

To run, we'd either need to double up the GHA jobs (faster) or run them back to back (fewer jobs).

**Comment by srittau** [comment]
Running them back to back has the advantage that we can easily skip the run of the second invocation when the first one fails, removing duplicate errors. Time-wise, pyright is one of the fastest checks, so it shouldn't make much of a difference.
