### ISSUE TITLE
enum.Flag.name can be None

### ISSUE THREAD

**Issue by mthuurne** [python/typeshed#5610]
If you run the following program:
```py
from enum import Flag, auto
from typing import TYPE_CHECKING

class MyFlag(Flag):
    A = auto()
    B = auto()

both = MyFlag.A | MyFlag.B
print(f"{both} has name {both.name}")
if TYPE_CHECKING:
    reveal_type(both.name)
```
It outputs:
```
MyFlag.B|A has name None
```
However, if it is checked with mypy, the output reads:
```
testcase.py:11:17: note: Revealed type is "builtins.str"
```
I think that `enum.Flag` should have `name` overridden to be `Optional[str]` instead of just `str`.

Since `Flag` inherits its `name` attribute from `Enum`, strictly speaking either `Enum.name` should also have type `Optional[str]` or we have to accept that `Flag` does not comply with the interface of its parent class. I think the latter is the more pragmatic solution.

**Comment by JelleZijlstra** [comment]
Agree that making just Flag.name none is better. Ideally we'd be able to tell the type checker that named flags never have a None name, but that's probably beyond what we can do in typeshed.

**Comment by mthuurne** [comment]
I'm not sure that would be feasible even with a plugin: if a function takes an argument of type `Flag`, you'd have to assume it can be a composite flag. Besides, if a program doesn't create composite flags, it shouldn't be using `Flag` in the first place, but `Enum` instead.

There is one special case where it could be useful: if a particular `Flag` subclass defines names for all possible combinations of set flags. I don't expect that to be common though: the number of combinations grows exponentially with the number of flags, so only small `Flag` subclasses could do this.

Anyway, would you like me to send a PR or is that overkill for a small change like this?

**Comment by Akuli** [comment]
Make a PR :)
