### ISSUE TITLE
Remove cryptography (depends on #5952)

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5618]
`cryptography` added `py.typed` in [release 3.4.4](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst#344---2021-02-09), released 2021-02-09.

**Comment by hauntsaninja** [comment]
One fun and different thing about types-cryptography is that other typeshed packages depend on it: paramiko, PyJWT, openssl-python.

So we will need to ensure stub packages can depend on non-typeshed-stub-packages.

**Comment by hauntsaninja** [comment]
Just in case, does anyone feel strongly against allowing stub packages from depending on real PEP 561 packages? cc @JukkaL

**Comment by srittau** [comment]
What do you mean by "real" PEP 561 packages?

**Comment by Akuli** [comment]
Perhaps packages that contain `.py` files and a `py.typed` file.

**Comment by hauntsaninja** [comment]
Yup, I started with "real packages", clarified to "PEP 561 packages", but missed editing out the "real".

**Comment by srittau** [comment]
Not speaking about stubs packages in general, but I think it's reasonable if typeshed packages depend on dependencies of the corresponding upstream package. I.e. if package `foo` depends on `cryptography`, it's fine that our `foo-types` depends on `cryptography` as well, since it doesn't introduce "new" dependencies. Apart from that we should vet dependencies carefully.

**Comment by JukkaL** [comment]
I agree with @srittau. 

I think that it would be sufficient to maintain an allowlist of vetted dependencies. I'd expect that the number of such dependencies will be fairly small, so it shouldn't be much effort to maintain.

**Comment by srittau** [comment]
Blocked by #5952.

**Comment by Akuli** [comment]
What is the current status of this? Can we now make other packages depend on `cryptography`?
