### ISSUE TITLE
Incomplete time types

### ISSUE THREAD

**Issue by richli** [python/typeshed#562]
Several functions were added to [time](https://docs.python.org/3/library/time.html) in Python 3.3. Notably, `time.clock()` is marked as deprecated in favor of `time.perf_counter()` and `time.process_time()`. These new functions -- and some added constants -- are not in `typeshed/stdlib/3/time.pyi`.

It looks like it's straight-forward to add the missing types. Would you like me to try it and open a pull request, or would someone else be interested in this?

**Comment by gvanrossum** [comment]
Sounds like a great and easy pull request -- go ahead! For version checks, use `if sys.version_info >= (3, 3):`. Good luck!

**Comment by richli** [comment]
I opened #563. It was pretty easy to make the changes, except that one of the new functions returns a `types.SimpleNamespace` object, so I annotated it as a `Dict` instead.

**Comment by richli** [comment]
Thanks for merging!
