### ISSUE TITLE
markupsafe.Markup.join()/.split()/.rsplit()/.splitlines() incorrectly typed: should return Markup, not text_type

### ISSUE THREAD

**Issue by mgedmin** [python/typeshed#5632]
The [type declaration of `Markup.join`](https://github.com/python/typeshed/blob/d3ba8a38587ceb8c54dfa9fed32c1028aa80595e/stubs/MarkupSafe/markupsafe/__init__.pyi#L16) is incorrect: it returns `text_type`, instead of `Markup`.

`.split()`/`.rsplit()`/`.splitlines()` are also incorrect in a similar way: they return `List[text_type]` rather than `List[Markup]`.

**Comment by srittau** [comment]
PR welcome!

**Comment by mgedmin** [comment]
Thank you for the encouragement!

I don't know where I got the wrong impression that these .pyi files are auto-generated.  If they're written manually, then a PR is simple to produce.

**Comment by srittau** [comment]
While some of our stubs were initially autogenerated, they are maintained by hand afterwards as autogeneration is generally fairly imprecise at the moment.
