### ISSUE TITLE
Question: Is there a changelog?

### ISSUE THREAD

**Issue by meshy** [python/typeshed#5633]
Hi! Thank you for producing this wealth of type hints, and for keeping them up to date.

Over the weekend I received some version bump pull requests from Dependabot:

- `types-requests`: `0.1.9` -> `0.1.11`
- `types-freezegun`: `0.1.2` ->  `0.1.3`

When merging library bumps, I am in the habit of checking changelogs/announcements to work out what has changed, but in this case, it has proved something of a challenge, mainly because I was unable to find release notes, git tags, or a changelog.

I ended up comparing [version release dates on PyPI](https://pypi.org/project/types-requests/#history) to the [history of commits to the corresponding directory](https://github.com/python/typeshed/commits/master/stubs/requests). On a day-to-day basis, this is workable, but for anyone lagging behind, I can imagine that process quickly becoming very frustrating.

I wonder if I have missed the changelog somewhere, or if there is some other method that people are using to determine what has changed in a release?

**Comment by srittau** [comment]
I agree that having a Changelog, shipped with the stubs would be a good idea. We could just autogenerate it from "git log".

**Comment by JelleZijlstra** [comment]
And just to be clear the answer to the question is no, there is no changelog.

We could implement this in https://github.com/typeshed-internal/stub_uploader by adding a snapshot of `git log` on upload, as @srittau suggests.

**Comment by JukkaL** [comment]
We'd probably only want to include the log entries for the relevant `stubs/*` directory to avoid noise.

**Comment by srittau** [comment]
My idea would be to store the generated changelog in git and whenever a new version is uploaded roughly do:

```
echo "# Changes in ${STUB_VERSION}\n" > $TMP
git log ${LAST_COMMIT+1}.. -- stubs/${STUBDIR} >> $TMP  # probably needs some cleanup
cat $CHANGELOG >>$TMP
mv $TMP $CHANGELOG
git add $CHANGELOG && git commit -m "..."
```

**Comment by Akuli** [comment]
Maybe we should get rid of the distribution name in the commit messages. If the commit message is `Pymysql cursor types and fetching return types (#5652)`, it's not very useful to repeat `Pymysql` in the pymysql-specific changelog.

**Comment by srittau** [comment]
If we implement this, we should be mindful of using more specific commit messages on general. While I used to rely on the fact that the commit messages were complementing the changes, now the commit messages must stand for itself.

**Comment by simonw** [comment]
> And just to be clear the answer to the question is no, there is no changelog.
> 
> We could implement this in https://github.com/typeshed-internal/stub_uploader by adding a snapshot of `git log` on upload, as @srittau suggests.

I'd really appreciate that! I just filed the same issue in #5678.

**Comment by kmurphy4** [comment]
Thanks for adding this @srittau -- it's very helpful!

My understanding is that the only way to _view_ the changelog is to download the package from PyPI, e.g.,

<details>
<summary>

```sh
$ curl -qs https://files.pythonhosted.org/packages/36/a6/e2092e750dc633d118d2d8c23316ea8b20f6df1c31ab82ef4aacc4c10710/types-psutil-5.8.3.tar.gz \
    | tar xz types-psutil-5.8.3/CHANGELOG.md --to-stdout
```

</summary>

```
## 5.8.3 (2021-09-06)

Improves `psutil/_common.pyi` (#6010)

* Improves `psutil/_common.pyi`

In this iteration I've fixed the most obvious types and corrected several mistakes.
We can go deeper in the next iteration(s).

* We don't need to import `Union`

* Update _common.pyi

* Update _common.pyi

* Update _common.pyi

## 5.8.2 (2021-09-06)

Adds more missing `ContextManager` types (#6007)

1. https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/_psbsd.py#L571
2. https://github.com/giampaolo/psutil/blob/c3e63b4dd59f1724a7fa29371e53dfa7f46cbcd3/psutil/_psosx.py#L365

## 5.8.1 (2021-09-05)

Fix return type of Process.oneshot() (#6006)

```

</details>

Is that correct? Or is there a way to view the changelogs before downloading?

**Comment by srittau** [comment]
The changelogs are also available at https://github.com/typeshed-internal/stub_uploader/tree/main/data/changelogs.

**Comment by kmurphy4** [comment]
Oh, amazing! Thank you!
