### ISSUE TITLE
Use of click.version_option results in "untyped decorator" error

### ISSUE THREAD

**Issue by cjolowicz** [python/typeshed#5642]
Using mypy 0.902 and types-click 7.1.1, `@click.version_option` is considered untyped, resulting in this error:

*Untyped decorator makes function "main" untyped*

**Steps to reproduce:**

*repro.py*

```python
import click


@click.command()
@click.version_option()
def main() -> None:
    """Main."""


if __name__ == "__main__":
    main()
```

*repro.sh*

```sh
#!/bin/bash

virtualenv -p 3.9 venv
. venv/bin/activate
pip install mypy types-click
mypy --strict --pretty repro.py
```

**Actual output:**

```
repro.py:5: error: Untyped decorator makes function "main" untyped
    @click.version_option()
     ^
Found 1 error in 1 file (checked 1 source file)
```

**Expected output:**

```
Success: no issues found in 1 source file
```

**Environment:**

```sh
$ venv/bin/pip freeze
mypy==0.902
mypy-extensions==0.4.3
toml==0.10.2
types-click==7.1.1
typing-extensions==3.10.0.0
```

**Comment by ska-kialo** [comment]
Having the same issue with `click.option` and `click.argument`.

**Comment by srittau** [comment]
Please note that starting with click 8, click ships a `py.typed` file and typeshed's stubs are ignored. In fact, when trying the original example with only `types-click` installed, but not `click`, it type checks just fine.

**Comment by cjolowicz** [comment]
@srittau Thanks for clarifying this.

I guess the pitfall here is:

1. upgrade mypy >= 0.900
2. install types-click because of the mypy warning
3. upgrade click >= 8.0
4. mypy complains about "untyped decorator"

Assuming that click is installed, removing types-click also solves this.

**Comment by srittau** [comment]
Weird that uninstalling types-click changes anything. Anyway, I have opened python/mypy#10652 to remove the suggestion to install these stubs.
