### ISSUE TITLE
docutils.frontend.OptionParser.__init__() signature is missing

### ISSUE THREAD

**Issue by mthuurne** [python/typeshed#5667]
`docutils.frontend.OptionParser` inherits from `optparse.OptionParser`, but has a different `__init__()` signature, which is missing from the type stubs.

I'll submit a PR later.

This is related to #1269, but the scope of that is so much broader that I think it's useful to track them separately.

**Comment by tristanlatr** [comment]
This issue has been fixed in https://github.com/python/typeshed/pull/5924. 

It can be closed in my opinion.
