### ISSUE TITLE
typeshed utilities package?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5673]
This came up in #5660. At least some of our tests, but also type checkers like mypy and pytype have code to work with the typeshed structure. Would it make sense to have a small `typeshed_utils` package that has a few utility packages, like iterating over all third-party stubs with metadata attached, or getting the metadata for a specific third-party library? At least at the start, we wouldn't even need to publish it on pypi, since mypy and pytype use a copy of typeshed.

**Comment by Akuli** [comment]
If our directory structure is so complicated that you need a package just to use it, then IMO we should instead simplify the directory structure. For example, we could split all third-party stubs into separate Python 2 and Python 3 stubs, and then the two lines of code that are currently copy/pasted are no longer necessary.

**Comment by JelleZijlstra** [comment]
I have https://github.com/JelleZijlstra/typeshed_client that I use in my type checker; it could be extended for other code that consumes typeshed. I'm not sure it's really worth it for the relatively simple code in our tests though.

**Comment by srittau** [comment]
So this package already exists. Perfect.
