### ISSUE TITLE
Incorrect ContextManager.__enter__ return type

### ISSUE THREAD

**Issue by hosford42** [python/typeshed#5674]
It appears the return type `ContextManager.__enter__` in `typing.pyi` is defined as the type of `self` for the context manager, because the default implementation of the method returns `self`. Mypy is complaining that my context manager which returns a different type is incorrect, as a result. However, context managers can and often do return other types of values. I believe the correct type should be `typing.Any`. Here is a toy example of a context manager which returns a different type than itself:

```python3
class ItemAccess:
    def __init__(self):
        self.items = []
    def __enter__(self):
        print("Accessing 'items'.")
        return self.items
    def __exit__(self, *args):
        print("Done accessing 'items'")

item_access = ItemAccess()
with item_access as items:
    items.append(1)
print("Items:", item_access.items)
```

In Python 3.8.5, this runs without error and generates the following output:
```
Accessing 'items'.
Done accessing 'items'
Items: [1]
```

**Comment by Akuli** [comment]
`TemporaryDirectory` is a practical example of a context manager returning non-`self` from `__enter__`. The `__enter__` return value is the path to the directory, as a string.

**Comment by JelleZijlstra** [comment]
> It appears the return type ContextManager.__enter__ in typing.pyi is defined as the type of self for the context manager

It's not: https://github.com/python/typeshed/blob/master/stdlib/typing.pyi#L422. I believe it's true that that's what the implementation of typing.py does, but the implementation isn't used by mypy.

> Here is a toy example of a context manager which returns a different type than itself

I tried that example just now and mypy gave no errors.

Could you be more concrete about what you think is not working correctly?

**Comment by hosford42** [comment]
My apologies. I was under the false impression that PyCharm uses mypy for its type checking, but it turns out they have their own closed-source implementation. I'm going to assume that's the source of the problem, and not typeshed. Thank you for clearing up that the typing.pyi entry is correct.
