### ISSUE TITLE
Improve the self types situation

### ISSUE THREAD

**Issue by JelleZijlstra** [python/typeshed#5676]
From micro codery on typing-sig:

> It was only after seeing the solution that I could find docs describing it on mypy.readthedocs. There is a note claiming that a generic self is still experimental but maybe a convention should be added to the typeshed contributing guide about using it, just like Sequence is recommended over list. 

From @srittau on #5675:

> I suggest that in the future we shouldn't accept `__enter__()` methods returning `self` anymore that don't use a type var.

I think we should do both of these things. We can find some existing offenders with `git grep  'def __enter__(self) -> [A-Z]'`.

**Comment by srittau** [comment]
We can also add a `Self` type var to `_typeshed`:

```python
Self = TypeVar("Self")
```

This can help us finding places where we should use `typing.Self` if this proposal is accepted.

**Comment by gruebel** [comment]
I think all of the work is done in the `stdlib`, except for Python 2 types. Do you also want to tackle it or just leave it as it is?

**Comment by srittau** [comment]
Personally, I would not put the work into Python 2 stubs, but I would accept PRs improving them.

**Comment by gruebel** [comment]
I'm also not up to put some work into Python 2 stubs 😄 so next would be the stubs under the `stubs` folder, right?

**Comment by JelleZijlstra** [comment]
Looks like there's no work left. (I forgot what Python 2 is.)
