### ISSUE TITLE
Unclear what has changed in new types-orjson release

### ISSUE THREAD

**Issue by simonw** [python/typeshed#5678]
I got a PR from dependabot telling me about `types-orjson` 0.1.1 https://github.com/CAVaccineInventory/vial/pull/684

I always glance at the changelog or commits to see what's changed before merging a PR like this - but for `types-orjson` I cannot figure out what's new in 0.1.1

https://pypi.org/project/types-orjson/#history shows 0.1.1 as being released on June 17th - but links back to the https://github.com/python/typeshed homepage

https://github.com/python/typeshed/commits/master/stubs/orjson shows that there have been no changes to the `typeshed/stubs/orjson` folder since January.

There's a `METADATA.toml` file here but it has a version number of `0.1` - not `0.1.1`: https://github.com/python/typeshed/blob/816a92b8e82a2fd035f9fcb528f8a1f8bd5de988/stubs/orjson/METADATA.toml#L1

I think it's important to be able to tell what has changed for this kind of package - right now it's a mystery!

**Comment by hauntsaninja** [comment]
Thanks for reporting, dupe of https://github.com/python/typeshed/issues/5633

**Comment by simonw** [comment]
I'll close this as a dupe, thanks!

**Comment by srittau** [comment]
@simonw As for your question: We recently changed our build process to also build sdists. This is why we published a new version of all packages.

**Comment by simonw** [comment]
Gotcha, that makes sense! Thanks.
