### ISSUE TITLE
abc.ABCMeta.__abstractmethods__ missing on py3+

### ISSUE THREAD

**Issue by graingert** [python/typeshed#5679]
with:

```python
import abc
import six

@six.add_metaclass(abc.ABCMeta)
class Foo(object):
    @abc.abstractmethod
    def foo(self):
        pass

v = Foo
v.__abstractmethods__
```

`abc.ABCMeta.__abstractmethods__` seems missing on py3+

https://mypy-play.net/?mypy=latest&python=2.7&gist=188750c833a234ed64e29755226a08ab
https://mypy-play.net/?mypy=latest&python=3.9&gist=188750c833a234ed64e29755226a08ab

**Comment by graingert** [comment]
seems defined in py2 stubs: https://github.com/python/typeshed/blob/816a92b8e82a2fd035f9fcb528f8a1f8bd5de988/stdlib/%40python2/abc.pyi#L10-L12 but not py3: https://github.com/python/typeshed/blob/816a92b8e82a2fd035f9fcb528f8a1f8bd5de988/stdlib/abc.pyi#L7-L9

**Comment by graingert** [comment]
seems there's a bunch of attributes defined in py2 abc.ABCMeta that are not defined for py3

**Comment by srittau** [comment]
I don't think this is anything that typeshed can help with. As far as I understand, `__abstractmethods__` is defined on the class itself when using `ABCMeta` as a metaclass, not on `ABCMeta`. typeshed can't communicate this via the type system. The only solution I can see is special-casing this in type checkers.

That `ABCMeta.__abstractmethods__` is defined in Python 2 seems like an error to me:

```python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from abc import ABCMeta
>>> ABCMeta.__abstractmethods__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: __abstractmethods__
```

**Comment by layday** [comment]
Isn't that just as much of an error as

```py
class Foo:
    bar: str

    def __init__(self, bar: str):
        self.bar = bar

Foo.bar
```

is?  `Foo` doesn't have `bar` but `Foo()` does.  `ABCMeta` doesn't have `__abstractmethods__` but classes with `ABCMeta`  as their metaclass do.

**Comment by srittau** [comment]
There is no way for typeshed to add annotations to this effect, though. At least not that I'm aware of. This is just something the type system can not express. But we should add `__abstractmethods__` to individual classes in typeshed that have an `ABCMeta` meta class.

**Comment by graingert** [comment]
Could mypy add the attributes instead? Or could the stdlib ABCMeta gain a `__abstractmethods__ = frozenset()` attribute?

**Comment by layday** [comment]
There's no way to add the attribute statically when using a decorator for Python 2 compatibility but it should work just fine with a metaclass.

**Comment by graingert** [comment]
> There's no way to add the attribute statically when using a decorator for Python 2 compatibility

mypy special cases six.add_metaclass

**Comment by graingert** [comment]
Wait, @layday you're right you can't even construct `ABCMeta()` so the py2 annotation needs to be moved to `def __init__`

**Comment by layday** [comment]
I don't think there's anything wrong with the Python 2 annotation. This:

```py
class FooMeta(type):
    bar: str

class Foo(metaclass=FooMeta):
    pass

reveal_type(FooMeta.bar)    # Revealed type is "builtins.str"
reveal_type(Foo.bar)        # Revealed type is "builtins.str"
```

... is strictly equivalent to:

```py
class Baz:
    qux: str

reveal_type(Baz.qux)        # Revealed type is "builtins.str"
reveal_type(Baz().qux)      # Revealed type is "builtins.str"


```

**Comment by srittau** [comment]
Disregard everything I wrote above. I did not know that attributes on metaclasses become a part of the class dict of the classes they construct. We should indeed add `__abstractmethods__` to `ABCMeta` for Python 3 as well. PR welcome!

**Comment by layday** [comment]
> Wait, @layday you're right you can't even construct `ABCMeta()` so the py2 annotation needs to be moved to `def __init__` and then copied to py3

To be clear, variables defined in `__init__` aren't handled any differently by mypy:

```py
class Baz:
    def __init__(self) -> None:
        self.qux: str = ""

reveal_type(Baz.qux)        # Revealed type is "builtins.str"
reveal_type(Baz().qux)      # Revealed type is "builtins.str"

```

**Comment by graingert** [comment]
Oh weird, maybe they should be?
