### ISSUE TITLE
QueueHandler sets args, exc_info, exc_text to None

### ISSUE THREAD

**Issue by kasium** [python/typeshed#5710]
Hi all,

I'm not sure what do with this. The logging.handlers.QueueHandler sets the args, exc_info, exc_text of the logging record to None, which is not present in the current type stubs.
I already opened a python bug asking for a documentation improvement: https://bugs.python.org/issue44473

However, is it possible somehow to reflect this in the type stubs w/o disturbing all users?

Code: https://github.com/python/cpython/blob/823460daa9fab3d0cf00ec553d1e35635ef73d40/Lib/logging/handlers.py#L1424-L1426

Thanks, Kai

**Comment by srittau** [comment]
I guess we should update `LogRecord.args` by adding `| None`. We could modify `__init__` as well. `exc_info` and `exc_text` already allow `None` values.

**Comment by kasium** [comment]
So in the case my current code would expect that args is never None, with a newer release of the type stubs, checkers like mypy would maybe find an issue, right?

**Comment by srittau** [comment]
Correct, they would.

**Comment by kasium** [comment]
Okay, should I make a PR?

**Comment by srittau** [comment]
A PR would be welcome!
