### ISSUE TITLE
ipaddress functions are too widely typed

### ISSUE THREAD

**Issue by deadpixi** [python/typeshed#5721]
The type definition for the `ipaddress.ip_address` in `ipaddress.pyi` is:

    def ip_address(address: object) -> Any: ...  # morally Union[IPv4Address, IPv6Address]

Note that the return type is annotated as `Any`.

The definitions for `ip_network` and `ip_interface` are similar.

Is there a reason why the return type for these functions isn't something like `Union[IPv4Address, IPv6Adress]`? The comments seem to indicate that his was desirable but avoided for some reason.

Thanks!

**Comment by hauntsaninja** [comment]
typeshed often avoids union return types: https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions
