### ISSUE TITLE
Missed annotations for aiofiles.tempfile

### ISSUE THREAD

**Issue by orsinium** [python/typeshed#5737]
[aiofiles](https://github.com/Tinche/aiofiles) has module [aiofiles.tempfile](https://github.com/Tinche/aiofiles/tree/master/src/aiofiles/tempfile) which is missed in [aiofiles stubs](https://pypi.org/project/types-aiofiles/)

**Comment by srittau** [comment]
Any PRs improving our stubs are welcome!

**Comment by AlexWaygood** [comment]
`aiofiles.tempfile` was added to typeshed's stubs in #7523. As @srittau says, further improvements are always welcome!
