### ISSUE TITLE
Add stubs for `docutils.parsers.rst.directives`

### ISSUE THREAD

**Issue by adamtheturtle** [python/typeshed#5755]
Checking the following with `mypy`:

```python
from docutils.parsers.rst import directives
```

gives:

```
src/sphinx_substitution_extensions/__init__.py:10: error: Module "docutils.parsers.rst" has no attribute "directives"; maybe "Directive"?
```

Relevant source code:

https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/parsers/rst/directives/

**Comment by AlexWaygood** [comment]
Fixed in #7256. (Further PRs to improve our docutils stubs are always welcome!)
