### ISSUE TITLE
Module has no attribute 'HTTPStatus'

### ISSUE THREAD

**Issue by aquilax** [python/typeshed#576]
When using with python3.5, mypy reports: Module has no attribute 'HTTPStatus'
Reference: https://docs.python.org/3/library/http.html#http.HTTPStatus

**Comment by gvanrossum** [comment]
Thanks for reporting this -- it looks like the stubs for the http package
are incomplete. Do you feel up to submitting a PR to address this? No
pressure, if you don't, we can add the "help wanted" label.

**Comment by aquilax** [comment]
I want to try. I'm pretty new in python land but that's how one learns.

**Comment by gvanrossum** [comment]
Great! Study some of the other stubs to see how things are generally done.
Sine HTTPStatus is new in 3.5, you need a version check of the form `if
sys.version_info >= (3, 5):` -- there are many occurrences of this already.
(Don't create new files in the 3.5 directory, that's an obsolete pattern.)
