### ISSUE TITLE
@retry decorator makes function untyped according to mypy

### ISSUE THREAD

**Issue by gitpushdashf** [python/typeshed#5786]
Using mypy 0.910's `--strict` mode, using the retry's module's `@retry` decorator will mark a function as untyped. I installed the decorator module and that's still the case.

types-retry 0.1.3

Possibly related: #5035

**Comment by hauntsaninja** [comment]
I think this might actually be the same thing as #5751

**Comment by gitpushdashf** [comment]
Interesting, thank you.

One other option for some may be to use tenacity instead of retry: https://github.com/jd/tenacity#tenacity

It's already typed and mostly compatible. retry isn't maintained anymore.

**Comment by JelleZijlstra** [comment]
This was likely #5751, which should not be an issue with newer releases of mypy. If there's something typeshed can do to fix this, leave a comment and reopen.
