### ISSUE TITLE
Let's rename "2.7 to "2"

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#579]
There's a "3" subdirectory which is the baseline for all supported Python 3 versions, i.e. 3.2 and up. Maybe we could also have a "2" subdirectory as the baseline for all supported Python 2 versions, i.e. 2.7 and up? The asymmetry bothers me, and I use pathname completion enough that I long for a shorter name here. @matthiaskramm Does pytype have any plans for supporting 2.6? I know mypy doesn't.

**Comment by matthiaskramm** [comment]
No major objections from my side. We don't plan to support 2.6.

The only advantage of 2.7 over 2 is that with 2.7 it's slightly more obvious that it's a Python version number.
