### ISSUE TITLE
requests 2.26.0 

### ISSUE THREAD

**Issue by kennylajara** [python/typeshed#5793]
`requests 2.26.0 ` has been released but `type-requests` is still on version 2.25.0 

I have not found any issue with the current `requests 2.26.0` and `type-requests 2.25.0`, but I think the version needs to be updated, just in case you didn't notice the new version has been released.

**Comment by gareth-j** [comment]
Yeah I'm getting a `error: Unexpected keyword argument "allowed_methods" for "Retry"` with Python 3.7. I think `method_whitelist` in the stub should be replaced with `allowed_methods`.

**Comment by hauntsaninja** [comment]
I think we're in good shape here? Feel free to open PRs if not
