### ISSUE TITLE
TypedDict for ciphers in ssl

### ISSUE THREAD

**Issue by gruebel** [python/typeshed#5807]
While working on improving the type hints in `ssl` (PR #5806) I found a missing method `SSLContext.get_ciphers()` https://docs.python.org/3.9/library/ssl.html#ssl.SSLContext.get_ciphers, but I'm not really sure on how to best approach it. Since the result dict changed with the OpenSSL version 1.1, I don't know how or if I should differentiate it.

I could, of course, create a `TypedDict` with `total=false` but this feels kind of weird, since I can't define which attributes are "optional". Or should I just define it as it should be since OpenSSL 1.1?

**Comment by gruebel** [comment]
Seeing [PEP644](https://www.python.org/dev/peps/pep-0644/) it feels like I could make two TypedDicts one without the `total` for Python 3.10+ and one with the flag set to `false`. Any thoughts?

**Comment by srittau** [comment]
I think just using the OpenSSL 1.1 version is fine. I think the newer releases even of older Python versions also support OpenSSL 1.1 by now.

**Comment by gruebel** [comment]
ok, thanks, will do that 😄
