### ISSUE TITLE
subprocess output not usable

### ISSUE THREAD

**Issue by tewe** [python/typeshed#581]
```
subprocess.run(something, stdout=subprocess.PIPE).stdout.decode()
```

results in

```
error: Some element of union has no attribute "decode"
```

because the stub uses Union[str, bytes] in case of the `universal_newlines=True` argument.

Unfortunately that argument is passed to run, which returns a CompletedProcess instance, which has the stdout attribute. So the stub would have to overload run and parametrise CompletedProcess?

**Comment by JukkaL** [comment]
A better type for `stdout` would likely be `Any`, since unions are a pain as return or attribute types. We can't overload based on values of boolean arguments.

**Comment by phouse512** [comment]
@JukkaL woops forgot to modify my commit message to close this automatically.  Can you close it?
