### ISSUE TITLE
requests: Cannot find reference 'packages' in '__init__.pyi'

### ISSUE THREAD

**Issue by stdedos** [python/typeshed#5811]
Hello there,

Is the solution offered to https://youtrack.jetbrains.com/issue/PY-49412#focus=Comments-27-4987466.0-0 as simple as it is shown? 😕 

I tried searching for `urllib3` across issues and PRs, but it seems that no-one has complained about those?!?

**Comment by srittau** [comment]
The following works with current mypy and types-requests:

```python
import requests
requests.packages.urllib3.disable_warnings()
```

The requests stubs also seem to be correct, as `requests/packages/__init__.pyi` exists, even in PyCharm's bundled typeshed stubs. This looks like a PyCharm bug to me.

**Comment by stdedos** [comment]
Glad to have verified that! Thanks 👍
