### ISSUE TITLE
Dictionary views "mapping" attribute in Python 3.10

### ISSUE THREAD

**Issue by lancelote** [python/typeshed#5812]
[bpo-40890](https://bugs.python.org/issue40890) introduced `mapping` attribute to views returned by `dict.keys()`, `dict.values()` and `dict.items()` in Python 3.10. It is not yet reflected in `typeshed`.

<img width="819" alt="mapping" src="https://user-images.githubusercontent.com/2500320/127282953-65d71358-eca6-4f88-a007-ad2af3b5d22d.png">

**Comment by hauntsaninja** [comment]
Fixed in #6312
