### ISSUE TITLE
Make `shelve.Shelf` a generic type

### ISSUE THREAD

**Issue by MapleCCC** [python/typeshed#5815]
It's more reasonable to write code as:

```python
import shelve
from shelve import Shelf

cache: Shelf[int] = shelve.open("~/.cache")
cache["apple"] = 1
```

than this:

```python
import shelve
from collections.abc import MutableMapping
from shelve import Shelve
from typing import cast

cache = cast(MutableMapping[str, int], shelve.open("~/.cache"))
cache["apple"] = 1
```

I suggest we change from:

```python
class Shelve(MutableMapping[Any, Any]):
```

to:

```python
class Shelve(MutableMapping[str, _VT]):
```

That being said, there could have been some nuances I didn't realize. Please don't hesitate to correct me.

**Comment by srittau** [comment]
I assume that this was typed when we didn't enforce generic parameters yet and the `[Any, Any]` was just added to make our tests pass when we changed that. At minimum, we should change the first parameter to `str`, but I think making the second parameter generic is worth a shot.

**Comment by MapleCCC** [comment]
@srittau Thanks for the feedback and information. Actually there are several more places in `shelve.pyi` that deserve some improvements. I am going to open a Pull Request to address them. Please feel free to correct me.
