### ISSUE TITLE
dict cannot receive a list

### ISSUE THREAD

**Issue by kasium** [python/typeshed#5819]
Hey,

the below works fine, but it seems like the stubs are incomplete:
```python
dict([x.split(",", maxsplit=1) for x in ["1,2", "2,3"]])
```
mypy:
```
x.py:1: error: Argument 1 to "dict" has incompatible type "List[List[str]]"; expected "Iterable[Tuple[<nothing>, <nothing>]]"
```

This code obviously only works if each sublist has only two entries.

**Comment by JelleZijlstra** [comment]
This is a duplicate of #2862, which points to python/typing#592. There's not much we can do about it in typeshed for now.

**Comment by kasium** [comment]
Thanks, can be closed
