### ISSUE TITLE
Type hint of requests(url, ...) doesn't accept URL value-types

### ISSUE THREAD

**Issue by Kache** [python/typeshed#5844]
Typeshed's [`requests.api`](https://github.com/python/typeshed/blob/475417fa97ff2815ec47490c8ed45de3279cb29b/stubs/requests/requests/api.pyi) type-hints `url` as `Union[Text, bytes]` even though [`requests` accepts any object as an url](https://github.com/python/typeshed/blob/475417fa97ff2815ec47490c8ed45de3279cb29b/stubs/requests/requests/api.pyi), passing it through `str()`. This means useful URL value types like [`furl`](https://pypi.org/project/furl/) won't type-match.

It's not uncommon for me to even use `pathlib.Path` to build URLs, which has a similar behavior.
Is there a way to resolve this without an extraneous `str()` nor `# typing.Any?`, like

```python
requests.get(str(url_type_obj))

url = url_type_obj  # typing.Any
requests.get(url)
```

How about any of:
- Set typeshed's `requests.api` stub for `url` to `Any`?
- Ask `furl` maintainer to subclass `Text`?
- Have `Path` subclass `Text`?
- Something else?

**Comment by JelleZijlstra** [comment]
I feel that using `requests.get(str(url_type_obj))` is the best solution. Setting the argument type to `Any` in the stub would throw away all type safety and make it impossible for typecheckers to catch mistakes like passing an `Optional[str]`. `Path` isn't a subclass of `str`, so we can't change its stub.

**Comment by Kache** [comment]
Hm, so no way of registering/declaring a type as "String-like", like implementing an interface, implementing a trait, or even Ruby's ducktype-y `to_str`/`to_ary` variants of `to_s`/`to_a`?

**Comment by JelleZijlstra** [comment]
Everything is convertible to a string in Python though. I'm not sure how you would represent "has a string representation that can sensibly be used as a URL" in the type system.

**Comment by Akuli** [comment]
In the past, it would have been useful to say "any object with meaningful `__str__`" in tkinter stubs. This is different from "any object with `__str__`", which as Jelle noted, means that any object is accepted. In tkinter, we ended up doing something like `str | float`.

One possible workaround for this would be to use a protocol that requires `.join()` to exist. It is a bit weird, but it would work: `str` and `furl.furl` both have a `join()` method, but None doesn't. There are no other methods in common with strings and `furl.furl` objects:

```python
>>> f=furl.furl('https://www.google.com')
>>> f
furl('https://www.google.com')
>>> f.
f.add(         f.fragmentstr  f.origin       f.query        f.strict
f.args         f.host         f.password     f.querystr     f.tostr(
f.asdict(      f.join(        f.path         f.remove(      f.url
f.copy(        f.load(        f.pathstr      f.scheme       f.username
f.fragment     f.netloc       f.port         f.set(         
>>> 
```

**Comment by Kache** [comment]
If the recommendation is to always `str()` the input, then the type system wouldn't catch `requests.get(str(actually_an_optional))` anyway, i.e. the type system is already unable to handle this scenario anyways, I'm thinking it doesn't help at all to only be unhelpfully noisy as well.

**Comment by srittau** [comment]
@Kache While that's true, it does catch involuntarily passing the wrong type, when not using `str()`, which is most likely the common case.

**Comment by Kache** [comment]
Hm, guess it's not truly "fixable" unless Python gets an standard url type to converge/build around.
