### ISSUE TITLE
"Any" type used in hasattr stub

### ISSUE THREAD

**Issue by ronf** [python/typeshed#5848]
When trying to improve mypy code coverage of type annotations, I noticed that any line which called hasattr() was flagged. Looking more closely, typeshed currently defines the stub for hasattr as:

```python
def hasattr(__obj: Any, __name: str) -> bool: ...
```

With Python 3, it seems like `__obj` could be declared as `object`, avoiding the call being flagged for not using explicit types. I did a quick test where I overrode the type annotation for hasattr locally, and it worked nicely. Is there a use case where this argument needs to be marked as `Any`?

**Comment by JelleZijlstra** [comment]
Yes, `object` would be better here. Feel free to submit a PR!

**Comment by ronf** [comment]
Thanks for the quick response! I have submitted this as PR #5874.
