### ISSUE TITLE
Best annotation for binary file-like object?

### ISSUE THREAD

**Issue by ronf** [python/typeshed#5876]
I've got some places in my code where I want to annotate a file-like object. From looking through existing typeshed annotations, would IO[bytes] be the right thing to use here? I'm thinking that would work for files, but probably not for objects that support the same set of methods such as sockets and pipes, since IO doesn't appear to be a Protocol.

The other option that seems like it might work are the SupportsRead and SupportsWrite protocols, though those only check for read() and write() methods and not close() or other common file methods.

On a related note, I see that connect_read_pipe() and connect_write_pipe() in the typeshed asyncio stubs currently use "Any" for the pipe argument. One of the things that led me to ask this is to see if there's something more specific I could suggest replacing that with.

Apologies in advance if this general question doesn't belong here. Is there a better forum for more general type annotation questions like this?

**Comment by srittau** [comment]
`IO` and its sub-classes `BinaryIO` and `StringIO` are semi-deprecated in typeshed. Generally, when returning file-like objects, it's better to return the concrete type, although for compatibility that often still needs to derive from `IO`. When accepting a file-like object, it best to use a tight protocol, possibly using one from `_typeshed`, or composing it from there.

**Comment by srittau** [comment]
We now have a discussions forum for typing-related questions: https://github.com/python/typing/discussions.

**Comment by ronf** [comment]
Thanks so much for the response, and for creating the new discussion forum! I'll definitely check that out and post future questions there, and I'll continue to focus on using protocols for this, which is where I was already leaning.
