### ISSUE TITLE
Type for argument of datetime.tzinfo.dst

### ISSUE THREAD

**Issue by dmoisset** [python/typeshed#589]
The stubs for the `datetime` module specify:

```python
class tzinfo:
    ...
    def dst(self, dt: Optional[datetime]) -> Optional[timedelta]: ...
```

But I've seen a lot of code written that assumes that `dt` is never None. That includes some of the official examples (like the `LocalTimezone` class in https://docs.python.org/3.6/library/datetime.html), although some other of the standard examples seem to check if the argument is `None` (see the `USTimeZone`, same documentation page).

I'm happy to submit the (trivial) patch but I couldn't find a clear spec detailing if `None` is actually a valid argument for this method.

**Comment by gvanrossum** [comment]
I looked in the implementation, and `time.dst()` calls `self._tzinfo.dst(None)`. I guess the examples in the docs are okay as long as you don't pass your tzinfo to `time()`, but the docs could be clearer that if you override this you should expect None. I think that's a Python doc bug though.

**Comment by dmoisset** [comment]
OK, in that case I'll close this. I opened http://bugs.python.org/issue28386
