### ISSUE TITLE
Add json types to _typeshed?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5910]
As this is an issue that pops up quite often and would be useful in a few places in typeshed as well: Should we add json types to `_typeshed`? As recursive types aren't possible at the moment, I'd suggest something simple like this:

```python
JsonObject = dict[str, Any]  # Any is Json
JsonArray = list[Any]  # Any is Json
Json = JsonObject | JsonArray | str | float | int | bool | None
```

This can be improved if recursive types become available and could be a useful placeholder if/when the stdlib gains a proper JSON type.

**Comment by srittau** [comment]
Cf. python/typing#182.

**Comment by hauntsaninja** [comment]
I don't think we should do this until we can do it in a way which works, since if users just go by the name it'll probably just lead to bad surprises for them. `_typeshed` isn't the most discoverable or user friendly thing anyway.

**Comment by JukkaL** [comment]
I wonder if we should have a third-party module on PyPI with only useful type definitions / aliases that can be more cleanly used in user code than importing from `_typeshed`. Unlike `typing_extensions`, these wouldn't introduce any new type system features -- it would all be just for convenience. And unlike `typing_extensions`, we could add arbitrary things not in `typing`.

**Comment by srittau** [comment]
No one is forced to use, but we can use it in our stubs. And it's an improvement over the status quo of just returning `Any`. Even just using `Json = Any` is an improvement, in my opinion.

**Comment by srittau** [comment]
@JukkaL That's actually a good idea. Just have a `types-typeshed` (or similar) module that can then be depended on by type checkers, third-party stubs and other packages.

**Comment by CobaltCause** [comment]
Fwiw, the following appears to work as expected with Pyright currently:

```python
JsonScalar = None | int | float | bool | str
JsonObject = dict[str, "JsonScalar | JsonList | JsonObject"]
JsonList = list["JsonScalar | JsonObject | JsonList"]
Json = JsonScalar | JsonList | JsonObject
```

I think this version allows all the possible cases and nothing else based on the conversion table [here](https://docs.python.org/3/library/json.html#encoders-and-decoders).

**Comment by hauntsaninja** [comment]
See also https://github.com/python/typing/issues/182#issuecomment-1320974824

I think we can close this, since we shouldn't add anything to typeshed. I'd accept a PR adding `JSON` and `JSON_ro` from that message to https://github.com/hauntsaninja/useful_types/
