### ISSUE TITLE
Move some types from _typeshed to typing_extensions

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5912]
I wonder if we should have a third-party module on PyPI with only useful type definitions / aliases that can be more cleanly used in user code than importing from `_typeshed`. Unlike `typing_extensions`, these wouldn't introduce any new type system features -- it would all be just for convenience. And unlike `typing_extensions`, we could add arbitrary things not in `typing`.

_Originally posted by @JukkaL in https://github.com/python/typeshed/issues/5910#issuecomment-896674008_

**Comment by hauntsaninja** [comment]
This is a little bit tricky if we're hoping to have stdlib types depend on this. E.g., we run into the same issues that caused us to pretend typing_extensions is part of the stdlib (what happens if users don't install `_typeshed`?).

**Comment by srittau** [comment]
Type checkers would need to depend on this package.

**Comment by hauntsaninja** [comment]
It could still lead to problems, e.g. with mypy's `--python-executable` option where it checks an environment other than its own, or if users pin a types-typeshed version that is incompatible with types-stdlib that gets shipped with a type checker.

**Comment by srittau** [comment]
Since I'd expect type checkers to depend on the correct types-typeshed version, pinning it by the user should conflict when pip installing, so this would lead to an impossible situation.

**Comment by MapleCCC** [comment]
+1 for this. It feels more sane to write `from typeutils import StrOrBytesPath` than writing `if TYPE_CHECKING: from _typeshed from StrOrBytesPath` every time.

**Comment by hauntsaninja** [comment]
Can we re-use typing_extensions for this? I feel like that could be less likely to cause confusion for users / typing_extensions already has things like `SupportsIndex`.

**Comment by srittau** [comment]
I think using typing-extensions would be the best idea.

**Comment by JelleZijlstra** [comment]
Yes, using typing-extensions makes sense to me. In the docs we should make a clear distinction between the backports and utilities parts of typing-extensions though.

**Comment by srittau** [comment]
We could put the custom types in a sub-package. `typing_extensions.ext` or so. We should also reconsider the typing-extensions version scheme in that case and probably decouple it from Python versions.

**Comment by tony** [comment]
`StrOrBytesPath` may be a good candidate for this, if it's stable: re conversations at https://stackoverflow.com/a/68027757/1396928

Could `StrOrBytesPath` also be compatible back to python 3.6? This type has been discussed since [PEP 519](https://peps.python.org/pep-0519/#provide-specific-type-hinting-support)

**Comment by AlexWaygood** [comment]
This now exists as https://github.com/hauntsaninja/useful_types
