### ISSUE TITLE
click: should _PathType allow pathlib.Path?

### ISSUE THREAD

**Issue by remexre** [python/typeshed#5917]
https://github.com/python/typeshed/blob/master/stubs/click/click/types.pyi#L73

https://github.com/pallets/click/blob/main/src/click/types.py#L767-L769

**Comment by JelleZijlstra** [comment]
The usage of the TypeVar dooesn't make a ton of sense to me since it's not in a generic class. Maybe it should instead use one of the aliases from `_typeshed`.

**Comment by Akuli** [comment]
We no longer have stubs for pallets projects (including click).
