### ISSUE TITLE
ZipFile.extractall signature change to accept `ZipInfo` members

### ISSUE THREAD

**Issue by rggjan** [python/typeshed#5935]
This seems wrong:
https://github.com/python/typeshed/blob/757d9622375d7375430938a4d7397e1b78fdf886/stdlib/zipfile.pyi#L143

ZipFile.extractall seems to support members as `str` as well as members as `ZipInfo`:
https://github.com/python/cpython/blob/3db42fc5aca320b0cac1895bc3cb731235ede794/Lib/zipfile.py#L1681

**Comment by srittau** [comment]
`extract()` already has the correct annotation. PR welcome!

**Comment by Nickedude** [comment]
I can give it a go! :)
