### ISSUE TITLE
collections.UserString should subtype str instead of Sequence[str]

### ISSUE THREAD

**Issue by ROpdebee** [python/typeshed#5957]
Since `collections.UserString` is meant to wrap around `str` transparently, I'd expect type checkers to allow it to be used in places were bare strings are expected, but they don't. Instead, they allow it to be used in places where sequences of bare strings are expected, which could lead to bugs.

```python
from collections import UserString
from collections.abc import Sequence

class Spam(UserString):
    ...

def takes_str(s: str) -> None:
    ...

def takes_seq(s: Sequence[str]) -> None:
    ...

takes_str(Spam('eggs'))  # mypy: error: Argument 1 to "takes_str" has incompatible type "Spam"; expected "str"
takes_seq(Spam('eggs'))  # fine, but shouldn't be
```

I think it should subtype `str` rather than `Sequence[str]` in the stub. AFAICT, the only reason it's inheriting from `Sequence` in cpython is for the mixin methods. It could also substantially simplify the stub by removing the need to redefine some `str` methods that don't depend on the exact `UserString` type.

Happy to submit a PR, just want to make sure I'm not misinterpreting something first.

**Comment by Akuli** [comment]
Stubs should generally reflect what the runtime is doing, as lying in the stubs tends to result in weird problems. For example, consider this code, taken from the implementation of `UserString`:

```python
        if isinstance(seq, str):
            self.data = seq
        elif isinstance(seq, UserString):
            self.data = seq.data[:]
        else:
            self.data = str(seq)
```

If `UserString` would inherit from `str`, mypy would complain about unreachable code, because the initial `if isinstance(seq, str)` would also include the second case.

If there was a type that represents an object that can be sanely converted to a string, but is not required to really be a string, then the correct fix would be to include `UserString` in that. But a type like that doesn't exist. It has caused other problems in the past, such as #5844 and #5076. Requiring `__str__()` to exist doesn't work, because any Python object has a `__str__()` method, inherited from `object` if not explicitly defined.

**Comment by srittau** [comment]
In addition to what @Akuli wrote, the following code would fail at runtime, but not at type check time:

```python
def foo(x: str) -> None:
    if not isinstance(x, str):
        raise TypeError("x must be a str")
    ...

foo(UserString(""))
```

**Comment by ROpdebee** [comment]
Thanks for providing examples that I overlooked. I've realised now that the problem goes deeper than what I initially thought. `UserString` isn't a true subtype of `str`, but it is a structural subtype, and mypy doesn't recognise that. I don't think there's currently any way to make it clear that it is a structural subtype, other than defining some sort of `StringLike` protocol. Just declaring that it can be converted into a meaningful string doesn't do `UserString` justice, since it implements the whole `str` interface. Alternatively, the `UserString` type could just subclass `str` directly in the implementation, which would be the more sensible thing to do for (what I believe to be) the class' intent.

However, looking deeper into this, I found that [`UserString`'s use has been discouraged at least as far back as 2.6, possibly 2.2/2.3](https://docs.python.org/2.6/library/userdict.html#module-UserString), and [it doesn't seem like anyone wants to touch it anymore](https://bugs.python.org/issue39944#msg364001), so any substantial effort wouldn't be worthwhile.

Thanks all!

**Comment by srittau** [comment]
@ROpdebee Having a `StringLike` protocol would be the "correct" solution. On the other hand that means that nearly all instances of `str` would need to be replaced with it. Especially considering the status of `UserString`, I don't think this would be worthwhile. A more general solution would be to have a way to say "this type fulfills the protocol of that other type, but isn't a subclass" in the type system (similar to what `abc.register()` does for ABCs). But that is of course a much larger issue.
