### ISSUE TITLE
Enable auto-merge?

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#5978]
We've been using auto-merge at work and it's pretty nice. You hit the merge button whenever you want and when tests pass, it'll merge: https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by JelleZijlstra** [comment]
Sounds useful! I often find myself waiting for CI to succeed.

**Comment by hauntsaninja** [comment]
Do you have permission to do this? https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-auto-merge-for-pull-requests-in-your-repository#managing-auto-merge

**Comment by JelleZijlstra** [comment]
I do, but let's give @srittau and @Akuli some time to weigh in before we make a change.

**Comment by srittau** [comment]
I'm fine with trying this. Sometimes, I want the input of another developer, though. Did requesting a review disable auto merge?

**Comment by hauntsaninja** [comment]
Given that we don't require approve reviews to merge, requesting review will not disable auto-merge.

However, if you want the input of another developer, I just wouldn't hit auto-merge. Also, if someone else hits auto-merge and the PR hasn't been merged yet, anyone else with write permission can turn off auto-merge for the PR.

**Comment by Akuli** [comment]
I'm fine with trying this. I generally don't like if the PR author has to learn a complex repo-specific process to follow in detail, but this seems like something the PR author can ignore.

**Comment by srittau** [comment]
Enabled.
