### ISSUE TITLE
typing.final supports properties

### ISSUE THREAD

**Issue by twoertwein** [python/typeshed#5984]
[PEP 591](https://www.python.org/dev/peps/pep-0591/): "The method decorator version may be used with all of instance methods, class methods, static methods, and properties."

```py
from typing import final

class Test:
    @final
    @property
    def bar(self):
        return "bar"
```

But `typing.final` is currently annotated as requiring a `Callable`:
https://github.com/python/typeshed/blob/5f77310418136a85a41157758e2620dfb70ad6b5/stdlib/typing.pyi#L54

pyright rejects the above code since it is using the typeshed annotations (mypy accepts it for some reason).
```
error: Argument of type "property" cannot be assigned to parameter "f" of type "_F@final" in function "final"
    Type "property" is incompatible with bound type "(*args: Any, **kwargs: Any) -> Any" for type variable "_F@final"
      Type "property" cannot be assigned to type "(*args: Any, **kwargs: Any) -> Any" (reportGeneralTypeIssues)
```

xref https://github.com/microsoft/pyright/issues/2242#issuecomment-908576390

**Comment by JelleZijlstra** [comment]
Thank you! We should just type it with an unconstrained TypeVar.
