### ISSUE TITLE
Third-party stubs: allow three-element version numbers

### ISSUE THREAD

**Issue by srittau** [python/typeshed#5992]
For some calver packages that use a YYYY.MM.DD format it makes sense to allow three-element versions in `METADATA.toml`'s `version` field, meaning four-element versions in the generated types packages (e.g. `types-foo 2021.08.21.3`). I think we should allow this.

Cc @JukkaL

**Comment by srittau** [comment]
`certifi` is one of the stubs where this is needed. I though there was another one, but I can't remember what it was and can't find it anymore.

**Comment by hauntsaninja** [comment]
Grepping years says maybe pytz?

**Comment by srittau** [comment]
`pytz` seems to use some calver variant, but only two components.
