### ISSUE TITLE
Should csv.DictWriter require fieldnames to be a Sequence?

### ISSUE THREAD

**Issue by PeterJCLaw** [python/typeshed#5993]
I realise that according to [the docs](https://docs.python.org/3/library/csv.html#csv.DictWriter) the `fieldnames` parameter to `DictWriter` should be a sequence, however code which doesn't actually pass a sequence (instead perhaps passing `dict.keys()`) does in fact work and may have a well-defined key ordering.

Should the typeshed record what actually works or closely match the docs?
(Should the docs be updated?)

**Comment by srittau** [comment]
Generally, we prefer to follow the implementation, not the docs in typeshed.
