### ISSUE TITLE
Specify how to annotate variable types

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#6]
We should probably have a single convention for attribute and module-level variable annotations that would at least be recommended (even if other ways would also work).

Here are some potential approaches:

* `x = 0`, `x = ''`, etc. (at least for built-in types)
* `x = Undefined(int)`
* `x = Undefined # type: int`
* `# var x: int` (a proposal for PEP 484, still under discussion)
* `x = ClassName()`

**Comment by JukkaL** [comment]
Another option:

* `x = None # type: int` (the type will be `int`, not `Optional[int]`)

**Comment by JukkaL** [comment]
Yet another option:

* `x = cast(int, None)`

**Comment by vlasovskikh** [comment]
The PEP now allows specifying the type of a variable without specifying its value:

```python
x = ...  # int
```

For variables with known default values we could use:

```python
x = 42  # int
```

**Comment by gvanrossum** [comment]
The PEP picked a syntax. It is used in many stubs, and mypy supports it. So I think this issue is fixed.
