### ISSUE TITLE
Pillow stub fromarray wrong declared

### ISSUE THREAD

**Issue by Erhie** [python/typeshed#6027]
Asking 
https://github.com/microsoft/pylance-release/issues/1798
Jake Bailey means it should be answered here.

But I had success by uninstall and newly installed Pillow and 
purge  in ...\.vscode\extensions\ms-python.vscode-pylance-2021.9.1\dist\typeshed-fallback\stubs\Pillow
and now there is no warning for this issue.

Erhy

**Comment by srittau** [comment]
This is deliberate. `mode` only accepts the values specified in the `Literal` value. If your code uses a variable for the mode parameter, I suggest to annotate it with `PIL.Image._Mode`. This could require quoting if using older Python versions and not using `from __future__ import annotations`. We also have a help forum for further questions: https://github.com/python/typing/discussions
