### ISSUE TITLE
[unittest] Argument 1 to "skip" has incompatible type Callable[[Any], Any]; expected "str"

### ISSUE THREAD

**Issue by Daenyth** [python/typeshed#603]
Doing the following is valid:

```python
class TestFoo(unittest.TestCase):
    @unittest.skip
    def test_foo(self):
        pass
```

mypy complains `error: Argument 1 to "skip" has incompatible type Callable[[Any], Any]; expected "str"`

The `str` is valid but optional.

**Comment by gvanrossum** [comment]
Are you *sure* that's valid (and doesn't just work by accident)? Neither the docs nor the source for unittest.skip() look like that form is intended. Maybe mypy just found a bug in your code!

**Comment by Daenyth** [comment]
You're quite right!

<insert cheesy "Thanks, mypy!" gif here>
