### ISSUE TITLE
tzlocal: api change since version 3.0

### ISSUE THREAD

**Issue by karlicoss** [python/typeshed#6038]
see [changelog]( https://github.com/regebro/tzlocal/blob/9a3fef832f759770f850acbfe695719a8c891da1/CHANGES.txt#L33), now it returns `ZoneInfo` object (instead of `pytz.BaseTzInfo`)

https://github.com/python/typeshed/blob/master/stubs/tzlocal/tzlocal/__init__.pyi

**Comment by AlexWaygood** [comment]
The latest version of `tzlocal` includes inline types. The `types-tzlocal` is now marked as obsolete, and a notice on PyPI recommends users not to install it; we'll be removing it from typeshed in a few months
