### ISSUE TITLE
Why is the `__val` argument to the `Generator.throw()` method annotated as `BaseException | object` instead of just `object`?

### ISSUE THREAD

**Issue by MapleCCC** [python/typeshed#6040]
Sorry if I miss something. In my understanding of the type hinting system, `BaseException | object` is just reduced to `object`. But below line shows that the `__val` argument of the `Generator.throw()` method is annotated as `BaseException | object`. I wonder if this is intended or just a typo?

https://github.com/python/typeshed/blob/e4c2c0f3021abac1078854da92a9ec14848b32f4/stdlib/typing.pyi#L208

**Comment by srittau** [comment]
This was introduced in #4253 by @milapsheth. Semantically this is indeed the same, but it could theoretically make a difference for syntax highlighters etc. or to show that this is usually a `BaseException`, but can be any other object, but I'm stabbing in the dark here. (I also wonder whether `Any` might be more appropriate, since the expected type probably depends on the `__typ` argument.)

**Comment by JelleZijlstra** [comment]
I guess Any could work too, but I'd prefer to stick with `object` in the spirit of avoiding `Any`. @MapleCCC  was there a concrete use case motivating this issue?

**Comment by milapsheth** [comment]
Sorry for the delayed response. As @srittau suggested, the reason I had it as such was for readability since the two are equivalent and because the original type hint was just `BaseException`. I share a preference of avoiding `Any` if possible, but don't have any strong opinions.

**Comment by MapleCCC** [comment]
Sorry it's been a while and I couldn't recall the exact use case that triggered this issue. I opened the issue because I thought a `Union` that contains `object` is always equivalent to simply `object`, hence rendering the `Union` redundant.

As @srittau and @milapsheth clarified, although it's redundant in the use case of static type checkers, it could still be useful for documentation and readability.

With these clarifications present, this issue is okay to be closed now.
