### ISSUE TITLE
requests.packages.urllib3.exceptions stubs are incomplete (e.g. SNIMissingWarning is missing)

### ISSUE THREAD

**Issue by rogalski** [python/typeshed#6054]
`from requests.packages.urllib3.exceptions import SNIMissingWarning` is valid import.
It's part of  module public API: https://github.com/urllib3/urllib3/blob/d8eabf304190c62766e05c79ef44be7ff94cfbcb/src/urllib3/exceptions.py#L260

Yet mypy complains: `error: Module "requests.packages.urllib3.exceptions" has no attribute "SNIMissingWarning"  [attr-defined]`

**Comment by srittau** [comment]
Any contributions are welcome!

**Comment by srittau** [comment]
We have decided to remove the `requests.packages.urllib3` sub-package and are instead concentrating on creating proper `urllib3` stubs.
