### ISSUE TITLE
`random.Random.getvalue` and `random.Random.setvalue` are unduly opinionated about their types and ill-suited for subclassing

### ISSUE THREAD

**Issue by posita** [python/typeshed#6063]
If i understand [the docs](https://docs.python.org/3/library/random.html) correctly, this …

> Class [`Random`](https://docs.python.org/3/library/random.html#random.Random) can also be subclassed if you want to use a different basic generator of your own devising: in that case, override the `random()`, `seed()`, `getstate()`, and `setstate()` methods. Optionally, a new generator can supply a `getrandbits()` method — this allows [`randrange()`](https://docs.python.org/3/library/random.html#random.randrange) to produce selections over an arbitrarily large range.
>
> …
>
> `random.`**`getstate`**`()`
> Return an object capturing the current internal state of the generator. This object can be passed to [`setstate()`](https://docs.python.org/3/library/random.html#random.setstate) to restore the state.
> 
> `random.`**`setstate`**`(`_`state`_`)`
_state_ should have been obtained from a previous call to [`getstate()`](https://docs.python.org/3/library/random.html#random.getstate), and [`setstate()`](https://docs.python.org/3/library/random.html#random.setstate) restores the internal state of the generator to what it was at the time [`getstate()`](https://docs.python.org/3/library/random.html#random.getstate) was called.

… strongly suggests that the return value of `getstate()` (and corresponding argument to `setstate()`) should be opaque and treated as implementation specific. However, typeshed [seems to want to enforce that they should be `Tuple`s](https://github.com/python/typeshed/blob/ee487304d76c671aa353a15e34bc1102bffa2362/stdlib/random.pyi#L12-L13).

This leads to warnings for subclasses who, e.g., capture state as `bytes` or a `dict`. E.G.:

```
…/foo.py:57: error: Return type "_RandState" of "getstate" incompatible with return type "Tuple[Any, ...]" in supertype "Random"
…/foo.py:57: error: Return type "_RandState" of "getstate" incompatible with return type "Tuple[int, ...]" in supertype "Random"
```

(Not sure what that second warning is or where it came from.)

**Comment by hauntsaninja** [comment]
Seems like another use case for defaulted generics.

**Comment by srittau** [comment]
For now, the best we could do is to use `Any` to prevent false positives? But in this particular case, for now, I believe we should keep the stubs as is, and rely on users overriding these methods to use `# type: ignore`.

**Comment by posita** [comment]
How would others define an interface with an opaque state that could be emitted/passed back? Or is that the point of "defaulted generics" and you want to preserve specific type checking for the standard library **_implementation_** until that arrives?

Just curious, but if the state is supposed to be opaque (I'm assuming even for the standard library), why preserve type checking around implementation details that leave and return via `getstate`/`setstate`? Aren't those properly accounted for inside the implementation/tests rather than public interfaces?

**Comment by srittau** [comment]
An opaque state could be defined in several ways: Either using the concrete type as done here. But a better way would probably be to use `NewType`, which forced the opaque type to match, without necessarily revealing its internals. This doesn't help when overriding the class, though.

**Comment by posita** [comment]
Right, so why not keep implementation typing separate from interface typing?

``` python
from collections.abc import Mapping as MappingC
from typing import Dict, Mapping, NewType, Protocol
_OpaqueT = NewType("_OpaqueT", object)
class Foo(Protocol):
  def getblob(self) -> _OpaqueT:
    ...
  def setblob(self, blob: _OpaqueT) -> None:
    ...

class FooImpl(Foo):
  def __init__(self):
    self._blob: Dict = {}
  @property
  def foo_impl_blob(self) -> Mapping:
    return self._blob
  def getblob(self) -> _OpaqueT:
    return _OpaqueT(self._blob)
  def setblob(self, blob: _OpaqueT) -> None:
    assert isinstance(blob, MappingC)
    self._blob = dict(blob)

foo = FooImpl()
blob: _OpaqueT = foo.getblob()
foo.setblob(blob)
assert "missing" not in foo.getblob()  # type: ignore  # Unsupported right operand type for in ("_OpaqueT")
assert "missing" not in foo.foo_impl_blob  # totally cool
```

**Comment by srittau** [comment]
As this is not something we can express in typeshed right now, but could be improved if typing improves, I've marked this as inexpressable and am closing this per our policy. This can be revisited if typing improves.
