### ISSUE TITLE
Type check failed for `inspect.Paramter.empty`

### ISSUE THREAD

**Issue by yanyongyu** [python/typeshed#6068]
`inspect.Paramter.empty` is class but not instance

merged pr https://github.com/python/typeshed/pull/6020 suggested that `empty` is an instance for class `_empty`

https://github.com/python/typeshed/blob/2217ac8a8c7004baad94a5adcb0d503d985eaa21/stdlib/inspect.pyi#L175

## Linked issue

more static type check detail canbe found here

https://github.com/microsoft/pylance-release/issues/1872

**Comment by hauntsaninja** [comment]
Thanks for reporting! Seems like people discussed `empty = _empty`, but then the wrong change was made. PR welcome!

**Comment by yanyongyu** [comment]
i've just made a pr to resolve this!
