### ISSUE TITLE
`open()` overloads mixes `typing.IO` and `io.IOBase` hierarchies

### ISSUE THREAD

**Issue by aucampia** [python/typeshed#6076]
Currently the overloads for the [`open` builtin](https://github.com/python/typeshed/blob/2217ac8/stdlib/builtins.pyi#L1164-L1249) uses `io.IOBase` based types for specific cases (specifically `io.{TextIOWrapper,FileIO,BufferedRandom,BufferedWriter,BufferedReader}`), but for fallbacks it uses `typing.IO` based types (specifically `typing.{BinaryIO,IO[Any]}`).

The same is the case for [`Path.open`](https://github.com/python/typeshed/blob/2217ac8/stdlib/pathlib.pyi#L89-L143) and [`Traversable.open`](https://github.com/python/typeshed/blob/2217ac8/stdlib/importlib/abc.pyi#L104-L163).

This would maybe not be a problem if the `io.IOBase` classes were considered subclasses, subtypes or implementations of `typing.IO`, but this is not the case. This can maybe be considered a problem on it's own, but it would still seem better to use a consistent approach for typing.

The practical problem that this causes is that functions that should deal with all result from open will have to accept both `typing.IO` and `io.IOBase`.

Written for commit 2217ac8, but can also be seen in typeshed included with mypy 0.910.

**Comment by aucampia** [comment]
Given this, I would assume the right approach is to rather move to typing.IO hierarchies then: https://github.com/python/typeshed/issues/6077

**Comment by srittau** [comment]
All types returned by `open()` derive from `typing.IO` (in the stubs, at least). It should be enough to annotate fields using `typing.IO[typing.Any]`. Are there any examples where this fails (and that are not related to mypy's open plugin)?

**Comment by aucampia** [comment]
The reason why this all came up, I'm trying to type functions that should accept things returned by open, and then would pass them onto TextIOWrapper, and I was typing them using `io.IOBase` heirarchy, but if I should not do that, then problem solved. I just did not know I should not do that. Apologies for the issue spam. I think the documentation could be clearer, but I understand now.

**Comment by aucampia** [comment]
Closing this issue as all returned types do derive from typing.IO, and typing.IO should be used instead of `io.*IOBase` when typing things.

**Comment by srittau** [comment]
@aucampia I agree. The typing documentation is lacking. I added better documentation for I/O as a todo item for our not-yet-written Best Practices document: python/typing#851.
