### ISSUE TITLE
No version git tags

### ISSUE THREAD

**Issue by kloczek** [python/typeshed#6092]
According to https://pypi.org/project/types-Markdown/ latest version is 3.3.3 but here there is no even single git tag.
Is it popssible to add `3.3.3` tag for at least last version?

**Comment by kloczek** [comment]
It would be good to add as well tests/ directory to sdist tar ball.

**Comment by JelleZijlstra** [comment]
Git tags wouldn't be easy to add here because the releases are created automatically, and we create releases for many pypi distributions from this repo. I guess we could have tags prefixed with the package name, though.

**Comment by srittau** [comment]
Adding tags would be complicated, as the stub uploader had to somehow set them on this repository. Also, there would be a ton of tags. @kloczek What's your use case?

**Comment by kloczek** [comment]
Closing.
I see that I was wrong.
Sorry.
