### ISSUE TITLE
Hacktoberfest 2021

### ISSUE THREAD

**Issue by gruebel** [python/typeshed#6100]
Hi,

I just wanted to ask, if `typeshed` will join Hacktoberfest this year?

**Comment by srittau** [comment]
I don't mind. Last year was slightly successful, but there were technical issues on Hacktoberfest's side. Is there documentation on what we need to do? See #4631 for last year's issue.

**Comment by gruebel** [comment]
it is again opt-in and you need to add `hacktoberfest` as a project topic.

from the official docs:
_A repository/project is considered to be participating in Hacktoberfest if the 'hacktoberfest' topic is present and is accepting public contributions via pull requests. An individual pull request can also be opted-in directly by adding the 'hacktoberfest-accepted' label._

**Comment by srittau** [comment]
I have now added the topic. Let's keep this open as a reminder to remove the topic again in November.

**Comment by Akuli** [comment]
The topic can now be removed, but apparently I don't have the permissions to do so.

**Comment by JelleZijlstra** [comment]
I removed it.
