### ISSUE TITLE
Standard lib sys.ps1 and sys.ps2 are mistyped

### ISSUE THREAD

**Issue by Lattay** [python/typeshed#6121]
From [the doc](https://docs.python.org/3/library/sys.html#sys.ps1), `sys.ps1` and `sys.ps2` can be any object that implements the `__str__` method.
However, the [stub](stdlib/sys.pyi) simply declare these two as `str`, not supporting the documented behaviour.

I think that there should be some `SupportsStr` protocol.
```python
# Taken from typing.SupportsInt
@runtime_checkable
class SupportsStr(Protocol):
    """An ABC with one abstract method __str__."""
    __slots__ = ()

    @abstractmethod
    def __str__(self) -> int:
        pass
# Fix to sys.pyi
ps1: SupportStr
ps2: SupportStr
```

Is this something that would be accepted in here? I would quickly do the PR is so.

**Comment by Akuli** [comment]
Every Python object has `__str__`, so requiring it in a protocol doesn't make sense. See also https://github.com/python/typeshed/issues/5844#issuecomment-892868682

I think `object` might be good for this. Unlike `Any`, using `object` would mean that you get an error for `print(sys.ps1.upper())`, which is not guaranteed to work if `sys.ps1` can be any object that has a `__str__` method (that is, any object whatsoever).
