### ISSUE TITLE
`types.coroutine` returns `CoroutineType` but it doesn't????

### ISSUE THREAD

**Issue by KotlinIsland** [python/typeshed#6126]
```py
from types import CoroutineType, coroutine

coro = coroutine(print)

print(isinstance(coro, CoroutineType))  # False
print(coro.cr_await)  # error
```
But no type errors?

**Comment by ajkaijanaho** [comment]
types.coroutine is incorrectly hinted to be returning a coroutine. In reality it returns a function:

```Python
import asyncio
import types
from typing import Generator

@types.coroutine
def foo() -> Generator[None, None, None]:
    print("1")
    yield
    print("2")

print(type(foo)) # <class 'function'>
print(type(foo())) # <class 'generator'>; pylance error Object of type "CoroutineType[Any, Any, Any]" is not callable
asyncio.run(foo()) # prints 1 and 2; pylance error Object of type "CoroutineType[Any, Any, Any]" is not callable
asyncio.run(foo) # raises ValueError: a coroutine was expected, got <function foo at 0x00000277484A3E20>
```

**Comment by sobolevn** [comment]
I guess this happens because `types.coroutine` can work with literally any function.

Docs: https://docs.python.org/3/library/types.html#types.coroutine

> If gen_func is a generator function, it will be modified in-place.
> If gen_func is not a generator function, it will be wrapped. If it returns an instance of collections.abc.Generator, the instance will be wrapped in an awaitable proxy object. All other types of objects will be returned as is.

Example:

```python
>>> from types import coroutine
>>> a = coroutine(int)
>>> a(0)
0
```

**Comment by KotlinIsland** [comment]
So what about something like:
```py
_Fn = TypeVar("_Fn", bound=Callable[..., object])
_R = TypeVar("_R")
_P = ParamSpec("_P")

# it's not really an Awaitable, but can be used in an await expression, real type: Generator & Awaitable
@overload
def coroutine(func: Callable[_P, Generator[_R, Any, Any]]) -> Callable[_P, Awaitable[_R]]: ...
@overload
def coroutine(func: _Fn) -> _Fn: ...
```

**Comment by sobolevn** [comment]
It looks fine! 

But, `ParamSpec` is not yet supported by `mypy`.
However, there are some use cases in `typeshed` already: https://github.com/python/typeshed/search?q=paramspec

**Comment by KotlinIsland** [comment]
Thanks :)
btw, is there a type for "usable in await" but doesn't have `__await__`? for this scenario.
