### ISSUE TITLE
`logging.dictConfig` to accept `TypedDict` as an argument

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6131]
Currently `dictConfig` accepts `Dict[str, Any]` as an argument.
https://github.com/python/typeshed/blob/3c58736d01b4befa4499e481e87bd7e8458dac20/stdlib/logging/config.pyi#L22

But, there's a clearly defined schema for its argument.
Docs: https://docs.python.org/3/library/logging.config.html#logging-config-dictschema

Maybe we can try to support it? It is really easy to mess things up in this long and nested dict.
The only downside is that `dictConfig()` might not accept some valid dicts with statically unknown shape.

**Comment by srittau** [comment]
Sounds like a good idea to me.
