### ISSUE TITLE
`logging.LogRecord` does not have a `message` attribute

### ISSUE THREAD

**Issue by dave-shawley** [python/typeshed#6132]
The stub for `LogRecord` includes both the `msg` and `message` attributes but `message` is actually added as a [side effect of `logging.Formatter.format`](https://github.com/python/cpython/blob/6811fdaec825bd6ab64e358a4b480108f5634d2d/Lib/logging/__init__.py#L681).

https://github.com/python/typeshed/blob/3c58736d01b4befa4499e481e87bd7e8458dac20/stdlib/logging/__init__.pyi#L329

I just ran into this today when writing a log filter and it surprised me.  I should be able to put together a PR for this but I wanted to make sure that it was flagged as an issue.

**Comment by dave-shawley** [comment]
Hmm... maybe this is an edge case but the annotation caused PyCharm to autocomplete it which ultimately caused a defect since I was doing `record.message += 'other stuff'` in  a logging filter.  Would a PR to remove the attribute be accepted?

**Comment by srittau** [comment]
As this has not been added explicitly, we can try to remove it. We should keep a comment, though.
