### ISSUE TITLE
Might be a wrong type annotation?

### ISSUE THREAD

**Issue by Jarvx** [python/typeshed#6136]
I  noticed that the **__call__**  function in the class  **AuthBase** has been given a return type of **models.PreparedRequest**. However, I could not even find a return statement or yield statement in its source code 

Stub file location: https://github.com/python/typeshed/blob/ee31999cafa7a7bcbfcb1a18210f388e660b0ede/stubs/requests/requests/auth.pyi#L15

Source of __call__ function:

https://github.com/psf/requests/blob/94f9f7357e50f6accf1ec1a87fd3223981e68003/requests/auth.py#L72

**Comment by JelleZijlstra** [comment]
The implementations (right below what you linked) all `return r`, so this seems right to me.

**Comment by Jarvx** [comment]
Hi, thanks for the quick response.  Do you mean the **__call__**  in  **HTTPBasicAuth** class?

For the **AuthBase**, the **__call__** has no return statement (line 76, auth.py)  but the stub file (line 15, auth.pyi) has a return type.

**Comment by JelleZijlstra** [comment]
That call is abstract and just raises NotImplementedError.

**Comment by Jarvx** [comment]
Many thanks for the response!

I understand this is an abstract function and will not be directly invoked.  My question is this function supposed to have a return type annotation in the stub file?

**Comment by JelleZijlstra** [comment]
Yes, because it's clear from the implementation that that's what classes inheriting from it are supposed to return.

**Comment by Jarvx** [comment]
So in this way, it's actually enforcing all the inheriting functions have the same return type. Thanks for explaining to me!
