### ISSUE TITLE
Specific default values missing in builtins.pyi

### ISSUE THREAD

**Issue by aivarannamaa** [python/typeshed#6145]
For example in `print`, the default values for `sep` and `end` parameters are known, but builtins.pyi uses ellipsis: https://github.com/python/typeshed/blob/76b1f63ac253759f875949dd7f157fe049d05d95/stdlib/builtins.pyi#L1252

Is this a specific policy or should I make a PR for fixing these?

I understand that Pylint and MyPy wouldn't benefit from precise default values, but stubs are also used for providing inline documentation and calltips in IDE-s.

**Comment by fismoilov20** [comment]
> 

Where is it? 
In Python website guidelines?
