### ISSUE TITLE
Fill in stdlib/3/posix.pyi

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#616]
There's a stub file for posix in PY3 but it's basically empty. We need help filling it in. The PY2 version is much better, maybe it can be used as a starting point (but please double check that APIs still exist before copying them).

**Comment by phouse512** [comment]
@gvanrossum is there a piece of documentation that you could point me to for this?  I've only been only to find this so far but it didn't have much:

https://docs.python.org/3/library/posix.html

Either way, I'll start working on this issue.
