### ISSUE TITLE
tkinter Treeview item() method missing Literal[""] in values argument

### ISSUE THREAD

**Issue by melassa** [python/typeshed#6177]
Example:
```
    x = tree.item('iid', 'values')
    tree.item('iid', values=x) # mypy error
```
Mypy:
`Argument "values" to "item" of "Treeview" has incompatible type "Union[Literal[''], Tuple[Any, ...]]"; expected "Union[List[Any], Tuple[Any, ...]]"`

item() define 'values' as:
  `values: tkinter._TkinterSequence[Any] = ...,`
should be:
  `values: tkinter._TkinterSequence[Any] | '' = ...,`

**Comment by Akuli** [comment]
Maybe all `_TkinterSequence`s should also allow empty strings. Sometimes tkinter returns them randomly instead of other empty sequences.

**Comment by Akuli** [comment]
I like the idea of getting rid of `_TkinterSequence`, replacing it with `list[Foo] | Tuple[Foo, ...]` everywhere. It should make the stubs easier to read, especially for people who haven't worked on them much. Even really long annotations become simpler: compare

```
displaycolumns: str | tkinter._TkinterSequence[str] | tkinter._TkinterSequence[int] | Literal["#all"] = ...
```

and

```
displaycolumns: str | list[str] | Tuple[str, ...] | list[int] | Tuple[int, ...] | Literal["#all"] = ...
```
