### ISSUE TITLE
Python 3.6 EOL (not before July 2022)

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#6189]
We're coming close to Python 3.6 EOL. Last year we were pretty prompt about dropping support for Python 3.5, dropping support within a month or two of EOL. I think I'd like us to be a little slower this time round (hence my posting of this in advance of anyone making a PR).

My impression is that Python 3.6 is still widely used. pypistats a couple packages says on the order of 20%. It's also the default on Ubuntu 18.04. Waiting six months would be in line with our removal policy for third party stubs, so that seems like a number we could default to, but curious if people have opinions.

**Comment by srittau** [comment]
I have updated the title with the "support until" date and added the "removal" label (which is not 100% appropriate, but close enough).

**Comment by KotlinIsland** [comment]
@hauntsaninja Could you please link to the PyPI Stats page you mentioned in the OP, thanks.

**Comment by hauntsaninja** [comment]
Oh I wasn't aware of https://pypistats.org/packages/__all__ , that's nice.

I have no idea which specific packages I looked at, but if you made me guess:
https://pypistats.org/packages/typing-extensions 
https://pypistats.org/packages/mypy
https://pypistats.org/packages/requests
https://pypistats.org/packages/setuptools
https://pypistats.org/packages/numpy

mypy has the least 3.6 usage of these at ~10%, others go up to ~20%

**Comment by AlexWaygood** [comment]
I'm pinning this issue, since our tentative removal date is coming up in around a month now.

**Comment by srittau** [comment]
As July is approaching fast: Are there any blockers for removing Python 3.6 support? I get the feeling that Python 3.6 support is becoming slightly annoying to maintain, so it will be a plus if we can remove it.
