### ISSUE TITLE
`type` stub is missing `__class_getitem__`

### ISSUE THREAD

**Issue by dzshn** [python/typeshed#6218]
At least as of python 3.9, `type[int]` returns a `GenericAlias`, but this does not seem to be implemented on `builtins.pyi` or at least with mypy specifically:

```sh
$ mypy -c 'type[int]'
<string>:1: error: Value of type "Type[type]" is not indexable
```

(p.s. I am not entirely sure if this is with mypy or typeshed, correct me if I'm wrong!)

**Comment by dzshn** [comment]
if I understood correctly, this should be a simple fix, right? on lines [`class type(object):`](https://github.com/python/typeshed/blob/f4143c40e85db42dc98549e09329e196668395ee/stdlib/builtins.pyi#L132) add:

```py
    if sys.version_info >= (3, 9):
        def __class_getitem__(cls, item: Any) -> GenericAlias: ...
```

**Comment by JelleZijlstra** [comment]
We recently discussed this in #6205. `type` does not in fact implement `__class_getitem__`.

**Comment by dzshn** [comment]
oh, I totally missed that! should this be moved to mypy's repo then?
