### ISSUE TITLE
New style unions and special forms

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6219]
Today we got a bug report in `mypy`, that `Literal[1] | Literal[2]` is not supported: https://github.com/python/mypy/issues/11426

Currently this happens on 3.10:

```python
from typing import Literal

Literal[1, 2] | Literal[3]
# error: Unsupported left operand type for | ("object")
```

This happens because `mypy` treats `|` as a regular `__or__` operator. And `_SpecialForm` does not have this method. We have two ways to solve this:
1. Special case it in `mypy`. This is quite easy, but I don't think that this is a good way
2. Add `__or__` method to `_SpecialForm` type, just like it is done in `cpython`: https://github.com/python/cpython/blob/14a4fce457033412278ca9a056787db424310dc3/Lib/typing.py#L396-L397 This way we can be sure `mypy` will just work! 🎉 

There are several notes:
- There are `_SpecialForm`s that raise `TypeError` when used with `|`. Example: `Final | int`. But, this happens because `Final` is not allowed for `Union`. But, operator is supported. So, I guess this should be handled by a typechecker itself
- `TypedDict` is not special in `typeshed`: https://github.com/python/typeshed/blob/f4143c40e85db42dc98549e09329e196668395ee/stdlib/typing.pyi#L57-L58 But, `|` is supported by it:
```python
>>> from typing import TypedDict
>>> class My(TypedDict): ...
... 
>>> My | int
__main__.My | int
```
- `TypeVar` is a separate class, not a special form. But, we can use `T | S` in runtime as well.

I will send a PR with my proposal. We can work from there! 👋

**Comment by srittau** [comment]
typeshed should match the implementation. We should add `__or__` (and the other missing methods) to `_SpecialForm` in the stubs.

**Comment by JelleZijlstra** [comment]
Agree with @srittau, but would changing typeshed really be enough to fix the mypy issue? Even if we return something from `__or__`, would mypy recognize the result as a type?

**Comment by sobolevn** [comment]
> Even if we return something from __or__, would mypy recognize the result as a type?

After trying this out locally, I can say for sure that it won't work. Because `L = Literal[1]; reveal_type(L)` would reveal `object` type, not `_SpecialForm`. 😞 

But, anyways adding new `_SpecialForm` methods is a good thing. I am working on it 🙂

**Comment by AlexWaygood** [comment]
`__or__`/`__ror__` were added to `_SpecialForm` in #6498, so I think this can now be closed
