### ISSUE TITLE
missing definitions in dbapi2.pyi

### ISSUE THREAD

**Issue by luxint** [python/typeshed#6277]
Hi,

i noticed that the following definitions are missing in stdlib/sqlite3/dbapi2.pyi:
```
SQLITE_DROP_VTABLE: int
SQLITE_FUNCTION: int
SQLITE_RECURSIVE: int
SQLITE_SAVEPOINT:int
```

These are Authorizer Actions Codes, see [here](https://www.sqlite.org/c3ref/c_alter_table.html)

**Comment by sobolevn** [comment]
Thanks! There are a lot of types missing there. PR is incomming.
