### ISSUE TITLE
Instructions for "preparing the environment" fail on Windows

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6282]
I'm on a Windows machine. Inside my ``typeshed`` clone and a fresh virtual environment, if I run ``python -m pip install
-r requirements-tests-py3.txt``, it fails due to the fact that pytype is [not currently supported on Windows](https://github.com/google/pytype#requirements).

pytype also [doesn't currently support Python 3.10](https://github.com/google/pytype/issues/1022).

The instructions in `CONTRIBUTING.md` don't state that MacOS/Linux is a necessary requirement to run the tests locally (and, it might be nice to have a narrower suite of tests that can be easily run on Windows! 🙂). `CONTRIBUTING.md` should also probably be updated to state that running tests on Python 3.10 is not yet supported.

**Comment by srittau** [comment]
All sound like good points. PRs welcome. :)
