### ISSUE TITLE
Stubs for PyMySQL

### ISSUE THREAD

**Issue by ghagerer** [python/typeshed#631]
Hi together,

I just began generating stubs for PyMySQL. I auto-generated the stuff via mypy/stubgen.py based on Python 3.5 and afterwards modified the .pyi files manually so that mypy doesn't return errors when type checking my small project. 

Since I am new to all this I would be glad to hear some feedback about the work and if there's an option to get this included in future versions of typeshed. Moreover I invite everybody to help me to improve the stubs, especially since it's my first contribution.

Here's the repo link:
[https://github.com/ghagerer/pymysql_stubs](https://github.com/ghagerer/pymysql_stubs)

**Comment by gvanrossum** [comment]
To start, we'd like to hear from the original project's authors. Read here: https://github.com/python/typeshed#third_party

**Comment by ghagerer** [comment]
I got a permission from [here](https://github.com/PyMySQL/PyMySQL/issues/524#issuecomment-256273404). So what's the next step then?

**Comment by gvanrossum** [comment]
Please make a PR for the typeshed repo that adds your stubs to the third_party tree. Depending on whether your stubs are for Python 2, Python 3, or both, they should go into third_party/2.7, third_party/3, or third_party/2and3. Make sure your PR states that it fixes this issue.

**Comment by JelleZijlstra** [comment]
`third_party/2and3/pymysql` exists now.
