### ISSUE TITLE
error: "CodeType" has no attribute "replace" while it has and typeshed defines it.

### ISSUE THREAD

**Issue by Carreau** [python/typeshed#6319]
I'm guessing this is a PEBKAC, but I can't figure out why.

CodeTypes definitely has a replace method, and it is defined in the pyi:

https://github.com/python/typeshed/blob/1b0e268102b8d9a2ea921ebdeac87bd5eb793d55/stdlib/types.pyi#L126-L130

Though a pretty strait forward example fails...

```python
$ cat foo.py
from types import CodeType
from typing import List

args:List = []
c = CodeType(*args)
c.replace
```

```
$ python -m mypy foo.py
foo.py:6: error: "CodeType" has no attribute "replace"
Found 1 error in 1 file (checked 1 source file)
```
And most recent versions.
```
$ python -V
Python 3.10.0
$ mypy -V
mypy 0.910
```

Any idea where I'm doing things wrong ?

**Comment by srittau** [comment]
I am not sure what is going wrong, but locally here it works:

```
srittau@blitz:~$ mypy foo.py
Success: no issues found in 1 source file
srittau@blitz:~$ python -V
Python 3.9.2
srittau@blitz:~$ mypy -V
mypy 0.910
```

**Comment by JelleZijlstra** [comment]
Most likely you're running mypy in pre-3.8 mode.

**Comment by Carreau** [comment]
> Most likely you're running mypy in pre-3.8 mode.

Yeah, that seem logic and indeed if I go in another folder it works, and there is a mypy.ini file. This was indeed PEBKAC.
Thanks.
