### ISSUE TITLE
ctypes/__init__.pyi uses TypeVar within ClassVar

### ISSUE THREAD

**Issue by erictraut** [python/typeshed#6333]
I just implemented a check in pyright to report an error if a TypeVar is used within a ClassVar declaration. PEP 526 specifically says:

>Note that a ClassVar parameter cannot include any type variables, regardless of the level of nesting: ClassVar[T] and ClassVar[List[Set[T]]] are both invalid if T is a type variable.

A similar [feature request](https://github.com/python/mypy/issues/11538) was recently filed in the mypy issue tracker.

Here's the issue in the pyright issue tracker: https://github.com/microsoft/pyright/issues/2567.

This check is highlighting a problem in the `pointer` class defined within the `ctypes/__init__.pyi` stub.

```python
class pointer(Generic[_CT], _PointerLike, _CData):
    _type_: ClassVar[Type[_CT]]
```

I don't know enough about ctypes to suggest a proper fix.

**Comment by JelleZijlstra** [comment]
At runtime `ctypes.pointer` is a function that creates (!) a type when you call it, and returns an instance of that type. `_type_` is indeed a ClassVar on that type, but probably we should just model it as a regular attribute.

Reference: https://github.com/python/cpython/blob/main/Modules/_ctypes/callproc.c#L1947. The POINTER function right above it is the one that creates the type.

**Comment by erictraut** [comment]
The `Array` class within the same file also exhibits this problem.

```python
class Array(Generic[_CT], _CData):
    _type_: ClassVar[Type[_CT]]
    ...
``

**Comment by sobolevn** [comment]
I can make a PR to mypy to forbid this pattern (https://github.com/python/mypy/issues/11538). Looks like we would need to fix typeshed first.

**Comment by sobolevn** [comment]
Mypy PR: https://github.com/python/mypy/pull/11585
