### ISSUE TITLE
Annotation for builtin max() function uses wrong comparison operator

### ISSUE THREAD

**Issue by rhettinger** [python/typeshed#6336]
The stubs for [max()](https://github.com/python/typeshed/blob/fbb89f9fd54566e292a63b80cb32053bd6eb1bb4/stdlib/builtins.pyi#L1135) use `SupportsLessThanT` but should use `SupportsGreaterThanT` instead.

The [CPython source](https://github.com/python/cpython/blob/32959108f9c543e3cb9f2b68bbc782bddded6f42/Python/bltinmodule.c#L1837) uses `Py_GT`.

Instrumenting calls to *max()* shows the '>' operator being invoked:

```
class I(int):
    def __gt__(self, other):
        print(f'{self} > {other}')
        return int.__gt__(self, other)
    def __lt__(self, other):
        print(f'{self} < {other}')
        return int.__Lt__(self, other)

>>> largest = max(map(I, [10, 40, 20]))
40 > 10
20 > 40
>>> largest
40
```

A class that supplies only `__gt__` suffices for a call to *max()*:

```
class ReverseInt:
    def __init__(self, x):
        self.x = x
    def __gt__(self, other):
        return self.x < other.x
    def __repr__(self):
        return f'{type(self).__name__}({self.x!r})'
  
>>> max(map(ReverseInt, [10, 40, 20]))
ReverseInt(10)
```

**Comment by AlexWaygood** [comment]
@rhettinger, would you mind commenting on whether you think [my analysis here](https://github.com/python/typeshed/pull/6342#issuecomment-974095969) is correct?

**Comment by rhettinger** [comment]
Thanks for fixing this.
