### ISSUE TITLE
`ctypes.Array` should be abstract

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6349]
Right now `Array` in `ctypes` is a regular class: 

https://github.com/python/typeshed/blob/5c8e68f0ebeb0528790c0a13fda3131d6434cda7/stdlib/ctypes/__init__.pyi#L269-L271

But, in reallity - you cannot instantiate it: 

```python
>>> from ctypes import Array, c_int
>>> i = c_int(1)
>>> Array(i)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: abstract class
```

Mypy is also not happy with `Array(...)` but for other reasons:

```
out/ex.py:4: error: Array constructor argument 1 of type "c_int" is not convertible to the array element type <nothing>
out/ex.py:4: note: Revealed type is "ctypes.Array[<nothing>]"
```

`Array(...)` is not tested in https://github.com/python/mypy/blob/master/test-data/unit/check-ctypes.test at all

**Comment by JelleZijlstra** [comment]
Note that mypy has a dedicated plugin for ctypes (https://github.com/python/mypy/blob/master/mypy/plugins/ctypes.py), so not everything here may be fixable in typeshed.

**Comment by srittau** [comment]
I don't think there is a good way to make `Array` abstract in typeshed. As it doesn't derive from `abc.ABCMeta` at runtime, we shouldn't derive it either. If you have an idea on how to mark it, please open a PR. Until then I'm closing this as "inexpressable".

**Comment by sobolevn** [comment]
We can try to make `_length_` and `_type_` abstract properties: https://github.com/python/cpython/blob/main/Modules/_ctypes/_ctypes.c#L1522-L1526

Docs: https://github.com/python/cpython/blob/1cbaa505d007e11c4a1f0d2073d72b6c02c7147c/Doc/library/ctypes.rst#arrays-and-pointers

This way, we would have a class with "abtract" attributes and it won't be possible to create instances of it.

**Comment by sobolevn** [comment]
But, they should be writable: 

```python
>>> from ctypes import c_int
>>> x = c_int * 3
>>> x
<class '__main__.c_int_Array_3'>
>>> x._length_
3
>>> x._length_ = 2
```

**Comment by sobolevn** [comment]
Refs https://github.com/python/typeshed/pull/6348
