### ISSUE TITLE
Redis-py version 4

### ISSUE THREAD

**Issue by agusdmb** [python/typeshed#6364]
I need for my project the stubs for the version 4 of [redis-py](https://github.com/Redis/redis-py) which came out recently

In fact what i actually needed was the changes i did [in this PR](https://github.com/python/typeshed/pull/6363) but i realized after i made it that those are not compatible with redis version 3.5 which is the one used here.

When is it going to be updated here? Is there a way to support both versions?

**Comment by Akuli** [comment]
See discussion on #6335. We would accept pull requests that port the existing redis stubs to redis 4, but #6335 isn't great because it throws away all the manual work that has been done to redis 3.x stubs.
