### ISSUE TITLE
ipaddress module types for convenience functions are all Any

### ISSUE THREAD

**Issue by wrgeorge1983** [python/typeshed#6377]
```
def ip_address(address: object) -> Any: ...  # morally IPv4Address | IPv6Address
def ip_network(address: object, strict: bool = ...) -> Any: ...  # morally IPv4Network | IPv6Network
def ip_interface(address: object) -> Any: ...  # morally IPv4Interface | IPv6Interface
```

As a consequence modern IDEs (the two I've checked:  PyCharm and VSCode / Pylance)  give up on typing these return values even though each of them has a quite consistent interface and should generate useful autocomplete, etc.  

My proposal is to either return union types (as indicated by the 'morally' comments) or return base classes that are already present in the stub:

```
class _BaseAddress(_IPAddressBase, SupportsInt):
...

class _BaseNetwork(_IPAddressBase, Container[_A], Iterable[_A], Generic[_A]):
...
class _BaseInterface(_BaseAddress, Generic[_A, _N]):  # notably this one exists in the stub, but not in the module itself?
...
```

I'm not sure if there's a conventional or technical reason not to return private base classes though.

I'm happy to submit a PR with either of these strategies (or other guidance you might have as how best to solve this).  

I've read enough to know "union returns are discouraged" but I'm not sure how or if the reasoning given applies to the case of a function that actually returns one of two types (each of which are equivalent and have identical or very similar interfaces).  The value of these functions is that they permit (and promote) version-independent IP address handling which is ever-more-important as time goes on and IPv6 adoption increases.  The strict union of these two types (exposing only the methods/properties that they have in common) is entirely appropriate for these, so I don't think you'd have lots of users wrapping this in `is_instance()` as a result of a union return.  Someone looking to do fancy things with special IPv6 address types and such wouldn't use these functions, they'd use the class directly.

I'm not deeply familiar with the typing, so I haven't been able to figure out if the "morally" comments hold some semantic meaning that should (or will in the future) be useful, so maybe that's a piece of this that I'm missing.

**Comment by Akuli** [comment]
Returning a protocol seems best to me, but I'd like to know what other maintainers think.
