### ISSUE TITLE
Multiple incompatibilities for the type of self

### ISSUE THREAD

**Issue by elazarg** [python/typeshed#638]
During my work ([mypy/#2381](https://github.com/python/mypy/pull/2381)) on a fix for [mypy/#2374](https://github.com/python/mypy/issues/2374), I have encountered many bad signatures - mostly missing the `self` parameter - in the following methods (only a selection of them was chekced manually by me)

Python3
1. [stdlib/3/multiprocessing/managers.pyi:8](../blob/master/stdlib/3/multiprocessing/managers.pyi#L8): `multiprocessing.managers.BaseManager.register`
2. [stdlib/3/ssl.pyi:222](../blob/master/stdlib/3/ssl.pyi#L222): `ssl.SSLContext.set_alpn_protocols`
3. [stdlib/3/ssl.pyi:223](../blob/master/stdlib/3/ssl.pyi#L223): `ssl.SSLContext.set_npn_protocols`
4. [stdlib/3/ssl.pyi:234](../blob/master/stdlib/3/ssl.pyi#L234): `ssl.SSLContext.wrap_bio`
5. [stdlib/3/unittest.pyi:141](../blob/master/stdlib/3/unittest.pyi#L141): `unittest.TestCase.addCleanup`
6. [stdlib/3/urllib/request.pyi:120](../blob/master/stdlib/3/urllib/request.pyi#L120): `urllib.request.HTTPPasswordMgrWithPriorAuth.update_authenticated`
7. [stdlib/3/urllib/request.pyi:122](../blob/master/stdlib/3/urllib/request.pyi#L122): `urllib.request.HTTPPasswordMgrWithPriorAuth.is_authenticated`
8. [stdlib/3/urllib/request.pyi:194](../blob/master/stdlib/3/urllib/request.pyi#L194): `urllib.request.URLopener.retrieve`
9. [stdlib/3/urllib/request.pyi:77](../blob/master/stdlib/3/urllib/request.pyi#L77): `urllib.request.BaseHandler.http_error_nnn`
10. [stdlib/3/urllib/robotparser.pyi:9](../blob/master/stdlib/3/urllib/robotparser.pyi#L9): `urllib.robotparser.RobotFileParser.__init__`

Python2:
1. [stdlib/2/imp.pyi:35](../blob/master/stdlib/2/imp.pyi#L35): `imp.NullImporter.find_module`
2. [stdlib/2/select.pyi:97](../blob/master/stdlib/2/select.pyi#L97): `select.epoll.unregister`
3. [stdlib/2/select.pyi:98](../blob/master/stdlib/2/select.pyi#L98): `select.epoll.poll`
4. [stdlib/2/shlex.pyi:13](../blob/master/stdlib/2/shlex.pyi#L13): `shlex.shlex.error_leader`
5. [stdlib/2/ssl.pyi:172](../blob/master/stdlib/2/ssl.pyi#L172): `ssl.SSLContext.set_alpn_protocols`
6. [stdlib/2/ssl.pyi:173](../blob/master/stdlib/2/ssl.pyi#L173): `ssl.SSLContext.set_npn_protocols`
7. [stdlib/2/_struct.pyi:12](../blob/master/stdlib/2/_struct.pyi#L12): `_struct.Struct.pack_into`
8. [stdlib/2/_symtable.pyi:39](../blob/master/stdlib/2/_symtable.pyi#L39): `_symtable.symtable.__init__`
9. [stdlib/2/tempfile.pyi:31](../blob/master/stdlib/2/tempfile.pyi#L31): `tempfile._RandomNameSequence.normcase`
10. [stdlib/2/tempfile.pyi:45](../blob/master/stdlib/2/tempfile.pyi#L45): `tempfile._TemporaryFileWrapper.unlink`
11. [The third overload of `file.__init__`](../blob/master/stdlib/2/__builtin__.pyi#L915):

``` Python
    def __init__(file: int, mode: str = 'r', buffering: int = ...) -> None: ...
```

Also, tons of `__builtin__` mismatches (possibly spurious).

Third party:
1. [third_party/3/pkg_resources.pyi:228](../blob/master/third_party/3/pkg_resources.pyi#L228): `IMetadataProvider.*`
2. [third_party/2/pymssql.pyi:21](../blob/master/third_party/2/pymssql.pyi#L21): `pymssql.Cursor.callproc`

**Comment by gvanrossum** [comment]
Eew! So good to catch these. Can you submit fixes? One PR per subdirectory would be fone.
