### ISSUE TITLE
Pre-commit runs on pushes made by pre-commit

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6422]
It probably doesn't need to.

**Comment by Akuli** [comment]
It seems harmless to me, and if `black` and `isort` disagree about something (e.g. black changes something and then isort reformats in a black-incompatible way), the problem will be noticed.

**Comment by AlexWaygood** [comment]
True, it doesn't take nearly as long as mypy_primer, so it's probably fine — just thought I'd mention it 🙂
