### ISSUE TITLE
Adding stubs for small projects

### ISSUE THREAD

**Issue by kasium** [python/typeshed#6479]
Hi guys,

I use some small projects such as ``flake8-simplify`` or ``sqlalchemy_schemadisplay``. These don't offer type hints, but I use them programmatically and therefore mypy complains about missing type stubs. Would typeshed be the right place to also add stubs for them or is the focus on libraries/projects which are used by a larger audience?

Thanks a lot

**Comment by srittau** [comment]
We generally accept stubs for all packages on PyPI, as long as they support current Python versions and don't ship their own stubs/type annotations.

**Comment by kasium** [comment]
Thanks a lot!
