### ISSUE TITLE
Python 2 compatible type hints in typeshed/third_party/2/?

### ISSUE THREAD

**Issue by ghagerer** [python/typeshed#648]
Hi,

I am wondering that there are many (all?) stub files among the typeshed/third_party/2/ folder which don't contain any Python 2 compatible type hints at all. This stands in contrast to the [typeshed README](https://github.com/python/typeshed#third_party). Moreover, the files therein are appear to be compatible with Python 3.5 according to [PEP 484](https://www.python.org/dev/peps/pep-0484).

Can somebody please confirm this impression?

Regarding Python 2 compatible type hints I am referring to:
- [PEP 484 -- Type Hints: Suggested syntax for Python 2.7 and straddling code](https://www.python.org/dev/peps/pep-0484/#suggested-syntax-for-python-2-7-and-straddling-code)
- [Mypy documentation: Type checking Python 2 code](http://mypy.readthedocs.io/en/latest/python2.html)

As examples for (seemingly) Python 3.5 compatible type hints within typeshed/third_party/2/ please consider any files from these subfolders:
- [typeshed/third_party/2/sqlalchemy/](https://github.com/python/typeshed/tree/master/third_party/2/sqlalchemy)
- [typeshed/third_party/2/OpenSSL/](https://github.com/python/typeshed/tree/master/third_party/2/OpenSSL)

These are just two random examples. In fact I cannot find any Python 2 compatible type hints in typeshed/third_party/2/ manually, which is totally against my expectation.

P.S.: I just tried `mypy --py2 sqlalchemy` from typeshed/third_party/2/. It ran without any errors. However, I am still confused by the fact that there are PEP484 type hints which are by definition not compatible to Python 2 in that folder.

**Comment by gvanrossum** [comment]
All stubs use the Python 3 syntax. mypy always uses the latest Python 3 syntax to parse stubs (and IIUC so does pytype).

I can find nothing in either the rep README or PEP 484 that promises that the Python 2 *stubs* must use the Python 2 syntax.

I hope this removes your worries!

**Comment by gvanrossum** [comment]
(In fact, the mypy docs state this explicitly, in http://mypy.readthedocs.io/en/latest/type_inference_and_annotations.html#types-in-stub-files .)

**Comment by ghagerer** [comment]
I see. Python 2.7 type hints are there just for Python 2.7 code. Stub files for Python 2.7 use Python 3 type hint syntax then, which is accordingly produced by mypy using `stubgen.py --py2`.

Thanks for clarification!

**Comment by gvanrossum** [comment]
You're welcome!
