### ISSUE TITLE
TOML stubs incomplete

### ISSUE THREAD

**Issue by mdjong1** [python/typeshed#6484]
We recently ran into an issue with the TOML stub related to the TomlDecodeError. Mypy threw this one at us: `"TomlDecodeError" has no attribute "msg"`. This appears to originate from types-toml, which is maintained from https://github.com/python/typeshed/tree/master/stubs/toml. But it seems that the definition of `TomlDecodeError` there does not include any of the original class variables, thus generating this error.

Adding this issue for tracking, will possibly update these stubs ourselves in the near future.

**Comment by mdjong1** [comment]
I just noticed that toml nowadays includes it's correct typing, so perhaps it should be moved out from here?
https://github.com/uiri/toml/blob/master/toml/decoder.pyi

**Comment by Akuli** [comment]
Afaik `toml` is no longer maintained: #6022

**Comment by srittau** [comment]
The latest released version of `toml` doesn't include stubs, so our stubs are still required. But as Akuli mentioned, toml seems to be not longer maintained and I would recommend to switch to `tomli`. That said, we accept PRs to improve our `toml` stubs.
