### ISSUE TITLE
CONTRIBUTING.md doesn't mention create_baseline_stubs script

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6502]
https://github.com/python/typeshed/blob/415d3870095a634ca8da6dddf5df03b449740d98/CONTRIBUTING.md#L131-L134

It would be better to recommend `scripts/create_baseline_stubs.py`, which calls stubgen and reformats the stubs automatically.

**Comment by hauntsaninja** [comment]
This was added at some point
