### ISSUE TITLE
Problems with `codecs.encode`

### ISSUE THREAD

**Issue by megapctr** [python/typeshed#652]
I'm getting an error from mypy:
```
Argument 1 to "encode" has incompatible type "bytes"; expected "str"
```
but actually
```
$ ipython3
Python 3.5.2 (default, Sep 10 2016, 08:21:44) 
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import codecs

In [2]: codecs.encode('foo', 'base64')
(...)
TypeError: encoding with 'base64' codec failed (TypeError: expected bytes-like object, not str)

In [3]: codecs.encode(b'foo', 'base64')
Out[3]: b'Zm9v\n'
```

**Comment by gvanrossum** [comment]
Oh, the base64 codec is backwards compared to standard encodings like utf-8. Please don't use that with encodings (especially not if you want it to type-check :-).

**Comment by megapctr** [comment]
So the only solution here is to add `type: ignore`?

**Comment by gvanrossum** [comment]
Or change your code, yes.

**Comment by megapctr** [comment]
The point is that making the call to codecs.encode pass typecheck results in TypeError upon execution - mypy complains about `bytes`, while the base64 encoder complains about str

**Comment by gvanrossum** [comment]
You should use the base64 module directly.

--Guido (mobile)

**Comment by gvanrossum** [comment]
See also https://github.com/python/typeshed/issues/300.
