### ISSUE TITLE
Support PEP 526 syntax in stubs

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#653]
Stubs are currently written using Python 3.5 syntax. In Python 3.6 we have a nice new notation to replace `# type:` comments due to [PEP 526](https://www.python.org/dev/peps/pep-0526/), e.g.
```python
foo: int
bar: int = ...
```
instead of
```python
foo = None  # type: int
bar = ...  # type: int
```
@matthiaskramm Is support for this syntax on the roadmap for pytype's parser?
@vlasovskikh When does PyCharm plan to support this?

**Comment by vlasovskikh** [comment]
The beta of the next PyCharm version already supports this syntax. We've set the default syntax version for Python stubs to 3.6.

**Comment by matthiaskramm** [comment]
(Sorry for the late reply - I was out on paternity leave)

Yes, we do want to support this syntax.

**Comment by gvanrossum** [comment]
Congrats on the new baby!

Let us know when this syntax is supported, so we can start using it in stubs. (It will need a small mypy change too, to allow the new syntax in stubs -- currently they are always parsed in 3.5 mode.)

**Comment by ambv** [comment]
@matthiaskramm I added third_party/3.6/click stubs that are using PEP 526 attributes, you can test with those :-)

**Comment by gvanrossum** [comment]
OT: Who is the developer for click? Are they okay with having stubs in
typeshed? (We are bound by PEP 484 and the typeshed README to have their
permission.)

**Comment by ambv** [comment]
Pallets, same people as Werkzeug, Jinja2, Flask, etc. Permission given verbally beforehand and forgiveness offered after the fact in https://github.com/pallets/click/issues/693.

**Comment by matthiaskramm** [comment]
About to add the new syntax (to our internal version, for starters). Do we need to support both

```
foo: int
```

and

```
foo: int = ...
```

?

Do they have different semantics?

**Comment by JukkaL** [comment]
@matthiaskramm Mypy treats them equivalently. PEP 526 implies that the latter could mean that the attribute has a default value that can be accessed through the class object, but this is left pretty vague and PEP 526 doesn't discuss stubs explicitly. I'd suggest supporting both variants for more flexibility.

**Comment by matthiaskramm** [comment]
The second syntax (with the "`= ...`") looks odd to me. At least in typeshed, we should encourage using only the short form.

**Comment by JukkaL** [comment]
If we want to be super precise in stubs, the distinction might occasionally be significant. Consider this example:

```py
# m.pyi
class A:
    id: str = ...
```

```py
# program.py
from m import A
print(A.id)  # Is this valid or not?
```

If there's no `= ...`, then perhaps the attribute is only initialized in `__init__` and there is no default in the type object, and the program would fail at runtime. `ClassVar[...]` is probably better in most cases, but mypy doesn't support it yet.

**Comment by ambv** [comment]
We can encourage but we shouldn't force, @matthiaskramm. You should be forgiving in what you accept and strict in what you emit. What purpose do arbitrary restrictions on what the parser accepts serve?

**Comment by ambv** [comment]
+1 to what Jukka just said.

**Comment by matthiaskramm** [comment]
Ok, I'll add both syntax variants.

**Comment by JukkaL** [comment]
Another potential case where this could plausibly make a difference:

```py
# m.pyi
class A:
    id: str = ...
```

```py
# program.py
class B(A):
    def __init__(self) -> None:
        pass  # we don't call base class __init__
B().a  # this is okay, but without the default in A this would perhaps result in AttributeError
```

**Comment by JelleZijlstra** [comment]
We've been using PEP 526 syntax in stubs for a while. I can't find the link back right now, but in some thread @ambv established that it works fine with all of mypy, pytype, and PyCharm, so I'm closing this issue.
