### ISSUE TITLE
Weird `n_fields` attributes, etc.

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6546]
There are a bunch of `NamedTuple`-like classes in some of the stranger corners of the stdlib that have the following three attributes:

- `n_fields`
- `n_sequence_fields`
- `n_unnamed_fields`

For example:

https://github.com/python/typeshed/blob/1fdd7e40afbad567a92de4ce98bdddaa6be14db5/tests/stubtest_allowlists/py3_common.txt#L620-L631

@Akuli [counts 22 classes](https://github.com/python/typeshed/pull/6500#discussion_r762599896) that are missing these attributes. Some classes, however, _do_ currently define these attributes in the stub currently. `time._struct_time` defines them as properties (which seems incorrect -- they seem more like `ClassVar`s to me):

https://github.com/python/typeshed/blob/1fdd7e40afbad567a92de4ce98bdddaa6be14db5/stdlib/time.pyi#L35-L50

As discussed [here](https://github.com/python/typeshed/pull/6500#discussion_r762599896), these attributes don't seem particularly _useful_. I'm also not sure there's much _harm_ in having them in the stubs, but it might be weird to have them popping up in autocompletion suggestions.

In any event, they should probably either all be added to the stubs, or all removed from stubs, and added to the "wontfix" section of the allowlists instead of the "missing from stubs" section of the allowlists.

Thoughts?

**Comment by srittau** [comment]
If they're there they should probably be added.

**Comment by JelleZijlstra** [comment]
These are instances of structseq (https://github.com/python/cpython/blob/main/Objects/structseq.c), an internal CPython type that is almost but not quite like a namedtuple. It may be worth adding a common base class for them in `_typeshed`, though at runtime they just inherit from tuple.

**Comment by AlexWaygood** [comment]
Given this comment at the top of the source code for `structseq`, I'm inclined to say that these attributes should _not_ be included in the stubs, and that they should just be treated like regular `NamedTuple`s:

> The structseq helper is considered an internal CPython implementation
> detail.  Docs for modules using structseqs should call them
> "named tuples" (be sure to include a space between the two
> words and add a link back to the term in Docs/glossary.rst).

**Comment by srittau** [comment]
Treating them as namedtuples is also worth a try.

**Comment by JelleZijlstra** [comment]
The constructor is different from namedtuples though. You have to initialize them with a single tuple.

**Comment by AlexWaygood** [comment]
> The constructor is different from namedtuples though. You have to initialize them with a single tuple.

Oh, I see. Yes, `os.uname_result` only takes a single argument, which must be a sequence of some kind, and must be of precisely the right length. So it's _like_ a `NamedTuple`, but with a very different constructor:

```python
>>> from os import uname_result
>>> uname_result('a', 'b', 'c', 'd', 'e')
TypeError: structseq() takes at most 2 arguments (5 given)
>>> uname_result(('a', 'b', 'c', 'd', 'e'))
posix.uname_result(sysname='a', nodename='b', release='c', version='d', ma
chine='e')
```

There appears to be an optional second argument, which has to be a `dict` of some kind.

So, creating a common base class for them in `_typeshed` sounds like a good shout.

**Comment by Akuli** [comment]
With a custom base class, it would be hard to support type-safe indexing, as type checkers usually hard-code this behavior for `tuple` and `NamedTuple`.

```python
>>> os.uname_result('abcde')
posix.uname_result(sysname='a', nodename='b', release='c', version='d', machine='e')
>>> os.uname_result('abcde')[0]
'a'
```

This would be useful for unpacking:

```python
sysname, nodename, release, version, machine = os.uname()
```

**Comment by AlexWaygood** [comment]
We could do something like this:

```python
from typing import ClassVar, Generic, Sequence, SupportsIndex, Type, TypeVar, overload

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)

class structseq(Sequence[_T_co], Generic[_T_co]):
    n_fields: ClassVar[int]
    n_unnamed_fields: ClassVar[int]
    n_sequence_fields: ClassVar[int]
    def __new__(cls: Type[_T], seq: Sequence[str]) -> _T: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, __i: SupportsIndex) -> _T_co: ...
    @overload
    def __getitem__(self, __i: slice) -> Sequence[_T_co]: ...

class uname_result(structseq[str]):
    sysname: str
    nodename: str
    release: str
    version: str
    machine: str
    
x = uname_result('abcde')
sysname, nodename, release, version, machine = x
y = x.sysname
z = x.n_fields

reveal_type(x)  # Revealed type is "__main__.uname_result"
reveal_type(y)  # Revealed type is "builtins.str"
reveal_type(z)  # Revealed type is "builtins.int"
reveal_type(sysname)  # Revealed type is "builtins.str*"
```

Advantages:
- The constructor is _more_ accurate than the current constructor. `uname_result(1, 2, 3, 4, 5)` currently passes mypy but fails at runtime.
- We can share code between these classes by having a common base class.
- We add the missing attributes `n_fields`, `n_sequence_fields` and `n_unnamed_fields` to these classes.

Disadvantages:
- There's no way to tell mypy that the `seq` argument to the constructor has to be exactly 5 items long. `uname_result((1, 2, 3, 4, 5, 6))` will pass mypy but fail at runtime.
- There's no way to tell mypy that `uname_result` instances will always contain exactly five items. `x = uname_result((1, 2, 3, 4, 5)); x[5]` will pass mypy but fail at runtime.

**Comment by Akuli** [comment]
> There's no way to tell mypy that the seq argument to the constructor has to be exactly 5 items long.

I don't think we can do this anyway. It works if we require it to be `tuple[str, str, str, str, str]`, but then passing in a list will fail.

**Comment by Akuli** [comment]
> class uname_result(structseq[str]):

This doesn't work so nicely when the struct sequence contains different types. Surprisingly, most struct sequences only have one type: `uname_result` has strings, `terminal_size` and `stat_result` have ints, `times_result` has floats. But `resource.struct_rusage` has ints and floats. In practice, `structseq[float]` might be good enough, because the attributes are more commonly accessed and they can be still `int` where needed.

**Comment by AlexWaygood** [comment]
> > There's no way to tell mypy that the seq argument to the constructor has to be exactly 5 items long.
> 
> I don't think we can do this anyway. It works if we require it to be `tuple[str, str, str, str, str]`, but then passing in a list will fail.

Yes, precisely. It's a "disadvantage" in that it is not a perfect solution, but it's not a regression vis-à-vis the current situation.

**Comment by AlexWaygood** [comment]
> We could do something like this:

My above suggestion has the disadvantage that the following would pass mypy, but fail at runtime:

```python
from os import uname_result
x = uname_result('abcde')
x.sysname = 'foo'
```

A slightly more cumbersome, but more accurate, definition would be something like the following:

```python
from typing import ClassVar, Generic, Sequence, SupportsIndex, Type, TypeVar, overload

_T = TypeVar("_T")
_T_co = TypeVar("_T_co", covariant=True)

class structseq(Sequence[_T_co], Generic[_T_co]):
    n_fields: ClassVar[int]
    n_unnamed_fields: ClassVar[int]
    n_sequence_fields: ClassVar[int]
    def __new__(cls: Type[_T], seq: Sequence[_T_co]) -> _T: ...
    def __len__(self) -> int: ...
    @overload
    def __getitem__(self, __i: SupportsIndex) -> _T_co: ...
    @overload
    def __getitem__(self, __i: slice) -> Sequence[_T_co]: ...

class uname_result(structseq[str]):
    @property
    def sysname(self): -> str: ...
    @property
    def nodename(self): -> str: ...
    @property
    def release(self): -> str: ...
    @property
    def version(self): -> str: ...
    @property
    def machine(self): -> str: ...
```
