### ISSUE TITLE
How should `jsonschema.protocols.Validator` be introduced?

### ISSUE THREAD

**Issue by sirosen** [python/typeshed#6564]
_For full background info, see also https://github.com/Julian/jsonschema/issues/548_

The `jsonschema` library is already in typeshed, but is going to introduce a new `Protocol` class (assuming I can sort out what should happen to add it).
This is made tricky by the fact that `jsonschema` does not have PEP561 metadata, but we want to add a `Protocol` which is explicitly meant for type-checking usages.

I'm not clear on what the correct order of operations is here. Should we get the protocol included in `jsonschema`, and then add it to typeshed, acknowledging that the protocol won't be that useful until we do?
I'm happy to work up the typeshed PR, but I'd like to do so with the assurance that it will be merged and that the types for `jsonschema` won't diverge from the library itself for too long.

**Comment by JelleZijlstra** [comment]
> Should we get the protocol included in jsonschema, and then add it to typeshed, acknowledging that the protocol won't be that useful until we do?

Yes, that sounds right! We're usually pretty quick at merging PRs, so we should be able to land this without much delay.
