### ISSUE TITLE
Mypy_primer is spammy if there's invalid syntax

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6567]
Mypy_primer produces very large diffs if some _fool_ of a contributor (like me) creates a PR that has invalid syntax. See, e.g., the early diffs in [my PR here](https://github.com/python/typeshed/pull/6560). These diffs are essentially useless, since the primer diff is the least of your concerns if the PR has invalid syntax.

Would it be possible for mypy_primer to do a quick sweep of typeshed checking for syntax errors before it starts the test? It could then fail quickly if any are discovered, and not bother attempting to find the diff.

**Comment by hauntsaninja** [comment]
There's already code that limits the length of diff in the github workflow, could potentially reduce that.
But since we hide comments of previous runs anyway, I'm not sure this matters much.

**Comment by sobolevn** [comment]
I am also a big fan of idea that we actually see these logs. Because you can break something and `--show-traceback` will be very helpful. It is especially helpful in mypy.

**Comment by AlexWaygood** [comment]
Fair! I'm persuaded that this wouldn't be a good idea 🙂
