### ISSUE TITLE
max() works with greater-than or less-than

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#6575]
Currently `max()` expects `__gt__`, but this example indicates that it also works if only `__lt__` is present:
```py
class Lt:
    def __init__(self, x):
        self.x = x

    def __repr__(self):
        return f"Lt({self.x})"

    def __lt__(self, other):
        return self.x < other.x

class Gt:
    def __init__(self, x):
        self.x = x

    def __repr__(self):
        return f"Gt({self.x})"

    def __gt__(self, other):
        return self.x > other.x

print(max(Lt(2), Lt(5)))  # Lt(5)
print(max(Lt(5), Lt(2)))  # Lt(5)
print(max(Gt(2), Gt(5)))  # Gt(5)
print(max(Gt(5), Gt(2)))  # Gt(5)
```

I think that we should accept either method.

The signature of `max()` was changed to expect `__gt__` in #6342.

**Comment by JukkaL** [comment]
Having `__ge__` or `__le__` is not sufficient, however.

**Comment by AlexWaygood** [comment]
In #6342, [I argued](https://github.com/python/typeshed/pull/6342#issuecomment-974095969)  that the signature of `max` should be the following due to [the way comparison operators are desugared by the interpreter](https://snarky.ca/unravelling-rich-comparison-operators/) :

```python
from typing import Any, Callable, Iterable, Protocol, TypeVar, Union, overload

_T = TypeVar("_T")
_T1 = TypeVar("_T1")
_T2 = TypeVar("_T2")

class _SupportsDunderLT(Protocol):
    def __lt__(self, other: Any) -> bool: ...

class _SupportsDunderGT(Protocol):
    def __gt__(self, other: Any) -> bool: ...

SupportsComparisons = Union[_SupportsDunderGT, _SupportsDunderLT]
SupportsComparisonsT = TypeVar('SupportsComparisonsT', bound=SupportsComparisons)

@overload
def max(
    __arg1: SupportsComparisonsT, __arg2: SupportsComparisonsT, *_args: SupportsComparisonsT, key: None = ...
) -> SupportsComparisonsT: ...
@overload
def max(__arg1: _T, __arg2: _T, *_args: _T, key: Callable[[_T], SupportsComparisons]) -> _T: ...
@overload
def max(__iterable: Iterable[SupportsComparisonsT], *, key: None = ...) -> SupportsComparisonsT: ...
@overload
def max(__iterable: Iterable[_T], *, key: Callable[[_T], SupportsComparisons]) -> _T: ...
@overload
def max(__iterable: Iterable[SupportsComparisonsT], *, key: None = ..., default: _T) -> SupportsComparisonsT| _T: ...
@overload
def max(__iterable: Iterable[_T1], *, key: Callable[[_T1], SupportsComparisons], default: _T2) -> _T1 | _T2: ...
```

If we make this change, we should probably update similar functions such as `min()` and `sorted()`, which have similar issues. But, I know @srittau disagrees with me 🙂

Related: the mypy issue I opened [here](https://github.com/python/mypy/issues/11588), following the conversation in #6342.

**Comment by JukkaL** [comment]
Ah, I missed the discussion in the original PR which covers this in detail. 

If we'd support this in type checkers, this could result in false negatives if user code tries to call `__lt__` or `__gt__`:

```py
def f(x: SupportsDunderGt, other: Any) -> bool:
    return x.__gt__(other)  # Doesn't do the right thing if __gt__ is missing

f(Lt(5), Lt(6))
```

The main issue I have is that this would add "ad-hoc" complexity at the type system level, which seems unnecessary in this case. We could easily support this use case in typeshed once, and this would work as expected with every type checker, and without false negatives as far as I can see. If we expect type checkers to support some sort of `__lt__`/`__gt__` equivalence, the implementation is likely to be more difficult to maintain, and it needs to be duplicated for every type checker, including current ones (at least mypy) and any possible future ones. And if some type checker doesn't implement the special case, this will result in false positives for the users of the type checker.  It's also possible that different type checkers would implement the rules differently, since this type checking behavior isn't explicitly defined in any PEP, including [PEP 544](https://www.python.org/dev/peps/pep-0544/).

Also, I don't think that semantics of `PyObject_RichCompareBool` are relevant here (this was mentioned in #6342). The protocol class only says that `__lt__` or `__gt__` is present, and the protocol doesn't talk anything about what is done with `__lt__` or `__gt__` by the callee. Another function with a signature similar to `max()` might require `__gt__` to be present, and wouldn't use `PyObject_RichCompareBool` or the equivalent at all.

For these reasons I'd prefer this to be handled in typeshed.

**Comment by srittau** [comment]
Would a custom "RichComparison" alias make sense here?

**Comment by JukkaL** [comment]
If we'd use the definitions from https://github.com/python/typeshed/issues/6575#issuecomment-992484040 above, I think this would make sense.

Maybe something like this?

```py
SupportsRichComparison = Union[_SupportsDunderGT, _SupportsDunderLT]
SupportsRichComparisonT = TypeVar('SupportsRichComparisonT', bound=SupportsRichComparison)
```

**Comment by AlexWaygood** [comment]
I'd be very interested in submitting a PR along these lines, if we have consensus?

**Comment by JukkaL** [comment]
@AlexWaygood I think that we have enough thumbs ups to move forward.

**Comment by AlexWaygood** [comment]
We need to reopen this, unfortunately. There was a logical error in my PR #6583, in that the following two types are not equivalent:

```python 
Callable[[_T], SupportsDunderLT | SupportsDunderGT]
```

is not the same as

```
Callable[[_T], SupportsDunderLT] | Callable[[_T], SupportsDunderGT]
```

The former is incorrect, and is what is currently in the stub in e.g. overloads 2, 4 & 6 of `max`. The latter is what _should_ be used in these situations.

I think we need another alias in typeshed — what should it be called? `CallableReturningComparable`?

**Comment by AlexWaygood** [comment]
@JukkaL I'm afraid this is probably a regression that was shipped with 0.920 ☹️

**Comment by JukkaL** [comment]
Have you seen issues caused by the new type? I believe that the union return type is fine, since the return type can vary covariantly (`Callable[..., X]` is valid if `Callable[..., X | Y]` is expected).

**Comment by AlexWaygood** [comment]
@JukkaL you're right, please ignore me — [it seems to work fine](https://mypy-play.net/?mypy=master&python=3.10&gist=8f77dca56e236928829bfdb73f7448bb).

**Comment by Kache** [comment]
Is the following expected? Or is there an issue with either typeshed or the type checker?

```py
def foo(a: SupportsRichComparisonT, b: SupportsRichComparisonT):
    return a < b
```

```
main.py:16: error: Unsupported left operand type for < (some union)  [operator]
Found 1 error in 1 file (checked 1 source file)
```

https://mypy-play.net/?mypy=master&python=3.11&gist=2dcc0cc29ac7d0ee49e87b14a327b301

**Comment by AlexWaygood** [comment]
@Kache please open a new issue rather than commenting on one that's been closed for two years :)

**Comment by Kache** [comment]
Zgcyviij k cbvcx get vongl4378+*%7

**Comment by Kache** [comment]
Sorry, wasn't sure if it was an actual issue worth posting about.
