### ISSUE TITLE
Merge 3.4 and 3.5 pathlib stubs

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#659]
There are separate stubs for pathlib for Python 3.4 and 3.5. Whatever differences these have should probably just be written using checks for sys.version_info rather than by maintaining two separate stub files.

**Comment by gvanrossum** [comment]
FYI here are the differences between the 3.4 and 3.5 versions.

Added methods:
- gethomedir
- home
- samefile
- read_bytes
- read_text
- write_bytes
- write_text
- expanduser

Changed methods:
- mkdir has a new arg exists_ok

**Comment by gvanrossum** [comment]
New in 3.6:
- resolve has a strict flag
- scandir
- `__fspath__`
- PurePath is a virtual subclass of os.PathLike

**Comment by phouse512** [comment]
@gvanrossum this makes sense, and I can try it out. I guess my question is where should the stub file with the version checks remain, in the 3.4 or 3.5 directory?

**Comment by gvanrossum** [comment]
A stub file should live in the directory corresponding to the earliest
Python version where the module appeared. So in this case 3.4 since that's
when pathlib.py first came onto the scene.

**Comment by phouse512** [comment]
Got it, so I have a [commit](https://github.com/phouse512/typeshed/commit/efcbbda552dfabfdc3b887af22180ba4070ca410) that handles those changes in 3.4 and removes `3.5/pathlib.pyi`, but I'm running into some issues with the conditional changes for 3.6.  How would I best go about handling the conditional implementation of the `os.PathLike` interface? Is it as simple as as doing something like this:

```
if sys.version_info <= (3, 5):
    class PurePath:
else:
    class PurePath(os.PathLike):
```

Also while I found the changes to `resolve` in 3.6, I couldn't find the changes to `scandir` or `__fspath__`.

**Comment by ambv** [comment]
Remember that stubs need to parse as Python files. Your if/else example doesn't. Since PurePath is pretty long, repeating yourself is going to be painful. How about:
```
if sys.version_info >= (3, 6):
    _PurePathBase = os.PathLike
else:
    _PurePathBase = object

class PurePath(_PurePathBase):
    ...
```

**Comment by phouse512** [comment]
@ambv oh wow that makes a lot of sense. thanks!! didn't realize I could do it that way.
