### ISSUE TITLE
mypy 0.920 has incorrect typing for signal handler

### ISSUE THREAD

**Issue by gitpushdashf** [python/typeshed#6592]
Upgrading from mypy 0.910 to 0.920, I get this:

```
error: Argument 2 to "signal" has incompatible type "Callable[[int, FrameType], None]"; expected "Union[Callable[[int, Optional[FrameType]], Any], int, Handlers, None]"
```

https://docs.python.org/3/library/signal.html#signal.signal

**Comment by gitpushdashf** [comment]
Ah, my bad. You are absolutely right. I misread the output, thinking it was expecting a third argument for the handler. I guess this is behaving as expected, so will close it out.

Thank you!

**Comment by hauntsaninja** [comment]
Thanks for helping find potential issues in new releases!

**Comment by gitpushdashf** [comment]
No problem at all!

**Comment by hauntsaninja** [comment]
There's some more discussion here: https://github.com/python/typeshed/pull/5622#issuecomment-859697505
