### ISSUE TITLE
Complete six.moves

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#66]
There are a bunch of six.moves submodules (and other things) that aren't supported yet because there are no stubs yet for the module to which they refer. We should remember to update six.moves whenever we add stubs for such a module.

References:
- Unmerged PR that added everything: https://github.com/python/typeshed/pull/21
- Merged PR that added only those items that work: https://github.com/python/typeshed/pull/61
- Issue with a list of things to do: https://github.com/python/typeshed/issues/22
- Tool that generated the initial PR (I think): https://github.com/o11c/stubtool

**Comment by JelleZijlstra** [comment]
This issue covers the same ground as #22 which has more discussion.
