### ISSUE TITLE
Logger.getChild bad signature

### ISSUE THREAD

**Issue by randolf-scholz** [python/typeshed#6606]
The signature of `Logger.getChild` is

```python
def getChild(self, suffix: str) -> Logger: ...
```

However, this fails if one subclasses `Logger`, e.g. the following code

```
logger = MyLogger(...)
child: MyLogger = logger.getChild(...)
```

Raises `type[assignment]` error (expression has type "Logger", variable has type "MyLogger"). The signature should be

```python
def getChild(self: T, suffix: str) -> T: ...
```

where `T = TypeVar('T', bound=Logger)`. Cf. https://github.com/python/mypy/issues/1212 and https://github.com/python/typing/discussions/980

**Comment by JelleZijlstra** [comment]
Fixes in #6609
