### ISSUE TITLE
html.parser is missing 'rawdata' field

### ISSUE THREAD

**Issue by aresler** [python/typeshed#6621]
Code sample (tested with Python 3.9 / 3.10)

```python
from html.parser import HTMLParser
parser = HTMLParser()
parser.rawdata
```

But, `typeshed/stdlib/html/parser.pyi` stub seems to be missing `rawdata`, causing a false-positive.

**Comment by srittau** [comment]
Indeed. In fact, all attributes (`convert_charrefs`, `rawdata`, `lasttag`, `interesting`, and `cdata_elem`) are missing from `HTMLParser`. PR welcome!

**Comment by jpy-git** [comment]
I'd be interested in making a PR, will take a look now 😄
