### ISSUE TITLE
Add new builtin exception types from Python 3.11 - BaseExceptionGroup & ExceptionGroup

### ISSUE THREAD

**Issue by lancelote** [python/typeshed#6632]
Introduced in [Python 3.11][1] by [PEP 654][2]

```python-repl
>>> BaseExceptionGroup
<class 'BaseExceptionGroup'>

>>> ExceptionGroup
<class 'ExceptionGroup'>
```

[1]: https://docs.python.org/3.11/whatsnew/3.11.html
[2]: https://www.python.org/dev/peps/pep-0654/

**Comment by sobolevn** [comment]
Also: `__note__` if not added.

**Comment by lancelote** [comment]
Right, PR to add `__note__` - #6633.
