### ISSUE TITLE
Stubgen: functions that yield

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6646]
When there is a yield statement and no return statements inside a function, stubgen generates `-> None` for the return type, even though the correct thing to do would be something like `-> Generator[Any, Any, Any]`. These have to be fixed manually, e.g. #6636 in pygments. This issue is a reminder for me to grep for `yield` statements in pygments and fix anything I find.

**Comment by srittau** [comment]
This has been fixed in stubgen 0.920.
