### ISSUE TITLE
python-dateutil parserinfo attributes

### ISSUE THREAD

**Issue by lmar76** [python/typeshed#6682]
`WEEKDAYS` and `MONTHS` `parserinfo` attributes are annotate as:

```python
WEEKDAYS: list[tuple[str, str]]
MONTHS: list[tuple[str, str]]
```

See:

https://github.com/python/typeshed/blob/e1ae89874b4f1c6782b84c16c825400179008489/stubs/python-dateutil/dateutil/parser/__init__.pyi#L8

However, this is in contrast with the actual [parserinfo](https://github.com/dateutil/dateutil/blob/83ec82cb5e032ab31e5aae49902cf61be38ddfc2/src/dateutil/parser/_parser.py#L241) implementation where the `MONTHS` list contains a tuple of three items:

```python
    MONTHS = [("Jan", "January"),
              ("Feb", "February"), 
              ("Mar", "March"),
              ("Apr", "April"),
              ("May", "May"),
              ("Jun", "June"),
              ("Jul", "July"),
              ("Aug", "August"),
              ("Sep", "Sept", "September"),
              ("Oct", "October"),
              ("Nov", "November"),
              ("Dec", "December")]
```

In my opinion, the two attributes should be annotated as:

```python
WEEKDAYS: list[tuple[str, ...]]
MONTHS: list[tuple[str, ...]]
```

**Comment by srittau** [comment]
Sounds like a good idea.
