### ISSUE TITLE
stubtest is failing for mock

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6683]
https://github.com/python/typeshed/runs/4622929362?check_suite_focus=true

**Comment by srittau** [comment]
Interesting, there has been no new release. Maybe we could just remove mock as all supported Python 3 include `unittest.mock`, of which this is a backport. For Python 2, types-mock 4.0.4 is still available.

**Comment by srittau** [comment]
Actually, this does not support Python 2.

**Comment by srittau** [comment]
And it offers features from newer Python versions to older ones, although I'm not sure there have been many improvements to unittest.mock since 3.6.

**Comment by srittau** [comment]
I'll work on a fix.

**Comment by hauntsaninja** [comment]
(Probably just from the 0.930 upgrade? CI has third party git skipping logic)

**Comment by srittau** [comment]
The problem is that stubtest fails after the first failing distribution. Will fix.
