### ISSUE TITLE
Add typing stubs for regex package

### ISSUE THREAD

**Issue by jpy-git** [python/typeshed#6710]
I would like to add stubs for the [regex](https://github.com/mrabarnett/mrab-regex) package:
`This regex implementation is backwards-compatible with the standard 're' module, but offers additional functionality.`

I've found it really useful in a couple projects and it currently doesn't have stubs/typing. It's implementation is similar to to the stdlib `re` module so will look there for inspiration.

This should help close this [issue](https://github.com/mrabarnett/mrab-regex/issues/423) in the `regex` repo.

**Comment by srittau** [comment]
We generally accept stubs for all packages installable via PyPI on modern Python versions.

**Comment by jpy-git** [comment]
Cool it's available on [PyPI](https://pypi.org/project/regex/) so should be fine 👍
