### ISSUE TITLE
Type error: `sys.version_info == (3, 4)`

### ISSUE THREAD

**Issue by elazarg** [python/typeshed#672]
I have tried changing the signature of [`object.__eq__`](https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L38) to `(T, T)->bool`, and mypy warns about the comparison in [importlib/abc.pyi](https://github.com/python/typeshed/blob/master/stdlib/3/importlib/abc.pyi#L34):
```Python
    if sys.version_info == (3, 4):
```
[`_version_info`](https://github.com/python/typeshed/blob/master/stdlib/3/sys.pyi#L104) subtypes `Tuple[int, int, int, str, int]` and can never be equal to (3, 4).
```
>>> from sys import version_info
>>> version_info
sys.version_info(major=3, minor=4, micro=3, releaselevel='final', serial=0)
>>> version_info == (3, 4)
False
```
I think the generic signature is helpful, even though it's overly restrictive.

**Comment by gvanrossum** [comment]
I don't understand what you're trying to say, unless you just mean that the code in importlib/abc.pyi is wrong -- it should be `if sys.version_info[:2] == (3, 4):`.

**Comment by gvanrossum** [comment]
Can you submit a PR to fix the bug here?

--Guido (mobile)

**Comment by elazarg** [comment]
Done (#673).
