### ISSUE TITLE
How to mark version dependent modules?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6733]
Today I found out that `_bootlocale` module does not exists for recent versions of Python.

<img width="752" alt="Снимок экрана 2021-12-29 в 20 26 07" src="https://user-images.githubusercontent.com/4660275/147688090-62324b02-501b-4ddc-99f0-830400ca4bfa.png">

But, the file in typeshed is there for all python versions: https://github.com/python/typeshed/blob/master/stdlib/_bootlocale.pyi

So, the question is: how can we mark modules the same way we mark functions / classes with `sys.version_info` guards?

**Comment by AlexWaygood** [comment]
You want https://github.com/python/typeshed/blob/master/stdlib/VERSIONS, where `_bootlocale.pyi` is already marked as being only available in Python <= 3.9 🙂

**Comment by sobolevn** [comment]
Thanks!
