### ISSUE TITLE
How to mark platform dependent modules?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6734]
Now when I know about [VERSIONS file](https://github.com/python/typeshed/blob/master/stdlib/VERSIONS) I have a second question: what about `platform` specific modules?

Simple repro:

```python
import winreg
``` 

<img width="752" alt="Снимок экрана 2021-12-29 в 20 54 44" src="https://user-images.githubusercontent.com/4660275/147690232-cee31528-5e70-4308-bab6-ed60403bea2f.png">

Related https://github.com/python/typeshed/issues/6733

**Comment by hauntsaninja** [comment]
We don't have a good solution for that. I'd be in favour of putting the whole module under a `sys.platform` check (we used to do this for `sys.version_info` before `VERSIONS` and it worked passably well)

**Comment by AlexWaygood** [comment]
The whole of `posix.pyi` is under a `sys.platform` check: https://github.com/python/typeshed/blob/master/stdlib/posix.pyi

Seems sensible to do the same thing for `winreg`.

**Comment by sobolevn** [comment]
Ok, I will send a PR to winreg today!

> Could also complicate the specification of VERSIONS, but it'd require support from all type checkers.

I think that using something like `platform` spec in pip might be a good idea.

**Comment by AlexWaygood** [comment]
`curses` is not available on Windows. Do we want to put all the submodules under a `sys.platform` check? Or just add one in `curses.__init__`? Or not bother?

**Comment by Akuli** [comment]
I think it's fine to add a `sys.platform` check to all submodules. There's not too many of them.

**Comment by hauntsaninja** [comment]
Thanks everyone, seems like we're in a decent place.

Closing since I don't think there's anything more to do (unless someone feels strongly about pushing for a change to the `VERSIONS` format).
