### ISSUE TITLE
asyncio.create_task hints say you can pass any Awaitable, but you cannot pass asyncio.Tasks

### ISSUE THREAD

**Issue by alkasm** [python/typeshed#6770]
The following program passes mypy type checking, but fails at runtime:

```python
import asyncio
from typing import Awaitable

async def main() -> None:
    async def coro() -> Awaitable[None]: pass
    task = asyncio.create_task(coro())
    asyncio.create_task(task)

asyncio.run(main())
```

```
(venv) ➜ python --version
Python 3.9.6
(venv) ➜ mypy --version
mypy 0.930
(venv) ➜ mypy --strict example.py 
Success: no issues found in 1 source file
(venv) ➜ python example.py
Traceback (most recent call last):
  File ".../create-task-types/example.py", line 10, in <module>
    asyncio.run(main())
  File ".../python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File ".../create-task-types/example.py", line 7, in main
    asyncio.create_task(task)
  File ".../python3.9/asyncio/tasks.py", line 361, in create_task
    task = loop.create_task(coro)
  File ".../python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
TypeError: a coroutine was expected, got <Task pending name='Task-2' coro=<main.<locals>.coro() running at .../create-task-types/example.py:4>>
```

**Comment by sobolevn** [comment]
See https://mail.python.org/archives/list/typing-sig@python.org/thread/JSZ4Q7B7FBF5LBVG2V6AAHLCQJSMDEAK/ and https://github.com/python/typing/issues/801

**Comment by AlexWaygood** [comment]
In the absence of a `Not` type, a clunky workaround is to use an overload returning `NoReturn`, [like we do in `datetime.date.__sub__`](https://github.com/python/typeshed/blob/d43cd997a47513be3e34c32cc9ef96eb266611ed/stdlib/datetime.pyi#L72-L77). If we change `asyncio.create_task`, though, we should also change `asyncio.events.AbstractEventLoop.create_task`, and any subclasses of that that appear in the stdlib.

@alkasm, I don't know much about asyncio -- is a `Task` object the only kind of awaitable that is not accepted by `create_task`, or are there others?

**Comment by AlexWaygood** [comment]
From my reading of the source code, it looks like `asyncio.create_task` [passes the coroutine to `asyncio.events.AbstractEventLoop.create_task`](https://github.com/python/cpython/blob/0b58bac3e7877d722bdbd3c38913dba2cb212f13/Lib/asyncio/tasks.py#L337). Judging by [the source code of `asyncio.base_events.BaseEventLoop`](https://github.com/python/cpython/blob/0b58bac3e7877d722bdbd3c38913dba2cb212f13/Lib/asyncio/base_events.py#L380), which inherits from `AbstractEventLoop`, it looks like the `create_task` method of an event loop will then pass the coroutine to the constructor of an `asyncio.tasks.Task` object. The `Task` constructor [raises an error](https://github.com/python/cpython/blob/0b58bac3e7877d722bdbd3c38913dba2cb212f13/Lib/asyncio/tasks.py#L96) unless the coroutine passed to it passes an `inspect.iscoroutine` test. `inspect.iscoroutine` [only returns `True` if the object passed to it is an instance of `types.CoroutineType`](https://github.com/python/cpython/blob/0b58bac3e7877d722bdbd3c38913dba2cb212f13/Lib/inspect.py#L442).

**Comment by alkasm** [comment]
Yeah, it seems the type is simply too permissive---the input type should be a coroutine, not any awaitable. In addition to the `Task` constructor explicitly checking for a coroutine as @AlexWaygood mentions, the documentation _and_ the parameter name for `create_task` [explicitly mention coroutines](https://docs.python.org/3/library/asyncio-task.html#asyncio.create_task):

> `asyncio.create_task(coro, *, name=None)`
> Wrap the coro coroutine into a Task and schedule its execution. Return the Task object.

**Comment by AlexWaygood** [comment]
> The `Task` constructor raises an error unless the coroutine passed to it passes an `inspect.iscoroutine` test. 

As @Akuli [points out here](https://github.com/python/typeshed/pull/6779#issuecomment-1003691929), I misread the source code — `Task.__init__` passes the coroutine to `asyncio.coroutines.iscoroutine`, a completely different function to `inspect.iscoroutine`!!

**Comment by alkasm** [comment]
Thanks so much for digging into this rather nontrivial bug!
