### ISSUE TITLE
signal._HANDLER signature should accept signal._SIGNUM

### ISSUE THREAD

**Issue by asfaltboy** [python/typeshed#6797]
The `signal._SIGNUM` type is `Union` of `int` and the `signal.Signals` enum ([see reference](https://github.com/python/typeshed/blob/master/stdlib/signal.pyi#L63-L64)).

It seems likely to me that users who prefer to use Enum (e.g to avoid magic numbers in their code) will type their handlers with `signal.Signals`, I'm not sure why can't we accept the enum in the handler as well as `int`?

**Comment by srittau** [comment]
The handler is not supplied with an enum, but an `int`:

```
$ python3.9
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from signal import signal, Signals
>>> def handler(sig, _):
...     print(type(sig))
... 
>>> signal(Signals.SIGHUP, handler)
<Handlers.SIG_DFL: 0>
>>> <class 'int'>
```

**Comment by asfaltboy** [comment]
Ah I see, of course the handler should be able to accept any int even if not defined in the enum. Sorry for misunderstanding and thanks for the prompt response 🙇
