### ISSUE TITLE
Policy for `__main__.py` files?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6798]
I've noticed that for some reason we don't include typings for `__main__.py` files.

CPython:

```
» fd __main__.py .
Lib/asyncio/__main__.py
Lib/ctypes/test/__main__.py
Lib/ensurepip/__main__.py
Lib/idlelib/__main__.py
Lib/lib2to3/__main__.py
Lib/lib2to3/tests/__main__.py
Lib/test/__main__.py
Lib/test/test_asyncio/__main__.py
Lib/test/test_email/__main__.py
Lib/test/test_import/__main__.py
Lib/test/test_importlib/__main__.py
Lib/test/test_importlib/builtin/__main__.py
Lib/test/test_importlib/extension/__main__.py
Lib/test/test_importlib/frozen/__main__.py
Lib/test/test_importlib/import_/__main__.py
Lib/test/test_importlib/source/__main__.py
Lib/test/test_json/__main__.py
Lib/test/test_peg_generator/__main__.py
Lib/test/test_sqlite3/__main__.py
Lib/test/test_tools/__main__.py
Lib/test/test_warnings/__main__.py
Lib/test/test_zoneinfo/__main__.py
Lib/tkinter/__main__.py
Lib/turtledemo/__main__.py
Lib/unittest/__main__.py
Lib/unittest/test/__main__.py
Lib/unittest/test/testmock/__main__.py
PC/layout/__main__.py
Tools/c-analyzer/c_analyzer/__main__.py
Tools/c-analyzer/c_parser/__main__.py
Tools/c-analyzer/c_parser/preprocessor/__main__.py
Tools/c-analyzer/cpython/__main__.py
Tools/peg_generator/pegen/__main__.py
```

Typeshed:

```
» fd __main__.pyi .  
stdlib/@python2/__main__.pyi
stdlib/__main__.pyi
```

I've seen PRs like https://github.com/python/typeshed/pull/6665 that even remove `__main__.py` typings.

My question is: what is the policy for these files? 

Let's say I want to add `asyncio/__main__.pyi`. It has several useful definitions inside: https://github.com/python/cpython/blob/549e62827262264cda30455e10e315602129da72/Lib/asyncio/__main__.py And I can imagine that some projects like `ipython` / `rich` / etc can benefit from importing `REPLThread` for example.

**Comment by srittau** [comment]
`__main__` files are generally not important as they are designed to execute a program. This caused problems with stubtest in the past and I don't see how having stubs for them would benefit our users.

**Comment by JelleZijlstra** [comment]
Agree with @srittau. We can mention this in our docs somewhere.

**Comment by srittau** [comment]
Also, "are generally not important" should have been "are generally not imported".
