### ISSUE TITLE
`multiprocessing` is missing several files

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#6799]
Directory in CPython: https://github.com/python/cpython/tree/main/Lib/multiprocessing
Directory in typeshed: https://github.com/python/typeshed/tree/master/stdlib/multiprocessing

- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/forkserver.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/heap.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_fork.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_forkserver.py
- [ ] https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_spawn_posix.py
- [ ] https://github.com/python/cpython/blob/main/Lib/multiprocessing/popen_spawn_win32.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/reduction.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/resource_sharer.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/resource_tracker.py
- [x] https://github.com/python/cpython/blob/main/Lib/multiprocessing/util.py

**Comment by hauntsaninja** [comment]
Yup. All of these are undocumented, so relatively low pri (as per checklist in https://github.com/python/typeshed/issues/4545 , issue also contains a script to get list of missing modules in stdlib).

**Comment by kkirsche** [comment]
Once the open merge requests are completed, I'll move onto the next series of files. I'm trying to avoid creating too many merge requests at any one time.

I seem to have missed where the script was in the linked issue to locate files/modules without stubs, but I'd be happy to address other modules if I can identify how to locate those.

**Comment by kkirsche** [comment]
Moving onto last two hopefully today, depending on my meeting schedule. If all goes to plan this should be able to be closed by the end of the week

**Comment by kkirsche** [comment]
This will be fixed when the remaining PR's are completed.

Note though that there are some additional opportunities in multiprocessing to expand stubs further, if interested
