### ISSUE TITLE
multiprocess.pool.ThreadPool is missing imap_unordered

### ISSUE THREAD

**Issue by DarwinAwardWinner** [python/typeshed#683]
I'm adding mypy to my Python project, and I'm getting:

    rganalysis/main.py:181: error: "ThreadPool" has no attribute "imap_unordered"

It looks like ThreadPool is missing a type annotation for this method.

**Comment by gvanrossum** [comment]
Thanks for the report! Do you want to contribute a PR to fix this?

**Comment by DarwinAwardWinner** [comment]
Sure, I'll take a stab at it.
