### ISSUE TITLE
mypy raise `Module has no attribute "__version__"` for urllib3 in linux

### ISSUE THREAD

**Issue by AChenQ** [python/typeshed#6889]
### Bug Report
mypy will raise urllib3 has no attribute "__version__" error when I install `types-urllib3`

### To Reproduce

```python
# test.py
import urllib3
print(urllib3.__version__)
```

```Shell
$ pip install types-urllib3
Collecting types-urllib3
  Downloading types_urllib3-1.26.3-py3-none-any.whl (12 kB)
Installing collected packages: types-urllib3
Successfully installed types-urllib3-1.26.3

$ mypy test.py --ignore-missing-imports
test.py:2: error: Module has no attribute "__version__"
Found 1 error in 1 file (checked 1 source file)
```

### Environment
 * Mypy version used: 0.91
 * Python version used: 3.8.0
  * Operating system and version: ubuntu 18.04

**Comment by hauntsaninja** [comment]
Thanks, PR welcome!

(for those wondering, stubtest doesn't complain about this because urllib3 defines `__all__` and `__version__` is not in it)
