### ISSUE TITLE
Remove urllib3 types (not before October 2023)

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6898]
#6858 added stubs for urllib3. It might have been a mistake, because urllib3 seems to have its own type annotations and even a `py.typed` marker, making the stubs unnecessary.

**Comment by hauntsaninja** [comment]
They wrote up a nice article about the process too :-) https://sethmlarson.dev/blog/2021-10-18/tests-arent-enough-case-study-after-adding-types-to-urllib3

**Comment by srittau** [comment]
The latest released version of urllib3 (1.26.8) doesn't include the marker yet. I assume that the next major version, which will drop Python 2 support, will include it. Until six months after that version's release, we can drop our version of the packages.

**Comment by JelleZijlstra** [comment]
Note that the master branch of urllib3 is *not* what it is currently releasing; the current release doesn't have the types yet. This confused us for a while in #6892.

**Comment by kkirsche** [comment]
As a status update here, the migration plan is documented here:
https://urllib3.readthedocs.io/en/stable/v2-roadmap.html#release-and-migration-schedule

In this, it includes:
> Release v1.26.0 with deprecation warnings for v2.0.0 breaking changes. This will be the last non-patch release within the v1.x stream.

The current release is 1.26.11 and includes the warnings:
https://github.com/urllib3/urllib3/releases/tag/1.26.11

At this time, the following item has not yet occurred:
> Release v2.0.0-alpha1 once all breaking changes have been completed. We’ll wait for users to report issues, bugs, and unexpected breakages at this stage to ensure the release v2.0.0 goes smoothly.

Current 2.0 progress can be viewed here, and is currently at 86% complete, with at least one open pull request to address dropping older OpenSSL versions:
https://github.com/urllib3/urllib3/milestone/6

**Comment by kkirsche** [comment]
2.0.0 was released on Wednesday, April 26, 2023, at 1:20 PM EDT

https://github.com/urllib3/urllib3/releases/tag/2.0.0

**Comment by AlexWaygood** [comment]
We should remember to do https://github.com/python/typeshed/issues/10142 when we do this (it can't be done before, or pyright will start flagging discrepancies between the inline types in `urllib3` and the stubs for `urllib3` we have in typeshed)
