### ISSUE TITLE
The definition of Awaitable is wrong

### ISSUE THREAD

**Issue by gvanrossum** [python/typeshed#690]
The entire inheritance tree around Awaitable and Coroutine needs careful review. See some discussion in a [code review for typing.py docs](http://bugs.python.org/review/28644/diff2/19123:19139/Doc/library/typing.rst).

**Comment by JelleZijlstra** [comment]
The current definition of Awaitable in typeshed is:
```python
class Awaitable(Generic[_T_co]):
    @abstractmethod
    def __await__(self) -> Generator[Any, None, _T_co]: ...
```
Looking at the discussion you linked, I'm not sure what the exact problem is. Is it the return type for `__await__`?

**Comment by gvanrossum** [comment]
Let's close it. I don't recall either, but the files in that dir have been improved a lot by people using asyncio in the past 5 months.

**Comment by ktbarrett** [comment]
Maybe I should make a new issue, but the type of the send parameter seems incorrect. I'm running into that issue currently. I don't see why it must be `None`.

The link in OP is broken, so maybe that had more context.

**Comment by gvanrossum** [comment]
I think this is the issue referred to: https://bugs.python.org/issue28644 -- not that much there though.

Anyway, @ktbarrett if you're pretty sure you have found a bug, please open a new issue here; or if you're not quite sure, you can try asking on discuss.python.org.
