### ISSUE TITLE
_SplitCondition type alias in builtins.pyi has misplaced comma

### ISSUE THREAD

**Issue by erictraut** [python/typeshed#6902]
The `_SplitCondition` type alias recently added to to `builtins.pyi` contains a bug. A comma is in the wrong place.

```python
tuple[type[BaseException, ...]]
```

should be

```python
tuple[type[BaseException], ...]
```

I'm surprised that this passed CI. Is this because CI doesn't cover Python 3.11 at this time? Perhaps this should be added to the matrix?

**Comment by JelleZijlstra** [comment]
Thanks, I submitted a fix. I don't think any of our CI runs in 3.11. Would pyright support running in 3.11 mode already?

**Comment by Akuli** [comment]
Indeed, the CI fails with pyright enabled for Python 3.11:

```
  /home/runner/work/typeshed/typeshed/stdlib/builtins.pyi:1667:71 - error: "..." not allowed in this context
  /home/runner/work/typeshed/typeshed/stdlib/builtins.pyi:1667:71 - error: Too many type arguments provided for "Type"; expected 1 but received 2
```
