### ISSUE TITLE
Inconsistencies between `__init__` and `__new__`

### ISSUE THREAD

**Issue by erictraut** [python/typeshed#6905]
I just implemented a new check in pyright called `reportInconsistentConstructor` that detects inconsistencies between the `__init__` and `__new__` methods. It's disabled by default but can be enabled in the configuration. It's in pyright 1.1.207, which I just published.

The check is pretty conservative, but it does identify three places in typeshed that look like legitimate problems.

1. The class `WeakMethod` in `weakref.pyi` defines a `__new__` that is incompatible with the `__init__` declared in its parent class `ReferenceType`.
2. The class `_TokenType` in `pygments/token.pyi` defines an `__init__` that is incompatible with the `__new__` in `tuple[str]`.
3. The class `CascadeOptions` in `SQLAlchemy/sqlalchemy/orm/util.pyi` defines a `__new__` that is incompatible with the `__init__` in its parent class `frozenset[Any]`.

If/when these are addressed, we might want to update pyright to 1.1.207 and enable the new diagnostic check to prevent future inconsistencies from being introduced.

**Comment by srittau** [comment]
Sounds like a good plan.

**Comment by AlexWaygood** [comment]
Relatedly (but slightly tangentially), can anybody explain to me why `classmethod.__new__` and `classmethod.__init__` have different signatures in `builtins`? I've never really understood why, and there's no comment clarifying it:

https://github.com/python/typeshed/blob/5d206358907c419802cd9afcfcc83cce4f01bebb/stdlib/builtins.pyi#L117-L118

(Same issue for `staticmethod`.)
