### ISSUE TITLE
Remove flake8-plugin-utils stubs (not before Jan 2024)

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6913]
A `py.typed` file was just added: https://github.com/afonasev/flake8-plugin-utils/pull/78

**Comment by srittau** [comment]
There's been no release since. We can remove this six months after a release with `py.typed`.

**Comment by kkirsche** [comment]
For others coming to this in the future,

flake8-plugin-utils was last released on May 5, 2021 per https://pypi.org/project/flake8-plugin-utils/#history while the referenced pull request was submitted on December 6, 2021 and merged on January 13, 2022.

**Comment by sobolevn** [comment]
Released: https://github.com/afonasev/flake8-plugin-utils/pull/78

**Comment by AlexWaygood** [comment]
A small bug in stubsabot was the reason why we didn't get an automated PR to mark these stubs as obsolete last night:

- #10368

**Comment by AlexWaygood** [comment]
Marked as obsolete in #10373 🎉
