### ISSUE TITLE
calendar missing data attributes day_name, day_abbr, month_name, month_abbr

### ISSUE THREAD

**Issue by henridwyer** [python/typeshed#692]
I'm not sure what types they are.

**Comment by phouse512** [comment]
@henridwyer do you have a little bit more information to make this issue easier to fix? what version of python where you using?

**Comment by henridwyer** [comment]
@phouse512 As far as I understand, to fix this we need to add types for those variables into the stub files here (they are currently missing day_name, day_abbr, month_name, month_abbr):
https://github.com/python/typeshed/blob/master/stdlib/2/calendar.pyi
https://github.com/python/typeshed/blob/master/stdlib/3/calendar.pyi

Is that right?

For information, I was using python 3.5, mypy 0.45

I'm still figuring out how this works, and I'm happy to provide more information

**Comment by phouse512** [comment]
@henridwyer yep those would be the spots we would need to adjust for this. I'm not too familiar with the calendar module so I found the documentation here:

https://docs.python.org/2/library/calendar.html#calendar.day_name
https://docs.python.org/3.5/library/calendar.html#calendar.day_name

From those, I think we could come up with a fix. Those attributes are what you are referring to correct?

**Comment by henridwyer** [comment]
Those are the attributes I'm referring to - @phouse512 I created a pull request
