### ISSUE TITLE
Signature of `dict.__ior__` is unsafe

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#6927]
Here is the signature of `MutableMapping.update` (inherited by `dict`):

https://github.com/python/typeshed/blob/af8e37d2736d3a6fbed8f5dfad71580dd417c612/stdlib/typing.pyi#L491-L496

Here is the signature of `dict.__ior__`:

https://github.com/python/typeshed/blob/af8e37d2736d3a6fbed8f5dfad71580dd417c612/stdlib/builtins.pyi#L874

They do the same thing, but have very different signatures. They should probably have the same signature (other than `__ior__` returning a `dict` rather than `None`).

**Comment by Akuli** [comment]
It should also return `Self` instead of a hard-coded `dict`:

```
>>> class Foo(dict): pass
... 
>>> type(Foo().__ior__({}))
<class '__main__.Foo'>
```

**Comment by AlexWaygood** [comment]
Looks like there's also an issue with `UserDict`. It [has `__or__`, `__ror__` and `__ior__` at runtime](https://github.com/python/cpython/blob/ff7703c4b609a697ada8165fd1c52a73404b6d07/Lib/collections/__init__.py#L1129), but [not in the stub](https://github.com/python/typeshed/blob/989fe1180655c01cc80f448ce752cb2dc49b4bed/stdlib/collections/__init__.pyi#L38).

@hauntsaninja, any idea why stubtest hasn't flagged these missing methods?

**Comment by hauntsaninja** [comment]
https://github.com/python/mypy/blob/0a03ba0d11136647ac74dc5fceac9b2cceb1f673/mypy/stubtest.py#L259

**Comment by AlexWaygood** [comment]
> There's some special casing for dunders: https://github.com/python/mypy/blob/0a03ba0d11136647ac74dc5fceac9b2cceb1f673/mypy/stubtest.py#L259 As the comment acknowledges, could probably work to remove some of it

Helping out with improving stubtest has been on my to-do list for a while, I'll get round to it at some point I promise :) thanks for the info!
