### ISSUE TITLE
io classes incomplete in Python 2

### ISSUE THREAD

**Issue by ddfisher** [python/typeshed#694]
`IOBase` and `BufferedIOBase` have no methods in Python 2.  They are, however, implemented in `_io` -- we should consider copying them over.

**Comment by JukkaL** [comment]
If they are the same class, we could just expose one of the definitions in the other module. For example, we can add `from _io import IOBase as IOBase` into the `io` stub.

**Comment by JelleZijlstra** [comment]
I think #1395 fixed this.
