### ISSUE TITLE
Update redis stubs to 4.1.1

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6951]
https://github.com/python/typeshed/runs/4847268271?check_suite_focus=true

**Comment by srittau** [comment]
redis 4.1.1 was released yesterday. The diff seems huge, though. #6952 should fix CI for now, although we should update redis to 4.1.1, of course.

**Comment by hauntsaninja** [comment]
We'll need to revert this allowlist change: https://github.com/python/typeshed/pull/6957/commits/1b4bda2c47b8f72f32483ce2fe11a7c646c82edf
