### ISSUE TITLE
Update cachetools stubs to 5.0

### ISSUE THREAD

**Issue by jerr0328** [python/typeshed#6953]
Cachetools updated to 5.0.0 (https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst#v500-2021-12-21) so the stubs should be updated to support that.

I also want to point out that some types are dependant on parameters. For instance, the [TTLCache](https://cachetools.readthedocs.io/en/stable/#cachetools.TTLCache) accepts a function for the `timer`, and the `ttl` should be something that can be added to the result of `timer()`. Currently it's `float`, but in the documentation, it could be `timedelta` if `timer` is set to `datetime.now`. I don't know if this should be split off into its own issue or just handled when upgrading the types.

**Comment by AlexWaygood** [comment]
Fixed by https://github.com/python/typeshed/pull/7455
