### ISSUE TITLE
Should urllib.request.Request use Mapping-like protocol for headers?

### ISSUE THREAD

**Issue by q0w** [python/typeshed#6963]
Request headers and unredirected_hdrs сould use a custom protocol like `SupportsItemsAndItemAccess` with 4 methods: `items`,  `__getitem__ `, `__setitem__`, `__delitem__`.

**Comment by JelleZijlstra** [comment]
I haven't checked the details, but if this is correct and useful for your code, let's go for it.

**Comment by q0w** [comment]
My bad, it should be MutableMapping
