### ISSUE TITLE
Noticing stubtest failures

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#6972]
Occasionally the nightly stubtest run fails. About 6 weeks ago, I wrote the following script, which checks whether the last run failed, and if it did, it adds a reminder for me to fix it:

```
#!/bin/bash
date
url="https://api.github.com/repos/python/typeshed/actions/workflows/stubtest.yml/runs?per_page=1"
if curl "$url" -H "Accept: application/vnd.github.v3+json" | grep failure; then
    echo $(date +'%Y-%m-%d') ONCE "typeshed: checking all stubs with stubtest is failing" >> ~/.tasklist
fi
```

I set this to run whenever I log in. When I see the reminder in my task list, I usually find the failure on github and create an issue such as #6683, #6501, #6855 or #6971.

This works, but relying on a script running on one maintainer's personal computer doesn't feel right. We could automate creating the issue, but the catch is that we will get a spam of several issues if stubtest is broken for several days: https://github.community/t/create-an-issue-case-the-workflow-fails/17247

**Comment by srittau** [comment]
I'm fine with this. If we don't manage to fix the problem within a day, we can always disable the workflow quite easily via the menu on https://github.com/python/typeshed/actions/workflows/stubtest.yml.

Also, according to [this page](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/notifications-for-workflow-runs), exactly one maintainer gets email notifications about failed runs. It's not me at the moment, though.

**Comment by JelleZijlstra** [comment]
I get the emails. I've been remiss in fixing them though.
