### ISSUE TITLE
Paramiko/client : connect() sock argument should accept a Channel 

### ISSUE THREAD

**Issue by Salamandar** [python/typeshed#6983]
Issue is here:
https://github.com/python/typeshed/blob/556e623a8163062eb6929dd530e2bae120ceba07/stubs/paramiko/paramiko/client.pyi#L31

Problematic code : 
```
import paramiko

client: paramiko.SSHClient = paramiko.SSHClient()
client.connect(...)
channel: paramiko.Channel = client.get_transport().open_channel(...)

client_bis: paramiko.SSHClient = paramiko.SSHClient()
client_bis.connect(sock=channel)
```

mypy error code:
```
Argument "sock" to "connect" of "SSHClient" has incompatible type "Channel"; expected "Optional[socket]
```

Paramiko doc : https://docs.paramiko.org/en/stable/api/channel.html
> A Channel is meant to behave like a socket, and has an API that should be indistinguishable from the Python socket API.

I don't know if the issue should be fixed where the Channel is defined or where it's used.

**Comment by itaisteinherz** [comment]
Would typing the `sock` argument as `socket.socket | paramiko.Channel | None` be the correct solution in this case?

**Comment by Salamandar** [comment]
I'm pretty sure it would, yes.
