### ISSUE TITLE
Add tests for stubs

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#7]

**Comment by vlasovskikh** [comment]
See also jquery.d.ts and jquery-tests.ts from [DefinitelyTyped TypeScript stubs repository](https://github.com/borisyankov/DefinitelyTyped/tree/master/jquery).

**Comment by gvanrossum** [comment]
Let me see if I can come up with a simple .travis.yml that installs mypy and runs its tests. (Hopefully I can hack my way around mypy's dependency on typeshed. :-)

**Comment by matthiaskramm** [comment]
It's probably (hopefully?) enough to run only the "stub" tests of mypy.

**Comment by gvanrossum** [comment]
Wow, this already found stuff! See https://github.com/python/typeshed/pull/63.

**Comment by gvanrossum** [comment]
Sigh.

**Comment by gvanrossum** [comment]
These tests still don't catch everything there is to catch. E.g. they didn't catch the asyncio issue (see #91, #89, #81).

**Comment by gvanrossum** [comment]
But I think this is the best we can and should do -- we can't afford to test stubs against the implementation.
