### ISSUE TITLE
tokenize.generate_tokens/tokenize doesn't accept readline with int arg

### ISSUE THREAD

**Issue by palfrey** [python/typeshed#7003]
[tokenize.generate_tokens](https://docs.python.org/2.7/library/tokenize.html#tokenize.generate_tokens) documents it as taking a callable with the interface for `readline`, which https://github.com/python/typeshed/blob/master/stdlib/%40python2/builtins.pyi#L1160 (and similarly https://github.com/python/typeshed/blob/master/stdlib/io.pyi#L129) documents as `Callable[[int], str]`, but `generate_tokens` and `tokenize` (https://github.com/python/typeshed/blob/master/stdlib/tokenize.pyi#L49) document it as `Callable[[], str]` (or bytes, depending) both without the size arg

**Comment by hauntsaninja** [comment]
You've linked the Python 2 documentation, whereas Python 3's documentation is pretty clear that `Callable[[], str]` is correct:

> Like tokenize(), the readline argument is a callable returning a single line of input. However, generate_tokens() expects readline to return a str object rather than bytes.

https://docs.python.org/3/library/tokenize.html#tokenize.generate_tokens

The Python 2 code also calls the `readline` function without any arguments: https://github.com/python/cpython/blob/11fc030b6f9294030f0baa15f3bd4e2293e260e4/Lib/tokenize.py#L311 , so `Callable[[int], str]` is definitely incorrect.

Note that it's not quite right to say ` def readline(self, __size: int = ...) -> str: ...` is exactly a `Callable[[int], str]`, it's also very much a `Callable[[], str]`!

Looking at the Python 2 code,

**Comment by palfrey** [comment]
> The Python 2 code also calls the `readline` function without any arguments: https://github.com/python/cpython/blob/11fc030b6f9294030f0baa15f3bd4e2293e260e4/Lib/tokenize.py#L311 , so `Callable[[int], str]` is definitely incorrect.

That gets tricky, because then it means calling it with `io.StringIO(text).readline` (as https://github.com/gristlabs/asttokens does which is the place I've hit this in) has the wrong arg type, which feels wrong!

**Comment by hauntsaninja** [comment]
Okay, looking at the issue you linked, I think the problem might be that on Python 2, `io.StringIO` is annotated as `def readline(self, limit: int = ...) -> unicode: ...`, so you actually want to accept `Callable[[], unicode]`

**Comment by palfrey** [comment]
> Okay, looking at the issue you linked, I think the problem might be that on Python 2, `io.StringIO` is annotated as `def readline(self, limit: int = ...) -> unicode: ...`, so you actually want to accept `Callable[[], unicode]`

The Python 3 `io.StringIO` `readline` is done as `def readline(self, __size: int = ...) -> str`, which seems to have the same argument issues (well, the return type variation, but I think that's just Python 2/3 string handling)

OTOH `IOBase` on Python 3 has a `readline` with `def readline(self, __size: int | None = ...) -> bytes: ...` - note the `None`, where as `IOBase` on Python 2 is `def readline(self, limit: int = ...) -> bytes: ...` without a `None`

I was expecting `readline` to be defined the same way in all these places (or at least the same for all definitions within a Python major version), and it appears to not be!

**Comment by Akuli** [comment]
The argument types are correct, at least on Python 3. If you have `def readline(self, limit: int = ...)`, or `def readline(self, limit: int | None = ...)`, then the `readline` method can be treated as `Callable[[], return_type]` or `Callable[[int], return_type]`. And it accepts None on Python 3:

```
>>> import io
>>> io.StringIO("blah\n").readline(None)
'blah\n'
```

I no longer have Python 2 installed, but if `None` works on Python 2 too, feel free to make a new pull request that changes the Python 2 stubs to `int | None`.

**Comment by palfrey** [comment]
> ```
> >>> import io
> >>> io.StringIO("blah\n").readline(None)
> 'blah\n'
> ```
> 
> I no longer have Python 2 installed, but if `None` works on Python 2 too, feel free to make a new pull request that changes the Python 2 stubs to `int | None`.

That code (well, with arg `u"blah\n"`) works on Python 2.7.16. I've submitted https://github.com/python/typeshed/pull/7041 and just seeing what mypy_primer comes back with

**Comment by JelleZijlstra** [comment]
Doesn't seem like there's anything left to do here.
