### ISSUE TITLE
mypy_extensions trait type signature

### ISSUE THREAD

**Issue by hmc-cs-mdrissi** [python/typeshed#7016]
The current implementation of [trait](https://github.com/python/mypy_extensions/blob/master/mypy_extensions.py#L143) in mypy_extensions is,

```python
def trait(cls):
    return cls

```

The current type [stub](https://github.com/python/typeshed/blob/master/stubs/mypy-extensions/mypy_extensions.pyi#L43) is,

```python
# This is intended as a class decorator, but mypy rejects abstract classes
# when a Type[_T] is expected, so we can't give it the type we want
def trait(cls: Any) -> Any: ...
```

The type stub produces a lot of type errors from pyright when run on mypy's [type_visitors](https://github.com/python/mypy/blob/master/mypy/type_visitor.py) file as Any return type causes the class to lose it's generic arguments.

I'm unsure the type stub comment is true today as it was written 4 years ago and hopefully mypy better handles abstract classes/decorators. Does mypy still have issues with abstract classes and class decorators? Would it be fine to make a small pr that updates the type stub to,

```python
def trait(cls: type[_T]) -> type[_T]: ...
```

or

```python
def trait(cls: _T) -> _T: ...
```

The former is more true with intent of usage while latter corresponds to the implementation. Either are much better then making a class turn into Any which confuses class hierarchy pretty badly.

**Comment by srittau** [comment]
It's at  least worth trying to change it.
