### ISSUE TITLE
Using types-jsonschema 4.4.0, mypy does not consider `jsonschema.validators.Draft7Validator` a type

### ISSUE THREAD

**Issue by DMRobertson** [python/typeshed#7028]
(I'm not sure if this is best filed as an issue against typeshed or mypy. Happy to move this if it's the latter.)

The snippet

```
import jsonschema
x: jsonschema.Draft7Validator
```

does not typecheck on with types-jsonschema 4.4.0. 

```
error: Variable "jsonschema.validators.Draft7Validator" is not valid as a type  [valid-type]
```

For cross referencing, we noticed this [here](https://github.com/matrix-org/synapse/pull/11813#issuecomment-1020459343).

The snippet above _does_ type-check with 4.3.0, where `Draft7Validator` was annotated as `Any`. The change was made in https://github.com/python/typeshed/pull/7025 .

Are we misunderstanding or misusing `Draft7Validator` - is it not expected to be a type like this? If not, perhaps this is a problem in mypy rather than the stubs?

For what it's worth: mypy's documentation [suggests](https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases) that `tp: Type[_Validator]` is considered a "variable of type `_Validator`". Perhaps mypy's complaint is that `tp`'s value could be a replaced with a different subtype of `_Validator` at runtime? With that in mind, I tried patching the stubs to read `Draft7Validator: Final[type[_Validator]]` but this didn't seem to appease the type gods.

**Comment by DMRobertson** [comment]
Come to think of it, maybe `Draft7Validator = NewType("Draft7Validator", _Validator)` would do the trick?

**Comment by Akuli** [comment]
We should probably just use empty classes with `_Validator` as a base class, as in `class Draft7Validator(_Validator): ...`. At runtime, jsonschema has a function that creates a new validator class, and making new classes in typeshed is the closest we can get to that.
