### ISSUE TITLE
Stubs for `filecmp` are missing `Pathlike` for `common` argument

### ISSUE THREAD

**Issue by bersbersbers** [python/typeshed#7034]
`bug.py`:
```python
"""Demo mypy bug."""
import filecmp
from pathlib import Path

d = Path.home()
filecmp.cmpfiles(d, d, d.glob("*"))
```

`mypy bug.py`:
```
bug.py:6: error: Value of type variable "AnyStr" of "cmpfiles" cannot be "Path"
Found 1 error in 1 file (checked 1 source file)
```

I guess `common` should be `Iterable[AnyStr | PathLike[AnyStr]]`:
https://github.com/python/typeshed/blob/7bc9c1625eb0df0500e70de96f3e1a698bb8c05a/stdlib/filecmp.pyi#L16-L18

Related: https://github.com/python/typeshed/issues/3858, https://github.com/python/typeshed/pull/3864

**Comment by srittau** [comment]
Sounds right. All arguments are just passed to to `os.path.join()`, which accepts `PathLike`s. PR welcome!

**Comment by itaisteinherz** [comment]
I'd like to work on this.

**Comment by bersbersbers** [comment]
Will I have to wait for a new release of `mypy` for this to be effective or is there another way to update the `typeshed`? E.g., uninstalling and installing `mypy` did not help.

**Comment by AlexWaygood** [comment]
> Will I have to wait for a new release of `mypy` for this to be effective or is there another way to update the `typeshed`? E.g., uninstalling and installing `mypy` did not help.

If you clone typeshed, you can use mypy with the `--custom-typeshed-dir` option. But yeah, you'll have to wait until [mypy 0.940](https://github.com/python/mypy/issues/12021) (at least) for mypy's vendored copy of these stubs to be updated.

**Comment by bersbersbers** [comment]
Works great, thanks everybody!

**Comment by bersbersbers** [comment]
Btw, after cloning, `MYPYPATH=/data/bers/typeshed/stdlib mypy bug.py` also works for this example.

**Comment by bersbersbers** [comment]
For the record, mypy 0.942 has not yet picked this up (in line with the history of the typeshed subdirectory at https://github.com/python/mypy/commits/v0.942/mypy/typeshed). https://github.com/python/mypy/pull/12321 should have it at one point.
