### ISSUE TITLE
pymysql Connection missing __enter__ and __exit__

### ISSUE THREAD

**Issue by mike-hart** [python/typeshed#7044]
When using `with pymysql.connect(various, connection, details) as connection:` mypy gives the following errors

```
        # "Connection[DictCursor]" has no attribute "__enter__"
        # "Connection[DictCursor]" has no attribute "__exit__"
```

`pymysql.connections.Connection` has both `__enter__` and `__exit__` methods (https://github.com/PyMySQL/PyMySQL/blob/b12efdb6c1baa55e58a4384271e33a7351d554d5/pymysql/connections.py#L355) but the type declarations appear to be missing them.

There has been a bit of back and forth with PyMySQL regarding support for context managers over the last few years (see https://github.com/PyMySQL/PyMySQL/pull/886 for the most recent discussion) but the current 1.0.x release series seems to have settled on using it for managing connection closure.

**Comment by Akuli** [comment]
We currently aim to support the latest 1.0.x release. PR welcome :)
