### ISSUE TITLE
Infer `defaultdict`/`Counter` key type of `str` from kwargs init

### ISSUE THREAD

**Issue by KotlinIsland** [python/typeshed#7045]
```py
from collections import defaultdict

reveal_type(defaultdict(a=1))  # defaultdict[<nothing>, int]
```

**Comment by KotlinIsland** [comment]
Same thing with `reveal_type(Counter(a=1))`

**Comment by srittau** [comment]
The constructors of these two classes should have similar overloads to `dict`, which doesn't has this problem.

**Comment by hauntsaninja** [comment]
I believe mypy has some special casing for dict

**Comment by AlexWaygood** [comment]
There's a similar issue with mapping `update` methods too (see the second bullet point of https://github.com/python/typeshed/issues/6056#issuecomment-999309201)

**Comment by AlexWaygood** [comment]
Does the same issue here not also apply to:

- `weakref.WeakValueDictionary`: https://github.com/python/typeshed/blob/6746e83f52ed0125e03d719e232487e00aad7779/stdlib/weakref.pyi#L35
- `weakref.WeakKeyDictionary`: https://github.com/python/typeshed/blob/6746e83f52ed0125e03d719e232487e00aad7779/stdlib/weakref.pyi#L73
- _Maybe_ `collections.UserDict`? Though as the comment points out, we're trying to keep that one in sync with `dict.__init__` https://github.com/python/typeshed/blob/6746e83f52ed0125e03d719e232487e00aad7779/stdlib/collections/__init__.pyi#L48

?

**Comment by AlexWaygood** [comment]
Mappings are really hard to type :(

**Comment by srittau** [comment]
I haven't looked at those, but I wouldn't be surprised if there are more instances of this.
