### ISSUE TITLE
Python error on Redis type parameter

### ISSUE THREAD

**Issue by noahg2** [python/typeshed#7096]
I'm noticing what seems to be a disagreement regarding generics between the type stubs for `redis` and the implementation. In particular, the type stubs indicate via `mypy` that the Redis client takes a type parameter, but Python throws an error when it encounters this in practice. 

As a simple example, if I have `demo.py` as follows:
```python3
from redis import Redis

def foo(redis: Redis) -> None:
    pass
```

I get the following from `mypy`
```
> mypy --strict demo.py
demo.py:3: error: Missing type parameters for generic type "Redis"
Found 1 error in 1 file (checked 1 source file)
```

If I give it a type parameter, then Python throws an error
```python3
def foo(redis: Redis[bytes]) -> None:
    pass
```
```
> python demo.py
Traceback (most recent call last):
  File "C:\Users\gilenoa\Development\redis-demo\demo.py", line 3, in <module>
    def foo(redis: Redis[bytes]) -> None:
TypeError: 'type' object is not subscriptable
```
`mypy` thinks this is correct, however
```
> mypy --strict demo.py
Success: no issues found in 1 source file
```
My initial thought is that `mypy` is referencing the `Generic[_StrType]` in [this line](https://github.com/python/typeshed/blob/f86f096e1ce6d414d726b75560368807b5759260/stubs/redis/redis/client.pyi#L70) when making that call. I don't notice an equivalent declaration in the `redis` package sources. I'm still familiarizing myself with type checking in Python, so I am not entirely sure if the stub is incorrect, or if this error is originating somewhere else.

OS: Windows 10
Python: 3.9.7
mypy: 0.931
redis: 4.1.2
types-redis: 4.1.13

**Comment by srittau** [comment]
The `Redis` class is not generic at runtime. Therefore you have to either quote the type annotation or use `from __future__ import annotations` so that no error is thrown at runtime.
