### ISSUE TITLE
Commented-out `pydoc.Scanner` class

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#7099]
In the stubs for both the Python 3 stdlib, and the Python 2 stdlib, there's a strange commented-out `Scanner` class in `pydoc.pyi`:

https://github.com/python/typeshed/blob/023e21dedfde6c2252626e20f629d94cb7ebe054/stdlib/%40python2/pydoc.pyi#L220-L227

The class seems [not to have existed](https://bugs.python.org/issue11182) since 2013, so I think it can be safely deleted from the Python 3 stdlib stubs (unless anyone disagrees). Given its "undocumented and unused" status (and the fact that nobody appears to have complained about the fact that it's been commented out in the stubs for a long time), I think it can probably be deleted from the Python 2 stdlib as well. It [does _exist_](https://github.com/python/cpython/blob/8d21aa21f2cbc6d50aab3f420bb23be1d081dac4/Lib/pydoc.py#L1970-L1991) in the last-released version of Python 2.7, however.

Thoughts?

**Comment by AlexWaygood** [comment]
Should we add it back to the Python 2 stubs? It is commented out in both.

**Comment by Akuli** [comment]
I think we should avoid touching the Python 2 stubs in general, and only fix them when someone specifically needs things to work in Python 2. See  #5049 for discussion.
