### ISSUE TITLE
google.cloud.ndb stubs incorrect argument for various validators

### ISSUE THREAD

**Issue by davidn** [python/typeshed#7103]
I have [some code](https://github.com/davidn/filter-feed/blob/9f6e616c9c39667a0b421358ef498d4bc1617c2d/filter_feed.py) using `google.cloud.ndb` that has started failing pytype checks. The core of it is:

```py
from google.cloud import ndb

def validate_url(prop, value):
    # some assert on value
    return value

def validate_jqqb(prop, value):
    # some 
    return value

class FilterFeed(ndb.Model):
    url = ndb.StringProperty(required=True, validator=validate_url)
    query_builder = ndb.JsonProperty(required=True, validator=validate_jqqb)
```

Since last year, this started failing pytype with error:

```
File "/home/david/Projects/filter-feed/filter_feed.py", line 19, in FilterFeed: Function JsonProperty.__init__ was called with the wrong arguments [wrong-arg-types]
         Expected: (self, name, compressed, json_type, indexed, repeated, required, default, choices, validator: Optional[Callable[[google.cloud.ndb.model.Property], object]] = ..., ...)
  Actually passed: (self, required, validator: Callable[[Any, Any], Any])

For more details, see https://google.github.io/pytype/errors.html#wrong-arg-types
ninja: build stopped: subcommand failed.
```

This appears to be because #5821 introduced [an ndb stub](https://github.com/python/typeshed/blob/master/stubs/google-cloud-ndb/google/cloud/ndb/model.pyi) that defines validators as `Callable[[Property], object]` while [upstream](https://github.com/googleapis/python-ndb/blob/main/google/cloud/ndb/model.py) defines it as `Callable[[~google.cloud.ndb.model.Property, Any], bool]` in docstrings.

**Comment by davidn** [comment]
having used a `#pytype: disable=wrong-arg-types` for that, I am now finding that there is at least one more error in the model.pyi. `get_by_id()` is annotated as returning  `tasklets_module.Future` but it actually returns `Optional[Model]`.

**Comment by srittau** [comment]
Any PRs to improve the stubs are welcome! Also cc @romanofski as original stub author.

**Comment by romanofski** [comment]
@srittau thanks for the ping! @davidn Thanks for the report! Will have a look tonight.

**Comment by romanofski** [comment]
So #7116 is the fix for the first problem discovered. Indeed the second problem is also a mistyping. Interestingly - for whatever reason - I typed the synchronous method to return a `Future` while the asynchronous method is typed to return a `Model`. Should be the other way around :/ Will double check the typings for the other sync/async methods.
