### ISSUE TITLE
install_requires argument not supported in setup?

### ISSUE THREAD

**Issue by ze-phyr-us** [python/typeshed#713]
```
from distutils.core import setup
```

```
setup.py:7: error: Unexpected keyword argument "install_requires" for "setup"
/usr/local/lib/mypy/typeshed/stdlib/2and3/distutils/core.pyi:8: note: "setup" defined here
```

It seems the stub here doesn't specify `install_requires`, even though it's widely used in my experience. https://github.com/python/typeshed/blob/master/stdlib/2and3/distutils/core.pyi

**Comment by gvanrossum** [comment]
That's because install_requires is only supported by setuptools, not by
distutils. (Sadly there are no stubs for setuptools yet -- do you want to
contribute some?)

**Comment by JelleZijlstra** [comment]
Closing as this isn't a bug. (Stubs for setuptools would be nice but that should be a separate issue.)
