### ISSUE TITLE
Remove xxhash types (not before April 2023)

### ISSUE THREAD

**Issue by FaresAhmedb** [python/typeshed#7142]
[ifduyue/python-xxhash](https://github.com/ifduyue/python-xxhash) added type hints to master the last month (here in #4689), however the latest release doesn't ship with `__init__.pyi` nor `py.typed`. so wait until xxhash's next release and remove [./stubs/xxhash](https://github.com/python/typeshed/tree/master/stubs/xxhash) from here?

**Comment by JelleZijlstra** [comment]
Thanks! Our rule is to remove the stubs 6 months after the first release that ships stubs.

**Comment by srittau** [comment]
xxhash doesn't seem to ship with `py.typed`, and I can't find any mention of `py.typed` in the repository either. I am going to close this until xxhash adds support for type hints.

**Comment by hauntsaninja** [comment]
Sort of seems the intention was to add a py.typed though (https://github.com/ifduyue/python-xxhash/pull/51 talks about PEP 561), so could mention it to the upstream project if anyone is so inclined.

**Comment by AlexWaygood** [comment]
Upstream just cut a release with a `py.typed` file: #8935
