### ISSUE TITLE
DefaultDict Typing is Overly Strict

### ISSUE THREAD

**Issue by blink1073** [python/typeshed#7159]
The docs for `defaultdict` say:

> The first argument provides the initial value for the [default_factory](https://docs.python.org/3/library/collections.html#collections.defaultdict.default_factory) attribute; it defaults to None. All remaining arguments are treated the same as if they were passed to the [dict](https://docs.python.org/3/library/stdtypes.html#dict) constructor, including keyword arguments.

However, the second argument is currently treated as a generic type that influences the type of the first argument.

The following should be valid:

```python
>>> dict([('foo', 'bar')])
{'foo': 'bar'}
>>> dct = collections.defaultdict(dict, [('foo', 'bar')])
>>> dct
defaultdict(<class 'dict'>, {'foo': 'bar'})
>>> dct['g']
{}
>>> dct
defaultdict(<class 'dict'>, {'foo': 'bar', 'g': {}})
```

However, we get the error `error: Argument 1 to "defaultdict" has incompatible type "Type[Dict[Any, Any]]"; expected "Optional[Callable[[], str]]"`.

**Comment by AlexWaygood** [comment]
It [works fine](https://mypy-play.net/?mypy=latest&python=3.10&flags=show-error-codes%2Cstrict&gist=9a40987fada0e97ac2b9765e71cd6e16) as long as you give it an explicit annotation:

```python
from collections import defaultdict
from typing import Any

dct: defaultdict[str, str | dict[Any, Any]] = defaultdict(dict, [('foo', 'bar')])
```

(If you're on <3.9, you'll obviously either have to use `typing.DefaultDict` and `typing.Dict` in your annotation, or use `from __future__ import annotations`.)

**Comment by blink1073** [comment]
Makes sense, thanks @AlexWaygood!

**Comment by AlexWaygood** [comment]
> Makes sense, thanks @AlexWaygood!

No worries, happy typing!
