### ISSUE TITLE
How to type a `dataclass`?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#7173]
There are several questions about these lines in CPython: https://github.com/python/cpython/blob/a65be6e077122017081618278d758113a4a2eefd/Lib/pstats.py#L57-L71

```python

@dataclass(unsafe_hash=True)
class FunctionProfile:
    ncalls: int
    tottime: float
    percall_tottime: float
    cumtime: float
    percall_cumtime: float
    file_name: str
    line_number: int

@dataclass(unsafe_hash=True)
class StatsProfile:
    '''Class for keeping track of an item in inventory.'''
    total_tt: float
    func_profiles: Dict[str, FunctionProfile]
```

1. Our docs say that `@dataclasses.dataclass` can be used: https://typing.readthedocs.io/en/latest/source/stubs.html#decorators But, it does not say "how" it can be used. With or without parameters (like `unsafe_hash`)?
2. What if parameters are different in different python versions? For example (not the case for `pstats), for `3.9` it is `unsafe_hash=True`, but for `3.10` it is `unsafe_hash=False`?
3. What are the alternatives?

**Comment by hauntsaninja** [comment]
Note the documentation you linked to is for type stubs in general, not just typeshed type stubs.

I think it's fine to use parameters if all Python versions the stub is targeting (so Python 3.6+ for typeshed) support the parameters. If you want to use version-specific parameters, the definition must be guarded by an appropriate `sys.version_info` check. Depending on circumstances, I'd also accept "lying" about the dataclass: inlining the generated `__init__` isn't too bad.

**Comment by hauntsaninja** [comment]
Closing, since there doesn't appear to be too much disagreement :-)
