### ISSUE TITLE
Why is `collections.ChainMap.__missing__` defined in the stub?

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#7188]
`collections.ChainMap.__missing__` is defined in typeshed here:

https://github.com/python/typeshed/blob/63489c305d9db1159ce04a6d6542ec3932132939/stdlib/collections/__init__.pyi#L329

But, at runtime, it [always raises `KeyError`](https://github.com/python/cpython/blob/0ae40191793da1877a12d512f0116d99301b2c51/Lib/collections/__init__.py#L983) (and always has done), so there's no situation in which it would be safe to call this method (it's really just an implementation detail to give `ChainMap` a nicer error message for when the key isn't present in any of the underlying mappings, as far as I can tell).

The method was added to typeshed in a standalone PR (#4784)... Am I `__missing__` something? Is there a good reason for it to be there?

**Comment by hauntsaninja** [comment]
Possibly useful for subclasses? Clearly not the most important stub, but the default good reason of "it exists at runtime" applies. Maybe @natemcmaster remembers if they had a specific use case in mind when they contributed #4784 :-)

**Comment by natemcmaster** [comment]
Yes, I added it for subclassing. I have a type in my project that overrides `ChainMap.__getitem__` and calls `__missing__`

**Comment by srittau** [comment]
It seems fine to have this method, although we could consider changing the return type to `NoReturn`.

**Comment by AlexWaygood** [comment]
> Yes, I added it for subclassing. I have a type in my project that overrides `ChainMap.__getitem__` and calls `__missing__`

Thanks! Makes sense :)

**Comment by natemcmaster** [comment]
Change to NoReturn would break my usecase since  my subclass returns a default value when  `__missing__ ` is called, similar to defaultdict. https://docs.python.org/3/library/collections.html#collections.defaultdict.__missing__
