### ISSUE TITLE
Stub for `importlib.metadata` on Python 3.10 is incomplete

### ISSUE THREAD

**Issue by Molkree** [python/typeshed#7262]
- [ ] [`entry_points()`](https://docs.python.org/3/library/importlib.metadata.html#entry-points) was [changed](https://docs.python.org/3/library/importlib.metadata.html#:~:text=definition%2C%20and%20usage.-,Compatibility%20Note,-The%20%E2%80%9Cselectable%E2%80%9D%20entry) in 3.10
- [ ] [`metadata()`](https://docs.python.org/3/library/importlib.metadata.html#distribution-metadata) function returns `PackageMetadata` which got new attribute [`json`](https://docs.python.org/3/library/importlib.metadata.html#:~:text=have%20been%20removed.-,New%20in%20version%203.10,-%3A%20The%20json%20attribute)

**Comment by hauntsaninja** [comment]
Thanks, PR would be appreciated (feel free to fix both in a single PR)

**Comment by itaisteinherz** [comment]
Wasn't the second item resolved in #6557?

**Comment by Molkree** [comment]
Oh, that's interesting. I see [`PackageMetadata`](https://github.com/python/typeshed/pull/6557/files#diff-1f2b877aefbe5f15c15f9304d7fd2977547f3e41eae2662fea68a0f091193130R5) class being added with `json` attribute but `metadata()` still returns `Message` and not the new structure?
https://github.com/python/typeshed/blob/4343153c8c6b780c37b78b71e2072566a14b8ab6/stdlib/importlib/metadata/__init__.pyi#L112

**Comment by itaisteinherz** [comment]
It seems like the typings in typeshed are inaccurate, however mypy is still able to tell that the return type of `metadata()` is `PackageMetadata` using the type hints in CPython:

https://github.com/python/cpython/blob/b77158b4da449ec5b8f682816a79d004fd65ed07/Lib/importlib/metadata/__init__.py#L954

**Comment by hauntsaninja** [comment]
(mypy and other type checkers never look at type hints in CPython code)

**Comment by itaisteinherz** [comment]
> (mypy and other type checkers never look at type hints in CPython code)

Then how come mypy reports different types than the ones in typeshed?

**Comment by hauntsaninja** [comment]
What exactly is the difference you're seeing? (sorry, haven't been following discussion here too closely)

mypy vendors a copy of typeshed. So the types you get depend on what version of mypy you're using and what types were last vendored when that version was released. You can use `mypy --custom-typeshed-dir ~/dev/my-local-typeshed-checkout repro.py` to check something using your local typeshed checkout.

**Comment by itaisteinherz** [comment]
I ran mypy with the a local clone of typeshed (on the latest commit in master) on this snippet:

```python
from importlib_metadata import metadata
m = metadata("mypy")
reveal_type(m)
```

And received the following output:

```
scratch.py:3: note: Revealed type is "importlib_metadata._meta.PackageMetadata"
```

Which doesn't make much sense to me, as:

https://github.com/python/typeshed/blob/7b024f5e9a9276cbf3f388dbe935b58daeb124cd/stdlib/importlib/metadata/__init__.pyi#L140

**Comment by hauntsaninja** [comment]
`importlib_metadata` is the backport, which is py.typed. Typeshed provides stubs for `importlib.metadata`, which is in the standard library.

**Comment by AlexWaygood** [comment]
@hauntsaninja beat me to it, but:

`importlib_metadata` is a different module to `importlib.metadata`:

- `importlib.metadata` is a standard-library module. For the standard library, mypy looks at typeshed stubs for its type annotations, because most of the standard library does not have inline type annotations.
- `importlib_metadata` is a third-party package on PyPI, which serves as a backport of `importlib.metadata` to earlier versions of Python. Because it has a `py.typed` file, mypy looks at the inline annotations in the source code of the library. rather than a stub file like those provided by typeshed.

**Comment by itaisteinherz** [comment]
@hauntsaninja @AlexWaygood Thanks for explaining :)
