### ISSUE TITLE
Use latest stubtest from git in CI

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#7305]
There have been a number of great additions to stubtest recently. Several of these introduce new errors in typeshed. This means whenever we next update stubtest, there'll be a large backlog of allowlist adjustments or regression fixes — often duplicating work done when validating the change to stubtest. Lack of support for submodules in VERSIONS has also recently confused two contributors.

When stubtest was new, we used to install it from git (with a pinned hash) and this let us iterate quickly (and before that, for the longest time, we used to run all of mypy unpinned from latest git master). The only real downside of this is that stubtest is marginally (not too noticeably) slower. If we really cared about speed, we could install from https://github.com/mypyc/mypy_mypyc-wheels.

There've been about ten commits to stubtest since 0.930, we can upgrade commits one by one if necessary.

cc @AlexWaygood (if this is something you'd be interested in!)

**Comment by hauntsaninja** [comment]
Reminder to re-enable stubtest on sqlalchemy once we have https://github.com/python/mypy/pull/12219

**Comment by srittau** [comment]
I'm fine doing this temporarily, but we should switch back to a stable version matching mypy as soon as possible.

**Comment by hauntsaninja** [comment]
We are officially using latest stubtest as of #7438, thanks everyone!
