### ISSUE TITLE
`selenium.webdriver.common.options` is missing

### ISSUE THREAD

**Issue by bersbersbers** [python/typeshed#7379]
See https://github.com/python/typeshed/tree/master/stubs/selenium/selenium/webdriver/common

While the following codes are running fine:
```python
"""Show bug."""
from typing import Any, Literal, Type

from selenium import webdriver
from selenium.webdriver import chrome, firefox
from selenium.webdriver.common.options import ArgOptions
from selenium.webdriver.remote.webdriver import WebDriver


def fun(browser: Literal["chrome", "firefox"]) -> Any:
    """Show bug."""
    driver_class: Type[WebDriver]
    options: ArgOptions
    if browser == "chrome":
        driver_class = webdriver.Chrome
        options = chrome.options.Options()
    elif browser == "firefox":
        driver_class = webdriver.Firefox
        options = firefox.options.Options()
    return (driver_class, options)
```

```python
"""Show bug."""
from selenium.webdriver import chrome
from selenium.webdriver.common.options import ArgOptions


def fun() -> ArgOptions:
    """Show bug."""
    return chrome.options.Options()
```

I see various errors in Pylance and mypy:

> Import "selenium.webdriver.common.options" could not be resolved
> Incompatible types in assignment (expression has type "Options", variable has type "ArgOptions") 
> Incompatible return value type (got "Options", expected "ArgOptions")  [return-value]

Interstingly, `selenium.webdriver.common.options` is not mentioned here, either: https://www.selenium.dev/selenium/docs/api/py/api.html#webdriver-common

**Comment by Akuli** [comment]
Are you using Selenium 3 or Selenium 4? If it is Selenium 4, you should upgrade to 4.1.2 (released yesterday). It comes with its own type annotations, and type checkers should use those instead of what's in typeshed.
