### ISSUE TITLE
Status/Success Stories for typeshed?

### ISSUE THREAD

**Issue by smontanaro** [python/typeshed#739]
I watch a huge stream of additions and edits go by, which is cool, I suppose. I have some questions related to its use/success:

- Is typeshed to the point where people are using it (or it+mypy) to do significant things to improve code quality?
- Are the type hints to or past a tipping point where there are enough now to get some good results about type problems?
- Anyone have some success stories to share?
- How are people using it in their toolchains?

**Comment by gvanrossum** [comment]
At Dropbox we rely on typeshed; without it our use of mypy would be much less effective. I know Zulip does the same (http://blog.zulip.org/2016/10/13/static-types-in-python-oh-mypy/).

I don't know about PyCharm users (it seems so far they maintain their own collection of stubs, though they seem to be planning to use typeshed).

**Comment by matthiaskramm** [comment]
We use typeshed at Google, via http://github.com/google/pytype

So far, we're hearing good things from all our internal projects that have converted to static type checking.

**Comment by ambv** [comment]
It's being used at Facebook with mypy. Not a ton of annotated code yet but we're actively working on it.

**Comment by Herst** [comment]
I'm working on a larger and quite evolved Python 2 project where it's used now, numerous little bugs and possible issues were found. The checks run for every commit (developers are being asked to install certain git-hooks and additionally there it's also being checked on the server-side checks before the automated tests run). Everything is annotated except for some 3rd party code. Parameters used are `--disallow-untyped-defs`, `--strict-optional` and `--warn-no-return`.

**Comment by JelleZijlstra** [comment]
This issue hasn't had comments for over a year and there's no concrete action item, so closing.
