### ISSUE TITLE
subprocess methods returning `Any`

### ISSUE THREAD

**Issue by not-my-profile** [python/typeshed#7413]
To quote the stdlib documentation:

>If encoding or errors are specified, or text is true, file objects for stdin, stdout and stderr are opened in text mode using the specified encoding and errors or the `io.TextIOWrapper` default. The universal_newlines argument is equivalent to text and is provided for backwards compatibility. By default, file objects are opened in binary mode.

When any of these parameters cannot be determined statically, e.g:

```python
def foo(text: bool):
    output = subprocess.check_output('test', text=text)
```

then the overloads of typeshed currently just return `Any` ... which IMO is just wrong. E.g. the following should not type check:

```python
def foo(text: bool):
    output = subprocess.check_output('test', text=text)
    output.isasci() # notice the typo
```

but it currently does. I think it would be better if e.g. `check_output` returned `str | bytes` instead of `Any` and `Popen` returned `Popen[str] | Popen[bytes]` instead of `Any` in the case that it can be either or.

**Comment by srittau** [comment]
This is a case where python/typing#566 could help. But in general we prefer false positives over false negatives in typeshed, and we don't want to force extraneous `isinstance` checks on users for working code. Given these constraints, `Any` is the best we can do at the moment.

**Comment by not-my-profile** [comment]
> we don't want to force extraneous `isinstance` checks

Returning accurate types does not force anybody to use `isinstance` checks. If you want to trade type safety for performance you can always use an explicit `Any` annotation:

```python
def foo(text: bool):
    output: Any = subprocess.check_output('test', text=text)
    # do whatever with output
```

To entertain a metaphor: I don't think the typeshed should come with holes in the roof.

**Comment by srittau** [comment]
Forcing `Any` annotations has the same problem: Working code needs to be changed. python/typing#566 is the correct solution.
