### ISSUE TITLE
Missing private global variables of `threading`

### ISSUE THREAD

**Issue by eggplants** [python/typeshed#7424]
ref: https://github.com/python/typeshed/blob/master/stdlib/threading.pyi

ref: https://github.com/python/cpython/blob/main/Lib/threading.py#L55

**Comment by eggplants** [comment]
- `_profile_hook`
- `_trace_hook`
- `_SHUTTING_DOWN`
- `_active_limbo_lock`
- `_main_thread`
- `_shutdown_locks_lock`
- `_shutdown_locks`

**Comment by Akuli** [comment]
If you need to access private variables, just make a pull request that adds what you need. We're not going to add them all just for the sake of completeness.

**Comment by eggplants** [comment]
@Akuli So if I create a PR to provide the above, will it be incorporated?

**Comment by JelleZijlstra** [comment]
Our general policy is to add private objects if someone asks for them. However, that's meant to happen when you're actually using them, not just to fill out the stub.

**Comment by eggplants** [comment]
Now, I try to provide type hints for [agronholm/typeguard](https://github.com/agronholm/typeguard).

typeguard uses `threading._profile_hook` in [src/typeguard/__init__.py](https://github.com/agronholm/typeguard/blob/de6ab051309ba74a0a27840f8172697c8778ae4f/src/typeguard/__init__.py#L1165-L1194). But it raises an `attr-defined` error when `mypy --strict` due to lacking type information.

**Comment by Akuli** [comment]
Alright, let's add only `_profile_hook` then :)
