### ISSUE TITLE
Question: Why not `*-stubs` but `types-*` in typeshed?

### ISSUE THREAD

**Issue by eggplants** [python/typeshed#7434]
As the title says. Is the reason simply to make a distinction?

---

Ref:

https://mypy.readthedocs.io/en/stable/installed_packages.html#using-installed-packages-with-mypy-pep-561

>As many packages don’t support type checking yet, you may also have to install a separate stub package, usually named `types-<library>`.

https://mypy.readthedocs.io/en/stable/installed_packages.html#creating-pep-561-compatible-packages

>If the package is stub-only (not imported at runtime), the package should have a prefix of the runtime package name and a suffix of `-stubs`.

**Comment by hauntsaninja** [comment]
Most of this history here is on https://github.com/python/typeshed/issues/2491 
I seem to remember one consideration was PyPA creating namespaces in the future, which is why we went with a prefix.

**Comment by eggplants** [comment]
Thank you for your answer!
