### ISSUE TITLE
AsyncSession sqlalchemy no return type annotated

### ISSUE THREAD

**Issue by Fikralaksana** [python/typeshed#7440]
https://github.com/python/typeshed/blob/cda3d9cf722f38f5646e99cacbc169620e268786/stubs/SQLAlchemy/sqlalchemy/ext/asyncio/session.pyi#L53

Because return type of `__aenter__` not anotated, pylance cant give a suggestion on `session` variable.
`session` variable not have `AsyncSession` type hint in vscode. it show `Any` type hint instead.
`session` variable not show any suggestion with this code structure.

```python
async def getParams(product_id: str, db_session: AsyncSession) -> dict:
    async with db_session as session:
        session.execute()
        
```

**Comment by Akuli** [comment]
If `db_session` and `session` should have the same type, the stub should be

```python3
    async def __aenter__(self: Self) -> Self: ...
```

where `Self` is imported from `_typeshed`. PR welcome!
