### ISSUE TITLE
DefaultEventLoopPolicy is not valid as a type / base class

### ISSUE THREAD

**Issue by henryiii** [python/typeshed#7452]
The following code fails `mypy tmp.py`:

```python
import asyncio

class MyEventLoopPolicy(asyncio.DefaultEventLoopPolicy):
    pass
```

with:

```
tmp.py:3: error: Variable "asyncio.DefaultEventLoopPolicy" is not valid as a type
tmp.py:3: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
tmp.py:3: error: Invalid base class "asyncio.DefaultEventLoopPolicy"
Found 2 errors in 1 file (checked 1 source file)
```

This MWE is copied from the Python docs here: https://docs.python.org/3/library/asyncio-policy.html#custom-policies.

Maybe this is because of the assignment here: https://github.com/python/typeshed/blob/fd750bf065fc06c4e567439df8b1b142724ed441/stdlib/asyncio/unix_events.pyi#L94-L99 ?

**Comment by AlexWaygood** [comment]
The bug appears to already be fixed on typeshed master as a result of https://github.com/python/typeshed/pull/7343 (merged just seven days ago) 😃

mypy's bundled version of the typeshed stubs won't be updated until at least 0.940. For now, though, you can clone typeshed and use mypy with the `--custom-typeshed-dir` option, or by setting the `MYPYPATH` environment variable.

**Comment by srittau** [comment]
@AlexWaygood was faster, but I agree with the analysis.

**Comment by henryiii** [comment]
That's fantastic. While I don't fully understand why this fixed the problem, I can verify that does in fact now pass.

```console
$ mypy tmp.py --custom-typeshed-dir ~/git/software/typeshed
Success: no issues found in 1 source file
```

**Comment by srittau** [comment]
Before, this line was in `asyncio/__init__.pyi`:

https://github.com/python/typeshed/blob/35bddd289f8d716603c63f68b827cbcddf5ac804/stdlib/asyncio/__init__.pyi#L113

This has been changed to a star import.

**Comment by AlexWaygood** [comment]
Yes, now the `DefaultEventLoopPolicy` name is imported either from `asyncio.unix_events` or `asyncio.windows_events`, depending on whether the machine running mypy is a Windows or Unix machine. This mirrors the behavior at runtime when importing `DefaultEventLoopPolicy` from `asyncio`.

**Comment by henryiii** [comment]
Ah, I missed that, thanks!
