### ISSUE TITLE
`SSLContext` in ssl-library: remove `ClassVar` from `sslsocket_class` and `sslobject_class`

### ISSUE THREAD

**Issue by prauscher** [python/typeshed#7459]
According to https://docs.python.org/3/library/ssl.html#ssl.SSLContext.sslsocket_class and https://docs.python.org/3/library/ssl.html#ssl.SSLContext.sslobject_class, both variables (`sslsocket_class` and `sslobject_class`) should be changeable on instance, so `ClassVar` should be removed from both files in https://github.com/python/typeshed/blob/master/stdlib/ssl.pyi#L396

Thanks to @AlexWaygood for pointing this out in https://github.com/python/mypy/issues/12308

**Comment by AlexWaygood** [comment]
Thanks - PR welcome!
