### ISSUE TITLE
sqlite3's Cursor.rollback() has no type

### ISSUE THREAD

**Issue by dmiyakawa** [python/typeshed#747]
```
    def rollback(self, *args, **kwargs): ...
```

There seems no TODO or "Any" typing. I cannot understand why it is left un-typed.

**Comment by JukkaL** [comment]
@dmiyakawa It's probably just an oversight. Was there a problem creating a PR to fix this?

**Comment by dmiyakawa** [comment]
Sorry for my mistake(s). Now I've prepared a correct PR.
