### ISSUE TITLE
`RawConfigParser.get` should return `str | None`, not `str`

### ISSUE THREAD

**Issue by Pyprohly** [python/typeshed#7476]
The `get` method on `RawConfigParser` method should return `str | None`, along with all with the other `get*` variants. The same applies to `SectionProxy`.

**Comment by jpy-git** [comment]
FYI `RawConfigParser` is a lot more permissive in what it allows for setting/getting (#6820)

Also `RawConfigParser` is considered legacy so worth updating code to `ConfigParser` if possible: https://github.com/python/typeshed/issues/6820#issuecomment-1006067169

**Comment by srittau** [comment]
Any PRs to improve the situation for either issue are welcome.
