### ISSUE TITLE
(🐞) `isinstance` works with `typing.Union`s on 3.10+

### ISSUE THREAD

**Issue by KotlinIsland** [python/typeshed#7505]
```py
from typing import Union

print(isinstance(1, Union[str, int]))  # error: Argument 2 to "isinstance" has incompatible type "object"; expected "Union[type, UnionType, Tuple[Union[type, UnionType, Tuple[Any, ...]], ...]]"
```
But this outputs `True`

`Union[X, Y]` is stubbed to return `object` when it really returns a `typing._UnionGenericAlias` to `typing.Union` so that would need to be fixed first.

[playground](https://mypy-play.net/?mypy=latest&python=3.10&gist=7897cc451becb2ac7a4905a2d2aa8943)

**Comment by srittau** [comment]
The stubs look correct to me:

https://github.com/python/typeshed/blob/e8286e7048aeeced78c24d6d38bf49e5b92ddf88/stdlib/builtins.pyi#L1161-L1172

I believe that his is purely a mypy bug, but someone could correct me here.

**Comment by KotlinIsland** [comment]
That doesn't contain anything about `typing.Union`.

Could you please elaborate?

**Comment by AlexWaygood** [comment]
Strictly speaking the `Union[str, int]` object being passed to the union is of type `typing._SpecialForm`, and it's true that the stub doesn't currently allow for the possibility of passing in `_SpecialForm` objects. 

I'm not sure this is really a problem that should be solved in the stubs, though. If we add `_SpecialForm` to the union of types that's allowed for the second argument, that might mean that type checkers might start allowing things like `isinstance(1, Literal[1])`, which fails at runtime. Given that it's really only this specific special form that works with `isinstance`, I think it's probably better for a type checker to special-case it.

**Comment by KotlinIsland** [comment]
@AlexWaygood Actually it's more specifically a `typing._UnionGenericAlias` , so would be perfectly safe to annotate with.

**Comment by AlexWaygood** [comment]
> I could make a pr when I get time.

Cool, I'll happily take a look at a PR!

In general I'm slightly leery of overcomplicating `typing.pyi` by reproducing the exact runtime implementation details, but if there's a way to do it simply, then sure!

**Comment by KotlinIsland** [comment]
Something roughly like this
```py
class _SpecialForm(Generic[T]):
    def __getitem__(self, typeargs: Any) -> T: ...

class _Union:
    pass
Union: _SpecialForm[_Union] = ...
```
```py
 def isinstance(__obj: object, __class_or_tuple: type | types.UnionType | _SpecialForm[_Union]) -> bool: ...
```

**Comment by KotlinIsland** [comment]
@AlexWaygood Here you go 😁 #7508

**Comment by AlexWaygood** [comment]
The consensus in #7508 was that this was an unusual and niche use case, so it's probably best to close this as a "wontfix".
