### ISSUE TITLE
Return type annotation for `importlib.metadata.version` is incorrect

### ISSUE THREAD

**Issue by DMRobertson** [python/typeshed#7513]
To my surprise, I discovered in https://github.com/matrix-org/synapse/issues/12223 that it is possible for `importlib.metadata.version("foo")` to return `None`. However, the stub suggests `version` and `Distribution.version` will always return a string:

https://github.com/python/typeshed/blob/50107e6e2b7144a1b0bfe6d46a7bc81926deed2b/stdlib/importlib/metadata/__init__.pyi#L161

https://github.com/python/typeshed/blob/50107e6e2b7144a1b0bfe6d46a7bc81926deed2b/stdlib/importlib/metadata/__init__.pyi#L213

To prove that `version` sometimes returns `None`:

1. Create a new virtual environment. I'm using CPython 3.10.2 as my interpreter.
2. Within the venv, `pip install bottle`. (Any package will do; I choose `bottle` because it's small and doesn't have any dependencies).
3. The `version` of `bottle` agrees with what you've just installed:
    ```shell
    $ python -c "import importlib.metadata as m; print(repr(m.version('bottle')))"
    '0.12.19'
    ````
4. Here's the dirty bit: remove the metadata files for that package but keep the metadata directory.
    - Use `pip show bottle` to find the `site-packages` location
    - From there, remove all files in the `bottle-VERSION-.dist-info` directory: `rm /path/to/site-packages/bottle-VERSION.dist-info/*'.
5. The `version` of `bottle` is now judged to be `None`:
    ```shell
    $ python -c "import importlib.metadata as m; print(repr(m.version('bottle')))"
    None
    ````

A few other notes:
- For a package `foo` that's not installed, `version("foo") raises a PackageNotFoundError`.
- I don't know if this ought to be considered a bug in the library rather than the annotations?
- I haven't dug much into the internals of `importlib.metadata` but it looks like the version is retrieved by looking inside a `metadata` attribute on a `Distribution`. I think other lookups are vulnerable to a similar problem; the only example I could find is `Distribution.name`.

**Comment by DMRobertson** [comment]
I'd be happy to PR an update to the annotations making `version` and `name` return `str | None`---but I'm not sure if that's the correct thing to do. Perhaps the implementation ought to be changed to raise an exception in this case, and this ought to be a bug against CPython and the backport `importlib_metadata`?

**Comment by JelleZijlstra** [comment]
Not too familiar with `importlib.metadata` either, but this does sound like it's better treated as a bug in the implementation. The documentation is at https://docs.python.org/3.10/library/importlib.metadata.html#distribution-versions. It's not very precise but doesn't say anything about version() returning None in exotic cases.

**Comment by DMRobertson** [comment]
> The documentation is at https://docs.python.org/3.10/library/importlib.metadata.html#distribution-versions.

There's also the backport of this module, which (strangely?) has a more complete reference. https://importlib-metadata.readthedocs.io/en/latest/api.html#importlib_metadata.version doesn't suggest anything about None there.

> this does sound like it's better treated as a bug in the implementation.

Thanks for confirming! I'll get filing issues elsewhere.

**Comment by JelleZijlstra** [comment]
Thanks! If you're reporting a bug, I'd suggest the docs should also state that it throws PackageNotFoundError for a package that is not installed. :)

**Comment by AlexWaygood** [comment]
> There's also the backport of this module, which (strangely?) has a more complete reference. https://importlib-metadata.readthedocs.io/en/latest/api.html#importlib_metadata.version doesn't suggest anything about None there.

If I understand correctly, I believe changes are usually made to importlib_metadata first, and then "forward-ported" to CPython (don't ask me why). So this isn't _that_ strange :)

**Comment by DMRobertson** [comment]
For completeness: I've raised https://bugs.python.org/issue47060. It looks like https://github.com/python/importlib_metadata/issues/371 might be related too.
