### ISSUE TITLE
Wrong type for `fget` of property

### ISSUE THREAD

**Issue by eagleoflqj** [python/typeshed#7516]
```py
class A:
    @property
    def foo(self):
        return 'a'

A.foo.fget(A())
```
pyright reports error `error: Expected 0 positional arguments (reportGeneralTypeIssues)`

**Comment by AlexWaygood** [comment]
I'm adding the "deferred" label since there's not much we can do on this without movement from mypy, unfortunately :(

**Comment by AlexWaygood** [comment]
It seems like this was actually a bug in pyright's special-casing for `property`. I can no longer reproduce this bug locally using VSCode.
