### ISSUE TITLE
`subprocess.{run, call, check_call, check_output}` do not have arguments new in 3.9+

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#7524]
The subprocess methods do not have `group`, `extra_groups`, `user`, and `umask` in their signature.

**Comment by AlexWaygood** [comment]
#8071 adds the new-in-3.9 parameters to `subprocess.run`, `suprocess.call`, `subprocess.call` and `subprocess.check_output`. However, there are new parameters in 3.10 and 3.11 that should be added to these functions in future PRs:

- 3.10 adds the `pipesize` parameter.
- 3.11 adds the `process_group` parameter.
