### ISSUE TITLE
invoke stubs report not callable

### ISSUE THREAD

**Issue by kasium** [python/typeshed#7530]
Example:
```python
from invoke import task, Context

@task
def foo(context: Context) -> None:
    pass

@task
def bar(context: Context) -> None:
    pass

@task(foo, bar)
def baz(context: Context) -> None:
    pass
```

Error: `foo.py:15:2: error: <nothing> not callable  [misc]`

I'm the author of the stubs, but I don't understand the error. Can someone please support?

**Comment by srittau** [comment]
I haven't looked at the implementation, but I think the second overload of `task` has the wrong return type:

https://github.com/python/typeshed/blob/b307142f62863be51f76c44fc564b6355b732851/stubs/invoke/invoke/tasks.pyi#L58-L76

It should return a function that gets called with a the wrapped function, i.e.:

```python
@overload 
 def task(...) -> Callable[[Callable[..., Any]], _TaskT]: ... 
```

**Comment by kasium** [comment]
@srittau missed that. Thanks a lot!
