### ISSUE TITLE
`func` argument to `functools.partial()` should be positional-only

### ISSUE THREAD

**Issue by Zac-HD** [python/typeshed#7549]
The following code executes without any runtime error, but `mypy` flags an error.

```python
import functools

def decorator(func):
    ...  # decorator logic here

functools.partial(decorator, func=lambda: None)
```
```
repro.py:6: error: "partial" gets multiple values for keyword argument "func"  [misc]
```

I believe this is because typeshed doesn't specify that `func` is a positional-only argument.

**Comment by hauntsaninja** [comment]
I think this was fixed a while back; are you using an older mypy?

**Comment by Zac-HD** [comment]
Apparently so!  Apologies for the noise 😳
