### ISSUE TITLE
What's the right set of declarations here?

### ISSUE THREAD

**Issue by smontanaro** [python/typeshed#755]
I've got a class which takes a port number (int) and hostname (str):

```
class X(object):
    def __init__(self, port=6600, host="x.y.com"):
        ...
```

elsewhere, it can be instantiated using values extracted from a dictionary:

```
if x is not None:
    self.x = X(port=x['port'], host=x['host'])
```

That dictionary is itself a parameter declared as as mapping strings to strings or ints:

```
    # type: Dict[str, Union[str, int]]
```

mypy complains about the call to X(...) because the values in x can be either strings or ints, but the port and host parameters are declared to be one or the other, not the union of the two.

What's the correct way to work around this issue?

**Comment by gvanrossum** [comment]
Short-term, your best bet is `# type: ignore`. You could also use casts but those have runtime costs (it's a Python function call so probably costs way more than than the dict lookups). In the future we'll have a "TypedDict" type that you can use for the type of that dictionary; see https://github.com/python/mypy/issues/985 and search the tracker for TypedDict to find various tasks still open before that's a viable solution.

**Comment by smontanaro** [comment]
On Wed, Dec 7, 2016 at 10:00 AM, Guido van Rossum
<notifications@github.com> wrote:
>
> Short-term, your best bet is # type: ignore.

Thanks, Guido. Ignore it is...

S
