### ISSUE TITLE
`sum` stub too permissive

### ISSUE THREAD

**Issue by jpy-git** [python/typeshed#7574]
Currently the stub for the `sum` built-in allows any iterable as an argument
https://github.com/python/typeshed/blob/ae6ff79c0e14cd054bf07374e7091a098a46cf1f/stdlib/builtins.pyi#L1480-L1489

This means mypy has no issue with:
```python
sum("hello")
```
Which results in this error at runtime:
```
TypeError: unsupported operand type(s) for +: 'int' and 'str'
```

context: I was introducing someone to mypy and used the example above as something that mypy should flag, but turns out it wasn't being flagged so logging here.

**Comment by Akuli** [comment]
It's easy to put a TypeVar bound on the first overload, but `sum()` doesn't work for strings even if you define `start=""`. It intentionally works with everything except strings.

```
>>> sum("asd", start="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: sum() can't sum strings [use ''.join(seq) instead]
```

Fixing this properly would require https://github.com/python/typing/issues/1043.

**Comment by AlexWaygood** [comment]
> It's easy to put a TypeVar bound on the first overload

Even that's actually a little tricky, because you get into the question of [what is a number](https://stackoverflow.com/questions/69334475/how-to-hint-at-number-types-i-e-subclasses-of-number-not-numbers-themselv/69383462#69383462).

For example, this works fine, even though there's not really anything that these classes all have in common either from a nominal or structural point of view:

```python
>>> import numpy as np
>>> from fractions import Fraction
>>> sum((3, np.float64(), Fraction(7, 22), complex(8, 0), 9.83))
(21.14818181818182+0j)
```

This does too:
```python
>>> from decimal import Decimal
>>> sum((3, Decimal('0.98')))
Decimal('3.98')
```

But this breaks:
```python
>>> from decimal import Decimal
>>> sum((2.34, Decimal('3.87')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'float' and 'decimal.Decimal'
```

**Comment by JelleZijlstra** [comment]
We could at least bound the TypeVar to a Protocol defining `__add__`. That wouldn't help with Alex's mixed numeric types, but it would help type checkers catch plausible mistakes like `sum([1, None])`.
