### ISSUE TITLE
Missing attributes for MappingView and subclasses in stdlib/collections_abc_.pyi

### ISSUE THREAD

**Issue by laundmo** [python/typeshed#7576]
Due to `stdlib/_collections_abc.pyi` importing most directly from `stdlib/typing.pyi`, MappingView and its subclasses are missing the `self._mapping` attribute. This is an issue if inheriting from them for implementing custom views. This causes pyright and mypy (with `--check-untyped-defs`) to fail.

Minimal Example:
```py
import collections.abc

class MyView(collections.abc.KeysView):
    def __iter__(self):
        for key in self._mapping:
            yield key + 1
```
`mypy --check-untyped-defs test.py`
```
test.py:5: error: "MyView" has no attribute "_mapping"
```
`pyright test.py`
```
test.py
  test.py:5:25 - error: Cannot access member "_mapping" for type "MyView"
    Member "_mapping" is unknown (reportGeneralTypeIssues)
1 error, 0 warnings, 0 informations
```

I'm open to trying to PR this myself, though I have little experience writing stub files.

**Comment by laundmo** [comment]
@AlexWaygood i would propose only adding them to `stdlib/_collections_abc.pyi` and not to typing.pyi, as they seem to be specific to the collections.abc implementation of MappingView, ValuesView etc.

in fact, i would be against adding them to typing.pyi as the attribute is not needed when implementing a completely custom MappingView that doesn't inherit from collections.abc

As for the usecase, in my case i wanted to create a custom mapping class that would convert the keys automatically, for which i need custom views to apply the conversions in case someone uses `.items()`, `.values()` etc. on my custom class.

**Comment by AlexWaygood** [comment]
If you're proposing decoupling the types in `collections.abc` from the types in `typing`, that would be a significant undertaking 🙂 (see #6257 for previous discussion and attempts to do just that). I'd advise not trying to do that.

**Comment by Akuli** [comment]
This is similar to #7153.

**Comment by AlexWaygood** [comment]
> This is similar to #7153.

Yes, though https://github.com/python/typeshed/pull/7153 was regarding a method with an extensive docstring, whereas this attribute is entirely undocumented from what I can see.

**Comment by laundmo** [comment]
> > This is similar to #7153.
> 
> Yes, though #7153 was regarding a method with an extensive docstring, whereas this attribute is entirely undocumented from what I can see.

entirely undocumented but also required if you want any tangible benefit from using collections.abc.MappingView and descendants

**Comment by Akuli** [comment]
Feel free to make a PR that adds `_mapping` :)

**Comment by AlexWaygood** [comment]
Closing due to lack of response from OP on the PR: https://github.com/python/typeshed/pull/7583#issuecomment-1172910793

Feel free to open a new PR with the requested changes, if you're still interested in this issue, @laundmo :)
