### ISSUE TITLE
What is the "right way" to annotate a wsgi application with middlewares?

### ISSUE THREAD

**Issue by sirosen** [python/typeshed#7585]
I'm working with `flask` and `werkzeug`, and trying to figure out how to improve some of my typing (`mypy --disallow-untyped-defs`). When I look at the types from typeshed for wsgiref, and how werkzeug handles this, I find things that are a bit confusing. This question is only somewhat flask/werkzeug specific, it mostly pertains to typeshed -- I'm happy to repost or cross-post in werkzeug if that seems better.

Here's something similar to what I have today, partially annotated:
```python
def make_flask_app() -> flask.Flask: ...

def apply_middlewares(app: Flask):
    profdir = os.getenv("WSGI_PROFILE_DIR")
    if profdir:
        return werkzeug.middleware.profiler.ProfilerMiddleware(app, profile_dir=profdir)
    return app

def make_app():
    app = make_flask_app()
    return apply_middewares(app)
```

So what is the return type of `apply_middlewares`?

Looking around, it seems like this is `_typeshed.wsgi.WSGIApplication`. But that's in `_typeshed` -- is it safe to import it at type-checking time? Could it be renamed in the future? `werkzeug` already does this:
```
if TYPE_CHECKING:
    from _typeshed.wsgi import WSGIApplication
```

Is this safe for me to do too? I'm going to probably do this for today but it would be great to either know that the name is stable or to find a better way.

Concretely, the type above is just `Flask | ProfilerMiddleware` today. But any other middleware will (spuriously) be flagged as changing the type if the code changes. So `WSGIApplication` is really much preferable.

I'd really like to see `WSGIApplication` (and some of the other stuff, like `StartResponse`) available as types that I can use at typing time. Does this require additions of some of these types as protocols to the stdlib? I'm more than happy to work on this, if it's not already in progress.

**Comment by sirosen** [comment]
Ah, I hadn't found that readme -- and particularly the API stability note. Thank you!

That solves my scenario nicely. It would still be nice to get these types into `wsgiref`. I'll try to remember to file something on cpython after the github issues migration. Should this be left open or closed?

**Comment by srittau** [comment]
Please see [bpo-42012](https://bugs.python.org/issue42012). Maybe a core developer (*wink* *wink*) could comment on this.

**Comment by sirosen** [comment]
I just looked to see if I could maybe help with this work, and I see https://github.com/python/cpython/pull/32335 already open!

As the OP, I think it's reasonable to close this and am doing so now. It will take a while for this to be usable for most people to be able to use the types in the stdlib, but things are on a good course.

Every time I try to help with typeshed and typing it's a pleasure. Thanks so much to everyone involved! 🎉
