### ISSUE TITLE
namedtuple() signature is too strict about sequence arg

### ISSUE THREAD

**Issue by belm0** [python/typeshed#7590]
The `field_names` arg of `namedtuple()` is defined as a "sequence", so it should allow more than List/tuple.   https://docs.python.org/3/library/collections.html#collections.namedtuple

Seen with mypy-0.942:
```python
d = {'bar': 10}
foo_type = namedtuple('Foo', d.keys())
```

```
error: List or tuple literal expected as the second argument to "namedtuple()"  [misc]
```

**Comment by JelleZijlstra** [comment]
Mypy specifically wants a list or tuple *literal*, so it can statically determine what the fields are. Dynamically creating a namedtuple like in your example is not supported.
