### ISSUE TITLE
Upgrade Redis stubs to 4.2.x

### ISSUE THREAD

**Issue by Ankhas** [python/typeshed#7597]
The redis-py package has been updated to 4.2.2 : https://github.com/redis/redis-py/releases/tag/v4.2.2 and currently stubs are in version 4.1.*

**Comment by kovalevvlad** [comment]
A big change here and the reason why I upvoted is the addition of asyncio

**Comment by AlexWaygood** [comment]
PR welcome!

**Comment by srittau** [comment]
#7675 didn't add async support. Reopening.

**Comment by squaresmile** [comment]
Thank you for the updated redis typing. 2 things I noticed with the new types:

```
from redis.asyncio import Redis 

async def func(redis: Redis, redis_key: str): # 1
    return await redis.get(redis_key)         # 2
```
- 1 leads to mypy error `Missing type parameters for generic type` while `TypeError: <class 'redis.asyncio.client.Redis'> is not a generic class`.
- 2 leads to `Incompatible types in "await" (actual type "Optional[Any]", expected type "Awaitable[Any]")`.
