### ISSUE TITLE
Package/module name clashes?

### ISSUE THREAD

**Issue by smontanaro** [python/typeshed#760]
I ran stubgen over a third party package yesterday (websocket-client in PyPI), and thought I might check it and submit it (with the author's approval), but then it occurred to me that "websocket" might be a non-unique name. Search for "websocket" on PyPI - I'd be kind of surprised if there weren't a couple top-level packages named "websocket" after installation. If I submit stubs for a package and someone else has a package with the same name, how are collisions avoided in typeshed? I saw nothing obvious in the MyPy docs or the typeshed README.md file. Maybe it's a practical non-issue, but if it is a possible gotcha, mentioning it in the docs (with possible workarounds) might be worthwhile.

**Comment by JukkaL** [comment]
We don't have an explicit policy for avoiding top-level package name collisions. However, we are currently mostly accepting stubs for relatively widely-used third-party packages to typeshed, and that makes conflicts less likely. A bigger problem is mutually API-incompatible versions of a single package.

Mentioning this in the docs would be reasonable, as other contributors might wonder about this same thing.

**Comment by JelleZijlstra** [comment]
I don't think this is a problem in practice because libraries that are well-known enough to be in typeshed probably have a unique name. More obscure packages should ship their own PEP 561-style stubs.

Closing this as I don't think it's worth spending time on until there is a concrete example of this problem.
