### ISSUE TITLE
stubgen crash trying to generate stubs for Pandas

### ISSUE THREAD

**Issue by smontanaro** [python/typeshed#766]
I got the following traceback from stubgen when trying to generate stubs for Pandas. Apologies for any typos - I work in an environment which doesn't allow me to send stuff out. This traceback went in through my eyeballs, and out through my fingers with some eliding performed by my cortex...)

```
Traceback (most recent call last):
  File ".../bin/stubgen", line 20, in <module>
  ...
  File ".../mypy/stubgen.py":, line 98, in generate_stub_for_module
    class_sigs=class_sigs)
  File ".../mypy/stubgenc.py", line 35, in generate_stub_for_c_module
    generate_c_type_stub(module, name, ...)
  File ".../mypy/stubgenc.py", line 150, in generate_c_type_stub
    if all_bases[-1] is object:
IndexError: list index out of range
```
Running with the --ignore-errors flag, and searching output for "Stub generation", it appears it was trying to generate stubs for pandas.hashtable, which is an extension module. I'll see what I can do to figure it out, but would appreciate some guidance on how to proceed. This is in a Conda Python 3 environment with Pandas 0.19.0 installed.

**Comment by gvanrossum** [comment]
I don't know that code at all, but from looking at it, it might be that the class somehow only has one item in its MRO. That's weird because for any class except `object` you'd expect there to be two classes at least in the MRO: the class itself, and `object`. But extension modules can do wacky stuff. So I recommend the simplest fix possible: change it to ```if all_bases and all_base[-1] is object:``` and see if that resolves the matter.

**Comment by JelleZijlstra** [comment]
It's probably choking on `pandas.hashtable.na_sentinel`, which at least on my Pandas 0.18.0 is an alias for `object` and therefore does indeed have a one-item MRO. I was able to reproduce the crash by creating a file containing `alias = object`, compiling it with Cython to a .so, and running stubgen on the resulting module.

I'll submit a PR to mypy to apply Guido's suggested fix.
