### ISSUE TITLE
Name 'cStringIO' already defined

### ISSUE THREAD

**Issue by smontanaro** [python/typeshed#767]
Working through a ton of error messages related to stubgen-generated stubs, mypy complains that cStringIO was already defined. I looked at the `pandas/__init__.pyi` stub and found this:

```
from cStringIO import StringIO as cStringIO
...
cStringIO = ... #type: Any
```
It's not exactly clear to me what the correct fix is. On the one hand, the cStringIO assignment would seem to be bogus, but there must be something else going on, as there are all sorts of type assignments like that for things like range, map, zip, FileNotFoundError, etc. Perhaps I'm just using stubgen all wrong?

**Comment by gvanrossum** [comment]
Stubgen isn't very smart. Its left hand doesn't know what its right hand does. There may well be two definitions of `cStringIO` in the original file (I don't have the Pandas source handy to look it up). I'd delete the offending one and move on. (A word of warning: if you're trying to automatically invoke stubgen as part of some build process and then use the generated stubs, you're in for a big disappointment. Stubgen output often needs manual cleanup.)

**Comment by smontanaro** [comment]
On Mon, Dec 12, 2016 at 11:40 AM, Guido van Rossum <notifications@github.com
> wrote:

> A word of warning: if you're trying to automatically invoke stubgen as
> part of some build process and then use the generated stubs, you're in for
> a big disappointment. Stubgen output often needs manual cleanup.


Nope, not at all. I expect to have to tweak the output, perhaps in
significant ways. Looking at the original source
(pandas/compat/__init__.py), it does appear that stubgen gets into hot
water trying to process both the try and except blocks in the face of an
ImportError. The cStringIO involved code looks like this:

try:
  import __builtin__ as builtins
  from cStringIO import StringIO as cStringIO
  ...
except ImportError:
  import builtins
  from io import StringIO, BytesIO
  cStringIO = StringIO
  ...

The stubgen output has no such try/except guard. I think I need to reinsert
the guard (or something like it). Which suggests a follow-up question: How
much does stubgen know about the py2/py3 environment? Is there a suitable
test I can insert into a set of stubs which I expect to go into a 2and3
directory? I see these definitions by Pandas:

PY2 = sys.version_info[0] == 2
PY3 = (sys.version_info[0] >= 3)
PY35 = (sys.version_info >= (3, 5))

Can I use them as-is in the stub, or must I explicitly do something like
what I see in argparse.pyi?

  if sys,version_info >= (3, 5):
    ...

**Comment by JukkaL** [comment]
Your best bet is to use something like `if sys.version_info >= ...`. Stubs only support a restricted subset of Python syntax, and even if mypy is not very strict about, other tools may give up if you something that is not officially supported in stubs.

**Comment by gvanrossum** [comment]
FWIW mypy does actually recognize constants named `PY2` and `PY3` with the quoted definitions too. You have to initialize them explicitly using definitions like above. Note that mypy doesn't actually read the definitions, it just treats any variable named `PY2` or `PY3` as such. (So hilarity will ensue if you define e.g. `PY2 = sys.version_info[0] >= 3`.)

**Comment by JelleZijlstra** [comment]
Sounds like the only potential bug here is in stubgen, not typeshed.
