### ISSUE TITLE
min/max are missing optional default keyword only argument

### ISSUE THREAD

**Issue by rmcgibbo** [python/typeshed#77]
In py3, the min and max argument take an optional keyword only argument, `default`, but this isn't in the type signature stub.

https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L660-L663

**Comment by gvanrossum** [comment]
Aha! The fix for this was waiting for a change in mypy. That change has now landed (https://github.com/JukkaL/mypy/issues/1150) so we can now accept a PR to add this.

**Comment by rmcgibbo** [comment]
I don't really know the `@overload` syntax. Should I just add another kwarg to https://github.com/python/typeshed/blob/master/stdlib/3/builtins.pyi#L663?

**Comment by gvanrossum** [comment]
Looks like you need to add `key: Callable[[_T], Any] = None` to line 661.

**Comment by rmcgibbo** [comment]
I raised this issue about the `default: _T=None` arg, not `key:`. I'll try it out each way.

**Comment by gvanrossum** [comment]
Oh, sorry. You're right.

**Comment by EdwardEisenhauer** [comment]
I experienced mix/max issues with the following code:
```python
from typing import Optional


class MyObject:
    def __init__(self, attribute: int) -> None:
        self.attribute = attribute


def find_biggest_attribute(objects: list[MyObject]) -> Optional[MyObject]:
    return max(objects, default=None, key=lambda object: object.attribute)


print(find_biggest_attribute([MyObject(42), MyObject(41)]))

print(find_biggest_attribute([]))
```
Running `mypy` raises:
```bash
mypy_bug.py:10: error: Item "None" of "Optional[MyObject]" has no attribute "attribute"  [union-attr]
        return max(objects, default=None, key=lambda object: object.attribute)
                                                             ^~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 1 source file)
```

As per [Python built-in max() documentation](https://docs.python.org/3/library/functions.html#max):

> The default argument specifies an object to return if the provided iterable is empty. If the iterable is empty and default is not provided, a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError) is raised.

**Comment by JelleZijlstra** [comment]
Please do not post on unrelated ancient issues. What you experience is a problem with mypy, not typeshed. It's probably the same as python/mypy#14664.
