### ISSUE TITLE
Missing special methods for `object`

### ISSUE THREAD

**Issue by z33ky** [python/typeshed#773]
As per python/mypy#2581.

`object` is missing some special methods. `__getattribute__` is mentioned in the mypy issue, but there are more, like `__bool__` for instance.

**Comment by z33ky** [comment]
I'm trying myself on a pull request adding these by going through the Python documentation for special methods.
While I'm going through them I'll reorder the methods I encounter as they are in the docs, if that's fine.

**Comment by gvanrossum** [comment]
Actually I much prefer PRs that don't clean up things. Easier to review and
keeps the "git blame" output more correct.

--Guido (mobile)

**Comment by JukkaL** [comment]
As mentioned in a comment left at the PR, please check that the methods actually exist at runtime (e.g., evaluate `object().__bool__`).

**Comment by gvanrossum** [comment]
Closed by #774.
