### ISSUE TITLE
Conda cannot parse our requirements-test.txt file

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#7757]
This came up at a mentored sprint event at pycon just now -- a new contributor was trying to use a conda virtual environment instead of the stdlib `venv`, but conda does not seem to be able to parse our requirements.txt file because of this line:

https://github.com/python/typeshed/blob/c6b3211afaa8fa450e79a9c9674bbfd472593702/requirements-tests.txt#L2

**Comment by AlexWaygood** [comment]
:(

I hate the idea of duplicating our test requirements in _yet another_ file. We already have substantial duplication between our `requirements-tests.txt` file and our `.pre-commit-config.yaml` file.

Given that this has only come up once, maybe this should be closed as "won't fix" for now.

**Comment by srittau** [comment]
I agree that closing this is the best solution. This is obviously a Conda bug, and having the marker is important.
