### ISSUE TITLE
Do turtle Vec2D TODO

### ISSUE THREAD

**Issue by jpgoldberg** [python/typeshed#7762]
`stdlib/turtle.pyi` contains this TODO

```
# TODO: Type this more accurately
# Vec2D is actually a custom subclass of 'tuple'.
Vec2D: TypeAlias = tuple[float, float]
```

I don't know what resources and priorities you all have, but this caused me a bit of bother. Here is some sample code illustrating the problem.

```
# Python 3.10.1; mypy 0.950
from turtle import Vec2D
# Vec2D is a class and a type alias

v1 = Vec2D(1,1) # mypy doesn't recognize it as callable

v2 = v1.rotate(90) # illustrate that Vec2D has methods
```

Resulting in

```
% mypy vec_type_problem.py 
vec_type_problem.py:5: error: "object" not callable
Found 1 error in 1 file (checked 1 source file)
```

I wish I could help, but I am new to Python and just trying to figure out how to get some type checking.

Is my mitigation in the meantime just to add a comment to line 5 telling mypy to ignore the error?

**Comment by JelleZijlstra** [comment]
Thanks for bringing this up! We'll fix it, but it will take a while before the fix makes it into a mypy release. In the meantime, I'd recommend `# type: ignore` with a comment pointing to this issue.
