### ISSUE TITLE
Compatibility issues between base and C-accelerated pyyaml types

### ISSUE THREAD

**Issue by masklinn** [python/typeshed#7768]
pyyaml does not implicitly swap out the C-accelerated types for the base ones because there are observable differences between the two (yaml/pyyaml#436).

However for packages only expected relatively simple inputs, a common pattern is to try and use the libYAML types if available and fallback:

```python
try:
    from yaml import CLoader as Loader
except ImportError:
    from yaml import Loader
```
However running this through mypy yields:
```
error: Incompatible import of "Loader" (imported name has type "Type[Loader]", local name has type "Type[CLoader]")
```
While this is *technically* correct, it's not exactly convenient. Is there a local workaround aside from `type: ignore`, or a way to fix this in the stubs?

Tested with:
- CPython 10.4
- mypy 0.950
- types_PyYAML 6.0.7

**Comment by JelleZijlstra** [comment]
I don't think we can fix this in typeshed. I believe there are already some mypy issues about this pattern.

**Comment by AlexWaygood** [comment]
> I don't think we can fix this in typeshed. I believe there are already some mypy issues about this pattern.

https://github.com/python/mypy/issues/1153 for one

**Comment by Akuli** [comment]
> Is there a local workaround aside from `type: ignore`

Yes, but it's much uglier than `# type: ignore`:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from yaml import Loader
else:
    try:
        from yaml import CLoader as Loader
    except ImportError:
        from yaml import Loader
```
