### ISSUE TITLE
unittest.TextTestRunner.run return type misjudge

### ISSUE THREAD

**Issue by reverbhorn** [python/typeshed#777]
I've got the following error when using mypy:

```
$ mypy -s foo.py
foo.py: note: In function "run_tests":
foo.py:10: error: "run" of "TestRunner" does not return a value
```
However, according to [3.5.2 documentation](https://docs.python.org/3/library/unittest.html#unittest.TestResult):
> ...a TestResult instance is returned by the TestRunner.run() method...

Although the result class can be altered in the constructor of `TextTestRunner`, I believe it should still be a child class of `TestResult`.

It should be able to fix by changing the return value in `typeshed/stdlib/3/unittest/__init__.pyi:290` from `None` to `TestResult`.

**Comment by ambv** [comment]
Yeah, TestResult is at least a class you can inherit from. TestRunner is a duck typed concept so the stubs lie and there's not really a way for us to use this type. The stubs need work here, definitely. For now, I'll appvoe #778 since it is an improvement.
