### ISSUE TITLE
How should functions that receive a hashlib.new value be typed?

### ISSUE THREAD

**Issue by hackaugusto** [python/typeshed#7775]
https://github.com/python/typeshed/pull/1268 made the class `Hash` private, I can get things working with:

```python
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from hashlib import _Hash


def f(h: "_Hash") -> None:
    ...

```

But I wonder what is the best practice in this case, should the type be redefined on my codebase instead of using the private value?

**Comment by JelleZijlstra** [comment]
Unfortunately there's no good solution for this in stubs. We could ask CPython to expose the Hash class publicly, which would solve the problem for future versions. Until then, `if TYPE_CHECKING:` is your best bet.

**Comment by AlexWaygood** [comment]
I'm closing this as I don't think there's anything actionable here for typeshed, unfortunately 😕 as @JelleZijlstra says, a potential solution probably lies with CPython — you could definitely consider opening an issue there 🙂
