### ISSUE TITLE
`subprocess.call()` is missing `text` argument (in Python >=3.7)

### ISSUE THREAD

**Issue by asqui** [python/typeshed#7777]
The type annotation for `subprocess.call()` is missing the `text` argument (introduced in Python 3.7).

The type annotation for `call()` is accompanied by a comment that says `# Same args as Popen.__init__` but is not Python-version-specific and does not include the `text` argument:
https://github.com/python/typeshed/blob/b1ccd03d51f5efe5f600e8ede1810a253d35e1cd/stdlib/subprocess.pyi#L446-L467

The annotation for `Popen.__init__`, nay `Popen.__new__`, on the other hand, is in a Py >=3.7 branch to include `text`:
https://github.com/python/typeshed/blob/b1ccd03d51f5efe5f600e8ede1810a253d35e1cd/stdlib/subprocess.pyi#L807-L833

I guess `call()` needs a similar 3.7+ branch?

**Comment by srittau** [comment]
Considering that we are dropping Python 3.6 support in about two months, I'd be fine with just adding the argument unconditionally.

**Comment by asqui** [comment]
Nice! That will certainly help maintainability… would you like me to prepare a PR?

**Comment by AlexWaygood** [comment]
> Nice! That will certainly help maintainability… would you like me to prepare a PR?

Go for it! We welcome PRs here in typeshed :)

**Comment by asqui** [comment]
Nice! Thanks for fixing this and sorry for dragging my feet on my proposed contribution. (I had to get open source contribution clearance from my employer which somewhat stifled momentum. Excuses excuses :-) )
