### ISSUE TITLE
Pillow Image.Image.paste() stub is incorrect

### ISSUE THREAD

**Issue by GameDungeon** [python/typeshed#7778]
I'm getting this error from mypy:
`Argument 1 to "paste" of "Image" has incompatible type "int"; expected "Image"`
The method paste on the Image class does accept an image for the first argument but it also accepts other things mentioned [here in the docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste):

> Instead of an image, the source can be a integer or tuple containing pixel values. The method then fills the region with the given color. When creating RGB images, you can also use color strings as supported by the ImageColor module.

**Comment by AlexWaygood** [comment]
Thanks — PR welcome!
