### ISSUE TITLE
PIllow: Image.mode should be _Mode, not str

### ISSUE THREAD

**Issue by Julian-O** [python/typeshed#7805]
When you create Image instances in Pillow, you pass a `mode` which tells it what colour system to use (e.g. "RGB", "CMYK") by passing a string. There are only 12 valid string values.

[Image.pyi](https://github.com/python/typeshed/blob/master/stubs/Pillow/PIL/Image.pyi) (line 17) defines a `_Mode` TypeAlias for the Literal values it can be. 

Once you have created the Image instance, you can find what mode it is in by accessing the `mode` attribute. [Image.pyi](https://github.com/python/typeshed/blob/master/stubs/Pillow/PIL/Image.pyi) (line 108) defines the `mode` attribute as a str

As a result, if you try to create one image instance with the same mode as another:

    from PIL import Image
    im1 = Image.new(mode="RGBA", size=(100, 100), color="white")
    im2 = Image.new(mode=im1.mode, size=im1.size, color="black")

you get a type warning that it expected a type Literal, but got a str instead.

----

My recommendation is that Image.pyi defines the `mode` attribute to be of type `_Mode`.

I am still a beginner with some of these concepts, so I suggest taking my recommendation with a grain of salt.

**Comment by JelleZijlstra** [comment]
That sounds right, feel free to submit a PR!
