### ISSUE TITLE
Unexpected typecheck failures with redis.asyncio type stubs

### ISSUE THREAD

**Issue by achimnol** [python/typeshed#7837]
```
tests/test_redis_storage.py:21: error: Missing type parameters for generic type "Redis"  [type-arg]
tests/test_redis_storage.py:34: error: Missing type parameters for generic type "Redis"  [type-arg]
tests/test_redis_storage.py:39: error: Incompatible types in "await" (actual type "Optional[bool]", expected type "Awaitable[Any]")  [misc]
tests/test_redis_storage.py:43: error: Missing type parameters for generic type "Redis"  [type-arg]
tests/test_redis_storage.py:45: error: Incompatible types in "await" (actual type "Optional[bool]", expected type "Awaitable[Any]")  [misc]
tests/test_redis_storage.py:49: error: Missing type parameters for generic type "Redis"  [type-arg]
tests/test_redis_storage.py:52: error: Incompatible types in "await" (actual type "Optional[Any]", expected type "Awaitable[Any]")  [misc]
...
```
Happens with:
 - Python 3.10.4
 - mypy 0.950
 - redis 4.3.1
 - types-redis 4.2.2
 - [a code](https://github.com/aio-libs/aiohttp-session/pull/701) that replaced `import aioredis` with `from redis import asyncio as aioredis` ([ghaction check result](https://github.com/aio-libs/aiohttp-session/runs/6440291499?check_suite_focus=true))

All the related codes run fine at runtime.

**Comment by Akuli** [comment]
All of your errors are explained here: https://github.com/python/typeshed/issues/7597#issuecomment-1117551641

**Comment by AlexWaygood** [comment]
@achimnol, do you still get false-positive errors with the latest `redis` stubs now that #7820 has been merged?

**Comment by achimnol** [comment]
I've updated `types-redis` to 4.2.3 and running mypy still gives:
```console
$ python -m mypy aiohttp_session
aiohttp_session/redis_storage.py:62: error: Incompatible types in "await" (actual type "Optional[bytes]", expected type "Awaitable[Any]")  [misc]
aiohttp_session/redis_storage.py:87: error: Incompatible types in "await" (actual type "Optional[bool]", expected type "Awaitable[Any]")  [misc]
Found 2 errors in 1 file (checked 6 source files)
```

**Comment by achimnol** [comment]
Ah, I could fix the above type errors in the aiohttp-session side.
Now it seems that everything is ok!

**Comment by AlexWaygood** [comment]
> Ah, I could fix the above type errors in the aiohttp-session side.
> Now it seems that everything is ok!

Brilliant, thanks for checking!
