### ISSUE TITLE
`_TemporaryFileWrapper[bytes]` somehow isn't a `BinaryIO`

### ISSUE THREAD

**Issue by adamnovak** [python/typeshed#7843]
With this test file `repro.py`:

```python
import tempfile
from typing import BinaryIO

my_var: BinaryIO = tempfile.NamedTemporaryFile()
```

I get this error from `mypy repro.py`:

```
repro.py:4:20: error: Incompatible types in assignment (expression has type "_TemporaryFileWrapper[bytes]", variable has type "BinaryIO")  [assignment]
    my_var: BinaryIO = tempfile.NamedTemporaryFile()
                       ^
Found 1 error in 1 file (checked 1 source file)
```

This is with `mypy` version 0.941.

The [`NamedTemporaryFile()` docs](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) say that it "operates exactly as [TemporaryFile()](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile) does", save for always having a name, and `TemporaryFile()` is documented to return a file-like object and to default to binary mode.

If `BinaryIO` is meant to represent a binary-mode file-like object, then there's something wrong with they type annotations if it's not able to match the return value of `NamedTemporaryFile()`.

**Comment by srittau** [comment]
`IO` and its subclasses `BinaryIO` and `TextIO` predate the introduction of protocols and are considered legacy by the typeshed team. Not every I/O class is going to subclass them and they shouldn't be used in argument types. In this particular case, it should be able to annotate the variable as `IO[bytes]`, though.
