### ISSUE TITLE
Make requests work for pyright in strict mode

### ISSUE THREAD

**Issue by brandonchinn178** [python/typeshed#7869]
Running pyright in strict mode currently errors for requests function calls:

```python
import requests
r = requests.post("http://httpbin.org/post", json={"a": 1})
print(r.json())
```

```
  48:19 - error: Type of "post" is partially unknown
  Type of "post" is "(url: str | bytes, data: str | bytes | MutableMapping[str, Any] | Iterable[Tuple[Text, str | None]] | IO[AnyStr] | None = ..., json: Any | None = ..., **kwargs) -> Response" (reportUnknownMemberType)
  59:18 - error: Type of "json" is partially unknown
  Type of "json" is "(**kwargs) -> Any" (reportUnknownMemberType)
```

**Comment by JelleZijlstra** [comment]
What specifically is pyright complaining about here? `requests.post` has no unannotated parameters: https://github.com/python/typeshed/blob/3aaa1d0adafc0ec58171980e8da579e7e44265fb/stubs/requests/requests/api.pyi#L91

**Comment by brandonchinn178** [comment]
I believe it doesn't like the Any?

**Comment by brandonchinn178** [comment]
oh apologies, I just realized I'm on a super old version of pyright, which bundles an old version of typeshed. Let me try updating

**Comment by Akuli** [comment]
I was about to say it probably uses a very old version of the stubs, because the error message mentions `**kwargs` which haven't been there in a long time :)
