### ISSUE TITLE
`assert(Not)AlmostEqual(s)` specifies the type as `float`

### ISSUE THREAD

**Issue by vnmabus** [python/typeshed#7891]
`assert(Not)AlmostEqual(s)` specifies the type as `float` or `datetime.datetime`, when in practice it works also with other types that support subtraction, absolute value, rounding and comparison with zero, such as `Fraction` or `Decimal`.

This should be fixed (using `TypeVar` and a `Protocol`) to prevent Mypy errors in tests that use these types.

**Comment by srittau** [comment]
Seems reasonable. Any PRs welcome!
