### ISSUE TITLE
Wrong stub for `fileinput.input()`

### ISSUE THREAD

**Issue by Molkree** [python/typeshed#7922]
@JelleZijlstra:
> the stubs appear to be wrong here:
https://github.com/python/typeshed/blob/6e18441a2c1e5836eca4e6763a9590d2b9270378/stdlib/fileinput.pyi#L32
Only the `openhook` argument constrains the TypeVar, but it has a default, and if the argument is not given there's nothing for the type checker to use to decide on the value of the TypeVar. The typeshed stub should be changed to add a separate overload where `openhook` is not given.

https://github.com/microsoft/pyright/issues/3494#issuecomment-1133985204

**Comment by AlexWaygood** [comment]
The stubs at the moment look quite buggy indeed! From my reading of the source code, I don't think it's actually the `openhook` parameter at all that determines whether the object returned is of type `FileInput[str]` or `FileInput[bytes]`. Instead, it's the value passed into the `mode` parameter. (You can see this by looking at the `FileInput._readline` method, which is called from `FileInput.__next__`.)

IO modes can be tricky to type in stub files, but it should be possible.
