### ISSUE TITLE
Awaitable is not a valid argument for ensure_future

### ISSUE THREAD

**Issue by WeirdCarrotMonster** [python/typeshed#794]
[Relevant documentation here](https://docs.python.org/3/library/asyncio-task.html#asyncio.ensure_future):
> Changed in version 3.5.1: The function accepts any awaitable object.

I'd submit a PR, but i don't quite understand project structure: do i need to fully copy stubs from 3.4 to 3.5 and add annotations there?

**Comment by ambv** [comment]
Use `if sys.version_info` checks, see stdlib/3.4/pathlib.pyi for an example.

**Comment by WeirdCarrotMonster** [comment]
Okay, i wrote version check for stubs:
```python
if sys.version_info < (3, 5, 1):
    def ensure_future(coro_or_future: Union[Future[_T], Generator[Any, None, _T]],
                      *, loop: AbstractEventLoop = ...) -> Future[_T]: ...
else:
    def ensure_future(coro_or_future: Union[Future[_T], Generator[Any, None, _T], Awaitable[_T]],
                      *, loop: AbstractEventLoop = ...) -> Future[_T]: ...
```
but mypy_test fails with error `All conditional function variants must have identical signatures`.
Why does it happen here, but not with other functions with different signatures, like `pathlib.mkdir`, `pathlib.resolve`. Did i miss something?

**Comment by gvanrossum** [comment]
Mypy currently doesn't support three-number version numbers. Just pretend that that function works that way from 3.5 up.

**Comment by JelleZijlstra** [comment]
Awaitable was itself only introduced with 3.5, so I'm not sure any version_info checking is useful here.

This issue can be closed.
