### ISSUE TITLE
`re.split` has seemingly unnecessary `Any`s

### ISSUE THREAD

**Issue by GrantGryczan** [python/typeshed#7940]
I would think that the ` | Any`s in the following four return types should be removed.

https://github.com/python/typeshed/blob/54e11a1ec48ccfde21642fafe1e531117c0da9f6/stdlib/typing.pyi#L1144
https://github.com/python/typeshed/blob/54e11a1ec48ccfde21642fafe1e531117c0da9f6/stdlib/typing.pyi#L1146
https://github.com/python/typeshed/blob/54e11a1ec48ccfde21642fafe1e531117c0da9f6/stdlib/re.pyi#L184
https://github.com/python/typeshed/blob/54e11a1ec48ccfde21642fafe1e531117c0da9f6/stdlib/re.pyi#L188

**Comment by JelleZijlstra** [comment]
They're there because the list entries can be None:

```
In [6]: re.split(r"(a)|(b)", "canada")
Out[6]: ['c', 'a', None, 'n', 'a', None, 'd', 'a', None, '']
```

Though this behavior doesn't appear to be documented: https://docs.python.org/3.10/library/re.html#re.split

**Comment by GrantGryczan** [comment]
Huh, alright then. Strange that it isn't documented.

**Comment by GrantGryczan** [comment]
Actually, would it be a bad idea to replace the `Any`s with `None` in that case?

**Comment by JukkaL** [comment]
Having `None` in the return value would likely cause many false positives, since often the caller can predict that there will only be strings. That's why the `| Any` was there in the first place instead of `| None`. 

It would be good to add a comment explaining the `Any` types, as otherwise this will continue to cause confusion.

**Comment by AlexWaygood** [comment]
> It would be good to add a comment explaining the `Any` types, as otherwise this will continue to cause confusion.

@srittau has proposed #7870 to tackle this problem in a more general way; we're currently ~~bikeshedding~~ debating the appropriate name for the feature.
