### ISSUE TITLE
csv.DictReader marked as producing Dict[str, str] but can have a None key

### ISSUE THREAD

**Issue by calimeroteknik** [python/typeshed#7953]
Here is an example to illustrate:
```python
import csv
from io import StringIO

csvtext = "foo,bar\n1,2\n3,4,5"

csvreader = csv.DictReader(StringIO(csvtext), delimiter=',')

#def checkrow(row: dict[str | None, str]) -> None:
def checkrow(row: dict[str, str]) -> None:
	if None in row:
		print(f"None found as key with value {row[None]!r}, someone broke a promise!")

for row in csvreader:
	print(row)
	checkrow(row)
```

Type checkers complain: `error: Invalid index type "None" for "Dict[str, str]"; expected type "str"`

Signature visible here: https://github.com/python/typeshed/blob/master/stdlib/csv.pyi#L107

I'm not certain what could/should be done, but by construction `if None in foo: something(row[None])" is assuredly fine.
And if it were unreachable code, then it would never execute. But it does execute:
```
None found as key with value ['5'], someone broke a promise!
```

Trying the commented signature doesn't make typechecking happy either:
```
error: Argument 1 to "checkrow" has incompatible type "Dict[str, str]"; expected "Dict[Optional[str], str]"
```

I suppose that the type in the typeshed isn't quite a match with the library currently.

**Comment by JelleZijlstra** [comment]
This is documented behavior (https://docs.python.org/3.10/library/csv.html#csv.DictReader), but I'm worried that it will lead to a lot of new false positives if we give the precise type.

Maybe we could use `dict[str | Any, str | Any]`

**Comment by calimeroteknik** [comment]
This seems like typeshed cannot do much about it indeed, as this library interface looks not to be adequately typable as it stands.

Perhaps the best way to handle the issue going forward, is to add a better interface to the DictReader module?
For instance usage such as `csv.DictReader(csvfile, enforce_fieldcount=True)` could result in an exception being raised in case there is a mismatch between the expected number of columns and the format of a row. This would forcefully lead to a homogenous row type.

An even better interface might be the idea of a TupleReader where it's possible to encode the fields of the table in the type system (in case it's static — this limits usefulness somewhat).

(In the meantime I am using a restkey with type `str`, but I would be glad to participate in making this interface saner!)

**Comment by AlexWaygood** [comment]
> Perhaps the best way to handle the issue going forward, is to add a better interface to the DictReader module?

At typeshed, we can't really do much to change the implementation. If you'd like to discuss changing the interface for `DictReader`, that needs to happen over at the CPython issue tracker (and it would probably be best to start a discussion over at https://discuss.python.org first).

I can't predict what kind of response you'll get, though -- I think the `csv` module has been pretty stable for a while now, and several core developers are quite resistant to the idea of changing stdlib interfaces for the benefit of static typing.

**Comment by Akuli** [comment]
`enforce_fieldcount=True` wouldn't be just for static typing though. It could prevent errors from passing silently if your csv file suddenly has more columns than expected.

**Comment by AlexWaygood** [comment]
> `enforce_fieldcount=True` wouldn't be just for static typing though. It could prevent errors from passing silently if your csv file suddenly has more columns than expected.

Better to lead with that than "this conversation started over at typeshed", I think, if we want to persuade the CPython core devs :)

**Comment by AlexWaygood** [comment]
https://github.com/python/typeshed/pull/8061#issuecomment-1153170245 confirms that we can't change the signature to `dict[str | None, str | None]` without introducing a large number of false-positive errors.
