### ISSUE TITLE
pillow image modes are missing

### ISSUE THREAD

**Issue by misimisi171718** [python/typeshed#7956]
some of the image modes are missing from type hints like `pa` and others documented [here](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes)

```python
PIL.Image.new("pa",(5,5),(255,255))
```
throes the error
```
Argument 1 to "new" has incompatible type "Literal['PA']"; expected "Literal['1', 'CMYK', 'F', 'HSV', 'I', 'L', 'LAB', 'P', 'RGB', 'RGBA', 'RGBX', 'YCbCr']"
```

**Comment by AlexWaygood** [comment]
Thanks — PR welcome!
