### ISSUE TITLE
request: Ansible stubs

### ISSUE THREAD

**Issue by q0w** [python/typeshed#8016]
Hi, I am interested in Ansible stubs. Would you accept the pr?

**Comment by AlexWaygood** [comment]
It looks like it meets [our criteria for being added](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-stubs), so: probably!

However, it looks like it's a pretty huge package. Please don't file a huge PR adding stubs for all parts of it all at once: a PR like that will be really difficult for us to review. Instead, take a look at [our guidelines for contributing stubs that are incomplete](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#incomplete-stubs). It would be much better to first add some incomplete stubs, and then in follow-up PRs gradually fill in the details for the rest of the library.
