### ISSUE TITLE
`xml.etree.ElementTree.Element` is not a subclass of `MutableSequence`

### ISSUE THREAD

**Issue by Prometheus3375** [python/typeshed#8030]
According to [Python docs](https://docs.python.org/3/library/collections.abc.html) any `MutableSequence` must define next methods:
```
# Must be defined by user
__getitem__
__setitem__
__delitem__
__len__
insert
# Defined in Sequence
__contains__
__iter__
__reversed__
index
count
# Defined in MutableSequence
append
reverse
extend
pop
remove
__iadd__
```
Methods defined in `Sequence` and `MutableSequence` are available in user's class only if that class inherits from them (or user defines these methods in the class).

`typeshed` [claims](https://github.com/python/typeshed/blob/master/stdlib/xml/etree/ElementTree.pyi#L135) that `xml.etree.ElementTree.Element` is a subclass of `MutableSequence`, i. e., `Element` defines all methods above. Unfortunately this is wrong. `Element` does not inherit from `MutableSequence` and it [defines](https://docs.python.org/3.10/library/xml.etree.elementtree.html#element-objects) only next methods from `MutableSequence`:
```
__len__
__getitem__
__setitem__
__delitem__
append
extend
insert
remove
```

In my opinion inheriting from `MutableSequence` must be removed to avoid errors like method `pop` being a part of `Element`.

**Comment by AlexWaygood** [comment]
> In my opinion inheriting from `MutableSequence` must be removed to avoid errors like method `pop` being a part of `Element`.

It's true that `Element` does not implement the full suite of mixin methods that classes get "for free" if they actually inherit from `collections.abc.MutableSequence` at runtime. However, it nonetheless implements the core interface of `MutableSequence`, and therefore does behave like a `MutableSequence` in most respects.

As a compromise we could do something like the following, which would mean that mypy would continue to recognise `Element` as a `MutableSequence`, but would also emit errors if a user tried to call `.pop()`, `.index()`, `.count()`, `.reverse()`, or `.__iadd__`. Mypy [gives an okay error message](https://mypy-play.net/?mypy=latest&python=3.10&flags=warn-unused-ignores&gist=25cdaeb79458a2dcf7236cfc68969ff0) if we do this:

```python 
from collections.abc import MutableSequence
from typing import ClassVar
from types import NotImplementedType

class Element(MutableSequence[Element]):
    # rest of the class definition as before
    pop: ClassVar[NotImplementedType]
    index: ClassVar[NotImplementedType]
    count: ClassVar[NotImplementedType]
    reverse: ClassVar[NotImplementedType]
    __iadd__: ClassVar[NotImplementedType]

e = Element()
e.pop()  # error: NotImplemented? not callable
```

**Comment by Prometheus3375** [comment]
> mypy would continue to recognise Element as a MutableSequence
Why is this necessary?

When `MutableSequence` is an argument, then it is expected that all its methods are available. Otherwise Liskov substitution principle is violated. Code below [passes mypy checks](https://mypy-play.net/?mypy=latest&python=3.10&flags=warn-unused-ignores&gist=edf8361ee7c5ee7cf0f985b9c0cb0913), but raises Attribute error at runtime:
```
from collections.abc import MutableSequence
from xml.etree.ElementTree import Element
from typing import TypeVar


T = TypeVar('T')


def pop_last_or_none(ms: MutableSequence[T], /) -> T | None:
    if len(ms) > 0:
        last = ms.pop()
    else:
        last = None
        
    return last
        

e = Element('child')
r = Element('root')
r[0] = e
pop_last_or_none(r)
``` 

In addition, subclassing `MutableSequence` is not required to correspond explicit runtime check, because `issubclass(Element, MutableSequence)` is `False`.

Honestly, I would be happy if `Element` implemented `MutableSequence` fully or subclassed it, but right now these methods are not available, and several dependent on typeshed tools (ex. PyCharm) suggest them. Your proposal will solve this.

**Comment by AlexWaygood** [comment]
Okay, I created a PR to remove inheritance from `MutableSequence`: #8056. I was expecting there to be a larger fallout from `mypy_primer`, but in fact it seems as though there is little impact on the third-party code tested by primer.

I still think that there might be unforeseen consequences to making this class no longer be a `(Mutable)Sequence`, give that it's been typed as a `Sequence` for so long in typeshed. The mixin methods on `MutableSequence` are much less important than the abstract methods, so for the vast majority of situations where a `MutableSequence` is required, an `Element` will suffice.

But I don't know that there are many situations where a function requires `<any sequence of some kind>` and a user passes in an `Element`. And I do agree that we should reflect the runtime as closely as possible in most situations. So I guess I'm neutral on this now.
