### ISSUE TITLE
Help isinstance() recognize _SelectorDatagramTransport as subtype of asyncio.DatagramProtocol

### ISSUE THREAD

**Issue by haxtibal** [python/typeshed#8051]
Consider a custom datagram-only asyncio protocol:
```python
import asyncio

class MyProtocol(asyncio.DatagramProtocol):
    def connection_made(self, transport: asyncio.BaseTransport):  # signature as per typeshed super class
        if not isinstance(transport, asyncio.DatagramTransport):
            raise TypeError("%s not supported because it's not a datagram transport." % type(transport))
        # ...
```

For UDP connections on Linux, the above code results in
```
TypeError: <class 'asyncio.selector_events._SelectorDatagramTransport'> not supported because it's not a datagram transport.
```

Per implementation, [class _SelectorDatagramTransport](https://github.com/python/cpython/blob/main/Lib/asyncio/selector_events.py#L1126) is a structural subtype of [class DatagramTransport](https://github.com/python/cpython/blob/main/Lib/asyncio/transports.py#L172), but it does not actually inherit. However, from a users perspective I'd say both static and runtime type checks should succeed.

I'm unsure if the required change would have to go to cpython (let `_SelectorDatagramTransport` inherit `DatagramTransport`) or to typeshed (define `BaseTransport` and `DatagramTransport` as `typing.Protocol` with `@runtime_checkable`). What would you say?

If you think this is a valid request, I could try a PR.

**Comment by AlexWaygood** [comment]
Typeshed doesn't have any control over the way `isinstance()` works at runtime. So if you want to make this structural check work at runtime, you'll have to file an issue over at CPython.

I'm sympathetic to making the protocols in `asyncio.protocols` `typing.Protocol`s in the stub, so that mypy would recognise `_SelectorDatagramTransport` as a subtype of `DatagramTransport`. But when I proposed doing that in #7186, the consensus among the other typeshed maintainers was that that was a bad idea.

**Comment by haxtibal** [comment]
Thank's for clarifying! Just found python/cpython#30291 will solve the exact issue. Looks like @asvetlov has it on his agenda.

So, feel free to close here (or leave open in case it somehow contributes to #7186).

**Comment by kumaraditya303** [comment]
I have fixed this upstream with https://github.com/python/cpython/pull/98844. With my limited understanding of typing, these should be `typing.Protocol` since `asyncio` supports duck typing for protocols and transports etc.
