### ISSUE TITLE
On including default values

### ISSUE THREAD

**Issue by hoechenberger** [python/typeshed#8060]
Hello all,

after reading the [contributing guide](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions) and following some discussions here and on the pyright issue trackers, it seems clear to me that default parameter values should not go into the type stubs. However, the last postings about this issue I could find are now already several months old, and I just wanted to kindly ask if there's been any new developments in the meantime?

I am asking because we're developing scientific software packages, and it's extremely important to our users that default values are displayed as part of the function signature in their IDE (VS Code). However, Pylance unfortunately doesn't replace the placeholder `...` shipping with `typeshed` with the functions' default values, so what users see is something like this (stubs for the `mne_bids` package are not yet part of `typeshed`; I'm currently working on them, following the contributing guide):

<img width="1045" alt="Screen Shot 2022-06-12 at 14 54 53" src="https://user-images.githubusercontent.com/2046265/173234230-50296a3b-3d4e-424e-8773-e32dd5baed54.png">

So I was wondering of how "strong" this rule is today – is it a "hard" requirement still, or just a recommendation?

Any advice would be greatly appreciated!

Thank you very much,
Richard

**Comment by AlexWaygood** [comment]
> So I was wondering of how "strong" this rule is today – is it a "hard" requirement still, or just a recommendation?

Currently, our linter `flake8-pyi` will emit an error if you try to use a default value for an argument that isn't `...` in a stub.

We could consider switching that error code off for your stubs, though, if it's a major problem.

**Comment by hoechenberger** [comment]
Thank you very much for your swift response, @AlexWaygood! I will be in touch again once the type stubs are ready and tested locally :) 

Since my question has been answered, I'll close this issue for now.

Thanks again, and have a great Sunday!

**Comment by AlexWaygood** [comment]
> Thanks again, and have a great Sunday!

Thank you, you too!
