### ISSUE TITLE
TypedDict `update()` method thinks that all fields need to be updated

### ISSUE THREAD

**Issue by wch** [python/typeshed#8086]
Example:

```py
from typing import TypedDict

class Foo(TypedDict):
    a: str
    b: str

f: Foo = {"a": "A1", "b": "B1"}
f.update({"a": "A2"})

print(f)
# > {'a': 'A2', 'b': 'B1'}
```

When I run it through pyright, I get the following output:

```
/...../test.py:10:10 - error: Argument of type "dict[str, str]" cannot be assigned to parameter "__m" of type "Foo" in function "update"
    "b" is required in "Foo" (reportGeneralTypeIssues)
```

I think this is because the `update()` method declaration says that `self` and `__m` are the same type:

```py
def update(self: _T, __m: _T) -> None: ...
```

https://github.com/python/typeshed/blob/4967c8bc12587d503a9ffcbeb3b716b1e97f19cc/stdlib/typing.pyi#L902-L916

**Comment by AlexWaygood** [comment]
I don't think the type can be expressed in the stub here. I think this needs to be special-cased by type checkers.

**Comment by AlexWaygood** [comment]
Mypy indeed has no issues with your code: https://mypy-play.net/?mypy=latest&python=3.10&flags=strict&gist=647449232e2516753510121119ef137c.

So I'm going to assert that this is a pyright-specific problem.

**Comment by wch** [comment]
Interesting. Is this special cased in mypy?

**Comment by AlexWaygood** [comment]
> Interesting. Is this special cased in mypy?

Presumably :)
