### ISSUE TITLE
Figure out a more precise type for `__format__`

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#810]
Currently it accepts a `str` only, but it seems to work with `unicode` in Python 2:

```
>>> object().__format__(u'')
u'<object object at 0x109195150>'
```

**Comment by JelleZijlstra** [comment]
In #1191 I changed a couple of Python 2-only stubs to use the form `def __format__(self, fmt: AnyStr) -> AnyStr: ...`. I haven't tested it on objects other than datetimes, but maybe we can use that form elsewhere.

**Comment by JelleZijlstra** [comment]
This affects only Python 2. If nobody felt the need to fix it since 2017, I don't think we still need this.
