### ISSUE TITLE
dbapi2 set_progress_handler callback return type

### ISSUE THREAD

**Issue by LefterisJP** [python/typeshed#8105]
I have a question regarding the type in dbapi's sqlite `set_progress_handler` callback return type.

It seems to be defined here:
https://github.com/python/typeshed/blob/a750a42c65b77963ff097b6cbb6d36cef5912eb7/stdlib/sqlite3/dbapi2.pyi#L344

and to set the return type to an optional bool.

But from what I see in the [docs](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.set_progress_handler) and from the behaviour when trying to use it the callback should return an `int` and if that is a non-zero int the execution will be terminated.

Now, with boolean this will also work, but execution would be terminated if `True` is returned, and it would keep on going if `False` is returned.

I think it would make more sense to have the type definitions aligned with the docs and have it return an Optional int.

**Comment by srittau** [comment]
I agree that we should change `bool` to `int`. `bool` returns will still be accepted though, since `bool` is a subtype of `int`. But that's a good thing here as it won't break existing code. PR welcome!

**Comment by LefterisJP** [comment]
Thanks, I will open a PR then @srittau! :)

Just wanted to confirm with an issue first by asking you guys!
