### ISSUE TITLE
Unable to find `collections.abc.Iterable`

### ISSUE THREAD

**Issue by lamenezes** [python/typeshed#817]
I've implemented something like the following code, but mypy checks returns the error in the title

```python
from collections import abc


class Foo(abc.Iterable, abc.Container):
    pass
```

The complete error output is:
```
example.py:4: error: Name 'abc.Iterable' is not defined
```

It seems mypy checks aren't considering the `collections.abc` module. Since `collections.Container` is found, but not `collections.abc.Iterable`.

Is this really an issue or am I missing something?

**Comment by gvanrossum** [comment]
Thanks for reporting. The problem is that the [stub for collections.abc](https://github.com/python/typeshed/blob/master/stdlib/3/collections/abc.pyi) is incomplete, it is missing some imports.

Do you feel like helping out by submitting a pull request?

**Comment by lamenezes** [comment]
Sure, I will submit a PR as soon as I can.
