### ISSUE TITLE
`types-bleach` mypy error: Dict entry 2 has incompatible type "str": "Callable[[str, str, str], bool]"; expected "str": "List[str]"

### ISSUE THREAD

**Issue by vin-ai** [python/typeshed#8193]
Can't use callable to filter attributes as bleach supports and has [documented](https://bleach.readthedocs.io/en/latest/clean.html#using-functions):

- **python**: 3.9.5
- **bleach**: 5.0.0
- **mypy**: 0.961

```python3
import bleach
from urllib.parse import urlparse

ALLOWED_IFRAME_DOMAINS = ["youtube.com", "facebook.com", "vimeo.com", "dailymotion.com"]


def allowed_iframe_src(tag: str, name: str, value: str) -> bool:
    if name in ("alt", "height", "width", "allowfullscreen"):
        return True

    if name == "src":
        parsed_result = urlparse(value)
        return (
            not parsed_result.netloc
        ) or parsed_result.netloc in ALLOWED_IFRAME_DOMAINS

    return False


ALLOWED_ATTRIBUTES = bleach.sanitizer.ALLOWED_ATTRIBUTES
ALLOWED_ATTRIBUTES.update(
    {
        "a": ALLOWED_ATTRIBUTES.get("a", []) + ["rel"],
        "img": ["width", "height", "src", "alt"],
        "iframe": allowed_iframe_src,  # type: ignore
        "*": ["style", "class"],
    }
)


@keep_lazy_text
def clean_html(content):
    return bleach.clean(
        content,
        tags=bleach.sanitizer.ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        css_sanitizer=css_sanitizer,
    )
```

**Comment by Akuli** [comment]
A side note that has nothing to do with typing: Filtering URLs like in your `allowed_iframe_src()` is potentially dangerous. Different URL parsers tend to produce different results in corner cases, and `urlparse()` and your user's web browser do different things, it can be possible to bypass your `netloc` check.

Maybe check with a regex instead? You probably don't want to allow redirect URLs within `youtube.com`, for example, which would cause the iframe to display something completely different than youtube.

**Comment by vin-ai** [comment]
> Are you sure you're meant to be directly calling `.update()` on it in the way that you're doing?

I think so, because I wanted to have extra attrs to html tags like a, img, iframe and *

**Comment by AlexWaygood** [comment]
> > Are you sure you're meant to be directly calling `.update()` on it in the way that you're doing?
> 
> I think so, because I wanted to have extra attrs to html tags like a, img, iframe and *

But the examples in the documentation would indicate that you should be doing something like this -- constructing a new dictionary instead of updating the existing dictionary:

```python
import bleach
from urllib.parse import urlparse

ALLOWED_IFRAME_DOMAINS = ["youtube.com", "facebook.com", "vimeo.com", "dailymotion.com"]


def allowed_iframe_src(tag: str, name: str, value: str) -> bool:
    if name in ("alt", "height", "width", "allowfullscreen"):
        return True

    if name == "src":
        parsed_result = urlparse(value)
        return (
            not parsed_result.netloc
        ) or parsed_result.netloc in ALLOWED_IFRAME_DOMAINS

    return False


ALLOWED_ATTRIBUTES = {
    **bleach.sanitizer.ALLOWED_ATTRIBUTES,
    "a": bleach.sanitizer.ALLOWED_ATTRIBUTES.get("a", []) + ["rel"],
    "img": ["width", "height", "src", "alt"],
    "iframe": allowed_iframe_src,
    "*": ["style", "class"],
    }


@keep_lazy_text
def clean_html(content):
    return bleach.clean(
        content,
        tags=bleach.sanitizer.ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        css_sanitizer=css_sanitizer,
    )
```

Mypy does not emit any errors if you do it like that.

**Comment by AlexWaygood** [comment]
I don't think we'll be making any changes here, so I'm closing this for now.

**Comment by vin-ai** [comment]
My bad I missed the docs explaining how to construct a new dict or update. It is clear to me. Thanks for all your time and pointing out what I was not doing in right way 👍

**Comment by AlexWaygood** [comment]
> My bad I missed the docs explaining how to construct a new dict or update. It is clear to me. Thanks for all your time and pointing out what I was not doing in right way 👍

No worries at all — glad we could help :)
