### ISSUE TITLE
how to type check the xml element class

### ISSUE THREAD

**Issue by ismail-s** [python/typeshed#82]
I have been adding type hints to the xml module [on this branch](https://github.com/ismail-s/typeshed/tree/feature/type_check_xml). Now, the Element class has one mandatory param which shoud be a str or bytes. But at in the [Comment function](https://hg.python.org/cpython/file/tip/Lib/xml/etree/ElementTree.py#l470) the Comment function itself is passed in instead, and then this is [used later on](https://hg.python.org/cpython/file/tip/Lib/xml/etree/ElementTree.py#l959) to identify that an element is a comment. An interesting way of checking this imo, but is there any way of dealing with thisʔ Atm, this will just mean the xml module will fail its own type check.

Also, if this issue should have been raised elsewhere, let me know.

**Comment by gvanrossum** [comment]
Short of using Any, maybe you could use Union[str, bytes,
Callable[..., Element]] ? Or if the typevar is important,
Union[AnyStr, Callable[..., Element]] ? (The '...' is a literal
ellipsis, to indicate the callable's argument list is unconstrained.)

**Comment by ismail-s** [comment]
1. Thanks for mentioning AnyStr, will use that instead everywhere.
1. Apparently the Element class can take strings or bytes, and I am assuming mixing the two would be bad, hence the typevar
1. Using Callable seemed the only way to me too, but I didn't think of the ellipsis. It just means that the type checking isn't perfect. But to be fair, the typing module doesn't try to cover all bases.
