### ISSUE TITLE
Calling `await asyncio.gather(*a)` returns empty tuple in Pyright

### ISSUE THREAD

**Issue by 0xjc** [python/typeshed#8270]
In the following code:

```
import asyncio
from typing import Awaitable, List


async def f(a: List[Awaitable[int]]):
    b = await asyncio.gather(*a)
    reveal_type(b)  # Type of "b" is "tuple[()]"
```

Pyright type checking now assumes that b is empty, leading to potential errors down the line.

Most likely related to this commit: https://github.com/python/typeshed/commit/0740d1c48e48ddd426ac8cb56572ebd12a3652b1

More context from the discussion in the Pyright issue tracker: https://github.com/microsoft/pyright/issues/3685

**Comment by AlexWaygood** [comment]
Thanks (and sorry for the regression). I've filed #8271.

**Comment by vitorrloureiro** [comment]
Is this fixed? I'm still facing this issue in VSCode with Pylance
