### ISSUE TITLE
Recent change to `tuple` constructor breaks subclasses of tuples

### ISSUE THREAD

**Issue by erictraut** [python/typeshed#8275]
A recent change to the `tuple.__new__` method in `builtins.pyi` introduced an overload:
```python
    @overload
    def __new__(cls) -> tuple[()]: ...
```

This overload is problematic for classes that derive from specialized tuples.

```python
class MyTuple(tuple[int, str, str]):
    ...

x = MyTuple()
reveal_type(x) # tuple[()] !!!!
```

Because of this overload, the wrong type is evaluated.

I think this overload should return `Self`, not `tuple[()]`. Admittedly, that doesn't produce the ideal type evaluation for `tuple()`. It produces `tuple[Any, ...]` rather than `tuple[()]`.

**Comment by AlexWaygood** [comment]
> ```python
> class MyTuple(tuple[int, str, str]):
>     ...
> 
> x = MyTuple()
> reveal_type(x) # tuple[()] !!!!
> ```

I feel like maybe a type checker should disallow this snippet. This is what happens at runtime:

```python
>>> class MyTuple(tuple[int, str, str]): ...
...
>>> MyTuple()
()
```

Perhaps type checkers should disallow calls to subclasses of specialised tuples unless `__new__` has been overridden?

**Comment by JelleZijlstra** [comment]
@AlexWaygood the runtime type of `MyTuple()` is in fact `MyTuple`. I don't see why type checkers should disallow that.

This change is from #7454. I already brought up this possible issue, but for whatever reason mypy doesn't infer the wrong type for subclasses in this case. Given that it causes a regression for pyright, I'm fine with reverting it.

**Comment by AlexWaygood** [comment]
> @AlexWaygood the runtime type of `MyTuple()` is in fact `MyTuple`. I don't see why type checkers should disallow that.

The runtime type is `MyTuple`, yes, but it's _not_ a subtype of `tuple[int, str, str]`. My concern is about situations like this:

```python
class MyTuple(tuple[int, str, str]):
    ...

x = MyTuple()  # type checker is happy with this, infers type of x as MyTuple
a, b, c = x  # type checker is happy with this due to x having inferred type of MyTuple, but this fails at runtime.
```

But I'm fine with reverting #7454 for now; I agree that it doesn't bring much benefit.
