### ISSUE TITLE
Asyncio is not importing taskgroups

### ISSUE THREAD

**Issue by jonaslb-bg** [python/typeshed#8276]
`asyncio.__init__` does not import `.taskgroups`, which means that e.g. Pyright gives "unknown import symbol" error for a line such as `from asyncio import TaskGroup`, even though this import works fine (under Python 3.11). 

The stub for `asyncio.taskgroups` is already there and indeed Pyright gives no error for `from asyncio.taskgroups import TaskGroup`. 

So it is only the module top-level import that appears to be missing.

**Comment by srittau** [comment]
Current HEAD has the import since May:

https://github.com/python/typeshed/blob/27db37240a5af17ff2d6aa9c9968fb2f13bd84a9/stdlib/asyncio/__init__.pyi#L23-L25

**Comment by AlexWaygood** [comment]
@jonaslb-bg, do you maybe have the wrong `pythonVersion` specified in your `pyrightconfig.json` file?

**Comment by jonaslb-bg** [comment]
Thanks for your comments. I had not entered `pythonVersion` into `pyrightconfig.json`, and entering worked. I assumed it used the current version when left unspecified - but I guess not?

**Comment by jonaslb-bg** [comment]
In any case this was a case of me being plain wrong about the stubs, so I'll close it I guess.

**Comment by AlexWaygood** [comment]
> Thanks for your comments. I had not entered `pythonVersion` into `pyrightconfig.json`, and entering worked. I assumed it used the current version when left unspecified - but I guess not?

I'm not sure; I'm not an expert on pyright's configuration settings. This may be because py311 is still in beta, it may be some subtlety of pyright's configuration settings that I don't know about, or it may be a bug in pyright. `¯\_(ツ)_/¯`
