### ISSUE TITLE
os.path.exists() and friends should take AnyString, but the Python 2 stub says "unicode"

### ISSUE THREAD

**Issue by markshannon** [python/typeshed#829]
In https://github.com/python/typeshed/blob/master/stdlib/2/os/path.pyi
```python
def exists(path: unicode) -> bool: ...
```
But `os.path.exists()` works fine (at least on 2.7 and linux) with non-ascii byte strings:
```
>>> open(b"\xff", "w").close()
>>> os.path.exists(b"\xff")
True
```

Is this deliberate or merely an oversight?

**Comment by JukkaL** [comment]
Mypy treats `str` as a subtype of `unicode` (details at https://github.com/python/typing/issues/208), and many of the stdlib stubs were originally lifted from mypy and make this assumption. 

We accept PRs that replace some `unicode` types with `Union[str, unicode]` or similar, but I'm not aware of anybody systematically planning to update these in the stubs.

**Comment by JelleZijlstra** [comment]
This has been fixed in master, probably by one of @euresti's PRs.
