### ISSUE TITLE
email.message.EmailMessage.walk() returns Message objects instead of EmailMessage objects

### ISSUE THREAD

**Issue by hoelbezier** [python/typeshed#8290]
The `email.message.EmailMessage.walk()` function yields legacy `email.message.Message` objects, which have fewer methods than `EmailMessage` objects, hence mypy complains when doing, for example, `[part for part in message.walk() if part.is_attachment()]` with `error: "Message" has no attribute "is_attachment"`

The culprit is https://github.com/python/typeshed/blob/master/stdlib/email/message.pyi#L58 which hardcodes `Message` in its return type.

Note that this is only a typing error: in practice the module does return EmailMessage objects so the previous snippet executes totally fine. The current typing also contredicts the documentation: “[The conceptual model provided by an EmailMessage object is that of an ordered dictionary of headers coupled with a payload that represents the RFC 5322 body of the message, which might be a list of sub-EmailMessage objects.](https://docs.python.org/3/library/email.message.html)”

**Comment by srittau** [comment]
In the case of a non-multipart message, `walk()` returns the message itself, in case of multipart messages, it returns all subpart, which theoretically could be plain messages. That said, I'd be fine with changing the return type to `Generator[Self, None, None]`.

**Comment by hoelbezier** [comment]
That would be perfect, thanks. :) Feel free to close the issue once the change is done.
