### ISSUE TITLE
functools.wraps returns function with incorrect signature

### ISSUE THREAD

**Issue by Aran-Fey** [python/typeshed#8317]
Applying `functools.wraps` to a function returns the function unchanged, but it should instead copy the signature of the wrapped function:

```python
def func(x: bool) -> str:
    return str(x)

@wraps(func)
def test(*args, **kwargs):
    return func(*args, **kwargs)

print(inspect.signature(test))  # (x: bool) -> str
reveal_type(test)  # Revealed type is "def (*args: Any, **kwargs: Any) -> Any"
```

**Comment by Hnasar** [comment]
This can be closed -- implemented by https://github.com/python/typeshed/commit/9c4bfd5d11b47677e128452baa8ac7eeb1903a8e

(Waiting for mypy to pick up the updated typeshed stubs)

**Comment by AlexWaygood** [comment]
> This can be closed -- implemented by [9c4bfd5](https://github.com/python/typeshed/commit/9c4bfd5d11b47677e128452baa8ac7eeb1903a8e)
> 
> (Waiting for mypy to pick up the updated typeshed stubs)

mypy reverts that patch as part of every typeshed sync. See, for example, https://github.com/python/mypy/pull/16382. If this is causing issues for you and you need that patch as a mypy user, please file an issue at mypy (feel free to ping me on that issue).

**Comment by AlexWaygood** [comment]
> mypy reverts that patch in its bundled version of typeshed's stubs as part of every typeshed sync. See, for example, [python/mypy#16382](https://github.com/python/mypy/pull/16382).

Oh, I see you already know that :) https://github.com/python/typing/discussions/1501#discussioncomment-7446020

**Comment by srittau** [comment]
This looks to be fixed in typeshed.
