### ISSUE TITLE
Issue with builtins.slice Signature

### ISSUE THREAD

**Issue by froomzy** [python/typeshed#832]
I have been trying mypy out, and I am hitting something I don't understand. I have the following line of code:
```
NZD = Currency(name='New Zealand Dollars', abbreviation='NZD', slice=slice(3, None, None), format='NZ${price:.2f}')
```
When I run mypy over it I get the following error (in python3.5 virtualenv):
```
mypy --strict-optional -p lists
lists\constants.py:13: error: Argument 2 to "slice" has incompatible type None; expected "int"
```
It seems that slice has a type signature of slice(int, int, int), but to get the behavior I want (give me everything in the string after the third character) I need to pass in a None. I think they should be Optional[int]s rather than ints.

Hopefully that makes sense.

**Comment by gvanrossum** [comment]
I think you can just submit a PR to fix this.

I expect that the attributes should also be Optional[int]?

There are also two issues discussing bigger changes to slice, but I think they are somewhat controversial:
- https://github.com/python/mypy/issues/2410
- https://github.com/python/typing/issues/159

**Comment by froomzy** [comment]
Righto. I have not done a pull request before, so time to go learn about that.

**Comment by JelleZijlstra** [comment]
Looks like this can be closed since the PR was merged.

**Comment by gvanrossum** [comment]
Which makes me think, reviewers should be more careful to edit the commit summary, message body, and auto-close text (preferably "fixes #x" or "closes #x" -- the latter if it's not really a fix but e.g. a feature request).
