### ISSUE TITLE
redis-py async pipelines not being awaited is an error

### ISSUE THREAD

**Issue by bentheiii** [python/typeshed#8324]
types-redis incorrectly marks async `Pipeline` commands as coroutines, when in truth they do not need to be awaited to work (and are not implemented as coroutines.

the following snippet
```python
from redis.asyncio import Redis
async def foo(redis: Redis):
  pipeline = redis.pipeline()
  pipeline.get(...)
  pipeline.set(...)
  await pipeline.execute()
```
is functional according to redis-py, but fails `mypy` with the error `error: Value of type "Coroutine[Any, Any, bool]" must be used`

**Comment by srittau** [comment]
This is basically the same issue we have with the non-async `Pipeline` class: It needs to override all redis command methods so that it doesn't inherit them from the base (async) `Redis` class. Any PRs to improve the situation are welcome.

**Comment by bentheiii** [comment]
Hi @srittau, I'd be happy to submit a PR, but I think a solution must be agreed upon beforehand. AFAICT every command in `Pipeline` can return either the pipeline itself or a coroutine to the command result. This leaves with 3 options I can see:

1. All commands return `Pipeline | Coroutine[Any, Any, ActualResultType]` this is technically correct, but it means that neither `pipeline.get(...).set(...).execute()` nor `(await pipeline.get(...)).decode()` will succeed.
2. All commands return `Any`. This will solve our issues but obviously will not catch other errors.
3. wait for `AnyOf` I guess.

**Comment by srittau** [comment]
Just to clarify (I didn't check): `asyncio.Pipeline` can return either a coroutine or itself? How is it decided what is returned? In case we can't model this, we should indeed just return `Any`, unfortunate as that is.

**Comment by bentheiii** [comment]
#8325
