### ISSUE TITLE
dict.update() method accepts dicts, not just **dict

### ISSUE THREAD

**Issue by karolyi** [python/typeshed#8344]
Hi,

```python
a = {}
a.update(dict(b=1))
assert a == {'b': 1}
```

this is valid code. According to typeshed (pyright sent me here), it's not.

Please correct.

**Comment by AlexWaygood** [comment]
I can't reproduce your problem on VSCode or mypy.

What's the specific error message you get, and on which line? What pyright configuration settings do you have enabled? When you say "pyright sent me here" -- did you file an issue over at pyright? Could you post a link to that, if so?

**Comment by AlexWaygood** [comment]
No worries. Glad you found a solution to the problem!

**Comment by karolyi** [comment]
Oh,  I forgot, the declaration/definition is really this:

```python
a: Dict[str, Union[int, list]] = dict(x=[])
a.update(dict(b=1))
assert a == {'b': 1}
```
Without the type definition, typeshed/pyright will show an error as an incompatible type.
