### ISSUE TITLE
Typing of ctypes' pointer types is wrong

### ISSUE THREAD

**Issue by svenpanne** [python/typeshed#8351]
https://docs.python.org/3/library/ctypes.html#pointers explicitly says:

> Calling the pointer type without an argument creates a NULL pointer.

and even has a code example for this:

```python
null_ptr = POINTER(c_int)()
```
But the `pointer` constructor https://github.com/python/typeshed/blob/10bc4b058462c4343a2cca9adfa7b25979c45562/stdlib/ctypes/__init__.pyi#L167 requires  an argument. This should be optional if I understand the code there correctly.

**Comment by AlexWaygood** [comment]
Hum, this was probably my mistake. I changed this in #8074 due to observing this behaviour in the interactive REPL:

```pycon
>>> from ctypes import pointer
>>> pointer()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: _ctypes.pointer() takes exactly one argument (0 given)
```

**Comment by AlexWaygood** [comment]
The entire `ctypes` stub appears to be a lie (`pointer()` is given as a class, but in reality it's a function). Ideally I think we'd fix that, but that might be a breaking change. Not really sure what the best course of action is tbh.

**Comment by srittau** [comment]
If there only was a way to judge the impact of a change. 🤔 But seriously, I would just try the changes and see whether primer explodes.

**Comment by AlexWaygood** [comment]
> If there only was a way to judge the impact of a change. 🤔 But seriously, I would just try the changes and see whether primer explodes.

I'll get on it.
