### ISSUE TITLE
all BeautifulSoup type hints are wrong

### ISSUE THREAD

**Issue by AIGeneratedUsername** [python/typeshed#8356]
## Summary

It is a total chaos. Where I have `BeautifulSoup`, I get `Iterable[PageElement]`. Where I have `Tag`, I get `PageElement`, etc. See the example below.

I have errors from Mypy in every line:
`Item "NavigableString" of "Union[Tag, NavigableString]" has no attribute "find_all"`
`"Iterable[PageElement]" has no attribute "__next__"  [attr-defined]`
`"enumerate" has incompatible type "BeautifulSoup"; expected "Iterable[<nothing>]"`
`Value of type "Union[Tag, NavigableString, None]" is not indexable`
etc.

The only workaround is either `#type: ignore` dozens of lines, or uninstall "types-beautifulsoup4".

## Reproducible code sample
```python
html_doc = """
<html><head><title>The Dormouse's story</title></head>
<body>
<p class="title"><b>The Dormouse's story</b></p>

<p class="story">Once upon a time there were three little sisters; and their names were
<a href="http://example.com/elsie" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/lacie" class="sister" id="link2">Lacie</a> and
<a href="http://example.com/tillie" class="sister" id="link3">Tillie</a>;
and they lived at the bottom of a well.</p>

<p class="story">...</p>
"""
from bs4 import BeautifulSoup
soup = BeautifulSoup(html_doc, 'lxml')
reveal_type(soup)
for el in soup:
    reveal_type(el)
```

## Output

```bash
_local.py:16:13: note: Revealed type is "bs4.BeautifulSoup"
_local.py:17:11: error: "Iterable[PageElement]" has no attribute "__next__"  [attr-defined]
    for el in soup:
              ^
_local.py:18:17: note: Revealed type is "Any"
Found 1 error in 1 file (checked 1 source file)
```

## Expected output
No errors.

## Versions

beautifulsoup4 = "4.11.1"
types-beautifulsoup4 = "4.11.1"

**Comment by JelleZijlstra** [comment]
Seems like the annotation for `Tag.__iter__` is incorrect: it should return an Iterator, not an Iterable.

We make that mistake in a few other places:
```
% git grep 'def __iter__' | grep Iterable
stdlib/_typeshed/wsgi.pyi:        def __iter__(self) -> Iterable[bytes]: ...
stdlib/wsgiref/types.pyi:    def __iter__(self) -> Iterable[bytes]: ...
stdlib/wsgiref/validate.pyi:    def __iter__(self) -> Iterable[bytes]: ...
stubs/beautifulsoup4/bs4/element.pyi:    def __iter__(self) -> Iterable[PageElement]: ...
stubs/python-gflags/gflags.pyi:    def __iter__(self) -> Iterable[str]: ...
```

**Comment by AlexWaygood** [comment]
> We make that mistake in a few other places:

Hmm, seems like something we could probably lint for in flake8-pyi.

**Comment by JelleZijlstra** [comment]
Yes. The most concerning one is in `wsgiref.types`. @srittau could you take a look? We may have to fix this in CPython too.

**Comment by srittau** [comment]
Yikes. This needs fixing indeed. I can prepare a PR tomorrow for CPython and typeshed if no one beats me to it.

**Comment by hauntsaninja** [comment]
Here you go:
https://github.com/python/typeshed/pull/8358
https://github.com/python/cpython/issues/95105
https://github.com/python/cpython/pull/95106

**Comment by hauntsaninja** [comment]
I filed https://github.com/PyCQA/flake8-pyi/issues/247

The code sample in the original issue now passes with latest `types-beautifulsoup4`

**Comment by ChemGuy88** [comment]
For the code block

```python
soup = BeautifulSoup(markup=filters_markup, features="xml")
entry_li = soup.find_all(name="entry")

for entry in entry_li:
    result = entry.find_all(name="category")  # raises alarm
```

I get an alarm on the fifth line from Pylance in VSCode:

```text
Cannot access attribute "find_all" for class "PageElement"
  Attribute "find_all" is unknownPylance[reportAttributeAccessIssue](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportAttributeAccessIssue.md)
Cannot access attribute "find_all" for class "NavigableString"
  Attribute "find_all" is unknownPylance[reportAttributeAccessIssue](https://github.com/microsoft/pylance-release/blob/main/docs/diagnostics/reportAttributeAccessIssue.md)
(method) find_all: Unknown | ((name: _FindMethodName = None, attrs: _StrainableAttributes = {}, recursive: bool = True, string: _StrainableString | None = None, limit: int | None = None, _stacklevel: int = 2, **kwargs: _StrainableAttribute) -> _QueryResults)
```

However, the code runs without problems.

Is this caused by the bug fixed by this issue? Or is this caused by something else?

**Comment by brianschubert** [comment]
@ChemGuy88 FYI beautifulsoup4 ships its own type hints since v4.13.0. The typeshed stubs are obsolete and scheduled to be removed soon. If you're having issues with bs4's current type hints, you'll likely need to report that to bs4 itself.

**Comment by ChemGuy88** [comment]
> [@ChemGuy88](https://github.com/ChemGuy88) FYI beautifulsoup4 ships its own type hints since v4.13.0. The typeshed stubs are obsolete and scheduled to be removed soon. If you're having issues with bs4's current type hints, you'll likely need to report that to bs4 itself.

Thank you, @brianschubert. I'll go ahead and do that.
