### ISSUE TITLE
Incomplete annotations for requests.api

### ISSUE THREAD

**Issue by WouldYouKindly** [python/typeshed#840]
Argument 'params' to requests.api.get is said to take
```
Union[dict[Union[str, unicode,
           Union[str, unicode]],
      Union[str, unicode]]
```

but actually takes more than that. Params are passed to requests.models.PreparedRequest._encode_params, which accepts either a dict, or a sequence of tuples.

As far as I see, keys in dict may be strings, ints of floats and values can be strings, ints, floats or iterables. And in my practice, it's common to pass and integer or list as a value:
```
>>> PreparedRequest._encode_params({1:2, 'all': 42})
'1=2&all=42'
>>> PreparedRequest._encode_params({1:2, 'all': [41,42]})
'1=2&all=41&all=42'
```

So I propose this annotation:
```
Union[
    Dict[Union[str, unicode, int, float], 
           Union[str, unicode, int, float, Iterable]], 
    Union[str, unicode], 
    Tuple[Union[str, unicode, int, float], 
             Union[str, unicode, int, float, Iterable]]]
]
```

I doubt it's complete, but it's better than the current, I think.
Also, the comment at the top says that stub is for Python 3, but it's in python 2 directory and specifies unicode type.

**Comment by ambv** [comment]
Fixed for Python 2, needs a PR for Python 3.

**Comment by sharmaeklavya2** [comment]
`bool` should also be included.

**Comment by gvanrossum** [comment]
@sharmaeklavya2 zcan you give an example og how bool is used with `requests.get()`?

**Comment by sharmaeklavya2** [comment]
`bool` is used something like this:
```python
requests.get(url, params={True: False})
```
This gives this querystring:
```
?True=False
```

I intended to include an example and some more details in my last comment but I forgot to do that, sorry.

**Comment by sharmaeklavya2** [comment]
A list of pairs also works.
```
>>> Request(url='http://localhost', params=[('a', 1), ('b', 2)]).prepare().url
'http://localhost/?a=1&b=2'
>>> Request(url='http://localhost', params=[('b', 2), ('a', 1)]).prepare().url
'http://localhost/?b=2&a=1'
```

**Comment by sharmaeklavya2** [comment]
I looked at the source code of requests (https://github.com/kennethreitz/requests/blob/master/requests/models.py#L82).

According to that, it accepts a mapping or a sequence of 2-tuples and makes a list of 2-tuples and sends that to [`urllib.parse.urlencode`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlencode). This is what `urlencode`'s documentation says:
> Convert a mapping object or a sequence of two-element tuples, which may contain `str` or `bytes` objects, to a percent-encoded ASCII text string.

When I tried it out, I observed that the types are not limited to `str` and `bytes` and anything that can be converted to a string can be used.

**Comment by gvanrossum** [comment]
Maybe it should just use `Any` then? Because *anything* can be converted to
a string. OTOH is that what they document/recommend? Maybe it would catch
errors if the stub were more restrictive?

**Comment by sharmaeklavya2** [comment]
I had tried to find documentation about this but I couldn't find anything apart from http://docs.python-requests.org/en/master/user/quickstart/#passing-parameters-in-urls.
It's not clearly mentioned there what all can be passed in `params`.

Perhaps we can ask maintainers of requests?

**Comment by gvanrossum** [comment]
Be sure to ask what their intention is, not what the code currently allows.

**Comment by sharmaeklavya2** [comment]
I asked them here: kennethreitz/requests#3856

They clarified that `params` is not intended to accept mappings and 2-tuple iterables of non-string items. They have updated their documentation (https://github.com/kennethreitz/requests/pull/3857/files) to make this clear. So I think we should roll back the fix to this issue.

I thought that telling them that I'm doing this for stubs might be helpful for both us and them. But I didn't know that they had already examined PEP 484 and decided that it's not a good fit for requests. So I was told to not bother requests' maintainers again regarding typeshed stubs.

**Comment by gvanrossum** [comment]
Hm, in the case of requests I can see that they don't want to be involved, as requests' true API is really too dynamic for mypy. But they also aren't asking us to remove it. So I think we should attempt to update it according what we think is most useful for typeshed users (especially mypy and PyCharm).

I'm not much of a requests user myself, so I can't help much, but I have one suggestion: perhaps we could unify the Python 2 and 3 versions into a single package (moved into typeshed/third_party/2and3/). We can use `Text` and `bytes` instead of `unicode` and `str`. Another suggestion would be to get rid of the unions for the mappings' keys/values, and instead use more `Any`.

**Comment by sharmaeklavya2** [comment]
Merging the python 2 and 3 versions of requests is a nice idea. We should open a new issue for it so that people can take it up.
