### ISSUE TITLE
pytz accepts duck typed types

### ISSUE THREAD

**Issue by robsdedude** [python/typeshed#8409]
For instance, consider https://github.com/python/typeshed/blob/master/stubs/pytz/pytz/tzinfo.pyi#L5-L10 :

```python
class BaseTzInfo(datetime.tzinfo):
    # ...
    @abstractmethod
    def localize(self, dt: datetime.datetime) -> datetime.datetime: ...
    # ...
```

But in reality, you can pass in any type that behaves like a datetime. You might be wondering if that is relevant at all: it is =) I'm developing a library that implements custom temporal types to add nanosecond precision because Python's native `datetime` library does not (yet) have that.

The interface should probably look something like

```python
_T = TypeVar("_T")

class _timedelta(Protocol):
    # ...

class _datetime(Protocol):
    def replace(self: _T, ...) -> _T: ...
    @overload
    def __sub__(self: _T, other: _timedelda) -> _T: ...
    @overload
    def __sub__(self, other: _datetime) -> _timedelta: ...
    # ...

_T_dt = TypeVar("_T_dt", bound=_datetime)
    
class BaseTzInfo(datetime.tzinfo):
    # ...
    @abstractmethod
    def localize(self, dt: _T_dt) -> _T_dt: ...
    # ...
```

There are quite a lot of blanks to be filled in here but I hope it gets the idea across.

I'm happy to work on a PR if this change is welcome.

**Comment by srittau** [comment]
One of the problems I see is that this applies to nearly every function and method in Python if it doesn't use `isinstance` checks. This would mean that we would need to use protocols everywhere. Unfortunately, I don't think that duck typing and static types aren't the best fit in Python currently.

**Comment by AlexWaygood** [comment]
I agree with @srittau here. I sympathise with your problem, but I'm not keen on duplicating the entire `datetime` interface with a parallel suite of `Protocol`s (that will need to be kept in sync with the `datetime` module as updates are made).

One possibility for your library might be to add stub files that tell some white lies — that pretend that your classes inherit from the classes in the stdlib `datetime`, even if that's not really what happens. Type checkers would then look at the stubs rather than at the runtime implementation, so from their perspective, your classes would be legitimate subclasses of the stdlib `datetime` classes.

**Comment by robsdedude** [comment]
While I accept this was won't fix here are some more thoughts of mine:

> Unfortunately, I don't think that duck typing and static types aren't the best fit in Python currently.

Isn't that exactly what `Protocol`s were introduced for in "[PEP 544 – Protocols: Structural subtyping (static duck typing)](https://peps.python.org/pep-0544/)". The title says it quite explicitly.

> But I'm not keen on duplicating the entire datetime interface with a parallel suite of Protocols

Makes sense. Even though, I'm pretty sure that pytz only relies on a (rather small) subset of methods provided by the different types in the `datetime` module. And it would be in the favor of getting the duck typing right to just require the actually used methods in the Protocols. So an update is not required when `datetime` changes, but when `pytz` changes what methods it uses.

> One possibility for your library might be to add stub files that tell some white lies.

That comes with its own problems as, in fact, my classes are no real sub-types. So methods that actually require real `datetime` types (like Python's builtin `zoneinfo.ZoneInfo.fromutc` et al.).

So I'll probably still go down the route of telling the type checker the inheritance lie and make do with the fact that the checker will not keep users of my lib from stuffing the custom temporal types into Python-provided methods that at runtime will reject them :disappointed: .

**Comment by AlexWaygood** [comment]
Maybe I/we misunderstood this sentence of your original message:

> There are quite a lot of blanks to be filled in here

I took that to mean that there would be substantial duplication of interfaces.

If the truth is closer to this:

> `pytz` only relies on a (rather small) subset of methods provided by the different types in the `datetime` module.

Then I, for one, would be more open to considering a PR :)

**Comment by robsdedude** [comment]
Ok then. Let me have a more thorough look into `pytz` and see what methods it currently uses for each datetime type. :eyes:

**Comment by robsdedude** [comment]
So here is the result of my initial investigation:

(`dt` would be the protocol type. `tzinfo`, `datetime`, and `timedelta` are the actual types from the `datetime` module)

calls to datetime:
 * `dt.replace(tzinfo=tzinfo | None)`
 * `dt.astimezone(tzinfo)` 
 * `dt.tzinfo: tzinfo | None`
 * `dt.__add__(timedelta)`
 * `dt.__sub__(timedelta)`
 * `dt.__eq__(dt)`
 * indirectly through `bisect_right`: `dt.__lt__(datetime)`
   * note: it also works if only `dt.__gt__(datetime)` is implemented...

observations:
 * `pytz.UTC.fromutc(dt)` requires dt to be an actual `datetime` if `dt.tzinfo is not None`
 
 That's surprisingly little, at least in my opinion.

**Comment by srittau** [comment]
> > Unfortunately, I don't think that duck typing and static types aren't the best fit in Python currently.
> 
> Isn't that exactly what `Protocol`s were introduced for in "[PEP 544 – Protocols: Structural subtyping (static duck typing)](https://peps.python.org/pep-0544/)"? The title says it quite explicitly.

Sure, but that doesn't mean that we can't just duplicate the whole hierarchy of concrete classes with protocols. That said, ...

> > But I'm not keen on duplicating the entire datetime interface with a parallel suite of Protocols.
> 
> Makes sense. Even though, I'm pretty sure that `pytz` only relies on a (rather small) subset of methods provided by the different types in the `datetime` module. And it would be in the favor of getting the duck typing right to just require the actually used methods in the Protocols and not all that `datetime` offers. So an update is not required when `datetime` changes, but when `pytz` changes what methods it uses.

... the `datetime` classes could be good candidates for protocols, considering how ubiquitous they are and how often they are mocked. As you point out, we should not copy the whole interface, but only the "typical" interface, possibly only the accessors for date/time parts.

**Comment by AlexWaygood** [comment]
> That's surprisingly little, at least in my opinion.

My opinion: it's not _very_ many, but it's enough to make me think that, to me, it would still feel a little hacky to use structural subtyping here. It doesn't look to me like the `pytz` authors were _designing_ their package to work with ducktyping; it looks more accidental than deliberate. If they change the implementation details of their methods at any time, we might have to rewrite the protocols we were using.

I think I'd still prefer not to go ahead with this, personally -- sorry.
