### ISSUE TITLE
Many stubtest_stdlib failures for `distutils` on 3.11b5

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#8410]
See e.g. https://github.com/python/typeshed/runs/7543946914?check_suite_focus=true

I have no idea what might be causing this, but it means CI is currently red for all new PRs we receive.

**Comment by kkirsche** [comment]
Looking into this.

It looks like recently the cpython team deleted a large volume of distutils related documentation:
https://github.com/python/cpython/pull/95239/files

Looking to continue reviewing and see if I can find modifications to these files that would explain what's going on.

**Comment by AlexWaygood** [comment]
I can't see how anything documentation-related could impact stubtest. It would also have to be changes that happened on the 3.11 branch between 3.11b4 and 3.11b5 (the `main` branch is 3.12).

**Comment by JelleZijlstra** [comment]
I'm not seeing any relevant changes in distutils between b4 and b5; the only change to distutils code is a minor one to a test file.

Maybe GH messed something up in their distribution of 3.11b5?

**Comment by AlexWaygood** [comment]
> Maybe GH messed something up in their distribution of 3.11b5?

Ah! Was the bundled version of `setuptools` updated in 3.11b5? It looks like stubtest might be finding `distutils` as a subpackage of the bundled `setuptools`, instead of finding the stdlib `distutils`. Here's a sample error from the failing CI run:

```
error: distutils.command.bdist_wininst is not present in stub
Stub:
MISSING
Runtime: in file /opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib/python3.11/site-packages/setuptools/_distutils/command/bdist_wininst.py
<module 'distutils.command.bdist_wininst' from '/opt/hostedtoolcache/Python/3.11.0-beta.5/x64/lib...
```

**Comment by JelleZijlstra** [comment]
Bingo:
```
% git diff --stat v3.11.0b4 v3.11.0b5 | grep setuptools 
 .../_bundled/setuptools-58.1.0-py3-none-any.whl    | Bin 816725 -> 0 bytes
 .../_bundled/setuptools-63.2.0-py3-none-any.whl    | Bin 0 -> 1228000 bytes
```

**Comment by AlexWaygood** [comment]
Thoughts on just doing a `distutils.*` allowlist entry for 3.11? The entire directory's going to be removed in 3.12 anyway.

**Comment by JelleZijlstra** [comment]
Yes, I think that makes sense.
