### ISSUE TITLE
Preferring explicit `Incomplete` for unannotated arguments

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#8472]
This came up in https://github.com/python/typeshed/pull/8458

Currently CONTRIBUTING.md states:

> Included functions and methods must list all arguments, but the arguments can be left unannotated. Do not use Any to mark unannotated arguments or return values.

Leaving things unannotated helps distinguish from cases where we actually need `Any`. But we didn't have `Incomplete` when that was written. `Incomplete` accomplishes the same thing and is easier to grep for, e.g. https://github.com/python/typeshed/issues/4641 mentions grepping for incomplete as a good way to find potential areas to contribute.

**Comment by hauntsaninja** [comment]
Oh, interesting. Agreed that we should prioritise type checker results over usability for ourselves.

That said, there's a quick and easy hack that seems to get us best of both worlds:
```
diff --git a/stdlib/_typeshed/__init__.pyi b/stdlib/_typeshed/__init__.pyi
index 89ca9d81..3a4840b1 100644
--- a/stdlib/_typeshed/__init__.pyi
+++ b/stdlib/_typeshed/__init__.pyi
@@ -34,7 +34,7 @@ AnyStr_co = TypeVar("AnyStr_co", str, bytes, covariant=True)  # noqa: Y001
 # isn't possible or a type is already partially known. In cases like these,
 # use Incomplete instead of Any as a marker. For example, use
 # "Incomplete | None" instead of "Any | None".
-Incomplete: TypeAlias = Any
+from ._does_not_exist import Incomplete as Incomplete  # type: ignore
 
 # stable
 class IdentityFunction(Protocol):
```

<img width="617" alt="Screen Shot 2022-08-02 at 1 12 49 PM" src="https://user-images.githubusercontent.com/12621235/182464669-c0d30f2f-7cf7-4b82-890a-6270bab39a33.png">

Alternatively, we could maybe ask Eric to bless `Incomplete`

**Comment by Akuli** [comment]
Mypy has different behaviour for unannotated arguments too, although it's more complicated:
- If anything at all in a function is annotated (some argument or the return type), the function is "typed" and everything unannotated behaves as if it was `Any`.
- If nothing is annotated, arguments behave as if they were `Any` typed, but the function is also marked as being "untyped", and using it at all will generates errors by default if you use `--strict`.

**Comment by srittau** [comment]
Apart from typechecker issues, I have a slight preference for unannotated items:

* I think it's a bit easier to manually spot an unannotated argument or return type than with "just another annotation".
* It doesn't require an import.
* Currently stubgen generates unannotated fields, although this could be changed, of course.

That said, I don't have strong feelings either way.

**Comment by AlexWaygood** [comment]
> Alternatively, we could maybe ask Eric to bless `Incomplete`

Since, as @Akuli points out, we'd probably want mypy to bless `Incomplete` as well, that sounds kinda like you're proposing writing a PEP ;)

**Comment by hauntsaninja** [comment]
Okay, sounds like there's maybe too much going on here to mess with + no one else really seems in favour of explicit `Incomplete`
