### ISSUE TITLE
Type hinting needed for 'psycopg2' and 'psutil' functions

### ISSUE THREAD

**Issue by tareqpi** [python/typeshed#8502]
I am currently working on a project that checks for static typing in its CI workflow. When running `mypy`, errors occur because untyped third-party libraries functions are called in a typed context in the project. Therefore, the addition of the correct type hinting is needed so that `mypy` stops complaining. Below is the mentioned test result.

https://github.com/tareqpi/Nominatim/runs/7705136880?check_suite_focus=true#step:14:12

**Comment by Akuli** [comment]
I recommend adding `disable_error_code = no-untyped-call` to your `mypy.ini`. This tells mypy to not complain when you call untyped functions. Lots of things are still untyped, so limiting yourself to functions that happen to be typed isn't reasonable yet.
