### ISSUE TITLE
Stubtest failures due to 3.10.6

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#8510]
3.10.6 was released a few days ago, and this caused a few stubtest failures on #8507. Unfortunately, GitHub Actions only seems to be using 3.10.6 for the Ubuntu stubtest run; the Windows and MacOS runs are still using 3.10.5. This makes it hard to update our allowlists/stubs.

Should we:

- Temporarily pin to 3.10.5 for all our stubtest runs?
- Leave the CI red for a little bit and hope the Windows and MacOS stubtest runs start using 3.10.6 soon?
- Something else?

**Comment by srittau** [comment]
> Temporarily pin to 3.10.5 for all our stubtest runs?

I would say that's the best option.
