### ISSUE TITLE
`Argument "headers" to "FieldStorage" has incompatible type `

### ISSUE THREAD

**Issue by yellowhat** [python/typeshed#8559]
**Bug Report**

Hi,
consider the following examples:

```python
import http.server
from cgi import FieldStorage
from http import HTTPStatus

class Handler(http.server.SimpleHTTPRequestHandler):
    def do_POST(self) -> None:
        if self.path == "/upload":
            result = self.receive_upload()
    def receive_upload(self) -> tuple[HTTPStatus, str]:
        result = (HTTPStatus.INTERNAL_SERVER_ERROR, "Server error")
        form = FieldStorage(fp=self.rfile, headers=self.headers, environ={"REQUEST_METHOD": "POST"})
        return result
```

I get:

```console
main.py:11: error: Argument "headers" to "FieldStorage" has incompatible type "Message"; expected "Optional[Mapping[str, str]]"
Found 1 error in 1 file (checked 1 source file)
```

**Your Environment**

Run on <https://mypy-play.net/?mypy=latest&python=3.10>

Am I missing something?

Thanks

**Comment by DMRobertson** [comment]
https://github.com/python/cpython/blob/5a094f0255eea1db58fb2cf14c200971e64ec36e/Lib/cgi.py#L401-L403 is pretty explicit that Messages are permitted!

**Comment by yellowhat** [comment]
Sorry, I am not familiar with how `typeshed`is released.
Is the fix going to be included in the next release of `mypy`?

Thanks

**Comment by JelleZijlstra** [comment]
Mypy bundles a copy of typeshed and generally updates it before each release.
