### ISSUE TITLE
`pow` `NoReturn` overload is used by Pyright and Pyre when argument types are not known

### ISSUE THREAD

**Issue by debonte** [python/typeshed#8566]
The first overload of `pow` currently looks like this:

```python
@overload
def pow(base: int, exp: int, mod: Literal[0]) -> NoReturn: ...
```

When the argument types are not known, Pyright and [Pyre](https://pyre-check.org/play?input=def%20RSAcompute(message%2C%20exponent%2C%20pubkey)%3A%0A%20%20%20%20data%20%3D%20pow(message%2C%20exponent%2C%20pubkey)%0A%20%20%20%20reveal_type(data)%0A%20%20%20%20return%20data%0A%0Aprint(%22OK%20start%22)%0Ares%20%3D%20RSAcompute(12%2C%2034%2C%2056)%0Aprint(%22Now%20pylance%20says%20unreachable%22)) use the first overload -- the `NoReturn` overload. 

Here's an example from https://github.com/microsoft/pylance-release/issues/3214:

```python
def RSAcompute(message, exponent, pubkey):
    data = pow(message, exponent, pubkey)
    # The rest of the function is marked as unreachable
    # because Pyright/Pylance see pow's return type as NoReturn
    toto = 42
    return data

res = RSAcompute(12, 34, 56)
print("Similarly this line is considered unreachable")
```

@AlexWaygood, it looks like you added the `NoReturn` overload [here](https://github.com/python/typeshed/pull/6287/files#diff-1580ddf7dc331234b0845ffb953b6f7a5f1e9afa15048ebc0762226a08f194b4R1281). Does it actually help users? I'm wondering if it could be removed, or at least moved down in the overload ordering so Pyright and Pyre would behave better in this situation.

**Comment by JelleZijlstra** [comment]
I think we should remove it. Returning `NoReturn` isn't a good fit for cases where the code throws an error the user probably isn't expecting, because it can easily lead to type checkers silently skipping the code. Ideally we'd be able to use something like TypingError from python/typing#1043. Until we have that, I think it's better to accept that we can't handle cases like this in the stub.

**Comment by AlexWaygood** [comment]
Sure, let's get rid of it and add a TODO comment. Thanks for raising the issue @debonte.
