### ISSUE TITLE
Making unittest type annotations for assertIsNone and assertIsNotNone stricter

### ISSUE THREAD

**Issue by 1kastner** [python/typeshed#8583]
Dear typeshed team,

first of all thanks for all the effort in this project. I am rather new to using Python typhints and I have taken quite some functionality in my IDE for granted. Recently, I tried to check a project of mine project with mypy and got some interesting results. As unittests and working examples were in place, I realized that several of the found issues were caused by not-so-perfect type hinting in the code. In one case, however, I thought that maybe the type hints provided by typeshed could be stricter.

In https://github.com/python/mypy/issues/5088#issuecomment-390518079, it is proposed that in the unittest stubs, `NoReturn` could be used whenever we know that an assert method call will fail. By elaborating the typehints of [assertIsNotNone](https://github.com/python/typeshed/blob/master/stdlib/unittest/case.pyi#L120), unittests could be even statically checked before execution. Obviously, the same is true for its symmetric partner `assertIsNone`.

Would a corresponding pull request be accepted given that it satisfies the quality criteria of this repository?

**Comment by sobolevn** [comment]
I personally think that this is a good idea. For example, we can catch things like:

```python
def init_database() -> None:
   print('db is ready')

class Test(unittest.TestCase):
   def test_init_database(self) -> None:
      self.assertIsNotNone(init_database())
      print('finished')  # will be reported as unreachable by mypy
```

**Comment by 1kastner** [comment]
Exactly! In addition, the unittest testcase method `self.assertIsNone()` will get the equivalent functionality of `assert is None` (and in both cases its negation).

**Comment by 1kastner** [comment]
Then I would give it a shot

**Comment by sobolevn** [comment]
Take a look at https://github.com/python/typeshed/issues/8566 as well for an alternative opinion

**Comment by 1kastner** [comment]
@sobolevn thank you for the link to that issue. As far as I understand, debonte suggests that the overload could be dropped (something not preferable in this case as I will argue shortly) or that it moved down in the overload ordering (for this planned PR, we could choose any ordering). The response of JelleZijlstra is *"Returning NoReturn isn't a good fit for cases where the code throws an error the user probably isn't expecting, because it can easily lead to type checkers silently skipping the code."* I cannot follow this line of argument. How is it possible that code is skipped? Could you provide an example? That would be awesome! For the first part, do I understand correctly that maybe we should not use type checking at all in unittests because we are just looking out for the unexpected to happen, such as that we failed to correctly annotate the types? In that case this raises the question of where to draw the line? Why should we use type annotations at all? Just as the devil's advocate - should we maybe drop the whole folder https://github.com/python/typeshed/tree/master/stdlib/unittest? I do not seriously suggest that, not at all, I just try to understand the part of code being falsely treated by static type checks. 

The anti-pattern discussed in https://github.com/python/mypy/issues/5088 is that we need a double check for one concept we want to test. First, the unittest checks whether it is not None (the intended unittest) and then an assertion statement checks the same (just for mypy to be happy). The assertion statement is supported by mypy for [type narrowing](https://mypy.readthedocs.io/en/stable/type_narrowing.html) and is required to pass the linting while it it [dropped in optimized code](https://docs.python.org/3/reference/simple_stmts.html#the-assert-statement). Thus, dropping the unittest changes the behavior of the code and dropping the assert affects the static type checks. Having both of them leads repeated code like this:

```python
def my_func() -> Optional[str]:
    ...


class MyUnitTest(unittest.TestCase):
    def test_my_func(self):
        result = my_func()
        self.assertIsNotNone(result)
        assert result is not None
        ....
        # continue to work with the string
        ....
```

This is what I would like to avoid.

**Comment by JelleZijlstra** [comment]
> I cannot follow this line of argument. How is it possible that code is skipped? 

Mypy generally doesn't typecheck code it considers unreachable. Here you can see an example: https://mypy-play.net/?mypy=0.971&python=3.10&gist=e5d8fe2c9552e2556d3de0e639349c57 (the type error on the return line isn't caught).

**Comment by AlexWaygood** [comment]
I'm not really sure we should change the signature of `assertIsNone`, either. It's true that we could do something like this, so that a type checker would error if anything except `None` was passed into the function:

```python
class TestCase:
    def assertIsNone(self, obj: None, msg: Any = ...) -> None: ...
```

But I think that might end up being really annoying for users. If you have to do type narrowing to make sure an object is `None` before you pass it in to `TestCase.assertIsNone()`, that sort of defeats the point of `TestCase.assertIsNone()`, surely?

**Comment by 1kastner** [comment]
Thank you for the elaboration! I was assuming that unreachable code was reported by default and thus I did not see that point before.

Regarding type narrowing, well, in some states the variable might be None and in others it should not. Definitely there are programming patterns, e.g. those that work with several state-dependent immutable representations of a concept, that could avoid this type narrowing. However, it might be a bit of over-engineering in my case.

**Comment by 1kastner** [comment]
Then it seems like the behavior of assert statements cannot be imitated by any method, right? Something like "if we have passed this point, we can be sure that this variable is not None." Or in more general terms, some types of a union can be excluded after some methods or functions are invoked. I was also checking on the TypeGuard approach but it seemed to require an if block and was thus not a perfect match for the given situation. And thanks again for your valuable and insightful comments!

**Comment by AlexWaygood** [comment]
> Then it seems like the behavior of assert statements cannot be imitated by any method, right? Something like "if we have passed this point, we can be sure that this variable is not None." Or in more general terms, some types of a union can be excluded after some methods or functions are invoked. I was also checking on the TypeGuard approach but it seemed to require an if block and was thus not a perfect match for the given situation. And thanks again for your valuable and insightful comments!

Yeah, we really need something like https://github.com/python/typing/issues/930 (interestingly, `assertIsNotNone` has already been mentioned in that issue!).

**Comment by 1kastner** [comment]
Thanks for the link! I understand the concerns for my initially proposed quick fix. I guess this issue can be closed for now. Let's hope the discussion you linked to continues to ve fruitful.

**Comment by sobolevn** [comment]
Ok then! Let's wait for `@typing_error` helper. 

@JelleZijlstra do you think that we need a PEP for it? I can totally work on it and announce it as a draft in typing-sig as soon as I have something real to show.

In my opinion this can bring python's type system to a new level!

**Comment by JelleZijlstra** [comment]
Yes, this would need a PEP.
