### ISSUE TITLE
Consider removing "github-pages" environment

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#8591]
It is listed as an active deployment: https://github.com/python/typeshed/deployments
But, it does not look that active to me ;)

It is also listed here:
<img width="319" alt="Снимок экрана 2022-08-22 в 16 21 21" src="https://user-images.githubusercontent.com/4660275/185931243-a3de92d8-d2d1-4f86-8539-283972c17d19.png">

**Comment by JelleZijlstra** [comment]
I have permission to delete this at https://github.com/python/typeshed/settings/environments (IIRC @srittau has this access too) but I'll wait a little bit in case somebody knows what it's for.

**Comment by JelleZijlstra** [comment]
Thanks, that explains what happened. I deleted it now.

**Comment by srittau** [comment]
Thanks for finding this!
