### ISSUE TITLE
type annotation for str.translate incomplete

### ISSUE THREAD

**Issue by GrozniyToaster** [python/typeshed#8628]
After reading the docs about [str.translate](https://docs.python.org/3/library/stdtypes.html#str.translate), I wrote a class with `__getitem__`:
```python
class SeparatorTranslator:
    separators_whitelist: Final = {' ', '\n', '\t'}

    def __getitem__(self, char_order_index: int) -> str:
        char = chr(char_order_index)
        if char.isspace() and char not in self.separators_whitelist:
            return ' '
        else:
            return char
```
When I check code like `'asd asd \v\t asd'.translate(separator_translator)` by mypy got an error:

```console
 error: Argument 1 to "translate" of "str" has incompatible type "SeparatorTranslator"; expected "Union[Mapping[int, Union[int, str, None]], Sequence[Union[int, str, None]]]"  [arg-type]
```
Seems `__table` argument  must be `SupportsGetItem[int, int | str | None]` 

Can I fix it?

**Comment by srittau** [comment]
I haven't looked at this, but generally all PRs to fix typing problems are welcome!
