### ISSUE TITLE
`ssl.SSLContext` type hint shouldn't have an `__init__` method, only `__new__`

### ISSUE THREAD

**Issue by tifv** [python/typeshed#8632]
stdlib/ssl.pyi currently contains a definition for `ssl.SSLContext.__init__()` with the `protocol`  argument. But the actual type in stdlib does not define `__init__()` at all, only `__new__()`.

On attempting to subclass `SSLContext` while overriding only `__new__()` method (with another set of arguments) type checker will incorrectly show an error (incompatibility between constructors). On the other hand, when overriding both `__new__()` and `__init__()` and calling `super().__init__(protocol)`, type checker will not complain, though the code will in fact produce a `TypeError: object.__init__() takes exactly one argument (the instance to initialize)` at runtime.

Would it be correct to remove `__init__` definition from `SSLContext` class, leaving only `__new__`? I have edited the local typeshed copy that pylance uses on my computer and it seems to work (removes the error in the first case and shows an error in the second).

**Comment by sobolevn** [comment]
Looking at the source code: https://github.com/python/cpython/blob/0ace820bec8892d621a4aadc1feb6c56e25560bf/Lib/ssl.py#L422-L439

Looks like `SSLContext` does not have `__init__`:

```
Python 3.12.0a0 (heads/main:f235178bec, Aug 13 2022, 12:11:52) [Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from ssl import SSLContext
>>> SSLContext.__init__
<slot wrapper '__init__' of 'object' objects>
```

And it never had one: https://github.com/python/cpython/blob/3.7/Lib/ssl.py#L390-L400
So, I guess removing it is the right thing!
