### ISSUE TITLE
migrate some stuffs in `ctypes/__init__.pyi` into `_ctypes.pyi`, but circular import occurs

### ISSUE THREAD

**Issue by junkmd** [python/typeshed#8633]
When we submitted PR that adds the `stdlib/_ctypes.pyi`(#8582), imports some stuffs from `ctypes`.

But [the implementation imports some stuffs from `_ctypes` to `ctypes`](https://github.com/python/cpython/blob/0ace820bec8892d621a4aadc1feb6c56e25560bf/Lib/ctypes/__init__.py#L8-L14).
- also related to https://github.com/python/typeshed/issues/8571#issuecomment-1221316973

However, trying to write type stubs as close as possible to the implementation would result in circular imports if we just move definitions around.
- For example, `CDLL` in args of `_CData` methods.
  - In implementation... 
    - `CDLLL` is defined in `ctypes`
    - `_CData`(base class of `_SimpleCData`) is defined in `_ctypes`.
- Some PRs, such as #5350, were merged as "should be fine in `pyi` files" even if they are circular imports.

Any opinions would be appreciated.

**Comment by hauntsaninja** [comment]
You don't really need to worry about circular imports, since stub files are never imported by Python. All type checkers know how to resolve circular imports when resolving references. That said, in this case you could probably move the fake definitions `_CArgObject, _PointerLike` to `_ctypes` and import them in `ctypes`.

**Comment by junkmd** [comment]
When we tried to make the change, we found that the test using [`pytype`](https://github.com/google/pytype) running in CI failed.
Please see #8643.

I will work on adding TODO comments to the stuffs originally defined in `_ctypes` until `pytype` is fixed or better workarounds are found.

**Comment by junkmd** [comment]
I submitted issue to `pytype` google/pytype#1281

**Comment by junkmd** [comment]
The `pytype` problem causes by [its own `_ctypes` stub](https://github.com/google/pytype/blob/ea1bc6734716e30afc4dabff20c059d3807f9965/pytype/stubs/stdlib/_ctypes.pytd).

This will be fixed ["in a few weeks"](https://github.com/google/pytype/issues/1281#issuecomment-1231093224).

**Comment by junkmd** [comment]
## List of the stuffs in `ctypes/__init__.pyi` those what originally defined in `_ctypes`
- `ArgumentError`
- `Array`
- `FormatError`
- `LoadLibrary`
- `POINTER`
- `RTLD_GLOBAL`(TODO marked)
- `RTLD_LOCAL`(TODO marked)
- `Structure`
- `Union`
- `_Pointer`
- `_SimpleCData`
  - `_CData`(hidden base class)
- `addressof`
- `alignment`
- `byref`
- `get_errno`
- `get_last_error`
- `pointer`
- `resize`
- `set_errno`
- `set_last_error`
- `sizeof`

**Comment by rchen152** [comment]
If you update to pytype 2022.08.30, you should be able to import `RTLD_GLOBAL` and `RTLD_LOCAL` from `_ctypes` now. (Just to clarify, what will happen "in a few weeks" is that I'll delete pytype's `_ctypes` stub so that it no longer has to be kept in sync with typeshed's.)

**Comment by junkmd** [comment]
Currently, `RTLD_GLOBAL` and `RTLD_LOCAL` are imported from `_ctypes.pyi`(#8656).

**Comment by AlexWaygood** [comment]
Yes, the pytype update did the trick — thanks v much @rchen152!

**Comment by AlexWaygood** [comment]
I just updated typeshed's pinned version of pytype to 2023.4.27 in #10111. pytype v2023.4.27 includes https://github.com/google/pytype/commit/2e2088fcae3767802fe60f419499090db59f6c4f, which removes pytype's copy of `stdlib/_ctypes.pyi`. This means we can now move the rest of the definitions that should be in `_ctypes.pyi` (but are currently in `ctypes/__init__.pyi`) over to `_ctypes.pyi`.

**Comment by junkmd** [comment]
#10118, #10125, #10128, #10130, #10133 and #10137 have been merged and the definition movings are completed.

The `CFuncPtr` and the `_FuncPointer` will be addressed within the scope of #8968 and #10132.
