### ISSUE TITLE
Missing method `TestLoader._match_path` from `unittest.loader.pyi`

### ISSUE THREAD

**Issue by priandey** [python/typeshed#8664]
The `unittest.loader.TestLoader._match_path` method and other private methods of `TestLoader` are missing from [the unittest.loader stubs](https://github.com/python/typeshed/blob/master/stdlib/unittest/loader.pyi#L14-L25).

While most of the missing private methods are not meant to be overriden, `_match_path` specify in a comment that it might be overidden.

``` python
def _match_path(self, path, full_path, pattern):
  # override this method to use alternative matching strategy
  return fnmatch(path, pattern)
```
When doing so, and calling `super()._match_path` in the child class, mypy will raise a false positive typing error.

It feels that this method should be reflected in the stub.

**Comment by srittau** [comment]
We accept PRs for type hints for private fields when required by a user, so PR welcome for `_match_path`! But I'm going to close the issue as untyped private fields are not considered "incomplete" by typeshed.
