### ISSUE TITLE
flake8 Y022 conflicts with CONTRIBUTING.md doc for arbitrary-length tuples

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#8667]
> use built-in generics (list, dict, tuple, set), instead of importing them from typing, except in type aliases, in base classes, and for arbitrary length tuples (Tuple[int, ...]);

Is the documentation correct? If so, should `Y022` be disabled? Or maybe the doc can mention to ignore this specific error with a `# noqa: Y022` comment when it is relevant to do so.

**Comment by JelleZijlstra** [comment]
I think this is out of date; mypy used to have more bugs supporting PEP 585 syntax but those have mostly been fixed now.
