### ISSUE TITLE
Type signature for Decimal is incomplete on python 2

### ISSUE THREAD

**Issue by lucaswiman** [python/typeshed#868]
The [stub for `decimal.Decimal.__init__` in python 2](https://github.com/python/typeshed/blob/c8435f43158ddf8ec4335a2a2877fcddc0a76c1b/stdlib/2/decimal.pyi#L57-L58) is incomplete:
```python
class Decimal(SupportsAbs[Decimal], SupportsFloat, SupportsInt):
    def __init__(cls, value: Union[_Decimal, float, str,
                                   Tuple[int, Sequence[int], int]] = ...,
                 context: Context = ...) -> None: ...
```

`decimal.Decimal` can also accept `unicode` strings as input. This leads to spurious errors in `mypy --py2`:

```sh
$ cat mydecimal.py
from __future__ import unicode_literals
import decimal

print(decimal.Decimal('1.0'))

$ python2.7 mydecimal.py 
1.0
$ python3.6 mydecimal.py 
1.0
$ mypy mydecimal.py 
$ mypy --py2 mydecimal.py 
mydecimal.py:4: error: Argument 1 to "Decimal" has incompatible type "unicode"; expected "Union[Union[Decimal, int], float, str, Tuple[int, Sequence[int], int]]"
```

**Comment by lucaswiman** [comment]
If you're amenable to changing the type signature, I'd be happy to submit a PR!

**Comment by ambv** [comment]
Go for it!

**Comment by lucaswiman** [comment]
Looks like `datetime.datetime.strptime` and `datetime.datetime.strftime` have the same issue (they accept `unicode` fine, but are annotated as only accepting `str`). I'll address those in the PR as well.
