### ISSUE TITLE
types for rdkit.Chem

### ISSUE THREAD

**Issue by swamidass** [python/typeshed#8697]
I've attempted to created the base types for rdkit.Chem. The initial generation works great:

`python scripts/create_baseline_stubs.py rdkit` 

However, testing reveals a problem:

`> mypy stubs/rdkit 

stubs/rdkit/rdkit/Chem/MolStandardize/rdMolStandardize.pyi:260: error: invalid syntax
`
This traces back to this class,

`

class TautomerEnumeratorResult(Boost.Python.instance):
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    @classmethod
    def __call__(cls, (anonymousnamespace)) -> Any: ...
    @classmethod
    def __getitem__(cls, (anonymousnamespace), int) -> Any: ...
    @classmethod
    def __iter__(cls, boost) -> Any: ...
    @classmethod
    def __len__(cls, (anonymousnamespace)) -> Any: ...
    @classmethod
    def __reduce__(cls) -> Any: ...
    @property
    def modifiedAtoms(self) -> Any: ...
    @property
    def modifiedBonds(self) -> Any: ...
    @property
    def smiles(self) -> Any: ...
    @property
    def smilesTautomerMap(self) -> Any: ...
    @property
    def status(self) -> Any: ...
    @property
    def tautomers(self) -> Any: ...
`
The line flagged is the first "anonymousnamespace" here. What is the correct fix for this error?

**Comment by Akuli** [comment]
Please make a pull request of the broken stubs, so it's easier to discuss and fix them :)
