### ISSUE TITLE
types-pyOpenSSL has an obsolete dependency on types-cryptography

### ISSUE THREAD

**Issue by woodruffw** [python/typeshed#8699]
First of all, thanks for maintaining all of these type hints! They've saved me from many bugs.

I noticed that `types-pyOpenSSL` depends on `types-cryptography`, despite `types-cryptography` being marked as obsolete (due to the upstream repository maintaining its own type stubs).

This causes false positives when typechecking a codebase that uses both `pyOpenSSL` and `cryptography`, as checking the former pulls in `types-cryptography`, which then conflicts with the correct baked-in types.

I think the fix here is to just remove the `types-cryptography` dependency, since it should no longer be strictly necessary. If that sounds alright, I'm happy to do a quick PR to do that.

**Comment by srittau** [comment]
Due to limitations with our build and test system, type packages can't depend on non-type packages at the moment. This is tracked in #5768 and #5618. I'm closing this as a duplicate here as we will update all dependencies when able to do so.

**Comment by woodruffw** [comment]
Thanks for the explanation, and for de-duping. I'll follow those issues.
