### ISSUE TITLE
Missing stub for "shelve"

### ISSUE THREAD

**Issue by lbolla** [python/typeshed#87]
There does not seem to be stubs for `shelve` (https://docs.python.org/2/library/shelve.html).

**Comment by gvanrossum** [comment]
Indeed. Would you like to help by contributing some? You may be able to run mypy's stub generator. Or try to experiment with this 3rd party stub generator: https://github.com/edreamleo/make-stub-files

**Comment by gvanrossum** [comment]
Fixed by #92
