### ISSUE TITLE
classmethod and staticmethod _only_ work as decorators

### ISSUE THREAD

**Issue by lucaswiman** [python/typeshed#870]
Refs #318 and #609. The stubs of `classmethod` and `staticmethod` do not correctly reflect their behavior: they can be passed arguments, and are callable. Properties appear to work correctly AFAICT.

## What's broken?

```sh
$ cat classdecorators.py 
foo = lambda: 'foo'
bar = lambda cls: 'bar'
baz = lambda self: 'baz'


class MyClass(object):
    foo = staticmethod(foo)
    bar = classmethod(bar)
    baz = property(baz)

print(MyClass().foo())
print(MyClass().bar())
print(MyClass().baz)
$ python3.6 classdecorators.py 
foo
bar
baz
$ mypy classdecorators.py 
classdecorators.py: note: In class "MyClass":
classdecorators.py:7: error: Too many arguments for "staticmethod"
classdecorators.py:8: error: Too many arguments for "classmethod"
classdecorators.py: note: At top level:
classdecorators.py:11: error: "staticmethod" not callable
classdecorators.py:12: error: "classmethod" not callable
```

That program should typecheck successfully, but fails.  I'll try to submit a PR for this in the next few days if time allows.

**Comment by lucaswiman** [comment]
As a side note, currently the test suite seems to not be set up to add test cases like the one in my issue description above. Would you be opposed to added example files which should or should not type-check and having them run as part of `runtests.sh`?

**Comment by gvanrossum** [comment]
Fixing this may be harder than you think. Regarding the addition of tests,
have you found the test suites in test-data/unit/?

**Comment by lucaswiman** [comment]
> Regarding the addition of tests, have you found the test suites in test-data/unit/?

Hmm, I assume you're referring to https://github.com/python/mypy/tree/master/test-data/unit ? That requires two pull requests to add a test to `typeshed`, though I suppose that's not too bad. Conceptually it's exercising the typeshed data on mypy's code, so there's not a "correct" answer to which repository it should live in. I'll switch to testing `typeshed` changes directly in the git submodule in `mypy`. Thanks!

**Comment by gvanrossum** [comment]
Ah, yes. I failed to notice that you're proposing to fix this purely by
changing typeshed. If that works, great, you cna ignore everything I said
and we won't need tests just a review -- that's how we currently live. (The
manual test is good though.)

**Comment by lucaswiman** [comment]
> Fixing this may be harder than you think.

It seems to be relatively straightforward to get my example from the description to typecheck:
```diff
-class staticmethod: pass   # Special, only valid as a decorator.
-class classmethod: pass  # Special, only valid as a decorator.
+class staticmethod:
+    def __init__(self, method: Callable) -> None: ...
+    def __call__(self, *args, **kwargs) -> Any: ...
+class classmethod:
+    def __init__(self, method: Callable) -> None: ...
+    def __call__(self, *args) -> Any: ...
```

This has some downsides:
- `staticmethod` objects do not actually have a `__call__` method.
- It doesn't retain type information when called directly (though mypy just failed completely previously):
```python
from typing import Callable

weird_staticmethod = lambda: 'foo'  # type: Callable[[], str]


class MyClass(object):
    weird_staticmethod = staticmethod(weird_staticmethod)

    @staticmethod
    def regular_staticmethod() -> str:
        return 'regular1'

# Both of the following should fail to type check successfully.
val1  = MyClass.weird_staticmethod()  # type: int

# But only this one does fail.
val2 = MyClass.regular_staticmethod()  # type: int
```

Is that change acceptable? If not, it's easier (though ugly) to just do:
```python
class Foo(object):
    static = cast(Callable, staticmethod(meth))  # type: ignore
```
rather than go into the internals of `mypy`. (This idiom is only used once in an innocuous-but-hard-to-remove place in the codebase I'm trying to add mypy to.)

**Comment by CraftSpider** [comment]
Not sure when, but at some point the definitions were changed. Current output I got is
```
> mypy .\classdecorators.py
Success: no issues found in 1 source file
```
I think the 'only valid as decorator' comment can be removed, also, as it's no longer true
