### ISSUE TITLE
Wrong type in `jsonschema._utils.format_as_index`

### ISSUE THREAD

**Issue by rudolfbyker** [python/typeshed#8707]
https://github.com/python/typeshed/blob/ff3c3b8373c6f67c2b1f79bf543e1f4e7f655e95/stubs/jsonschema/jsonschema/_utils.pyi#L18

I think this should be 

```py
def format_as_index(indices: Iterable[Any]) -> str: ...
```

Given that the implementation is:

```py
def format_as_index(indices):
    """
    Construct a single string containing indexing operations for the indices.

    For example, [1, 2, "foo"] -> [1][2]["foo"]

    Arguments:

        indices (sequence):

            The indices to format.
    """

    if not indices:
        return ""
    return "[%s]" % "][".join(repr(index) for index in indices)
```

**Comment by srittau** [comment]
Where do you see that definition?

git HEAD as well as the current version from PyPI has the extra `container` argument we have in the stubs:

https://github.com/python-jsonschema/jsonschema/blob/05b18609db84954d7309d69d7628cd882ba90dc3/jsonschema/_utils.py#L65

That said, the `indices` argument is indeed iterable, although I would either use `int | str` for the `Iterable` argument.

**Comment by rudolfbyker** [comment]
> Where do you see that definition?

Hmm, in version 3.2.0. This seems to have changed here https://github.com/python-jsonschema/jsonschema/commit/b88852007bd365b40be64f1c9fe27a56dbc683ba . Sorry :)

> That said, the indices argument is indeed iterable, although I would either use int | str for the Iterable argument.

OK, but if it should only be `int | str`, why would the implementation use `repr()`?

**Comment by rudolfbyker** [comment]
Happy to close this, if you are.

**Comment by srittau** [comment]
> OK, but if it should only be `int | str`, why would the implementation use `repr()`?

Technically, it could be `object` as `repr()` works on any object. But if I understand the function correctly, it's supposed to print an indexed string, where everything but a `str` or `int` would return an invalid result.

We're happy to accept a PR that annotates the `indices` argument. But I'm closing it as we're usually not keeping issues open for this. Thanks!
