### ISSUE TITLE
Constants from email.utils are missing

### ISSUE THREAD

**Issue by septatrix** [python/typeshed#8710]
This includes e.g. `COMMASPACE`

**Comment by AlexWaygood** [comment]
These appear to be undocumented, and are omitted from `__all__` -- we generally don't add things like that to the stub unless people ask for them. But if you have a valid use case for them, we'd probably accept a PR adding them!

**Comment by septatrix** [comment]
I have just started using the module and am not sure how useful these are generally when creating messages but I noticed it after my IDE showed me a warning while I was trying some [code I found on StackOverflow](https://stackoverflow.com/a/3363254/7583539) about emails with attachments. If the RFC is strict regarding the formatting of the `"To"` field then it might make sense to expose this - otherwise probably not.

**Comment by srittau** [comment]
We are usually not keeping issues about undocumented field open, but please feel free to send PRs for all constants that you believe should be supported by typeshed!
