### ISSUE TITLE
Update *func* parameter annotation for sqlite3's create_function().

### ISSUE THREAD

**Issue by shawnbrown** [python/typeshed#8727]
The *func* parameter type for sqlite3's `create_function()` is defined as `callback | None` (see [docs](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.create_function)) but the typeshed stub does not include `None` as a valid type. This is a long-undocumented feature that was only recently added to the docs (see related issue python/cpython#95235 and commit python/cpython@5012bed).

In **stdlib/sqlite3/dbapi2.pyi**, the annotation for this parameter currently reads ``func: Callable[..., _SqliteData]`` ([link](https://github.com/python/typeshed/blob/1ec57121e3570cf8d10c00dc418e043a35996b2e/stdlib/sqlite3/dbapi2.pyi#L319-L324)) but it should be changed to ``func: Callable[..., _SqliteData] | None``:

```python
if sys.version_info >= (3, 8):
    def create_function(
        self, name: str, narg: int, func: Callable[..., _SqliteData] | None, *, deterministic: bool = ...
    ) -> None: ...
else:
    def create_function(
        self, name: str, num_params: int, func: Callable[..., _SqliteData] | None
    ) -> None: ...
```

**Comment by srittau** [comment]
Fixed in #8728.
