### ISSUE TITLE
`stubtest_stdlib` failing on macos for Python 3.11

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#8739]
`stubtest_stdlib.py` seems to be failing on `master` for MacOS on Python 3.11:

- Attempt 1 here: https://github.com/python/typeshed/actions/runs/3060435467/attempts/1
- Attempt 2 here: https://github.com/python/typeshed/actions/runs/3060435467/attempts/2
- Attempt 3 here: https://github.com/python/typeshed/actions/runs/3060435467

<details>
<summary>The failures are related to the `dbm`, `locale`, `os` and `posix` modules:</summary>

```
error: dbm.gnu failed to import, ModuleNotFoundError: No module named '_gdbm'
Stub: at line 1
MypyFile:1(
  stdlib/dbm/gnu.pyi
  IgnoredLines(38, 39))
Runtime:
MISSING

error: locale.bind_textdomain_codeset is not present at runtime
Stub: at line 141
def (builtins.str, Union[builtins.str, None]) -> Union[builtins.str, None]
Runtime:
MISSING

error: locale.bindtextdomain is not present at runtime
Stub: at line 140
def (builtins.str, Union[Union[builtins.str, os.PathLike[builtins.str]], None]) -> builtins.str
Runtime:
MISSING

error: locale.dcgettext is not present at runtime
Stub: at line [13](https://github.com/python/typeshed/actions/runs/3060435467/jobs/4939171652#step:6:14)8
def (Union[builtins.str, None], builtins.str, builtins.int) -> builtins.str
Runtime:
MISSING

error: locale.dgettext is not present at runtime
Stub: at line 137
def (Union[builtins.str, None], builtins.str) -> builtins.str
Runtime:
MISSING

error: locale.gettext is not present at runtime
Stub: at line 136
def (builtins.str) -> builtins.str
Runtime:
MISSING

error: locale.textdomain is not present at runtime
Stub: at line 139
def (Union[builtins.str, None]) -> builtins.str
Runtime:
MISSING

error: os.preadv is not present in stub
Stub:
MISSING
Runtime:
<built-in function preadv>

error: os.pwritev is not present in stub
Stub:
MISSING
Runtime:
<built-in function pwritev>

error: posix.preadv is not present in stub
Stub:
MISSING
Runtime:
<built-in function preadv>

error: posix.pwritev is not present in stub
Stub:
MISSING
Runtime:
<built-in function pwritev>

Found 11 errors (checked 484 modules)

```

</details>

It's a little bizarre, as GitHub Actions seems to be using 3.11.0-rc.2 on MacOS fairly consistently, and previous runs on MacOS using that Python version appear to have passed just fine:

- https://github.com/python/typeshed/actions/runs/3059672095/jobs/4937321524
- https://github.com/python/typeshed/actions/runs/3057862083/jobs/4933452495

**Comment by JelleZijlstra** [comment]
It's probably some changes to OS configuration. All the functions it complains about are conditionally defined, e.g. the locale ones depend on libintl being present: https://github.com/python/cpython/blob/e37ac5fbb6de593521cf218aa05bc58a45c5a7c9/Modules/_localemodule.c#L804

**Comment by AlexWaygood** [comment]
Shall we just allowlist for now...? These functions are evidently present _sometimes_ :(

**Comment by hauntsaninja** [comment]
In the spirit of minimising false positives, we should add preadv and pwritev and then use the allowlist trick of `(entry)?` to have these be allowlisted without complaints about unused allowlist entries
