### ISSUE TITLE
Add stubs for Scrapy

### ISSUE THREAD

**Issue by xlurio** [python/typeshed#8759]
Apparently there are no type stubs for [Scrapy](https://pypi.org/project/Scrapy/) and I always have to write it on my own. Can we start to build one?

**Comment by AlexWaygood** [comment]
Hi! We're unlikely to add stubs for Scrapy ourselves, but we'd probably accept stubs for Scrapy if you'd like to submit a PR! There's instructions in `CONTRIBUTING.md` for how to go about doing that :)

**Comment by xlurio** [comment]
> 

Yeah, with "we" I actually meant "me" hahah. I just wanted to create a issue before so to avoid problems.
Thank you for the answer! I'll make a pull request soon enough!

**Comment by srittau** [comment]
I'm closing this issue as per our policy about stub requests, but new stub contributions are very welcome!

**Comment by afeld** [comment]
Issue around adding type hints to Scrapy: https://github.com/scrapy/scrapy/issues/4041

**Comment by AlexanderHOtt** [comment]
Is anyone work on this yet? If not, I think I could start.

**Comment by AlexWaygood** [comment]
> Is anyone work on this yet?

Not that I know of. @xlurio?

**Comment by xlurio** [comment]
> > Is anyone work on this yet?
> 
> Not that I know of. @xlurio?

I [am](https://github.com/xlurio/typeshed), but still at 5%.

**Comment by AlexanderHOtt** [comment]
@xlurio I'd love to help, should I make PRs to your forked repo?

**Comment by xlurio** [comment]
> @xlurio I'd love to help, should I make PRs to your forked repo?

Yes, please!

**Comment by guyarad** [comment]
@xlurio @AlexanderHott hey guys, was it abandoned?

**Comment by xlurio** [comment]
yeah... I didn't had time anymore to work on it

**Comment by AlexanderHott** [comment]
It was a lot more work than I expected when I look into it. You would have to type the underlying parsing libraries that use xpath and css selectors, which I didn't want to get into. I don't have a use for scrapy right now, so I'm not working on it.

If you wanted to give it a shot, you should probably start with the publicly exposed dependencies that scrapy uses as return types and parameter types. As far as I rememeber, it uses `parsel` https://github.com/scrapy/scrapy/blob/master/scrapy/selector/unified.py#L7

**Comment by Tuhin-thinks** [comment]
Just wondering if anyone have yet contributed towards Scrapy types or anyone working on it currently?
