### ISSUE TITLE
Remove emoji stubs (not before May 2023)

### ISSUE THREAD

**Issue by kkirsche** [python/typeshed#8760]
With https://github.com/carpedm20/emoji/pull/166 merged using the stubs previously contributed to typeshed, the ~~latest release now~~ next release should include type hints. Seems 2.1.0 was tagged directly before type hints being merged.

**Comment by AlexWaygood** [comment]
As per our [policy](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#third-party-library-removal-policy), we'll want to wait until the library has shipped with a `py.typed` file for at least six months before removing the stubs from typeshed, but this is great to hear! :)

**Comment by kkirsche** [comment]
Emoji 2.1.0 was released on September 17, 2022. 

https://pypi.org/project/emoji/2.1.0/

When in front of a computer, I'll confirm that it has the py.typed marker. If so, this should give us a date for when this should be removed. 

I'll plan to file a separate issue for automated `py.typed` detection to gauge interest in this type of automation / integration.

**Comment by AlexWaygood** [comment]
> I'll plan to file a separate issue for automated `py.typed` detection to gauge interest in this type of automation / integration.

Stubsabot already does that for us. If there's already been an `emoji` release that has a `py.typed` file, that indicates that there's a bug in stubsabot.

**Comment by hauntsaninja** [comment]
Probably a bug in emoji packaging

**Comment by Avasam** [comment]
https://github.com/carpedm20/emoji/pull/239

**Comment by AlexWaygood** [comment]
We now have a release with a `py.typed` file!

- #9051
