### ISSUE TITLE
How to use SQLAlchemy type stubs

### ISSUE THREAD

**Issue by kasium** [python/typeshed#8763]
Hi guys,

I have the following question: In a project of mine I use SQLAlchemy with a declarative Base, which means for proper typing I use SQLAlchemy's mypy plugin and therefore [sqlalchemy2-stubs](https://github.com/sqlalchemy/sqlalchemy2-stubs). Now, I use also flask-sqlachemy and would like to annotate them here with SQLAlchemy hints (these are still missing in the stub).

1. Why do we have types-sqlalcehmy if sqlalchemy2-stubs exists (as far as I know sqlalchemy2-stubs are really just pyi files)?
2. If I use sqlalchemy2-stubs in my project and types-flask-sqlalchemy bases on types-sqlalchemy it will lead to a clash of typing stubs, right?

Thanks a lot for clarifying this

**Comment by srittau** [comment]
The stubs here don't require a plugin and work in all type checkers. I actually plan to improve these stubs further (from my own stubs), but didn't find the time yet.

**Comment by kasium** [comment]
Thanks for info. As far as I can feel sqlalchemy 2-stubs are also just stub files and don't require a plugin, don't they? Would it make sense to combine the efforts?

Do you know what happens if two stubs for the same project are installed?

**Comment by srittau** [comment]
As SQLAlchemy 2 will be type annotated, I don't think that too much effort should be put into the existing type stubs.

**Comment by kasium** [comment]
okay, thanks :-)
