### ISSUE TITLE
Stubsabot isn't updating open stubsabot PRs

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#8778]
If I understand correctly, stubsabot has logic that _should_ mean that it auto-updates PRs (providing no manual changes have been made to the PR branch by maintainers).

That part of the script doesn't seem to be working correctly. #8490 was filed by stubsabot on August 5th, to bump `types-stripe` from `3.5.*` to `4.0.*`. But since then, stripe `4.1` was released on August 19th. Since no maintainers have pushed to that PR branch, I think stubsabot _should_ have force-pushed to that branch so that the PR proposes updating to `4.1.*` instead of `4.0.*` -- but it hasn't.

https://github.com/python/typeshed/issues/8778#tasklist-block-e07bdbeb-93d3-4b63-bbcc-ba29a36d73bc

**Comment by hauntsaninja** [comment]
Okay, I think https://github.com/python/typeshed/pull/8851 fixed this. Although interestingly it shows up as @JelleZijlstra force pushing. I also think that updating might be annoying with the change to daily. I still kind of believe what I said here: https://github.com/python/typeshed/pull/8813#issue-1391886154

**Comment by AlexWaygood** [comment]
> I also think that updating might be annoying with the change to daily.

Yeah, I now see what you mean. I think #8854 might make it better.
