### ISSUE TITLE
`typing` does not export `WriteableBuffer`

### ISSUE THREAD

**Issue by rrthomas** [python/typeshed#8795]
**Bug Report**

I need to use `WriteableBuffer` to annotate the `read` method of my subclass of `RawIOBase`, but it's not exported.

**Your Environment**

- Mypy version used: 0.971 (compiled)
- Python version used: 3.10

**Comment by JelleZijlstra** [comment]
I'm not sure what you mean. Neither name is exported from https://github.com/python/typeshed/blob/master/stdlib/typing.pyi.

**Comment by rrthomas** [comment]
> I'm not sure what you mean. Neither name is exported from https://github.com/python/typeshed/blob/master/stdlib/typing.pyi.

Sorry, my mistake, the comment about `ReadableBuffer` was a distraction, I've removed it from the issue description.

**Comment by srittau** [comment]
`ReadableBuffer` and `WriteableBuffer` are currently exported from `_typeshed`, which is available at type check time only:

```python
from __future__ import annotations

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from _typeshed import WriteableBuffer
```

**Comment by rrthomas** [comment]
> `ReadableBuffer` and `WriteableBuffer` are currently exported from `_typeshed`, which is available at type check time only:
> 
> ```python
> from __future__ import annotations
> 
> from typing import TYPE_CHECKING
> if TYPE_CHECKING:
>     from _typeshed import WriteableBuffer
> ```

Thanks for this, is that an idiom I should have found somewhere in the documentation?

**Comment by srittau** [comment]
Well, you *should* have found it, but you *wouldn't* have found it. Our documentation is unfortunately quite lacking in some areas, especially when it comes to typeshed-specific idioms. For now, I have at least opened python/typing#1262 to track this.

**Comment by rrthomas** [comment]
Thanks @srittau!

There seems to be one more missing element I need: if I use `WriteableBuffer` as an annotation having imported it with the code you suggest then type-checking works fine, but the code still does not run; I get the error:

```
  File "/home/rrt/Software/rpl/./rpl", line 100, in ChainStream
    def readinto(self, b: WriteableBuffer) -> int:
NameError: name 'WriteableBuffer' is not defined
```

**Comment by AlexWaygood** [comment]
> the code still does not run; I get the error:
> 
> ```
>   File "/home/rrt/Software/rpl/./rpl", line 100, in ChainStream
>     def readinto(self, b: WriteableBuffer) -> int:
> NameError: name 'WriteableBuffer' is not defined
> ```

It sounds like you maybe don't have `from __future__ import annotations` at the top of your file :)

**Comment by rrthomas** [comment]
That's it, thanks! I hadn't realised that I needed even more futuristic annotations treatment than I already have in Python 3.10!
