### ISSUE TITLE
No stubs for stdlib module "calendar"

### ISSUE THREAD

**Issue by lbolla** [python/typeshed#88]
Stubs are missing for `calendar` module https://docs.python.org/2/library/calendar.html

**Comment by gvanrossum** [comment]
Would you like to contribute some? There are Python 3 stubs for calendar, which could be reused, but they look pretty incomplete...

**Comment by lbolla** [comment]
I submitted a pull request: https://github.com/python/typeshed/pull/90
I ran into some issues, described in the PR itself. I wonder if you can give me some guidance, as this is my first contribution to this project!

**Comment by lbolla** [comment]
PR merged. Thanks!
