### ISSUE TITLE
Using DictProxy.values() yields false positives

### ISSUE THREAD

**Issue by prauscher** [python/typeshed#8814]
If I run mypy with the following code:
```
from multiprocessing.managers import DictProxy
from multiprocessing import Manager

d: DictProxy[str, float] = Manager().dict()

d["hallo"] = 4.2
d["test"] = 2.8

print(sum(d.values()))
```

It should give no typing errors, as the values of DictProxy should be an Iterable[float]. Instead however, i receive `error: Argument 1 to "sum" has incompatible type "List[Tuple[str, float]]"; expected "Iterable[bool]"` for line 9 (the print-line)

Is this an issue with typeshed or more with the python multiprocessing-library?

**Comment by AlexWaygood** [comment]
> Is this an issue with typeshed or more with the python multiprocessing-library?

Definitely typeshed :)

I've filed #8815
