### ISSUE TITLE
Expected type arguments for generic class "StreamHandler"

### ISSUE THREAD

**Issue by GabrielCappelli** [python/typeshed#8840]
Hello, 

I'm inheriting from logging.StreamHandler and getting this error on Pyright

```python
class MyStreamHandler(StreamHandler):
```

`Expected type arguments for generic class "StreamHandler"`

If I try to add an argument then I get code that doesn't work:

```python
class MyStreamHandler(StreamHandler[TextIO]):
```

```
    class MyStreamHandler(StreamHandler[TextIO]):
TypeError: 'type' object is not subscriptable
```

I believe this is due to this class being generic on typeshed, but not in stdlib. Now I'm not really sure how to inherit from it and make the typechecker happy

**Comment by JelleZijlstra** [comment]
See https://mypy.readthedocs.io/en/stable/runtime_troubles.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime

**Comment by AlexWaygood** [comment]
See also the discussion in https://github.com/python/typeshed/pull/5954#issuecomment-1114253234, and the following comments

**Comment by GabrielCappelli** [comment]
Thank you! was a bit tunnel visioned on `StreamHandler` and didn't search properly
