### ISSUE TITLE
`bytes` constructor does not permit `PickleBuffer`

### ISSUE THREAD

**Issue by jakirkham** [python/typeshed#8889]
Currently it appears `PickleBuffer` is not included in `SupportsBytes`.

As a result, linting tools may complain if a user writes a script like the one below.

```python
# script2.py


from pickle import PickleBuffer

b1 = b"abc"
pb = PickleBuffer(b1)
b2 = bytes(pb)         # <- linter raises here
print(b2)
```

Executing the script above `print`s out `b'abc'` as expected, but linters don't expect `PickleBuffer` to be a valid input to `bytes`.

If possible, it would be helpful if `PickleBuffer` was added to `SupportsBytes`.

xref: https://github.com/microsoft/pyright/issues/4043

**Comment by srittau** [comment]
I think the issue here is that the `bytes()` constructor does not accept `ReadableBuffer` objects, although `PickleBuffer` implements the buffer protocols. Cc @JelleZijlstra as someone who has more experience with the buffer protocol (I think).

**Comment by jakirkham** [comment]
Idk what `ReadableBuffer` entails. Does that just mean any read-only or writeable [buffer protocol]( https://docs.python.org/3/c-api/buffer.html ) object?

If so, there is this line in the Python docs about what [`bytes`]( https://docs.python.org/3/library/stdtypes.html#bytes ) accepts:

> Copying existing binary data via the buffer protocol: `bytes(obj)`

**Comment by JelleZijlstra** [comment]
> Idk what `ReadableBuffer` entails. Does that just mean any read-only or writeable [buffer protocol](https://docs.python.org/3/c-api/buffer.html) object?

Yes, that's the intention. I looked at the code for `bytes.__new__` and it has separate codepaths for `__bytes__` and buffers, so I submitted a PR making it explicit that both are supported.

**Comment by jakirkham** [comment]
Thanks Jelle! 🙏

Also want to say I really appreciate the work you are doing to make the buffer protocol easier to use in Python (like [PEP 688]( https://peps.python.org/pep-0688/ )). This is incredibly useful for those of us working with data in Python (NumPy, Pandas, etc.).
