### ISSUE TITLE
stub for asyncio.coroutine incorrect

### ISSUE THREAD

**Issue by ddfisher** [python/typeshed#89]
In PR #81, an incorrect stub was introduced for coroutine (see [here](https://github.com/dsp/typeshed/commit/4d0a9e6d491efae6442d963a771854e980f8f78e#diff-85036776c276ba424c200fda68df75f5R6)) which breaks [this mypy unit test](https://github.com/python/mypy/blob/master/mypy/test/data/pythoneval-asyncio.test#L46), among others.  I'm not sure why this wasn't caught by CI.

A fix for this is blocking https://github.com/python/mypy/pull/1218, which needs to update to the latest typeshed master.

**Comment by gvanrossum** [comment]
Can you investigate why typeshed's CI didn't catch this? Also go ahead and fix it in typeshed.

**Comment by gvanrossum** [comment]
FWIW typeshed's CI doesn't run mypy's unit tests. It just runs mypy over the code in typeshed.

**Comment by ddfisher** [comment]
Oh okay.  That would be why it wasn't caught by CI, then.

**Comment by gvanrossum** [comment]
It would be caught by mypy's CI on the diff that synced up to the new typeshed version though... But I haven't made that diff yet (and now I won't until I've verified everything properly).

**Comment by ddfisher** [comment]
Right.  That's exactly how I caught it, actually.
