### ISSUE TITLE
Invoke stubs fail with latest changes

### ISSUE THREAD

**Issue by kasium** [python/typeshed#8936]
Hi,

with the latest changes added to the invoke-stubs, mypy fails

```py
from invoke import task, Context

@task
def docker_build(context: Context) -> None:
    pass

@task(docker_build)
def docker_push(context: Context) -> None:
    pass
```

```
foo.py:9:2: error: Argument 1 to "__call__" of "Task" has incompatible type "Callable[[Context], None]"; expected "Context"  [arg-type]
    @task(docker_build)
```

As soon as I add any argument to `@task(docker_build)` like `@task(docker_build, name="fooo")` it works. I guess mypy fails to distinguish task overload 1 and 2. Do you have any idea how to solve this?

**Comment by Akuli** [comment]
We could try switching the order of the first two overloads. When passing in a `Task` object, we want to match the overload that has `Task`, not the more general overload that has `Callable` (which matches because `Task` defines `__call__`).

**Comment by kasium** [comment]
Hi, the issue is closed by the change of @AlexWaygood , but I found another one

```py
from __future__ import annotations

from typing import Any

from invoke import Context, Task, task

test_task2: Task[..., Any]


@task(pre_ci_test2)
def test_task(context: Context) -> None:
    pass
```

-> `foo.py:10:2: error: Untyped decorator makes function "test_task" untyped  [misc]`

This is Independent of the order of the overloads. In my case I have a factory which creates test_task2 and returns it as `Task[..., Any]`. However, mypy gives up here

**Comment by AlexWaygood** [comment]
@kasium can you give us the definition of `pre_ci_test2`? It'll be pretty hard to reproduce and fix this problem without it :)

**Comment by kasium** [comment]
@AlexWaygood sorry, `pre_ci_test2` should have been `test_task2`. I adapted the code above

**Comment by kasium** [comment]
@AlexWaygood can you please have another look on that?

**Comment by kasium** [comment]
invoke now has it's own types. Let's close it
