### ISSUE TITLE
Remove partial classes/modules from CONTRIBUTING?

### ISSUE THREAD

**Issue by srittau** [python/typeshed#8955]
We still have a section about "Incomplete stubs" in CONTRIBUTING. I believe we should remove this as nowadays stubs are generally generated using stubgen, so this shouldn't be an issue anymore. I don't want to encourage new incomplete stubs, and it makes the CONTRIBUTING file a longer read.

We only should leave the sentence about unannotated arguments and return values.

**Comment by ramvikrams** [comment]
Done with the changes

**Comment by Avasam** [comment]
With this, should `ignore_missing_stub` default to false? If we don't want to encourage new incomplete stubs, it's mainly really needed for stubs that are already present and incomplete, or would result in an allowlist that's too complex.
