### ISSUE TITLE
"master" branch renamed to "main"

### ISSUE THREAD

**Issue by srittau** [python/typeshed#8956]
I don't want to go into the political reasons for renaming the branch, but in my opinion there is a clear push to standardize on the new name `main`. I believe there was also a SC decision that all projects under the python org should eventually change to that name, although we haven't been approached about this. But CPython has switched (and the stub_uploader always used `main`). Selfishly, I also renamed the branches in most of my projects, with typeshed being one of the last still using `master`.

**Comment by AlexWaygood** [comment]
I support doing this.

**Comment by srittau** [comment]
From what I can see, the following files need to be updated after the transition:

* `.github/workflows/mypy_primer.yml`
* `README.md`
* `scripts/stubsabot.py`

**Comment by srittau** [comment]
Also in the stub_uploader:

* `stub_uploader/build_wheel.py`
* `stub_uploader/get_version.py`

**Comment by srittau** [comment]
I have renamed the branch now. Contributors will need to run the following commands locally to update their local copy:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
