### ISSUE TITLE
Possible bug in definition of datetime.timedelta

### ISSUE THREAD

**Issue by Dr-Irv** [python/typeshed#8971]
```
from datetime import timedelta

class Too(timedelta):
    def __abs__(self) -> Too:
        return Too()

t = Too()
t1 = abs(t)
t2 = t.__abs__()
reveal_type(t1)
reveal_type(t2)
```
Here the revealed types (with pyright and mypy) of `t1` and `t2` are `timedelta` and `Too`, respectively, but the type of `t1` should be `Too`.

`pyright` claims this is a bug in typeshed.  See https://github.com/microsoft/pyright/issues/4082#issuecomment-1288206453

**Comment by AlexWaygood** [comment]
Interesting. The direct inheritance from a protocol here is indeed "a bit fishy", as @erictraut says -- it probably dates from before PEP 544 was a thing.
