### ISSUE TITLE
Mark types-pkg-resources as obsolete

### ISSUE THREAD

**Issue by hauntsaninja** [python/typeshed#8976]
This confused a user here: https://github.com/python/typeshed/pull/8975

Ideally there's some indication on https://pypi.org/project/types-pkg-resources/ that types-setuptools should be used instead. This would probably involve making a manual release of some sort.

**Comment by hauntsaninja** [comment]
Would be good to also mark https://pypi.org/project/types-typing-extensions/

**Comment by srittau** [comment]
We should probably upload an empty packages, i.e. one that only contains an empty `__init__.pyi` file to clearly mark that there's something wrong if someone updates the stubs.

**Comment by AlexWaygood** [comment]
Closing in favour of #10340
