### ISSUE TITLE
Argument of `float.__new__` should be positional-only

### ISSUE THREAD

**Issue by LeeeeT** [python/typeshed#8990]
Currently the first argument of `float.__new__` is marked as positional or keyword.

https://github.com/python/typeshed/blob/fd75bc21fca7d62235bdd2063ce65cdddbd40a1a/stdlib/builtins.pyi#L301-L302

This is incorrect since `float(x=1)` leads to an error. `x` should be changed to `__x`.

**Comment by hauntsaninja** [comment]
PR welcome!
