### ISSUE TITLE
Should we use `_ProtocolMeta` in `typing.py`?

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#8998]
Right now `_ProtocolMeta` is never used:

https://github.com/python/typeshed/blob/739711e94725d7720d5ae923f6ff44c8aeb5f915/stdlib/typing.pyi#L282

But, it is a base metaclass for `Protocol` type in `typing.py`: https://github.com/python/cpython/blame/723ebe76e787cfa6b08cc9587dd679f3234a1025/Lib/typing.py#L1965

It is also used for all `Protocol` types (we currently just use `ABCMeta` for them`): 

https://github.com/python/typeshed/blob/739711e94725d7720d5ae923f6ff44c8aeb5f915/stdlib/typing.pyi#L287-L305

CPython: https://github.com/python/cpython/blame/723ebe76e787cfa6b08cc9587dd679f3234a1025/Lib/typing.py#L2745

So, the question is:
1. Should we use for `Protocol` class? It is rather complex, because right now `Protocol` is `_SpecialForm`
2. Should we use it for `Protocol` types in `typing.pyi`?

**Comment by JelleZijlstra** [comment]
typing.pyi is central to type checking and typecheckers need to heavily special case for the contents of the stub. Therefore, I think we should only make changes here if they fix a concrete problem for users, not out of mere perfectionism.
