### ISSUE TITLE
ABC's missing register function

### ISSUE THREAD

**Issue by zrothberg** [python/typeshed#8999]
So I am not 100% this is because of typeshed, but because I am having the issue in both pycharm and VSCode I am 85% sure its because of typeshed. 

For whatever reason, none of the abc's from the collections module have the method `register`. I am FAIRLY certain it used to appear just fine and I have no idea when this started. As far as I can tell none of ABC metas methods are visible on the class. I don't use VSCode much and it may have always been the case and pycharm just recently started being weird about it on a recent update.

Is this intentional or just a side effect of the classes claiming they are coming from typing and not abc.

**Comment by JelleZijlstra** [comment]
I think it's a type checker bug. `typing.Hashable` in typeshed has `metaclass=ABCMeta`, and `abc.ABCMeta` defines a `register` method. If type checkers don't pick up the metaclass method, that's not something typeshed can fix.

**Comment by AlexWaygood** [comment]
> I think it's a type checker bug. `typing.Hashable` in typeshed has `metaclass=ABCMeta`, and `abc.ABCMeta` defines a `register` method. If type checkers don't pick up the metaclass method, that's not something typeshed can fix.

I agree, I'm not sure there's much we can do here. `ABCMeta` is at the heart of the typing system, so is heavily special-cased by type checkers. That's likely the cause of the problem here; the typeshed definitions look correct to me (other than the classes being defined in `typing.pyi` rather than `_collections_abc.pyi` -- but I can't see how that would cause this problem).

**Comment by zrothberg** [comment]
It is actually even more annoyingly broken then I had thought it also claims I can import the entire `collections.abc` names directly from `collections`. They are probably going to need to special case this entire module since it literally powers the bulk of stubs. 

The only thing I see that looks off is that protocol is defined as a `_specialform`and would have a parent class with a different metaclass then the one assigned. IDK if that would cause an issues but that is the only thing that looks off. I shall check with pylance and see if they have any idea. I custom created an inline class and it gets the metaclass methods no problem.

**Comment by zrothberg** [comment]
Yea I'm guessing pycharm is getting confused because it looks like its saying if its 3.10 or above its imported but the line in stubs is intended to mean only import if its 3.10 or above because you aren't importing the entire `collections.abc`. 

Alright thanks helping me out here. Hopefully this is something that is easy for them to fix.
