### ISSUE TITLE
Migrating stubs from other repositories

### ISSUE THREAD

**Issue by JukkaL** [python/typeshed#9]
These may include sources like PyCharm, mypy, pytypedecl, etc. We may also want to formally review at least some of the stubs before committing to make sure that they conform to the typeshed conventions.

If the same stubs is available from multiple sources, we'd probably want to start with the most complete/precise ones. We also want to keep Python 2 and 3 stubs for each module reasonably similar, but this is not absolutely necessary.

**Comment by gvanrossum** [comment]
I don't see anything particularly actionable here, so let's close this issue. (If the PyCharm folks wants to submit their stubs, please go ahead with PRs.)
