### ISSUE TITLE
Add stubs for pycocotools

### ISSUE THREAD

**Issue by hoel-bagard** [python/typeshed#9061]
Hi,

I would be interested in adding stubs for [pycocotools](https://github.com/ppwwyyxx/cocoapi) to typeshed (original repo [here](https://github.com/cocodataset/cocoapi), on pypi [here](https://pypi.org/project/pycocotools/))

If there isn't any issue with that, I would like to start working on a PR.

**Comment by srittau** [comment]
We welcome all type stubs for PyPI packages that don't ship with type information here on typeshed! I'm going to close this issue for now per our policy, but please free to open a PR. It's also okay to open a draft PR while working on it if you want early feedback.
