### ISSUE TITLE
A lot of CI failures bacause of `No matching distribution found for pytype==2022.08.30`

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#9067]
Example: https://github.com/python/typeshed/actions/runs/3379717081/jobs/5611639599

I am not sure we can anything from our side, except trying to clear cache: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#managing-caches

I cannot do this myself, can someone else please try it?

**Comment by JelleZijlstra** [comment]
![Screen Shot 2022-11-02 at 10 31 13 AM](https://user-images.githubusercontent.com/906600/199560495-371c1fa6-fab5-43dc-9ca6-f9e6bae9b246.png)

Nothing is cached.

**Comment by AlexWaygood** [comment]
Doesn't look like we have anything cached:

![image](https://user-images.githubusercontent.com/66076021/199560395-a5cb9b8e-7539-4fb6-a863-55f96609fa03.png)

**Comment by sobolevn** [comment]
🤔 

Thanks for checking!

Why is it failing then?
Another idea is that `pip` resolver is broken in some very specific way.

**Comment by JelleZijlstra** [comment]
See also google/pytype#1308.
