### ISSUE TITLE
Shouldn't a slice of a bytestring be a bytestring?

### ISSUE THREAD

**Issue by dvarrazzo** [python/typeshed#9080]
Slicing bytes, bytearray, memoryview objects, the result is an object of the same type.

However, slicing ByteArray, mypy complains:

```python
from collections.abc import ByteString

def f(s: ByteString) -> ByteString:
    return s[10:20]
```

```
mypy test-bytestring-slice.py
test-bytestring-slice.py:4: error: Incompatible return value type (got "Sequence[int]", expected "ByteString")
```

Tested with mypy 0.982, 0.990 (from git).

Is this a typeshed shortcoming?

**Comment by JelleZijlstra** [comment]
Don't use ByteString, it's basically useless. It declares no methods.

The behavior you see is because `ByteString` inherits `__getitem__` from Sequence, and `Sequence.__getitem__` doesn't guarantee that you get the same kind of Sequence back.

**Comment by dvarrazzo** [comment]
Ok.

Mine was an attempt to replace the homegrown `Buffer` type in psycopg (defined as `Union[bytes, bytearray, memoryview]` - something supporting the Buffer protocol) with something from the stdlib.

I guess we'll keep our `Buffer` :smile:

**Comment by hauntsaninja** [comment]
Yeah, would love to see the back of ByteString https://github.com/python/cpython/issues/91896

**Comment by JelleZijlstra** [comment]
In typeshed we have our own Buffer alias with a bunch more types: https://github.com/python/typeshed/blob/main/stdlib/_typeshed/__init__.pyi#L236. You can use it at type checking type (`if TYPE_CHECKING: from _typeshed import ReadableBuffer`).
