### ISSUE TITLE
Support types for `format_compact_decimal` (Babel 2.11.0)

### ISSUE THREAD

**Issue by DenverCoder1** [python/typeshed#9090]
I am getting an error using `format_compact_decimal` with Pyright and I was told the issue is that it's missing from the typeshed stubs here.

https://github.com/microsoft/pyright/issues/4138

(This will probably also apply to `format_compact_currency`, `Format.compact_decimal` and `Format.compact currency` which will be in the next Babel release (2.12.0))

**Comment by AlexWaygood** [comment]
PR welcome!

**Comment by DenverCoder1** [comment]
I'll work on it.

Should the types only go up to the latest stable version?

**Comment by AlexWaygood** [comment]
We currently don't have the ability (or bandwidth!) to provide stubs for multiple versions of packages — typeshed's stubs should generally only be assumed to be correct for the latest version of the runtime package :)
