### ISSUE TITLE
error: Module "_typeshed" has no attribute "Incomplete"

### ISSUE THREAD

**Issue by MinsungKim-BlockCrafters** [python/typeshed#9119]
I am having a trouble in importing Incomplete from _typeshed in Python 3.5.6. Is this a bug or should I install some additional modules via pip? Here is a code:

```python
from _typeshed import Incomplete

a: Incomplete
```

and here is a error message from `mypy bruh/bruh4.pyi`:

```shell
bruh/bruh4.pyi:1: error: Module "_typeshed" has no attribute "Incomplete"
```

**Comment by AlexWaygood** [comment]
What version of mypy are you using?

**Comment by AlexWaygood** [comment]
Each version of mypy vendors a copy of typeshed from a specific point in time. If you're using an old version of mypy, it might not have the `Incomplete` symbol in its vendored copy of the `stdlib/_typeshed/__init__.pyi` file. There are two solutions, if that's the case:
- Upgrade mypy to a more up-to-date version
- Clone the typeshed repo and use mypy with the `--custom-typeshed-dir` option pointing to your local clone of typeshed.

**Comment by MinsungKim-BlockCrafters** [comment]
> What version of mypy are you using?

```shell
python % mypy --version
mypy 0.910
```
 Is `0.910` too old?

**Comment by MinsungKim-BlockCrafters** [comment]
@AlexWaygood I clone typeshed repo and ran with `--custom-typeshed-dir` current main branch and got following errors;

```shell
(ccxt) minsungkim@Minsungui-MacBookPro python % mypy bruh/bruh4.pyi --custom-typeshed-dir typeshed 
Traceback (most recent call last):
  File "/Users/minsungkim/miniconda3/envs/ccxt/bin/mypy", line 11, in <module>
    sys.exit(console_entry())
  File "/Users/minsungkim/miniconda3/envs/ccxt/lib/python3.5/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "mypy/main.py", line 87, in main
  File "mypy/main.py", line 165, in run_build
  File "mypy/build.py", line 179, in build
  File "mypy/build.py", line 254, in _build
  File "mypy/build.py", line 2697, in dispatch
  File "mypy/build.py", line 3021, in process_graph
  File "mypy/build.py", line 3138, in process_stale_scc
  File "mypy/build.py", line 2288, in write_cache
  File "mypy/build.py", line 1475, in write_cache
  File "mypy/nodes.py", line 313, in serialize
  File "mypy/nodes.py", line 3149, in serialize
  File "mypy/nodes.py", line 3083, in serialize
AssertionError: Definition of sre_constants.Self is unexpectedly incomplete
```

Is there any possibility that because the Python version is 3.5?

**Comment by AlexWaygood** [comment]
> Is `0.910` too old?

I'm afraid so, yes. You'll have to upgrade to at least mypy 0.950 if you want to be able to use `_typeshed.Incomplete` without `--custom-typeshed-dir`.

> I clone typeshed repo and ran with --custom-typeshed-dir and current main branch and got following errors [...] Is there any possibility that because the Python version is 3.5?

I've no idea — but, it seems likely. CPython, Mypy and typeshed no longer support Python 3.6, let alone Python 3.5. If at all possible, I'd recommend upgrading to at least Python 3.7 :)

**Comment by MinsungKim-BlockCrafters** [comment]
So the situation is that I am trying to add support type hints of some library, and for unknown reason it has support for Python 3.5 and 3.6. Maybe I should request them to upgrade minimum supported Python version. Thanks for your quick help anyway.

**Comment by AlexWaygood** [comment]
No worries, happy to help. I'm going to close this out now, as I think there's not much actionable for typeshed here, but feel free to ask any further questions if you have any :)

**Comment by MinsungKim-BlockCrafters** [comment]
For anyone who wants to use mypy **in Python 3.5** (Note that I used miniconda) - The max available mypy version is `0.910`.

**Comment by JelleZijlstra** [comment]
Note that there's no particularly strong reason to use `_typeshed.Incomplete` in your stubs. It's just an alias for Any. You can just `Incomplete = Any` in your stubs and it will work the same.

**Comment by MinsungKim-BlockCrafters** [comment]
> Note that there's no particularly strong reason to use `_typeshed.Incomplete` in your stubs. It's just an alias for Any. You can just `Incomplete = Any` in your stubs and it will work the same.

That's good, mypy's stubgen generated stub codes using `Incomplete` so I thought that was something special. I will try with `Incomplete = Any`.

**Comment by MinsungKim-BlockCrafters** [comment]
I retried stub generation with stubgen and it does not generate `Incomplete` anymore, perhaps because I removed mypy cache. (But I have no idea what was going on) Anyway it worked well!
