### ISSUE TITLE
Adapt ast types for mypy 0.990 

### ISSUE THREAD

**Issue by kasium** [python/typeshed#9129]
With mypy 0.990 the complex/int/float promotion was changed (see https://github.com/python/mypy/issues/14030).
Therefore checks like `isinstance(node, ast.Num) and isinstance(node.n, int)` fails with strict mode enabled.

The recommendation by mypy is to change complex to `Union[int, float, complex]`. Are there any objections to do so in the ast module?

**Comment by srittau** [comment]
I'm not sure what you would want to change. Stubs don't use `isinstance` checks.

**Comment by kasium** [comment]
Ah sorry;

so in my code I use code like `isinstance(node, ast.Num) and isinstance(node.n, int)` and this fails now with mypy 0.990 (see https://github.com/python/mypy/issues/14030). The recommendation by mypy is to adapt the types of `ast.Num.n` to be `Union[int, float, complex]`

**Comment by ilevkivskyi** [comment]
FWIW I also think `n` for both `Num` and `Constant` should be `Union[int, float, complex]`. This is more correct, and doesn't implicitly rely on type promotions.

**Comment by kasium** [comment]
Okay, let me then give a PR a try

**Comment by ilevkivskyi** [comment]
Hm, as noticed in the PR, it looks like tpyeshed is using a flake8 lint rule that actually prohibits `int | float`. This is bad, there is a chance there are some other places with incorrect plain `complex` annotations.

@srittau I would propose to disable this rule globally.

**Comment by ilevkivskyi** [comment]
I briefly scrolled through and found only other problematic annotations in typed-ast https://github.com/python/typeshed/blob/main/stubs/typed-ast/typed_ast/ast27.pyi#L241 and https://github.com/python/typeshed/blob/main/stubs/typed-ast/typed_ast/ast3.pyi#L260. @kasium maybe you can add these to your PR?

**Comment by kasium** [comment]
sure!
