### ISSUE TITLE
`secrets.choice` not accepting `str`

### ISSUE THREAD

**Issue by SimonSchick** [python/typeshed#9144]
Error via pylance:

Current python version: `3.9.14`
Running on latest MacOS in vscode.
```
(constant) CODE_ALPHABET: str
Argument of type "str" cannot be assigned to parameter "seq" of type "SupportsLenAndGetItem[_T@choice]" in function "choice"
  "str" is incompatible with protocol "SupportsLenAndGetItem[LiteralString]"
    TypeVar "_T_co@SupportsLenAndGetItem" is covariant
      "str" is incompatible with "LiteralString"Pylance[reportGeneralTypeIssues](https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules)
```

Definitions also served via pylance but seem up-to-date:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/3259089/200968389-e2f45f9c-6430-40a6-8ae9-f29fd08e88a7.png">

This seems kinda odd, unsure if this is a pylance issue or a problem with the definitions, please advice.

**Comment by JelleZijlstra** [comment]
This seems like a pyright bug. I can't reproduce it though: pyright gives me no errors for

```python
import secrets
secrets.choice("abc")
```

**Comment by srittau** [comment]
Maybe pyright has some option to make `str` incompatible with str sequences?

**Comment by sobolevn** [comment]
> "str" is incompatible with "LiteralString"

Do you use `LiteralString` somewhere? 🤔
