### ISSUE TITLE
Issue with annotation six.byte2int starting 1.16.21.2

### ISSUE THREAD

**Issue by levincarmel** [python/typeshed#9145]
Hi,
Starting 1.16.21.2 we have an issue with mypy failing for annotations of `six.byte2int`.
We had this method:

```python 
def byte2int(c: Union[bytes, int]) -> int:
    if isinstance(c, bytes):
        return six.byte2int(c)
    return c
```

which was called the following way:
`pp_fingerprint = ":".join("{:02x}".format(byte2int(c)) for c in fingerprint).upper()`

This used to work until now, but now we get this failure:
`Argument 1 to "byte2int" has incompatible type "bytes"; expected "SupportsGetItem[int, <nothing>]"
`
Is this an issue with this release? Or are we supposed to fix our annotations in some way?

Thanks in advance!

**Comment by AlexWaygood** [comment]
Cc. @Avasam

**Comment by Avasam** [comment]
The example can be simplified to:
```
import six
six.byte2int(b"1")
```
Weird mypy-specific issue that I ironically didn't catch because I was specifically trying to not use bytes.
An overload easily fixes this, PR incoming.

**Comment by JelleZijlstra** [comment]
@levincarmel what version of mypy are you running?
