### ISSUE TITLE
Tests failing due to pip install connection issues

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#9189]
I've seen ***a lot*** of tests failing during the install step lately due to `ERROR: Could not install packages due to an OSError: HTTPSConnectionPool`.

The python action offers a way to cache pip dependency and specify a differently named `requirements.txt` to base itself off: https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
Maybe this could help?

**Comment by AlexWaygood** [comment]
Caching pip requirements seems like a good idea to me. I've no idea whether it'll solve this problem, but it might do. And I've seen it speed up CI on other projects pretty substantially, so there's no real downside AFAICS.

**Comment by Avasam** [comment]
Completed in #9192
