### ISSUE TITLE
DecimalTuple definition is incorrect

### ISSUE THREAD

**Issue by dapper91** [python/typeshed#9191]
Current `DecimalTuple` definition is:
```py
class DecimalTuple(NamedTuple):
    sign: int
    digits: tuple[int, ...]
    exponent: int
```
source: https://github.com/python/typeshed/blob/main/stdlib/_decimal.pyi#L16

But if a decimal value is `NaN` the exponent is of type `str`.  The following example illustrate that:
```py
>>> from decimal import Decimal
>>> exponent = Decimal('NaN').as_tuple().exponent
>>> print(exponent)
n
>>> print(type(exponent))
<class 'str'>
>>>
```

It seems like the correct definition should be like this:
```py
class DecimalTuple(NamedTuple):
    sign: int
    digits: tuple[int, ...]
    exponent: Union[int, str]
```

**Comment by JelleZijlstra** [comment]
Looks like it can also be `N` for a signaling NaN and `F` for infinity. I suppose we could do `int | Literal["n", "N", "F"]`.
