### ISSUE TITLE
loop.create_connection should return Transport not BaseTransport

### ISSUE THREAD

**Issue by bmerry** [python/typeshed#9199]
According to [the docs](https://docs.python.org/3/library/asyncio-protocol.html?highlight=transport#asyncio.Transport), Transport is the class created by `loop.create_connection`, but the annotations have it returning a BaseTransport. This causes a false positive when the returned transport is passed to a StreamWriter, which as of #7611 expects a WriteTransport (a base class of Transport but not of BaseTransport).

**Comment by bmerry** [comment]
Here's an example that works at runtime but fails to typecheck with mypy 0.991:

```python
#!/usr/bin/env python3

import asyncio


async def main() -> None:
    reader = asyncio.StreamReader()
    protocol = asyncio.StreamReaderProtocol(reader)
    loop = asyncio.get_running_loop()
    transport, _ = await loop.create_connection(lambda: protocol, "www.google.com", 80)
    writer = asyncio.StreamWriter(transport, protocol, reader, loop)
    writer.write(b"HTTP/1.0 GET /\r\n\r\n")
    print((await reader.readline()).decode())


asyncio.run(main())
```

**Comment by srittau** [comment]
Related: #6936. If I understand correctly, `create_connection()` will always return a full read/write `Transport`, but I'm not too experienced in asyncio. If that's the case, we should definitely change the return type.

**Comment by srittau** [comment]
A PR is certainly welcome. This will also help us judge real world impact.
