### ISSUE TITLE
netCDF4 package

### ISSUE THREAD

**Issue by jarrodcolburn** [python/typeshed#9241]
I'm working on [my fork | `netcdf` branch | `stubs/netCDF4` directory](https://github.com/jarrodcolburn/typeshed/tree/netcdf4/stubs/netCDF4) in prep to create a PR to add type support for the `netCDF4` [package](https://github.com/Unidata/netcdf4-python).
It's coming along, but if I could get with someone with experience to ask a few questions it would be appreciated.

I'm a VSCode guy, so if anyone is up for doing a Live Share sessions that'd be great, thanks

**Comment by srittau** [comment]
@jarrodcolburn Sorry for the late reply. We have typing support forums over at https://github.com/python/typing/discussions, especially the "Q&A" and "Reviews" forum. Please feel free to ask any questions to have over there.
