### ISSUE TITLE
Jinja2 stubs incorrect with use of InternationalizationExtension due to dynamic editing of Environment

### ISSUE THREAD

**Issue by timabbott** [python/typeshed#927]
If you're using the Jinja2 internationalization extension, the following code will run (and is sorta necessary?):
```
from jinja2 import Environment                                 
from django.utils import translation                                                                 
                                      
env = Environment(options)
env.install_gettext_translations(translation, True)
```

By mypy won't like it because `install_gettext_extension` isn't in the stubs:
```
foo.py:4: error: Argument 1 to "Environment" has incompatible type Dict[None, None]; expected "str"
foo.py:5: error: "Environment" has no attribute "install_gettext_translations"
```

the reason is that the internationalization extension works as follows (see https://github.com/pallets/jinja/blob/master/jinja2/ext.py#L156):

```
class InternationalizationExtension(Extension):                                                      
    ...
    def __init__(self, environment):                                                                 
        Extension.__init__(self, environment)                                                        
        environment.globals['_'] = _gettext_alias                                                    
        environment.extend(                                                                          
            install_gettext_translations=self._install,                                              
            install_null_translations=self._install_null,                                            
            install_gettext_callables=self._install_callables,                                       
            uninstall_gettext_translations=self._uninstall,                                          
            extract_translations=self._extract,                                                      
            newstyle_gettext=False                                                                   
        )                                                                                            
```

Basically, it adds some extra attributes to `class Environment` dynamically.  

I think probably the right fix is to just add these attributes to the Environment class in the stubs, but I'm not sure, since they seem to have been auto-generated using stubgen.

**Comment by gvanrossum** [comment]
I don't understand where the variable `options` comes from, but ignoring that, you should just be able to send a PR that updates the stubs -- those stubs presumably were initially generated by stubgen but then manually updated without removing the comment. We never run stubgen once the code has been checked in.

**Comment by timabbott** [comment]
Sorry, should have just put `{}` in for options; took a bit to simplify the example.  OK, makes sense re: stubgen ; does that mean one should make a practice of deleting stubgen comments when checking it in?

**Comment by gvanrossum** [comment]
Yes.

--Guido (mobile)

On Feb 10, 2017 7:35 PM, "Tim Abbott" <notifications@github.com> wrote:

Sorry, should have just put {} in for options; took a bit to simplify the
example. OK, makes sense re: stubgen ; does that mean one should make a
practice of deleting stubgen comments when checking it in?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/python/typeshed/issues/927#issuecomment-279118153>, or mute
the thread
