### ISSUE TITLE
Add method Catalog.is_identical for babel package

### ISSUE THREAD

**Issue by hyzyla** [python/typeshed#9277]
Seems like `is_identacal` method of `Catalog` from `babel` package is missing

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/7952949/204035583-a7868f28-9695-4dec-b39a-bc295979d4f9.png">

**Comment by AlexWaygood** [comment]
Yes, looks like both `Catalog` and `Message` are missing the `is_identical()` method they have at runtime. PR welcome!
