### ISSUE TITLE
None-able fields from `chardet.detect` are annotated as not None

### ISSUE THREAD

**Issue by pinterior** [python/typeshed#9292]
chardet returns `dict` as return value of `chardet.detect` (or `UniversalDetector.close`).
in typeshed, type of these `dict`s is annotated as `_FinalResultType` and it's field type is all not None.

https://github.com/python/typeshed/blob/c6800d12142b139271a606facdfdd47fdaba841f/stubs/chardet/chardet/__init__.pyi#L20
https://github.com/python/typeshed/blob/c6800d12142b139271a606facdfdd47fdaba841f/stubs/chardet/chardet/universaldetector.pyi#L5-L8

but `encoding` and `language` field may be `None` on some short input. these two fileds should has type `None | str`.
(in other words, no need to distinguish `_IntermediateResultType` and `_FinalResultType`)

```
$ python
Python 3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import chardet
>>> chardet.__version__
'5.0.0'
>>> chardet.detect(b"")
{'encoding': None, 'confidence': 0.0, 'language': None}
>>> chardet.detect(b"\x81")
{'encoding': None, 'confidence': 0.0, 'language': None}
```

**Comment by sobolevn** [comment]
Hi, @pinterior!

`chardet` now has type annotations! https://github.com/chardet/chardet/blob/72642823f7bd4b12efe9fa066ec7a84c607e141f/chardet/resultdict.py#L10 (it is the same as we have). So, you can report this issue there: people from upstream can judge better: this might be a bug / or incorrect annotation / etc. And after that we can backport the fix here as well :)

Waiting for a new release to drop them at some point (6 months, I guess) 🎉

**Comment by sobolevn** [comment]
> Waiting for a new release to drop them at some point (6 months, I guess)

Yes, we still have to wait :(

**Comment by AlexWaygood** [comment]
The upstream library has just made a release with a `py.typed` file, that also includes the fix for this issue. So your best available fix is to upgrade your version of the runtime package and uninstall typeshed's stubs package.

That said, if someone wants to backport the fix to typeshed's stubs, I won't object! But I'll close this issue for now :)
