### ISSUE TITLE
`StrOrBytesPath | FileDescriptor` alias

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#9297]
Opening an issue so we don't forget.

[Original comment](https://github.com/python/typeshed/pull/9279#discussion_r1033813535) from @AlexWaygood :
> We could actually consider adding this alias to `_typeshed`; there's a bunch of functions in `os/__init__.pyi` that could use it. `os/__init__.pyi` currently defines an `_FdOrAnyPath` alias. We don't need to add the alias to `_typeshed` in this PR, though.

There's a handful of `_OpenFile` aliases also defined in multiple stubs

There's also a lot of `int | StrOrBytesPath`, `StrOrBytesPath | int` and `StrOrBytesPath | FileDescriptor` which could be replaced by the alias.

**Comment by Avasam** [comment]
With a new mypy release around the corner, adding helper types before mypy updates its vendored typeshed might be a good idea.

**Comment by AlexWaygood** [comment]
There don't seem to be any objections :)

Three only reservation I have is about the name. `_OpenFile` isn't very descriptive, since for the `StrOrBytesPath` half of the alias, the file _hasn't_ actually been opened yet. Maybe something like `FileDescriptorOrPath`?

**Comment by JelleZijlstra** [comment]
I would be okay with `PathOrFD` since "FD" for "file descriptor" is pretty commonly understood, but maybe it's still too obscure.

**Comment by hauntsaninja** [comment]
"fd" seems fine; it's commonly used as an identifier in the Python docs and e.g. `os.fdopen` is a thing

**Comment by AlexWaygood** [comment]
I'd still lean towards `FileDescriptorOrPath`, but happy with either!
