### ISSUE TITLE
Python 3.11: importlib.abc has moved to importlib.resources.abc

### ISSUE THREAD

**Issue by tristanlatr** [python/typeshed#9321]
From python 3.11, the location of the ABCs of the `importlib` package are now in ``importlib.resources.abc``

```python
if TYPE_CHECKING:
    if sys.version_info >= (3,11):
        from importlib.resources.abc import Traversable
    elif sys.version_info >= (3,9):
        from importlib.abc import Traversable
    else:
        Traversable = Any
```

I get mypy error:

```
error: Skipping analyzing "importlib.resources.abc": module is
installed, but missing library stubs or py.typed marker  [import]
            from importlib.resources.abc import Traversable
```

**Comment by JelleZijlstra** [comment]
The ABCs still exist in `importlib.abc` too, and only a few were moved (`ResourceReader, Traversable, TraversableResources`).

`importlib.resources` was made into a package in https://github.com/python/cpython/pull/30176/files.
