### ISSUE TITLE
Use a `JSON` return type for `requests.Response.json`

### ISSUE THREAD

**Issue by Viicos** [python/typeshed#9335]
As stated [here](https://github.com/python/typing/issues/182#issuecomment-1320974824), recursive type aliases are supported by most type checkers, and a `JSON` type can now be properly defined. I'd like to know if changing the return type of the `json` method to this could be feasible.

https://github.com/python/typeshed/blob/89fb1d5521aeccb37dd2d278234913d4e9ff6063/stubs/requests/requests/models.pyi#L129-L139

**Comment by hauntsaninja** [comment]
Unfortunately, no. As I state in the comment you link:

> As always, if you return a union type, your callers will have to assert the structure of their JSON in order to type check. If this an issue, return e.g. dict[str, Any] or Any or cast or type-ignore or just bite the bullet and assert.

Typeshed typically avoids union return types in cases where callers typically know their structure, since we weight false positives more heavily than false negatives. You may be interested in https://github.com/python/typing/issues/1096

**Comment by Viicos** [comment]
Ok good to know that we are trying to avoid union return types! So for instance when making an API wrapper using `requests`, one could define the following method:

```python
class MyClient:
    ...
    def get_ressource(self) -> dict[str, Any]:
        return cast(dict[str, Any], requests.get("http://api.example.com"))
```

If I know that my ressource will have the type `dict[str, Any]`, could this be a viable solution?

Thanks in advance

**Comment by hauntsaninja** [comment]
Yes, that could work, but I'd do it slightly differently:
```
class MyClient:
    def get_resource(self) -> dict[str, Any]:
        ret: dict[str, Any] = requests.get("http://api.example.com").json()
        return ret
```
This avoids the cast, which is as unsafe as `# type: ignore` (and more unsafe than `# type: ignore[no-any-return]`)... in particular, the cast covers up a real problem in your example, which is that you forgot `.json()` ;-)

That is, possible solutions are:
- assign to a variable with a known type before returning
- use `# type: ignore[no-any-return]` with the error code
- use `mypy --strict --no-warn-return-any` (e.g. if you use a lot of untyped APIs)
- finally, you can use `cast` or `# type: ignore` without the error code, but this could cover up other errors like forgetting to add `.json()`

**Comment by Viicos** [comment]
Great catch indeed `.json()` was missing. I like the solution to assign to a variable before returning, in my opinion this is more readable than using `cast`. Thanks for the clear explanation! Closing.
