### ISSUE TITLE
stubtest_third_party.py fails on Debian systems with a bad error message due to no ensurepip module

### ISSUE THREAD

**Issue by hamdanal** [python/typeshed#9375]
I was testing a change locally and while running stubtest the test exits with a traceback like this one:

```console
$ python3.8 t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import venv; venv.create("/tmp/venv_dir_108341Y4HR", with_pip=True, clear=True)
  File "/usr/lib/python3.8/venv/__init__.py", line 391, in create
    builder.create(env_dir)
  File "/usr/lib/python3.8/venv/__init__.py", line 68, in create
    self._setup_pip(context)
  File "/usr/lib/python3.8/venv/__init__.py", line 289, in _setup_pip
    subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/tmp/venv_dir_108341Y4HR/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
I have the following `t.py`: `import venv; venv.create("/tmp/venv_dir_108341Y4HR", with_pip=True, clear=True)`
and python3.8 installed but not `python3.8-venv` on Ubunu 22.04.

In stubtest, the error is produced on this line:
https://github.com/python/typeshed/blob/04d4cbd92f2f6b2f845e1c3e0b257a96c3e170a5/tests/stubtest_third_party.py#L46

The traceback isn't very helpful and it doesn't clearly show the origin of the problem. I spent quiet some time to figure it out since I am usually a virtualvenv user and rarely interact with venv. Would you accept a PR that prints a more helpful message in case a subprocess.CalledProcessError is raised by this line?

**Comment by AlexWaygood** [comment]
To clarify (I've never used Debian) — are you saying some Debian builds don't include the `venv` module from the standard library?

**Comment by hamdanal** [comment]
On Debian systems (including Ubuntu) venv is unbundled from the stdlib and must be installed with `sudo apt install python3-venv` or `sudo apt install python3.x-venv`. The same thing is done with [deadsnakes](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) on Ubuntu. So I would say (almost all) debian systems don't have venv by default. I think `pyenv` does not unbundle venv, but I am not sure.

**Comment by AlexWaygood** [comment]
I see. Would it fix it if we added `virtualenv` to `requirements-tests.txt` and used that instead of the stdlib `venv`? I haven't used `virtualenv` much — can it be used as a drop-in replacement for this kind of thing?

**Comment by srittau** [comment]
I think a better error message is a good idea. Python development without python3-venv installed will be unpleasant in any case.

**Comment by hamdanal** [comment]
> Would it fix it if we added virtualenv to requirements-tests.txt and used that instead of the stdlib venv?

Yes. virtualenv would work cross platform regardless if venv exists or not.

> I haven't used virtualenv much — can it be used as a drop-in replacement for this kind of thing?

While it offers the same functionality and more, the interface is different https://virtualenv.pypa.io/en/latest/user_guide.html#programmatic-api

> I think a better error message is a good idea.

+1

> Python development without python3-venv installed will be unpleasant in any case.

Depends on your workflow. I tend to use virtualenv more. I also have python3-venv installed for python 3.10 but not for other versions and when I was working in a python3.9 environment, I got bit by the exception above. One of the conveniences offered by virtualenv is that you install it once and use it with python versions.

**Comment by AlexWaygood** [comment]
I'd happily accept a PR either improving the error message or switching to `virtualenv` -- but it looks like both @srittau and @JelleZijlstra prefer the former solution, so let's go with that :)
