### ISSUE TITLE
Introducing: `typeshed-stats`

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#9386]
Hi,

I've created a website to display various statistics and useful pieces of information on typeshed's stubs packages: https://alexwaygood.github.io/typeshed-stats/. The website auto-updates twice a day. The project was heavily inspired by @srittau's PR #7537 and @hauntsaninja's stubsabot script.

You can also generate these statistics manually by `pip install`ing `typeshed-stats`: https://pypi.org/project/typeshed-stats/. It comes with both an API you can use inside Python, and a CLI tool. _Beware_, however, that I'm iterating on the API quite quickly at the moment, so there are 0 stability guarantees when it comes to the API currently :)

The repo powering it all is https://github.com/AlexWaygood/typeshed-stats

This has basically been a hobby project over the last few weeks, but I figured others might also find it useful!

**Comment by AlexWaygood** [comment]
There's nothing actionable here, so we can close this -- unless we perhaps want to add a link to this somewhere in typeshed? Depends on if others see enough value here or not :)

**Comment by hauntsaninja** [comment]
I liked Avasam's suggestion to mention it as a tool for making contributions in https://github.com/python/typeshed/issues/4641

**Comment by AlexWaygood** [comment]
Nothing actionable here, so I'll close this now
