### ISSUE TITLE
Incorrect return type for jmespath.search()

### ISSUE THREAD

**Issue by mwgamble** [python/typeshed#9393]
After this PR last week, the return type of `jmespath.search()` is listed as an internal data structure named `_TreeNode`:

https://github.com/python/typeshed/pull/9338

However I don't think this is accurate. The return type is supposed to be `Any`, like it was before the changes in that PR. `jmespath.search()` returns a value based on the input, which could be anything at all.

**Comment by srittau** [comment]
Cc @mondeja @AlexWaygood

**Comment by mondeja** [comment]
Ups, sorry for the error, is being fixed by #9394
