### ISSUE TITLE
Adding stubs for pydantic-xml?

### ISSUE THREAD

**Issue by victorbnl** [python/typeshed#9478]
There are no typing stubs for the package `pydantic-xml` and I'm planning to create some. Should I create my own `types-pydantic-xml` package on PyPI or would you be interested in a pull requests to add those?

**Comment by AlexWaygood** [comment]
It looks like the package already has a lot of type annotations. Have you asked the maintainer whether they might consider adding a `py.typed` file? If they did, you'd be able to use the inline types directly, which would be preferable to having stubs for the package :)

**Comment by AlexWaygood** [comment]
If the maintainer is unwilling to add a `py.typed` file for whatever reason, then I think it's very likely we'd accept a PR adding stubs to typeshed! But better to ask first.

**Comment by victorbnl** [comment]
Indeed, I'm going to ask the maintainer and see if they answer
