### ISSUE TITLE
Change `ignore_missing_stub` default to `false`?

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#9538]
I've been wondering about this.

Possible reasons:
1. More and more stubs are "stubtest" complete (not counting pyright and mypy)
	1.1. It should be relatively easy to "minimally complete" missing ones using stugben. Especially after the reduction of stubtest false-positives by https://github.com/python/mypy/pull/14270
	1.2. Eventually most if not all stubs will have `ignore_missing_stub = false`, which could be the only entry under `[tool.stubtest]`
2. It's easier to search for `ignore_missing_stub = true` than to search for a missing line.
3. `None` would mean `False` in the metadata parser. (feels more intuitive?)
4. #8955
    > I don't want to encourage new incomplete stubs
    
Cons:
- Have to update the metadata parser
- A commit that flips (adds/removes) the value in all metadata.toml
- Maybe wait until there's even less (if not all) "stubtest incomplete" stubs left.

**Comment by AlexWaygood** [comment]
I agree that we should change the default here. @hauntsaninja proposed doing this a while back (can't find the reference immediately), and I opposed it then. But I think I've been proven wrong since.
