### ISSUE TITLE
Integrate requirements-stubtest.txt into METADATA.toml

### ISSUE THREAD

**Issue by srittau** [python/typeshed#9547]
Currently, stubtest requirements are defined in `@tests/requirements-stubtest.txt`, while other stubtest configuration and other dependencies are configured in `METADATA.toml`. I find this a bit confusing and think we should integrate the stubtest dependencies into the `[tool.stubtest]` section of `METADATA.toml`.

**Comment by AlexWaygood** [comment]
I agree. Maybe a `test_requirements` field in the `tool.stubtest` section?

**Comment by srittau** [comment]
Just to bikeshed: I would drop the redundant `test_` prefix.

**Comment by AlexWaygood** [comment]
> Just to bikeshed: I would drop the redundant `test_` prefix.

_Strictly_ speaking it's redundant, but I feel like you could easily get confused between the `requires` field in the top-level table and the `requires`/`requirements` field in the `tool.stubtest` table if you didn't have the prefix :)
