### ISSUE TITLE
`Mapping.get` overload has covariant type as argument

### ISSUE THREAD

**Issue by randolf-scholz** [python/typeshed#9555]
https://github.com/python/typeshed/blob/2b9f200e7e111ab714217b7846b80538e875b472/stdlib/typing.pyi#L576-L589

Shouldn't the second overload simply be

```python
@overload 
def get(self, __key: _KT, default: _T) -> _VT_co | _T: ... 
```

Why is there a covariant variable being used as a function input? Is there any case where this simplified signature would be incompatible with the current signature?

**Comment by srittau** [comment]
This was previously tried in #2810, but then reverted in #2817, which has extensive discussion about this.

**Comment by randolf-scholz** [comment]
@srittau Looking at the example given in the PR

```
m: Mapping[str, List[str]]
x = m.get('x', [])
reveal_type(x)  # list[<nothing>] instead of list[str]
```

it seems that the issue is that there is a reasonable expectation that for `Mapping.get`, if `T` is a subtype of `V_co`, then the return value should be interpreted as `V_co`. It seems that to do this correctly, some kind of conditional `@overload` would be required

```python
@overload  # if _T ≤ _VT_co
def get(self, __key: _KT, default: _T) -> _VT_co: ... 
@overload  # else
def get(self, __key: _KT, default: _T) -> _T: ... 
```

**Comment by srittau** [comment]
@randolf-scholz If you want to write an explanatory PR that would certainly be welcome. We have a much better test infrastructure nowadays that allows us to judge the impact of any changes.

**Comment by randolf-scholz** [comment]
@srittau I think with the current typing system it's unfortunately impossible. One would need something like [TypeScript's Conditional Types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-8.html#conditional-types)
