### ISSUE TITLE
pickle.load parameter type expects '_ReadableFileobj' type

### ISSUE THREAD

**Issue by tamruta** [python/typeshed#9573]
I'm having sending a file as a parameter to ``pickle.load``. I get this error
```console
conver_pickle.py:3: error: Argument 1 to "load" has incompatible type "TextIOWrapper"; expected "_ReadableFileobj"  [arg-type]
```
While the code is :
```python
    import typing
    with open(pickle_filename, 'r') as file:
        data = pickle.load(file)    # type: typing.TextIO
```
I'm not sure what is going on and why Readable FileObj doesn't cover TextIOWrapper or if I need to add a different hint

**Comment by JelleZijlstra** [comment]
This is correct: `pickle.load` wants a file opened in binary mode, and you're passing a text file. Your code will fail at runtime. Ideally the error message would be better but I don't think that's something we can fix in typeshed.

**Comment by tamruta** [comment]
Thank you for clarifying that!

**Comment by Akuli** [comment]
Presumably we could rename `_ReadableFileobj` to something like `_ReadableBytesFile`.
