### ISSUE TITLE
Several errors in overloaded functions in the stdlib

### ISSUE THREAD

**Issue by AlexWaygood** [python/typeshed#9608]
Attempting to add defaults to overloaded functions in #9606 highlighted many instances where we have incorrect overloads in the stdlib. An example is this overload in `_bisect.pyi`:

https://github.com/python/typeshed/blob/808a431a57e7efb2ec8afa97840c368e760d2e11/stdlib/_bisect.pyi#L13-L21

This overload incorrectly marks the `key` parameter as having a default value. But this has several issues:
- If no value is provided for this parameter by the user, we actually want the type checker to pick the _first_ overload (not this overload, which is the second overload). Specifying a default value for this parameter in this overload is confusing.
- If the type checker _did_ select this overload, the `_T` TypeVar would go unsolved if no value was specified for the `key` parameter.
- If we try to add the default value for this parameter (`None`), mypy will (correctly) complain that we're using an implicit optional type for the type annotation.

There are several issues like this in our stdlib stubs that should be fixed (see https://github.com/python/typeshed/pull/9606/commits/b39305ee691e2789e5e6ba4e525b2e619f0d33b4 for a summary of the problematic functions — this is the commit in #9606 in which I reverted all the defaults `stubdefaulter` had added that caused mypy to emit errors).

**Comment by AlexWaygood** [comment]
There are several functions in `asyncio.events` and `asyncio.base_events` where `stubdefaulter` added default values that I had to revert (see https://github.com/python/typeshed/commit/b39305ee691e2789e5e6ba4e525b2e619f0d33b4). I can see that the overloads are incorrect, but I'm not sure what the correct fix is. I'd appreciate it if somebody who knows their `asyncio` better than I do could take a look.

**Comment by srittau** [comment]
I'm not sure anyone understands asyncio ...

**Comment by AlexWaygood** [comment]
Other than the asyncio ones, all the fixable ones that I know about have now been fixed (though we'll probably discover a few more once https://github.com/JelleZijlstra/stubdefaulter/issues/35 is implemented...).

I'll open a followup issue for the asyncio ones. Many thanks, everybody, for the speedy reviews on my PRs!
