### ISSUE TITLE
Stubs for multiple versions of the same library

### ISSUE THREAD

**Issue by pkch** [python/typeshed#961]
Is it worth allowing stubs to be present for multiple versions of the same python standard library?

Currently, only one stub per library is allowed, and versioning is achieved with statements like `if sys.version_info >= (3, 4)`. As the number of versions grows, these if statements could become somewhat messy, especially as methods / attributes can be added and removed over time.

At first glance, it seems that it's relatively easy to allow multiple stubs per library. For example, stubs from all version folders could be parsed, in ascending order of version number, with global objects from them placed in the same namespace.

To avoid code duplication when an existing class is slightly modified, one could use a decorator to update a class, kinda like this:

```
# updates old_cls with new_cls definition
def incremental(old_cls):
    def update_class(new_cls):
        for attr in dir(old_cls):
            if not hasattr(new_cls, attr):
                setattr(new_cls, attr, getattr(old_cls, attr))
        return new_cls
    return update_class
```

In 3.4/a.pyi
```
class A:
    def f(self, x: int) -> int:
        return x + 1
    def g(self, x: int) -> str:
        return 'a'

class B:
    def h() -> None:
        pass
```

In 3.5/a.pyi:
```
# A.f changed signature in version 3.5
@incremental(A)
class A:
    def f(self, x: str) -> str:
        return x.strip()

# B is removed in version 3.5
del B

# C is added in version 3.5
class C:
    def k(self) -> None:
        pass
```

**Comment by gvanrossum** [comment]
I don't think that would be an improvement; I'd rather have everything
together in one file than spread out.

**Comment by pkch** [comment]
I don't have a strong argument in favor, so since the current approach works fine, I'm closing it.
