### ISSUE TITLE
Include LICENSE file in pypi tars

### ISSUE THREAD

**Issue by sanjayankur31** [python/typeshed#9621]
Hi there,

Would it be possible to please include the license file in the generated pypi tars? It'll make it a tad easier for downstream distributions to package the different type packages. (At the moment we fetch and include the license as an additional source)

Cheers,

**Comment by srittau** [comment]
I never noticed that we don't ship the LICENSE file. But we should indeed definitely do so. Moving to the stub_upload repository.
