### ISSUE TITLE
Encountered error: Library stubs not installed for "pytz"  after installing types-pytz

### ISSUE THREAD

**Issue by codebrotherone** [python/typeshed#9638]
Hello, 

I am unsure if this is a user problem (ie. me) but I am hoping I can get some help. 

I'm running python3.9 and trying to get mypy to check the pytz import. 

However, after installing `types-pytz` as well as running `mypy --install-types` I can't get it to work. The same errors that result are:

```
src/lambda.py:12: error: Library stubs not installed for "pytz"  [import]
src/lambda.py:12: note: Hint: "python3 -m pip install types-pytz"
src/lambda.py:12: note: (or run "mypy --install-types" to install all missing stub packages)
src/lambda.py:12: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
```

Confirming that I have it installed below via pip list

```
Package           Version
----------------- -----------
black             22.12.0
boto3-stubs       1.26.60
botocore-stubs    1.29.60
cfgv              3.3.1
click             8.1.3
distlib           0.3.6
filelock          3.9.0
flake8            6.0.0
identify          2.5.13
isort             5.12.0
mccabe            0.7.0
mypy              0.991
mypy-extensions   0.4.3
nodeenv           1.7.0
pathspec          0.11.0
pip               22.3.1
platformdirs      2.6.2
pre-commit        2.21.0
pycodestyle       2.10.0
pyflakes          3.0.1
pytz              2022.7.1
PyYAML            6.0
setuptools        65.6.3
tomli             2.0.1
types-awscrt      0.16.4
types-pytz        2022.7.1.0
types-s3transfer  0.6.0.post5
types-urllib3     1.26.25.4
typing_extensions 4.4.0
virtualenv        20.17.1
wheel             0.38.4
```
Per the documentation [here](https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker) I have exhausted all steps, and am confused as to why I can't get this import to pass mypy. 

Additionally it seems as if [this SO post](https://stackoverflow.com/questions/74177931/mypy-not-finding-stubs-already-installed) also has the same issue I am facing. 

Any help would be much appreciated! Thanks in advance!

**Comment by AlexWaygood** [comment]
To try to see if I could reproduce this issue, I ran the following steps:

```bash
> mdkir pytz-repro
> cd pytz-repro
pytz-repro> python -m venv env
pytz-repro> env\scripts\activate
(env) pytz-repro> mkdir src
(env) pytz-repro> pip install mypy types-pytz
```

I then created a file `src/lambda.py` with just `import pytz` in it.

Running `mypy src` after these steps, the output was:

```
Success: no issues found in 1 source file
```

**Comment by AlexWaygood** [comment]
Unless another maintainer is able to reproduce this, or you're able to give more detailed steps to reproduce, I'm afraid there's not much we can do to help here :(

**Comment by hauntsaninja** [comment]
Consider using `python -m mypy ...` to type check and using `python -m pip install types-pytz` to install stub packages. This can help ensure that mypy and the stub packages end up installed in the same environment and can find each other.

I'm closing this now, but please feel free to post if you can't get it working :-)

**Comment by NinjaMasoud** [comment]
Had the same situation. I put # type ignore. I am 100% sure I am using the right environment with types-pytz installed.
