### ISSUE TITLE
Add missing stripe.checkout.Session.expire stub

### ISSUE THREAD

**Issue by nidico** [python/typeshed#9693]
Stripe [2.62.0](https://github.com/stripe/stripe-python/blob/master/CHANGELOG.md#2620---2021-11-11) introduced `stripe.checkout.Session.expire`.

This function is missing in the typeshed stubs.

**Comment by AlexWaygood** [comment]
PR welcome! Note though that our stubs are currently tested against v3.5 of `stripe`, so if you try to add any features to the stub that were introduced in a later version, the tests will fail.

**Comment by nidico** [comment]
Fix released in [types-stripe 3.5.2.8](https://pypi.org/project/types-stripe/3.5.2.8/#history).

Works fine, thanks!
