### ISSUE TITLE
improve typing of datetime with more detailed return types

### ISSUE THREAD

**Issue by Joshix-1** [python/typeshed#9705]
date.month should be typed as Literal[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
date.day should be typed as only 1 to 31
datetime.minute and datetime.hour should both be limited to 0 to 59

an so on. Same things for timedelta, time and ...

On https://docs.python.org/3/library/typing.html#typing.Annotated there is `Annotated[int, ValueRange(-10, 5)]` maybe something like that could be used.

the use-case: I want to have a function that converts month to string representation and the method should only allow 1 to 12 as argument. That won't type-check when date.month returns int

**Comment by JukkaL** [comment]
Literals types aren't supposed to be used for annotating integer ranges. Type checkers aren't expected to support any arithmetic on literal types. Using `Annotated` would be better. We'd need some standardized way to do this, which we don't have at the moment, as far as I know.

**Comment by srittau** [comment]
Built-in range types (python/typing#1304) would help here, but I don't think anyone is currently working on that.

**Comment by AlexWaygood** [comment]
Closing as per @JukkaL's rationale. You might be interested in https://github.com/annotated-types/annotated-types, @Joshix-1
