### ISSUE TITLE
Signature for weakref __new__ incorrect?

### ISSUE THREAD

**Issue by alicederyn** [python/typeshed#9712]
The signature for `weakref.ReferenceType.__new__` seems to be saying the arguments can be named:

https://github.com/python/typeshed/blob/52cf716831ea11c08741db5f07ed740b3c9714c2/stdlib/_weakref.pyi#L23

If I try doing the following:

```python
from weakref import ref

class Foo:
  pass

def callback(_):
  print("Deleted")

x = Foo()
y = ref(x, callback=callback)
```

pyright and mypy both seem happy with this, but in both Python 3.9 and 3.11 I get:

```text
TypeError: ref() takes no keyword arguments
```

Should the parameters be renamed to `__o` and `__callback` to indicate they are positional-only?

**Comment by Akuli** [comment]
Yes, they should be named `__o` and `__callback`. I looked at the C code, and it uses `PyArg_UnpackTuple` whose [documentation](https://docs.python.org/3/c-api/arg.html#c.PyArg_UnpackTuple) mentions this exact thing. PR welcome!

While you're at it, you could change the `= ...` to `= None`. In the C code, passing in `None` for the callback is handled the same as not giving a callback.
