### ISSUE TITLE
cffi: FFI.string invalid signature

### ISSUE THREAD

**Issue by senyai** [python/typeshed#9735]
https://github.com/python/typeshed/blob/140bba3425229a69cf4d5ccf7f5348ff85f66c16/stubs/cffi/cffi/api.pyi#L42

I know that `maxlen` agument [is optional](https://cffi.readthedocs.io/en/latest/ref.html#ffi-string-ffi-unpack).

**Comment by senyai** [comment]
After installing `python -m pip install types-cffi --user` (1.15.1.15) I got this file structure in site-packages:
```types_cffi-1.15.1.5.dist-info/RECORD
types_cffi-1.15.1.5.dist-info/INSTALLER
types_cffi-1.15.1.5.dist-info/WHEEL
types_cffi-1.15.1.5.dist-info/METADATA
types_cffi-1.15.1.5.dist-info/top_level.txt
types_cffi-1.15.1.5.dist-info/REQUESTED
_cffi_backend-stubs/__init__.pyi
_cffi_backend-stubs/METADATA.toml
cffi-stubs/recompiler.pyi
cffi-stubs/error.pyi
cffi-stubs/__init__.pyi
cffi-stubs/lock.pyi
cffi-stubs/ffiplatform.pyi
cffi-stubs/vengine_gen.pyi
cffi-stubs/model.pyi
cffi-stubs/cparser.pyi
cffi-stubs/api.pyi
cffi-stubs/commontypes.pyi
cffi-stubs/cffi_opcode.pyi
cffi-stubs/backend_ctypes.pyi
cffi-stubs/setuptools_ext.pyi
cffi-stubs/vengine_cpy.pyi
cffi-stubs/verifier.pyi
cffi-stubs/pkgconfig.pyi
cffi-stubs/METADATA.toml
```

where `cffi-stubs/api.pyi` has the right signature and `_cffi_backend-stubs/__init__.pyi` has the wrong one: `def string(self, cdata: CData, maxlen: int) -> bytes | str: ...` What is going on?

**Comment by srittau** [comment]
This looks to be a bug in `stubs/cffi/_cffi_backend.pyi`. PR welcome!
