### ISSUE TITLE
Support TypeGuard on `builtins.all` for type narrowing

### ISSUE THREAD

**Issue by sterliakov** [python/typeshed#9749]
With the following definition, one of `all` builtin use cases would be supported by typecheckers automatically:

```python
from collections.abc import Iterable, Sequence
from typing import Literal, Protocol, TypeGuard, TypeVar

_T = TypeVar('_T')

def all(__iterable: Iterable[_T | None]) -> TypeGuard[Iterable[_T]]:
    return builtins.all(__iterable)
```

That means, `all` serves as a TypeGuard for an iterable of optional types to iterable of non-optional types. Moreover, this can be expanded to any user-defined falsey types:

```python
from collections.abc import Iterable, Sequence
from typing import Literal, Protocol, TypeGuard, TypeVar

_T = TypeVar('_T')

class Falsey(Protocol):
    def __bool__(self) -> Literal[False]: ...

def all(__iterable: Iterable[_T | Falsey | None]) -> TypeGuard[Iterable[_T]]:
    return builtins.all(__iterable)
```

This was asked [on SO](https://stackoverflow.com/questions/75493271/why-isnt-all-builtin-defined-as-typeguard) by me.

Are there any drawbacks of replacing current definition (`def all(__iterable: Iterable[object]) -> bool`) with some of mentioned above? I'm ready to make a PR for this.

**Comment by sterliakov** [comment]
I see the problem, this is more about TypeGuard definition. It's upcasting, so this may lead to much more serious problems (e.g. `list[str]` will be destroyed to `Iterable[str]`, when narrowed by such `all` call). Is there something that can be done with this regard?

**Comment by AlexWaygood** [comment]
> It's upcasting, so this may lead to much more serious problems (e.g. `list[str]` will be destroyed to `Iterable[str]`, when narrowed by such `all` call). Is there something that can be done with this regard?

Yes, this is an unfortunate aspect of the way `TypeGuard` has been implemented in mypy and pyright (I don't know how pyre and pytype handle `TypeGuard`). It would be nice to avoid the upcast in cases where the type of the input variable is already known to be a subtype of `T` for a function that returns `TypeGuard[T]`.

I don't know enough about how `TypeGuard` is implemented in type checkers to comment on how difficult that might be to implement. I'd suggest starting a conversation in an issue at https://github.com/python/typing if you'd like to discuss this behavior with authors of type checkers.

**Comment by sterliakov** [comment]
This looks like we need higher-kind types for this, similar to that implemented with plugin in https://github.com/dry-python/returns. Since it's a loong way to go (there are some discussion about HKT, but no real steps towards it), I'd close this for now.
