### ISSUE TITLE
dir argument to TemporaryDir, mktemp, mkstemp, mkdtemp should be Optional[str] instead of str

### ISSUE THREAD

**Issue by gkoller** [python/typeshed#975]
`TemporaryDir`, `mktemp`, `mkstemp`, `mkdtemp` have an optional `dir` argument. However in https://github.com/python/typeshed/blob/master/stdlib/3/tempfile.pyi the type annotation is specified to be `str` instead of `Optional[str]`

**Comment by gvanrossum** [comment]
The presence of a default placeholder (`= ...`) indicates that the argument is optional. Are you saying that it ought to be allowed to pass `dir=None` explicitly? (If so, indeed their types should be changed to `Optional[str]` and you can submit a PR to fix them.)

**Comment by gkoller** [comment]
> Are you saying that it ought to be allowed to pass dir=None explicitly?

Yes I am. I'm creating a `TemporaryDirectory` with arguments that it got from a function it is used in:

```python
tmp_dir = tempfile.TemporaryDirectory(prefix=prefix, dir=tmp.as_posix() if tmp else None)
``` 
`tmp` (a `Path`) is the argument from the outer function. It could be `None`.

I'll created a PR later this week. 

BTW I'm on Python 3.4. Hence the `tmp.as_posix()`. Anxiously looking forward to use 3.6 which has *PEP 519: Adding a file system path protocol* implemented.
