### ISSUE TITLE
stubsabot: find_first_release_with_py_typed() doesn't work when only the latest release has py.typed

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#9759]
https://github.com/python/typeshed/blob/da9366d0163bb65817216bba13ec4538f0a6e6c0/scripts/stubsabot.py#L173-L180

This function returns `None` if the latest release has `py.typed` and other releases don't. This is because the first `next(release_iter)` consumes the first release and essentially hides it from the rest of this function.

Broken in #9754

**Comment by AlexWaygood** [comment]
cc. @Avasam
