### ISSUE TITLE
tkinter: grid_rowconfigure and grid_columnconfigure can take a list/tuple

### ISSUE THREAD

**Issue by Akuli** [python/typeshed#9784]
This creates a row of 10 buttons that stay evenly spaced as the window is resized:

```py
import tkinter

root = tkinter.Tk()
for i in range(10):
    tkinter.Button(root, text="hi").grid(row=0, column=i)
root.grid_columnconfigure(list(range(10)), weight=1)
root.mainloop()
```

But mypy doesn't like passing a list to `grid_columnconfigure()`: `asd.py:6: error: Argument 1 to "grid_columnconfigure" of "Misc" has incompatible type "List[int]"; expected "Union[int, str]"  [arg-type]`

Also applies to `grid_rowconfigure`. The code also works if I change `list` to `tuple`, but similar to many other things in tkinter, it needs a list or tuple rather than an arbitrary sequence (so `grid_columnconfigure(range(10), ...)` doesn't work).

**Comment by HeziSadikov** [comment]
Not sure if the right place, but:

I encountered a similar issue when using tuples for the index parameter in the methods: 
1. grid_columnconfigure()  
2. grid_rowconfigure()

The code works perfectly, but type checkers raise warnings due to the current type hint (**_GridIndex: TypeAlias = int | str**).

Here's an example of a code that works but raises type warnings:
```py
import tkinter as tk

root = tk.Tk()

# warnings here
# type hint suggests the arguments should be int or str
root.grid_columnconfigure((0, 1, 2), weight=1) 
root.grid_rowconfigure((0, 1, 2), weight=1) 

for i in range(3):
    for j in range(3):
        tk.Button(root, text="Button").grid(row=i, column=j)

root.mainloop()
```
```
Argument of type \"tuple[Literal[0], Literal[1], Literal[2]]\" cannot be assigned to parameter \"index\" of type \"_GridIndex\" in function \"grid_columnconfigure\"\n  Type \"tuple[Literal[0], Literal[1], Literal[2]]\" cannot be assigned to type \"_GridIndex\"\n    \"tuple[Literal[0], Literal[1], Literal[2]]\" is incompatible with \"int\"\n    \"tuple[Literal[0], Literal[1], Literal[2]]\" is incompatible with \"str\"",
	"source": "Pylance",
	"startLineNumber": 7,
	"startColumn": 27,
	"endLineNumber": 7,
	"endColumn": 36
```
```
Argument of type \"tuple[Literal[0], Literal[1], Literal[2]]\" cannot be assigned to parameter \"index\" of type \"_GridIndex\" in function \"grid_rowconfigure\"\n  Type \"tuple[Literal[0], Literal[1], Literal[2]]\" cannot be assigned to type \"_GridIndex\"\n    \"tuple[Literal[0], Literal[1], Literal[2]]\" is incompatible with \"int\"\n    \"tuple[Literal[0], Literal[1], Literal[2]]\" is incompatible with \"str\"",
	"source": "Pylance",
	"startLineNumber": 8,
	"startColumn": 24,
	"endLineNumber": 8,
	"endColumn": 33
```

**Comment by Akuli** [comment]
You discovered the same issue as I did :) Want to make a PR to fix it?

**Comment by Akuli** [comment]
I think we should also delete the `_GridIndex` type alias and just use `str | int` everywhere (similar to #9970). This would simplify error messages.

**Comment by HeziSadikov** [comment]
> You discovered the same issue as I did :) Want to make a PR to fix it?

I would if I knew how, I'm a beginner :)

Just out of curiosity, will a change in that [line](https://github.com/python/typeshed/blob/60939b00afede13feeec3cee6f6dfe6eb2df1593/stdlib/tkinter/__init__.pyi#L182) to:
```py
_GridIndex: TypeAlias = int | str | list[int] | tuple[int]
```
break anything?

But I trust your suggestion is better than that.

**Comment by Akuli** [comment]
It would break things, because other uses of `_GridIndex` accept lists and tuples (I think I checked when creating this issue). You should instead change the definitions of `grid_rowconfigure()` and `grid_columnconfigure()`.

Also, you need `tuple[int, ...]` instead of `tuple[int]`. Without `...` it means the tuple must contain only one int, such as `(3,)`.
