### ISSUE TITLE
stubsabot: support more source comparison links and stats

### ISSUE THREAD

**Issue by Avasam** [python/typeshed#9792]
stubsabot generates lots of helpful links and stats when the project source is on github.

Could more sources be supported?
For a specific example: https://github.com/python/typeshed/pull/9644 openpyxl's source is hosted on `foss.heptapod.net` . Even if stats are limited due to some API restrictions, some more data could be shown. For example, a releases comparison link would look something like this:
https://foss.heptapod.net/openpyxl/openpyxl/-/compare/3.0.0...3.1.1?from_project_id=322

Gitlab and bitbucket would be other similar request (IF typeshed has stubs whose's stubbed package is hosted there).

**Comment by AlexWaygood** [comment]
> Could more sources be supported?

They certainly _could_, but I'm not sure it would be worth it to add the necessary logic. We have _loads_ of stubs where the runtime is hosted on GitHub, but only a few that are hosted on GitLab/foss.heptapod.net/bitbucket/whatever. There's a fair amount of logic required to produce the diff link and stats for the projects hosted on GitHub — I don't like the idea of having to replicate that for sites that have very few runtime-versions-of-stubs hosted on them. It feels like stubsabot would use that logic relatively rarely, but it might make the stubsabot code significantly more complex.

**Comment by AlexWaygood** [comment]
Looks like the consensus is with me here, so I'm closing this for now :)
