### ISSUE TITLE
Covariance of Awaitable and friends

### ISSUE THREAD

**Issue by vectro** [python/typeshed#9812]
Shouldn't `typing.Awaitable`, `asyncio.Task`, `asyncio.Future`, etc., be covariant on their respective type paremeters?

**Comment by vectro** [comment]
Looking more closely, it appears that:

- `Awaitable` was always covariant
- `Task` was made covariant in #8781
- `Future` cannot be covariant because it is mutable.

It does seem unfortunate that we cannot always convert `Future` to `Awaitable` though?

**Comment by AlexWaygood** [comment]
> Maybe at least `Task` should inherit directly from `Awaitable` rather than through `Future`?

That's not what happens at runtime, unfortunately. For a variety of reasons, it's good practice for typeshed to hew closely to runtime, rather than inventing fictional inheritance structures and method-resolution orders.

**Comment by AlexWaygood** [comment]
I'm afraid I don't really see anything further we can do to improve the situation here, but I'm happy to reconsider if you have any specific suggestions :)

**Comment by hauntsaninja** [comment]
Feel free to post example code that you wish type checked!

**Comment by vectro** [comment]
Sure, this is a sketch of what I'm trying to do:

```python
async def get_int() -> int:
    return 5


async def fun() -> None:
    awaitables: set[typing.Awaitable[int]] = set(get_int() for _ in range(10))

    while awaitables:
        finished_tasks, awaitables = await asyncio.wait(
            awaitables, return_when=asyncio.FIRST_COMPLETED
        )
        finished_results = await asyncio.gather(*finished_tasks)
        print(finished_results)
```

This results in an error on the line `finished_tasks, awaitables = await asyncio.wait(`, which is
```
error: Incompatible types in assignment (expression has type "Set[Task[int]]", variable has type "Set[Awaitable[int]]")  [assignment]
```

**Comment by JelleZijlstra** [comment]
In that case the variance of Awaitable and co wouldn't help you, since `set` is already invariant.

**Comment by hauntsaninja** [comment]
Yup, Jelle is correct. Consider using `typing.AbstractSet` instead.

**Comment by vectro** [comment]
I see. Thanks folks!
