### ISSUE TITLE
Remove stubs for Babel (not until August 2023)

### ISSUE THREAD

**Issue by DenverCoder1** [python/typeshed#9829]
[`Babel`](https://github.com/python-babel/babel) has just incorporated typeshed's stubs as inline annotations and added a `py.typed` file (see https://github.com/python-babel/babel/pull/934). These changes were released in [`v2.12.0`](https://github.com/python-babel/babel/releases/tag/v2.12.0) on Feb 28, 2023.

**Comment by akx** [comment]
2.12.1 is out now :)

**Comment by AlexWaygood** [comment]
@akx thanks so much for the hotfix release!
