### ISSUE TITLE
docopt.pyi is missing all classes from docopt.py

### ISSUE THREAD

**Issue by sodul** [python/typeshed#9833]
When installing types-docopt (any version but also up to the latest 0.6.11.2) we get mypy errors when we reference any of the classes in docopt.py such as:
```
[types-docopt==0.6.11.2](error: Module has no attribute "DocoptExit"  [attr-defined])
```

In that case we were referencing `docopt.DocoptExit`.

**Comment by srittau** [comment]
The docopt module seems to be missing quite a few items. Any PRs to improve the situation are welcome!

**Comment by AlexWaygood** [comment]
The reason why our tests haven't flagged these classes as being missing from the stub is that docopt has [a very minimal `__all__` at runtime](https://github.com/docopt/docopt/blob/20b9c4ffec71d17cee9fd963238c8ec240905b65/docopt.py#L13), and we generally only provide stubs for the public interface of a runtime package unless somebody specifically asks for other things to be included. But, as @srittau says — if you need these things, feel free to make a PR!

**Comment by sodul** [comment]
@AlexWaygood thanks for the explanation. In our case mypy is complaining in a unittest which accesses the `docopt.DocoptExit` exception. We'll just add a `# type: ignore` comment.

**Comment by sodul** [comment]
Thanks @hauntsaninja. I followed up and filed a report with the docopt project. I personally believe that exceptions that are raised to the caller code should be made public so they can be captured and handled properly so as not to force others to catch `Exception`.
