### ISSUE TITLE
Structural subtyping in typeshed stubs is not strictly correct (due to parameter names)

### ISSUE THREAD

**Issue by kmillikin** [python/typeshed#9848]
For example, I'm trying to typecheck a call to `min(1, 2)`.  The first overload is generic and ultimately we will end up checking that the argument type `int` (from `Literal[1]`) is a structural subtype of the type variable's bound `SupportsDunderLT[Any]` (or else `SupportsDunderGT[Any]`).

Substituting `Any` for the type parameter of the protocol `SupportsDunderLT` requires a method `__lt__` with signature `(__other: Any) -> bool`.  `int` has a method `__lt__` with signature `(__value: int) -> bool` which is not a consistent subtype of the signature from the protocol.

The issue is that the positional/keyword parameter name does not match.  A value `x` of type `SupportsDunderLT` might be invoked like `x.__lt__(__other=whatever)` and `int` is not prepared to accept that keyword argument.

One fix is to ensure that the positional/keyword parameter names match.

Another fix is to make these positional-only parameters in the protocols:

```python
class SupportsDunderLT(Protocol[_T_contra]):
    def __lt__(self, __other: _T_contra, /) -> bool: ...
```

My workaround is for the typechecker to check if it's performing structural subtyping (or override checking) against a type in typeshed and then to treat parameters with `__` names as implicitly positional-only.  But this is kind of warty and shouldn't be necessary.

**Comment by AlexWaygood** [comment]
> Another fix is to make these positional-only parameters in the protocols:

The parameters are already marked as being positional-only in the protocols. Prepending a parameter name with `__` is the way you mark a parameter as being positional-only on Python 3.7 (and typeshed still supports Python 3.7). This is stated in PEP 484 here: https://peps.python.org/pep-0484/#positional-only-arguments

If a type checker you are using does not understand these parameters as being marked as positional only, that's a bug in the type checker, and should be reported there.

**Comment by kmillikin** [comment]
Thanks, I've missed that in all my readings of PEP-484.

**Comment by kmillikin** [comment]
Out of curiosity, what do you think is the status of the parameter `__`.  It does begin with `__` and end with `__` so I guess it's a normal one?

**Comment by AlexWaygood** [comment]
Heh, no idea. Try it out on mypy/pyright, and see what they say, maybe?

**Comment by kmillikin** [comment]
Mypy says it's a normal parameter, pyright says it's implicitly positional-only.

(I did verify that they both get structural subtyping correct for explicitly positional-only and explicitly normal parameters so there's no bug just a different implementation decision.)
