### ISSUE TITLE
Missing Redis properties

### ISSUE THREAD

**Issue by dragonpaw** [python/typeshed#9851]
I'm totally not sure if this is the right place to ask or not, so feel free to point me elsewhere if this isn't the forum.

I'm using the redis package and notice that whlle types-redis has most of the methods, none of the properties seem to be there.

Example:
```python
import redis.client
import resis.lock

lock = redis.lock.Lock(name='foo', redis=redis.client.Redis('localhost'))

# The below isn't known by mypy, or any other properties like timeout or redis (the client)
print(lock.name) # type: ignore[attr-defined]
```

**Comment by srittau** [comment]
Indeed. Any PRs to improve the situation are welcome.

**Comment by smallSwed** [comment]
I made a PR. Not sure how to link whit this issue: https://github.com/python/typeshed/pull/9867
