### ISSUE TITLE
multiprocessing: Value / Array with lock=False are not Sized

### ISSUE THREAD

**Issue by prauscher** [python/typeshed#9898]
Hello everyone,

Consider the following code:
```py
from multiprocessing import Array
from ctypes import c_char

a = Array(c_char, 128, lock=True)
print(len(a))  # this is fine

b = Array(c_char, 128, lock=False)
print(len(b))  # this is: Argument 1 to "len" has incompatible type "c_char"; expected "Sized"
```

To my untrained eye, the issue is with https://github.com/python/typeshed/blob/main/stdlib/multiprocessing/sharedctypes.pyi#L40 returning `_CT` while https://github.com/python/typeshed/blob/main/stdlib/multiprocessing/sharedctypes.pyi#L48 returns `SynchronizedArray[Any]`

Actually, `Array` does support `__len__` even with `lock=False` and therefore is `Sized`. I'm quite sure there is a reason to return `_CT` instead for `lock=False`, but I do not know it and it probably should not have this side effect.

**Comment by srittau** [comment]
I have not experience with sharedctypes, but this looks to be to be a simple bug: `b` should return `_SomeArrayType[_CT]`, instead of  `c_char`. At runtime, the type returned identifies as `multiprocessing.sharedctypes.c_char_Array_128`, but that type doesn't exist. I would think we need to defined a type-specific array type and use that. But maybe someone with more sharedctypes experience can chime in.

**Comment by Akuli** [comment]
I think it should be `ctypes.Array[_CT]`. It would be consistent with how the `*` operator is annotated, and the `*` operator is how you usually create an array type in ctypes:

```
>>> import ctypes
>>> ctypes.c_char * 128
<class '__main__.c_char_Array_128'>
```

**Comment by prauscher** [comment]
Thanks @Akuli, i tested your suggestion by replacing `_CT` with `ctypes.Array[_CT]` in https://github.com/python/typeshed/blob/3802899a01269df575ea32a21534c5400fb9218a/stdlib/multiprocessing/context.pyi#L90 

So while this would solve the issue, I'm not sure about possible side effects...

**Comment by srittau** [comment]
You can always open an exploratory PR here. mypy_primer will test the change against quite a lot of projects, which helps us to judge the impact.

**Comment by prauscher** [comment]
I created #11576 to test this change, maybe someone can help with review there?
