### ISSUE TITLE
`datetime` supports non-`int` arguments

### ISSUE THREAD

**Issue by sobolevn** [python/typeshed#9902]
While discussing https://github.com/python/cpython/issues/102791 I've noticed that `datetime`'s objects can support non-`int` arguments:

```python
>>> import datetime
>>> class Day:
...     def __index__(self):
...          return 1  # whatever
... 
>>> datetime.datetime(year=2023, month=3, day=Day())
datetime.datetime(2023, 3, 1, 0, 0)
```

Technically it might be used with some libs/dsls like `datetime.datetime(year=Year(2023), month=Month(3), day=Day(2))`

Should we use `SupportsIndex` there?

**Comment by srittau** [comment]
I am ok with supporting it here, since the various date classes explicitly check for it. But nothing I find particularly important, unless someone explicitly asks for it.

**Comment by AlexWaygood** [comment]
The change SGTM too!

**Comment by sobolevn** [comment]
Resolved in https://github.com/python/typeshed/pull/9915
