### ISSUE TITLE
openpyxl Worksheet rows is incorrectly typed

### ISSUE THREAD

**Issue by Vegemash** [python/typeshed#9904]
Worksheet:rows is typed as `Generator[Cell, None, None]`. All it does is call `self.iter_rows()` (no args)  and thus should be typed `Generator[tuple[Cell, ...], None, None]`

**Comment by srittau** [comment]
Thanks! I added the fix to my PR #9892.

**Comment by Avasam** [comment]
@srittau Seems this issue should be closed?
