### ISSUE TITLE
logging module LogRecord `__init__` mismatch

### ISSUE THREAD

**Issue by aminalaee** [python/typeshed#9913]
According to the Python docs for the `LogRecord` in `logging` module the `msg` argument and property is a string:
https://docs.python.org/3/library/logging.html#logging.LogRecord

In the typeshed, the attribute is set to a `str`:
https://github.com/python/typeshed/blob/dd2818a41db6cd31e4680abf5e1362a7e5bfb5a6/stdlib/logging/__init__.pyi#L392

But the msg input argument is set to `object`:
https://github.com/python/typeshed/blob/dd2818a41db6cd31e4680abf5e1362a7e5bfb5a6/stdlib/logging/__init__.pyi#L407

And looking at the source the argument is not changed at all:
https://github.com/python/cpython/blob/7f760c2fca3dc5f46a518f5b7622783039bc8b7b/Lib/logging/__init__.py#L305

Unless this is for a backwards-compatible version, I guess this is a mismatch.

**Comment by Akuli** [comment]
I think we should just use `str` everywhere. If you are passing a non-string, and it isn't converted to a string anywhere in `logging`, it may fail when some completely unrelated code handles the log records elsewhere. IMO this is exactly what type checking is supposed to avoid.

**Comment by aminalaee** [comment]
But in that case type checking is actually stricter than the implementation, and causes mismatch between typeshed and python docs and implementation.
