### ISSUE TITLE
Add links to Stdlib Documentation and C Implementation

### ISSUE THREAD

**Issue by antoniomenteguiaga** [python/typeshed#9974]
I understand that it's difficult for the stubs to properly document the standard library due to being implemented in C. 

I would find it useful if the stub had some comments that showed me where I can read the C implementation and where I can read the official documentation. Normally I have to search for this myself, and it tends to take a lot of effort and guess work.

For example, right now if you go to `math.fsum` on Python >=3.8 you see this.

```python
def fsum(__seq: Iterable[_SupportsFloatOrIndex]) -> float: ...
```

This proposed change would show you something like this instead

```python
# https://docs.python.org/3.8/library/math.html#math.fsum
# https://github.com/python/cpython/blob/main/Modules/mathmodule.c#L1385
def fsum(__seq: Iterable[_SupportsFloatOrIndex]) -> float: ...
```

The usual way I find myself looking at a stub is through VSCode's jump to definition feature, so this happens frequently when I'm interested in the implementation of something implemented in c. That type of use-case is where I think this would be the most frequently used.

**Comment by AlexWaygood** [comment]
> I would find it useful if when clicking on a standard function, and being brought to the python stubs

What do you mean when you say "When clicking on a function"? Is this in a specific IDE?

**Comment by antoniomenteguiaga** [comment]
Yeah, sorry. I was talking about VSCode when typing that but I meant any feature that can take you to the definition of something through some kind of shortcut.

**Comment by AlexWaygood** [comment]
For the stdlib, I feel like Pylance could  probably automatically link straight to the documentation for stdlib functions and classes using the https://docs.python.org/3/objects.inv inventory file that's published with the Python docs. That could be a good feature request to Pylance.

The same can't be said with regards to the implementation of an arbitrary function or class in the stdlib. I suppose we _could_ add comments linking to the implementation, but I can't say I'm thrilled about the idea of adding thousands of comments like that across our stubs for the stdlib — it feels to me like they'd be pretty noisy, and pretty tangential to typeshed's core purpose. (Aside from anything else, the comments could easily go out of date without us noticing.) Personally, I've never found it _too_ difficult to find the implementation of a function or class just by browsing the CPython repo.

**Comment by JelleZijlstra** [comment]
Manually adding comments like this to typeshed is going to be unmaintainable and it's outside the scope of this project. However, it shouldn't be difficult to write an external tool that does what you want automatically by scanning the source code and connecting it to the stubs. You're welcome to write such a tool.
