### ISSUE TITLE
[redis] Incorrect type in ConnectionPool

### ISSUE THREAD

**Issue by Rafiot** [python/typeshed#9979]
If I'm not mistaken, the type for `connection_class` should be `AbstractConnection` instead of `Connection` https://github.com/python/typeshed/blob/ed915c5cde48329e3d1e597e60c4baee27b7854a/stubs/redis/redis/connection.pyi#L257

It is causing an error for with `UnixDomainSocketConnection` (which is an `AbstractConnection` but not a `Connection`).

**Comment by srittau** [comment]
I haven't looked into this, but this sounds plausible. PR welcome!
