### ISSUE TITLE
[redis] CredentialProvider types missing from __init__.pyi

### ISSUE THREAD

**Issue by nint8835** [python/typeshed#9980]
In Redis' `__init__.py`, `CredentialProvider` and `UsernamePasswordCredentialProvider` are imported and re-exported (see [here](https://github.com/redis/redis-py/blob/master/redis/__init__.py#L69-L71)).

However, in the type stubs these types are missing from the `__init__.pyi` (see [here](https://github.com/python/typeshed/blob/main/stubs/redis/redis/__init__.pyi#L12-L13)).

The types are defined in `credentials.py`, so if you use `redis.credentials.CredentialProvider` in your code it works fine, but if you try to use `redis.CredentialProvider` directly, like in the [docs](https://redis.readthedocs.io/en/stable/examples/connection_examples.html#), you get the error `error: Name "redis.CredentialProvider" is not defined`

**Comment by srittau** [comment]
PR welcome!
